var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",h=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,r,u;
if(ea){var fs=require("fs"),ha=require("path");q=l?ha.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};u=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};r=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,k)=>{e?c(e):b(d?k.buffer:k)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&
(module.exports=g);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof ia||a.context instanceof ia))throw a;});h=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&
(u=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),r=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};g.print||console.log.bind(console);var v=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(h=g.quit);
var w;g.wasmBinary&&(w=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&ja("no native wasm support detected");var ka,y,la=!1,ma,z,na,oa,A,pa,B,C;function qa(){var a=ka.buffer;g.HEAP8=ma=new Int8Array(a);g.HEAP16=na=new Int16Array(a);g.HEAP32=A=new Int32Array(a);g.HEAPU8=z=new Uint8Array(a);g.HEAPU16=oa=new Uint16Array(a);g.HEAPU32=pa=new Uint32Array(a);g.HEAPF32=B=new Float32Array(a);g.HEAPF64=C=new Float64Array(a)}var ra,sa=[],ta=[],ua=[],va=[],wa=[];
function xa(){var a=g.preRun.shift();sa.unshift(a)}var D=0,ya=null,E=null;function ja(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";v(a);la=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function za(a){return a.startsWith("data:application/octet-stream;base64,")}var F;F="arraytex-sapp.wasm";if(!za(F)){var Aa=F;F=g.locateFile?g.locateFile(Aa,q):q+Aa}
function Ba(a){if(a==F&&w)return new Uint8Array(w);if(u)return u(a);throw"both async and sync fetching of the wasm failed";}function Ca(a){if(!w&&(da||l)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ba(a));if(r)return new Promise((b,c)=>{r(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ba(a))}
function Da(a,b,c){return Ca(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{v("failed to asynchronously prepare wasm: "+d);ja(d)})}
function Ea(a,b){var c=F;w||"function"!=typeof WebAssembly.instantiateStreaming||za(c)||c.startsWith("file://")||ea||"function"!=typeof fetch?Da(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){v("wasm streaming compile failed: "+e);v("falling back to ArrayBuffer instantiation");return Da(c,a,b)}))}function ia(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Fa=a=>{for(;0<a.length;)a.shift()(g)},Ia=a=>{var b=Ga();a();Ha(b)},Ja=0;function Ka(){for(var a=G.length-1;0<=a;--a)La(a);G=[];Ma=[]}var Ma=[];function Na(){if(navigator.userActivation?navigator.userActivation.isActive:Ja&&Oa.Ub)for(var a=0;a<Ma.length;++a){var b=Ma[a];Ma.splice(a,1);--a;b.Gc.apply(null,b.wc)}}var G=[];function La(a){var b=G[a];b.target.removeEventListener(b.Nb,b.sc,b.Ob);G.splice(a,1)}
function H(a){function b(d){++Ja;Oa=a;Na();a.Qb(d);Na();--Ja}if(!a.target)return-4;if(a.Pb)a.sc=b,a.target.addEventListener(a.Nb,b,a.Ob),G.push(a),Pa||(va.push(Ka),Pa=!0);else for(var c=0;c<G.length;++c)G[c].target==a.target&&G[c].Nb==a.Nb&&La(c--);return 0}function Qa(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Pa,Oa,Ra,Sa,Ta,Ua,Va,Wa,Xa,Ya="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,I=(a,b)=>{var c=z,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&Ya)return Ya.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var k=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|k<<6|f:(e&7)<<18|k<<12|f<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Za=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];function J(a){a=2<a?a?I(a):"":a;return Za[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function $a(a){return 0>Za.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
var ab=[],K=a=>{var b=ab[a];b||(a>=ab.length&&(ab.length=a+1),ab[a]=b=ra.get(a));return b},L=(a,b,c)=>{var d=z;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);if(55296<=f&&57343>=f){var m=a.charCodeAt(++k);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=
0;return b-e};function bb(a,b,c,d,e,k){Ra||(Ra=M(256));a={target:J(a),Nb:k,Pb:d,Qb:function(f=event){var m=f.target.id?f.target.id:"",n=Ra;L(Qa(f.target),n+0,128);L(m,n+128,128);K(d)(e,n,b)&&f.preventDefault()},Ob:c};return H(a)}
function cb(a,b,c,d,e,k){Sa||(Sa=M(176));a={target:J(a),Ub:!0,Nb:k,Pb:d,Qb:function(f){var m=Sa;C[m>>3]=f.timeStamp;var n=m>>2;A[n+2]=f.location;A[n+3]=f.ctrlKey;A[n+4]=f.shiftKey;A[n+5]=f.altKey;A[n+6]=f.metaKey;A[n+7]=f.repeat;A[n+8]=f.charCode;A[n+9]=f.keyCode;A[n+10]=f.which;L(f.key||"",m+44,32);L(f.code||"",m+76,32);L(f.char||"",m+108,32);L(f.locale||"",m+140,32);K(d)(e,m,b)&&f.preventDefault()},Ob:c};return H(a)}
function db(a,b,c){C[a>>3]=b.timeStamp;a>>=2;A[a+2]=b.screenX;A[a+3]=b.screenY;A[a+4]=b.clientX;A[a+5]=b.clientY;A[a+6]=b.ctrlKey;A[a+7]=b.shiftKey;A[a+8]=b.altKey;A[a+9]=b.metaKey;na[2*a+20]=b.button;na[2*a+21]=b.buttons;A[a+11]=b.movementX;A[a+12]=b.movementY;c=$a(c);A[a+13]=b.clientX-c.left;A[a+14]=b.clientY-c.top}
function N(a,b,c,d,e,k){Ta||(Ta=M(72));a=J(a);return H({target:a,Ub:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Nb:k,Pb:d,Qb:function(f=event){db(Ta,f,a);K(d)(e,Ta,b)&&f.preventDefault()},Ob:c})}function eb(a,b,c,d,e){Ua||(Ua=M(260));return H({target:a,Nb:e,Pb:d,Qb:function(k=event){var f=Ua,m=document.pointerLockElement||document.Rb||document.bc||document.ac;A[f>>2]=!!m;var n=m&&m.id?m.id:"";L(Qa(m),f+4,128);L(n,f+132,128);K(d)(20,f,b)&&k.preventDefault()},Ob:c})}
function fb(a,b,c,d,e){return H({target:a,Nb:e,Pb:d,Qb:function(k=event){K(d)(38,0,b)&&k.preventDefault()},Ob:c})}
function gb(a,b,c,d){Va||(Va=M(36));a=J(a);return H({target:a,Nb:"resize",Pb:d,Qb:function(e=event){if(e.target==a){var k=document.body;if(k){var f=Va;A[f>>2]=e.detail;A[f+4>>2]=k.clientWidth;A[f+8>>2]=k.clientHeight;A[f+12>>2]=innerWidth;A[f+16>>2]=innerHeight;A[f+20>>2]=outerWidth;A[f+24>>2]=outerHeight;A[f+28>>2]=pageXOffset;A[f+32>>2]=pageYOffset;K(d)(10,f,b)&&e.preventDefault()}}},Ob:c})}
function hb(a,b,c,d,e,k){Wa||(Wa=M(1696));a=J(a);return H({target:a,Ub:"touchstart"==k||"touchend"==k,Nb:k,Pb:d,Qb:function(f){for(var m,n={},p=f.touches,x=0;x<p.length;++x)m=p[x],m.fc=m.ic=0,n[m.identifier]=m;for(x=0;x<f.changedTouches.length;++x)m=f.changedTouches[x],m.fc=1,n[m.identifier]=m;for(x=0;x<f.targetTouches.length;++x)n[f.targetTouches[x].identifier].ic=1;p=Wa;C[p>>3]=f.timeStamp;var t=p>>2;A[t+3]=f.ctrlKey;A[t+4]=f.shiftKey;A[t+5]=f.altKey;A[t+6]=f.metaKey;t+=7;var O=$a(a),V=0;for(x in n)if(m=
n[x],A[t]=m.identifier,A[t+1]=m.screenX,A[t+2]=m.screenY,A[t+3]=m.clientX,A[t+4]=m.clientY,A[t+5]=m.pageX,A[t+6]=m.pageY,A[t+7]=m.fc,A[t+8]=m.ic,A[t+9]=m.clientX-O.left,A[t+10]=m.clientY-O.top,t+=13,31<++V)break;A[p+8>>2]=V;K(d)(e,p,b)&&f.preventDefault()},Ob:c})}
function ib(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,k){b.drawArraysInstancedANGLE(c,d,e,k)},a.drawElementsInstanced=function(c,d,e,k,f){b.drawElementsInstancedANGLE(c,d,e,k,f)})}
function jb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function kb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function lb(a){a.yc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function mb(a){a.zc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function nb(a){a.Bc=a.getExtension("WEBGL_multi_draw")}var ob=1,pb=[],P=[],qb=[],rb=[],sb=[],Q=[],tb=[],ub=[],R=[],vb={},wb=4;function S(a){xb||(xb=a)}function yb(a){for(var b=ob++,c=a.length;c<b;c++)a[c]=null;return b}
function zb(a,b){a.Rb||(a.Rb=a.getContext,a.getContext=function(d,e){e=a.Rb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.hc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Ab(c,b):0}function Ab(a,b){var c=yb(ub),d={handle:c,attributes:b,version:b.hc,Zb:a};a.canvas&&(a.canvas.vc=d);ub[c]=d;("undefined"==typeof b.ec||b.ec)&&Bb(d);return c}
function Bb(a){a||(a=T);if(!a.uc){a.uc=!0;var b=a.Zb;ib(b);jb(b);kb(b);lb(b);mb(b);2<=a.version&&(b.dc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.dc)b.dc=b.getExtension("EXT_disjoint_timer_query");nb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var xb,T;function Cb(a,b,c,d,e,k){a={target:J(a),Nb:k,Pb:d,Qb:(f=event)=>{K(d)(e,0,b)&&f.preventDefault()},Ob:c};H(a)}
function Db(a,b,c,d){Xa||(Xa=M(104));return H({target:a,Ub:!0,Nb:"wheel",Pb:d,Qb:function(e=event){var k=Xa;db(k,e,a);C[k+72>>3]=e.deltaX;C[k+80>>3]=e.deltaY;C[k+88>>3]=e.deltaZ;A[k+96>>2]=e.deltaMode;K(d)(9,k,b)&&e.preventDefault()},Ob:c})}var Eb=["default","low-power","high-performance"];function Fb(a,b,c,d){for(var e=0;e<a;e++){var k=U[c](),f=k&&yb(d);k?(k.name=f,d[f]=k):S(1282);A[b+4*e>>2]=f}}
function Gb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=U.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>T.version){S(1282);return}c=2*(U.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>T.version){S(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=U.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":S(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:S(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)A[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){S(1280);v("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:S(1280);v("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}A[b>>2]=c}else S(1281)}
var Hb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b};function Ib(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}var Jb=[];function Kb(a){a-=5120;return 0==a?ma:1==a?z:2==a?na:4==a?A:6==a?B:5==a||28922==a||28520==a||30779==a||30782==a?pa:oa}function W(a){var b=U.rc;if(b){var c=b.Tb[a];"number"==typeof c&&(b.Tb[a]=c=U.getUniformLocation(b,b.pc[a]+(0<c?"["+c+"]":"")));return c}S(1282)}
for(var X=[],Y=[],Lb=a=>{if(!noExitRuntime){if(g.onExit)g.onExit(a);la=!0}h(a,new ia(a))},Nb=a=>{var b=Hb(a)+1,c=Mb(b);L(a,c,b);return c},U,Z=0;32>Z;++Z)Jb.push(Array(Z));var Ob=new Float32Array(288);for(Z=0;288>Z;++Z)X[Z]=Ob.subarray(0,Z+1);var Pb=new Int32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Pb.subarray(0,Z+1);
var Wb={l:()=>{ja("")},ca:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},da:function(a,b,c){a=J(a);if(!a)return-4;a=$a(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},Va:(a,b,c)=>z.copyWithin(a,b,b+c),Ta:function(a,b){function c(d){K(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Wa:a=>{var b=z.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,
d+(65536-d%65536)%65536)-ka.buffer.byteLength+65535>>>16;try{ka.grow(e);qa();var k=1;break a}catch(f){}k=void 0}if(k)return!0}return!1},M:function(a,b,c,d){return bb(a,b,c,d,12,"blur")},ba:function(a,b,c){a=J(a);if(!a)return-4;a.width=b;a.height=c;return 0},N:function(a,b,c,d){return bb(a,b,c,d,13,"focus")},W:function(a,b,c,d){return cb(a,b,c,d,2,"keydown")},U:function(a,b,c,d){return cb(a,b,c,d,1,"keypress")},V:function(a,b,c,d){return cb(a,b,c,d,3,"keyup")},aa:function(a,b,c,d){return N(a,b,c,d,
5,"mousedown")},Z:function(a,b,c,d){return N(a,b,c,d,33,"mouseenter")},Y:function(a,b,c,d){return N(a,b,c,d,34,"mouseleave")},_:function(a,b,c,d){return N(a,b,c,d,8,"mousemove")},$:function(a,b,c,d){return N(a,b,c,d,6,"mouseup")},P:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Rb||document.body.bc||document.body.ac))return-1;a=J(a);if(!a)return-4;eb(a,b,c,d,"mozpointerlockchange");eb(a,b,c,d,"webkitpointerlockchange");eb(a,b,c,d,"mspointerlockchange");
return eb(a,b,c,d,"pointerlockchange")},O:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Rb||document.body.bc||document.body.ac))return-1;a=J(a);if(!a)return-4;fb(a,b,c,d,"mozpointerlockerror");fb(a,b,c,d,"webkitpointerlockerror");fb(a,b,c,d,"mspointerlockerror");return fb(a,b,c,d,"pointerlockerror")},Ua:function(a,b,c,d){return gb(a,b,c,d)},Q:function(a,b,c,d){return hb(a,b,c,d,25,"touchcancel")},R:function(a,b,c,d){return hb(a,b,c,d,23,"touchend")},S:function(a,
b,c,d){return hb(a,b,c,d,24,"touchmove")},T:function(a,b,c,d){return hb(a,b,c,d,22,"touchstart")},L:function(a,b,c,d){Cb(a,b,c,d,31,"webglcontextlost");return 0},K:function(a,b,c,d){Cb(a,b,c,d,32,"webglcontextrestored");return 0},X:function(a,b,c,d){return(a=J(a))?"undefined"!=typeof a.onwheel?Db(a,b,c,d):-1:-4},Ra:function(a,b){b>>=2;b={alpha:!!A[b],depth:!!A[b+1],stencil:!!A[b+2],antialias:!!A[b+3],premultipliedAlpha:!!A[b+4],preserveDrawingBuffer:!!A[b+5],powerPreference:Eb[A[b+6]],failIfMajorPerformanceCaveat:!!A[b+
7],hc:A[b+8],Ac:A[b+9],ec:A[b+10],tc:A[b+11],Cc:A[b+12],Dc:A[b+13]};a=J(a);return!a||b.tc?0:zb(a,b)},Pa:function(a,b){a=ub[a];b=b?I(b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&ib(U);"OES_vertex_array_object"==b&&jb(U);"WEBGL_draw_buffers"==b&&kb(U);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&lb(U);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&mb(U);"WEBGL_multi_draw"==b&&nb(U);return!!a.Zb.getExtension(b)},Sa:function(a){a>>=2;for(var b=0;14>b;++b)A[a+
b]=0;A[a]=A[a+1]=A[a+3]=A[a+4]=A[a+8]=A[a+10]=1},Qa:function(a){T=ub[a];g.xc=U=T&&T.Zb;return!a||U?0:-5},g:function(a){U.activeTexture(a)},z:function(a,b){U.attachShader(P[a],Q[b])},d:function(a,b){35051==a?U.cc=b:35052==a&&(U.Vb=b);U.bindBuffer(a,pb[b])},i:function(a,b){U.bindFramebuffer(a,qb[b])},h:function(a,b){U.bindSampler(a,R[b])},a:function(a,b){U.bindTexture(a,sb[b])},I:function(a){U.bindVertexArray(tb[a])},E:function(a,b,c,d){U.blendColor(a,b,c,d)},F:function(a,b){U.blendEquationSeparate(a,
b)},G:function(a,b,c,d){U.blendFuncSeparate(a,b,c,d)},Ya:function(a,b,c,d,e,k,f,m,n,p){U.blitFramebuffer(a,b,c,d,e,k,f,m,n,p)},ya:function(a,b,c,d){2<=T.version?c&&b?U.bufferData(a,z,d,c,b):U.bufferData(a,b,d):U.bufferData(a,c?z.subarray(c,c+b):b,d)},xa:function(a,b,c,d){2<=T.version?c&&U.bufferSubData(a,b,z,d,c):U.bufferSubData(a,b,z.subarray(d,d+c))},rb:function(a,b,c,d){U.clearBufferfi(a,b,c,d)},ha:function(a,b,c){U.clearBufferfv(a,b,B,c>>2)},qb:function(a,b,c){U.clearBufferiv(a,b,A,c>>2)},j:function(a,
b,c,d){U.colorMask(!!a,!!b,!!c,!!d)},la:function(a){U.compileShader(Q[a])},ra:function(){var a=yb(P),b=U.createProgram();b.name=a;b.Yb=b.Wb=b.Xb=0;b.$b=1;P[a]=b;return a},na:function(a){var b=yb(Q);Q[b]=U.createShader(a);return b},B:function(a){U.cullFace(a)},La:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=pb[d];e&&(U.deleteBuffer(e),e.name=0,pb[d]=null,d==U.cc&&(U.cc=0),d==U.Vb&&(U.Vb=0))}},k:function(a,b){for(var c=0;c<a;++c){var d=A[b+4*c>>2],e=qb[d];e&&(U.deleteFramebuffer(e),e.name=
0,qb[d]=null)}},J:function(a){if(a){var b=P[a];b?(U.deleteProgram(b),b.name=0,P[a]=null):S(1281)}},Ja:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=rb[d];e&&(U.deleteRenderbuffer(e),e.name=0,rb[d]=null)}},Ha:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=R[d];e&&(U.deleteSampler(e),e.name=0,R[d]=null)}},r:function(a){if(a){var b=Q[a];b?(U.deleteShader(b),Q[a]=null):S(1281)}},Ka:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=sb[d];e&&(U.deleteTexture(e),e.name=0,sb[d]=null)}},
Ga:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2];U.deleteVertexArray(tb[d]);tb[d]=null}},u:function(a){U.depthFunc(a)},t:function(a){U.depthMask(!!a)},c:function(a){U.disable(a)},H:function(a){U.disableVertexAttribArray(a)},_a:function(a,b,c){U.drawArrays(a,b,c)},$a:function(a,b,c,d){U.drawArraysInstanced(a,b,c,d)},bb:function(a,b,c,d){U.drawElements(a,b,c,d)},cb:function(a,b,c,d,e){U.drawElementsInstanced(a,b,c,d,e)},f:function(a){U.enable(a)},nb:function(a){U.enableVertexAttribArray(a)},
C:function(a){U.frontFace(a)},za:function(a,b){Fb(a,b,"createBuffer",pb)},sa:function(a,b){Fb(a,b,"createSampler",R)},wa:function(a,b){Fb(a,b,"createTexture",sb)},Fa:function(a,b){Fb(a,b,"createVertexArray",tb)},ja:function(a,b){return U.getAttribLocation(P[a],b?I(b):"")},b:function(a,b){Gb(a,b)},pa:function(a,b,c,d){a=U.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(A[c>>2]=b)},y:function(a,b,c){if(c)if(a>=ob)S(1281);else if(a=P[a],35716==b)a=U.getProgramInfoLog(a),
null===a&&(a="(unknown error)"),A[c>>2]=a.length+1;else if(35719==b){if(!a.Yb)for(b=0;b<U.getProgramParameter(a,35718);++b)a.Yb=Math.max(a.Yb,U.getActiveUniform(a,b).name.length+1);A[c>>2]=a.Yb}else if(35722==b){if(!a.Wb)for(b=0;b<U.getProgramParameter(a,35721);++b)a.Wb=Math.max(a.Wb,U.getActiveAttrib(a,b).name.length+1);A[c>>2]=a.Wb}else if(35381==b){if(!a.Xb)for(b=0;b<U.getProgramParameter(a,35382);++b)a.Xb=Math.max(a.Xb,U.getActiveUniformBlockName(a,b).length+1);A[c>>2]=a.Xb}else A[c>>2]=U.getProgramParameter(a,
b);else S(1281)},ka:function(a,b,c,d){a=U.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(A[c>>2]=b)},w:function(a,b,c){c?35716==b?(a=U.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),A[c>>2]=a?a.length+1:0):35720==b?(a=U.getShaderSource(Q[a]),A[c>>2]=a?a.length+1:0):A[c>>2]=U.getShaderParameter(Q[a],b):S(1281)},Ma:function(a,b){if(2>T.version)return S(1282),0;var c=vb[a];if(c)return 0>b||b>=c.length?(S(1281),0):c[b];switch(a){case 7939:return c=U.getSupportedExtensions()||
[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){var e=Hb(d)+1,k=M(e);k&&L(d,k,e);return k}),c=vb[a]=c,0>b||b>=c.length?(S(1281),0):c[b];default:return S(1280),0}},m:function(a,b){b=b?I(b):"";if(a=P[a]){var c=a,d=c.Tb,e=c.qc,k;if(!d)for(c.Tb=d={},c.pc={},k=0;k<U.getProgramParameter(c,35718);++k){var f=U.getActiveUniform(c,k);var m=f.name;f=f.size;var n=Ib(m);n=0<n?m.slice(0,n):m;var p=c.$b;c.$b+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.pc[p++]=n}c=a.Tb;d=0;e=b;k=Ib(b);0<k&&(d=parseInt(b.slice(k+
1))>>>0,e=b.slice(0,k));if((e=a.qc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||U.getUniformLocation(a,b)))return d}else S(1281);return-1},Xa:function(a,b,c){for(var d=Jb[b],e=0;e<b;e++)d[e]=A[c+4*e>>2];U.invalidateFramebuffer(a,d)},qa:function(a){a=P[a];U.linkProgram(a);a.Tb=0;a.qc={}},Ea:function(a,b){3317==a&&(wb=b);U.pixelStorei(a,b)},D:function(a,b){U.polygonOffset(a,b)},Za:function(a){U.readBuffer(a)},A:function(a,b,c){U.samplerParameterf(R[a],b,c)},e:function(a,b,c){U.samplerParameteri(R[a],b,c)},sb:function(a,
b,c,d){U.scissor(a,b,c,d)},ma:function(a,b,c,d){for(var e="",k=0;k<b;++k){var f=d?A[d+4*k>>2]:-1,m=A[c+4*k>>2];f=m?I(m,0>f?void 0:f):"";e+=f}U.shaderSource(Q[a],e)},Ca:function(a,b,c){U.stencilFunc(a,b,c)},ga:function(a,b,c,d){U.stencilFuncSeparate(a,b,c,d)},s:function(a){U.stencilMask(a)},Ba:function(a,b,c){U.stencilOp(a,b,c)},fa:function(a,b,c,d){U.stencilOpSeparate(a,b,c,d)},va:function(a,b,c,d,e,k,f,m,n){if(2<=T.version)if(U.Vb)U.texImage2D(a,b,c,d,e,k,f,m,n);else if(n){var p=Kb(m);U.texImage2D(a,
b,c,d,e,k,f,m,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else U.texImage2D(a,b,c,d,e,k,f,m,null);else{p=U;var x=p.texImage2D;if(n){var t=Kb(m),O=31-Math.clz32(t.BYTES_PER_ELEMENT),V=wb;n=t.subarray(n>>O,n+e*(d*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*(1<<O)+V-1&-V)>>O)}else n=null;x.call(p,a,b,c,d,e,k,f,m,n)}},ta:function(a,b,c,d,e,k,f,m,n,p){if(U.Vb)U.texImage3D(a,b,c,d,e,k,f,m,n,p);else if(p){var x=Kb(n);U.texImage3D(a,b,c,d,e,k,f,m,n,x,p>>31-Math.clz32(x.BYTES_PER_ELEMENT))}else U.texImage3D(a,
b,c,d,e,k,f,m,n,null)},mb:function(a,b,c){if(2<=T.version)b&&U.uniform1fv(W(a),B,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);U.uniform1fv(W(a),d)}},x:function(a,b){U.uniform1i(W(a),b)},hb:function(a,b,c){if(2<=T.version)b&&U.uniform1iv(W(a),A,c>>2,b);else{if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);U.uniform1iv(W(a),d)}},kb:function(a,b,c){if(2<=T.version)b&&U.uniform2fv(W(a),B,c>>2,2*b);else{if(144>=
b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);U.uniform2fv(W(a),d)}},gb:function(a,b,c){if(2<=T.version)b&&U.uniform2iv(W(a),A,c>>2,2*b);else{if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);U.uniform2iv(W(a),d)}},jb:function(a,b,c){if(2<=T.version)b&&U.uniform3fv(W(a),B,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],
d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);U.uniform3fv(W(a),d)}},fb:function(a,b,c){if(2<=T.version)b&&U.uniform3iv(W(a),A,c>>2,3*b);else{if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);U.uniform3iv(W(a),d)}},ib:function(a,b,c){if(2<=T.version)b&&U.uniform4fv(W(a),B,c>>2,4*b);else{if(72>=b){var d=X[4*b-1],e=B;c>>=2;for(var k=0;k<4*b;k+=4){var f=c+k;d[k]=e[f];d[k+1]=e[f+1];d[k+2]=e[f+2];d[k+3]=
e[f+3]}}else d=B.subarray(c>>2,c+16*b>>2);U.uniform4fv(W(a),d)}},eb:function(a,b,c){if(2<=T.version)b&&U.uniform4iv(W(a),A,c>>2,4*b);else{if(72>=b)for(var d=Y[4*b-1],e=0;e<4*b;e+=4)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2],d[e+3]=A[c+(4*e+12)>>2];else d=A.subarray(c>>2,c+16*b>>2);U.uniform4iv(W(a),d)}},db:function(a,b,c,d){if(2<=T.version)b&&U.uniformMatrix4fv(W(a),!!c,B,d>>2,16*b);else{if(18>=b){var e=X[16*b-1],k=B;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=k[m];e[f+1]=k[m+
1];e[f+2]=k[m+2];e[f+3]=k[m+3];e[f+4]=k[m+4];e[f+5]=k[m+5];e[f+6]=k[m+6];e[f+7]=k[m+7];e[f+8]=k[m+8];e[f+9]=k[m+9];e[f+10]=k[m+10];e[f+11]=k[m+11];e[f+12]=k[m+12];e[f+13]=k[m+13];e[f+14]=k[m+14];e[f+15]=k[m+15]}}else e=B.subarray(d>>2,d+64*b>>2);U.uniformMatrix4fv(W(a),!!c,e)}},n:function(a){a=P[a];U.useProgram(a);U.rc=a},ob:function(a,b){U.vertexAttribDivisor(a,b)},pb:function(a,b,c,d,e,k){U.vertexAttribPointer(a,b,c,!!d,e,k)},ia:function(a,b,c,d){U.viewport(a,b,c,d)},Oa:function(){g.jc=a=>{0!=Qb()&&
(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.jc)},Ia:function(){g.oc=a=>{const b=a.clipboardData.getData("text");Ia(()=>{const c=Nb(b);Rb(c)})};window.addEventListener("paste",g.oc)},Aa:function(a){g.Ec=[];a=a?I(a):"";a=document.getElementById(a);g.kc=b=>{b.stopPropagation();b.preventDefault()};g.lc=b=>{b.stopPropagation();b.preventDefault()};g.mc=b=>{b.stopPropagation();b.preventDefault()};g.nc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;
g.Fc=c;Sb(c.length);for(let e=0;e<c.length;e++)Ia(()=>{const k=Nb(c[e].name);Tb(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Ub(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.kc,!1);a.addEventListener("dragleave",g.lc,!1);a.addEventListener("dragover",g.mc,!1);a.addEventListener("drop",g.nc,!1)},lb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},q:function(){const a=document.createElement("input");
a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Vb()});document.body.append(a)},p:function(){document.getElementById("_sokol_app_input_element").focus()},oa:function(a){a=a?I(a):"";g.Sb=document.getElementById(a);g.Sb||console.log("sokol_app.h: invalid target:"+a);g.Sb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Na:function(){window.removeEventListener("beforeunload",g.jc)},Da:function(){window.removeEventListener("paste",
g.oc)},ua:function(a){a=a?I(a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.kc);a.removeEventListener("dragleave",g.lc);a.removeEventListener("dragover",g.mc);a.removeEventListener("drop",g.nc)},v:function(){g.Sb&&g.Sb.requestPointerLock&&g.Sb.requestPointerLock()},ab:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(z.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");
a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},o:function(){document.getElementById("_sokol_app_input_element").blur()},ea:function(a,b){b=b?I(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};
(function(){function a(c){y=c=c.exports;ka=y.tb;qa();ra=y.Jb;ta.unshift(y.ub);D--;g.monitorRunDependencies&&g.monitorRunDependencies(D);if(0==D&&(null!==ya&&(clearInterval(ya),ya=null),E)){var d=E;E=null;d()}return c}var b={a:Wb};D++;g.monitorRunDependencies&&g.monitorRunDependencies(D);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return v("Module.instantiateWasm callback failed with error: "+c),!1}Ea(b,function(c){a(c.instance)});return{}})();
var Vb=g.__sapp_emsc_notify_keyboard_hidden=()=>(Vb=g.__sapp_emsc_notify_keyboard_hidden=y.vb)(),Rb=g.__sapp_emsc_onpaste=a=>(Rb=g.__sapp_emsc_onpaste=y.wb)(a),Qb=g.__sapp_html5_get_ask_leave_site=()=>(Qb=g.__sapp_html5_get_ask_leave_site=y.xb)(),Sb=g.__sapp_emsc_begin_drop=a=>(Sb=g.__sapp_emsc_begin_drop=y.yb)(a),Tb=g.__sapp_emsc_drop=(a,b)=>(Tb=g.__sapp_emsc_drop=y.zb)(a,b),Ub=g.__sapp_emsc_end_drop=(a,b,c)=>(Ub=g.__sapp_emsc_end_drop=y.Ab)(a,b,c);
g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,k,f,m)=>(g.__sapp_emsc_invoke_fetch_cb=y.Bb)(a,b,c,d,e,k,f,m);var Xb=g._main=(a,b)=>(Xb=g._main=y.Cb)(a,b);g.__saudio_emsc_pull=a=>(g.__saudio_emsc_pull=y.Db)(a);g.__sfetch_emsc_head_response=(a,b)=>(g.__sfetch_emsc_head_response=y.Eb)(a,b);g.__sfetch_emsc_get_response=(a,b,c)=>(g.__sfetch_emsc_get_response=y.Fb)(a,b,c);g.__sfetch_emsc_failed_http_status=(a,b)=>(g.__sfetch_emsc_failed_http_status=y.Gb)(a,b);
g.__sfetch_emsc_failed_buffer_too_small=a=>(g.__sfetch_emsc_failed_buffer_too_small=y.Hb)(a);var M=a=>(M=y.Ib)(a),Ga=()=>(Ga=y.Kb)(),Ha=a=>(Ha=y.Lb)(a),Mb=a=>(Mb=y.Mb)(a);g.___start_em_js=8984;g.___stop_em_js=18659;var Yb;E=function Zb(){Yb||$b();Yb||(E=Zb)};function ac(a=[]){var b=Xb;a.unshift(ca);var c=a.length,d=Mb(4*(c+1)),e=d>>2;a.forEach(f=>{A[e++]=Nb(f)});A[e]=0;try{var k=b(c,d);Lb(k)}catch(f){f instanceof ia||"unwind"==f||h(1,f)}}
function $b(){var a=ba;function b(){if(!Yb&&(Yb=!0,g.calledRun=!0,!la)){Fa(ta);Fa(ua);if(g.onRuntimeInitialized)g.onRuntimeInitialized();bc&&ac(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();wa.unshift(c)}Fa(wa)}}if(!(0<D)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)xa();Fa(sa);0<D||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var bc=!0;g.noInitialRun&&(bc=!1);$b();
