var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs");require("path");k=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?
"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var la=f.print||console.log.bind(console),m=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);var ma=f.wasmBinary,na,p=!1,oa,r,t,pa,qa,u,v,x,y,ra=a=>a.startsWith("data:application/octet-stream;base64,"),ka=a=>a.startsWith("file://");
function sa(){var a=na.buffer;f.HEAP8=r=new Int8Array(a);f.HEAP16=pa=new Int16Array(a);f.HEAPU8=t=new Uint8Array(a);f.HEAPU16=qa=new Uint16Array(a);f.HEAP32=u=new Int32Array(a);f.HEAPU32=v=new Uint32Array(a);f.HEAPF32=x=new Float32Array(a);f.HEAPF64=y=new Float64Array(a);f.HEAP64=new BigInt64Array(a);f.HEAPU64=new BigUint64Array(a)}var ua=[],va=[],wa=[],xa=[];function ya(){var a=f.preRun.shift();ua.unshift(a)}var z=0,A=null;
function za(a){f.onAbort?.(a);a="Aborted("+a+")";m(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Aa;async function Ba(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==Aa&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ca(a,b){try{var c=await Ba(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),za(d)}}async function Da(a){var b=Aa;if(!(ma||"function"!=typeof WebAssembly.instantiateStreaming||ra(b)||ka(b)||ca))try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return Ca(b,a)}
class Ea{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Fa=a=>{for(;0<a.length;)a.shift()(f)},Ga=f.noExitRuntime||!0,Ha=0,B={},Ia=a=>{a instanceof Ea||"unwind"==a||ha(1,a)},Ja=a=>{oa=a;Ga||0<Ha||(f.onExit?.(a),p=!0);ha(a,new Ea(a))},Ka=a=>{oa=a;Ja(a)},La=()=>{if(!(Ga||0<Ha))try{var a=oa;oa=a;Ja(a)}catch(b){Ia(b)}},Ma=a=>{if(!p)try{a(),La()}catch(b){Ia(b)}},Ta=(a,b)=>{Na=a;Oa=b;if(C)if(Pa||=!0,0==a)D=function(){setTimeout(F,Math.max(0,Qa+b-performance.now())|0)};else if(1==a)D=function(){Ra(F)};else if(2==a){if("undefined"==typeof Sa)if("undefined"==
typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Sa=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Sa=setImmediate;D=function(){Sa(F)}}},bb=(a,b,c,d,e)=>{function h(){return g<Ua?(La(),!1):!0}C=a;Va=d;var g=Ua;Pa=!1;F=function(){if(!p)if(0<Wa.length){var l=Wa.shift();
l.ld(l.ad);if(Xa){var n=Xa,q=0==n%1?n-1:Math.floor(n);Xa=l.cd?q:(8*n+(q+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",n=Xa??0,q=Ya.jd??0,n?n<q?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));h()&&setTimeout(F,0)}else if(h())if(Za=Za+1|0,1==Na&&1<Oa&&0!=Za%Oa)D();else{0==Na&&(Qa=performance.now());a:if(!p){for(l of $a)if(!1===l())break a;Ma(a);for(n of ab)n()}h()&&D()}};e||(0<b?Ta(0,1E3/b):Ta(1,1),D());if(c)throw"unwind";},Pa=!1,D=null,Ua=0,C=
null,Va=0,Na=0,Oa=0,Za=0,Wa=[],$a=[],ab=[];function cb(){D=null;Ua++}var G=0;function Ra(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===G)G=b+1E3/60;else for(;b+2>=G;)G+=1E3/60;setTimeout(a,Math.max(G-b,0))}}var Ya={},Qa,F,Sa,Xa;function db(a){var b=H.ac[a];b.target.removeEventListener(b.$b,b.Fc,b.bc);H.ac.splice(a,1)}
function eb(){if(navigator.userActivation?navigator.userActivation.isActive:H.rc&&H.Sc.pc){var a=H.ec;H.ec=[];for(var b of a)b.uc(...b.Ac)}}function I(a){if(!a.target)return-4;if(a.cc)a.Fc=function(c){++H.rc;H.Sc=a;eb();a.dc(c);eb();--H.rc},a.target.addEventListener(a.$b,a.Fc,a.bc),H.ac.push(a);else for(var b=0;b<H.ac.length;++b)H.ac[b].target==a.target&&H.ac[b].$b==a.$b&&db(b--);return 0}function fb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var H={bd:0,md:0,sc:0,nc:0,yc:0,wc:0,qc:0,gd:0,qd:0,ed:0,kd:0,tc:0,zd:0,vc:0,od(a,b,c){r.set(r.subarray(b,b+c),a)},sd(){for(;H.ac.length;)db(H.ac.length-1);H.ec=[]},rc:0,ec:[],dd(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var l in h)if(h[l]!=g[l])return!1;return!0}for(var e of H.ec)if(e.uc==a&&d(e.Ac,c))return;H.ec.push({uc:a,Jc:b,Ac:c});H.ec.sort((h,g)=>h.Jc<g.Jc)},ud(a){H.ec=H.ec.filter(b=>b.uc!=a)},ac:[],td:(a,b)=>{for(var c=0;c<H.ac.length;++c)H.ac[c].target!=a||b&&b!=H.ac[c].$b||
db(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},gb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,J=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&gb)return gb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,
d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},hb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?J(t,a):"":a;return hb[a]||("undefined"!=typeof document?document.querySelector(a):null)},ib=a=>0>hb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},jb=[],kb,L=a=>{var b=jb[a];b||(a>=jb.length&&(jb.length=a+1),jb[a]=b=kb.get(a));return b},M=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=
a.charCodeAt(h);if(55296<=g&&57343>=g){var l=a.charCodeAt(++h);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},lb=(a,b,c,d,e,h)=>{H.qc||(H.qc=N(256));a={target:K(a),$b:h,cc:d,dc:(g=event)=>{var l=g.target.id?g.target.id:"",n=H.qc;M(fb(g.target),n+0,128);M(l,n+128,128);L(d)(e,
n,b)&&g.preventDefault()},bc:c};return I(a)},mb=(a,b,c,d,e,h)=>{H.sc||(H.sc=N(160));a={target:K(a),$b:h,cc:d,dc:g=>{var l=H.sc;y[l>>3]=g.timeStamp;var n=l>>2;u[n+2]=g.location;r[l+12]=g.ctrlKey;r[l+13]=g.shiftKey;r[l+14]=g.altKey;r[l+15]=g.metaKey;r[l+16]=g.repeat;u[n+5]=g.charCode;u[n+6]=g.keyCode;u[n+7]=g.which;M(g.key||"",l+32,32);M(g.code||"",l+64,32);M(g.char||"",l+96,32);M(g.locale||"",l+128,32);L(d)(e,l,b)&&g.preventDefault()},bc:c};return I(a)},nb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;
u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=ib(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,h)=>{H.nc||(H.nc=N(64));a=K(a);return I({target:a,pc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,$b:h,cc:d,dc:(g=event)=>{nb(H.nc,g,a);L(d)(e,H.nc,b)&&g.preventDefault()},bc:c})},ob=(a,b,c,d,e)=>{H.tc||
(H.tc=N(257));return I({target:a,$b:e,cc:d,dc:(h=event)=>{var g=H.tc,l=document.pointerLockElement||document.ic||document.Bc||document.zc;r[g]=!!l;var n=l?.id||"";M(fb(l),g+1,128);M(n,g+129,128);L(d)(20,g,b)&&h.preventDefault()},bc:c})},pb=(a,b,c,d,e)=>I({target:a,$b:e,cc:d,dc:(h=event)=>{L(d)(38,0,b)&&h.preventDefault()},bc:c}),qb=(a,b,c,d)=>{H.wc||(H.wc=N(36));a=K(a);return I({target:a,$b:"resize",cc:d,dc:(e=event)=>{if(e.target==a){var h=document.body;if(h){var g=H.wc;u[g>>2]=0;u[g+4>>2]=h.clientWidth;
u[g+8>>2]=h.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;L(d)(10,g,b)&&e.preventDefault()}}},bc:c})},rb=(a,b,c,d,e,h)=>{H.vc||(H.vc=N(1552));a=K(a);return I({target:a,pc:"touchstart"==h||"touchend"==h,$b:h,cc:d,dc:g=>{var l={},n=g.touches;for(var q of n)q.Gc=q.Ic=0,l[q.identifier]=q;for(var w of g.changedTouches)w.Gc=1,l[w.identifier]=w;for(var ta of g.targetTouches)l[ta.identifier].Ic=1;n=
H.vc;y[n>>3]=g.timeStamp;r[n+12]=g.ctrlKey;r[n+13]=g.shiftKey;r[n+14]=g.altKey;r[n+15]=g.metaKey;q=n+16;w=ib(a);ta=0;for(let E of Object.values(l))if(l=q>>2,u[l]=E.identifier,u[l+1]=E.screenX,u[l+2]=E.screenY,u[l+3]=E.clientX,u[l+4]=E.clientY,u[l+5]=E.pageX,u[l+6]=E.pageY,r[q+28]=E.Gc,r[q+29]=E.Ic,u[l+8]=E.clientX-(w.left|0),u[l+9]=E.clientY-(w.top|0),q+=48,31<++ta)break;u[n+8>>2]=ta;L(d)(e,n,b)&&g.preventDefault()},bc:c})},P,sb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=
(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,d,e,h,g))},tb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},ub=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,
d)=>b.drawBuffersWEBGL(c,d))},vb=a=>{a.hd=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},wb=a=>{a.nd=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},xb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},yb=1,Q=[],R=[],zb=[],Ab=[],Bb=[],S=[],Cb=[],Db=[],T=[],Eb={},Fb=4,Gb=0,Hb=a=>{for(var b=yb++,c=a.length;c<b;c++)a[c]=null;return b},Ib=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=P[c](),g=h&&Hb(d);h?(h.name=g,d[g]=h):U||=1282;u[b+4*e>>2]=g}},Kb=(a,b)=>{a.ic||(a.ic=a.getContext,a.getContext=function(d,e){e=a.ic(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Hc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?Jb(c,b):0},Jb=(a,b)=>{var c=Hb(Db),d={handle:c,attributes:b,version:b.Hc,oc:a};a.canvas&&(a.canvas.$c=d);Db[c]=d;("undefined"==typeof b.Ec||b.Ec)&&Lb(d);return c},Lb=a=>{a||=V;if(!a.Xc){a.Xc=!0;var b=a.oc;b.Yc=b.getExtension("WEBGL_multi_draw");b.Wc=b.getExtension("EXT_polygon_offset_clamp");b.Vc=b.getExtension("EXT_clip_control");b.Zc=b.getExtension("WEBGL_polygon_mode");sb(b);tb(b);ub(b);vb(b);wb(b);2<=a.version&&(b.Dc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||
!b.Dc)b.Dc=b.getExtension("EXT_disjoint_timer_query");xb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},U,V,Mb=(a,b,c,d,e,h)=>{a={target:K(a),$b:h,cc:d,dc:(g=event)=>{L(d)(e,0,b)&&g.preventDefault()},bc:c};I(a)},Nb=(a,b,c,d)=>{H.yc||(H.yc=N(96));return I({target:a,pc:!0,$b:"wheel",cc:d,dc:(e=event)=>{var h=H.yc;nb(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+80>>3]=e.deltaZ;u[h+88>>2]=e.deltaMode;L(d)(9,h,b)&&e.preventDefault()},bc:c})},Ob=["default","low-power",
"high-performance"],Pb=[null,[],[]],Qb=()=>{var a=xb(P);return a=a.concat(a.map(b=>"GL_"+b))},Rb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=Qb().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=P.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;
case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);
return}}break;default:U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else U||=1281},Sb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Tb=a=>{var b=Sb(a)+1,c=N(b);c&&M(a,c,b);return c},Ub=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Vb=[],Wb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?u:6==a?x:5==a||28922==a||28520==a||30779==a||30782==
a?v:qa},W=a=>{var b=P.Tc;if(b){var c=b.jc[a];"number"==typeof c&&(b.jc[a]=c=P.getUniformLocation(b,b.Qc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],Xb=[],Zb=a=>{var b=Sb(a)+1,c=Yb(b);M(a,c,b);return c},bc=a=>{var b=$b();a();ac(b)};f.requestAnimationFrame=Ra;f.pauseMainLoop=cb;f.resumeMainLoop=function(){Ua++;var a=Na,b=Oa,c=C;C=null;bb(c,0,!1,Va,!0);Ta(a,b);D()};f.preMainLoop&&$a.push(f.preMainLoop);f.postMainLoop&&ab.push(f.postMainLoop);for(var Y=0;32>Y;++Y)Vb.push(Array(Y));var cc=new Float32Array(288);
for(Y=0;288>=Y;++Y)X[Y]=cc.subarray(0,Y);var dc=new Int32Array(288);for(Y=0;288>=Y;++Y)Xb[Y]=dc.subarray(0,Y);
var kc={eb:()=>za(""),_a:()=>{Ga=!1;Ha=0},$a:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];Ma(()=>ec(a,performance.now()))},b);B[a]={id:c,yd:b};return 0},Pa:()=>{cb();C=null},ba:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,fa:(a,b,c)=>{a=K(a);if(!a)return-4;a=ib(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Qa:()=>performance.now(),Xa:(a,b)=>{function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ab:a=>
{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);sa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},L:(a,b,c,d)=>lb(a,b,c,d,12,"blur"),aa:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},M:(a,b,c,d)=>lb(a,b,c,d,13,"focus"),V:(a,b,c,d)=>mb(a,b,c,d,2,"keydown"),T:(a,b,c,d)=>mb(a,b,c,d,1,"keypress"),
U:(a,b,c,d)=>mb(a,b,c,d,3,"keyup"),Ya:(a,b,c)=>{a=L(a);bb(a,b,c)},$:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),Y:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),X:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),Z:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),_:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),O:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.ic||document.body.Bc||document.body.zc))return-1;a=K(a);if(!a)return-4;ob(a,b,c,d,"mozpointerlockchange");ob(a,b,c,d,"webkitpointerlockchange");ob(a,
b,c,d,"mspointerlockchange");return ob(a,b,c,d,"pointerlockchange")},N:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.ic||document.body.Bc||document.body.zc))return-1;a=K(a);if(!a)return-4;pb(a,b,c,d,"mozpointerlockerror");pb(a,b,c,d,"webkitpointerlockerror");pb(a,b,c,d,"mspointerlockerror");return pb(a,b,c,d,"pointerlockerror")},ca:(a,b,c,d)=>qb(a,b,c,d),P:(a,b,c,d)=>rb(a,b,c,d,25,"touchcancel"),Q:(a,b,c,d)=>rb(a,b,c,d,23,"touchend"),R:(a,b,c,d)=>rb(a,b,c,d,24,"touchmove"),
S:(a,b,c,d)=>rb(a,b,c,d,22,"touchstart"),K:(a,b,c,d)=>{Mb(a,b,c,d,31,"webglcontextlost");return 0},J:(a,b,c,d)=>{Mb(a,b,c,d,32,"webglcontextrestored");return 0},W:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?Nb(a,b,c,d):-1:-4,Wa:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Ob[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Hc:u[c+4],pd:u[c+5],Ec:r[b+24],Uc:r[b+25],rd:u[c+7],vd:r[b+
32]};a=K(a);return!a||b.Uc?0:Kb(a,b)},Ta:(a,b)=>{a=Db[a];b=b?J(t,b):"";b.startsWith("GL_")&&(b=b.slice(3));"ANGLE_instanced_arrays"==b&&sb(P);"OES_vertex_array_object"==b&&tb(P);"WEBGL_draw_buffers"==b&&ub(P);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&vb(P);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&wb(P);"WEBGL_multi_draw"==b&&(P.Yc=P.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(P.Wc=P.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&
(P.Vc=P.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(P.Zc=P.getExtension("WEBGL_polygon_mode"));return!!a.oc.getExtension(b)},Va:a=>{V=Db[a];f.ctx=P=V?.oc;return!a||P?0:-5},db:()=>52,bb:function(){return 70},cb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var g=v[b>>2],l=v[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=t[g+n],w=Pb[a];0===q||10===q?((1===a?la:m)(J(w)),w.length=0):w.push(q)}e+=l}v[d>>2]=e;return 0},k:a=>P.activeTexture(a),w:(a,b)=>{P.attachShader(R[a],S[b])},b:(a,b)=>{35051==a?P.Cc=
b:35052==a&&(P.hc=b);P.bindBuffer(a,Q[b])},a:(a,b,c)=>{P.bindBufferBase(a,b,Q[c])},m:(a,b)=>{P.bindFramebuffer(a,zb[b])},Ca:(a,b)=>{P.bindRenderbuffer(a,Ab[b])},j:(a,b)=>{P.bindSampler(a,T[b])},c:(a,b)=>{P.bindTexture(a,Bb[b])},I:a=>{P.bindVertexArray(Cb[a])},E:(a,b,c,d)=>P.blendColor(a,b,c,d),F:(a,b)=>P.blendEquationSeparate(a,b),G:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),gb:(a,b,c,d,e,h,g,l,n,q)=>P.blitFramebuffer(a,b,c,d,e,h,g,l,n,q),Ea:(a,b,c,d)=>{2<=V.version?c&&b?P.bufferData(a,t,d,c,b):P.bufferData(a,
b,d):P.bufferData(a,c?t.subarray(c,c+b):b,d)},y:(a,b,c,d)=>{2<=V.version?c&&P.bufferSubData(a,b,t,d,c):P.bufferSubData(a,b,t.subarray(d,d+c))},zb:(a,b,c,d)=>P.clearBufferfi(a,b,c,d),ga:(a,b,c)=>{P.clearBufferfv(a,b,x,c>>2)},yb:(a,b,c)=>{P.clearBufferiv(a,b,u,c>>2)},l:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},Cb:a=>{P.compileShader(S[a])},va:(a,b,c,d,e,h,g,l)=>{2<=V.version?P.hc||!g?P.compressedTexImage2D(a,b,c,d,e,h,g,l):P.compressedTexImage2D(a,b,c,d,e,h,t,l,g):P.compressedTexImage2D(a,b,c,d,e,h,
t.subarray(l,l+g))},ta:(a,b,c,d,e,h,g,l,n)=>{P.hc?P.compressedTexImage3D(a,b,c,d,e,h,g,l,n):P.compressedTexImage3D(a,b,c,d,e,h,g,t,n,l)},pa:()=>{var a=Hb(R),b=P.createProgram();b.name=a;b.mc=b.kc=b.lc=0;b.xc=1;R[a]=b;return a},la:a=>{var b=Hb(S);S[b]=P.createShader(a);return b},B:a=>P.cullFace(a),Ha:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(P.deleteBuffer(e),e.name=0,Q[d]=null,d==P.Cc&&(P.Cc=0),d==P.hc&&(P.hc=0))}},h:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=zb[d];e&&(P.deleteFramebuffer(e),
e.name=0,zb[d]=null)}},o:a=>{if(a){var b=R[a];b?(P.deleteProgram(b),b.name=0,R[a]=null):U||=1281}},z:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Ab[d];e&&(P.deleteRenderbuffer(e),e.name=0,Ab[d]=null)}},q:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=T[d];e&&(P.deleteSampler(e),e.name=0,T[d]=null)}},n:a=>{if(a){var b=S[a];b?(P.deleteShader(b),S[a]=null):U||=1281}},A:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Bb[d];e&&(P.deleteTexture(e),e.name=0,Bb[d]=null)}},Ga:(a,b)=>{for(var c=0;c<
a;c++){var d=u[b+4*c>>2];P.deleteVertexArray(Cb[d]);Cb[d]=null}},t:a=>P.depthFunc(a),s:a=>{P.depthMask(!!a)},e:a=>P.disable(a),H:a=>{P.disableVertexAttribArray(a)},ib:(a,b,c)=>{P.drawArrays(a,b,c)},jb:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},kb:(a,b,c,d)=>{P.drawElements(a,b,c,d)},lb:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},g:a=>P.enable(a),vb:a=>{P.enableVertexAttribArray(a)},C:a=>P.frontFace(a),Fa:(a,b)=>{Ib(a,b,"createBuffer",Q)},Da:(a,b)=>{Ib(a,b,"createRenderbuffer",Ab)},ra:(a,b)=>
{Ib(a,b,"createSampler",T)},za:(a,b)=>{Ib(a,b,"createTexture",Bb)},Oa:(a,b)=>{Ib(a,b,"createVertexArray",Cb)},Ab:(a,b)=>P.getAttribLocation(R[a],b?J(t,b):""),d:(a,b)=>Rb(a,b),na:(a,b,c,d)=>{a=P.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},v:(a,b,c)=>{if(c)if(a>=yb)U||=1281;else if(a=R[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.mc){var d=P.getProgramParameter(a,35718);for(b=0;b<d;++b)a.mc=
Math.max(a.mc,P.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.mc}else if(35722==b){if(!a.kc)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.kc=Math.max(a.kc,P.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.kc}else if(35381==b){if(!a.lc)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.lc=Math.max(a.lc,P.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.lc}else u[c>>2]=P.getProgramParameter(a,b);else U||=1281},Bb:(a,b,c,d)=>{a=P.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?
M(a,d,b):0;c&&(u[c>>2]=b)},ja:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(S[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=P.getShaderParameter(S[a],b):U||=1281},Ma:(a,b)=>{if(2>V.version)return U||=1282,0;var c=Eb[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Qb().map(Tb),c=Eb[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},u:(a,b)=>{b=b?J(t,b):"";if(a=R[a]){var c=
a,d=c.jc,e=c.Rc,h;if(!d){c.jc=d={};c.Qc={};var g=P.getProgramParameter(c,35718);for(h=0;h<g;++h){var l=P.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Ub(n);q=0<q?n.slice(0,q):n;var w=c.xc;c.xc+=l;e[q]=[l,w];for(n=0;n<l;++n)d[w]=n,c.Qc[w++]=q}}c=a.jc;d=0;e=b;h=Ub(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Rc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else U||=1281;return-1},fb:(a,b,c)=>{for(var d=Vb[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];P.invalidateFramebuffer(a,
d)},oa:a=>{a=R[a];P.linkProgram(a);a.jc=0;a.Rc={}},Na:(a,b)=>{3317==a?Fb=b:3314==a&&(Gb=b);P.pixelStorei(a,b)},D:(a,b)=>P.polygonOffset(a,b),hb:a=>P.readBuffer(a),Ba:(a,b,c,d,e)=>P.renderbufferStorageMultisample(a,b,c,d,e),x:(a,b,c)=>{P.samplerParameterf(T[a],b,c)},f:(a,b,c)=>{P.samplerParameteri(T[a],b,c)},ha:(a,b,c,d)=>P.scissor(a,b,c,d),Db:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var g=(g=v[c+4*h>>2])?J(t,g,d?v[d+4*h>>2]:void 0):"";e+=g}P.shaderSource(S[a],e)},Ka:(a,b,c)=>P.stencilFunc(a,b,c),ea:(a,
b,c,d)=>P.stencilFuncSeparate(a,b,c,d),r:a=>P.stencilMask(a),Ja:(a,b,c)=>P.stencilOp(a,b,c),da:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),ua:(a,b,c,d,e,h,g,l,n)=>{if(2<=V.version){if(P.hc){P.texImage2D(a,b,c,d,e,h,g,l,n);return}if(n){var q=Wb(l);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);P.texImage2D(a,b,c,d,e,h,g,l,q,n);return}}if(n){q=Wb(l);var w=e*((Gb||d)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT+Fb-1&-Fb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),
n+w>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;P.texImage2D(a,b,c,d,e,h,g,l,n)},sa:(a,b,c,d,e,h,g,l,n,q)=>{if(P.hc)P.texImage3D(a,b,c,d,e,h,g,l,n,q);else if(q){var w=Wb(n);P.texImage3D(a,b,c,d,e,h,g,l,n,w,q>>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else P.texImage3D(a,b,c,d,e,h,g,l,n,null)},ya:(a,b,c)=>P.texParameteri(a,b,c),xa:(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),wa:(a,b,c,d,e,h)=>P.texStorage3D(a,b,c,d,e,h),ub:(a,b,c)=>{if(2<=V.version)b&&P.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=
X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);P.uniform1fv(W(a),d)}},ma:(a,b)=>{P.uniform1i(W(a),b)},qb:(a,b,c)=>{if(2<=V.version)b&&P.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=Xb[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);P.uniform1iv(W(a),d)}},tb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);P.uniform2fv(W(a),d)}},
pb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Xb[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);P.uniform2iv(W(a),d)}},sb:(a,b,c)=>{if(2<=V.version)b&&P.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);P.uniform3fv(W(a),d)}},ob:(a,b,c)=>{if(2<=V.version)b&&P.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=
b){b*=3;for(var d=Xb[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);P.uniform3iv(W(a),d)}},rb:(a,b,c)=>{if(2<=V.version)b&&P.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);P.uniform4fv(W(a),d)}},nb:(a,b,c)=>{if(2<=V.version)b&&P.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Xb[b],
e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);P.uniform4iv(W(a),d)}},mb:(a,b,c,d)=>{if(2<=V.version)b&&P.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=x;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=
h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(W(a),!!c,e)}},i:a=>{a=R[a];P.useProgram(a);P.Tc=a},wb:(a,b)=>{P.vertexAttribDivisor(a,b)},xb:(a,b,c,d,e,h)=>{P.vertexAttribPointer(a,b,c,!!d,e,h)},ia:(a,b,c,d)=>P.viewport(a,b,c,d),Za:Ja,Fb:function(){f.Kc=a=>{0!=fc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Kc)},Ua:function(){f.Pc=a=>{const b=a.clipboardData.getData("text");bc(()=>{const c=Zb(b);gc(c)})};window.addEventListener("paste",
f.Pc)},Ra:function(){f.wd=[];f.Lc=b=>{b.stopPropagation();b.preventDefault()};f.Mc=b=>{b.stopPropagation();b.preventDefault()};f.Nc=b=>{b.stopPropagation();b.preventDefault()};f.Oc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.xd=c;hc(c.length);for(let e=0;e<c.length;e++)bc(()=>{const h=Zb(c[e].name);ic(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);jc(b.clientX,b.clientY,d)};const a=f.fc;a.addEventListener("dragenter",f.Lc,!1);a.addEventListener("dragleave",
f.Mc,!1);a.addEventListener("dragover",f.Nc,!1);a.addEventListener("drop",f.Oc,!1)},Aa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ia:function(a,b){0!==b&&(document.title=b?J(t,b):"");a=a?J(t,a):"";void 0!==f.canvas&&("object"===typeof f.canvas?hb[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.fc=K(a);f.fc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.fc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",
a)},Eb:function(){window.removeEventListener("beforeunload",f.Kc)},Sa:function(){window.removeEventListener("paste",f.Pc)},La:function(){const a=f.fc;a.removeEventListener("dragenter",f.Lc);a.removeEventListener("dragleave",f.Mc);a.removeEventListener("dragover",f.Nc);a.removeEventListener("drop",f.Oc)},p:function(){f.fc&&f.fc.requestPointerLock&&f.fc.requestPointerLock()},qa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,
b);h.data.set(t.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},ka:function(a,b){b=b?J(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;na=Z.Gb;sa();kb=Z.Vb;va.unshift(Z.Hb);z--;f.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;f.monitorRunDependencies?.(z);var b={a:kc};if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return m(`Module.instantiateWasm callback failed with error: ${c}`),!1}Aa??=ra("basisu-sapp.wasm")?"basisu-sapp.wasm":f.locateFile?f.locateFile("basisu-sapp.wasm",k):k+"basisu-sapp.wasm";return a((await Da(b)).instance)})();
var N=a=>(N=Z.Ib)(a),gc=f.__sapp_emsc_onpaste=a=>(gc=f.__sapp_emsc_onpaste=Z.Jb)(a),fc=f.__sapp_html5_get_ask_leave_site=()=>(fc=f.__sapp_html5_get_ask_leave_site=Z.Kb)(),hc=f.__sapp_emsc_begin_drop=a=>(hc=f.__sapp_emsc_begin_drop=Z.Lb)(a),ic=f.__sapp_emsc_drop=(a,b)=>(ic=f.__sapp_emsc_drop=Z.Mb)(a,b),jc=f.__sapp_emsc_end_drop=(a,b,c)=>(jc=f.__sapp_emsc_end_drop=Z.Nb)(a,b,c);f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,g,l)=>(f.__sapp_emsc_invoke_fetch_cb=Z.Ob)(a,b,c,d,e,h,g,l);
var lc=f._main=(a,b)=>(lc=f._main=Z.Pb)(a,b);f.__saudio_emsc_pull=a=>(f.__saudio_emsc_pull=Z.Qb)(a);f.__sfetch_emsc_head_response=(a,b)=>(f.__sfetch_emsc_head_response=Z.Rb)(a,b);f.__sfetch_emsc_get_response=(a,b,c)=>(f.__sfetch_emsc_get_response=Z.Sb)(a,b,c);f.__sfetch_emsc_failed_http_status=(a,b)=>(f.__sfetch_emsc_failed_http_status=Z.Tb)(a,b);f.__sfetch_emsc_failed_buffer_too_small=a=>(f.__sfetch_emsc_failed_buffer_too_small=Z.Ub)(a);
var ec=(a,b)=>(ec=Z.Wb)(a,b),ac=a=>(ac=Z.Xb)(a),Yb=a=>(Yb=Z.Yb)(a),$b=()=>($b=Z.Zb)();function mc(a=[]){var b=lc;a.unshift(fa);var c=a.length,d=Yb(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=Zb(g);e+=4});v[e>>2]=0;try{var h=b(c,d);Ka(h)}catch(g){Ia(g)}}
function nc(a=ea){function b(){f.calledRun=!0;if(!p){Fa(va);Fa(wa);f.onRuntimeInitialized?.();f.noInitialRun||mc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();xa.unshift(c)}Fa(xa)}}if(0<z)A=nc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ya();Fa(ua);0<z?A=nc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();nc();
