var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},g),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs"),ka=require("path");k=__dirname+"/";ja=a=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a)};ia=a=>{a=la(a)?new URL(a):ka.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!g.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&
document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?"":k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=a=>la(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var ma=g.print||console.log.bind(console),m=g.printErr||console.error.bind(console);Object.assign(g,da);da=null;g.arguments&&(ea=g.arguments);g.thisProgram&&(fa=g.thisProgram);var na=g.wasmBinary,oa,p=!1,pa,r,t,qa,ra,u,v,x,y;
function sa(){var a=oa.buffer;g.HEAP8=r=new Int8Array(a);g.HEAP16=qa=new Int16Array(a);g.HEAPU8=t=new Uint8Array(a);g.HEAPU16=ra=new Uint16Array(a);g.HEAP32=u=new Int32Array(a);g.HEAPU32=v=new Uint32Array(a);g.HEAPF32=x=new Float32Array(a);g.HEAPF64=y=new Float64Array(a)}var ua=[],va=[],wa=[],xa=[];function ya(){var a=g.preRun;a&&("function"==typeof a&&(a=[a]),a.forEach(za));Aa(ua)}function za(a){ua.unshift(a)}function Ba(a){xa.unshift(a)}var z=0,Ca=null,A=null;
function Da(a){g.onAbort?.(a);a="Aborted("+a+")";m(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ea=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),Fa;function Ga(a){if(a==Fa&&na)return new Uint8Array(na);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}function Ha(a){return na?Promise.resolve().then(()=>Ga(a)):ia(a).then(b=>new Uint8Array(b),()=>Ga(a))}
function Ia(a,b,c){return Ha(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{m(`failed to asynchronously prepare wasm: ${d}`);Da(d)})}function Ja(a,b){var c=Fa;na||"function"!=typeof WebAssembly.instantiateStreaming||Ea(c)||la(c)||ca||"function"!=typeof fetch?Ia(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){m(`wasm streaming compile failed: ${e}`);m("falling back to ArrayBuffer instantiation");return Ia(c,a,b)}))}
function Ka(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Aa=a=>{a.forEach(b=>b(g))},La=g.noExitRuntime||!0,B={},Ma=a=>{a instanceof Ka||"unwind"==a||ha(1,a)},Na=0,Oa=a=>{pa=a;La||0<Na||(g.onExit?.(a),p=!0);ha(a,new Ka(a))},Pa=a=>{pa=a;Oa(a)},Qa=()=>{if(!(La||0<Na))try{var a=pa;pa=a;Oa(a)}catch(b){Ma(b)}},Ra=a=>{if(!p)try{a(),Qa()}catch(b){Ma(b)}},Ya=(a,b)=>{Sa=a;Ta=b;if(C)if(Ua||=!0,0==a)D=function(){setTimeout(E,Math.max(0,Va+b-performance.now())|0)};else if(1==a)D=function(){Wa(E)};else if(2==a){if("undefined"==typeof Xa)if("undefined"==typeof setImmediate){var c=
[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Xa=d=>{c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Xa=setImmediate;D=function(){Xa(E)}}},gb=(a,b,c,d,e)=>{function h(){return f<Za?(Qa(),!1):!0}C=a;$a=d;var f=Za;Ua=!1;E=function(){if(!p)if(0<ab.length){var l=ab.shift();l.pd(l.dd);if(bb){var n=bb,
q=0==n%1?n-1:Math.floor(n);bb=l.gd?q:(8*n+(q+.5))/9}g.setStatus&&(l=g.statusMessage||"Please wait...",n=bb??0,q=cb.nd??0,n?n<q?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(l):g.setStatus(""));h()&&setTimeout(E,0)}else if(h())if(db=db+1|0,1==Sa&&1<Ta&&0!=db%Ta)D();else{0==Sa&&(Va=performance.now());a:if(!p){for(l of eb)if(!1===l())break a;Ra(a);for(n of fb)n()}h()&&D()}};e||(b&&0<b?Ya(0,1E3/b):Ya(1,1),D());if(c)throw"unwind";},Ua=!1,D=null,Za=0,C=null,$a=0,Sa=0,Ta=0,db=
0,ab=[],eb=[],fb=[];function hb(){D=null;Za++}var G=0;function Wa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===G)G=b+1E3/60;else for(;b+2>=G;)G+=1E3/60;setTimeout(a,Math.max(G-b,0))}}var cb={},Va,E,Xa,bb;function ib(a){var b=H.dc[a];b.target.removeEventListener(b.cc,b.Ic,b.ec);H.dc.splice(a,1)}function jb(){if(navigator.userActivation?navigator.userActivation.isActive:H.uc&&H.Vc.sc){var a=H.ic;H.ic=[];for(var b of a)b.xc(...b.Cc)}}
function I(a){if(!a.target)return-4;if(a.fc)a.Ic=function(c){++H.uc;H.Vc=a;jb();a.hc(c);jb();--H.uc},a.target.addEventListener(a.cc,a.Ic,a.ec),H.dc.push(a);else for(var b=0;b<H.dc.length;++b)H.dc[b].target==a.target&&H.dc[b].cc==a.cc&&ib(b--);return 0}function kb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var H={ed:0,qd:0,vc:0,qc:0,Bc:0,zc:0,tc:0,ld:0,td:0,kd:0,od:0,wc:0,Cd:0,yc:0,vd(){for(;H.dc.length;)ib(H.dc.length-1);H.ic=[]},uc:0,ic:[],jd(a,b,c){function d(h,f){if(h.length!=f.length)return!1;for(var l in h)if(h[l]!=f[l])return!1;return!0}for(var e of H.ic)if(e.xc==a&&d(e.Cc,c))return;H.ic.push({xc:a,Mc:b,Cc:c});H.ic.sort((h,f)=>h.Mc<f.Mc)},xd(a){H.ic=H.ic.filter(b=>b.xc!=a)},dc:[],wd:(a,b)=>{for(var c=0;c<H.dc.length;++c)H.dc[c].target!=a||b&&b!=H.dc[c].cc||ib(c--)},fullscreenEnabled(){return document.fullscreenEnabled||
document.webkitFullscreenEnabled}},lb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,J=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&lb)return lb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
mb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?J(t,a):"":a;return mb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},nb=a=>0>mb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},ob=[],pb,L=a=>{var b=ob[a];b||(a>=ob.length&&(ob.length=a+1),ob[a]=b=pb.get(a));return b},M=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var l=a.charCodeAt(++h);f=65536+
((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},qb=(a,b,c,d,e,h)=>{H.tc||(H.tc=N(256));a={target:K(a),cc:h,fc:d,hc:(f=event)=>{var l=f.target.id?f.target.id:"",n=H.tc;M(kb(f.target),n+0,128);M(l,n+128,128);L(d)(e,n,b)&&f.preventDefault()},ec:c};return I(a)},rb=(a,b,c,d,e,h)=>{H.vc||
(H.vc=N(160));a={target:K(a),cc:h,fc:d,hc:f=>{var l=H.vc;y[l>>3]=f.timeStamp;var n=l>>2;u[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;u[n+5]=f.charCode;u[n+6]=f.keyCode;u[n+7]=f.which;M(f.key||"",l+32,32);M(f.code||"",l+64,32);M(f.char||"",l+96,32);M(f.locale||"",l+128,32);L(d)(e,l,b)&&f.preventDefault()},ec:c};return I(a)},sb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+
24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;qa[2*d+14]=b.button;qa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=nb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,h)=>{H.qc||(H.qc=N(64));a=K(a);return I({target:a,sc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,cc:h,fc:d,hc:(f=event)=>{sb(H.qc,f,a);L(d)(e,H.qc,b)&&f.preventDefault()},ec:c})},tb=(a,b,c,d,e)=>{H.wc||(H.wc=N(257));return I({target:a,cc:e,fc:d,hc:(h=event)=>{var f=H.wc,
l=document.pointerLockElement||document.kc||document.Gc||document.Ec;r[f]=!!l;var n=l?.id||"";M(kb(l),f+1,128);M(n,f+129,128);L(d)(20,f,b)&&h.preventDefault()},ec:c})},ub=(a,b,c,d,e)=>I({target:a,cc:e,fc:d,hc:(h=event)=>{L(d)(38,0,b)&&h.preventDefault()},ec:c}),vb=(a,b,c,d)=>{H.zc||(H.zc=N(36));a=K(a);return I({target:a,cc:"resize",fc:d,hc:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=H.zc;u[f>>2]=0;u[f+4>>2]=h.clientWidth;u[f+8>>2]=h.clientHeight;u[f+12>>2]=innerWidth;u[f+16>>2]=innerHeight;
u[f+20>>2]=outerWidth;u[f+24>>2]=outerHeight;u[f+28>>2]=pageXOffset|0;u[f+32>>2]=pageYOffset|0;L(d)(10,f,b)&&e.preventDefault()}}},ec:c})},wb=(a,b,c,d,e,h)=>{H.yc||(H.yc=N(1552));a=K(a);return I({target:a,sc:"touchstart"==h||"touchend"==h,cc:h,fc:d,hc:f=>{var l={},n=f.touches;for(var q of n)q.Jc=q.Lc=0,l[q.identifier]=q;for(var w of f.changedTouches)w.Jc=1,l[w.identifier]=w;for(var ta of f.targetTouches)l[ta.identifier].Lc=1;n=H.yc;y[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=f.shiftKey;r[n+14]=
f.altKey;r[n+15]=f.metaKey;q=n+16;w=nb(a);ta=0;for(let F of Object.values(l))if(l=q>>2,u[l]=F.identifier,u[l+1]=F.screenX,u[l+2]=F.screenY,u[l+3]=F.clientX,u[l+4]=F.clientY,u[l+5]=F.pageX,u[l+6]=F.pageY,r[q+28]=F.Jc,r[q+29]=F.Lc,u[l+8]=F.clientX-(w.left|0),u[l+9]=F.clientY-(w.top|0),q+=48,31<++ta)break;u[n+8>>2]=ta;L(d)(e,n,b)&&f.preventDefault()},ec:c})},P,xb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},yb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},zb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Ab=a=>{a.md=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
Bb=a=>{a.rd=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Cb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Db=1,Q=[],R=[],Eb=[],Fb=[],Gb=[],S=[],Hb=[],Ib=[],T=[],Jb={},Kb=4,Lb=0,Mb=a=>{for(var b=Db++,c=a.length;c<b;c++)a[c]=null;return b},Nb=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=P[c](),f=h&&Mb(d);h?(h.name=f,d[f]=h):U||=1282;u[b+4*e>>2]=f}},Pb=(a,b)=>{a.kc||(a.kc=a.getContext,a.getContext=function(d,e){e=a.kc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Kc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?Ob(c,b):0},Ob=(a,b)=>{var c=Mb(Ib),d={handle:c,attributes:b,version:b.Kc,rc:a};a.canvas&&(a.canvas.cd=d);Ib[c]=d;("undefined"==typeof b.Hc||b.Hc)&&Qb(d);return c},Qb=a=>{a||=V;if(!a.$c){a.$c=!0;var b=a.rc;b.ad=b.getExtension("WEBGL_multi_draw");b.Zc=b.getExtension("EXT_polygon_offset_clamp");b.Yc=b.getExtension("EXT_clip_control");b.bd=b.getExtension("WEBGL_polygon_mode");xb(b);yb(b);zb(b);Ab(b);Bb(b);2<=a.version&&(b.Fc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||
!b.Fc)b.Fc=b.getExtension("EXT_disjoint_timer_query");Cb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},U,V,Rb=(a,b,c,d,e,h)=>{a={target:K(a),cc:h,fc:d,hc:(f=event)=>{L(d)(e,0,b)&&f.preventDefault()},ec:c};I(a)},Sb=(a,b,c,d)=>{H.Bc||(H.Bc=N(96));return I({target:a,sc:!0,cc:"wheel",fc:d,hc:(e=event)=>{var h=H.Bc;sb(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+80>>3]=e.deltaZ;u[h+88>>2]=e.deltaMode;L(d)(9,h,b)&&e.preventDefault()},ec:c})},Tb=["default","low-power",
"high-performance"],Ub=[null,[],[]];function Vb(){var a=Cb(P);return a=a.concat(a.map(b=>"GL_"+b))}
var Wb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=Vb().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=P.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else U||=1281},Xb=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Yb=a=>{var b=Xb(a)+1,c=N(b);c&&M(a,c,b);return c},Zb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),$b=[],ac=a=>{a-=5120;return 0==a?r:1==a?t:2==a?qa:4==a?u:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?v:ra},W=a=>{var b=P.Wc;if(b){var c=b.mc[a];"number"==typeof c&&(b.mc[a]=c=P.getUniformLocation(b,b.Tc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],bc=[],dc=a=>{var b=Xb(a)+
1,c=cc(b);M(a,c,b);return c},gc=a=>{var b=ec();a();fc(b)};g.requestAnimationFrame=Wa;g.pauseMainLoop=hb;g.resumeMainLoop=function(){Za++;var a=Sa,b=Ta,c=C;C=null;gb(c,0,!1,$a,!0);Ya(a,b);D()};g.preMainLoop&&eb.push(g.preMainLoop);g.postMainLoop&&fb.push(g.postMainLoop);for(var Y=0;32>Y;++Y)$b.push(Array(Y));var hc=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=hc.subarray(0,Y);var ic=new Int32Array(288);for(Y=0;288>=Y;++Y)bc[Y]=ic.subarray(0,Y);
var tc={eb:()=>{Da("")},bb:(a,b,c)=>t.copyWithin(a,b,b+c),_a:()=>{La=!1;Na=0},$a:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];Ra(()=>jc(a,performance.now()))},b);B[a]={id:c,Bd:b};return 0},Oa:()=>{hb();C=null},$:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ba:(a,b,c)=>{a=K(a);if(!a)return-4;a=nb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Pa:()=>performance.now(),Wa:(a,b)=>{function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
ab:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},J:(a,b,c,d)=>qb(a,b,c,d,12,"blur"),_:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},K:(a,b,c,d)=>qb(a,b,c,d,13,"focus"),T:(a,b,c,d)=>rb(a,b,c,d,2,"keydown"),R:(a,b,c,d)=>rb(a,b,c,d,1,"keypress"),
S:(a,b,c,d)=>rb(a,b,c,d,3,"keyup"),Xa:(a,b,c)=>{a=L(a);gb(a,b,c)},Z:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),W:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),V:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),X:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),Y:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),M:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.kc||document.body.Gc||document.body.Ec))return-1;a=K(a);if(!a)return-4;tb(a,b,c,d,"mozpointerlockchange");tb(a,b,c,d,"webkitpointerlockchange");tb(a,
b,c,d,"mspointerlockchange");return tb(a,b,c,d,"pointerlockchange")},L:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.kc||document.body.Gc||document.body.Ec))return-1;a=K(a);if(!a)return-4;ub(a,b,c,d,"mozpointerlockerror");ub(a,b,c,d,"webkitpointerlockerror");ub(a,b,c,d,"mspointerlockerror");return ub(a,b,c,d,"pointerlockerror")},aa:(a,b,c,d)=>vb(a,b,c,d),N:(a,b,c,d)=>wb(a,b,c,d,25,"touchcancel"),O:(a,b,c,d)=>wb(a,b,c,d,23,"touchend"),P:(a,b,c,d)=>wb(a,b,c,d,24,"touchmove"),
Q:(a,b,c,d)=>wb(a,b,c,d,22,"touchstart"),I:(a,b,c,d)=>{Rb(a,b,c,d,31,"webglcontextlost");return 0},H:(a,b,c,d)=>{Rb(a,b,c,d,32,"webglcontextrestored");return 0},U:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?Sb(a,b,c,d):-1:-4,Ua:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Tb[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Kc:u[c+4],sd:u[c+5],Hc:r[b+24],Xc:r[b+25],ud:u[c+7],yd:r[b+
32]};a=K(a);return!a||b.Xc?0:Pb(a,b)},Sa:(a,b)=>{a=Ib[a];b=b?J(t,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&xb(P);"OES_vertex_array_object"==b&&yb(P);"WEBGL_draw_buffers"==b&&zb(P);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Ab(P);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Bb(P);"WEBGL_multi_draw"==b&&(P.ad=P.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(P.Zc=P.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&
(P.Yc=P.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(P.bd=P.getExtension("WEBGL_polygon_mode"));return!!a.rc.getExtension(b)},Ta:a=>{V=Ib[a];g.hd=P=V?.rc;return!a||P?0:-5},cb:()=>52,Ya:function(){return 70},db:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var f=v[b>>2],l=v[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=t[f+n],w=Ub[a];0===q||10===q?((1===a?ma:m)(J(w)),w.length=0):w.push(q)}e+=l}v[d>>2]=e;return 0},i:a=>P.activeTexture(a),v:(a,b)=>{P.attachShader(R[a],S[b])},b:(a,b)=>{35051==a?P.Dc=
b:35052==a&&(P.jc=b);P.bindBuffer(a,Q[b])},a:(a,b,c)=>{P.bindBufferBase(a,b,Q[c])},m:(a,b)=>{P.bindFramebuffer(a,Eb[b])},xa:(a,b)=>{P.bindRenderbuffer(a,Fb[b])},h:(a,b)=>{P.bindSampler(a,T[b])},c:(a,b)=>{P.bindTexture(a,Gb[b])},G:a=>{P.bindVertexArray(Hb[a])},C:(a,b,c,d)=>P.blendColor(a,b,c,d),D:(a,b)=>P.blendEquationSeparate(a,b),E:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),gb:(a,b,c,d,e,h,f,l,n,q)=>P.blitFramebuffer(a,b,c,d,e,h,f,l,n,q),Aa:(a,b,c,d)=>{2<=V.version?c&&b?P.bufferData(a,t,d,c,b):P.bufferData(a,
b,d):P.bufferData(a,c?t.subarray(c,c+b):b,d)},x:(a,b,c,d)=>{2<=V.version?c&&P.bufferSubData(a,b,t,d,c):P.bufferSubData(a,b,t.subarray(d,d+c))},zb:(a,b,c,d)=>P.clearBufferfi(a,b,c,d),fa:(a,b,c)=>{P.clearBufferfv(a,b,x,c>>2)},yb:(a,b,c)=>{P.clearBufferiv(a,b,u,c>>2)},k:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},Eb:a=>{P.compileShader(S[a])},ra:(a,b,c,d,e,h,f,l)=>{2<=V.version?P.jc||!f?P.compressedTexImage2D(a,b,c,d,e,h,f,l):P.compressedTexImage2D(a,b,c,d,e,h,t,l,f):P.compressedTexImage2D(a,b,c,d,e,h,
t.subarray(l,l+f))},pa:(a,b,c,d,e,h,f,l,n)=>{P.jc?P.compressedTexImage3D(a,b,c,d,e,h,f,l,n):P.compressedTexImage3D(a,b,c,d,e,h,f,t,n,l)},la:()=>{var a=Mb(R),b=P.createProgram();b.name=a;b.pc=b.nc=b.oc=0;b.Ac=1;R[a]=b;return a},Gb:a=>{var b=Mb(S);S[b]=P.createShader(a);return b},z:a=>P.cullFace(a),Ga:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(P.deleteBuffer(e),e.name=0,Q[d]=null,d==P.Dc&&(P.Dc=0),d==P.jc&&(P.jc=0))}},j:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=Eb[d];e&&(P.deleteFramebuffer(e),
e.name=0,Eb[d]=null)}},y:a=>{if(a){var b=R[a];b?(P.deleteProgram(b),b.name=0,R[a]=null):U||=1281}},Ea:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Fb[d];e&&(P.deleteRenderbuffer(e),e.name=0,Fb[d]=null)}},Da:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=T[d];e&&(P.deleteSampler(e),e.name=0,T[d]=null)}},o:a=>{if(a){var b=S[a];b?(P.deleteShader(b),S[a]=null):U||=1281}},Fa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Gb[d];e&&(P.deleteTexture(e),e.name=0,Gb[d]=null)}},Ca:(a,b)=>{for(var c=
0;c<a;c++){var d=u[b+4*c>>2];P.deleteVertexArray(Hb[d]);Hb[d]=null}},s:a=>P.depthFunc(a),r:a=>{P.depthMask(!!a)},e:a=>P.disable(a),F:a=>{P.disableVertexAttribArray(a)},ib:(a,b,c)=>{P.drawArrays(a,b,c)},jb:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},kb:(a,b,c,d)=>{P.drawElements(a,b,c,d)},lb:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},g:a=>P.enable(a),vb:a=>{P.enableVertexAttribArray(a)},A:a=>P.frontFace(a),Ba:(a,b)=>{Nb(a,b,"createBuffer",Q)},ya:(a,b)=>{Nb(a,b,"createRenderbuffer",Fb)},ma:(a,
b)=>{Nb(a,b,"createSampler",T)},va:(a,b)=>{Nb(a,b,"createTexture",Gb)},Na:(a,b)=>{Nb(a,b,"createVertexArray",Hb)},Cb:(a,b)=>P.getAttribLocation(R[a],b?J(t,b):""),d:(a,b)=>Wb(a,b),ja:(a,b,c,d)=>{a=P.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},u:(a,b,c)=>{if(c)if(a>=Db)U||=1281;else if(a=R[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.pc){var d=P.getProgramParameter(a,35718);for(b=0;b<d;++b)a.pc=
Math.max(a.pc,P.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.pc}else if(35722==b){if(!a.nc)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.nc=Math.max(a.nc,P.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.nc}else if(35381==b){if(!a.oc)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.oc=Math.max(a.oc,P.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.oc}else u[c>>2]=P.getProgramParameter(a,b);else U||=1281},Db:(a,b,c,d)=>{a=P.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?
M(a,d,b):0;c&&(u[c>>2]=b)},ha:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(S[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=P.getShaderParameter(S[a],b):U||=1281},La:(a,b)=>{if(2>V.version)return U||=1282,0;var c=Jb[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Vb().map(Yb),c=Jb[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},n:(a,b)=>{b=b?J(t,b):"";if(a=R[a]){var c=
a,d=c.mc,e=c.Uc,h;if(!d){c.mc=d={};c.Tc={};var f=P.getProgramParameter(c,35718);for(h=0;h<f;++h){var l=P.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Zb(n);q=0<q?n.slice(0,q):n;var w=c.Ac;c.Ac+=l;e[q]=[l,w];for(n=0;n<l;++n)d[w]=n,c.Tc[w++]=q}}c=a.mc;d=0;e=b;h=Zb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Uc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else U||=1281;return-1},fb:(a,b,c)=>{for(var d=$b[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];P.invalidateFramebuffer(a,
d)},ka:a=>{a=R[a];P.linkProgram(a);a.mc=0;a.Uc={}},Ma:(a,b)=>{3317==a?Kb=b:3314==a&&(Lb=b);P.pixelStorei(a,b)},B:(a,b)=>P.polygonOffset(a,b),hb:a=>P.readBuffer(a),wa:(a,b,c,d,e)=>P.renderbufferStorageMultisample(a,b,c,d,e),w:(a,b,c)=>{P.samplerParameterf(T[a],b,c)},f:(a,b,c)=>{P.samplerParameteri(T[a],b,c)},Ab:(a,b,c,d)=>P.scissor(a,b,c,d),Fb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=v[c+4*h>>2])?J(t,f,d?v[d+4*h>>2]:void 0):"";e+=f}P.shaderSource(S[a],e)},Ja:(a,b,c)=>P.stencilFunc(a,b,c),ea:(a,
b,c,d)=>P.stencilFuncSeparate(a,b,c,d),q:a=>P.stencilMask(a),Ia:(a,b,c)=>P.stencilOp(a,b,c),da:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),qa:(a,b,c,d,e,h,f,l,n)=>{if(2<=V.version){if(P.jc){P.texImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var q=ac(l);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);P.texImage2D(a,b,c,d,e,h,f,l,q,n);return}}if(n){q=ac(l);var w=e*((Lb||d)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*q.BYTES_PER_ELEMENT+Kb-1&-Kb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),
n+w>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;P.texImage2D(a,b,c,d,e,h,f,l,n)},na:(a,b,c,d,e,h,f,l,n,q)=>{if(P.jc)P.texImage3D(a,b,c,d,e,h,f,l,n,q);else if(q){var w=ac(n);P.texImage3D(a,b,c,d,e,h,f,l,n,w,q>>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else P.texImage3D(a,b,c,d,e,h,f,l,n,null)},ua:(a,b,c)=>P.texParameteri(a,b,c),ta:(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),sa:(a,b,c,d,e,h)=>P.texStorage3D(a,b,c,d,e,h),ub:(a,b,c)=>{if(2<=V.version)b&&P.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=
X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);P.uniform1fv(W(a),d)}},ia:(a,b)=>{P.uniform1i(W(a),b)},qb:(a,b,c)=>{if(2<=V.version)b&&P.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=bc[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);P.uniform1iv(W(a),d)}},tb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);P.uniform2fv(W(a),d)}},
pb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=bc[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);P.uniform2iv(W(a),d)}},sb:(a,b,c)=>{if(2<=V.version)b&&P.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);P.uniform3fv(W(a),d)}},ob:(a,b,c)=>{if(2<=V.version)b&&P.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=
b){b*=3;for(var d=bc[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);P.uniform3iv(W(a),d)}},rb:(a,b,c)=>{if(2<=V.version)b&&P.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);P.uniform4fv(W(a),d)}},nb:(a,b,c)=>{if(2<=V.version)b&&P.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=bc[b],
e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);P.uniform4iv(W(a),d)}},mb:(a,b,c,d)=>{if(2<=V.version)b&&P.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=
h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(W(a),!!c,e)}},l:a=>{a=R[a];P.useProgram(a);P.Wc=a},wb:(a,b)=>{P.vertexAttribDivisor(a,b)},xb:(a,b,c,d,e,h)=>{P.vertexAttribPointer(a,b,c,!!d,e,h)},Bb:(a,b,c,d)=>P.viewport(a,b,c,d),Za:Oa,Jb:function(){g.Nc=a=>{0!=kc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Nc)},Va:function(){g.Sc=a=>{const b=a.clipboardData.getData("text");gc(()=>{const c=dc(b);lc(c)})};window.addEventListener("paste",
g.Sc)},Qa:function(a){g.zd=[];a=a?J(t,a):"";a=document.getElementById(a);g.Oc=b=>{b.stopPropagation();b.preventDefault()};g.Pc=b=>{b.stopPropagation();b.preventDefault()};g.Qc=b=>{b.stopPropagation();b.preventDefault()};g.Rc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Ad=c;mc(c.length);for(let e=0;e<c.length;e++)gc(()=>{const h=dc(c[e].name);nc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);oc(b.clientX,b.clientY,d)};a.addEventListener("dragenter",
g.Oc,!1);a.addEventListener("dragleave",g.Pc,!1);a.addEventListener("dragover",g.Qc,!1);a.addEventListener("drop",g.Rc,!1)},oa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},za:function(){document.exitPointerLock&&document.exitPointerLock()},Ha:function(a){a=a?J(t,a):"";g.lc=document.getElementById(a);g.lc||console.log("sokol_app.h: invalid target:"+a);g.lc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},
Ib:function(){window.removeEventListener("beforeunload",g.Nc)},Ra:function(){window.removeEventListener("paste",g.Sc)},Ka:function(a){a=a?J(t,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.Oc);a.removeEventListener("dragleave",g.Pc);a.removeEventListener("dragover",g.Qc);a.removeEventListener("drop",g.Rc)},p:function(){g.lc&&g.lc.requestPointerLock&&g.lc.requestPointerLock()},Hb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),
h=e.createImageData(a,b);h.data.set(t.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},t:function(a,b,c,d,e,h){b=b?J(t,b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const l=0<d;l&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!l){const n=
new Uint8Array(f.response),q=n.length;q<=h?(t.set(n,e),pc(a,d,q)):qc(a)}else rc(a,f.status)};f.send()},ga:function(a,b){b=b?J(t,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");sc(a,d)}else rc(a,c.status)};c.send()},ca:function(a,b){b=b?J(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},
Z=function(){function a(c){Z=c.exports;oa=Z.Kb;sa();pb=Z.Zb;va.unshift(Z.Lb);z--;g.monitorRunDependencies?.(z);0==z&&(null!==Ca&&(clearInterval(Ca),Ca=null),A&&(c=A,A=null,c()));return Z}var b={a:tc};z++;g.monitorRunDependencies?.(z);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return m(`Module.instantiateWasm callback failed with error: ${c}`),!1}Fa??=Ea("cgltf-sapp.wasm")?"cgltf-sapp.wasm":g.locateFile?g.locateFile("cgltf-sapp.wasm",k):k+"cgltf-sapp.wasm";Ja(b,function(c){a(c.instance)});
return{}}(),N=a=>(N=Z.Mb)(a),lc=g.__sapp_emsc_onpaste=a=>(lc=g.__sapp_emsc_onpaste=Z.Nb)(a),kc=g.__sapp_html5_get_ask_leave_site=()=>(kc=g.__sapp_html5_get_ask_leave_site=Z.Ob)(),mc=g.__sapp_emsc_begin_drop=a=>(mc=g.__sapp_emsc_begin_drop=Z.Pb)(a),nc=g.__sapp_emsc_drop=(a,b)=>(nc=g.__sapp_emsc_drop=Z.Qb)(a,b),oc=g.__sapp_emsc_end_drop=(a,b,c)=>(oc=g.__sapp_emsc_end_drop=Z.Rb)(a,b,c);g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,f,l)=>(g.__sapp_emsc_invoke_fetch_cb=Z.Sb)(a,b,c,d,e,h,f,l);
var uc=g._main=(a,b)=>(uc=g._main=Z.Tb)(a,b);g.__saudio_emsc_pull=a=>(g.__saudio_emsc_pull=Z.Ub)(a);
var sc=g.__sfetch_emsc_head_response=(a,b)=>(sc=g.__sfetch_emsc_head_response=Z.Vb)(a,b),pc=g.__sfetch_emsc_get_response=(a,b,c)=>(pc=g.__sfetch_emsc_get_response=Z.Wb)(a,b,c),rc=g.__sfetch_emsc_failed_http_status=(a,b)=>(rc=g.__sfetch_emsc_failed_http_status=Z.Xb)(a,b),qc=g.__sfetch_emsc_failed_buffer_too_small=a=>(qc=g.__sfetch_emsc_failed_buffer_too_small=Z.Yb)(a),jc=(a,b)=>(jc=Z._b)(a,b),fc=a=>(fc=Z.$b)(a),cc=a=>(cc=Z.ac)(a),ec=()=>(ec=Z.bc)(),vc,wc;A=function xc(){vc||yc();vc||(A=xc)};
function zc(a=[]){var b=uc;a.unshift(fa);var c=a.length,d=cc(4*(c+1)),e=d;a.forEach(f=>{v[e>>2]=dc(f);e+=4});v[e>>2]=0;try{var h=b(c,d);Pa(h)}catch(f){Ma(f)}}function yc(){var a=ea;function b(){if(!vc&&(vc=1,g.calledRun=1,!p)){Aa(va);Aa(wa);g.onRuntimeInitialized?.();Ac&&zc(a);var c=g.postRun;c&&("function"==typeof c&&(c=[c]),c.forEach(Ba));Aa(xa)}}if(!(0<z)){if(!wc&&(wc=1,ya(),0<z))return;g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Ac=!0;g.noInitialRun&&(Ac=!1);yc();
