
var d;d||(d=typeof Module !== 'undefined' ? Module : {});var g={},l;for(l in d)d.hasOwnProperty(l)&&(g[l]=d[l]);var r=[],aa="./this.program";function t(a,b){throw b;}var u=!1,v=!1,ba=!1,ca=!1;u="object"===typeof window;v="function"===typeof importScripts;ba="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ca=!u&&!ba&&!v;var x="",y,da,z,ea,fa;
if(ba)x=v?require("path").dirname(x)+"/":__dirname+"/",y=function(a,b){ea||(ea=require("fs"));fa||(fa=require("path"));a=fa.normalize(a);return ea.readFileSync(a,b?null:"utf8")},z=function(a){a=y(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),r=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=d),process.on("uncaughtException",function(a){if(!(a instanceof ha))throw a;}),process.on("unhandledRejection",
A),t=function(a){process.exit(a)},d.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=typeof read&&(y=function(a){return read(a)}),z=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?r=scriptArgs:"undefined"!=typeof arguments&&(r=arguments),"function"===typeof quit&&(t=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(u||v)v?x=self.location.href:"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src),x=0!==x.indexOf("blob:")?x.substr(0,x.lastIndexOf("/")+1):"",y=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(z=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
da=function(a,b,c){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)};d.print||console.log.bind(console);var B=d.printErr||console.warn.bind(console);for(l in g)g.hasOwnProperty(l)&&(d[l]=g[l]);g=null;d.arguments&&(r=d.arguments);d.thisProgram&&(aa=d.thisProgram);d.quit&&(t=d.quit);var C;d.wasmBinary&&(C=d.wasmBinary);var noExitRuntime;d.noExitRuntime&&(noExitRuntime=d.noExitRuntime);
"object"!==typeof WebAssembly&&A("no native wasm support detected");var ia,ja=!1;function assert(a,b){a||A("Assertion failed: "+b)}function ka(a){var b=d["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function la(a,b,c){var e={string:function(m){var q=0;if(null!==m&&void 0!==m&&0!==m){var p=(m.length<<2)+1;q=D(p);E(m,F,q,p)}return q},array:function(m){var q=D(m.length);ma.set(m,q);return q}};a=ka(a);var f=[],h=0;if(c)for(var k=0;k<c.length;k++){var n=e[b[k]];n?(0===h&&(h=na()),f[k]=n(c[k])):f[k]=c[k]}a.apply(null,f);0!==h&&oa(h)}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function G(a){if(a){for(var b=F,c=a+NaN,e=a;b[e]&&!(e>=c);)++e;if(16<e-a&&b.subarray&&pa)a=pa.decode(b.subarray(a,e));else{for(c="";a<e;){var f=b[a++];if(f&128){var h=b[a++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|h);else{var k=b[a++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|b[a++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}a=c}}else a="";return a}
function E(a,b,c,e){if(0<e){e=c+e-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var k=a.charCodeAt(++f);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=e)break;b[c++]=h}else{if(2047>=h){if(c+1>=e)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=e)break;b[c++]=224|h>>12}else{if(c+3>=e)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0}}
function qa(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}function ra(a){var b=qa(a)+1,c=D(b);E(a,ma,c,b);return c}var sa,ma,F,ta,H,I;
function ua(){var a=ia.buffer;sa=a;d.HEAP8=ma=new Int8Array(a);d.HEAP16=ta=new Int16Array(a);d.HEAP32=H=new Int32Array(a);d.HEAPU8=F=new Uint8Array(a);d.HEAPU16=new Uint16Array(a);d.HEAPU32=new Uint32Array(a);d.HEAPF32=new Float32Array(a);d.HEAPF64=I=new Float64Array(a)}var J,va=[],wa=[],xa=[],ya=[],za=[];wa.push({Jb:function(){Aa()}});function Ba(){var a=d.preRun.shift();va.unshift(a)}var K=0,Ca=null,L=null;d.preloadedImages={};d.preloadedAudios={};
function A(a){if(d.onAbort)d.onAbort(a);B(a);ja=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Da(a){var b=M;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ea(){return Da("data:application/octet-stream;base64,")}var M="clear-sapp.wasm";if(!Ea()){var Fa=M;M=d.locateFile?d.locateFile(Fa,x):x+Fa}
function Ga(){var a=M;try{if(a==M&&C)return new Uint8Array(C);if(z)return z(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function Ha(){if(!C&&(u||v)){if("function"===typeof fetch&&!Da("file://"))return fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ga()});if(da)return new Promise(function(a,b){da(M,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ga()})}
function N(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.Jb;"number"===typeof c?void 0===b.tb?J.get(c)():J.get(c)(b.tb):c(void 0===b.tb?null:b.tb)}}}var Ia=0;function Ja(){for(var a=O.length-1;0<=a;--a)Ka(a);O=[];P=[]}var P=[];function La(){if(Ia&&Ma.rb)for(var a=0;a<P.length;++a){var b=P[a];P.splice(a,1);--a;b.$b.apply(null,b.Ob)}}var O=[];function Ka(a){var b=O[a];b.target.removeEventListener(b.mb,b.Hb,b.nb);O.splice(a,1)}
function Q(a){function b(e){++Ia;Ma=a;La();a.pb(e);La();--Ia}if(a.ob)a.Hb=b,a.target.addEventListener(a.mb,b,a.nb),O.push(a),Na||(ya.push(Ja),Na=!0);else for(var c=0;c<O.length;++c)O[c].target==a.target&&O[c].mb==a.mb&&Ka(c--)}var Na,Ma,Oa,R,Pa,Qa,Ra,Sa,Ta=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function S(a){a=2<a?G(a):a;return Ta[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Ua(a){return 0>Ta.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function Va(a,b,c,e,f,h){Oa||(Oa=T(164));a={target:S(a),rb:!0,mb:h,ob:e,pb:function(k){var n=Oa,m=n>>2;H[m]=k.location;H[m+1]=k.ctrlKey;H[m+2]=k.shiftKey;H[m+3]=k.altKey;H[m+4]=k.metaKey;H[m+5]=k.repeat;H[m+6]=k.charCode;H[m+7]=k.keyCode;H[m+8]=k.which;E(k.key||"",F,n+36,32);E(k.code||"",F,n+68,32);E(k.char||"",F,n+100,32);E(k.locale||"",F,n+132,32);J.get(e)(f,n,b)&&k.preventDefault()},nb:c};Q(a)}
function Wa(a,b,c){a>>=2;H[a]=b.screenX;H[a+1]=b.screenY;H[a+2]=b.clientX;H[a+3]=b.clientY;H[a+4]=b.ctrlKey;H[a+5]=b.shiftKey;H[a+6]=b.altKey;H[a+7]=b.metaKey;ta[2*a+16]=b.button;ta[2*a+17]=b.buttons;H[a+9]=b.movementX;H[a+10]=b.movementY;c=Ua(c);H[a+11]=b.clientX-c.left;H[a+12]=b.clientY-c.top}function U(a,b,c,e,f,h){R||(R=T(64));a=S(a);Q({target:a,rb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,mb:h,ob:e,pb:function(k){k=k||event;Wa(R,k,a);J.get(e)(f,R,b)&&k.preventDefault()},nb:c})}
function Xa(a,b,c,e,f){Pa||(Pa=T(260));Q({target:a,mb:f,ob:e,pb:function(h){h=h||event;var k=Pa,n=document.pointerLockElement||document.yb||document.Ab||document.zb;H[k>>2]=!!n;var m=n&&n.id?n.id:"";E(n?n==window?"#window":n==screen?"#screen":n&&n.nodeName?n.nodeName:"":"",F,k+4,128);E(m,F,k+132,128);J.get(e)(20,k,b)&&h.preventDefault()},nb:c})}function Ya(a,b,c,e,f){Q({target:a,mb:f,ob:e,pb:function(h){h=h||event;J.get(e)(38,0,b)&&h.preventDefault()},nb:c})}
function Za(a,b,c,e){Qa||(Qa=T(36));a=S(a);Q({target:a,mb:"resize",ob:e,pb:function(f){f=f||event;if(f.target==a){var h=document.body;if(h){var k=Qa;H[k>>2]=f.detail;H[k+4>>2]=h.clientWidth;H[k+8>>2]=h.clientHeight;H[k+12>>2]=innerWidth;H[k+16>>2]=innerHeight;H[k+20>>2]=outerWidth;H[k+24>>2]=outerHeight;H[k+28>>2]=pageXOffset;H[k+32>>2]=pageYOffset;J.get(e)(10,k,b)&&f.preventDefault()}}},nb:c})}
function $a(a,b,c,e,f,h){Ra||(Ra=T(1684));a=S(a);Q({target:a,rb:"touchstart"==h||"touchend"==h,mb:h,ob:e,pb:function(k){for(var n={},m=k.touches,q=0;q<m.length;++q){var p=m[q];n[p.identifier]=p}m=k.changedTouches;for(q=0;q<m.length;++q)p=m[q],p.Lb=1,n[p.identifier]=p;m=k.targetTouches;for(q=0;q<m.length;++q)n[m[q].identifier].Mb=1;m=Ra;p=m>>2;H[p+1]=k.ctrlKey;H[p+2]=k.shiftKey;H[p+3]=k.altKey;H[p+4]=k.metaKey;p+=5;var bb=Ua(a),cb=0;for(q in n){var w=n[q];H[p]=w.identifier;H[p+1]=w.screenX;H[p+2]=
w.screenY;H[p+3]=w.clientX;H[p+4]=w.clientY;H[p+5]=w.pageX;H[p+6]=w.pageY;H[p+7]=w.Lb;H[p+8]=w.Mb;H[p+9]=w.clientX-bb.left;H[p+10]=w.clientY-bb.top;p+=13;if(31<++cb)break}H[m>>2]=cb;J.get(e)(f,m,b)&&k.preventDefault()},nb:c})}function ab(a,b,c,e,f,h){a={target:S(a),mb:h,ob:e,pb:function(k){k=k||event;J.get(e)(f,0,b)&&k.preventDefault()},nb:c};Q(a)}
function db(a,b,c,e){Sa||(Sa=T(96));Q({target:a,rb:!0,mb:"wheel",ob:e,pb:function(f){f=f||event;var h=Sa;Wa(h,f,a);I[h+64>>3]=f.deltaX;I[h+72>>3]=f.deltaY;I[h+80>>3]=f.deltaZ;H[h+88>>2]=f.deltaMode;J.get(e)(9,h,b)&&f.preventDefault()},nb:c})}
function eb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,e){b.vertexAttribDivisorANGLE(c,e)},a.drawArraysInstanced=function(c,e,f,h){b.drawArraysInstancedANGLE(c,e,f,h)},a.drawElementsInstanced=function(c,e,f,h,k){b.drawElementsInstancedANGLE(c,e,f,h,k)})}
function fb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function gb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,e){b.drawBuffersWEBGL(c,e)})}
function hb(a){a.Qb=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function ib(a){a.Tb=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function jb(a){a.Vb=a.getExtension("WEBGL_multi_draw")}var kb=1,lb=[],mb=[],nb=[],ob=[],pb=[],V=[],qb=[],rb={},sb={};function W(a){tb||(tb=a)}function ub(a){for(var b=kb++,c=a.length;c<b;c++)a[c]=null;return b}
function vb(a){a||(a=X);if(!a.Kb){a.Kb=!0;var b=a.sb;eb(b);fb(b);gb(b);hb(b);ib(b);b.Rb=b.getExtension("EXT_disjoint_timer_query");jb(b);(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var tb,X,wb=["default","low-power","high-performance"];
function xb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var e=Y.getParameter(34467);c=e?e.length:0;break;case 33309:if(2>X.version){W(1282);return}c=2*(Y.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>X.version){W(1280);return}c=33307==a?3:0}if(void 0===c)switch(e=Y.getParameter(a),typeof e){case "number":c=e;break;case "boolean":c=e?1:0;break;case "string":W(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:W(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)H[b+4*a>>2]=e[a];return}try{c=e.name|0}catch(f){W(1280);B("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:W(1280);B("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+e+" of type "+typeof e+"!");return}H[b>>2]=c}else W(1281)}
function Z(a){var b=qa(a)+1,c=T(b);E(a,F,c,b);return c}
var Y,Cb={y:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},Q:function(a,b,c){a=S(a);if(!a)return-4;a=Ua(a);I[b>>3]=a.width;I[c>>3]=a.height;return 0},T:function(a,b,c){F.copyWithin(a,b,b+c)},ia:function(a,b){function c(e){J.get(a)(e,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},U:function(a){a>>>=0;var b=F.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);e=Math.max(16777216,a,e);0<e%65536&&(e+=65536-e%65536);
a:{try{ia.grow(Math.min(2147483648,e)-sa.byteLength+65535>>>16);ua();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},x:function(a,b,c){a=S(a);if(!a)return-4;a.width=b;a.height=c;return 0},J:function(a,b,c,e){Va(a,b,c,e,2,"keydown");return 0},H:function(a,b,c,e){Va(a,b,c,e,1,"keypress");return 0},I:function(a,b,c,e){Va(a,b,c,e,3,"keyup");return 0},P:function(a,b,c,e){U(a,b,c,e,5,"mousedown");return 0},M:function(a,b,c,e){U(a,b,c,e,33,"mouseenter");return 0},L:function(a,b,c,e){U(a,b,c,e,
34,"mouseleave");return 0},N:function(a,b,c,e){U(a,b,c,e,8,"mousemove");return 0},O:function(a,b,c,e){U(a,b,c,e,6,"mouseup");return 0},C:function(a,b,c,e){if(!document||!document.body||!(document.body.requestPointerLock||document.body.yb||document.body.Ab||document.body.zb))return-1;a=S(a);if(!a)return-4;Xa(a,b,c,e,"pointerlockchange");Xa(a,b,c,e,"mozpointerlockchange");Xa(a,b,c,e,"webkitpointerlockchange");Xa(a,b,c,e,"mspointerlockchange");return 0},B:function(a,b,c,e){if(!document||!(document.body.requestPointerLock||
document.body.yb||document.body.Ab||document.body.zb))return-1;a=S(a);if(!a)return-4;Ya(a,b,c,e,"pointerlockerror");Ya(a,b,c,e,"mozpointerlockerror");Ya(a,b,c,e,"webkitpointerlockerror");Ya(a,b,c,e,"mspointerlockerror");return 0},wa:function(a,b,c,e){Za(a,b,c,e);return 0},D:function(a,b,c,e){$a(a,b,c,e,25,"touchcancel");return 0},E:function(a,b,c,e){$a(a,b,c,e,23,"touchend");return 0},F:function(a,b,c,e){$a(a,b,c,e,24,"touchmove");return 0},G:function(a,b,c,e){$a(a,b,c,e,22,"touchstart");return 0},
A:function(a,b,c,e){ab(a,b,c,e,31,"webglcontextlost");return 0},z:function(a,b,c,e){ab(a,b,c,e,32,"webglcontextrestored");return 0},K:function(a,b,c,e){a=S(a);return"undefined"!==typeof a.onwheel?(db(a,b,c,e),0):-1},r:function(a,b){b>>=2;b={alpha:!!H[b],depth:!!H[b+1],stencil:!!H[b+2],antialias:!!H[b+3],premultipliedAlpha:!!H[b+4],preserveDrawingBuffer:!!H[b+5],powerPreference:wb[H[b+6]],failIfMajorPerformanceCaveat:!!H[b+7],xb:H[b+8],Ub:H[b+9],wb:H[b+10],Ib:H[b+11],Wb:H[b+12],Xb:H[b+13]};a=S(a);
if(!a||b.Ib)b=0;else if(a=1<b.xb?a.getContext("webgl2",b):a.getContext("webgl",b)){var c=ub(qb),e={Sb:c,attributes:b,version:b.xb,sb:a};a.canvas&&(a.canvas.Nb=e);qb[c]=e;("undefined"===typeof b.wb||b.wb)&&vb(e);b=c}else b=0;return b},R:function(a,b){a=qb[a];b=G(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&eb(Y);"OES_vertex_array_object"==b&&fb(Y);"WEBGL_draw_buffers"==b&&gb(Y);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&hb(Y);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==
b&&ib(Y);"WEBGL_multi_draw"==b&&jb(Y);return!!a.sb.getExtension(b)},da:function(a){a>>=2;for(var b=0;14>b;++b)H[a+b]=0;H[a]=H[a+1]=H[a+3]=H[a+4]=H[a+8]=H[a+10]=1},S:function(a){X=qb[a];d.Pb=Y=X&&X.sb;return!a||Y?0:-5},b:function(a){Y.activeTexture(a)},g:function(a,b){35051==a?Y.ub=b:35052==a&&(Y.vb=b);Y.bindBuffer(a,lb[b])},d:function(a,b){Y.bindFramebuffer(a,nb[b])},a:function(a,b){Y.bindTexture(a,pb[b])},v:function(a){Y.bindVertexArray(V[a])},aa:function(a,b,c,e){Y.blendColor(a,b,c,e)},ba:function(a,
b){Y.blendEquationSeparate(a,b)},ca:function(a,b,c,e){Y.blendFuncSeparate(a,b,c,e)},h:function(a,b,c,e,f,h,k,n,m,q){Y.blitFramebuffer(a,b,c,e,f,h,k,n,m,q)},V:function(a){Y.clear(a)},q:function(a,b,c,e){Y.clearColor(a,b,c,e)},p:function(a){Y.clearDepth(a)},W:function(a){Y.clearStencil(a)},j:function(a,b,c,e){Y.colorMask(!!a,!!b,!!c,!!e)},Z:function(a){Y.cullFace(a)},na:function(a,b){for(var c=0;c<a;c++){var e=H[b+4*c>>2],f=lb[e];f&&(Y.deleteBuffer(f),f.name=0,lb[e]=null,e==Y.ub&&(Y.ub=0),e==Y.vb&&
(Y.vb=0))}},f:function(a,b){for(var c=0;c<a;++c){var e=H[b+4*c>>2],f=nb[e];f&&(Y.deleteFramebuffer(f),f.name=0,nb[e]=null)}},la:function(a){if(a){var b=mb[a];b?(Y.deleteProgram(b),b.name=0,mb[a]=null):W(1281)}},w:function(a,b){for(var c=0;c<a;c++){var e=H[b+4*c>>2],f=ob[e];f&&(Y.deleteRenderbuffer(f),f.name=0,ob[e]=null)}},ma:function(a,b){for(var c=0;c<a;c++){var e=H[b+4*c>>2],f=pb[e];f&&(Y.deleteTexture(f),f.name=0,pb[e]=null)}},ja:function(a,b){for(var c=0;c<a;c++){var e=H[b+4*c>>2];Y.deleteVertexArray(V[e]);
V[e]=null}},u:function(a){Y.depthFunc(a)},t:function(a){Y.depthMask(!!a)},e:function(a){Y.disable(a)},ga:function(a){Y.disableVertexAttribArray(a)},n:function(a){Y.enable(a)},_:function(a){Y.frontFace(a)},ha:function(a,b){for(var c=0;c<a;c++){var e=Y.createVertexArray(),f=e&&ub(V);e?(e.name=f,V[f]=e):W(1282);H[b+4*c>>2]=f}},c:function(a,b){xb(a,b)},pa:function(a){if(rb[a])return rb[a];switch(a){case 7939:var b=Y.getSupportedExtensions()||[];b=b.concat(b.map(function(e){return"GL_"+e}));b=Z(b.join(" "));
break;case 7936:case 7937:case 37445:case 37446:(b=Y.getParameter(a))||W(1280);b=Z(b);break;case 7938:b=Y.getParameter(7938);b=2<=X.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Z(b);break;case 35724:b=Y.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Z(b);break;default:return W(1280),0}return rb[a]=b},oa:function(a,b){if(2>X.version)return W(1282),0;var c=sb[a];if(c)return 0>
b||b>=c.length?(W(1281),0):c[b];switch(a){case 7939:return c=Y.getSupportedExtensions()||[],c=c.concat(c.map(function(e){return"GL_"+e})),c=c.map(function(e){return Z(e)}),c=sb[a]=c,0>b||b>=c.length?(W(1281),0):c[b];default:return W(1280),0}},$:function(a,b){Y.polygonOffset(a,b)},i:function(a){Y.readBuffer(a)},X:function(a,b,c,e){Y.scissor(a,b,c,e)},fa:function(a,b,c){Y.stencilFunc(a,b,c)},s:function(a){Y.stencilMask(a)},ea:function(a,b,c){Y.stencilOp(a,b,c)},ka:function(a){Y.useProgram(mb[a])},Y:function(a,
b,c,e){Y.viewport(a,b,c,e)},va:function(){d.Bb=function(a){0!=yb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",d.Bb)},ua:function(){d.Gb=function(a){a=a.clipboardData.getData("text");la("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",d.Gb)},ta:function(a){d.Yb=[];a=G(a);a=document.getElementById(a);d.Cb=function(b){b.stopPropagation();b.preventDefault()};d.Db=function(b){b.stopPropagation();b.preventDefault()};d.Eb=function(b){b.stopPropagation();
b.preventDefault()};d.Fb=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;d.Zb=c;zb(c.length);var e;for(e=0;e<c.length;e++)la("_sapp_emsc_drop",["number","string"],[e,c[e].name]);Ab(b.clientX,b.clientY)};a.addEventListener("dragenter",d.Cb,!1);a.addEventListener("dragleave",d.Db,!1);a.addEventListener("dragover",d.Eb,!1);a.addEventListener("drop",d.Fb,!1)},m:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize=
"none";a.addEventListener("focusout",function(){Bb()});document.body.append(a)},l:function(){document.getElementById("_sokol_app_input_element").focus()},xa:function(a){a=G(a);d.qb=document.getElementById(a);d.qb||console.log("sokol_app.h: invalid target:"+a);d.qb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},sa:function(){window.removeEventListener("beforeunload",d.Bb)},ra:function(){window.removeEventListener("paste",d.Gb)},qa:function(a){a=G(a);a=
document.getElementById(a);a.removeEventListener("dragenter",d.Cb);a.removeEventListener("dragleave",d.Db);a.removeEventListener("dragover",d.Eb);a.removeEventListener("drop",d.Fb)},o:function(){d.qb&&d.qb.requestPointerLock&&d.qb.requestPointerLock()},k:function(){document.getElementById("_sokol_app_input_element").blur()}};
(function(){function a(f){d.asm=f.exports;ia=d.asm.ya;ua();J=d.asm.lb;K--;d.monitorRunDependencies&&d.monitorRunDependencies(K);0==K&&(null!==Ca&&(clearInterval(Ca),Ca=null),L&&(f=L,L=null,f()))}function b(f){a(f.instance)}function c(f){return Ha().then(function(h){return WebAssembly.instantiate(h,e)}).then(f,function(h){B("failed to asynchronously prepare wasm: "+h);A(h)})}var e={a:Cb};K++;d.monitorRunDependencies&&d.monitorRunDependencies(K);if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(f){return B("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){return C||"function"!==typeof WebAssembly.instantiateStreaming||Ea()||Da("file://")||"function"!==typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(h){B("wasm streaming compile failed: "+h);B("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Aa=d.___wasm_call_ctors=function(){return(Aa=d.___wasm_call_ctors=d.asm.za).apply(null,arguments)},Bb=d.__sapp_emsc_notify_keyboard_hidden=function(){return(Bb=d.__sapp_emsc_notify_keyboard_hidden=d.asm.Aa).apply(null,arguments)};d.__sapp_emsc_onpaste=function(){return(d.__sapp_emsc_onpaste=d.asm.Ba).apply(null,arguments)};
var yb=d.__sapp_html5_get_ask_leave_site=function(){return(yb=d.__sapp_html5_get_ask_leave_site=d.asm.Ca).apply(null,arguments)},zb=d.__sapp_emsc_begin_drop=function(){return(zb=d.__sapp_emsc_begin_drop=d.asm.Da).apply(null,arguments)};d.__sapp_emsc_drop=function(){return(d.__sapp_emsc_drop=d.asm.Ea).apply(null,arguments)};var Ab=d.__sapp_emsc_end_drop=function(){return(Ab=d.__sapp_emsc_end_drop=d.asm.Fa).apply(null,arguments)};
d.__sapp_emsc_invoke_fetch_cb=function(){return(d.__sapp_emsc_invoke_fetch_cb=d.asm.Ga).apply(null,arguments)};d.___em_js__sapp_js_create_textfield=function(){return(d.___em_js__sapp_js_create_textfield=d.asm.Ha).apply(null,arguments)};d.___em_js__sapp_js_focus_textfield=function(){return(d.___em_js__sapp_js_focus_textfield=d.asm.Ia).apply(null,arguments)};d.___em_js__sapp_js_unfocus_textfield=function(){return(d.___em_js__sapp_js_unfocus_textfield=d.asm.Ja).apply(null,arguments)};
d.___em_js__sapp_js_add_beforeunload_listener=function(){return(d.___em_js__sapp_js_add_beforeunload_listener=d.asm.Ka).apply(null,arguments)};d.___em_js__sapp_js_remove_beforeunload_listener=function(){return(d.___em_js__sapp_js_remove_beforeunload_listener=d.asm.La).apply(null,arguments)};d.___em_js__sapp_js_add_clipboard_listener=function(){return(d.___em_js__sapp_js_add_clipboard_listener=d.asm.Ma).apply(null,arguments)};
d.___em_js__sapp_js_remove_clipboard_listener=function(){return(d.___em_js__sapp_js_remove_clipboard_listener=d.asm.Na).apply(null,arguments)};d.___em_js__sapp_js_write_clipboard=function(){return(d.___em_js__sapp_js_write_clipboard=d.asm.Oa).apply(null,arguments)};d.___em_js__sapp_js_add_dragndrop_listeners=function(){return(d.___em_js__sapp_js_add_dragndrop_listeners=d.asm.Pa).apply(null,arguments)};
d.___em_js__sapp_js_dropped_file_size=function(){return(d.___em_js__sapp_js_dropped_file_size=d.asm.Qa).apply(null,arguments)};d.___em_js__sapp_js_fetch_dropped_file=function(){return(d.___em_js__sapp_js_fetch_dropped_file=d.asm.Ra).apply(null,arguments)};d.___em_js__sapp_js_remove_dragndrop_listeners=function(){return(d.___em_js__sapp_js_remove_dragndrop_listeners=d.asm.Sa).apply(null,arguments)};
d.___em_js__sapp_js_pointer_init=function(){return(d.___em_js__sapp_js_pointer_init=d.asm.Ta).apply(null,arguments)};d.___em_js__sapp_js_request_pointerlock=function(){return(d.___em_js__sapp_js_request_pointerlock=d.asm.Ua).apply(null,arguments)};d.___em_js__sapp_js_exit_pointerlock=function(){return(d.___em_js__sapp_js_exit_pointerlock=d.asm.Va).apply(null,arguments)};d._main=function(){return(d._main=d.asm.Wa).apply(null,arguments)};
d.___em_js__stm_js_perfnow=function(){return(d.___em_js__stm_js_perfnow=d.asm.Xa).apply(null,arguments)};d.__saudio_emsc_pull=function(){return(d.__saudio_emsc_pull=d.asm.Ya).apply(null,arguments)};d.___em_js__saudio_js_init=function(){return(d.___em_js__saudio_js_init=d.asm.Za).apply(null,arguments)};d.___em_js__saudio_js_shutdown=function(){return(d.___em_js__saudio_js_shutdown=d.asm._a).apply(null,arguments)};
d.___em_js__saudio_js_sample_rate=function(){return(d.___em_js__saudio_js_sample_rate=d.asm.$a).apply(null,arguments)};d.___em_js__saudio_js_buffer_frames=function(){return(d.___em_js__saudio_js_buffer_frames=d.asm.ab).apply(null,arguments)};d.___em_js__sfetch_js_send_head_request=function(){return(d.___em_js__sfetch_js_send_head_request=d.asm.bb).apply(null,arguments)};d.___em_js__sfetch_js_send_get_request=function(){return(d.___em_js__sfetch_js_send_get_request=d.asm.cb).apply(null,arguments)};
d.__sfetch_emsc_head_response=function(){return(d.__sfetch_emsc_head_response=d.asm.db).apply(null,arguments)};d.__sfetch_emsc_get_response=function(){return(d.__sfetch_emsc_get_response=d.asm.eb).apply(null,arguments)};d.__sfetch_emsc_failed_http_status=function(){return(d.__sfetch_emsc_failed_http_status=d.asm.fb).apply(null,arguments)};d.__sfetch_emsc_failed_buffer_too_small=function(){return(d.__sfetch_emsc_failed_buffer_too_small=d.asm.gb).apply(null,arguments)};
var T=d._malloc=function(){return(T=d._malloc=d.asm.hb).apply(null,arguments)},na=d.stackSave=function(){return(na=d.stackSave=d.asm.ib).apply(null,arguments)},oa=d.stackRestore=function(){return(oa=d.stackRestore=d.asm.jb).apply(null,arguments)},D=d.stackAlloc=function(){return(D=d.stackAlloc=d.asm.kb).apply(null,arguments)},Db;function ha(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}L=function Eb(){Db||Fb();Db||(L=Eb)};
function Fb(a){function b(){if(!Db&&(Db=!0,d.calledRun=!0,!ja)){N(wa);N(xa);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(Gb){var c=a,e=d._main;c=c||[];var f=c.length+1,h=D(4*(f+1));H[h>>2]=ra(aa);for(var k=1;k<f;k++)H[(h>>2)+k]=ra(c[k-1]);H[(h>>2)+f]=0;try{var n=e(f,h);if(!noExitRuntime||0!==n){if(!noExitRuntime){if(d.onExit)d.onExit(n);ja=!0}t(n,new ha(n))}}catch(m){m instanceof ha||("unwind"==m?noExitRuntime=!0:((c=m)&&"object"===typeof m&&m.stack&&(c=[m,m.stack]),B("exception thrown: "+
c),t(1,m)))}finally{}}if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;)c=d.postRun.shift(),za.unshift(c);N(za)}}a=a||r;if(!(0<K)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Ba();N(va);0<K||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);b()},1)):b())}}d.run=Fb;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();
var Gb=!0;d.noInitialRun&&(Gb=!1);noExitRuntime=!0;Fb();
