var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,k="function"==typeof importScripts,ba="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ca=Object.assign({},e),da=[],ea="./this.program",fa=(a,b)=>{throw b;},l="",ha,p;
if(ba){var fs=require("fs"),ia=require("path");l=__dirname+"/";p=a=>{a=q(a)?new URL(a):ia.normalize(a);return fs.readFileSync(a)};ha=a=>{a=q(a)?new URL(a):ia.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,f)=>{d?c(d):b(f.buffer)})})};!e.thisProgram&&1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||k)k?l=self.location.href:"undefined"!=typeof document&&
document.currentScript&&(l=document.currentScript.src),l=l.startsWith("blob:")?"":l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1),k&&(p=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=a=>q(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));e.print||console.log.bind(console);var t=e.printErr||console.error.bind(console);Object.assign(e,ca);ca=null;e.arguments&&(da=e.arguments);e.thisProgram&&(ea=e.thisProgram);var ja=e.wasmBinary,ka,u=!1,la,v,x,ma,y,z,na,A;
function oa(){var a=ka.buffer;e.HEAP8=v=new Int8Array(a);e.HEAP16=ma=new Int16Array(a);e.HEAPU8=x=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAP32=y=new Int32Array(a);e.HEAPU32=z=new Uint32Array(a);e.HEAPF32=na=new Float32Array(a);e.HEAPF64=A=new Float64Array(a)}var qa=[],ra=[],sa=[],ta=[];function ua(){var a=e.preRun.shift();qa.unshift(a)}var B=0,va=null,C=null;
function wa(a){e.onAbort?.(a);a="Aborted("+a+")";t(a);u=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var xa=a=>a.startsWith("data:application/octet-stream;base64,"),q=a=>a.startsWith("file://"),ya;function za(a){if(a==ya&&ja)return new Uint8Array(ja);if(p)return p(a);throw"both async and sync fetching of the wasm failed";}function Aa(a){return ja?Promise.resolve().then(()=>za(a)):ha(a).then(b=>new Uint8Array(b),()=>za(a))}
function Ba(a,b,c){return Aa(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{t(`failed to asynchronously prepare wasm: ${d}`);wa(d)})}function Ca(a,b){var c=ya;ja||"function"!=typeof WebAssembly.instantiateStreaming||xa(c)||q(c)||ba||"function"!=typeof fetch?Ba(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(f){t(`wasm streaming compile failed: ${f}`);t("falling back to ArrayBuffer instantiation");return Ba(c,a,b)}))}
function Da(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Ea=a=>{for(;0<a.length;)a.shift()(e)},Fa=e.noExitRuntime||!0,D={},Ga=a=>{a instanceof Da||"unwind"==a||fa(1,a)},Ha=0,Ia=a=>{la=a;Fa||0<Ha||(e.onExit?.(a),u=!0);fa(a,new Da(a))},Ja=a=>{la=a;Ia(a)},Ka=()=>{if(!(Fa||0<Ha))try{var a=la;la=a;Ia(a)}catch(b){Ga(b)}},La=a=>{if(!u)try{a(),Ka()}catch(b){Ga(b)}},Ma;Ma=()=>performance.now();
var Ta=(a,b)=>{Na=a;Oa=b;if(E)if(Pa||=!0,0==a)F=function(){var d=Math.max(0,Qa+b-Ma())|0;setTimeout(G,d)};else if(1==a)F=function(){Ra(G)};else if(2==a){if("undefined"==typeof Sa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Sa=d=>{c.push(d);if(k){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate",
"*")}}else Sa=setImmediate;F=function(){Sa(G)}}},$a=(a,b,c,d,f)=>{function g(){return h<Ua?(Ka(),!1):!0}E=a;Va=d;var h=Ua;Pa=!1;G=function(){if(!u)if(0<Wa.length){var m=Wa.shift();m.Qb(m.Kb);if(Xa){var n=Xa,r=0==n%1?n-1:Math.floor(n);Xa=m.Mb?r:(8*n+(r+.5))/9}e.setStatus&&(m=e.statusMessage||"Please wait...",n=Xa,r=Ya.Pb,n?n<r?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(m):e.setStatus(""));g()&&setTimeout(G,0)}else g()&&(Za=Za+1|0,1==Na&&1<Oa&&0!=Za%Oa?F():(0==Na&&(Qa=
Ma()),u||e.preMainLoop&&!1===e.preMainLoop()||(La(a),e.postMainLoop?.()),g()&&("object"==typeof SDL&&SDL.audio?.Ub?.(),F())))};f||(b&&0<b?Ta(0,1E3/b):Ta(1,1),F());if(c)throw"unwind";},Pa=!1,F=null,Ua=0,E=null,Va=0,Na=0,Oa=0,Za=0,Wa=[];function ab(){F=null;Ua++}var Ya={},Qa,G,Xa,H=!1,bb=!1,cb=[];
function db(){function a(){bb=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}if(!eb){eb=!0;var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&b.addEventListener("click",c=>{!bb&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),c.preventDefault())},!1))}}var fb=!1,gb=void 0,I=void 0;
function hb(){if(!H)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var J=0;function Ra(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===J)J=b+1E3/60;else for(;b+2>=J;)J+=1E3/60;setTimeout(a,Math.max(J-b,0))}}var ib=[];function jb(){var a=e.canvas;ib.forEach(b=>b(a.width,a.height))}
function L(a,b,c){b&&c?(a.Ib=b,a.Eb=c):(b=a.Ib,c=a.Eb);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*
g)}I?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Sa,eb,kb=0,lb=[];
function mb(){if(navigator.userActivation?navigator.userActivation.isActive:kb&&nb.jb){var a=lb;lb=[];for(var b of a)b.Yb(...b.Lb)}}var M=[];function ob(a){var b=M[a];b.target.removeEventListener(b.bb,b.sb,b.cb);M.splice(a,1)}function N(a){if(!a.target)return-4;if(a.eb)a.sb=function(c){++kb;nb=a;mb();a.fb(c);mb();--kb},a.target.addEventListener(a.bb,a.sb,a.cb),M.push(a);else for(var b=0;b<M.length;++b)M[b].target==a.target&&M[b].bb==a.bb&&ob(b--);return 0}
function pb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var nb,qb,rb,sb,tb,ub,vb,wb,xb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,O=a=>{if(a){for(var b=x,c=a+NaN,d=a;b[d]&&!(d>=c);)++d;if(16<d-a&&b.buffer&&xb)a=xb.decode(b.subarray(a,d));else{for(c="";a<d;){var f=b[a++];if(f&128){var g=b[a++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var h=b[a++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|b[a++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}a=
c}}else a="";return a},yb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],P=a=>{a=2<a?O(a):a;return yb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},zb=a=>0>yb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Ab=[],Bb,Q=a=>{var b=Ab[a];b||(a>=Ab.length&&(Ab.length=a+1),Ab[a]=b=Bb.get(a));return b},R=(a,b,c)=>{var d=x;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&
1023)<<10)|h&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}},Cb=(a,b,c,d,f,g)=>{qb||=S(256);a={target:P(a),bb:g,eb:d,fb:(h=event)=>{var m=h.target.id?h.target.id:"",n=qb;R(pb(h.target),n+0,128);R(m,n+128,128);Q(d)(f,n,b)&&h.preventDefault()},cb:c};return N(a)},Db=(a,b,c,d,f,g)=>{rb||=S(160);a={target:P(a),
bb:g,eb:d,fb:h=>{var m=rb;A[m>>3]=h.timeStamp;var n=m>>2;y[n+2]=h.location;v[m+12]=h.ctrlKey;v[m+13]=h.shiftKey;v[m+14]=h.altKey;v[m+15]=h.metaKey;v[m+16]=h.repeat;y[n+5]=h.charCode;y[n+6]=h.keyCode;y[n+7]=h.which;R(h.key||"",m+32,32);R(h.code||"",m+64,32);R(h.char||"",m+96,32);R(h.locale||"",m+128,32);Q(d)(f,m,b)&&h.preventDefault()},cb:c};return N(a)},Eb=(a,b,c)=>{A[a>>3]=b.timeStamp;var d=a>>2;y[d+2]=b.screenX;y[d+3]=b.screenY;y[d+4]=b.clientX;y[d+5]=b.clientY;v[a+24]=b.ctrlKey;v[a+25]=b.shiftKey;
v[a+26]=b.altKey;v[a+27]=b.metaKey;ma[2*d+14]=b.button;ma[2*d+15]=b.buttons;y[d+8]=b.movementX;y[d+9]=b.movementY;a=zb(c);y[d+10]=b.clientX-(a.left|0);y[d+11]=b.clientY-(a.top|0)},T=(a,b,c,d,f,g)=>{sb||=S(64);a=P(a);return N({target:a,jb:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,bb:g,eb:d,fb:(h=event)=>{Eb(sb,h,a);Q(d)(f,sb,b)&&h.preventDefault()},cb:c})},Fb=(a,b,c,d,f)=>{tb||=S(257);return N({target:a,bb:f,eb:d,fb:(g=event)=>{var h=tb,m=document.pointerLockElement||document.gb||document.qb||
document.mb;v[h]=!!m;var n=m?.id||"";R(pb(m),h+1,128);R(n,h+129,128);Q(d)(20,h,b)&&g.preventDefault()},cb:c})},Gb=(a,b,c,d,f)=>N({target:a,bb:f,eb:d,fb:(g=event)=>{Q(d)(38,0,b)&&g.preventDefault()},cb:c}),Hb=(a,b,c,d)=>{ub||=S(36);a=P(a);return N({target:a,bb:"resize",eb:d,fb:(f=event)=>{if(f.target==a){var g=document.body;if(g){var h=ub;y[h>>2]=0;y[h+4>>2]=g.clientWidth;y[h+8>>2]=g.clientHeight;y[h+12>>2]=innerWidth;y[h+16>>2]=innerHeight;y[h+20>>2]=outerWidth;y[h+24>>2]=outerHeight;y[h+28>>2]=pageXOffset|
0;y[h+32>>2]=pageYOffset|0;Q(d)(10,h,b)&&f.preventDefault()}}},cb:c})},Ib=(a,b,c,d,f,g)=>{vb||=S(1552);a=P(a);return N({target:a,jb:"touchstart"==g||"touchend"==g,bb:g,eb:d,fb:h=>{var m={},n=h.touches;for(var r of n)r.tb=r.ub=0,m[r.identifier]=r;for(var K of h.changedTouches)K.tb=1,m[K.identifier]=K;for(var pa of h.targetTouches)m[pa.identifier].ub=1;n=vb;A[n>>3]=h.timeStamp;v[n+12]=h.ctrlKey;v[n+13]=h.shiftKey;v[n+14]=h.altKey;v[n+15]=h.metaKey;r=n+16;K=zb(a);pa=0;for(let w of Object.values(m))if(m=
r>>2,y[m]=w.identifier,y[m+1]=w.screenX,y[m+2]=w.screenY,y[m+3]=w.clientX,y[m+4]=w.clientY,y[m+5]=w.pageX,y[m+6]=w.pageY,v[r+28]=w.tb,v[r+29]=w.ub,y[m+8]=w.clientX-(K.left|0),y[m+9]=w.clientY-(K.top|0),r+=48,31<++pa)break;y[n+8>>2]=pa;Q(d)(f,n,b)&&h.preventDefault()},cb:c})},U,Jb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,f,g)=>b.drawArraysInstancedANGLE(c,d,f,g),a.drawElementsInstanced=(c,d,f,g,h)=>
b.drawElementsInstancedANGLE(c,d,f,g,h))},Kb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Lb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Mb=a=>{a.Ob=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},Nb=a=>{a.Rb=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},
Ob=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Pb=1,Qb=[],Rb=[],Sb=[],Tb=[],Ub=[],V=[],W=[],Vb=[],Wb={},Xb=a=>{for(var b=Pb++,c=a.length;c<b;c++)a[c]=null;return b},Zb=(a,b)=>{a.gb||(a.gb=a.getContext,a.getContext=function(d,f){f=a.gb(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=1<b.lb?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Yb(c,b):0},Yb=(a,b)=>{var c=Xb(W),d={handle:c,attributes:b,version:b.lb,ib:a};a.canvas&&(a.canvas.Jb=d);W[c]=d;
("undefined"==typeof b.rb||b.rb)&&$b(d);return c},ac=a=>{X=W[a];e.kb=U=X?.ib;return!(a&&!U)},$b=a=>{a||=X;if(!a.Fb){a.Fb=!0;var b=a.ib;b.Gb=b.getExtension("WEBGL_multi_draw");b.Db=b.getExtension("EXT_polygon_offset_clamp");b.Cb=b.getExtension("EXT_clip_control");b.Hb=b.getExtension("WEBGL_polygon_mode");Jb(b);Kb(b);Lb(b);Mb(b);Nb(b);2<=a.version&&(b.pb=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.pb)b.pb=b.getExtension("EXT_disjoint_timer_query");Ob(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},bc={},Y,X,cc=(a,b,c,d,f,g)=>{a={target:P(a),bb:g,eb:d,fb:(h=event)=>{Q(d)(f,0,b)&&h.preventDefault()},cb:c};N(a)},dc=(a,b,c,d)=>{wb||=S(96);return N({target:a,jb:!0,bb:"wheel",eb:d,fb:(f=event)=>{var g=wb;Eb(g,f,a);A[g+64>>3]=f.deltaX;A[g+72>>3]=f.deltaY;A[g+80>>3]=f.deltaZ;y[g+88>>2]=f.deltaMode;Q(d)(9,g,b)&&f.preventDefault()},cb:c})},ec=["default","low-power","high-performance"];function fc(){var a=Ob(U);return a=a.concat(a.map(b=>"GL_"+b))}
var gc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=U.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>X.version){Y||=1282;return}c=fc().length;break;case 33307:case 33308:if(2>X.version){Y||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=U.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:Y||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)y[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){Y||=1280;t(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:Y||=1280;t(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}y[b>>2]=c}else Y||=1281},hc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ic=a=>{var b=hc(a)+1,c=S(b);c&&R(a,c,b);return c},jc=[],lc=a=>{var b=hc(a)+1,c=kc(b);R(a,c,b);return c},oc=a=>{var b=mc();a();nc(b)};
e.requestFullscreen=function(a,b){function c(){H=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=hb,gb&&d.requestPointerLock(),H=!0,I?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>2]|8388608),L(e.canvas),jb()):L(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),I?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>
2]&-8388609),L(e.canvas),jb()):L(d));e.onFullScreen?.(H);e.onFullscreen?.(H)}gb=a;I=b;"undefined"==typeof gb&&(gb=!0);"undefined"==typeof I&&(I=!1);var d=e.canvas;fb||(fb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var f=document.createElement("div");d.parentNode.insertBefore(f,d);f.appendChild(d);f.requestFullscreen=f.requestFullscreen||
f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?()=>f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(f.webkitRequestFullScreen?()=>f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);f.requestFullscreen()};e.requestAnimationFrame=Ra;e.setCanvasSize=function(a,b,c){L(e.canvas,a,b);c||jb()};e.pauseMainLoop=ab;e.resumeMainLoop=function(){Ua++;var a=Na,b=Oa,c=E;E=null;$a(c,0,!1,Va,!0);Ta(a,b);F()};
e.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};e.createContext=function(a,b,c,d){if(b&&e.kb&&a==e.canvas)return e.kb;var f;if(b){var g={antialias:!1,alpha:!1,lb:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!=typeof bc&&(f=Zb(a,g)))var m=W[f].ib}else m=a.getContext("2d");if(!m)return null;c&&(e.kb=m,b&&ac(f),cb.forEach(n=>n()),db());return m};
for(var pc=0;32>pc;++pc)jc.push(Array(pc));
var wc={V:()=>{wa("")},T:(a,b,c)=>x.copyWithin(a,b,b+c),R:()=>{Fa=!1;Ha=0},S:(a,b)=>{D[a]&&(clearTimeout(D[a].id),delete D[a]);if(!b)return 0;var c=setTimeout(()=>{delete D[a];La(()=>qc(a,Ma()))},b);D[a]={id:c,Zb:b};return 0},xa:()=>{ab();E=null},L:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,N:(a,b,c)=>{a=P(a);if(!a)return-4;a=zb(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},ya:()=>performance.now(),Fa:(a,b)=>{function c(d){Q(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
U:a=>{var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ka.buffer.byteLength+65535)/65536;try{ka.grow(d);oa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},t:(a,b,c,d)=>Cb(a,b,c,d,12,"blur"),K:(a,b,c)=>{a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},u:(a,b,c,d)=>Cb(a,b,c,d,13,"focus"),D:(a,b,c,d)=>Db(a,b,c,d,2,"keydown"),B:(a,b,c,d)=>Db(a,b,c,d,1,"keypress"),
C:(a,b,c,d)=>Db(a,b,c,d,3,"keyup"),Ga:(a,b,c)=>{a=Q(a);$a(a,b,c)},J:(a,b,c,d)=>T(a,b,c,d,5,"mousedown"),G:(a,b,c,d)=>T(a,b,c,d,33,"mouseenter"),F:(a,b,c,d)=>T(a,b,c,d,34,"mouseleave"),H:(a,b,c,d)=>T(a,b,c,d,8,"mousemove"),I:(a,b,c,d)=>T(a,b,c,d,6,"mouseup"),w:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.gb||document.body.qb||document.body.mb))return-1;a=P(a);if(!a)return-4;Fb(a,b,c,d,"mozpointerlockchange");Fb(a,b,c,d,"webkitpointerlockchange");Fb(a,
b,c,d,"mspointerlockchange");return Fb(a,b,c,d,"pointerlockchange")},v:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.gb||document.body.qb||document.body.mb))return-1;a=P(a);if(!a)return-4;Gb(a,b,c,d,"mozpointerlockerror");Gb(a,b,c,d,"webkitpointerlockerror");Gb(a,b,c,d,"mspointerlockerror");return Gb(a,b,c,d,"pointerlockerror")},M:(a,b,c,d)=>Hb(a,b,c,d),x:(a,b,c,d)=>Ib(a,b,c,d,25,"touchcancel"),y:(a,b,c,d)=>Ib(a,b,c,d,23,"touchend"),z:(a,b,c,d)=>Ib(a,b,c,d,24,"touchmove"),
A:(a,b,c,d)=>Ib(a,b,c,d,22,"touchstart"),s:(a,b,c,d)=>{cc(a,b,c,d,31,"webglcontextlost");return 0},r:(a,b,c,d)=>{cc(a,b,c,d,32,"webglcontextrestored");return 0},E:(a,b,c,d)=>(a=P(a))?"undefined"!=typeof a.onwheel?dc(a,b,c,d):-1:-4,Ea:(a,b)=>{var c=b>>2;b={alpha:!!v[b+0],depth:!!v[b+1],stencil:!!v[b+2],antialias:!!v[b+3],premultipliedAlpha:!!v[b+4],preserveDrawingBuffer:!!v[b+5],powerPreference:ec[y[c+2]],failIfMajorPerformanceCaveat:!!v[b+12],lb:y[c+4],Sb:y[c+5],rb:v[b+24],Bb:v[b+25],Tb:y[c+7],Vb:v[b+
32]};a=P(a);return!a||b.Bb?0:Zb(a,b)},Ba:(a,b)=>{a=W[a];b=O(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Jb(U);"OES_vertex_array_object"==b&&Kb(U);"WEBGL_draw_buffers"==b&&Lb(U);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Mb(U);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Nb(U);"WEBGL_multi_draw"==b&&(U.Gb=U.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(U.Db=U.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&(U.Cb=
U.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(U.Hb=U.getExtension("WEBGL_polygon_mode"));return!!a.ib.getExtension(b)},Da:a=>ac(a)?0:-5,i:a=>U.activeTexture(a),d:(a,b)=>{35051==a?U.nb=b:35052==a&&(U.ob=b);U.bindBuffer(a,Qb[b])},a:(a,b,c)=>{U.bindBufferBase(a,b,Qb[c])},g:(a,b)=>{U.bindFramebuffer(a,Sb[b])},h:(a,b)=>{U.bindSampler(a,Vb[b])},c:(a,b)=>{U.bindTexture(a,Ub[b])},q:a=>{U.bindVertexArray(V[a])},na:(a,b,c,d)=>U.blendColor(a,b,c,d),oa:(a,b)=>U.blendEquationSeparate(a,b),pa:(a,
b,c,d)=>U.blendFuncSeparate(a,b,c,d),X:(a,b,c,d,f,g,h,m,n,r)=>U.blitFramebuffer(a,b,c,d,f,g,h,m,n,r),$:(a,b,c,d)=>U.clearBufferfi(a,b,c,d),m:(a,b,c)=>{U.clearBufferfv(a,b,na,c>>2)},_:(a,b,c)=>{U.clearBufferiv(a,b,y,c>>2)},j:(a,b,c,d)=>{U.colorMask(!!a,!!b,!!c,!!d)},ja:a=>U.cullFace(a),ia:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],f=Qb[d];f&&(U.deleteBuffer(f),f.name=0,Qb[d]=null,d==U.nb&&(U.nb=0),d==U.ob&&(U.ob=0))}},f:(a,b)=>{for(var c=0;c<a;++c){var d=y[b+4*c>>2],f=Sb[d];f&&(U.deleteFramebuffer(f),
f.name=0,Sb[d]=null)}},ea:a=>{if(a){var b=Rb[a];b?(U.deleteProgram(b),b.name=0,Rb[a]=null):Y||=1281}},ga:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],f=Tb[d];f&&(U.deleteRenderbuffer(f),f.name=0,Tb[d]=null)}},fa:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],f=Vb[d];f&&(U.deleteSampler(f),f.name=0,Vb[d]=null)}},ha:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],f=Ub[d];f&&(U.deleteTexture(f),f.name=0,Ub[d]=null)}},ca:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2];U.deleteVertexArray(V[d]);V[d]=null}},
p:a=>U.depthFunc(a),o:a=>{U.depthMask(!!a)},e:a=>U.disable(a),ta:a=>{U.disableVertexAttribArray(a)},l:a=>U.enable(a),la:a=>U.frontFace(a),wa:(a,b)=>{for(var c=0;c<a;c++){var d=U.createVertexArray(),f=d&&Xb(V);d?(d.name=f,V[f]=d):Y||=1282;y[b+4*c>>2]=f}},b:(a,b)=>gc(a,b),ua:(a,b)=>{if(2>X.version)return Y||=1282,0;var c=Wb[a];if(c)return 0>b||b>=c.length?(Y||=1281,0):c[b];switch(a){case 7939:return c=fc().map(ic),c=Wb[a]=c,0>b||b>=c.length?(Y||=1281,0):c[b];default:return Y||=1280,0}},W:(a,b,c)=>{for(var d=
jc[b],f=0;f<b;f++)d[f]=y[c+4*f>>2];U.invalidateFramebuffer(a,d)},va:(a,b)=>{U.pixelStorei(a,b)},ma:(a,b)=>U.polygonOffset(a,b),Y:a=>U.readBuffer(a),aa:(a,b,c,d)=>U.scissor(a,b,c,d),ra:(a,b,c)=>U.stencilFunc(a,b,c),n:a=>U.stencilMask(a),qa:(a,b,c)=>U.stencilOp(a,b,c),da:a=>{a=Rb[a];U.useProgram(a);U.Nb=a},ba:(a,b,c,d)=>U.viewport(a,b,c,d),Q:Ia,Ia:function(){e.vb=a=>{0!=rc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.vb)},Ca:function(){e.Ab=a=>{const b=a.clipboardData.getData("text");
oc(()=>{const c=lc(b);sc(c)})};window.addEventListener("paste",e.Ab)},za:function(a){e.Wb=[];a=O(a);a=document.getElementById(a);e.wb=b=>{b.stopPropagation();b.preventDefault()};e.xb=b=>{b.stopPropagation();b.preventDefault()};e.yb=b=>{b.stopPropagation();b.preventDefault()};e.zb=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Xb=c;tc(c.length);for(let f=0;f<c.length;f++)oc(()=>{const g=lc(c[f].name);uc(f,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);
b.metaKey&&(d|=8);vc(b.clientX,b.clientY,d)};a.addEventListener("dragenter",e.wb,!1);a.addEventListener("dragleave",e.xb,!1);a.addEventListener("dragover",e.yb,!1);a.addEventListener("drop",e.zb,!1)},Z:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},ka:function(a){a=O(a);e.hb=document.getElementById(a);e.hb||console.log("sokol_app.h: invalid target:"+a);e.hb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},
Ha:function(){window.removeEventListener("beforeunload",e.vb)},Aa:function(){window.removeEventListener("paste",e.Ab)},sa:function(a){a=O(a);a=document.getElementById(a);a.removeEventListener("dragenter",e.wb);a.removeEventListener("dragleave",e.xb);a.removeEventListener("dragover",e.yb);a.removeEventListener("drop",e.zb)},k:function(){e.hb&&e.hb.requestPointerLock&&e.hb.requestPointerLock()},P:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),
g=f.createImageData(a,b);g.data.set(x.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},O:function(a,b){b=O(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;ka=Z.Ja;oa();Bb=Z.Za;ra.unshift(Z.Ka);B--;e.monitorRunDependencies?.(B);0==B&&(null!==va&&(clearInterval(va),
va=null),C&&(c=C,C=null,c()));return Z}var b={a:wc};B++;e.monitorRunDependencies?.(B);if(e.instantiateWasm)try{return e.instantiateWasm(b,a)}catch(c){return t(`Module.instantiateWasm callback failed with error: ${c}`),!1}ya||=xa("clear-sapp.wasm")?"clear-sapp.wasm":e.locateFile?e.locateFile("clear-sapp.wasm",l):l+"clear-sapp.wasm";Ca(b,function(c){a(c.instance)});return{}}(),sc=e.__sapp_emsc_onpaste=a=>(sc=e.__sapp_emsc_onpaste=Z.La)(a),rc=e.__sapp_html5_get_ask_leave_site=()=>(rc=e.__sapp_html5_get_ask_leave_site=
Z.Ma)(),tc=e.__sapp_emsc_begin_drop=a=>(tc=e.__sapp_emsc_begin_drop=Z.Na)(a),uc=e.__sapp_emsc_drop=(a,b)=>(uc=e.__sapp_emsc_drop=Z.Oa)(a,b),vc=e.__sapp_emsc_end_drop=(a,b,c)=>(vc=e.__sapp_emsc_end_drop=Z.Pa)(a,b,c);e.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,f,g,h,m)=>(e.__sapp_emsc_invoke_fetch_cb=Z.Qa)(a,b,c,d,f,g,h,m);var xc=e._main=(a,b)=>(xc=e._main=Z.Ra)(a,b);e.__saudio_emsc_pull=a=>(e.__saudio_emsc_pull=Z.Sa)(a);e.__sfetch_emsc_head_response=(a,b)=>(e.__sfetch_emsc_head_response=Z.Ta)(a,b);
e.__sfetch_emsc_get_response=(a,b,c)=>(e.__sfetch_emsc_get_response=Z.Ua)(a,b,c);e.__sfetch_emsc_failed_http_status=(a,b)=>(e.__sfetch_emsc_failed_http_status=Z.Va)(a,b);e.__sfetch_emsc_failed_buffer_too_small=a=>(e.__sfetch_emsc_failed_buffer_too_small=Z.Wa)(a);var S=a=>(S=Z.Xa)(a),qc=(a,b)=>(qc=Z.Ya)(a,b),nc=a=>(nc=Z._a)(a),kc=a=>(kc=Z.$a)(a),mc=()=>(mc=Z.ab)(),yc;C=function zc(){yc||Ac();yc||(C=zc)};
function Bc(a=[]){var b=xc;a.unshift(ea);var c=a.length,d=kc(4*(c+1)),f=d;a.forEach(h=>{z[f>>2]=lc(h);f+=4});z[f>>2]=0;try{var g=b(c,d);Ja(g)}catch(h){Ga(h)}}
function Ac(){var a=da;function b(){if(!yc&&(yc=!0,e.calledRun=!0,!u)){Ea(ra);Ea(sa);e.onRuntimeInitialized?.();Cc&&Bc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();ta.unshift(c)}Ea(ta)}}if(!(0<B)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)ua();Ea(qa);0<B||(e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b())}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Cc=!0;e.noInitialRun&&(Cc=!1);Ac();
