var f;f||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},f),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,k="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,l="",ha,ia,ja;
if(fa){var fs=require("fs"),ka=require("path");l=k?ka.dirname(l)+"/":__dirname+"/";ha=(a,b)=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ja=a=>{a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a};ia=(a,b,c,d=!0)=>{a=la(a)?new URL(a):ka.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,h)=>{e?c(e):b(d?h.buffer:h)})};!f.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof ma||a.context instanceof ma))throw a;});da=(a,b)=>{process.exitCode=a;throw b;}}else if(ea||k)k?l=self.location.href:"undefined"!=typeof document&&document.currentScript&&(l=document.currentScript.src),l=l.startsWith("blob:")?"":l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1),ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},k&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);
return new Uint8Array(b.response)}),ia=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};f.print||console.log.bind(console);var p=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);f.thisProgram&&(ca=f.thisProgram);f.quit&&(da=f.quit);var q;f.wasmBinary&&(q=f.wasmBinary);"object"!=typeof WebAssembly&&na("no native wasm support detected");
var oa,r=!1,t,w,pa,y,z,A,B;function qa(){var a=oa.buffer;f.HEAP8=new Int8Array(a);f.HEAP16=pa=new Int16Array(a);f.HEAPU8=w=new Uint8Array(a);f.HEAPU16=new Uint16Array(a);f.HEAP32=y=new Int32Array(a);f.HEAPU32=z=new Uint32Array(a);f.HEAPF32=A=new Float32Array(a);f.HEAPF64=B=new Float64Array(a)}var ra=[],sa=[],ta=[],ua=[];function va(){var a=f.preRun.shift();ra.unshift(a)}var C=0,wa=null,D=null;
function na(a){f.onAbort?.(a);a="Aborted("+a+")";p(a);r=!0;t=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var xa=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),E;E="cube-sapp.wasm";if(!xa(E)){var ya=E;E=f.locateFile?f.locateFile(ya,l):l+ya}function za(a){if(a==E&&q)return new Uint8Array(q);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}
function Aa(a){if(!q&&(ea||k)){if("function"==typeof fetch&&!la(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>za(a));if(ia)return new Promise((b,c)=>{ia(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>za(a))}function Ba(a,b,c){return Aa(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{p(`failed to asynchronously prepare wasm: ${d}`);na(d)})}
function Ca(a,b){var c=E;q||"function"!=typeof WebAssembly.instantiateStreaming||xa(c)||la(c)||fa||"function"!=typeof fetch?Ba(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){p(`wasm streaming compile failed: ${e}`);p("falling back to ArrayBuffer instantiation");return Ba(c,a,b)}))}function ma(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Da=a=>{for(;0<a.length;)a.shift()(f)},Ea=f.noExitRuntime||!0,Ma=(a,b)=>{Fa=a;Ga=b;if(F)if(Ha||=!0,0==a)G=function(){var d=Math.max(0,Ia+b-Ja())|0;setTimeout(H,d)};else if(1==a)G=function(){Ka(H)};else if(2==a){if("undefined"==typeof La)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);La=function(d){c.push(d);k?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),
postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}else La=setImmediate;G=function(){La(H)}}},Ja;Ja=()=>performance.now();
var Ua=(a,b,c,d,e)=>{F=a;Na=d;var h=I;Ha=!1;H=function(){if(!r)if(0<Oa.length){var g=Oa.shift();g.xc(g.sc);if(Pa){var m=Pa,n=0==m%1?m-1:Math.floor(m);Pa=g.uc?n:(8*m+(n+.5))/9}f.setStatus&&(g=f.statusMessage||"Please wait...",m=Pa,n=Qa.wc,m?m<n?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(g):f.setStatus(""));h<I||setTimeout(H,0)}else if(!(h<I))if(Ra=Ra+1|0,1==Fa&&1<Ga&&0!=Ra%Ga)G();else{0==Fa&&(Ia=Ja());if(!(r||f.preMainLoop&&!1===f.preMainLoop())){if(!r)try{if(a(),!Ea)try{t=
g=t,Sa(g)}catch(u){Ta(u)}}catch(u){Ta(u)}f.postMainLoop?.()}h<I||("object"==typeof SDL&&SDL.audio?.Bc?.(),G())}};e||(b&&0<b?Ma(0,1E3/b):Ma(1,1),G());if(c)throw"unwind";},Ta=a=>{a instanceof ma||"unwind"==a||da(1,a)},Sa=a=>{t=a;Ea||(f.onExit?.(a),r=!0);da(a,new ma(a))},Va=a=>{t=a;Sa(a)},Ha=!1,G=null,I=0,F=null,Na=0,Fa=0,Ga=0,Ra=0,Oa=[];function Wa(){G=null;I++}var Qa={},Ia,H,Pa,Xa=!1,Ya=!1,Za=[];
function $a(){function a(){Ya=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!ab){ab=!0;var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!Ya&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}var bb=!1,cb=void 0,J=void 0;
function db(){if(!Xa)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var eb=0;function Ka(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===eb)eb=b+1E3/60;else for(;b+2>=eb;)eb+=1E3/60;setTimeout(a,Math.max(eb-b,0))}}var fb=[];function gb(){var a=f.canvas;fb.forEach(b=>b(a.width,a.height))}
function hb(a,b,c){b&&c?(a.qc=b,a.nc=c):(b=a.qc,c=a.nc);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var h=Math.min(screen.width/d,screen.height/e);d=Math.round(d*h);e=Math.round(e*
h)}J?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var La,ab,kb=a=>{var b=ib();a();jb(b)},lb=0,mb=[];
function nb(){if(navigator.userActivation?navigator.userActivation.isActive:lb&&ob.Qb)for(var a=0;a<mb.length;++a){var b=mb[a];mb.splice(a,1);--a;b.Fc(...b.tc)}}var K=[];function pb(a){var b=K[a];b.target.removeEventListener(b.Fb,b.$b,b.Gb);K.splice(a,1)}function L(a){if(!a.target)return-4;if(a.Hb)a.$b=function(c){++lb;ob=a;nb();a.Ib(c);nb();--lb},a.target.addEventListener(a.Fb,a.$b,a.Gb),K.push(a);else for(var b=0;b<K.length;++b)K[b].target==a.target&&K[b].Fb==a.Fb&&pb(b--);return 0}
function qb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var ob,rb,sb,tb,ub,vb,wb,xb,yb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,M=(a,b)=>{var c=w,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&yb)return yb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
zb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],N=a=>{a=2<a?a?M(a):"":a;return zb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Ab=a=>0>zb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Bb=[],Cb,O=a=>{var b=Bb[a];b||(a>=Bb.length&&(Bb.length=a+1),Bb[a]=b=Cb.get(a));return b},P=(a,b,c)=>{var d=w;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&
1023)<<10)|m&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},Db=(a,b,c,d,e,h)=>{rb||=Q(256);a={target:N(a),Fb:h,Hb:d,Ib:(g=event)=>{var m=g.target.id?g.target.id:"",n=rb;P(qb(g.target),n+0,128);P(m,n+128,128);O(d)(e,n,b)&&g.preventDefault()},Gb:c};return L(a)},Eb=(a,b,c,d,e,h)=>{sb||=Q(176);a={target:N(a),
Fb:h,Hb:d,Ib:g=>{var m=sb;B[m>>3]=g.timeStamp;var n=m>>2;y[n+2]=g.location;y[n+3]=g.ctrlKey;y[n+4]=g.shiftKey;y[n+5]=g.altKey;y[n+6]=g.metaKey;y[n+7]=g.repeat;y[n+8]=g.charCode;y[n+9]=g.keyCode;y[n+10]=g.which;P(g.key||"",m+44,32);P(g.code||"",m+76,32);P(g.char||"",m+108,32);P(g.locale||"",m+140,32);O(d)(e,m,b)&&g.preventDefault()},Gb:c};return L(a)},Fb=(a,b,c)=>{B[a>>3]=b.timeStamp;a>>=2;y[a+2]=b.screenX;y[a+3]=b.screenY;y[a+4]=b.clientX;y[a+5]=b.clientY;y[a+6]=b.ctrlKey;y[a+7]=b.shiftKey;y[a+8]=
b.altKey;y[a+9]=b.metaKey;pa[2*a+20]=b.button;pa[2*a+21]=b.buttons;y[a+11]=b.movementX;y[a+12]=b.movementY;c=Ab(c);y[a+13]=b.clientX-(c.left|0);y[a+14]=b.clientY-(c.top|0)},Gb=(a,b,c,d,e,h)=>{tb||=Q(72);a=N(a);return L({target:a,Qb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Fb:h,Hb:d,Ib:(g=event)=>{Fb(tb,g,a);O(d)(e,tb,b)&&g.preventDefault()},Gb:c})},Hb=(a,b,c,d,e)=>{ub||=Q(260);return L({target:a,Fb:e,Hb:d,Ib:(h=event)=>{var g=ub,m=document.pointerLockElement||document.Jb||document.Vb||document.Ub;
y[g>>2]=!!m;var n=m?.id||"";P(qb(m),g+4,128);P(n,g+132,128);O(d)(20,g,b)&&h.preventDefault()},Gb:c})},Ib=(a,b,c,d,e)=>L({target:a,Fb:e,Hb:d,Ib:(h=event)=>{O(d)(38,0,b)&&h.preventDefault()},Gb:c}),Jb=(a,b,c,d)=>{vb||=Q(36);a=N(a);return L({target:a,Fb:"resize",Hb:d,Ib:(e=event)=>{if(e.target==a){var h=document.body;if(h){var g=vb;y[g>>2]=0;y[g+4>>2]=h.clientWidth;y[g+8>>2]=h.clientHeight;y[g+12>>2]=innerWidth;y[g+16>>2]=innerHeight;y[g+20>>2]=outerWidth;y[g+24>>2]=outerHeight;y[g+28>>2]=pageXOffset|
0;y[g+32>>2]=pageYOffset|0;O(d)(10,g,b)&&e.preventDefault()}}},Gb:c})},Mb=(a,b,c,d,e,h)=>{wb||=Q(1696);a=N(a);return L({target:a,Qb:"touchstart"==h||"touchend"==h,Fb:h,Hb:d,Ib:g=>{for(var m,n={},u=g.touches,x=0;x<u.length;++x)m=u[x],m.ac=m.bc=0,n[m.identifier]=m;for(x=0;x<g.changedTouches.length;++x)m=g.changedTouches[x],m.ac=1,n[m.identifier]=m;for(x=0;x<g.targetTouches.length;++x)n[g.targetTouches[x].identifier].bc=1;u=wb;B[u>>3]=g.timeStamp;var v=u>>2;y[v+3]=g.ctrlKey;y[v+4]=g.shiftKey;y[v+5]=
g.altKey;y[v+6]=g.metaKey;v+=7;var Kb=Ab(a),Lb=0;for(x in n)if(m=n[x],y[v]=m.identifier,y[v+1]=m.screenX,y[v+2]=m.screenY,y[v+3]=m.clientX,y[v+4]=m.clientY,y[v+5]=m.pageX,y[v+6]=m.pageY,y[v+7]=m.ac,y[v+8]=m.bc,y[v+9]=m.clientX-(Kb.left|0),y[v+10]=m.clientY-(Kb.top|0),v+=13,31<++Lb)break;y[u+8>>2]=Lb;O(d)(e,u,b)&&g.preventDefault()},Gb:c})},Nb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,
d,e,h),a.drawElementsInstanced=(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,d,e,h,g))},Ob=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Pb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Qb=a=>{a.vc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
Rb=a=>{a.yc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Sb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Tb=1,Ub=[],R=[],Vb=[],Wb=[],Xb=[],S=[],Yb=[],Zb=[],$b=[],ac={},bc=a=>{for(var b=Tb++,c=a.length;c<b;c++)a[c]=null;return b},cc=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=T[c](),g=h&&bc(d);h?(h.name=g,d[g]=h):U||=1282;y[b+4*e>>2]=g}},ec=(a,b)=>{a.Jb||(a.Jb=a.getContext,a.getContext=function(d,e){e=a.Jb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Sb?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
dc(c,b):0},dc=(a,b)=>{var c=bc(Zb),d={handle:c,attributes:b,version:b.Sb,Mb:a};a.canvas&&(a.canvas.rc=d);Zb[c]=d;("undefined"==typeof b.Zb||b.Zb)&&fc(d);return c},gc=a=>{V=Zb[a];f.Rb=T=V?.Mb;return!(a&&!T)},fc=a=>{a||=V;if(!a.oc){a.oc=!0;var b=a.Mb;Nb(b);Ob(b);Pb(b);Qb(b);Rb(b);2<=a.version&&(b.Yb=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Yb)b.Yb=b.getExtension("EXT_disjoint_timer_query");b.pc=b.getExtension("WEBGL_multi_draw");Sb(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},hc={},U,V,ic=(a,b,c,d,e,h)=>{a={target:N(a),Fb:h,Hb:d,Ib:(g=event)=>{O(d)(e,0,b)&&g.preventDefault()},Gb:c};L(a)},jc=(a,b,c,d)=>{xb||=Q(104);return L({target:a,Qb:!0,Fb:"wheel",Hb:d,Ib:(e=event)=>{var h=xb;Fb(h,e,a);B[h+72>>3]=e.deltaX;B[h+80>>3]=e.deltaY;B[h+88>>3]=e.deltaZ;y[h+96>>2]=e.deltaMode;O(d)(9,h,b)&&e.preventDefault()},Gb:c})},kc=["default","low-power","high-performance"];function lc(){var a=Sb(T);return a=a.concat(a.map(b=>"GL_"+b))}
var mc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=T.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=lc().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=T.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)y[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;p(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;p(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}y[b>>2]=c}else U||=1281},nc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},oc=a=>{var b=nc(a)+1,c=Q(b);c&&P(a,c,b);return c},pc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),qc=[],W=a=>{var b=T.lc;if(b){var c=b.Lb[a];"number"==typeof c&&(b.Lb[a]=c=T.getUniformLocation(b,b.jc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],rc=[],tc=a=>{var b=nc(a)+1,c=sc(b);P(a,c,b);return c};
f.requestFullscreen=function(a,b){function c(){Xa=!1;var h=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===h?(d.exitFullscreen=db,cb&&d.requestPointerLock(),Xa=!0,J?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>2]|8388608),hb(f.canvas),gb()):hb(d)):(h.parentNode.insertBefore(d,h),h.parentNode.removeChild(h),J?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>
2]&-8388609),hb(f.canvas),gb()):hb(d));f.onFullScreen?.(Xa);f.onFullscreen?.(Xa)}cb=a;J=b;"undefined"==typeof cb&&(cb=!0);"undefined"==typeof J&&(J=!1);var d=f.canvas;bb||(bb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};f.requestAnimationFrame=Ka;f.setCanvasSize=function(a,b,c){hb(f.canvas,a,b);c||gb()};f.pauseMainLoop=Wa;f.resumeMainLoop=function(){I++;var a=Fa,b=Ga,c=F;F=null;Ua(c,0,!1,Na,!0);Ma(a,b);G()};
f.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};f.createContext=function(a,b,c,d){if(b&&f.Rb&&a==f.canvas)return f.Rb;var e;if(b){var h={antialias:!1,alpha:!1,Sb:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var g in d)h[g]=d[g];if("undefined"!=typeof hc&&(e=ec(a,h)))var m=Zb[e].Mb}else m=a.getContext("2d");if(!m)return null;c&&(f.Rb=m,b&&gc(e),f.Gc=b,Za.forEach(n=>n()),$a());return m};
for(var T,Y=0;32>Y;++Y)qc.push(Array(Y));var uc=new Float32Array(288);for(Y=0;288>Y;++Y)X[Y]=uc.subarray(0,Y+1);var vc=new Int32Array(288);for(Y=0;288>Y;++Y)rc[Y]=vc.subarray(0,Y+1);
var Bc={j:()=>{na("")},Ia:()=>{Wa();F=null},aa:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ca:(a,b,c)=>{a=N(a);if(!a)return-4;a=Ab(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},Sa:(a,b,c)=>w.copyWithin(a,b,b+c),Ja:()=>performance.now(),Qa:(a,b)=>{function c(d){O(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ta:a=>{var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,
2147483648,d+(65536-d%65536)%65536)-oa.buffer.byteLength+65535)/65536;try{oa.grow(e);qa();var h=1;break a}catch(g){}h=void 0}if(h)return!0}return!1},K:(a,b,c,d)=>Db(a,b,c,d,12,"blur"),$:(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},L:(a,b,c,d)=>Db(a,b,c,d,13,"focus"),U:(a,b,c,d)=>Eb(a,b,c,d,2,"keydown"),S:(a,b,c,d)=>Eb(a,b,c,d,1,"keypress"),T:(a,b,c,d)=>Eb(a,b,c,d,3,"keyup"),Ra:(a,b,c)=>{a=O(a);Ua(a,b,c)},_:(a,b,c,d)=>Gb(a,b,c,d,5,"mousedown"),X:(a,b,c,d)=>Gb(a,b,c,d,33,"mouseenter"),
W:(a,b,c,d)=>Gb(a,b,c,d,34,"mouseleave"),Y:(a,b,c,d)=>Gb(a,b,c,d,8,"mousemove"),Z:(a,b,c,d)=>Gb(a,b,c,d,6,"mouseup"),N:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Jb||document.body.Vb||document.body.Ub))return-1;a=N(a);if(!a)return-4;Hb(a,b,c,d,"mozpointerlockchange");Hb(a,b,c,d,"webkitpointerlockchange");Hb(a,b,c,d,"mspointerlockchange");return Hb(a,b,c,d,"pointerlockchange")},M:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.Jb||
document.body.Vb||document.body.Ub))return-1;a=N(a);if(!a)return-4;Ib(a,b,c,d,"mozpointerlockerror");Ib(a,b,c,d,"webkitpointerlockerror");Ib(a,b,c,d,"mspointerlockerror");return Ib(a,b,c,d,"pointerlockerror")},ba:(a,b,c,d)=>Jb(a,b,c,d),O:(a,b,c,d)=>Mb(a,b,c,d,25,"touchcancel"),P:(a,b,c,d)=>Mb(a,b,c,d,23,"touchend"),Q:(a,b,c,d)=>Mb(a,b,c,d,24,"touchmove"),R:(a,b,c,d)=>Mb(a,b,c,d,22,"touchstart"),J:(a,b,c,d)=>{ic(a,b,c,d,31,"webglcontextlost");return 0},I:(a,b,c,d)=>{ic(a,b,c,d,32,"webglcontextrestored");
return 0},V:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?jc(a,b,c,d):-1:-4,Pa:(a,b)=>{b>>=2;b={alpha:!!y[b],depth:!!y[b+1],stencil:!!y[b+2],antialias:!!y[b+3],premultipliedAlpha:!!y[b+4],preserveDrawingBuffer:!!y[b+5],powerPreference:kc[y[b+6]],failIfMajorPerformanceCaveat:!!y[b+7],Sb:y[b+8],zc:y[b+9],Zb:y[b+10],mc:y[b+11],Ac:y[b+12],Cc:y[b+13]};a=N(a);return!a||b.mc?0:ec(a,b)},Ma:(a,b)=>{a=Zb[a];b=b?M(b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Nb(T);"OES_vertex_array_object"==
b&&Ob(T);"WEBGL_draw_buffers"==b&&Pb(T);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Qb(T);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Rb(T);"WEBGL_multi_draw"==b&&(T.pc=T.getExtension("WEBGL_multi_draw"));return!!a.Mb.getExtension(b)},Oa:a=>gc(a)?0:-5,h:a=>T.activeTexture(a),y:(a,b)=>{T.attachShader(R[a],S[b])},a:(a,b)=>{35051==a?T.Wb=b:35052==a&&(T.Xb=b);T.bindBuffer(a,Ub[b])},k:(a,b)=>{T.bindFramebuffer(a,Vb[b])},g:(a,b)=>{T.bindSampler(a,$b[b])},d:(a,b)=>{T.bindTexture(a,
Xb[b])},H:a=>{T.bindVertexArray(Yb[a])},D:(a,b,c,d)=>T.blendColor(a,b,c,d),E:(a,b)=>T.blendEquationSeparate(a,b),F:(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),Va:(a,b,c,d,e,h,g,m,n,u)=>T.blitFramebuffer(a,b,c,d,e,h,g,m,n,u),ua:(a,b,c,d)=>{2<=V.version?c&&b?T.bufferData(a,w,d,c,b):T.bufferData(a,b,d):T.bufferData(a,c?w.subarray(c,c+b):b,d)},ta:(a,b,c,d)=>{2<=V.version?c&&T.bufferSubData(a,b,w,d,c):T.bufferSubData(a,b,w.subarray(d,d+c))},ga:(a,b,c,d)=>T.clearBufferfi(a,b,c,d),u:(a,b,c)=>{T.clearBufferfv(a,
b,A,c>>2)},fa:(a,b,c)=>{T.clearBufferiv(a,b,y,c>>2)},i:(a,b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},ma:a=>{T.compileShader(S[a])},sa:()=>{var a=bc(R),b=T.createProgram();b.name=a;b.Pb=b.Nb=b.Ob=0;b.Tb=1;R[a]=b;return a},oa:a=>{var b=bc(S);S[b]=T.createShader(a);return b},A:a=>T.cullFace(a),Aa:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=Ub[d];e&&(T.deleteBuffer(e),e.name=0,Ub[d]=null,d==T.Wb&&(T.Wb=0),d==T.Xb&&(T.Xb=0))}},f:(a,b)=>{for(var c=0;c<a;++c){var d=y[b+4*c>>2],e=Vb[d];e&&(T.deleteFramebuffer(e),
e.name=0,Vb[d]=null)}},z:a=>{if(a){var b=R[a];b?(T.deleteProgram(b),b.name=0,R[a]=null):U||=1281}},ya:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=Wb[d];e&&(T.deleteRenderbuffer(e),e.name=0,Wb[d]=null)}},xa:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=$b[d];e&&(T.deleteSampler(e),e.name=0,$b[d]=null)}},n:a=>{if(a){var b=S[a];b?(T.deleteShader(b),S[a]=null):U||=1281}},za:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=Xb[d];e&&(T.deleteTexture(e),e.name=0,Xb[d]=null)}},wa:(a,b)=>{for(var c=
0;c<a;c++){var d=y[b+4*c>>2];T.deleteVertexArray(Yb[d]);Yb[d]=null}},r:a=>T.depthFunc(a),q:a=>{T.depthMask(!!a)},c:a=>T.disable(a),G:a=>{T.disableVertexAttribArray(a)},Xa:(a,b,c)=>{T.drawArrays(a,b,c)},Ya:(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},Za:(a,b,c,d)=>{T.drawElements(a,b,c,d)},_a:(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},e:a=>T.enable(a),ib:a=>{T.enableVertexAttribArray(a)},B:a=>T.frontFace(a),va:(a,b)=>{cc(a,b,"createBuffer",Ub)},Ha:(a,b)=>{cc(a,b,"createVertexArray",Yb)},ja:(a,
b)=>T.getAttribLocation(R[a],b?M(b):""),b:(a,b)=>mc(a,b),pa:(a,b,c,d)=>{a=T.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?P(a,d,b):0;c&&(y[c>>2]=b)},x:(a,b,c)=>{if(c)if(a>=Tb)U||=1281;else if(a=R[a],35716==b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b){if(!a.Pb)for(b=0;b<T.getProgramParameter(a,35718);++b)a.Pb=Math.max(a.Pb,T.getActiveUniform(a,b).name.length+1);y[c>>2]=a.Pb}else if(35722==b){if(!a.Nb)for(b=0;b<T.getProgramParameter(a,
35721);++b)a.Nb=Math.max(a.Nb,T.getActiveAttrib(a,b).name.length+1);y[c>>2]=a.Nb}else if(35381==b){if(!a.Ob)for(b=0;b<T.getProgramParameter(a,35382);++b)a.Ob=Math.max(a.Ob,T.getActiveUniformBlockName(a,b).length+1);y[c>>2]=a.Ob}else y[c>>2]=T.getProgramParameter(a,b);else U||=1281},la:(a,b,c,d)=>{a=T.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?P(a,d,b):0;c&&(y[c>>2]=b)},v:(a,b,c)=>{c?35716==b?(a=T.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),y[c>>2]=a?a.length+1:0):35720==
b?(a=T.getShaderSource(S[a]),y[c>>2]=a?a.length+1:0):y[c>>2]=T.getShaderParameter(S[a],b):U||=1281},Fa:(a,b)=>{if(2>V.version)return U||=1282,0;var c=ac[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=lc().map(oc),c=ac[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},l:(a,b)=>{b=b?M(b):"";if(a=R[a]){var c=a,d=c.Lb,e=c.kc,h;if(!d)for(c.Lb=d={},c.jc={},h=0;h<T.getProgramParameter(c,35718);++h){var g=T.getActiveUniform(c,h);var m=g.name;g=g.size;var n=
pc(m);n=0<n?m.slice(0,n):m;var u=c.Tb;c.Tb+=g;e[n]=[g,u];for(m=0;m<g;++m)d[u]=m,c.jc[u++]=n}c=a.Lb;d=0;e=b;h=pc(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.kc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else U||=1281;return-1},Ua:(a,b,c)=>{for(var d=qc[b],e=0;e<b;e++)d[e]=y[c+4*e>>2];T.invalidateFramebuffer(a,d)},ra:a=>{a=R[a];T.linkProgram(a);a.Lb=0;a.kc={}},Ga:(a,b)=>{T.pixelStorei(a,b)},C:(a,b)=>T.polygonOffset(a,b),Wa:a=>T.readBuffer(a),ha:(a,b,c,d)=>
T.scissor(a,b,c,d),na:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var g=(g=z[c+4*h>>2])?M(g,d?z[d+4*h>>2]:void 0):"";e+=g}T.shaderSource(S[a],e)},Da:(a,b,c)=>T.stencilFunc(a,b,c),t:(a,b,c,d)=>T.stencilFuncSeparate(a,b,c,d),p:a=>T.stencilMask(a),Ca:(a,b,c)=>T.stencilOp(a,b,c),s:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),hb:(a,b,c)=>{if(2<=V.version)b&&T.uniform1fv(W(a),A,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);T.uniform1fv(W(a),d)}},w:(a,b)=>{T.uniform1i(W(a),
b)},db:(a,b,c)=>{if(2<=V.version)b&&T.uniform1iv(W(a),y,c>>2,b);else{if(288>=b)for(var d=rc[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);T.uniform1iv(W(a),d)}},gb:(a,b,c)=>{if(2<=V.version)b&&T.uniform2fv(W(a),A,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);T.uniform2fv(W(a),d)}},cb:(a,b,c)=>{if(2<=V.version)b&&T.uniform2iv(W(a),y,c>>2,2*b);else{if(144>=b)for(var d=rc[2*b-1],e=0;e<2*b;e+=2)d[e]=
y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);T.uniform2iv(W(a),d)}},fb:(a,b,c)=>{if(2<=V.version)b&&T.uniform3fv(W(a),A,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);T.uniform3fv(W(a),d)}},bb:(a,b,c)=>{if(2<=V.version)b&&T.uniform3iv(W(a),y,c>>2,3*b);else{if(96>=b)for(var d=rc[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=
y.subarray(c>>2,c+12*b>>2);T.uniform3iv(W(a),d)}},eb:(a,b,c)=>{if(2<=V.version)b&&T.uniform4fv(W(a),A,c>>2,4*b);else{if(72>=b){var d=X[4*b-1],e=A;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=A.subarray(c>>2,c+16*b>>2);T.uniform4fv(W(a),d)}},ab:(a,b,c)=>{if(2<=V.version)b&&T.uniform4iv(W(a),y,c>>2,4*b);else{if(72>=b)for(var d=rc[4*b-1],e=0;e<4*b;e+=4)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2],d[e+3]=y[c+(4*e+12)>>2];else d=
y.subarray(c>>2,c+16*b>>2);T.uniform4iv(W(a),d)}},$a:(a,b,c,d)=>{if(2<=V.version)b&&T.uniformMatrix4fv(W(a),!!c,A,d>>2,16*b);else{if(18>=b){var e=X[16*b-1],h=A;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=h[m+13];e[g+14]=h[m+14];e[g+15]=h[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);T.uniformMatrix4fv(W(a),!!c,e)}},
m:a=>{a=R[a];T.useProgram(a);T.lc=a},jb:(a,b)=>{T.vertexAttribDivisor(a,b)},ea:(a,b,c,d,e,h)=>{T.vertexAttribPointer(a,b,c,!!d,e,h)},ia:(a,b,c,d)=>T.viewport(a,b,c,d),lb:function(){f.cc=a=>{0!=wc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.cc)},Na:function(){f.ic=a=>{const b=a.clipboardData.getData("text");kb(()=>{const c=tc(b);xc(c)})};window.addEventListener("paste",f.ic)},Ka:function(a){f.Dc=[];a=a?M(a):"";a=document.getElementById(a);f.dc=b=>{b.stopPropagation();
b.preventDefault()};f.ec=b=>{b.stopPropagation();b.preventDefault()};f.fc=b=>{b.stopPropagation();b.preventDefault()};f.hc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Ec=c;yc(c.length);for(let e=0;e<c.length;e++)kb(()=>{const h=tc(c[e].name);zc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Ac(b.clientX,b.clientY,d)};a.addEventListener("dragenter",f.dc,!1);a.addEventListener("dragleave",f.ec,!1);a.addEventListener("dragover",f.fc,
!1);a.addEventListener("drop",f.hc,!1)},qa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ba:function(a){a=a?M(a):"";f.Kb=document.getElementById(a);f.Kb||console.log("sokol_app.h: invalid target:"+a);f.Kb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},kb:function(){window.removeEventListener("beforeunload",f.cc)},La:function(){window.removeEventListener("paste",f.ic)},Ea:function(a){a=a?M(a):"";a=document.getElementById(a);
a.removeEventListener("dragenter",f.dc);a.removeEventListener("dragleave",f.ec);a.removeEventListener("dragover",f.fc);a.removeEventListener("drop",f.hc)},o:function(){f.Kb&&f.Kb.requestPointerLock&&f.Kb.requestPointerLock()},ka:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(w.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=
d.toDataURL();document.head.appendChild(a)},da:function(a,b){b=b?M(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;oa=Z.mb;qa();Cb=Z.Bb;sa.unshift(Z.nb);C--;f.monitorRunDependencies?.(C);0==C&&(null!==wa&&(clearInterval(wa),wa=null),D&&(c=D,D=null,c()));return Z}var b={a:Bc};C++;f.monitorRunDependencies?.(C);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return p(`Module.instantiateWasm callback failed with error: ${c}`),
!1}Ca(b,function(c){a(c.instance)});return{}}(),xc=f.__sapp_emsc_onpaste=a=>(xc=f.__sapp_emsc_onpaste=Z.ob)(a),wc=f.__sapp_html5_get_ask_leave_site=()=>(wc=f.__sapp_html5_get_ask_leave_site=Z.pb)(),yc=f.__sapp_emsc_begin_drop=a=>(yc=f.__sapp_emsc_begin_drop=Z.qb)(a),zc=f.__sapp_emsc_drop=(a,b)=>(zc=f.__sapp_emsc_drop=Z.rb)(a,b),Ac=f.__sapp_emsc_end_drop=(a,b,c)=>(Ac=f.__sapp_emsc_end_drop=Z.sb)(a,b,c);
f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,g,m)=>(f.__sapp_emsc_invoke_fetch_cb=Z.tb)(a,b,c,d,e,h,g,m);var Cc=f._main=(a,b)=>(Cc=f._main=Z.ub)(a,b);f.__saudio_emsc_pull=a=>(f.__saudio_emsc_pull=Z.vb)(a);f.__sfetch_emsc_head_response=(a,b)=>(f.__sfetch_emsc_head_response=Z.wb)(a,b);f.__sfetch_emsc_get_response=(a,b,c)=>(f.__sfetch_emsc_get_response=Z.xb)(a,b,c);f.__sfetch_emsc_failed_http_status=(a,b)=>(f.__sfetch_emsc_failed_http_status=Z.yb)(a,b);
f.__sfetch_emsc_failed_buffer_too_small=a=>(f.__sfetch_emsc_failed_buffer_too_small=Z.zb)(a);var Q=a=>(Q=Z.Ab)(a),ib=()=>(ib=Z.Cb)(),jb=a=>(jb=Z.Db)(a),sc=a=>(sc=Z.Eb)(a);f.___start_em_js=7704;f.___stop_em_js=16925;var Dc;D=function Ec(){Dc||Fc();Dc||(D=Ec)};function Gc(a=[]){var b=Cc;a.unshift(ca);var c=a.length,d=sc(4*(c+1)),e=d;a.forEach(g=>{z[e>>2]=tc(g);e+=4});z[e>>2]=0;try{var h=b(c,d);Va(h)}catch(g){Ta(g)}}
function Fc(){var a=ba;function b(){if(!Dc&&(Dc=!0,f.calledRun=!0,!r)){Da(sa);Da(ta);if(f.onRuntimeInitialized)f.onRuntimeInitialized();Hc&&Gc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();ua.unshift(c)}Da(ua)}}if(!(0<C)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)va();Da(ra);0<C||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},
1)):b())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Hc=!0;f.noInitialRun&&(Hc=!1);Fc();
