var f;f||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,h=!!globalThis.WorkerGlobalScope,ba=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,ca=[],da="./this.program",ea=(a,b)=>{throw b;},fa=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?fa=__filename:h&&(fa=self.location.href);var ha="",ia,ja;
if(ba){var fs=require("fs");ha=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));ca=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);ea=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||h){try{ha=(new URL(".",fa)).href}catch{}h&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var n=console.error.bind(console),p,r=!1,la,ka=a=>a.startsWith("file://"),u,v,ma,na,w,x,oa,y;
function pa(){var a=qa.buffer;u=new Int8Array(a);ma=new Int16Array(a);v=new Uint8Array(a);na=new Uint16Array(a);w=new Int32Array(a);x=new Uint32Array(a);oa=new Float32Array(a);y=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function ra(a){f.onAbort?.(a);a="Aborted("+a+")";n(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var sa;
async function ta(a){if(!p)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==sa&&p)a=new Uint8Array(p);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}async function ua(a,b){try{var c=await ta(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),ra(d)}}
async function va(a){var b=sa;if(!p&&!ka(b)&&!ba)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return ua(b,a)}class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var xa=a=>{for(;0<a.length;)a.shift()(f)},ya=[],za=[],Aa=()=>{var a=f.preRun.shift();za.push(a)},A=0,B=null,Ba=!0,Ca=0,C={},Da=a=>{a instanceof wa||"unwind"==a||ea(1,a)},Ea=a=>{la=a;Ba||0<Ca||(f.onExit?.(a),r=!0);ea(a,new wa(a))},Fa=a=>{la=a;Ea(a)},Ga=()=>{if(!(Ba||0<Ca))try{var a=la;la=a;Ea(a)}catch(b){Da(b)}},Ha=a=>{if(!r)try{a(),Ga()}catch(b){Da(b)}},Oa=(a,b)=>{Ia=a;Ja=b;if(D)if(Ka||=!0,0==a)E=function(){setTimeout(F,Math.max(0,La+b-performance.now())|0)};else if(1==a)E=function(){Ma(F)};else if(2==
a){if(!Na)if(globalThis.setImmediate)Na=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Na=d=>{c.push(d);if(h){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}E=function(){Na(F)}}},Xa=(a,b,c,d,e)=>{function k(){return g<Pa?(Ga(),!1):!0}D=a;Qa=d;var g=Pa;Ka=!1;F=function(){if(!r)if(0<Ra.length){var l=
Ra.shift();l.kd(l.Xc);if(Sa){var m=Sa,q=0==m%1?m-1:Math.floor(m);Sa=l.$c?q:(8*m+(q+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",m=Sa??0,q=Ta.gd??0,m?m<q?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));k()&&setTimeout(F,0)}else if(k())if(Ua=Ua+1|0,1==Ia&&1<Ja&&0!=Ua%Ja)E();else{0==Ia&&(La=performance.now());a:if(!r){for(l of Va)if(!1===l())break a;Ha(a);for(m of Wa)m()}k()&&E()}};e||(0<b?Oa(0,1E3/b):Oa(1,1),E());if(c)throw"unwind";},Ka=!1,E=
null,Pa=0,D=null,Qa=0,Ia=0,Ja=0,Ua=0,Ra=[],Va=[],Wa=[];function Ya(){E=null;Pa++}var G=0;function Ma(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===G)G=b+1E3/60;else for(;b+2>=G;)G+=1E3/60;setTimeout(a,Math.max(G-b,0))}}
var Ta={},La,F,Na,Sa,Za=globalThis.TextDecoder&&new TextDecoder,H=(a=0,b)=>{var c=v;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&Za)return Za.decode(c.subarray(a,d));for(b="";a<d;){var e=c[a++];if(e&128){var k=c[a++]&63;if(192==(e&224))b+=String.fromCharCode((e&31)<<6|k);else{var g=c[a++]&63;e=224==(e&240)?(e&15)<<12|k<<6|g:(e&7)<<18|k<<12|g<<6|c[a++]&63;65536>e?b+=String.fromCharCode(e):(e-=65536,b+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else b+=String.fromCharCode(e)}return b},
$a=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],I=a=>{a=2<a?a?H(a):"":a;return $a[a]||("undefined"!=typeof document?document.querySelector(a):null)},ab=a=>0>$a.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},bb=[],J=a=>{var b=bb[a];b||(bb[a]=b=cb.get(a));return b};function db(a){var b=L.$b[a];b.target.removeEventListener(b.Zb,b.Ec,b.ac);L.$b.splice(a,1)}
function eb(){if(navigator.userActivation?navigator.userActivation.isActive:L.qc&&L.Rc.nc){var a=L.ec;L.ec=[];for(var b of a)b.tc(...b.Ac)}}function M(a){if(!a.target)return-4;if(a.bc)a.Ec=function(c){++L.qc;L.Rc=a;eb();a.cc(c);eb();--L.qc},a.target.addEventListener(a.Zb,a.Ec,a.ac),L.$b.push(a);else for(var b=0;b<L.$b.length;++b)L.$b[b].target==a.target&&L.$b[b].Zb==a.Zb&&db(b--);return 0}function fb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var L={Yc:0,ld:0,rc:0,lc:0,xc:0,vc:0,oc:0,dd:0,qd:0,cd:0,pc:0,sc:0,zd:0,uc:0,nd(a,b,c){u.set(u.subarray(b,b+c),a)},sd(){for(;L.$b.length;)db(L.$b.length-1);L.ec=[]},qc:0,ec:[],bd(a,b,c){function d(k,g){if(k.length!=g.length)return!1;for(var l in k)if(k[l]!=g[l])return!1;return!0}for(var e of L.ec)if(e.tc==a&&d(e.Ac,c))return;L.ec.push({tc:a,Ic:b,Ac:c});L.ec.sort((k,g)=>k.Ic<g.Ic)},ud(a){L.ec=L.ec.filter(b=>b.tc!=a)},$b:[],td:(a,b)=>{for(var c=0;c<L.$b.length;++c)L.$b[c].target!=a||b&&b!=L.$b[c].Zb||
db(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},N=(a,b,c)=>{var d=v;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var g=a.codePointAt(k);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;k++}}d[b]=0;return b-
e},gb=(a,b,c,d,e,k)=>{L.oc||(L.oc=O(256));a={target:I(a),Zb:k,bc:d,cc:(g=event)=>{var l=g.target.id?g.target.id:"",m=L.oc;N(fb(g.target),m+0,128);N(l,m+128,128);J(d)(e,m,b)&&g.preventDefault()},ac:c};return M(a)},hb=(a,b,c,d,e)=>{L.pc||(L.pc=O(276));return M({target:a,Zb:e,bc:d,cc:(k=event)=>{var g=L.pc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,m=!!l;u[g]=m;u[g+1]=L.fullscreenEnabled();
var q=m?l:L.Vc,t=q?.id||"";N(fb(q),g+2,128);N(t,g+130,128);w[g+260>>2]=q?q.clientWidth:0;w[g+264>>2]=q?q.clientHeight:0;w[g+268>>2]=screen.width;w[g+272>>2]=screen.height;m&&(L.Vc=l);J(d)(19,g,b)&&k.preventDefault()},ac:c})},ib=(a,b,c,d,e,k)=>{L.rc||(L.rc=O(160));a={target:I(a),Zb:k,bc:d,cc:g=>{var l=L.rc;y[l>>3]=g.timeStamp;var m=l>>2;w[m+2]=g.location;u[l+12]=g.ctrlKey;u[l+13]=g.shiftKey;u[l+14]=g.altKey;u[l+15]=g.metaKey;u[l+16]=g.repeat;w[m+5]=g.charCode;w[m+6]=g.keyCode;w[m+7]=g.which;N(g.key||
"",l+32,32);N(g.code||"",l+64,32);N(g.char||"",l+96,32);N(g.locale||"",l+128,32);J(d)(e,l,b)&&g.preventDefault()},ac:c};return M(a)},jb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;w[d+2]=b.screenX;w[d+3]=b.screenY;w[d+4]=b.clientX;w[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;ma[2*d+14]=b.button;ma[2*d+15]=b.buttons;w[d+8]=b.movementX;w[d+9]=b.movementY;a=ab(c);w[d+10]=b.clientX-(a.left|0);w[d+11]=b.clientY-(a.top|0)},P=(a,b,c,d,e,k)=>{L.lc||(L.lc=O(64));a=
I(a);return M({target:a,nc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Zb:k,bc:d,cc:(g=event)=>{jb(L.lc,g,a);J(d)(e,L.lc,b)&&g.preventDefault()},ac:c})},kb=(a,b,c,d)=>{L.sc||(L.sc=O(257));return M({target:a,Zb:"pointerlockchange",bc:d,cc:(e=event)=>{var k=L.sc,g=document.pointerLockElement;u[k]=!!g;var l=g?.id||"";N(fb(g),k+1,128);N(l,k+129,128);J(d)(20,k,b)&&e.preventDefault()},ac:c})},lb=(a,b,c,d)=>M({target:a,Zb:"pointerlockerror",bc:d,cc:(e=event)=>{J(d)(38,0,b)&&e.preventDefault()},ac:c}),
mb=(a,b,c,d)=>{L.vc||(L.vc=O(36));a=I(a);return M({target:a,Zb:"resize",bc:d,cc:(e=event)=>{if(e.target==a){var k=document.body;if(k){var g=L.vc;w[g>>2]=0;w[g+4>>2]=k.clientWidth;w[g+8>>2]=k.clientHeight;w[g+12>>2]=innerWidth;w[g+16>>2]=innerHeight;w[g+20>>2]=outerWidth;w[g+24>>2]=outerHeight;w[g+28>>2]=pageXOffset|0;w[g+32>>2]=pageYOffset|0;J(d)(10,g,b)&&e.preventDefault()}}},ac:c})},nb=(a,b,c,d,e,k)=>{L.uc||(L.uc=O(1552));a=I(a);return M({target:a,nc:"touchstart"==k||"touchend"==k,Zb:k,bc:d,cc:g=>
{var l={},m=g.touches;for(var q of m)q.Fc=q.Hc=0,l[q.identifier]=q;for(var t of g.changedTouches)t.Fc=1,l[t.identifier]=t;for(var K of g.targetTouches)l[K.identifier].Hc=1;m=L.uc;y[m>>3]=g.timeStamp;u[m+12]=g.ctrlKey;u[m+13]=g.shiftKey;u[m+14]=g.altKey;u[m+15]=g.metaKey;q=m+16;t=ab(a);K=0;for(let z of Object.values(l))if(l=q>>2,w[l]=z.identifier,w[l+1]=z.screenX,w[l+2]=z.screenY,w[l+3]=z.clientX,w[l+4]=z.clientY,w[l+5]=z.pageX,w[l+6]=z.pageY,u[q+28]=z.Fc,u[q+29]=z.Hc,w[l+8]=z.clientX-(t.left|0),w[l+
9]=z.clientY-(t.top|0),q+=48,31<++K)break;w[m+8>>2]=K;J(d)(e,m,b)&&g.preventDefault()},ac:c})},Q,ob=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=(c,d,e,k,g)=>b.drawElementsInstancedANGLE(c,d,e,k,g))},pb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},qb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},rb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},sb=1,R=[],S=[],tb=[],T=[],U=[],V=[],ub=[],vb=[],W=[],wb={},xb=4,yb=0,zb=a=>{for(var b=sb++,c=a.length;c<b;c++)a[c]=null;return b},Y=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=Q[c](),g=k&&zb(d);k?(k.name=g,d[g]=k):X||=1282;w[b+4*e>>2]=g}},Bb=(a,b)=>{a.zc||(a.zc=a.getContext,a.getContext=function(d,e){e=a.zc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Gc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Ab(c,b):0},Ab=(a,b)=>{var c=zb(vb),d={handle:c,attributes:b,version:b.Gc,yc:a};a.canvas&&(a.canvas.Wc=d);vb[c]=d;("undefined"==typeof b.Dc||b.Dc)&&Cb(d);return c},Cb=a=>{a||=Z;if(!a.Uc){a.Uc=!0;var b=a.yc;b.pd=b.getExtension("WEBGL_multi_draw");b.jd=b.getExtension("EXT_polygon_offset_clamp");b.hd=b.getExtension("EXT_clip_control");b.Ad=b.getExtension("WEBGL_polygon_mode");ob(b);pb(b);qb(b);b.ed=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.md=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Cc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Cc)b.Cc=b.getExtension("EXT_disjoint_timer_query");rb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},X,Z,Db=(a,b,c,d,e,k)=>{a={target:I(a),Zb:k,bc:d,cc:(g=event)=>{J(d)(e,0,b)&&g.preventDefault()},ac:c};M(a)},Eb=(a,b,c,d)=>{L.xc||(L.xc=O(96));return M({target:a,nc:!0,Zb:"wheel",bc:d,cc:(e=event)=>{var k=L.xc;jb(k,e,a);y[k+64>>3]=e.deltaX;y[k+72>>3]=e.deltaY;y[k+80>>3]=e.deltaZ;
w[k+88>>2]=e.deltaMode;J(d)(9,k,b)&&e.preventDefault()},ac:c})},Fb=["default","low-power","high-performance"],Gb=[],Hb=()=>{var a=rb(Q);return a=a.concat(a.map(b=>"GL_"+b))},Ib=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Q.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Z.version){X||=1282;return}c=Hb().length;break;case 33307:case 33308:if(2>Z.version){X||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=Q.getParameter(a),
typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":X||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:X||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)w[b+
4*a>>2]=d[a];return}try{c=d.name|0}catch(e){X||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:X||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}w[b>>2]=c}else X||=1281},Jb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Kb=a=>{var b=Jb(a)+1,c=O(b);c&&N(a,c,
b);return c},Lb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Mb=a=>{a-=5120;return 0==a?u:1==a?v:2==a?ma:4==a?w:6==a?oa:5==a||28922==a||28520==a||30779==a||30782==a?x:na},Ob=a=>{var b=Jb(a)+1,c=Nb(b);N(a,c,b);return c},Rb=a=>{var b=Pb();a();Qb(b)};f.requestAnimationFrame=Ma;f.pauseMainLoop=Ya;f.resumeMainLoop=function(){Pa++;var a=Ia,b=Ja,c=D;D=null;Xa(c,0,!1,Qa,!0);Oa(a,b);E()};f.preMainLoop&&Va.push(f.preMainLoop);f.postMainLoop&&Wa.push(f.postMainLoop);for(let a=0;32>a;++a)Gb.push(Array(a));
f.noExitRuntime&&(Ba=f.noExitRuntime);f.printErr&&(n=f.printErr);f.wasmBinary&&(p=f.wasmBinary);f.arguments&&(ca=f.arguments);f.thisProgram&&(da=f.thisProgram);if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();
var O,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Qb,Nb,Pb,qa,cb,Zb={db:()=>ra(""),ab:()=>{Ba=!1;Ca=0},bb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ha(()=>Yb(a,performance.now()))},b);C[a]={id:c,yd:b};return 0},Sa:()=>{Ya();D=null},ka:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ma:(a,b,c)=>{a=I(a);if(!a)return-4;a=ab(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Ta:()=>performance.now(),Za:(a,b)=>{function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
cb:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-qa.buffer.byteLength+65535)/65536|0;try{qa.grow(d);pa();var e=1;break a}catch(k){}e=void 0}if(e)return!0}return!1},U:(a,b,c,d)=>gb(a,b,c,d,12,"blur"),ja:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},V:(a,b,c,d)=>gb(a,b,c,d,13,"focus"),T:(a,b,c,d)=>{if(!L.fullscreenEnabled())return-1;a=I(a);if(!a)return-4;
hb(a,b,c,d,"webkitfullscreenchange");return hb(a,b,c,d,"fullscreenchange")},ca:(a,b,c,d)=>ib(a,b,c,d,2,"keydown"),aa:(a,b,c,d)=>ib(a,b,c,d,1,"keypress"),ba:(a,b,c,d)=>ib(a,b,c,d,3,"keyup"),_a:(a,b,c)=>{a=J(a);Xa(a,b,c)},ia:(a,b,c,d)=>P(a,b,c,d,5,"mousedown"),fa:(a,b,c,d)=>P(a,b,c,d,33,"mouseenter"),ea:(a,b,c,d)=>P(a,b,c,d,34,"mouseleave"),ga:(a,b,c,d)=>P(a,b,c,d,8,"mousemove"),ha:(a,b,c,d)=>P(a,b,c,d,6,"mouseup"),X:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?kb(a,b,c,d):-4:-1,W:(a,b,c,d)=>
document.body?.requestPointerLock?(a=I(a))?lb(a,b,c,d):-4:-1,la:(a,b,c,d)=>mb(a,b,c,d),Y:(a,b,c,d)=>nb(a,b,c,d,25,"touchcancel"),Z:(a,b,c,d)=>nb(a,b,c,d,23,"touchend"),_:(a,b,c,d)=>nb(a,b,c,d,24,"touchmove"),$:(a,b,c,d)=>nb(a,b,c,d,22,"touchstart"),S:(a,b,c,d)=>{Db(a,b,c,d,31,"webglcontextlost");return 0},R:(a,b,c,d)=>{Db(a,b,c,d,32,"webglcontextrestored");return 0},da:(a,b,c,d)=>(a=I(a))?"undefined"!=typeof a.onwheel?Eb(a,b,c,d):-1:-4,Ya:(a,b)=>{var c=b>>2;b={alpha:!!u[b+0],depth:!!u[b+1],stencil:!!u[b+
2],antialias:!!u[b+3],premultipliedAlpha:!!u[b+4],preserveDrawingBuffer:!!u[b+5],powerPreference:Fb[w[c+2]],failIfMajorPerformanceCaveat:!!u[b+12],Gc:w[c+4],od:w[c+5],Dc:u[b+24],Tc:u[b+25],rd:w[c+7],vd:u[b+32]};a=I(a);return!a||b.Tc?0:Bb(a,b)},Wa:a=>{Z=vb[a];f.ctx=Q=Z?.yc;return!a||Q?0:-5},o:a=>Q.activeTexture(a),s:(a,b)=>{Q.attachShader(S[a],V[b])},a:(a,b)=>{35051==a?Q.Bc=b:35052==a&&(Q.fc=b);Q.bindBuffer(a,R[b])},v:(a,b,c)=>{Q.bindBufferBase(a,b,R[c])},jb:(a,b,c,d,e)=>{Q.bindBufferRange(a,b,R[c],
d,e)},g:(a,b)=>{Q.bindFramebuffer(a,tb[b])},vb:(a,b)=>{Q.bindRenderbuffer(a,T[b])},n:(a,b)=>{Q.bindSampler(a,W[b])},c:(a,b)=>{Q.bindTexture(a,U[b])},Q:a=>{Q.bindVertexArray(ub[a])},L:(a,b,c,d)=>Q.blendColor(a,b,c,d),M:(a,b)=>Q.blendEquationSeparate(a,b),N:(a,b,c,d)=>Q.blendFuncSeparate(a,b,c,d),fb:(a,b,c,d,e,k,g,l,m,q)=>Q.blitFramebuffer(a,b,c,d,e,k,g,l,m,q),Ha:(a,b,c,d)=>{2<=Z.version?c&&b?Q.bufferData(a,v,d,c,b):Q.bufferData(a,b,d):Q.bufferData(a,c?v.subarray(c,c+b):b,d)},F:(a,b,c,d)=>{2<=Z.version?
c&&Q.bufferSubData(a,b,v,d,c):Q.bufferSubData(a,b,v.subarray(d,d+c))},sb:a=>Q.checkFramebufferStatus(a),pb:(a,b,c,d)=>Q.clearBufferfi(a,b,c,d),qa:(a,b,c)=>{Q.clearBufferfv(a,b,oa,c>>2)},ob:(a,b,c)=>{Q.clearBufferiv(a,b,w,c>>2)},p:(a,b,c,d)=>{Q.colorMask(!!a,!!b,!!c,!!d)},zb:a=>{Q.compileShader(V[a])},E:(a,b,c,d,e,k,g,l,m)=>{2<=Z.version?Q.fc||!l?Q.compressedTexSubImage2D(a,b,c,d,e,k,g,l,m):Q.compressedTexSubImage2D(a,b,c,d,e,k,g,v,m,l):Q.compressedTexSubImage2D(a,b,c,d,e,k,g,v.subarray(m,m+l))},Ca:(a,
b,c,d,e,k,g,l,m,q,t)=>{Q.fc?Q.compressedTexSubImage3D(a,b,c,d,e,k,g,l,m,q,t):Q.compressedTexSubImage3D(a,b,c,d,e,k,g,l,m,v,t,q)},ya:()=>{var a=zb(S),b=Q.createProgram();b.name=a;b.kc=b.ic=b.jc=0;b.wc=1;S[a]=b;return a},va:a=>{var b=zb(V);V[b]=Q.createShader(a);return b},I:a=>Q.cullFace(a),Ka:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=R[d];e&&(Q.deleteBuffer(e),e.name=0,R[d]=null,d==Q.Bc&&(Q.Bc=0),d==Q.fc&&(Q.fc=0))}},t:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=tb[d];e&&(Q.deleteFramebuffer(e),
e.name=0,tb[d]=null)}},m:a=>{if(a){var b=S[a];b?(Q.deleteProgram(b),b.name=0,S[a]=null):X||=1281}},G:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=T[d];e&&(Q.deleteRenderbuffer(e),e.name=0,T[d]=null)}},H:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=W[d];e&&(Q.deleteSampler(e),e.name=0,W[d]=null)}},k:a=>{if(a){var b=V[a];b?(Q.deleteShader(b),V[a]=null):X||=1281}},h:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=U[d];e&&(Q.deleteTexture(e),e.name=0,U[d]=null)}},Ja:(a,b)=>{for(var c=0;c<a;c++){var d=
w[b+4*c>>2];Q.deleteVertexArray(ub[d]);ub[d]=null}},x:a=>Q.depthFunc(a),w:a=>{Q.depthMask(!!a)},d:a=>Q.disable(a),O:a=>{Q.disableVertexAttribArray(a)},hb:(a,b,c)=>{Q.drawArrays(a,b,c)},i:(a,b,c,d)=>{Q.drawArraysInstanced(a,b,c,d)},sa:(a,b)=>{for(var c=Gb[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];Q.drawBuffers(c)},ib:(a,b,c,d)=>{Q.drawElements(a,b,c,d)},r:(a,b,c,d,e)=>{Q.drawElementsInstanced(a,b,c,d,e)},f:a=>Q.enable(a),kb:a=>{Q.enableVertexAttribArray(a)},ra:(a,b,c,d)=>{Q.framebufferRenderbuffer(a,b,c,T[d])},
j:(a,b,c,d,e)=>{Q.framebufferTexture2D(a,b,c,U[d],e)},y:(a,b,c,d,e)=>{Q.framebufferTextureLayer(a,b,U[c],d,e)},J:a=>Q.frontFace(a),Ia:(a,b)=>{Y(a,b,"createBuffer",R)},P:(a,b)=>{Y(a,b,"createFramebuffer",tb)},wb:(a,b)=>{Y(a,b,"createRenderbuffer",T)},Aa:(a,b)=>{Y(a,b,"createSampler",W)},Fa:(a,b)=>{Y(a,b,"createTexture",U)},Ra:(a,b)=>{Y(a,b,"createVertexArray",ub)},xb:(a,b)=>Q.getAttribLocation(S[a],b?H(b):""),b:(a,b)=>Ib(a,b),xa:(a,b,c,d)=>{a=Q.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");
b=0<b&&d?N(a,d,b):0;c&&(w[c>>2]=b)},A:(a,b,c)=>{if(c)if(a>=sb)X||=1281;else if(a=S[a],35716==b)a=Q.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.kc){var d=Q.getProgramParameter(a,35718);for(b=0;b<d;++b)a.kc=Math.max(a.kc,Q.getActiveUniform(a,b).name.length+1)}w[c>>2]=a.kc}else if(35722==b){if(!a.ic)for(d=Q.getProgramParameter(a,35721),b=0;b<d;++b)a.ic=Math.max(a.ic,Q.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.ic}else if(35381==b){if(!a.jc)for(d=
Q.getProgramParameter(a,35382),b=0;b<d;++b)a.jc=Math.max(a.jc,Q.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.jc}else w[c>>2]=Q.getProgramParameter(a,b);else X||=1281},yb:(a,b,c,d)=>{a=Q.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?N(a,d,b):0;c&&(w[c>>2]=b)},ta:(a,b,c)=>{c?35716==b?(a=Q.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(V[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=Q.getShaderParameter(V[a],b):X||=1281},Pa:(a,
b)=>{if(2>Z.version)return X||=1282,0;var c=wb[a];if(c)return 0>b||b>=c.length?(X||=1281,0):c[b];switch(a){case 7939:return c=Hb().map(Kb),c=wb[a]=c,0>b||b>=c.length?(X||=1281,0):c[b];default:return X||=1280,0}},z:(a,b)=>{b=b?H(b):"";if(a=S[a]){var c=a,d=c.hc,e=c.Qc,k;if(!d){c.hc=d={};c.Pc={};var g=Q.getProgramParameter(c,35718);for(k=0;k<g;++k){var l=Q.getActiveUniform(c,k);var m=l.name;l=l.size;var q=Lb(m);q=0<q?m.slice(0,q):m;var t=c.wc;c.wc+=l;e[q]=[l,t];for(m=0;m<l;++m)d[t]=m,c.Pc[t++]=q}}c=
a.hc;d=0;e=b;k=Lb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.Qc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||Q.getUniformLocation(a,b)))return d}else X||=1281;return-1},eb:(a,b,c)=>{for(var d=Gb[b],e=0;e<b;e++)d[e]=w[c+4*e>>2];Q.invalidateFramebuffer(a,d)},B:a=>{a=S[a];Q.linkProgram(a);a.hc=0;a.Qc={}},Qa:(a,b)=>{3317==a?xb=b:3314==a&&(yb=b);Q.pixelStorei(a,b)},K:(a,b)=>Q.polygonOffset(a,b),gb:a=>Q.readBuffer(a),ub:(a,b,c,d,e)=>Q.renderbufferStorageMultisample(a,b,c,d,e),C:(a,b,c)=>{Q.samplerParameterf(W[a],
b,c)},e:(a,b,c)=>{Q.samplerParameteri(W[a],b,c)},qb:(a,b,c,d)=>Q.scissor(a,b,c,d),ua:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var g=(g=x[c+4*k>>2])?H(g,d?x[d+4*k>>2]:void 0):"";e+=g}Q.shaderSource(V[a],e)},Na:(a,b,c)=>Q.stencilFunc(a,b,c),pa:(a,b,c,d)=>Q.stencilFuncSeparate(a,b,c,d),q:a=>Q.stencilMask(a),Ma:(a,b,c)=>Q.stencilOp(a,b,c),oa:(a,b,c,d)=>Q.stencilOpSeparate(a,b,c,d),Ea:(a,b,c,d,e)=>Q.texStorage2D(a,b,c,d,e),Da:(a,b,c,d,e,k)=>Q.texStorage3D(a,b,c,d,e,k),D:(a,b,c,d,e,k,g,l,m)=>{if(2<=Z.version){if(Q.fc){Q.texSubImage2D(a,
b,c,d,e,k,g,l,m);return}if(m){var q=Mb(l);Q.texSubImage2D(a,b,c,d,e,k,g,l,q,m>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(m){q=Mb(l);var t=k*((yb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT+xb-1&-xb);m=q.subarray(m>>>31-Math.clz32(q.BYTES_PER_ELEMENT),m+t>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else m=null;Q.texSubImage2D(a,b,c,d,e,k,g,l,m)},Ba:(a,b,c,d,e,k,g,l,m,q,t)=>{if(Q.fc)Q.texSubImage3D(a,b,c,d,e,k,g,l,m,q,t);else if(t){var K=Mb(q);
Q.texSubImage3D(a,b,c,d,e,k,g,l,m,q,K,t>>>31-Math.clz32(K.BYTES_PER_ELEMENT))}else Q.texSubImage3D(a,b,c,d,e,k,g,l,m,q,null)},wa:(a,b)=>{var c=Q,d=c.uniform1i;var e=Q.Sc;if(e){var k=e.hc[a];"number"==typeof k&&(e.hc[a]=k=Q.getUniformLocation(e,e.Pc[a]+(0<k?`[${k}]`:"")));a=k}else X||=1282,a=void 0;d.call(c,a,b)},l:a=>{a=S[a];Q.useProgram(a);Q.Sc=a},lb:(a,b)=>{Q.vertexAttribDivisor(a,b)},mb:(a,b,c,d,e)=>{Q.vertexAttribIPointer(a,b,c,d,e)},nb:(a,b,c,d,e,k)=>{Q.vertexAttribPointer(a,b,c,!!d,e,k)},rb:(a,
b,c,d)=>Q.viewport(a,b,c,d),$a:Ea,Cb:function(){f.Jc=a=>{0!=Tb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Jc)},Xa:function(){f.Oc=a=>{const b=a.clipboardData.getData("text");Rb(()=>{const c=Ob(b);Sb(c)})};window.addEventListener("paste",f.Oc)},Ua:function(){f.wd=[];f.Kc=b=>{b.stopPropagation();b.preventDefault()};f.Lc=b=>{b.stopPropagation();b.preventDefault()};f.Mc=b=>{b.stopPropagation();b.preventDefault()};f.Nc=b=>{b.stopPropagation();b.preventDefault();
const c=b.dataTransfer.files;f.xd=c;Ub(c.length);for(let e=0;e<c.length;e++)Rb(()=>{const k=Ob(c[e].name);Vb(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Wb(b.clientX,b.clientY,d)};const a=f.dc;a.addEventListener("dragenter",f.Kc,!1);a.addEventListener("dragleave",f.Lc,!1);a.addEventListener("dragover",f.Mc,!1);a.addEventListener("drop",f.Nc,!1)},Ab:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},za:function(a){f.mc&&
(URL.revokeObjectURL(f.mc[a].Zc),f.mc[a]=null)},La:function(a,b){0!==b&&(document.title=b?H(b):"");a=a?H(a):"";void 0!==f.canvas&&("object"===typeof f.canvas?$a[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.dc=I(a);f.dc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.dc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Bb:function(){window.removeEventListener("beforeunload",f.Jc)},Va:function(){window.removeEventListener("paste",
f.Oc)},Oa:function(){const a=f.dc;a.removeEventListener("dragenter",f.Kc);a.removeEventListener("dragleave",f.Lc);a.removeEventListener("dragover",f.Mc);a.removeEventListener("drop",f.Nc)},u:function(){f.dc&&f.dc.requestPointerLock&&f.dc.requestPointerLock()},Ga:function(a,b,c){if(f.dc){if(0===b)a="none";else if(0!=c)a=f.mc[a].ad;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a=
"ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.dc.style.cursor=a}},tb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(v.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},na:function(a,
b){b=b?H(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function $b(a=[]){var b=Xb;a.unshift(da);var c=a.length,d=Nb(4*(c+1)),e=d;a.forEach(g=>{x[e>>2]=Ob(g);e+=4});x[e>>2]=0;try{var k=b(c,d);Fa(k)}catch(g){Da(g)}}
function ac(a=ca){function b(){f.calledRun=!0;if(!r){bc.Eb();f.onRuntimeInitialized?.();f.noInitialRun||$b(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();ya.push(c)}xa(ya)}}if(0<A)B=ac;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Aa();xa(za);0<A?B=ac:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}var bc;
(async function(){function a(c){c=bc=c.exports;O=c.Fb;Sb=f.__sapp_emsc_onpaste=c.Gb;Tb=f.__sapp_html5_get_ask_leave_site=c.Hb;Ub=f.__sapp_emsc_begin_drop=c.Ib;Vb=f.__sapp_emsc_drop=c.Jb;Wb=f.__sapp_emsc_end_drop=c.Kb;f.__sapp_emsc_invoke_fetch_cb=c.Lb;f.__sapp_emsc_set_fullscreen_flag=c.Mb;Xb=f._main=c.Nb;f.__saudio_emsc_pull=c.Ob;f.__sfetch_emsc_head_response=c.Pb;f.__sfetch_emsc_get_response=c.Qb;f.__sfetch_emsc_failed_http_status=c.Rb;f.__sfetch_emsc_failed_buffer_too_small=c.Sb;f.__sfetch_emsc_failed_other=
c.Tb;Yb=c.Ub;Qb=c.Wb;Nb=c.Xb;Pb=c.Yb;qa=c.Db;cb=c.Vb;pa();A--;f.monitorRunDependencies?.(A);0==A&&B&&(c=B,B=null,c());return bc}A++;f.monitorRunDependencies?.(A);var b={a:Zb};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});sa??=f.locateFile?f.locateFile("drawex-sapp.wasm",ha):ha+"drawex-sapp.wasm";return a((await va(b)).instance)})();ac();
