var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",h=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,u,v;
if(ea){var fs=require("fs"),ha=require("path");q=l?ha.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};u=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,k)=>{e?c(e):b(d?k.buffer:k)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&
(module.exports=g);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof w||a.context instanceof w))throw a;});h=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(v=
a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};g.print||console.log.bind(console);var x=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(h=g.quit);
var y;g.wasmBinary&&(y=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&ia("no native wasm support detected");var ja,ka=!1,la,z,ma,na,A,oa,B,C;function pa(){var a=ja.buffer;g.HEAP8=la=new Int8Array(a);g.HEAP16=ma=new Int16Array(a);g.HEAP32=A=new Int32Array(a);g.HEAPU8=z=new Uint8Array(a);g.HEAPU16=na=new Uint16Array(a);g.HEAPU32=oa=new Uint32Array(a);g.HEAPF32=B=new Float32Array(a);g.HEAPF64=C=new Float64Array(a)}var qa,ra=[],sa=[],ta=[],ua=[],va=[];
function wa(){var a=g.preRun.shift();ra.unshift(a)}var D=0,xa=null,E=null;function ia(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";x(a);ka=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function ya(a){return a.startsWith("data:application/octet-stream;base64,")}var F;F="dyntex-sapp.wasm";if(!ya(F)){var za=F;F=g.locateFile?g.locateFile(za,q):q+za}
function Aa(a){if(a==F&&y)return new Uint8Array(y);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}function Ba(a){if(!y&&(da||l)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Aa(a));if(u)return new Promise((b,c)=>{u(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Aa(a))}
function Ca(a,b,c){return Ba(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{x("failed to asynchronously prepare wasm: "+d);ia(d)})}
function Da(a,b){var c=F;y||"function"!=typeof WebAssembly.instantiateStreaming||ya(c)||c.startsWith("file://")||ea||"function"!=typeof fetch?Ca(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){x("wasm streaming compile failed: "+e);x("falling back to ArrayBuffer instantiation");return Ca(c,a,b)}))}function w(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ea=a=>{for(;0<a.length;)a.shift()(g)},Ha=a=>{var b=Fa();a();Ga(b)},Ia=0;function Ja(){for(var a=G.length-1;0<=a;--a)Ka(a);G=[];La=[]}var La=[];function Ma(){if(navigator.userActivation?navigator.userActivation.isActive:Ia&&Na.Xb)for(var a=0;a<La.length;++a){var b=La[a];La.splice(a,1);--a;b.Ic.apply(null,b.yc)}}var G=[];function Ka(a){var b=G[a];b.target.removeEventListener(b.Pb,b.uc,b.Qb);G.splice(a,1)}
function H(a){function b(d){++Ia;Na=a;Ma();a.Sb(d);Ma();--Ia}if(!a.target)return-4;if(a.Rb)a.uc=b,a.target.addEventListener(a.Pb,b,a.Qb),G.push(a),Oa||(ua.push(Ja),Oa=!0);else for(var c=0;c<G.length;++c)G[c].target==a.target&&G[c].Pb==a.Pb&&Ka(c--);return 0}function Pa(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Oa,Na,Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,I=(a,b)=>{var c=z,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&Xa)return Xa.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var k=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|k<<6|f:(e&7)<<18|k<<12|f<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ya=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];function J(a){a=2<a?a?I(a):"":a;return Ya[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function Za(a){return 0>Ya.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
var $a=[],K=a=>{var b=$a[a];b||(a>=$a.length&&($a.length=a+1),$a[a]=b=qa.get(a));return b},L=(a,b,c)=>{var d=z;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);if(55296<=f&&57343>=f){var m=a.charCodeAt(++k);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=
0;return b-e};function ab(a,b,c,d,e,k){Qa||(Qa=M(256));a={target:J(a),Pb:k,Rb:d,Sb:function(f=event){var m=f.target.id?f.target.id:"",n=Qa;L(Pa(f.target),n+0,128);L(m,n+128,128);K(d)(e,n,b)&&f.preventDefault()},Qb:c};return H(a)}
function bb(a,b,c,d,e,k){Ra||(Ra=M(176));a={target:J(a),Xb:!0,Pb:k,Rb:d,Sb:function(f){var m=Ra;C[m>>3]=f.timeStamp;var n=m>>2;A[n+2]=f.location;A[n+3]=f.ctrlKey;A[n+4]=f.shiftKey;A[n+5]=f.altKey;A[n+6]=f.metaKey;A[n+7]=f.repeat;A[n+8]=f.charCode;A[n+9]=f.keyCode;A[n+10]=f.which;L(f.key||"",m+44,32);L(f.code||"",m+76,32);L(f.char||"",m+108,32);L(f.locale||"",m+140,32);K(d)(e,m,b)&&f.preventDefault()},Qb:c};return H(a)}
function cb(a,b,c){C[a>>3]=b.timeStamp;a>>=2;A[a+2]=b.screenX;A[a+3]=b.screenY;A[a+4]=b.clientX;A[a+5]=b.clientY;A[a+6]=b.ctrlKey;A[a+7]=b.shiftKey;A[a+8]=b.altKey;A[a+9]=b.metaKey;ma[2*a+20]=b.button;ma[2*a+21]=b.buttons;A[a+11]=b.movementX;A[a+12]=b.movementY;c=Za(c);A[a+13]=b.clientX-c.left;A[a+14]=b.clientY-c.top}
function N(a,b,c,d,e,k){Sa||(Sa=M(72));a=J(a);return H({target:a,Xb:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Pb:k,Rb:d,Sb:function(f=event){cb(Sa,f,a);K(d)(e,Sa,b)&&f.preventDefault()},Qb:c})}function db(a,b,c,d,e){Ta||(Ta=M(260));return H({target:a,Pb:e,Rb:d,Sb:function(k=event){var f=Ta,m=document.pointerLockElement||document.Ub||document.dc||document.cc;A[f>>2]=!!m;var n=m&&m.id?m.id:"";L(Pa(m),f+4,128);L(n,f+132,128);K(d)(20,f,b)&&k.preventDefault()},Qb:c})}
function eb(a,b,c,d,e){return H({target:a,Pb:e,Rb:d,Sb:function(k=event){K(d)(38,0,b)&&k.preventDefault()},Qb:c})}
function fb(a,b,c,d){Ua||(Ua=M(36));a=J(a);return H({target:a,Pb:"resize",Rb:d,Sb:function(e=event){if(e.target==a){var k=document.body;if(k){var f=Ua;A[f>>2]=e.detail;A[f+4>>2]=k.clientWidth;A[f+8>>2]=k.clientHeight;A[f+12>>2]=innerWidth;A[f+16>>2]=innerHeight;A[f+20>>2]=outerWidth;A[f+24>>2]=outerHeight;A[f+28>>2]=pageXOffset;A[f+32>>2]=pageYOffset;K(d)(10,f,b)&&e.preventDefault()}}},Qb:c})}
function gb(a,b,c,d,e,k){Va||(Va=M(1696));a=J(a);return H({target:a,Xb:"touchstart"==k||"touchend"==k,Pb:k,Rb:d,Sb:function(f){for(var m,n={},p=f.touches,r=0;r<p.length;++r)m=p[r],m.ic=m.kc=0,n[m.identifier]=m;for(r=0;r<f.changedTouches.length;++r)m=f.changedTouches[r],m.ic=1,n[m.identifier]=m;for(r=0;r<f.targetTouches.length;++r)n[f.targetTouches[r].identifier].kc=1;p=Va;C[p>>3]=f.timeStamp;var t=p>>2;A[t+3]=f.ctrlKey;A[t+4]=f.shiftKey;A[t+5]=f.altKey;A[t+6]=f.metaKey;t+=7;var kb=Za(a),lb=0;for(r in n)if(m=
n[r],A[t]=m.identifier,A[t+1]=m.screenX,A[t+2]=m.screenY,A[t+3]=m.clientX,A[t+4]=m.clientY,A[t+5]=m.pageX,A[t+6]=m.pageY,A[t+7]=m.ic,A[t+8]=m.kc,A[t+9]=m.clientX-kb.left,A[t+10]=m.clientY-kb.top,t+=13,31<++lb)break;A[p+8>>2]=lb;K(d)(e,p,b)&&f.preventDefault()},Qb:c})}
function hb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,k){b.drawArraysInstancedANGLE(c,d,e,k)},a.drawElementsInstanced=function(c,d,e,k,f){b.drawElementsInstancedANGLE(c,d,e,k,f)})}
function ib(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function jb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function mb(a){a.Ac=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function nb(a){a.Bc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function ob(a){a.Dc=a.getExtension("WEBGL_multi_draw")}var pb=1,qb=[],O=[],rb=[],sb=[],tb=[],P=[],ub=[],vb=[],Q=[],wb={},xb=4;function R(a){yb||(yb=a)}function zb(a){for(var b=pb++,c=a.length;c<b;c++)a[c]=null;return b}
function Ab(a,b){a.Ub||(a.Ub=a.getContext,a.getContext=function(d,e){e=a.Ub(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.jc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Bb(c,b):0}function Bb(a,b){var c=zb(vb),d={handle:c,attributes:b,version:b.jc,ac:a};a.canvas&&(a.canvas.xc=d);vb[c]=d;("undefined"==typeof b.hc||b.hc)&&Cb(d);return c}
function Cb(a){a||(a=S);if(!a.wc){a.wc=!0;var b=a.ac;hb(b);ib(b);jb(b);mb(b);nb(b);2<=a.version&&(b.fc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.fc)b.fc=b.getExtension("EXT_disjoint_timer_query");ob(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var yb,S;function Db(a,b,c,d,e,k){a={target:J(a),Pb:k,Rb:d,Sb:(f=event)=>{K(d)(e,0,b)&&f.preventDefault()},Qb:c};H(a)}
function Eb(a,b,c,d){Wa||(Wa=M(104));return H({target:a,Xb:!0,Pb:"wheel",Rb:d,Sb:function(e=event){var k=Wa;cb(k,e,a);C[k+72>>3]=e.deltaX;C[k+80>>3]=e.deltaY;C[k+88>>3]=e.deltaZ;A[k+96>>2]=e.deltaMode;K(d)(9,k,b)&&e.preventDefault()},Qb:c})}var Fb=["default","low-power","high-performance"];function Gb(a,b,c,d){for(var e=0;e<a;e++){var k=T[c](),f=k&&zb(d);k?(k.name=f,d[f]=k):R(1282);A[b+4*e>>2]=f}}
function Hb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=T.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>S.version){R(1282);return}c=2*(T.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>S.version){R(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=T.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":R(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:R(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)A[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){R(1280);x("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:R(1280);x("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}A[b>>2]=c}else R(1281)}
var Ib=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b};function Jb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}var Kb=[];function U(a){a-=5120;return 0==a?la:1==a?z:2==a?ma:4==a?A:6==a?B:5==a||28922==a||28520==a||30779==a||30782==a?oa:na}function V(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}
function Lb(a,b,c,d,e){a=U(a);var k=V(a),f=xb;return a.subarray(e>>k,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<k)+f-1&-f)>>k)}function W(a){var b=T.tc;if(b){var c=b.Wb[a];"number"==typeof c&&(b.Wb[a]=c=T.getUniformLocation(b,b.rc[a]+(0<c?"["+c+"]":"")));return c}R(1282)}for(var X=[],Y=[],Mb=a=>{if(!noExitRuntime){if(g.onExit)g.onExit(a);ka=!0}h(a,new w(a))},Ob=a=>{var b=Ib(a)+1,c=Nb(b);L(a,c,b);return c},T,Z=0;32>Z;++Z)Kb.push(Array(Z));var Pb=new Float32Array(288);
for(Z=0;288>Z;++Z)X[Z]=Pb.subarray(0,Z+1);var Qb=new Int32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Qb.subarray(0,Z+1);
var Xb={l:()=>{ia("")},ca:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},da:function(a,b,c){a=J(a);if(!a)return-4;a=Za(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},Va:(a,b,c)=>z.copyWithin(a,b,b+c),Ta:function(a,b){function c(d){K(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Wa:a=>{var b=z.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,
d+(65536-d%65536)%65536)-ja.buffer.byteLength+65535>>>16;try{ja.grow(e);pa();var k=1;break a}catch(f){}k=void 0}if(k)return!0}return!1},M:function(a,b,c,d){return ab(a,b,c,d,12,"blur")},ba:function(a,b,c){a=J(a);if(!a)return-4;a.width=b;a.height=c;return 0},N:function(a,b,c,d){return ab(a,b,c,d,13,"focus")},W:function(a,b,c,d){return bb(a,b,c,d,2,"keydown")},U:function(a,b,c,d){return bb(a,b,c,d,1,"keypress")},V:function(a,b,c,d){return bb(a,b,c,d,3,"keyup")},aa:function(a,b,c,d){return N(a,b,c,d,
5,"mousedown")},Z:function(a,b,c,d){return N(a,b,c,d,33,"mouseenter")},Y:function(a,b,c,d){return N(a,b,c,d,34,"mouseleave")},_:function(a,b,c,d){return N(a,b,c,d,8,"mousemove")},$:function(a,b,c,d){return N(a,b,c,d,6,"mouseup")},P:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Ub||document.body.dc||document.body.cc))return-1;a=J(a);if(!a)return-4;db(a,b,c,d,"mozpointerlockchange");db(a,b,c,d,"webkitpointerlockchange");db(a,b,c,d,"mspointerlockchange");
return db(a,b,c,d,"pointerlockchange")},O:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Ub||document.body.dc||document.body.cc))return-1;a=J(a);if(!a)return-4;eb(a,b,c,d,"mozpointerlockerror");eb(a,b,c,d,"webkitpointerlockerror");eb(a,b,c,d,"mspointerlockerror");return eb(a,b,c,d,"pointerlockerror")},Ua:function(a,b,c,d){return fb(a,b,c,d)},Q:function(a,b,c,d){return gb(a,b,c,d,25,"touchcancel")},R:function(a,b,c,d){return gb(a,b,c,d,23,"touchend")},S:function(a,
b,c,d){return gb(a,b,c,d,24,"touchmove")},T:function(a,b,c,d){return gb(a,b,c,d,22,"touchstart")},L:function(a,b,c,d){Db(a,b,c,d,31,"webglcontextlost");return 0},K:function(a,b,c,d){Db(a,b,c,d,32,"webglcontextrestored");return 0},X:function(a,b,c,d){return(a=J(a))?"undefined"!=typeof a.onwheel?Eb(a,b,c,d):-1:-4},Ra:function(a,b){b>>=2;b={alpha:!!A[b],depth:!!A[b+1],stencil:!!A[b+2],antialias:!!A[b+3],premultipliedAlpha:!!A[b+4],preserveDrawingBuffer:!!A[b+5],powerPreference:Fb[A[b+6]],failIfMajorPerformanceCaveat:!!A[b+
7],jc:A[b+8],Cc:A[b+9],hc:A[b+10],vc:A[b+11],Ec:A[b+12],Fc:A[b+13]};a=J(a);return!a||b.vc?0:Ab(a,b)},Pa:function(a,b){a=vb[a];b=b?I(b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&hb(T);"OES_vertex_array_object"==b&&ib(T);"WEBGL_draw_buffers"==b&&jb(T);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&mb(T);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&nb(T);"WEBGL_multi_draw"==b&&ob(T);return!!a.ac.getExtension(b)},Sa:function(a){a>>=2;for(var b=0;14>b;++b)A[a+
b]=0;A[a]=A[a+1]=A[a+3]=A[a+4]=A[a+8]=A[a+10]=1},Qa:function(a){S=vb[a];g.zc=T=S&&S.ac;return!a||T?0:-5},f:function(a){T.activeTexture(a)},z:function(a,b){T.attachShader(O[a],P[b])},d:function(a,b){35051==a?T.ec=b:35052==a&&(T.Tb=b);T.bindBuffer(a,qb[b])},i:function(a,b){T.bindFramebuffer(a,rb[b])},g:function(a,b){T.bindSampler(a,Q[b])},a:function(a,b){T.bindTexture(a,tb[b])},I:function(a){T.bindVertexArray(ub[a])},E:function(a,b,c,d){T.blendColor(a,b,c,d)},F:function(a,b){T.blendEquationSeparate(a,
b)},G:function(a,b,c,d){T.blendFuncSeparate(a,b,c,d)},_a:function(a,b,c,d,e,k,f,m,n,p){T.blitFramebuffer(a,b,c,d,e,k,f,m,n,p)},ya:function(a,b,c,d){2<=S.version?c&&b?T.bufferData(a,z,d,c,b):T.bufferData(a,b,d):T.bufferData(a,c?z.subarray(c,c+b):b,d)},xa:function(a,b,c,d){2<=S.version?c&&T.bufferSubData(a,b,z,d,c):T.bufferSubData(a,b,z.subarray(d,d+c))},tb:function(a,b,c,d){T.clearBufferfi(a,b,c,d)},ha:function(a,b,c){T.clearBufferfv(a,b,B,c>>2)},sb:function(a,b,c){T.clearBufferiv(a,b,A,c>>2)},j:function(a,
b,c,d){T.colorMask(!!a,!!b,!!c,!!d)},la:function(a){T.compileShader(P[a])},ra:function(){var a=zb(O),b=T.createProgram();b.name=a;b.$b=b.Yb=b.Zb=0;b.bc=1;O[a]=b;return a},na:function(a){var b=zb(P);P[b]=T.createShader(a);return b},B:function(a){T.cullFace(a)},La:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=qb[d];e&&(T.deleteBuffer(e),e.name=0,qb[d]=null,d==T.ec&&(T.ec=0),d==T.Tb&&(T.Tb=0))}},k:function(a,b){for(var c=0;c<a;++c){var d=A[b+4*c>>2],e=rb[d];e&&(T.deleteFramebuffer(e),e.name=
0,rb[d]=null)}},J:function(a){if(a){var b=O[a];b?(T.deleteProgram(b),b.name=0,O[a]=null):R(1281)}},Ja:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=sb[d];e&&(T.deleteRenderbuffer(e),e.name=0,sb[d]=null)}},Ha:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=Q[d];e&&(T.deleteSampler(e),e.name=0,Q[d]=null)}},r:function(a){if(a){var b=P[a];b?(T.deleteShader(b),P[a]=null):R(1281)}},Ka:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=tb[d];e&&(T.deleteTexture(e),e.name=0,tb[d]=null)}},
Ga:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2];T.deleteVertexArray(ub[d]);ub[d]=null}},u:function(a){T.depthFunc(a)},t:function(a){T.depthMask(!!a)},c:function(a){T.disable(a)},H:function(a){T.disableVertexAttribArray(a)},ab:function(a,b,c){T.drawArrays(a,b,c)},bb:function(a,b,c,d){T.drawArraysInstanced(a,b,c,d)},db:function(a,b,c,d){T.drawElements(a,b,c,d)},eb:function(a,b,c,d,e){T.drawElementsInstanced(a,b,c,d,e)},h:function(a){T.enable(a)},pb:function(a){T.enableVertexAttribArray(a)},
C:function(a){T.frontFace(a)},za:function(a,b){Gb(a,b,"createBuffer",qb)},sa:function(a,b){Gb(a,b,"createSampler",Q)},wa:function(a,b){Gb(a,b,"createTexture",tb)},Fa:function(a,b){Gb(a,b,"createVertexArray",ub)},ja:function(a,b){return T.getAttribLocation(O[a],b?I(b):"")},b:function(a,b){Hb(a,b)},pa:function(a,b,c,d){a=T.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(A[c>>2]=b)},y:function(a,b,c){if(c)if(a>=pb)R(1281);else if(a=O[a],35716==b)a=T.getProgramInfoLog(a),
null===a&&(a="(unknown error)"),A[c>>2]=a.length+1;else if(35719==b){if(!a.$b)for(b=0;b<T.getProgramParameter(a,35718);++b)a.$b=Math.max(a.$b,T.getActiveUniform(a,b).name.length+1);A[c>>2]=a.$b}else if(35722==b){if(!a.Yb)for(b=0;b<T.getProgramParameter(a,35721);++b)a.Yb=Math.max(a.Yb,T.getActiveAttrib(a,b).name.length+1);A[c>>2]=a.Yb}else if(35381==b){if(!a.Zb)for(b=0;b<T.getProgramParameter(a,35382);++b)a.Zb=Math.max(a.Zb,T.getActiveUniformBlockName(a,b).length+1);A[c>>2]=a.Zb}else A[c>>2]=T.getProgramParameter(a,
b);else R(1281)},ka:function(a,b,c,d){a=T.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(A[c>>2]=b)},w:function(a,b,c){c?35716==b?(a=T.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),A[c>>2]=a?a.length+1:0):35720==b?(a=T.getShaderSource(P[a]),A[c>>2]=a?a.length+1:0):A[c>>2]=T.getShaderParameter(P[a],b):R(1281)},Ma:function(a,b){if(2>S.version)return R(1282),0;var c=wb[a];if(c)return 0>b||b>=c.length?(R(1281),0):c[b];switch(a){case 7939:return c=T.getSupportedExtensions()||
[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){var e=Ib(d)+1,k=M(e);k&&L(d,k,e);return k}),c=wb[a]=c,0>b||b>=c.length?(R(1281),0):c[b];default:return R(1280),0}},m:function(a,b){b=b?I(b):"";if(a=O[a]){var c=a,d=c.Wb,e=c.sc,k;if(!d)for(c.Wb=d={},c.rc={},k=0;k<T.getProgramParameter(c,35718);++k){var f=T.getActiveUniform(c,k);var m=f.name;f=f.size;var n=Jb(m);n=0<n?m.slice(0,n):m;var p=c.bc;c.bc+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.rc[p++]=n}c=a.Wb;d=0;e=b;k=Jb(b);0<k&&(d=parseInt(b.slice(k+
1))>>>0,e=b.slice(0,k));if((e=a.sc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else R(1281);return-1},Za:function(a,b,c){for(var d=Kb[b],e=0;e<b;e++)d[e]=A[c+4*e>>2];T.invalidateFramebuffer(a,d)},qa:function(a){a=O[a];T.linkProgram(a);a.Wb=0;a.sc={}},Ea:function(a,b){3317==a&&(xb=b);T.pixelStorei(a,b)},D:function(a,b){T.polygonOffset(a,b)},$a:function(a){T.readBuffer(a)},A:function(a,b,c){T.samplerParameterf(Q[a],b,c)},e:function(a,b,c){T.samplerParameteri(Q[a],b,c)},ub:function(a,
b,c,d){T.scissor(a,b,c,d)},ma:function(a,b,c,d){for(var e="",k=0;k<b;++k){var f=d?A[d+4*k>>2]:-1,m=A[c+4*k>>2];f=m?I(m,0>f?void 0:f):"";e+=f}T.shaderSource(P[a],e)},Ca:function(a,b,c){T.stencilFunc(a,b,c)},ga:function(a,b,c,d){T.stencilFuncSeparate(a,b,c,d)},s:function(a){T.stencilMask(a)},Ba:function(a,b,c){T.stencilOp(a,b,c)},fa:function(a,b,c,d){T.stencilOpSeparate(a,b,c,d)},va:function(a,b,c,d,e,k,f,m,n){if(2<=S.version)if(T.Tb)T.texImage2D(a,b,c,d,e,k,f,m,n);else if(n){var p=U(m);T.texImage2D(a,
b,c,d,e,k,f,m,p,n>>V(p))}else T.texImage2D(a,b,c,d,e,k,f,m,null);else T.texImage2D(a,b,c,d,e,k,f,m,n?Lb(m,f,d,e,n):null)},ta:function(a,b,c,d,e,k,f,m,n,p){if(T.Tb)T.texImage3D(a,b,c,d,e,k,f,m,n,p);else if(p){var r=U(n);T.texImage3D(a,b,c,d,e,k,f,m,n,r,p>>V(r))}else T.texImage3D(a,b,c,d,e,k,f,m,n,null)},Ya:function(a,b,c,d,e,k,f,m,n){if(2<=S.version)if(T.Tb)T.texSubImage2D(a,b,c,d,e,k,f,m,n);else if(n){var p=U(m);T.texSubImage2D(a,b,c,d,e,k,f,m,p,n>>V(p))}else T.texSubImage2D(a,b,c,d,e,k,f,m,null);
else p=null,n&&(p=Lb(m,f,e,k,n)),T.texSubImage2D(a,b,c,d,e,k,f,m,p)},Xa:function(a,b,c,d,e,k,f,m,n,p,r){if(T.Tb)T.texSubImage3D(a,b,c,d,e,k,f,m,n,p,r);else if(r){var t=U(p);T.texSubImage3D(a,b,c,d,e,k,f,m,n,p,t,r>>V(t))}else T.texSubImage3D(a,b,c,d,e,k,f,m,n,p,null)},ob:function(a,b,c){if(2<=S.version)b&&T.uniform1fv(W(a),B,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);T.uniform1fv(W(a),d)}},x:function(a,b){T.uniform1i(W(a),b)},jb:function(a,
b,c){if(2<=S.version)b&&T.uniform1iv(W(a),A,c>>2,b);else{if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);T.uniform1iv(W(a),d)}},mb:function(a,b,c){if(2<=S.version)b&&T.uniform2fv(W(a),B,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);T.uniform2fv(W(a),d)}},ib:function(a,b,c){if(2<=S.version)b&&T.uniform2iv(W(a),A,c>>2,2*b);else{if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=
A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);T.uniform2iv(W(a),d)}},lb:function(a,b,c){if(2<=S.version)b&&T.uniform3fv(W(a),B,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);T.uniform3fv(W(a),d)}},hb:function(a,b,c){if(2<=S.version)b&&T.uniform3iv(W(a),A,c>>2,3*b);else{if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>
2];else d=A.subarray(c>>2,c+12*b>>2);T.uniform3iv(W(a),d)}},kb:function(a,b,c){if(2<=S.version)b&&T.uniform4fv(W(a),B,c>>2,4*b);else{if(72>=b){var d=X[4*b-1],e=B;c>>=2;for(var k=0;k<4*b;k+=4){var f=c+k;d[k]=e[f];d[k+1]=e[f+1];d[k+2]=e[f+2];d[k+3]=e[f+3]}}else d=B.subarray(c>>2,c+16*b>>2);T.uniform4fv(W(a),d)}},gb:function(a,b,c){if(2<=S.version)b&&T.uniform4iv(W(a),A,c>>2,4*b);else{if(72>=b)for(var d=Y[4*b-1],e=0;e<4*b;e+=4)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2],d[e+3]=A[c+
(4*e+12)>>2];else d=A.subarray(c>>2,c+16*b>>2);T.uniform4iv(W(a),d)}},fb:function(a,b,c,d){if(2<=S.version)b&&T.uniformMatrix4fv(W(a),!!c,B,d>>2,16*b);else{if(18>=b){var e=X[16*b-1],k=B;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=k[m];e[f+1]=k[m+1];e[f+2]=k[m+2];e[f+3]=k[m+3];e[f+4]=k[m+4];e[f+5]=k[m+5];e[f+6]=k[m+6];e[f+7]=k[m+7];e[f+8]=k[m+8];e[f+9]=k[m+9];e[f+10]=k[m+10];e[f+11]=k[m+11];e[f+12]=k[m+12];e[f+13]=k[m+13];e[f+14]=k[m+14];e[f+15]=k[m+15]}}else e=B.subarray(d>>2,d+64*b>>2);T.uniformMatrix4fv(W(a),
!!c,e)}},n:function(a){a=O[a];T.useProgram(a);T.tc=a},qb:function(a,b){T.vertexAttribDivisor(a,b)},rb:function(a,b,c,d,e,k){T.vertexAttribPointer(a,b,c,!!d,e,k)},ia:function(a,b,c,d){T.viewport(a,b,c,d)},Oa:function(){g.lc=a=>{0!=Rb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.lc)},Ia:function(){g.qc=a=>{const b=a.clipboardData.getData("text");Ha(()=>{const c=Ob(b);Sb(c)})};window.addEventListener("paste",g.qc)},Aa:function(a){g.Gc=[];a=a?I(a):"";a=document.getElementById(a);
g.mc=b=>{b.stopPropagation();b.preventDefault()};g.nc=b=>{b.stopPropagation();b.preventDefault()};g.oc=b=>{b.stopPropagation();b.preventDefault()};g.pc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Hc=c;Tb(c.length);for(let e=0;e<c.length;e++)Ha(()=>{const k=Ob(c[e].name);Ub(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Vb(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.mc,!1);a.addEventListener("dragleave",g.nc,!1);a.addEventListener("dragover",
g.oc,!1);a.addEventListener("drop",g.pc,!1)},nb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},q:function(){const a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Wb()});document.body.append(a)},p:function(){document.getElementById("_sokol_app_input_element").focus()},oa:function(a){a=a?I(a):"";g.Vb=document.getElementById(a);g.Vb||console.log("sokol_app.h: invalid target:"+
a);g.Vb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Na:function(){window.removeEventListener("beforeunload",g.lc)},Da:function(){window.removeEventListener("paste",g.qc)},ua:function(a){a=a?I(a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.mc);a.removeEventListener("dragleave",g.nc);a.removeEventListener("dragover",g.oc);a.removeEventListener("drop",g.pc)},v:function(){g.Vb&&g.Vb.requestPointerLock&&g.Vb.requestPointerLock()},
cb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(z.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},o:function(){document.getElementById("_sokol_app_input_element").blur()},ea:function(a,b){b=b?I(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);
break;default:console.info(b)}}};
(function(){function a(c){c=c.exports;g.asm=c;ja=g.asm.vb;pa();qa=g.asm.Lb;sa.unshift(g.asm.wb);D--;g.monitorRunDependencies&&g.monitorRunDependencies(D);if(0==D&&(null!==xa&&(clearInterval(xa),xa=null),E)){var d=E;E=null;d()}return c}var b={a:Xb};D++;g.monitorRunDependencies&&g.monitorRunDependencies(D);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return x("Module.instantiateWasm callback failed with error: "+c),!1}Da(b,function(c){a(c.instance)});return{}})();
var Wb=g.__sapp_emsc_notify_keyboard_hidden=function(){return(Wb=g.__sapp_emsc_notify_keyboard_hidden=g.asm.xb).apply(null,arguments)},Sb=g.__sapp_emsc_onpaste=function(){return(Sb=g.__sapp_emsc_onpaste=g.asm.yb).apply(null,arguments)},Rb=g.__sapp_html5_get_ask_leave_site=function(){return(Rb=g.__sapp_html5_get_ask_leave_site=g.asm.zb).apply(null,arguments)},Tb=g.__sapp_emsc_begin_drop=function(){return(Tb=g.__sapp_emsc_begin_drop=g.asm.Ab).apply(null,arguments)},Ub=g.__sapp_emsc_drop=function(){return(Ub=
g.__sapp_emsc_drop=g.asm.Bb).apply(null,arguments)},Vb=g.__sapp_emsc_end_drop=function(){return(Vb=g.__sapp_emsc_end_drop=g.asm.Cb).apply(null,arguments)};g.__sapp_emsc_invoke_fetch_cb=function(){return(g.__sapp_emsc_invoke_fetch_cb=g.asm.Db).apply(null,arguments)};var Yb=g._main=function(){return(Yb=g._main=g.asm.Eb).apply(null,arguments)};g.__saudio_emsc_pull=function(){return(g.__saudio_emsc_pull=g.asm.Fb).apply(null,arguments)};
g.__sfetch_emsc_head_response=function(){return(g.__sfetch_emsc_head_response=g.asm.Gb).apply(null,arguments)};g.__sfetch_emsc_get_response=function(){return(g.__sfetch_emsc_get_response=g.asm.Hb).apply(null,arguments)};g.__sfetch_emsc_failed_http_status=function(){return(g.__sfetch_emsc_failed_http_status=g.asm.Ib).apply(null,arguments)};g.__sfetch_emsc_failed_buffer_too_small=function(){return(g.__sfetch_emsc_failed_buffer_too_small=g.asm.Jb).apply(null,arguments)};
function M(){return(M=g.asm.Kb).apply(null,arguments)}function Fa(){return(Fa=g.asm.Mb).apply(null,arguments)}function Ga(){return(Ga=g.asm.Nb).apply(null,arguments)}function Nb(){return(Nb=g.asm.Ob).apply(null,arguments)}g.___start_em_js=9352;g.___stop_em_js=19027;var Zb;E=function $b(){Zb||ac();Zb||(E=$b)};function bc(a=[]){var b=Yb;a.unshift(ca);var c=a.length,d=Nb(4*(c+1)),e=d>>2;a.forEach(f=>{A[e++]=Ob(f)});A[e]=0;try{var k=b(c,d);Mb(k)}catch(f){f instanceof w||"unwind"==f||h(1,f)}}
function ac(){var a=ba;function b(){if(!Zb&&(Zb=!0,g.calledRun=!0,!ka)){Ea(sa);Ea(ta);if(g.onRuntimeInitialized)g.onRuntimeInitialized();cc&&bc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();va.unshift(c)}Ea(va)}}if(!(0<D)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)wa();Ea(ra);0<D||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var cc=!0;g.noInitialRun&&(cc=!1);ac();
