var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs");require("path");k=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?
"":k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};f.print||console.log.bind(console);var m=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);var la=f.wasmBinary,ma,p=!1,na,r,t,oa,pa,u,v,w,x;
function qa(){var a=ma.buffer;f.HEAP8=r=new Int8Array(a);f.HEAP16=oa=new Int16Array(a);f.HEAPU8=t=new Uint8Array(a);f.HEAPU16=pa=new Uint16Array(a);f.HEAP32=u=new Int32Array(a);f.HEAPU32=v=new Uint32Array(a);f.HEAPF32=w=new Float32Array(a);f.HEAPF64=x=new Float64Array(a)}var ra=[],sa=[],ta=[],ua=[];function va(){var a=f.preRun.shift();ra.unshift(a)}var z=0,A=null;
function wa(a){f.onAbort?.(a);a="Aborted("+a+")";m(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var xa=a=>a.startsWith("data:application/octet-stream;base64,"),ka=a=>a.startsWith("file://"),ya;async function za(a){if(!la)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==ya&&la)a=new Uint8Array(la);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Aa(a,b){try{var c=await za(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),wa(d)}}async function Ba(a){var b=ya;if(!(la||"function"!=typeof WebAssembly.instantiateStreaming||xa(b)||ka(b)||ca)&&"function"==typeof fetch)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return Aa(b,a)}
class Ca{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Da=a=>{for(;0<a.length;)a.shift()(f)},Ea=f.noExitRuntime||!0,Fa=0,B={},Ga=a=>{a instanceof Ca||"unwind"==a||ha(1,a)},Ha=a=>{na=a;Ea||0<Fa||(f.onExit?.(a),p=!0);ha(a,new Ca(a))},Ia=a=>{na=a;Ha(a)},Ja=()=>{if(!(Ea||0<Fa))try{var a=na;na=a;Ha(a)}catch(b){Ga(b)}},Ka=a=>{if(!p)try{a(),Ja()}catch(b){Ga(b)}},Ra=(a,b)=>{La=a;Ma=b;if(C)if(Na||=!0,0==a)D=function(){setTimeout(F,Math.max(0,Oa+b-performance.now())|0)};else if(1==a)D=function(){Pa(F)};else if(2==a){if("undefined"==typeof Qa)if("undefined"==
typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Qa=setImmediate;D=function(){Qa(F)}}},$a=(a,b,c,d,e)=>{function h(){return g<Sa?(Ja(),!1):!0}C=a;Ta=d;var g=Sa;Na=!1;F=function(){if(!p)if(0<Ua.length){var l=Ua.shift();
l.hd(l.Yc);if(Va){var n=Va,q=0==n%1?n-1:Math.floor(n);Va=l.$c?q:(8*n+(q+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",n=Va??0,q=Wa.ed??0,n?n<q?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));h()&&setTimeout(F,0)}else if(h())if(Xa=Xa+1|0,1==La&&1<Ma&&0!=Xa%Ma)D();else{0==La&&(Oa=performance.now());a:if(!p){for(l of Ya)if(!1===l())break a;Ka(a);for(n of Za)n()}h()&&D()}};e||(b&&0<b?Ra(0,1E3/b):Ra(1,1),D());if(c)throw"unwind";},Na=!1,D=null,Sa=
0,C=null,Ta=0,La=0,Ma=0,Xa=0,Ua=[],Ya=[],Za=[];function ab(){D=null;Sa++}var G=0;function Pa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===G)G=b+1E3/60;else for(;b+2>=G;)G+=1E3/60;setTimeout(a,Math.max(G-b,0))}}var Wa={},Oa,F,Qa,Va;function bb(a){var b=H.Yb[a];b.target.removeEventListener(b.Xb,b.Cc,b.Zb);H.Yb.splice(a,1)}
function cb(){if(navigator.userActivation?navigator.userActivation.isActive:H.oc&&H.Pc.mc){var a=H.cc;H.cc=[];for(var b of a)b.rc(...b.yc)}}function I(a){if(!a.target)return-4;if(a.$b)a.Cc=function(c){++H.oc;H.Pc=a;cb();a.ac(c);cb();--H.oc},a.target.addEventListener(a.Xb,a.Cc,a.Zb),H.Yb.push(a);else for(var b=0;b<H.Yb.length;++b)H.Yb[b].target==a.target&&H.Yb[b].Xb==a.Xb&&bb(b--);return 0}function db(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var H={Zc:0,jd:0,pc:0,kc:0,vc:0,tc:0,nc:0,cd:0,nd:0,bd:0,gd:0,qc:0,wd:0,sc:0,ld(a,b,c){r.set(r.subarray(b,b+c),a)},pd(){for(;H.Yb.length;)bb(H.Yb.length-1);H.cc=[]},oc:0,cc:[],ad(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var l in h)if(h[l]!=g[l])return!1;return!0}for(var e of H.cc)if(e.rc==a&&d(e.yc,c))return;H.cc.push({rc:a,Gc:b,yc:c});H.cc.sort((h,g)=>h.Gc<g.Gc)},rd(a){H.cc=H.cc.filter(b=>b.rc!=a)},Yb:[],qd:(a,b)=>{for(var c=0;c<H.Yb.length;++c)H.Yb[c].target!=a||b&&b!=H.Yb[c].Xb||
bb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},eb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,J=(a=0,b=NaN)=>{var c=t,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&eb)return eb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=
65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},fb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?J(a):"":a;return fb[a]||("undefined"!=typeof document?document.querySelector(a):null)},gb=a=>0>fb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},hb=[],ib,L=a=>{var b=hb[a];b||(a>=hb.length&&(hb.length=a+1),hb[a]=b=ib.get(a));return b},M=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<
a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var l=a.charCodeAt(++h);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},jb=(a,b,c,d,e,h)=>{H.nc||(H.nc=N(256));a={target:K(a),Xb:h,$b:d,ac:(g=event)=>{var l=g.target.id?g.target.id:"",n=H.nc;M(db(g.target),n+0,128);
M(l,n+128,128);L(d)(e,n,b)&&g.preventDefault()},Zb:c};return I(a)},kb=(a,b,c,d,e,h)=>{H.pc||(H.pc=N(160));a={target:K(a),Xb:h,$b:d,ac:g=>{var l=H.pc;x[l>>3]=g.timeStamp;var n=l>>2;u[n+2]=g.location;r[l+12]=g.ctrlKey;r[l+13]=g.shiftKey;r[l+14]=g.altKey;r[l+15]=g.metaKey;r[l+16]=g.repeat;u[n+5]=g.charCode;u[n+6]=g.keyCode;u[n+7]=g.which;M(g.key||"",l+32,32);M(g.code||"",l+64,32);M(g.char||"",l+96,32);M(g.locale||"",l+128,32);L(d)(e,l,b)&&g.preventDefault()},Zb:c};return I(a)},lb=(a,b,c)=>{x[a>>3]=b.timeStamp;
var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=gb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,h)=>{H.kc||(H.kc=N(64));a=K(a);return I({target:a,mc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Xb:h,$b:d,ac:(g=event)=>{lb(H.kc,g,a);L(d)(e,H.kc,b)&&g.preventDefault()},Zb:c})},mb=(a,b,
c,d,e)=>{H.qc||(H.qc=N(257));return I({target:a,Xb:e,$b:d,ac:(h=event)=>{var g=H.qc,l=document.pointerLockElement||document.ec||document.xc||document.wc;r[g]=!!l;var n=l?.id||"";M(db(l),g+1,128);M(n,g+129,128);L(d)(20,g,b)&&h.preventDefault()},Zb:c})},nb=(a,b,c,d,e)=>I({target:a,Xb:e,$b:d,ac:(h=event)=>{L(d)(38,0,b)&&h.preventDefault()},Zb:c}),ob=(a,b,c,d)=>{H.tc||(H.tc=N(36));a=K(a);return I({target:a,Xb:"resize",$b:d,ac:(e=event)=>{if(e.target==a){var h=document.body;if(h){var g=H.tc;u[g>>2]=0;
u[g+4>>2]=h.clientWidth;u[g+8>>2]=h.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;L(d)(10,g,b)&&e.preventDefault()}}},Zb:c})},pb=(a,b,c,d,e,h)=>{H.sc||(H.sc=N(1552));a=K(a);return I({target:a,mc:"touchstart"==h||"touchend"==h,Xb:h,$b:d,ac:g=>{var l={},n=g.touches;for(var q of n)q.Dc=q.Fc=0,l[q.identifier]=q;for(var y of g.changedTouches)y.Dc=1,l[y.identifier]=y;for(var P of g.targetTouches)l[P.identifier].Fc=
1;n=H.sc;x[n>>3]=g.timeStamp;r[n+12]=g.ctrlKey;r[n+13]=g.shiftKey;r[n+14]=g.altKey;r[n+15]=g.metaKey;q=n+16;y=gb(a);P=0;for(let E of Object.values(l))if(l=q>>2,u[l]=E.identifier,u[l+1]=E.screenX,u[l+2]=E.screenY,u[l+3]=E.clientX,u[l+4]=E.clientY,u[l+5]=E.pageX,u[l+6]=E.pageY,r[q+28]=E.Dc,r[q+29]=E.Fc,u[l+8]=E.clientX-(y.left|0),u[l+9]=E.clientY-(y.top|0),q+=48,31<++P)break;u[n+8>>2]=P;L(d)(e,n,b)&&g.preventDefault()},Zb:c})},Q,qb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=
(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,d,e,h,g))},rb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},sb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,
d)=>b.drawBuffersWEBGL(c,d))},tb=a=>{a.dd=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},ub=a=>{a.kd=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},vb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},wb=1,xb=[],R=[],yb=[],zb=[],Ab=[],S=[],Bb=[],Cb=[],T=[],Db={},Eb=4,Fb=0,Gb=a=>{for(var b=wb++,c=a.length;c<b;c++)a[c]=null;return b},Hb=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=Q[c](),g=h&&Gb(d);h?(h.name=g,d[g]=h):U||=1282;u[b+4*e>>2]=g}},Jb=(a,b)=>{a.ec||(a.ec=a.getContext,a.getContext=function(d,e){e=a.ec(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Ec?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?Ib(c,b):0},Ib=(a,b)=>{var c=Gb(Cb),d={handle:c,attributes:b,version:b.Ec,lc:a};a.canvas&&(a.canvas.Xc=d);Cb[c]=d;("undefined"==typeof b.Bc||b.Bc)&&Kb(d);return c},Kb=a=>{a||=V;if(!a.Uc){a.Uc=!0;var b=a.lc;b.Vc=b.getExtension("WEBGL_multi_draw");b.Tc=b.getExtension("EXT_polygon_offset_clamp");b.Sc=b.getExtension("EXT_clip_control");b.Wc=b.getExtension("WEBGL_polygon_mode");qb(b);rb(b);sb(b);tb(b);ub(b);2<=a.version&&(b.Ac=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||
!b.Ac)b.Ac=b.getExtension("EXT_disjoint_timer_query");vb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},U,V,Lb=(a,b,c,d,e,h)=>{a={target:K(a),Xb:h,$b:d,ac:(g=event)=>{L(d)(e,0,b)&&g.preventDefault()},Zb:c};I(a)},Mb=(a,b,c,d)=>{H.vc||(H.vc=N(96));return I({target:a,mc:!0,Xb:"wheel",$b:d,ac:(e=event)=>{var h=H.vc;lb(h,e,a);x[h+64>>3]=e.deltaX;x[h+72>>3]=e.deltaY;x[h+80>>3]=e.deltaZ;u[h+88>>2]=e.deltaMode;L(d)(9,h,b)&&e.preventDefault()},Zb:c})},Nb=["default","low-power",
"high-performance"],Ob=()=>{var a=vb(Q);return a=a.concat(a.map(b=>"GL_"+b))},Pb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Q.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=Ob().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=Q.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=
1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);
return}}break;default:U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else U||=1281},Qb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Rb=a=>{var b=Qb(a)+1,c=N(b);c&&M(a,c,b);return c},Sb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Tb=[],Ub=a=>{a-=5120;return 0==a?r:1==a?t:2==a?oa:4==a?u:6==a?w:5==a||28922==a||28520==a||30779==a||30782==
a?v:pa},Vb=(a,b,c,d,e)=>{a=Ub(a);b=d*((Fb||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Eb-1&-Eb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=Q.Qc;if(b){var c=b.fc[a];"number"==typeof c&&(b.fc[a]=c=Q.getUniformLocation(b,b.Nc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],Wb=[],Yb=a=>{var b=Qb(a)+1,c=Xb(b);M(a,c,b);return c},ac=a=>{var b=Zb();a();$b(b)};
f.requestAnimationFrame=Pa;f.pauseMainLoop=ab;f.resumeMainLoop=function(){Sa++;var a=La,b=Ma,c=C;C=null;$a(c,0,!1,Ta,!0);Ra(a,b);D()};f.preMainLoop&&Ya.push(f.preMainLoop);f.postMainLoop&&Za.push(f.postMainLoop);for(var Y=0;32>Y;++Y)Tb.push(Array(Y));var bc=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=bc.subarray(0,Y);var cc=new Int32Array(288);for(Y=0;288>=Y;++Y)Wb[Y]=cc.subarray(0,Y);
var jc={$a:()=>wa(""),_a:(a,b,c)=>t.copyWithin(a,b,b+c),Xa:()=>{Ea=!1;Fa=0},Ya:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];Ka(()=>dc(a,performance.now()))},b);B[a]={id:c,vd:b};return 0},Ma:()=>{ab();C=null},_:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,aa:(a,b,c)=>{a=K(a);if(!a)return-4;a=gb(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},Na:()=>performance.now(),Ua:(a,b)=>{function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
Za:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ma.buffer.byteLength+65535)/65536|0;try{ma.grow(d);qa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},I:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),Z:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},J:(a,b,c,d)=>jb(a,b,c,d,13,"focus"),S:(a,b,c,d)=>kb(a,b,c,d,2,"keydown"),Q:(a,b,c,d)=>kb(a,b,c,d,1,"keypress"),
R:(a,b,c,d)=>kb(a,b,c,d,3,"keyup"),Va:(a,b,c)=>{a=L(a);$a(a,b,c)},Y:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),V:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),U:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),W:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),X:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),L:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.ec||document.body.xc||document.body.wc))return-1;a=K(a);if(!a)return-4;mb(a,b,c,d,"mozpointerlockchange");mb(a,b,c,d,"webkitpointerlockchange");mb(a,
b,c,d,"mspointerlockchange");return mb(a,b,c,d,"pointerlockchange")},K:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.ec||document.body.xc||document.body.wc))return-1;a=K(a);if(!a)return-4;nb(a,b,c,d,"mozpointerlockerror");nb(a,b,c,d,"webkitpointerlockerror");nb(a,b,c,d,"mspointerlockerror");return nb(a,b,c,d,"pointerlockerror")},$:(a,b,c,d)=>ob(a,b,c,d),M:(a,b,c,d)=>pb(a,b,c,d,25,"touchcancel"),N:(a,b,c,d)=>pb(a,b,c,d,23,"touchend"),O:(a,b,c,d)=>pb(a,b,c,d,24,"touchmove"),
P:(a,b,c,d)=>pb(a,b,c,d,22,"touchstart"),H:(a,b,c,d)=>{Lb(a,b,c,d,31,"webglcontextlost");return 0},G:(a,b,c,d)=>{Lb(a,b,c,d,32,"webglcontextrestored");return 0},T:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?Mb(a,b,c,d):-1:-4,Ta:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Nb[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Ec:u[c+4],md:u[c+5],Bc:r[b+24],Rc:r[b+25],od:u[c+7],sd:r[b+
32]};a=K(a);return!a||b.Rc?0:Jb(a,b)},Qa:(a,b)=>{a=Cb[a];b=b?J(b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&qb(Q);"OES_vertex_array_object"==b&&rb(Q);"WEBGL_draw_buffers"==b&&sb(Q);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&tb(Q);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&ub(Q);"WEBGL_multi_draw"==b&&(Q.Vc=Q.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(Q.Tc=Q.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&
(Q.Sc=Q.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(Q.Wc=Q.getExtension("WEBGL_polygon_mode"));return!!a.lc.getExtension(b)},Sa:a=>{V=Cb[a];f.ctx=Q=V?.lc;return!a||Q?0:-5},j:a=>Q.activeTexture(a),v:(a,b)=>{Q.attachShader(R[a],S[b])},b:(a,b)=>{35051==a?Q.zc=b:35052==a&&(Q.bc=b);Q.bindBuffer(a,xb[b])},a:(a,b,c)=>{Q.bindBufferBase(a,b,xb[c])},m:(a,b)=>{Q.bindFramebuffer(a,yb[b])},i:(a,b)=>{Q.bindSampler(a,T[b])},c:(a,b)=>{Q.bindTexture(a,Ab[b])},F:a=>{Q.bindVertexArray(Bb[a])},B:(a,b,
c,d)=>Q.blendColor(a,b,c,d),C:(a,b)=>Q.blendEquationSeparate(a,b),D:(a,b,c,d)=>Q.blendFuncSeparate(a,b,c,d),db:(a,b,c,d,e,h,g,l,n,q)=>Q.blitFramebuffer(a,b,c,d,e,h,g,l,n,q),ya:(a,b,c,d)=>{2<=V.version?c&&b?Q.bufferData(a,t,d,c,b):Q.bufferData(a,b,d):Q.bufferData(a,c?t.subarray(c,c+b):b,d)},xa:(a,b,c,d)=>{2<=V.version?c&&Q.bufferSubData(a,b,t,d,c):Q.bufferSubData(a,b,t.subarray(d,d+c))},wb:(a,b,c,d)=>Q.clearBufferfi(a,b,c,d),da:(a,b,c)=>{Q.clearBufferfv(a,b,w,c>>2)},vb:(a,b,c)=>{Q.clearBufferiv(a,
b,u,c>>2)},k:(a,b,c,d)=>{Q.colorMask(!!a,!!b,!!c,!!d)},fa:a=>{Q.compileShader(S[a])},ra:(a,b,c,d,e,h,g,l)=>{2<=V.version?Q.bc||!g?Q.compressedTexImage2D(a,b,c,d,e,h,g,l):Q.compressedTexImage2D(a,b,c,d,e,h,t,l,g):Q.compressedTexImage2D(a,b,c,d,e,h,t.subarray(l,l+g))},pa:(a,b,c,d,e,h,g,l,n)=>{Q.bc?Q.compressedTexImage3D(a,b,c,d,e,h,g,l,n):Q.compressedTexImage3D(a,b,c,d,e,h,g,t,n,l)},ma:()=>{var a=Gb(R),b=Q.createProgram();b.name=a;b.jc=b.hc=b.ic=0;b.uc=1;R[a]=b;return a},ha:a=>{var b=Gb(S);S[b]=Q.createShader(a);
return b},y:a=>Q.cullFace(a),Ea:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=xb[d];e&&(Q.deleteBuffer(e),e.name=0,xb[d]=null,d==Q.zc&&(Q.zc=0),d==Q.bc&&(Q.bc=0))}},h:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=yb[d];e&&(Q.deleteFramebuffer(e),e.name=0,yb[d]=null)}},x:a=>{if(a){var b=R[a];b?(Q.deleteProgram(b),b.name=0,R[a]=null):U||=1281}},Ca:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=zb[d];e&&(Q.deleteRenderbuffer(e),e.name=0,zb[d]=null)}},Ba:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+
4*c>>2],e=T[d];e&&(Q.deleteSampler(e),e.name=0,T[d]=null)}},n:a=>{if(a){var b=S[a];b?(Q.deleteShader(b),S[a]=null):U||=1281}},Da:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Ab[d];e&&(Q.deleteTexture(e),e.name=0,Ab[d]=null)}},Aa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];Q.deleteVertexArray(Bb[d]);Bb[d]=null}},r:a=>Q.depthFunc(a),q:a=>{Q.depthMask(!!a)},e:a=>Q.disable(a),E:a=>{Q.disableVertexAttribArray(a)},fb:(a,b,c)=>{Q.drawArrays(a,b,c)},gb:(a,b,c,d)=>{Q.drawArraysInstanced(a,b,c,d)},hb:(a,
b,c,d)=>{Q.drawElements(a,b,c,d)},ib:(a,b,c,d,e)=>{Q.drawElementsInstanced(a,b,c,d,e)},g:a=>Q.enable(a),sb:a=>{Q.enableVertexAttribArray(a)},z:a=>Q.frontFace(a),za:(a,b)=>{Hb(a,b,"createBuffer",xb)},na:(a,b)=>{Hb(a,b,"createSampler",T)},wa:(a,b)=>{Hb(a,b,"createTexture",Ab)},La:(a,b)=>{Hb(a,b,"createVertexArray",Bb)},zb:(a,b)=>Q.getAttribLocation(R[a],b?J(b):""),d:(a,b)=>Pb(a,b),ja:(a,b,c,d)=>{a=Q.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},u:(a,b,c)=>
{if(c)if(a>=wb)U||=1281;else if(a=R[a],35716==b)a=Q.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.jc){var d=Q.getProgramParameter(a,35718);for(b=0;b<d;++b)a.jc=Math.max(a.jc,Q.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.jc}else if(35722==b){if(!a.hc)for(d=Q.getProgramParameter(a,35721),b=0;b<d;++b)a.hc=Math.max(a.hc,Q.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.hc}else if(35381==b){if(!a.ic)for(d=Q.getProgramParameter(a,35382),b=0;b<d;++b)a.ic=
Math.max(a.ic,Q.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.ic}else u[c>>2]=Q.getProgramParameter(a,b);else U||=1281},Ab:(a,b,c,d)=>{a=Q.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},s:(a,b,c)=>{c?35716==b?(a=Q.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(S[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=Q.getShaderParameter(S[a],b):U||=1281},Ja:(a,b)=>{if(2>V.version)return U||=1282,0;var c=Db[a];
if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Ob().map(Rb),c=Db[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},t:(a,b)=>{b=b?J(b):"";if(a=R[a]){var c=a,d=c.fc,e=c.Oc,h;if(!d){c.fc=d={};c.Nc={};var g=Q.getProgramParameter(c,35718);for(h=0;h<g;++h){var l=Q.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Sb(n);q=0<q?n.slice(0,q):n;var y=c.uc;c.uc+=l;e[q]=[l,y];for(n=0;n<l;++n)d[y]=n,c.Nc[y++]=q}}c=a.fc;d=0;e=b;h=Sb(b);0<h&&(d=parseInt(b.slice(h+1))>>>
0,e=b.slice(0,h));if((e=a.Oc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||Q.getUniformLocation(a,b)))return d}else U||=1281;return-1},cb:(a,b,c)=>{for(var d=Tb[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];Q.invalidateFramebuffer(a,d)},ka:a=>{a=R[a];Q.linkProgram(a);a.fc=0;a.Oc={}},Ka:(a,b)=>{3317==a?Eb=b:3314==a&&(Fb=b);Q.pixelStorei(a,b)},A:(a,b)=>Q.polygonOffset(a,b),eb:a=>Q.readBuffer(a),w:(a,b,c)=>{Q.samplerParameterf(T[a],b,c)},f:(a,b,c)=>{Q.samplerParameteri(T[a],b,c)},xb:(a,b,c,d)=>Q.scissor(a,b,c,d),ga:(a,b,c,d)=>
{for(var e="",h=0;h<b;++h){var g=(g=v[c+4*h>>2])?J(g,d?v[d+4*h>>2]:void 0):"";e+=g}Q.shaderSource(S[a],e)},Ha:(a,b,c)=>Q.stencilFunc(a,b,c),ca:(a,b,c,d)=>Q.stencilFuncSeparate(a,b,c,d),p:a=>Q.stencilMask(a),Ga:(a,b,c)=>Q.stencilOp(a,b,c),ba:(a,b,c,d)=>Q.stencilOpSeparate(a,b,c,d),qa:(a,b,c,d,e,h,g,l,n)=>{if(2<=V.version){if(Q.bc){Q.texImage2D(a,b,c,d,e,h,g,l,n);return}if(n){var q=Ub(l);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);Q.texImage2D(a,b,c,d,e,h,g,l,q,n);return}}q=n?Vb(l,g,d,e,n):null;Q.texImage2D(a,
b,c,d,e,h,g,l,q)},oa:(a,b,c,d,e,h,g,l,n,q)=>{if(Q.bc)Q.texImage3D(a,b,c,d,e,h,g,l,n,q);else if(q){var y=Ub(n);Q.texImage3D(a,b,c,d,e,h,g,l,n,y,q>>>31-Math.clz32(y.BYTES_PER_ELEMENT))}else Q.texImage3D(a,b,c,d,e,h,g,l,n,null)},va:(a,b,c)=>Q.texParameteri(a,b,c),ua:(a,b,c,d,e)=>Q.texStorage2D(a,b,c,d,e),sa:(a,b,c,d,e,h)=>Q.texStorage3D(a,b,c,d,e,h),bb:(a,b,c,d,e,h,g,l,n)=>{if(2<=V.version){if(Q.bc){Q.texSubImage2D(a,b,c,d,e,h,g,l,n);return}if(n){var q=Ub(l);Q.texSubImage2D(a,b,c,d,e,h,g,l,q,n>>>31-
Math.clz32(q.BYTES_PER_ELEMENT));return}}n=n?Vb(l,g,e,h,n):null;Q.texSubImage2D(a,b,c,d,e,h,g,l,n)},ab:(a,b,c,d,e,h,g,l,n,q,y)=>{if(Q.bc)Q.texSubImage3D(a,b,c,d,e,h,g,l,n,q,y);else if(y){var P=Ub(q);Q.texSubImage3D(a,b,c,d,e,h,g,l,n,q,P,y>>>31-Math.clz32(P.BYTES_PER_ELEMENT))}else Q.texSubImage3D(a,b,c,d,e,h,g,l,n,q,null)},rb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform1fv(W(a),w,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);Q.uniform1fv(W(a),d)}},ia:(a,
b)=>{Q.uniform1i(W(a),b)},nb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=Wb[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);Q.uniform1iv(W(a),d)}},qb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform2fv(W(a),w,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);Q.uniform2fv(W(a),d)}},mb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=
Wb[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);Q.uniform2iv(W(a),d)}},pb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform3fv(W(a),w,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);Q.uniform3fv(W(a),d)}},lb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Wb[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=
u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);Q.uniform3iv(W(a),d)}},ob:(a,b,c)=>{if(2<=V.version)b&&Q.uniform4fv(W(a),w,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=w;c>>=2;b*=4;for(var h=0;h<b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);Q.uniform4fv(W(a),d)}},kb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Wb[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=
u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);Q.uniform4iv(W(a),d)}},jb:(a,b,c,d)=>{if(2<=V.version)b&&Q.uniformMatrix4fv(W(a),!!c,w,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);Q.uniformMatrix4fv(W(a),
!!c,e)}},l:a=>{a=R[a];Q.useProgram(a);Q.Qc=a},tb:(a,b)=>{Q.vertexAttribDivisor(a,b)},ub:(a,b,c,d,e,h)=>{Q.vertexAttribPointer(a,b,c,!!d,e,h)},yb:(a,b,c,d)=>Q.viewport(a,b,c,d),Wa:Ha,Cb:function(){f.Hc=a=>{0!=ec()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Hc)},Ra:function(){f.Mc=a=>{const b=a.clipboardData.getData("text");ac(()=>{const c=Yb(b);fc(c)})};window.addEventListener("paste",f.Mc)},Oa:function(){f.td=[];f.Ic=b=>{b.stopPropagation();b.preventDefault()};
f.Jc=b=>{b.stopPropagation();b.preventDefault()};f.Kc=b=>{b.stopPropagation();b.preventDefault()};f.Lc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.ud=c;gc(c.length);for(let e=0;e<c.length;e++)ac(()=>{const h=Yb(c[e].name);hc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);ic(b.clientX,b.clientY,d)};const a=f.dc;a.addEventListener("dragenter",f.Ic,!1);a.addEventListener("dragleave",f.Jc,!1);a.addEventListener("dragover",f.Kc,!1);
a.addEventListener("drop",f.Lc,!1)},ta:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Fa:function(a){a=a?J(a):"";void 0!==f.canvas&&("object"===typeof f.canvas?fb[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.dc=K(a);f.dc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.dc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Bb:function(){window.removeEventListener("beforeunload",
f.Hc)},Pa:function(){window.removeEventListener("paste",f.Mc)},Ia:function(){const a=f.dc;a.removeEventListener("dragenter",f.Ic);a.removeEventListener("dragleave",f.Jc);a.removeEventListener("dragover",f.Kc);a.removeEventListener("drop",f.Lc)},o:function(){f.dc&&f.dc.requestPointerLock&&f.dc.requestPointerLock()},la:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(t.subarray(c,c+a*b*4));e.putImageData(h,0,
0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},ea:function(a,b){b=b?J(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;ma=Z.Db;qa();ib=Z.Tb;sa.unshift(Z.Eb);z--;f.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;f.monitorRunDependencies?.(z);var b={a:jc};if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return m(`Module.instantiateWasm callback failed with error: ${c}`),!1}ya??=xa("dyntex-sapp.wasm")?"dyntex-sapp.wasm":f.locateFile?f.locateFile("dyntex-sapp.wasm",k):k+"dyntex-sapp.wasm";b=await Ba(b);a(b.instance);return b})();
var fc=f.__sapp_emsc_onpaste=a=>(fc=f.__sapp_emsc_onpaste=Z.Fb)(a),ec=f.__sapp_html5_get_ask_leave_site=()=>(ec=f.__sapp_html5_get_ask_leave_site=Z.Gb)(),gc=f.__sapp_emsc_begin_drop=a=>(gc=f.__sapp_emsc_begin_drop=Z.Hb)(a),hc=f.__sapp_emsc_drop=(a,b)=>(hc=f.__sapp_emsc_drop=Z.Ib)(a,b),ic=f.__sapp_emsc_end_drop=(a,b,c)=>(ic=f.__sapp_emsc_end_drop=Z.Jb)(a,b,c);f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,g,l)=>(f.__sapp_emsc_invoke_fetch_cb=Z.Kb)(a,b,c,d,e,h,g,l);
var kc=f._main=(a,b)=>(kc=f._main=Z.Lb)(a,b);f.__saudio_emsc_pull=a=>(f.__saudio_emsc_pull=Z.Mb)(a);f.__sfetch_emsc_head_response=(a,b)=>(f.__sfetch_emsc_head_response=Z.Nb)(a,b);f.__sfetch_emsc_get_response=(a,b,c)=>(f.__sfetch_emsc_get_response=Z.Ob)(a,b,c);f.__sfetch_emsc_failed_http_status=(a,b)=>(f.__sfetch_emsc_failed_http_status=Z.Pb)(a,b);f.__sfetch_emsc_failed_buffer_too_small=a=>(f.__sfetch_emsc_failed_buffer_too_small=Z.Qb)(a);
var N=a=>(N=Z.Rb)(a),dc=(a,b)=>(dc=Z.Sb)(a,b),$b=a=>($b=Z.Ub)(a),Xb=a=>(Xb=Z.Vb)(a),Zb=()=>(Zb=Z.Wb)(),lc;A=function mc(){lc||nc();lc||(A=mc)};function oc(a=[]){var b=kc;a.unshift(fa);var c=a.length,d=Xb(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=Yb(g);e+=4});v[e>>2]=0;try{var h=b(c,d);Ia(h)}catch(g){Ga(g)}}
function nc(){var a=ea;function b(){if(!lc&&(lc=!0,f.calledRun=!0,!p)){Da(sa);Da(ta);f.onRuntimeInitialized?.();pc&&oc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();ua.unshift(c)}Da(ua)}}if(!(0<z)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)va();Da(ra);0<z||(f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var pc=!0;f.noInitialRun&&(pc=!1);nc();
