var f;f||(f=typeof Module !== 'undefined' ? Module : {});var g={},l;for(l in f)f.hasOwnProperty(l)&&(g[l]=f[l]);var p=[],aa="./this.program";function t(a,b){throw b;}var u=!1,v=!1,ba=!1,ca=!1,ea=!1;u="object"===typeof window;v="function"===typeof importScripts;ba=(ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!u&&!v;ea=!u&&!ba&&!v;var w="",fa,x,ha,ia;
if(ba)w=__dirname+"/",fa=function(a,b){ha||(ha=require("fs"));ia||(ia=require("path"));a=ia.normalize(a);return ha.readFileSync(a,b?null:"utf8")},x=function(a){a=fa(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),p=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof ja))throw a;}),process.on("unhandledRejection",ka),t=function(a){process.exit(a)},
f.inspect=function(){return"[Emscripten Module object]"};else if(ea)"undefined"!=typeof read&&(fa=function(a){return read(a)}),x=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?p=scriptArgs:"undefined"!=typeof arguments&&(p=arguments),"function"===typeof quit&&(t=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=
console.error="undefined"!==typeof printErr?printErr:print);else if(u||v)v?w=self.location.href:document.currentScript&&(w=document.currentScript.src),w=0!==w.indexOf("blob:")?w.substr(0,w.lastIndexOf("/")+1):"",fa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(x=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var la=f.print||console.log.bind(console),z=f.printErr||console.warn.bind(console);for(l in g)g.hasOwnProperty(l)&&(f[l]=g[l]);g=null;f.arguments&&(p=f.arguments);f.thisProgram&&(aa=f.thisProgram);f.quit&&(t=f.quit);var A;f.wasmBinary&&(A=f.wasmBinary);var B;f.noExitRuntime&&(B=f.noExitRuntime);"object"!==typeof WebAssembly&&z("no native wasm support detected");var C,ma=new WebAssembly.Table({initial:83,maximum:83,element:"anyfunc"}),na=!1;function assert(a,b){a||ka("Assertion failed: "+b)}
function oa(){var a=f.__sapp_emsc_onpaste;assert(a,"Cannot call unknown function _sapp_emsc_onpaste, make sure it is exported");return a}function pa(a){var b=["string"],c={string:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=D(c);E(a,F,b,c)}return b},array:function(a){var b=D(a.length);qa.set(a,b);return b}},d=oa(),e=[],h=0;if(a)for(var k=0;k<a.length;k++){var m=c[b[k]];m?(0===h&&(h=ra()),e[k]=m(a[k])):e[k]=a[k]}d.apply(null,e);0!==h&&sa(h)}
var ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function G(a,b){if(a){var c=F,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&ta)a=ta.decode(c.subarray(a,b));else{for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var k=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|k:(e&7)<<18|h<<12|k<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}a=d}}else a="";return a}
function E(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);if(55296<=k&&57343>=k){var m=a.charCodeAt(++h);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function va(a){var b=ua(a)+1,c=D(b);E(a,qa,c,b);return c}var buffer,qa,F,wa,xa,H,ya,I,J;
function za(a){buffer=a;f.HEAP8=qa=new Int8Array(a);f.HEAP16=wa=new Int16Array(a);f.HEAP32=H=new Int32Array(a);f.HEAPU8=F=new Uint8Array(a);f.HEAPU16=xa=new Uint16Array(a);f.HEAPU32=ya=new Uint32Array(a);f.HEAPF32=I=new Float32Array(a);f.HEAPF64=J=new Float64Array(a)}var Aa=f.TOTAL_MEMORY||33554432;f.wasmMemory?C=f.wasmMemory:C=new WebAssembly.Memory({initial:Aa/65536});C&&(buffer=C.buffer);Aa=buffer.byteLength;za(buffer);H[396380]=6828560;
function Ba(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.fc;"number"===typeof c?void 0===b.Xb?f.dynCall_v(c):f.dynCall_vi(c,b.Xb):c(void 0===b.Xb?null:b.Xb)}}}var Ca=[],Da=[],Ea=[],Fa=[],Ga=[];function Ha(){var a=f.preRun.shift();Ca.unshift(a)}var K=0,Ia=null,Ja=null;f.preloadedImages={};f.preloadedAudios={};function ka(a){if(f.onAbort)f.onAbort(a);la(a);z(a);na=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function Ka(){var a=L;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var L="dyntex-sapp-ui.wasm";if(!Ka()){var La=L;L=f.locateFile?f.locateFile(La,w):w+La}function Ma(){try{if(A)return new Uint8Array(A);if(x)return x(L);throw"both async and sync fetching of the wasm failed";}catch(a){ka(a)}}
function Na(){return A||!u&&!v||"function"!==typeof fetch?new Promise(function(a){a(Ma())}):fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ma()})}Da.push({fc:function(){Oa()}});var Pa=0,Qa=0,M=0,Ra=0,Sa=0,Ta=null,Ua=null,Va=!1;function Wa(){for(var a=N.length-1;0<=a;--a)Xa(a);N=[];Ya=[]}var Ya=[];
function Za(){if($a&&ab.Vb)for(var a=0;a<Ya.length;++a){var b=Ya[a];Ya.splice(a,1);--a;b.qc.apply(this,b.kc)}}var $a=0,ab=null,N=[];function Xa(a){var b=N[a];b.target.removeEventListener(b.Ob,b.dc,b.Qb);N.splice(a,1)}function O(a){function b(b){++$a;ab=a;Za();a.Sb(b);Za();--$a}if(a.Rb)a.dc=b,a.target.addEventListener(a.Ob,b,a.Qb),N.push(a),Va||(Fa.push(Wa),Va=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Ob==a.Ob&&Xa(c--)}function bb(a){return a===a+0?G(a):a}
var cb=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function P(a){return cb[a]||("undefined"!==typeof document?document.querySelector(bb(a)):void 0)}
function db(a,b,c,d,e,h){Pa||(Pa=Q(164));a={target:P(a),Vb:!0,Ob:h,Rb:d,Sb:function(a){a=a||event;var c=Pa;E(a.key?a.key:"",F,c+0,32);E(a.code?a.code:"",F,c+32,32);H[c+64>>2]=a.location;H[c+68>>2]=a.ctrlKey;H[c+72>>2]=a.shiftKey;H[c+76>>2]=a.altKey;H[c+80>>2]=a.metaKey;H[c+84>>2]=a.repeat;E(a.locale?a.locale:"",F,c+88,32);E(a.char?a.char:"",F,c+120,32);H[c+152>>2]=a.charCode;H[c+156>>2]=a.keyCode;H[c+160>>2]=a.which;R(d,e,c,b)&&a.preventDefault()},Qb:c};O(a)}
function eb(a,b,c){H[a>>2]=b.screenX;H[a+4>>2]=b.screenY;H[a+8>>2]=b.clientX;H[a+12>>2]=b.clientY;H[a+16>>2]=b.ctrlKey;H[a+20>>2]=b.shiftKey;H[a+24>>2]=b.altKey;H[a+28>>2]=b.metaKey;wa[a+32>>1]=b.button;wa[a+34>>1]=b.buttons;var d=b.movementY||b.screenY-Ua;H[a+36>>2]=b.movementX||b.screenX-Ta;H[a+40>>2]=d;c=0>cb.indexOf(c)?c.getBoundingClientRect():{left:0,top:0};H[a+44>>2]=b.clientX-c.left;H[a+48>>2]=b.clientY-c.top;"wheel"!==b.type&&"mousewheel"!==b.type&&(Ta=b.screenX,Ua=b.screenY)}
function fb(a,b,c,d,e,h){Qa||(Qa=Q(64));a=P(a);O({target:a,Vb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Ob:h,Rb:d,Sb:function(c){c=c||event;eb(Qa,c,a);R(d,e,Qa,b)&&c.preventDefault()},Qb:c})}
function gb(a,b,c,d){Ra||(Ra=Q(36));a=P(a);O({target:a,Ob:"resize",Rb:d,Sb:function(c){c=c||event;if(c.target==a){var e=Ra,k=document.body;H[e>>2]=c.detail;H[e+4>>2]=k.clientWidth;H[e+8>>2]=k.clientHeight;H[e+12>>2]=innerWidth;H[e+16>>2]=innerHeight;H[e+20>>2]=outerWidth;H[e+24>>2]=outerHeight;H[e+28>>2]=pageXOffset;H[e+32>>2]=pageYOffset;R(d,10,e,b)&&c.preventDefault()}},Qb:c})}
function hb(a,b,c,d,e,h){Sa||(Sa=Q(1684));a=P(a);O({target:a,Vb:"touchstart"==h||"touchend"==h,Ob:h,Rb:d,Sb:function(c){c=c||event;for(var h={},k=0;k<c.touches.length;++k){var q=c.touches[k];q.Zb=!1;h[q.identifier]=q}for(k=0;k<c.changedTouches.length;++k)q=c.changedTouches[k],h[q.identifier]=q,q.Zb=!0;for(k=0;k<c.targetTouches.length;++k)q=c.targetTouches[k],h[q.identifier].ic=!0;var r=q=Sa;H[r+4>>2]=c.ctrlKey;H[r+8>>2]=c.shiftKey;H[r+12>>2]=c.altKey;H[r+16>>2]=c.metaKey;r+=20;var da=a.getBoundingClientRect(),
mb=0;for(k in h){var y=h[k];H[r>>2]=y.identifier;H[r+4>>2]=y.screenX;H[r+8>>2]=y.screenY;H[r+12>>2]=y.clientX;H[r+16>>2]=y.clientY;H[r+20>>2]=y.pageX;H[r+24>>2]=y.pageY;H[r+28>>2]=y.Zb;H[r+32>>2]=y.ic;H[r+36>>2]=y.clientX-da.left;H[r+40>>2]=y.clientY-da.top;r+=52;if(32<=++mb)break}H[q>>2]=mb;R(d,e,q,b)&&c.preventDefault()},Qb:c})}function ib(a,b,c,d,e,h){a={target:P(a),Ob:h,Rb:d,Sb:function(a){a=a||event;R(d,e,0,b)&&a.preventDefault()},Qb:c};O(a)}
function jb(a,b,c,d,e){function h(c){c=c||event;eb(M,c,a);J[M+64>>3]=c.wheelDeltaX||0;J[M+72>>3]=-(c.wheelDeltaY||c.wheelDelta);J[M+80>>3]=0;H[M+88>>2]=0;R(d,9,M,b)&&c.preventDefault()}function k(c){c=c||event;var e=M;eb(e,c,a);J[e+64>>3]=c.deltaX;J[e+72>>3]=c.deltaY;J[e+80>>3]=c.deltaZ;H[e+88>>2]=c.deltaMode;R(d,9,e,b)&&c.preventDefault()}M||(M=Q(96));O({target:a,Vb:!0,Ob:e,Rb:d,Sb:"wheel"==e?k:h,Qb:c})}
function kb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(a,d){b.vertexAttribDivisorANGLE(a,d)},a.drawArraysInstanced=function(a,d,e,h){b.drawArraysInstancedANGLE(a,d,e,h)},a.drawElementsInstanced=function(a,d,e,h,k){b.drawElementsInstancedANGLE(a,d,e,h,k)})}
function lb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(a){b.deleteVertexArrayOES(a)},a.bindVertexArray=function(a){b.bindVertexArrayOES(a)},a.isVertexArray=function(a){return b.isVertexArrayOES(a)})}function nb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(a,d){b.drawBuffersWEBGL(a,d)})}
var ob=1,pb=0,qb=[],S=[],rb=[],sb=[],tb=[],T=[],U=[],ub=[],vb={},V=null,wb={},xb={},yb={};function W(a){pb||(pb=a)}function zb(a){for(var b=ob++,c=a.length;c<b;c++)a[c]=null;return b}var X=[0];
function Ab(a){a||(a=V);if(!a.hc){a.hc=!0;var b=a.Wb;2>a.version&&(kb(b),lb(b),nb(b));b.mc=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(a){-1!=c.indexOf(a)&&b.getExtension(a)})}}var Bb,Cb,Db=["default","low-power","high-performance"],Eb=[];function Fb(a,b,c,d){for(var e=0;e<a;e++){var h=Y[c](),k=h&&zb(d);h?(h.name=k,d[k]=h):W(1282);H[b+4*e>>2]=k}}
function Gb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Y.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){W(1282);return}c=2*(Y.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>V.version){W(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=Y.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=
0;break;default:W(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)H[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){W(1280);z("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:W(1280);z("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}H[b>>2]=c}else W(1281)}
function Hb(a){var b=ua(a)+1,c=Q(b);E(a,F,c,b);return c}function Ib(a){a-=5120;return 0==a?qa:1==a?F:2==a?wa:4==a?H:6==a?I:5==a||28922==a||28520==a||30779==a||30782==a?ya:xa}function Jb(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Kb(a,b,c,d,e){a=Ib(a);var h=Jb(a);return a.subarray(e>>h,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<h)+4-1&-4)>>h)}for(var Y,Lb=new Float32Array(256),Z=0;256>Z;Z++)X[Z]=Lb.subarray(0,Z+1);for(Z=0;256>Z;Z++);
for(var Mb=0;32>Mb;Mb++)Eb.push(Array(Mb));
var Tb={Y:function(){return devicePixelRatio||1},ba:function(a,b,c){a=P(a);if(!a)return-4;a=a.getBoundingClientRect();J[b>>3]=a.width;J[c>>3]=a.height;return 0},Ya:function(a,b,c){F.set(F.subarray(b,b+c),a)},Ka:function(a,b){function c(d){Nb(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Za:function(a){var b=qa.length;if(2147418112<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{C.grow(Math.min(2147418112,
d)-buffer.byteLength+65535>>16);za(C.buffer);var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},S:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ua:function(a,b,c,d){db(a,b,c,d,2,"keydown");return 0},Sa:function(a,b,c,d){db(a,b,c,d,1,"keypress");return 0},Ta:function(a,b,c,d){db(a,b,c,d,3,"keyup");return 0},ja:function(a,b,c,d){fb(a,b,c,d,5,"mousedown");return 0},Xa:function(a,b,c,d){fb(a,b,c,d,33,"mouseenter");return 0},Wa:function(a,b,c,d){fb(a,b,c,d,34,"mouseleave");
return 0},ab:function(a,b,c,d){fb(a,b,c,d,8,"mousemove");return 0},gb:function(a,b,c,d){fb(a,b,c,d,6,"mouseup");return 0},Pa:function(a,b,c,d){gb(a,b,c,d);return 0},Na:function(a,b,c,d){hb(a,b,c,d,25,"touchcancel");return 0},Oa:function(a,b,c,d){hb(a,b,c,d,23,"touchend");return 0},Qa:function(a,b,c,d){hb(a,b,c,d,24,"touchmove");return 0},Ra:function(a,b,c,d){hb(a,b,c,d,22,"touchstart");return 0},Ma:function(a,b,c,d){ib(a,b,c,d,31,"webglcontextlost");return 0},La:function(a,b,c,d){ib(a,b,c,d,32,"webglcontextrestored");
return 0},Va:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(jb(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(jb(a,b,c,d,"mousewheel"),0):-1},L:function(a,b){var c={};b>>=2;c.alpha=!!H[b];c.depth=!!H[b+1];c.stencil=!!H[b+2];c.antialias=!!H[b+3];c.premultipliedAlpha=!!H[b+4];c.preserveDrawingBuffer=!!H[b+5];c.powerPreference=Db[H[b+6]];c.failIfMajorPerformanceCaveat=!!H[b+7];c.bc=H[b+8];c.nc=H[b+9];c.ac=H[b+10];c.ec=H[b+11];c.oc=H[b+12];c.pc=H[b+13];a=P(a);if(!a||c.ec)c=0;
else if(a=1<c.bc?a.getContext("webgl2",c):a.getContext("webgl",c)){b=Q(8);var d={handle:b,attributes:c,version:c.bc,Wb:a};a.canvas&&(a.canvas.jc=d);vb[b]=d;("undefined"===typeof c.ac||c.ac)&&Ab(d);c=b}else c=0;return c},oa:function(a,b){a=vb[a];b=G(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b?kb(Y):"OES_vertex_array_object"==b?lb(Y):"WEBGL_draw_buffers"==b&&nb(Y);return!!a.Wb.getExtension(b)},Ba:function(a){a>>=2;for(var b=0;14>b;++b)H[a+b]=0;H[a]=H[a+1]=H[a+3]=H[a+4]=H[a+8]=
H[a+10]=1},sa:function(a){V=vb[a];f.lc=Y=V&&V.Wb;return!a||Y?0:-5},g:function(a){Y.activeTexture(a)},N:function(a,b){Y.attachShader(S[a],U[b])},b:function(a,b){35051==a?Y.$b=b:35052==a&&(Y.Pb=b);Y.bindBuffer(a,qb[b])},h:function(a,b){Y.bindFramebuffer(a,rb[b])},Q:function(a,b){Y.bindRenderbuffer(a,sb[b])},a:function(a,b){Y.bindTexture(a,tb[b])},X:function(a){Y.bindVertexArray(ub[a])},D:function(a,b,c,d){Y.blendColor(a,b,c,d)},E:function(a,b){Y.blendEquationSeparate(a,b)},F:function(a,b,c,d){Y.blendFuncSeparate(a,
b,c,d)},k:function(a,b,c,d,e,h,k,m,n,q){Y.blitFramebuffer(a,b,c,d,e,h,k,m,n,q)},T:function(a,b,c,d){2<=V.version?c?Y.bufferData(a,F,d,c,b):Y.bufferData(a,b,d):Y.bufferData(a,c?F.subarray(c,c+b):b,d)},n:function(a,b,c,d){2<=V.version?Y.bufferSubData(a,b,F,d,c):Y.bufferSubData(a,b,F.subarray(d,d+c))},I:function(a){Y.clear(a)},ra:function(a,b,c,d){Y.clearColor(a,b,c,d)},qa:function(a){Y.clearDepth(a)},pa:function(a){Y.clearStencil(a)},v:function(a,b,c,d){Y.colorMask(!!a,!!b,!!c,!!d)},$a:function(a){Y.compileShader(U[a])},
Aa:function(a,b,c,d,e,h,k,m){2<=V.version?Y.Pb?Y.compressedTexImage2D(a,b,c,d,e,h,k,m):Y.compressedTexImage2D(a,b,c,d,e,h,F,m,k):Y.compressedTexImage2D(a,b,c,d,e,h,m?F.subarray(m,m+k):null)},ya:function(a,b,c,d,e,h,k,m,n){Y.Pb?Y.compressedTexImage3D(a,b,c,d,e,h,k,m,n):Y.compressedTexImage3D(a,b,c,d,e,h,k,F,n,m)},wa:function(){var a=zb(S),b=Y.createProgram();b.name=a;S[a]=b;return a},cb:function(a){var b=zb(U);U[b]=Y.createShader(a);return b},C:function(a){Y.cullFace(a)},W:function(a,b){for(var c=
0;c<a;c++){var d=H[b+4*c>>2],e=qb[d];e&&(Y.deleteBuffer(e),e.name=0,qb[d]=null,d==Bb&&(Bb=0),d==Cb&&(Cb=0),d==Y.$b&&(Y.$b=0),d==Y.Pb&&(Y.Pb=0))}},i:function(a,b){for(var c=0;c<a;++c){var d=H[b+4*c>>2],e=rb[d];e&&(Y.deleteFramebuffer(e),e.name=0,rb[d]=null)}},x:function(a){if(a){var b=S[a];b?(Y.deleteProgram(b),b.name=0,S[a]=null,wb[a]=null):W(1281)}},o:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],e=sb[d];e&&(Y.deleteRenderbuffer(e),e.name=0,sb[d]=null)}},w:function(a){if(a){var b=U[a];b?(Y.deleteShader(b),
U[a]=null):W(1281)}},V:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],e=tb[d];e&&(Y.deleteTexture(e),e.name=0,tb[d]=null)}},Ea:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2];Y.deleteVertexArray(ub[d]);ub[d]=null}},t:function(a){Y.depthFunc(a)},u:function(a){Y.depthMask(!!a)},c:function(a){Y.disable(a)},y:function(a){Y.disableVertexAttribArray(a)},ca:function(a,b,c){Y.drawArrays(a,b,c)},m:function(a,b){for(var c=Eb[a],d=0;d<a;d++)c[d]=H[b+4*d>>2];Y.drawBuffers(c)},da:function(a,b,c,d){Y.drawElements(a,
b,c,d)},e:function(a){Y.enable(a)},ka:function(a){Y.enableVertexAttribArray(a)},B:function(a){Y.frontFace(a)},U:function(a,b){Fb(a,b,"createBuffer",qb)},R:function(a,b){Fb(a,b,"createRenderbuffer",sb)},Ca:function(a,b){Fb(a,b,"createTexture",tb)},Fa:function(a,b){Fb(a,b,"createVertexArray",ub)},ta:function(a,b){return Y.getAttribLocation(S[a],G(b))},d:function(a,b){Gb(a,b)},ua:function(a,b,c,d){a=Y.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,F,d,b):0;c&&(H[c>>2]=b)},M:function(a,
b,c){if(c)if(a>=ob)W(1281);else{var d=wb[a];if(d)if(35716==b)a=Y.getProgramInfoLog(S[a]),null===a&&(a="(unknown error)"),H[c>>2]=a.length+1;else if(35719==b)H[c>>2]=d.Yb;else if(35722==b){if(-1==d.Tb){a=S[a];var e=Y.getProgramParameter(a,35721);for(b=d.Tb=0;b<e;++b)d.Tb=Math.max(d.Tb,Y.getActiveAttrib(a,b).name.length+1)}H[c>>2]=d.Tb}else if(35381==b){if(-1==d.Ub)for(a=S[a],e=Y.getProgramParameter(a,35382),b=d.Ub=0;b<e;++b)d.Ub=Math.max(d.Ub,Y.getActiveUniformBlockName(a,b).length+1);H[c>>2]=d.Ub}else H[c>>
2]=Y.getProgramParameter(S[a],b);else W(1282)}else W(1281)},_a:function(a,b,c,d){a=Y.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,F,d,b):0;c&&(H[c>>2]=b)},_:function(a,b,c){c?35716==b?(a=Y.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),H[c>>2]=a.length+1):35720==b?(a=Y.getShaderSource(U[a]),H[c>>2]=null===a||0==a.length?0:a.length+1):H[c>>2]=Y.getShaderParameter(U[a],b):W(1281)},Ha:function(a){if(xb[a])return xb[a];switch(a){case 7939:var b=Y.getSupportedExtensions()||
[];b=b.concat(b.map(function(a){return"GL_"+a}));b=Hb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Y.getParameter(a))||W(1280);b=Hb(b);break;case 7938:b=Y.getParameter(7938);b=2<=V.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Hb(b);break;case 35724:b=Y.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Hb(b);break;default:return W(1280),0}return xb[a]=b},
Ga:function(a,b){if(2>V.version)return W(1282),0;var c=yb[a];if(c)return 0>b||b>=c.length?(W(1281),0):c[b];switch(a){case 7939:return c=Y.getSupportedExtensions()||[],c=c.concat(c.map(function(a){return"GL_"+a})),c=c.map(function(a){return Hb(a)}),c=yb[a]=c,0>b||b>=c.length?(W(1281),0):c[b];default:return W(1280),0}},j:function(a,b){b=G(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=wb[a]&&wb[a].cc[b])&&0<=c&&c<a[0]?a[1]+c:
-1},va:function(a){Y.linkProgram(S[a]);var b=S[a];a=wb[a]={cc:{},Yb:0,Tb:-1,Ub:-1};for(var c=a.cc,d=Y.getProgramParameter(b,35718),e=0;e<d;++e){var h=Y.getActiveUniform(b,e),k=h.name;a.Yb=Math.max(a.Yb,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,k.lastIndexOf("[")));var m=Y.getUniformLocation(b,k);if(m){var n=zb(T);c[k]=[h.size,n];T[n]=m;for(var q=1;q<h.size;++q)m=Y.getUniformLocation(b,k+"["+q+"]"),n=zb(T),T[n]=m}}},A:function(a,b){Y.polygonOffset(a,b)},l:function(a){Y.readBuffer(a)},Da:function(a,
b,c,d){Y.renderbufferStorage(a,b,c,d)},P:function(a,b,c,d,e){Y.renderbufferStorageMultisample(a,b,c,d,e)},J:function(a,b,c,d){Y.scissor(a,b,c,d)},bb:function(a,b,c,d){for(var e="",h=0;h<b;++h){var k=d?H[d+4*h>>2]:-1;e+=G(H[c+4*h>>2],0>k?void 0:k)}Y.shaderSource(U[a],e)},fb:function(a,b,c){Y.stencilFunc(a,b,c)},H:function(a,b,c,d){Y.stencilFuncSeparate(a,b,c,d)},s:function(a){Y.stencilMask(a)},eb:function(a,b,c){Y.stencilOp(a,b,c)},G:function(a,b,c,d){Y.stencilOpSeparate(a,b,c,d)},za:function(a,b,
c,d,e,h,k,m,n){if(2<=V.version)if(Y.Pb)Y.texImage2D(a,b,c,d,e,h,k,m,n);else if(n){var q=Ib(m);Y.texImage2D(a,b,c,d,e,h,k,m,q,n>>Jb(q))}else Y.texImage2D(a,b,c,d,e,h,k,m,null);else Y.texImage2D(a,b,c,d,e,h,k,m,n?Kb(m,k,d,e,n):null)},xa:function(a,b,c,d,e,h,k,m,n,q){if(Y.Pb)Y.texImage3D(a,b,c,d,e,h,k,m,n,q);else if(q){var r=Ib(n);Y.texImage3D(a,b,c,d,e,h,k,m,n,r,q>>Jb(r))}else Y.texImage3D(a,b,c,d,e,h,k,m,n,null)},O:function(a,b,c){Y.texParameterf(a,b,c)},f:function(a,b,c){Y.texParameteri(a,b,c)},$:function(a,
b,c,d,e,h,k,m,n){if(2<=V.version)if(Y.Pb)Y.texSubImage2D(a,b,c,d,e,h,k,m,n);else if(n){var q=Ib(m);Y.texSubImage2D(a,b,c,d,e,h,k,m,q,n>>Jb(q))}else Y.texSubImage2D(a,b,c,d,e,h,k,m,null);else q=null,n&&(q=Kb(m,k,e,h,n)),Y.texSubImage2D(a,b,c,d,e,h,k,m,q)},aa:function(a,b,c,d,e,h,k,m,n,q,r){if(Y.Pb)Y.texSubImage3D(a,b,c,d,e,h,k,m,n,q,r);else if(r){var da=Ib(q);Y.texSubImage3D(a,b,c,d,e,h,k,m,n,q,da,r>>Jb(da))}else Y.texSubImage3D(a,b,c,d,e,h,k,m,n,q,null)},ia:function(a,b,c){if(2<=V.version)Y.uniform1fv(T[a],
I,c>>2,b);else{if(256>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=I[c+4*e>>2];else d=I.subarray(c>>2,c+4*b>>2);Y.uniform1fv(T[a],d)}},z:function(a,b){Y.uniform1i(T[a],b)},ha:function(a,b,c){if(2<=V.version)Y.uniform2fv(T[a],I,c>>2,2*b);else{if(256>=2*b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=I[c+4*e>>2],d[e+1]=I[c+(4*e+4)>>2];else d=I.subarray(c>>2,c+8*b>>2);Y.uniform2fv(T[a],d)}},ga:function(a,b,c){if(2<=V.version)Y.uniform3fv(T[a],I,c>>2,3*b);else{if(256>=3*b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=I[c+
4*e>>2],d[e+1]=I[c+(4*e+4)>>2],d[e+2]=I[c+(4*e+8)>>2];else d=I.subarray(c>>2,c+12*b>>2);Y.uniform3fv(T[a],d)}},fa:function(a,b,c){if(2<=V.version)Y.uniform4fv(T[a],I,c>>2,4*b);else{if(256>=4*b)for(var d=X[4*b-1],e=0;e<4*b;e+=4)d[e]=I[c+4*e>>2],d[e+1]=I[c+(4*e+4)>>2],d[e+2]=I[c+(4*e+8)>>2],d[e+3]=I[c+(4*e+12)>>2];else d=I.subarray(c>>2,c+16*b>>2);Y.uniform4fv(T[a],d)}},ea:function(a,b,c,d){if(2<=V.version)Y.uniformMatrix4fv(T[a],!!c,I,d>>2,16*b);else{if(256>=16*b)for(var e=X[16*b-1],h=0;h<16*b;h+=
16)e[h]=I[d+4*h>>2],e[h+1]=I[d+(4*h+4)>>2],e[h+2]=I[d+(4*h+8)>>2],e[h+3]=I[d+(4*h+12)>>2],e[h+4]=I[d+(4*h+16)>>2],e[h+5]=I[d+(4*h+20)>>2],e[h+6]=I[d+(4*h+24)>>2],e[h+7]=I[d+(4*h+28)>>2],e[h+8]=I[d+(4*h+32)>>2],e[h+9]=I[d+(4*h+36)>>2],e[h+10]=I[d+(4*h+40)>>2],e[h+11]=I[d+(4*h+44)>>2],e[h+12]=I[d+(4*h+48)>>2],e[h+13]=I[d+(4*h+52)>>2],e[h+14]=I[d+(4*h+56)>>2],e[h+15]=I[d+(4*h+60)>>2];else e=I.subarray(d>>2,d+64*b>>2);Y.uniformMatrix4fv(T[a],!!c,e)}},na:function(a){Y.useProgram(S[a])},la:function(a,b){Y.vertexAttribDivisor(a,
b)},ma:function(a,b,c,d,e,h){Y.vertexAttribPointer(a,b,c,!!d,e,h)},K:function(a,b,c,d){Y.viewport(a,b,c,d)},memory:C,r:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Ob()});document.body.append(a)},q:function(){document.getElementById("_sokol_app_input_element").focus()},Ja:function(){window.addEventListener("beforeunload",function(a){0!=Pb()&&(a.preventDefault(),a.returnValue=" ")})},
hb:function(){window.addEventListener("paste",function(a){a=a.clipboardData.getData("text");pa([a])})},p:function(){document.getElementById("_sokol_app_input_element").blur()},Ia:function(a){a=G(a);var b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);
b.select();document.execCommand("copy");document.body.removeChild(b)},db:function(a,b,c,d,e,h){b=G(b);var k=new XMLHttpRequest;k.open("GET",b);k.responseType="arraybuffer";var m=0<d;m&&k.setRequestHeader("Range","bytes="+c+"-"+(c+d));k.onreadystatechange=function(){if(this.readyState==this.DONE)if(206==this.status||200==this.status&&!m){var b=new Uint8Array(k.response),c=b.length;c<=h?(F.set(b,e),Qb(a,d,c)):Rb(a)}else Sb(a,this.status)};k.send()},Z:function(){return navigator.userAgent.includes("Macintosh")?
1:0},table:ma},Ub=function(){function a(a){f.asm=a.exports;K--;f.monitorRunDependencies&&f.monitorRunDependencies(K);0==K&&(null!==Ia&&(clearInterval(Ia),Ia=null),Ja&&(a=Ja,Ja=null,a()))}function b(b){a(b.instance)}function c(a){return Na().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){z("failed to asynchronously prepare wasm: "+a);ka(a)})}var d={env:Tb,wasi_snapshot_preview1:Tb};K++;f.monitorRunDependencies&&f.monitorRunDependencies(K);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return z("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(A||"function"!==typeof WebAssembly.instantiateStreaming||Ka()||"function"!==typeof fetch)return c(b);fetch(L,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){z("wasm streaming compile failed: "+a);z("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();f.asm=Ub;
var Oa=f.___wasm_call_ctors=function(){return(Oa=f.___wasm_call_ctors=f.asm.ib).apply(null,arguments)},Ob=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Ob=f.__sapp_emsc_notify_keyboard_hidden=f.asm.jb).apply(null,arguments)};f.___em_js__sapp_js_create_textfield=function(){return(f.___em_js__sapp_js_create_textfield=f.asm.kb).apply(null,arguments)};f.___em_js__sapp_js_focus_textfield=function(){return(f.___em_js__sapp_js_focus_textfield=f.asm.lb).apply(null,arguments)};
f.___em_js__sapp_js_unfocus_textfield=function(){return(f.___em_js__sapp_js_unfocus_textfield=f.asm.mb).apply(null,arguments)};f.__sapp_emsc_onpaste=function(){return(f.__sapp_emsc_onpaste=f.asm.nb).apply(null,arguments)};var Pb=f.__sapp_html5_get_ask_leave_site=function(){return(Pb=f.__sapp_html5_get_ask_leave_site=f.asm.ob).apply(null,arguments)};f.___em_js__sapp_js_hook_beforeunload=function(){return(f.___em_js__sapp_js_hook_beforeunload=f.asm.pb).apply(null,arguments)};
f.___em_js__sapp_js_init_clipboard=function(){return(f.___em_js__sapp_js_init_clipboard=f.asm.qb).apply(null,arguments)};f.___em_js__sapp_js_write_clipboard=function(){return(f.___em_js__sapp_js_write_clipboard=f.asm.rb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.sb).apply(null,arguments)};var Q=f._malloc=function(){return(Q=f._malloc=f.asm.tb).apply(null,arguments)};f._free=function(){return(f._free=f.asm.ub).apply(null,arguments)};
f.___em_js__stm_js_perfnow=function(){return(f.___em_js__stm_js_perfnow=f.asm.vb).apply(null,arguments)};f.__saudio_emsc_pull=function(){return(f.__saudio_emsc_pull=f.asm.wb).apply(null,arguments)};f.___em_js__saudio_js_init=function(){return(f.___em_js__saudio_js_init=f.asm.xb).apply(null,arguments)};f.___em_js__saudio_js_sample_rate=function(){return(f.___em_js__saudio_js_sample_rate=f.asm.yb).apply(null,arguments)};
f.___em_js__saudio_js_buffer_frames=function(){return(f.___em_js__saudio_js_buffer_frames=f.asm.zb).apply(null,arguments)};f.___em_js__sfetch_js_send_head_request=function(){return(f.___em_js__sfetch_js_send_head_request=f.asm.Ab).apply(null,arguments)};f.___em_js__sfetch_js_send_get_request=function(){return(f.___em_js__sfetch_js_send_get_request=f.asm.Bb).apply(null,arguments)};f.__sfetch_emsc_head_response=function(){return(f.__sfetch_emsc_head_response=f.asm.Cb).apply(null,arguments)};
var Qb=f.__sfetch_emsc_get_response=function(){return(Qb=f.__sfetch_emsc_get_response=f.asm.Db).apply(null,arguments)},Sb=f.__sfetch_emsc_failed_http_status=function(){return(Sb=f.__sfetch_emsc_failed_http_status=f.asm.Eb).apply(null,arguments)},Rb=f.__sfetch_emsc_failed_buffer_too_small=function(){return(Rb=f.__sfetch_emsc_failed_buffer_too_small=f.asm.Fb).apply(null,arguments)};f.___em_js__simgui_js_is_osx=function(){return(f.___em_js__simgui_js_is_osx=f.asm.Gb).apply(null,arguments)};
var ra=f.stackSave=function(){return(ra=f.stackSave=f.asm.Hb).apply(null,arguments)},D=f.stackAlloc=function(){return(D=f.stackAlloc=f.asm.Ib).apply(null,arguments)},sa=f.stackRestore=function(){return(sa=f.stackRestore=f.asm.Jb).apply(null,arguments)};f.dynCall_vi=function(){return(f.dynCall_vi=f.asm.Kb).apply(null,arguments)};f.dynCall_v=function(){return(f.dynCall_v=f.asm.Lb).apply(null,arguments)};
var R=f.dynCall_iiii=function(){return(R=f.dynCall_iiii=f.asm.Mb).apply(null,arguments)},Nb=f.dynCall_idi=function(){return(Nb=f.dynCall_idi=f.asm.Nb).apply(null,arguments)};f.asm=Ub;var Vb;function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ja=function Wb(){Vb||Xb();Vb||(Ja=Wb)};
function Xb(a){function b(){if(!Vb&&(Vb=!0,!na)){Ba(Da);Ba(Ea);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Yb){var b=a,d=f._main;b=b||[];var e=b.length+1,h=D(4*(e+1));H[h>>2]=va(aa);for(var k=1;k<e;k++)H[(h>>2)+k]=va(b[k-1]);H[(h>>2)+e]=0;try{var m=d(e,h);if(!B||0!==m){if(!B&&(na=!0,f.onExit))f.onExit(m);t(m,new ja(m))}}catch(n){n instanceof ja||("unwind"==n?B=!0:((b=n)&&"object"===typeof n&&n.stack&&(b=[n,n.stack]),z("exception thrown: "+b),t(1,n)))}finally{}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=f.postRun.shift(),Ga.unshift(b);Ba(Ga)}}a=a||p;if(!(0<K)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ha();Ba(Ca);0<K||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Xb;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Yb=!0;f.noInitialRun&&(Yb=!1);B=!0;Xb();
