var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},h="",ia,ja;
if(ca){var fs=require("fs"),ka=require("path");h=__dirname+"/";ja=a=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a)};ia=a=>{a=la(a)?new URL(a):ka.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof ma||a.context instanceof ma))throw a;
});ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?h=self.location.href:"undefined"!=typeof document&&document.currentScript&&(h=document.currentScript.src),h=h.startsWith("blob:")?"":h.substr(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=a=>la(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{(200==
d.status||0==d.status&&d.response)&&c(d.response);b(d.status)};d.onerror=b;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var na=f.print||console.log.bind(console),m=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);f.quit&&(ha=f.quit);var q;f.wasmBinary&&(q=f.wasmBinary);var oa,r=!1,t,u,v,pa,qa,w,x,z,A;
function ra(){var a=oa.buffer;f.HEAP8=u=new Int8Array(a);f.HEAP16=pa=new Int16Array(a);f.HEAPU8=v=new Uint8Array(a);f.HEAPU16=qa=new Uint16Array(a);f.HEAP32=w=new Int32Array(a);f.HEAPU32=x=new Uint32Array(a);f.HEAPF32=z=new Float32Array(a);f.HEAPF64=A=new Float64Array(a)}var sa=[],ta=[],ua=[],va=[];function wa(){var a=f.preRun.shift();sa.unshift(a)}var B=0,xa=null,C=null;
function ya(a){f.onAbort?.(a);a="Aborted("+a+")";m(a);r=!0;t=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Aa=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),Ba;function Ca(a){if(a==Ba&&q)return new Uint8Array(q);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}function Da(a){return q?Promise.resolve().then(()=>Ca(a)):ia(a).then(b=>new Uint8Array(b),()=>Ca(a))}
function Ea(a,b,c){return Da(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{m(`failed to asynchronously prepare wasm: ${d}`);ya(d)})}function Fa(a,b){var c=Ba;q||"function"!=typeof WebAssembly.instantiateStreaming||Aa(c)||la(c)||ca||"function"!=typeof fetch?Ea(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){m(`wasm streaming compile failed: ${e}`);m("falling back to ArrayBuffer instantiation");return Ea(c,a,b)}))}
function ma(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ga=a=>{for(;0<a.length;)a.shift()(f)},Ha=f.noExitRuntime||!0,Ia="undefined"!=typeof TextDecoder?new TextDecoder:void 0,D=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ia)return Ia.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var k=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|k<<6|g:(e&7)<<18|k<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|
e&1023))}}else d+=String.fromCharCode(e)}return d},Qa=(a,b)=>{Ja=a;Ka=b;if(E)if(La||=!0,0==a)G=function(){var d=Math.max(0,Ma+b-Na())|0;setTimeout(H,d)};else if(1==a)G=function(){Oa(H)};else if(2==a){if("undefined"==typeof Pa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Pa=function(d){c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);
postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Pa=setImmediate;G=function(){Pa(H)}}},Na;Na=()=>performance.now();
var Ya=(a,b,c,d,e)=>{E=a;Ra=d;var k=I;La=!1;H=function(){if(!r)if(0<Sa.length){var g=Sa.shift();g.Yc(g.Tc);if(Ta){var l=Ta,n=0==l%1?l-1:Math.floor(l);Ta=g.Vc?n:(8*l+(n+.5))/9}f.setStatus&&(g=f.statusMessage||"Please wait...",l=Ta,n=Ua.Xc,l?l<n?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(g):f.setStatus(""));k<I||setTimeout(H,0)}else if(!(k<I))if(Va=Va+1|0,1==Ja&&1<Ka&&0!=Va%Ka)G();else{0==Ja&&(Ma=Na());if(!(r||f.preMainLoop&&!1===f.preMainLoop())){if(!r)try{if(a(),!Ha)try{t=
g=t,Wa(g)}catch(p){Xa(p)}}catch(p){Xa(p)}f.postMainLoop?.()}k<I||("object"==typeof SDL&&SDL.audio?.bd?.(),G())}};e||(b&&0<b?Qa(0,1E3/b):Qa(1,1),G());if(c)throw"unwind";},Xa=a=>{a instanceof ma||"unwind"==a||ha(1,a)},Wa=a=>{t=a;Ha||(f.onExit?.(a),r=!0);ha(a,new ma(a))},Za=a=>{t=a;Wa(a)},La=!1,G=null,I=0,E=null,Ra=0,Ja=0,Ka=0,Va=0,Sa=[];function $a(){G=null;I++}var Ua={},Ma,H,Ta,ab=!1,bb=!1,cb=[];
function db(){function a(){bb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!eb){eb=!0;var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!bb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}var fb=!1,gb=void 0,J=void 0;
function hb(){if(!ab)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var ib=0;function Oa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ib)ib=b+1E3/60;else for(;b+2>=ib;)ib+=1E3/60;setTimeout(a,Math.max(ib-b,0))}}var jb=[];function kb(){var a=f.canvas;jb.forEach(b=>b(a.width,a.height))}
function lb(a,b,c){b&&c?(a.Rc=b,a.Nc=c):(b=a.Rc,c=a.Nc);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var k=Math.min(screen.width/d,screen.height/e);d=Math.round(d*k);e=Math.round(e*
k)}J?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Pa,eb,mb=0,nb=[];
function ob(){if(navigator.userActivation?navigator.userActivation.isActive:mb&&pb.rc){var a=nb;nb=[];for(var b of a)b.ed(...b.Uc)}}var K=[];function qb(a){var b=K[a];b.target.removeEventListener(b.ec,b.yc,b.fc);K.splice(a,1)}function L(a){if(!a.target)return-4;if(a.hc)a.yc=function(c){++mb;pb=a;ob();a.ic(c);ob();--mb},a.target.addEventListener(a.ec,a.yc,a.fc),K.push(a);else for(var b=0;b<K.length;++b)K[b].target==a.target&&K[b].ec==a.ec&&qb(b--);return 0}
function rb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var pb,sb,tb,ub,vb,wb,xb,yb,zb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],M=a=>{a=2<a?a?D(v,a):"":a;return zb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Ab=a=>0>zb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Bb=[],Cb,N=a=>{var b=Bb[a];b||(a>=Bb.length&&(Bb.length=a+1),Bb[a]=b=Cb.get(a));return b},O=(a,b,c)=>{var d=v;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var g=a.charCodeAt(k);if(55296<=g&&57343>=g){var l=
a.charCodeAt(++k);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},Db=(a,b,c,d,e,k)=>{sb||=P(256);a={target:M(a),ec:k,hc:d,ic:(g=event)=>{var l=g.target.id?g.target.id:"",n=sb;O(rb(g.target),n+0,128);O(l,n+128,128);N(d)(e,n,b)&&g.preventDefault()},fc:c};return L(a)},Eb=(a,
b,c,d,e,k)=>{tb||=P(160);a={target:M(a),ec:k,hc:d,ic:g=>{var l=tb;A[l>>3]=g.timeStamp;var n=l>>2;w[n+2]=g.location;u[l+12]=g.ctrlKey;u[l+13]=g.shiftKey;u[l+14]=g.altKey;u[l+15]=g.metaKey;u[l+16]=g.repeat;w[n+5]=g.charCode;w[n+6]=g.keyCode;w[n+7]=g.which;O(g.key||"",l+32,32);O(g.code||"",l+64,32);O(g.char||"",l+96,32);O(g.locale||"",l+128,32);N(d)(e,l,b)&&g.preventDefault()},fc:c};return L(a)},Fb=(a,b,c)=>{A[a>>3]=b.timeStamp;var d=a>>2;w[d+2]=b.screenX;w[d+3]=b.screenY;w[d+4]=b.clientX;w[d+5]=b.clientY;
u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;w[d+8]=b.movementX;w[d+9]=b.movementY;a=Ab(c);w[d+10]=b.clientX-(a.left|0);w[d+11]=b.clientY-(a.top|0)},Gb=(a,b,c,d,e,k)=>{ub||=P(64);a=M(a);return L({target:a,rc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,ec:k,hc:d,ic:(g=event)=>{Fb(ub,g,a);N(d)(e,ub,b)&&g.preventDefault()},fc:c})},Hb=(a,b,c,d,e)=>{vb||=P(257);return L({target:a,ec:e,hc:d,ic:(k=event)=>{var g=vb,l=document.pointerLockElement||
document.lc||document.Ac||document.zc;u[g]=!!l;var n=l?.id||"";O(rb(l),g+1,128);O(n,g+129,128);N(d)(20,g,b)&&k.preventDefault()},fc:c})},Ib=(a,b,c,d,e)=>L({target:a,ec:e,hc:d,ic:(k=event)=>{N(d)(38,0,b)&&k.preventDefault()},fc:c}),Jb=(a,b,c,d)=>{wb||=P(36);a=M(a);return L({target:a,ec:"resize",hc:d,ic:(e=event)=>{if(e.target==a){var k=document.body;if(k){var g=wb;w[g>>2]=0;w[g+4>>2]=k.clientWidth;w[g+8>>2]=k.clientHeight;w[g+12>>2]=innerWidth;w[g+16>>2]=innerHeight;w[g+20>>2]=outerWidth;w[g+24>>2]=
outerHeight;w[g+28>>2]=pageXOffset|0;w[g+32>>2]=pageYOffset|0;N(d)(10,g,b)&&e.preventDefault()}}},fc:c})},Kb=(a,b,c,d,e,k)=>{xb||=P(1552);a=M(a);return L({target:a,rc:"touchstart"==k||"touchend"==k,ec:k,hc:d,ic:g=>{var l={},n=g.touches;for(var p of n)p.Bc=p.Cc=0,l[p.identifier]=p;for(var y of g.changedTouches)y.Bc=1,l[y.identifier]=y;for(var za of g.targetTouches)l[za.identifier].Cc=1;n=xb;A[n>>3]=g.timeStamp;u[n+12]=g.ctrlKey;u[n+13]=g.shiftKey;u[n+14]=g.altKey;u[n+15]=g.metaKey;p=n+16;y=Ab(a);za=
0;for(let F of Object.values(l))if(l=p>>2,w[l]=F.identifier,w[l+1]=F.screenX,w[l+2]=F.screenY,w[l+3]=F.clientX,w[l+4]=F.clientY,w[l+5]=F.pageX,w[l+6]=F.pageY,u[p+28]=F.Bc,u[p+29]=F.Cc,w[l+8]=F.clientX-(y.left|0),w[l+9]=F.clientY-(y.top|0),p+=48,31<++za)break;w[n+8>>2]=za;N(d)(e,n,b)&&g.preventDefault()},fc:c})},Lb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),
a.drawElementsInstanced=(c,d,e,k,g)=>b.drawElementsInstancedANGLE(c,d,e,k,g))},Mb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Nb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Ob=a=>{a.Wc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
Pb=a=>{a.Zc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Qb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Rb=1,Sb=[],Q=[],Tb=[],Ub=[],Vb=[],R=[],Wb=[],Xb=[],S=[],Yb={},Zb=4,$b=0,ac=a=>{for(var b=Rb++,c=a.length;c<b;c++)a[c]=null;return b},bc=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=T[c](),g=k&&ac(d);k?(k.name=g,d[g]=k):U||=1282;w[b+4*e>>2]=g}},dc=(a,b)=>{a.lc||(a.lc=a.getContext,a.getContext=function(d,e){e=a.lc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.tc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?cc(c,b):0},cc=(a,b)=>{var c=ac(Xb),d={handle:c,attributes:b,version:b.tc,nc:a};a.canvas&&(a.canvas.Sc=d);Xb[c]=d;("undefined"==typeof b.xc||b.xc)&&ec(d);return c},fc=a=>{V=Xb[a];f.sc=T=V?.nc;return!(a&&!T)},ec=a=>{a||=V;if(!a.Oc){a.Oc=!0;var b=a.nc;Lb(b);Mb(b);Nb(b);Ob(b);Pb(b);2<=a.version&&(b.wc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.wc)b.wc=b.getExtension("EXT_disjoint_timer_query");b.Pc=b.getExtension("WEBGL_multi_draw");Qb(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},gc={},U,V,hc=(a,b,c,d,e,k)=>{a={target:M(a),ec:k,hc:d,ic:(g=event)=>{N(d)(e,0,b)&&g.preventDefault()},fc:c};L(a)},ic=(a,b,c,d)=>{yb||=P(96);return L({target:a,rc:!0,ec:"wheel",hc:d,ic:(e=event)=>{var k=yb;Fb(k,e,a);A[k+64>>3]=e.deltaX;A[k+72>>3]=e.deltaY;A[k+80>>3]=e.deltaZ;w[k+88>>2]=e.deltaMode;N(d)(9,k,b)&&e.preventDefault()},fc:c})},jc=["default","low-power","high-performance"],kc=[null,[],[]];
function lc(){var a=Qb(T);return a=a.concat(a.map(b=>"GL_"+b))}
var mc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=T.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=lc().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=T.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}w[b>>2]=c}else U||=1281},nc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},oc=a=>{var b=nc(a)+1,c=P(b);c&&O(a,c,b);return c},pc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),qc=[],rc=a=>{a-=5120;return 0==a?u:1==a?v:2==a?pa:4==a?w:6==a?z:5==a||28922==a||28520==a||30779==a||30782==a?x:qa},W=a=>{var b=T.Lc;if(b){var c=b.mc[a];"number"==typeof c&&(b.mc[a]=c=T.getUniformLocation(b,b.Jc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],sc=[],uc=a=>{var b=nc(a)+
1,c=tc(b);O(a,c,b);return c},xc=a=>{var b=vc();a();wc(b)};
f.requestFullscreen=function(a,b){function c(){ab=!1;var k=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===k?(d.exitFullscreen=hb,gb&&d.requestPointerLock(),ab=!0,J?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]|8388608),lb(f.canvas),kb()):lb(d)):(k.parentNode.insertBefore(d,k),k.parentNode.removeChild(k),J?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>
2]&-8388609),lb(f.canvas),kb()):lb(d));f.onFullScreen?.(ab);f.onFullscreen?.(ab)}gb=a;J=b;"undefined"==typeof gb&&(gb=!0);"undefined"==typeof J&&(J=!1);var d=f.canvas;fb||(fb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};f.requestAnimationFrame=Oa;f.setCanvasSize=function(a,b,c){lb(f.canvas,a,b);c||kb()};f.pauseMainLoop=$a;f.resumeMainLoop=function(){I++;var a=Ja,b=Ka,c=E;E=null;Ya(c,0,!1,Ra,!0);Qa(a,b);G()};
f.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};f.createContext=function(a,b,c,d){if(b&&f.sc&&a==f.canvas)return f.sc;var e;if(b){var k={antialias:!1,alpha:!1,tc:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var g in d)k[g]=d[g];if("undefined"!=typeof gc&&(e=dc(a,k)))var l=Xb[e].nc}else l=a.getContext("2d");if(!l)return null;c&&(f.sc=l,b&&fc(e),f.gd=b,cb.forEach(n=>n()),db());return l};
for(var T,Y=0;32>Y;++Y)qc.push(Array(Y));var yc=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=yc.subarray(0,Y);var zc=new Int32Array(288);for(Y=0;288>=Y;++Y)sc[Y]=zc.subarray(0,Y);
var Fc={ha:function(){return 0},fb:function(){return 0},hb:function(){},ib:()=>{ya("")},cb:(a,b,c)=>v.copyWithin(a,b,b+c),Sa:()=>{$a();E=null},ca:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ea:(a,b,c)=>{a=M(a);if(!a)return-4;a=Ab(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},Ta:()=>performance.now(),Za:(a,b)=>{function c(d){N(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},bb:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/
c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-oa.buffer.byteLength+65535)/65536;try{oa.grow(e);ra();var k=1;break a}catch(g){}k=void 0}if(k)return!0}return!1},M:(a,b,c,d)=>Db(a,b,c,d,12,"blur"),ba:(a,b,c)=>{a=M(a);if(!a)return-4;a.width=b;a.height=c;return 0},N:(a,b,c,d)=>Db(a,b,c,d,13,"focus"),W:(a,b,c,d)=>Eb(a,b,c,d,2,"keydown"),U:(a,b,c,d)=>Eb(a,b,c,d,1,"keypress"),V:(a,b,c,d)=>Eb(a,b,c,d,3,"keyup"),_a:(a,b,c)=>{a=N(a);Ya(a,b,c)},
aa:(a,b,c,d)=>Gb(a,b,c,d,5,"mousedown"),Z:(a,b,c,d)=>Gb(a,b,c,d,33,"mouseenter"),Y:(a,b,c,d)=>Gb(a,b,c,d,34,"mouseleave"),_:(a,b,c,d)=>Gb(a,b,c,d,8,"mousemove"),$:(a,b,c,d)=>Gb(a,b,c,d,6,"mouseup"),P:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.lc||document.body.Ac||document.body.zc))return-1;a=M(a);if(!a)return-4;Hb(a,b,c,d,"mozpointerlockchange");Hb(a,b,c,d,"webkitpointerlockchange");Hb(a,b,c,d,"mspointerlockchange");return Hb(a,b,c,d,"pointerlockchange")},
O:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.lc||document.body.Ac||document.body.zc))return-1;a=M(a);if(!a)return-4;Ib(a,b,c,d,"mozpointerlockerror");Ib(a,b,c,d,"webkitpointerlockerror");Ib(a,b,c,d,"mspointerlockerror");return Ib(a,b,c,d,"pointerlockerror")},da:(a,b,c,d)=>Jb(a,b,c,d),Q:(a,b,c,d)=>Kb(a,b,c,d,25,"touchcancel"),R:(a,b,c,d)=>Kb(a,b,c,d,23,"touchend"),S:(a,b,c,d)=>Kb(a,b,c,d,24,"touchmove"),T:(a,b,c,d)=>Kb(a,b,c,d,22,"touchstart"),L:(a,b,c,d)=>{hc(a,b,
c,d,31,"webglcontextlost");return 0},K:(a,b,c,d)=>{hc(a,b,c,d,32,"webglcontextrestored");return 0},X:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?ic(a,b,c,d):-1:-4,Ya:(a,b)=>{var c=b>>2;b={alpha:!!u[b+0],depth:!!u[b+1],stencil:!!u[b+2],antialias:!!u[b+3],premultipliedAlpha:!!u[b+4],preserveDrawingBuffer:!!u[b+5],powerPreference:jc[w[c+2]],failIfMajorPerformanceCaveat:!!u[b+12],tc:w[c+4],$c:w[c+5],xc:u[b+24],Mc:u[b+25],ad:w[c+7],cd:u[b+32]};a=M(a);return!a||b.Mc?0:dc(a,b)},Wa:(a,b)=>{a=Xb[a];
b=b?D(v,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Lb(T);"OES_vertex_array_object"==b&&Mb(T);"WEBGL_draw_buffers"==b&&Nb(T);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Ob(T);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Pb(T);"WEBGL_multi_draw"==b&&(T.Pc=T.getExtension("WEBGL_multi_draw"));return!!a.nc.getExtension(b)},Xa:a=>fc(a)?0:-5,ga:()=>52,eb:()=>52,ab:function(){return 70},db:(a,b,c,d)=>{for(var e=0,k=0;k<c;k++){var g=x[b>>2],l=x[b+4>>2];b+=
8;for(var n=0;n<l;n++){var p=v[g+n],y=kc[a];0===p||10===p?((1===a?na:m)(D(y,0)),y.length=0):y.push(p)}e+=l}x[d>>2]=e;return 0},i:a=>T.activeTexture(a),v:(a,b)=>{T.attachShader(Q[a],R[b])},b:(a,b)=>{35051==a?T.vc=b:35052==a&&(T.kc=b);T.bindBuffer(a,Sb[b])},a:(a,b,c)=>{T.bindBufferBase(a,b,Sb[c])},o:(a,b)=>{T.bindFramebuffer(a,Tb[b])},Da:(a,b)=>{T.bindRenderbuffer(a,Ub[b])},h:(a,b)=>{T.bindSampler(a,S[b])},c:(a,b)=>{T.bindTexture(a,Vb[b])},J:a=>{T.bindVertexArray(Wb[a])},F:(a,b,c,d)=>T.blendColor(a,
b,c,d),G:(a,b)=>T.blendEquationSeparate(a,b),H:(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),kb:(a,b,c,d,e,k,g,l,n,p)=>T.blitFramebuffer(a,b,c,d,e,k,g,l,n,p),Fa:(a,b,c,d)=>{2<=V.version?c&&b?T.bufferData(a,v,d,c,b):T.bufferData(a,b,d):T.bufferData(a,c?v.subarray(c,c+b):b,d)},x:(a,b,c,d)=>{2<=V.version?c&&T.bufferSubData(a,b,v,d,c):T.bufferSubData(a,b,v.subarray(d,d+c))},Eb:(a,b,c,d)=>T.clearBufferfi(a,b,c,d),la:(a,b,c)=>{T.clearBufferfv(a,b,z,c>>2)},Db:(a,b,c)=>{T.clearBufferiv(a,b,w,c>>2)},k:(a,b,c,d)=>
{T.colorMask(!!a,!!b,!!c,!!d)},Ib:a=>{T.compileShader(R[a])},xa:(a,b,c,d,e,k,g,l)=>{2<=V.version?T.kc||!g?T.compressedTexImage2D(a,b,c,d,e,k,g,l):T.compressedTexImage2D(a,b,c,d,e,k,v,l,g):T.compressedTexImage2D(a,b,c,d,e,k,l?v.subarray(l,l+g):null)},ua:(a,b,c,d,e,k,g,l,n)=>{T.kc?T.compressedTexImage3D(a,b,c,d,e,k,g,l,n):T.compressedTexImage3D(a,b,c,d,e,k,g,v,n,l)},ra:()=>{var a=ac(Q),b=T.createProgram();b.name=a;b.qc=b.oc=b.pc=0;b.uc=1;Q[a]=b;return a},Kb:a=>{var b=ac(R);R[b]=T.createShader(a);return b},
C:a=>T.cullFace(a),Ja:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Sb[d];e&&(T.deleteBuffer(e),e.name=0,Sb[d]=null,d==T.vc&&(T.vc=0),d==T.kc&&(T.kc=0))}},j:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=Tb[d];e&&(T.deleteFramebuffer(e),e.name=0,Tb[d]=null)}},y:a=>{if(a){var b=Q[a];b?(T.deleteProgram(b),b.name=0,Q[a]=null):U||=1281}},A:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Ub[d];e&&(T.deleteRenderbuffer(e),e.name=0,Ub[d]=null)}},z:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=S[d];
e&&(T.deleteSampler(e),e.name=0,S[d]=null)}},q:a=>{if(a){var b=R[a];b?(T.deleteShader(b),R[a]=null):U||=1281}},B:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Vb[d];e&&(T.deleteTexture(e),e.name=0,Vb[d]=null)}},Ia:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2];T.deleteVertexArray(Wb[d]);Wb[d]=null}},t:a=>T.depthFunc(a),s:a=>{T.depthMask(!!a)},e:a=>T.disable(a),I:a=>{T.disableVertexAttribArray(a)},mb:(a,b,c)=>{T.drawArrays(a,b,c)},nb:(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},ob:(a,b,c,d)=>{T.drawElements(a,
b,c,d)},pb:(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},g:a=>T.enable(a),Ab:a=>{T.enableVertexAttribArray(a)},D:a=>T.frontFace(a),Ha:(a,b)=>{bc(a,b,"createBuffer",Sb)},Ea:(a,b)=>{bc(a,b,"createRenderbuffer",Ub)},sa:(a,b)=>{bc(a,b,"createSampler",S)},Ba:(a,b)=>{bc(a,b,"createTexture",Vb)},Ra:(a,b)=>{bc(a,b,"createVertexArray",Wb)},Gb:(a,b)=>T.getAttribLocation(Q[a],b?D(v,b):""),d:(a,b)=>mc(a,b),Lb:(a,b,c,d)=>{a=T.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(w[c>>
2]=b)},oa:(a,b,c)=>{if(c)if(a>=Rb)U||=1281;else if(a=Q[a],35716==b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.qc)for(b=0;b<T.getProgramParameter(a,35718);++b)a.qc=Math.max(a.qc,T.getActiveUniform(a,b).name.length+1);w[c>>2]=a.qc}else if(35722==b){if(!a.oc)for(b=0;b<T.getProgramParameter(a,35721);++b)a.oc=Math.max(a.oc,T.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.oc}else if(35381==b){if(!a.pc)for(b=0;b<T.getProgramParameter(a,35382);++b)a.pc=
Math.max(a.pc,T.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.pc}else w[c>>2]=T.getProgramParameter(a,b);else U||=1281},Hb:(a,b,c,d)=>{a=T.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(w[c>>2]=b)},ma:(a,b,c)=>{c?35716==b?(a=T.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=T.getShaderSource(R[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=T.getShaderParameter(R[a],b):U||=1281},Oa:(a,b)=>{if(2>V.version)return U||=1282,0;var c=Yb[a];
if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=lc().map(oc),c=Yb[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},p:(a,b)=>{b=b?D(v,b):"";if(a=Q[a]){var c=a,d=c.mc,e=c.Kc,k;if(!d)for(c.mc=d={},c.Jc={},k=0;k<T.getProgramParameter(c,35718);++k){var g=T.getActiveUniform(c,k);var l=g.name;g=g.size;var n=pc(l);n=0<n?l.slice(0,n):l;var p=c.uc;c.uc+=g;e[n]=[g,p];for(l=0;l<g;++l)d[p]=l,c.Jc[p++]=n}c=a.mc;d=0;e=b;k=pc(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=
b.slice(0,k));if((e=a.Kc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else U||=1281;return-1},jb:(a,b,c)=>{for(var d=qc[b],e=0;e<b;e++)d[e]=w[c+4*e>>2];T.invalidateFramebuffer(a,d)},qa:a=>{a=Q[a];T.linkProgram(a);a.mc=0;a.Kc={}},Qa:(a,b)=>{3317==a?Zb=b:3314==a&&($b=b);T.pixelStorei(a,b)},E:(a,b)=>T.polygonOffset(a,b),lb:a=>T.readBuffer(a),Ca:(a,b,c,d,e)=>T.renderbufferStorageMultisample(a,b,c,d,e),w:(a,b,c)=>{T.samplerParameterf(S[a],b,c)},f:(a,b,c)=>{T.samplerParameteri(S[a],
b,c)},m:(a,b,c,d)=>T.scissor(a,b,c,d),Jb:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var g=(g=x[c+4*k>>2])?D(v,g,d?x[d+4*k>>2]:void 0):"";e+=g}T.shaderSource(R[a],e)},Na:(a,b,c)=>T.stencilFunc(a,b,c),ka:(a,b,c,d)=>T.stencilFuncSeparate(a,b,c,d),r:a=>T.stencilMask(a),Ma:(a,b,c)=>T.stencilOp(a,b,c),ja:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),va:(a,b,c,d,e,k,g,l,n)=>{if(2<=V.version){if(T.kc){T.texImage2D(a,b,c,d,e,k,g,l,n);return}if(n){var p=rc(l);n>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);T.texImage2D(a,b,c,
d,e,k,g,l,p,n);return}}if(n){p=rc(l);var y=e*(($b||d)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*p.BYTES_PER_ELEMENT+Zb-1&-Zb);n=p.subarray(n>>>31-Math.clz32(p.BYTES_PER_ELEMENT),n+y>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else n=null;T.texImage2D(a,b,c,d,e,k,g,l,n)},ta:(a,b,c,d,e,k,g,l,n,p)=>{if(T.kc)T.texImage3D(a,b,c,d,e,k,g,l,n,p);else if(p){var y=rc(n);T.texImage3D(a,b,c,d,e,k,g,l,n,y,p>>>31-Math.clz32(y.BYTES_PER_ELEMENT))}else T.texImage3D(a,b,c,d,e,k,g,l,n,null)},
Aa:(a,b,c)=>T.texParameteri(a,b,c),za:(a,b,c,d,e)=>T.texStorage2D(a,b,c,d,e),ya:(a,b,c,d,e,k)=>T.texStorage3D(a,b,c,d,e,k),zb:(a,b,c)=>{if(2<=V.version)b&&T.uniform1fv(W(a),z,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);T.uniform1fv(W(a),d)}},na:(a,b)=>{T.uniform1i(W(a),b)},vb:(a,b,c)=>{if(2<=V.version)b&&T.uniform1iv(W(a),w,c>>2,b);else{if(288>=b)for(var d=sc[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);T.uniform1iv(W(a),
d)}},yb:(a,b,c)=>{if(2<=V.version)b&&T.uniform2fv(W(a),z,c>>2,2*b);else{if(144>=b)for(var d=X[2*b],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);T.uniform2fv(W(a),d)}},ub:(a,b,c)=>{if(2<=V.version)b&&T.uniform2iv(W(a),w,c>>2,2*b);else{if(144>=b)for(var d=sc[2*b],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);T.uniform2iv(W(a),d)}},xb:(a,b,c)=>{if(2<=V.version)b&&T.uniform3fv(W(a),z,c>>2,3*b);else{if(96>=b)for(var d=
X[3*b],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);T.uniform3fv(W(a),d)}},tb:(a,b,c)=>{if(2<=V.version)b&&T.uniform3iv(W(a),w,c>>2,3*b);else{if(96>=b)for(var d=sc[3*b],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);T.uniform3iv(W(a),d)}},wb:(a,b,c)=>{if(2<=V.version)b&&T.uniform4fv(W(a),z,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=z;c>>=2;for(var k=0;k<4*b;k+=4){var g=
c+k;d[k]=e[g];d[k+1]=e[g+1];d[k+2]=e[g+2];d[k+3]=e[g+3]}}else d=z.subarray(c>>2,c+16*b>>2);T.uniform4fv(W(a),d)}},sb:(a,b,c)=>{if(2<=V.version)b&&T.uniform4iv(W(a),w,c>>2,4*b);else{if(72>=b)for(var d=sc[4*b],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);T.uniform4iv(W(a),d)}},rb:(a,b,c,d)=>{if(2<=V.version)b&&T.uniformMatrix4fv(W(a),!!c,z,d>>2,16*b);else{if(18>=b){var e=X[16*b],k=z;d>>=2;for(var g=0;g<16*b;g+=
16){var l=d+g;e[g]=k[l];e[g+1]=k[l+1];e[g+2]=k[l+2];e[g+3]=k[l+3];e[g+4]=k[l+4];e[g+5]=k[l+5];e[g+6]=k[l+6];e[g+7]=k[l+7];e[g+8]=k[l+8];e[g+9]=k[l+9];e[g+10]=k[l+10];e[g+11]=k[l+11];e[g+12]=k[l+12];e[g+13]=k[l+13];e[g+14]=k[l+14];e[g+15]=k[l+15]}}else e=z.subarray(d>>2,d+64*b>>2);T.uniformMatrix4fv(W(a),!!c,e)}},l:a=>{a=Q[a];T.useProgram(a);T.Lc=a},Bb:(a,b)=>{T.vertexAttribDivisor(a,b)},Cb:(a,b,c,d,e,k)=>{T.vertexAttribPointer(a,b,c,!!d,e,k)},n:(a,b,c,d)=>T.viewport(a,b,c,d),Mb:function(){f.Dc=a=>
{0!=Ac()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Dc)},Va:function(){f.Ic=a=>{const b=a.clipboardData.getData("text");xc(()=>{const c=uc(b);Bc(c)})};window.addEventListener("paste",f.Ic)},La:function(a){f.dd=[];a=a?D(v,a):"";a=document.getElementById(a);f.Ec=b=>{b.stopPropagation();b.preventDefault()};f.Fc=b=>{b.stopPropagation();b.preventDefault()};f.Gc=b=>{b.stopPropagation();b.preventDefault()};f.Hc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;
f.Qc=c;Cc(c.length);for(let e=0;e<c.length;e++)xc(()=>{const k=uc(c[e].name);Dc(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Ec(b.clientX,b.clientY,d)};a.addEventListener("dragenter",f.Ec,!1);a.addEventListener("dragleave",f.Fc,!1);a.addEventListener("dragover",f.Gc,!1);a.addEventListener("drop",f.Hc,!1)},qb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ka:function(a){const b=f.Qc;return 0>a||a>=b.length?
0:b[a].size},Fb:function(){document.exitPointerLock&&document.exitPointerLock()},wa:function(a){a=a?D(v,a):"";f.jc=document.getElementById(a);f.jc||console.log("sokol_app.h: invalid target:"+a);f.jc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},$a:function(){window.removeEventListener("beforeunload",f.Dc)},Ua:function(){window.removeEventListener("paste",f.Ic)},Ga:function(a){a=a?D(v,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",
f.Ec);a.removeEventListener("dragleave",f.Fc);a.removeEventListener("dragover",f.Gc);a.removeEventListener("drop",f.Hc)},u:function(){f.jc&&f.jc.requestPointerLock&&f.jc.requestPointerLock()},ia:function(a,b){if(f.jc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";
break;case 10:a="not-allowed";break;default:a="auto"}f.jc.style.cursor=a}},gb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(v.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Pa:function(a){a=a?D(v,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");
b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},pa:function(){return navigator.userAgent.includes("Macintosh")?1:0},fa:function(a,b){b=b?D(v,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},
Z=function(){function a(c){Z=c.exports;oa=Z.Nb;ra();Cb=Z.ac;ta.unshift(Z.Ob);B--;f.monitorRunDependencies?.(B);0==B&&(null!==xa&&(clearInterval(xa),xa=null),C&&(c=C,C=null,c()));return Z}var b={a:Fc};B++;f.monitorRunDependencies?.(B);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return m(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ba||=Aa("events-sapp.wasm")?"events-sapp.wasm":f.locateFile?f.locateFile("events-sapp.wasm",h):h+"events-sapp.wasm";Fa(b,function(c){a(c.instance)});
return{}}(),P=a=>(P=Z.Pb)(a),Bc=f.__sapp_emsc_onpaste=a=>(Bc=f.__sapp_emsc_onpaste=Z.Qb)(a),Ac=f.__sapp_html5_get_ask_leave_site=()=>(Ac=f.__sapp_html5_get_ask_leave_site=Z.Rb)(),Cc=f.__sapp_emsc_begin_drop=a=>(Cc=f.__sapp_emsc_begin_drop=Z.Sb)(a),Dc=f.__sapp_emsc_drop=(a,b)=>(Dc=f.__sapp_emsc_drop=Z.Tb)(a,b),Ec=f.__sapp_emsc_end_drop=(a,b,c)=>(Ec=f.__sapp_emsc_end_drop=Z.Ub)(a,b,c);f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,k,g,l)=>(f.__sapp_emsc_invoke_fetch_cb=Z.Vb)(a,b,c,d,e,k,g,l);
var Gc=f._main=(a,b)=>(Gc=f._main=Z.Wb)(a,b);f.__saudio_emsc_pull=a=>(f.__saudio_emsc_pull=Z.Xb)(a);f.__sfetch_emsc_head_response=(a,b)=>(f.__sfetch_emsc_head_response=Z.Yb)(a,b);f.__sfetch_emsc_get_response=(a,b,c)=>(f.__sfetch_emsc_get_response=Z.Zb)(a,b,c);f.__sfetch_emsc_failed_http_status=(a,b)=>(f.__sfetch_emsc_failed_http_status=Z._b)(a,b);f.__sfetch_emsc_failed_buffer_too_small=a=>(f.__sfetch_emsc_failed_buffer_too_small=Z.$b)(a);
var wc=a=>(wc=Z.bc)(a),tc=a=>(tc=Z.cc)(a),vc=()=>(vc=Z.dc)(),Hc;C=function Ic(){Hc||Jc();Hc||(C=Ic)};function Kc(a=[]){var b=Gc;a.unshift(fa);var c=a.length,d=tc(4*(c+1)),e=d;a.forEach(g=>{x[e>>2]=uc(g);e+=4});x[e>>2]=0;try{var k=b(c,d);Za(k)}catch(g){Xa(g)}}
function Jc(){var a=ea;function b(){if(!Hc&&(Hc=!0,f.calledRun=!0,!r)){Ga(ta);Ga(ua);f.onRuntimeInitialized?.();Lc&&Kc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();va.unshift(c)}Ga(va)}}if(!(0<B)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)wa();Ga(sa);0<B||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Lc=!0;f.noInitialRun&&(Lc=!1);Jc();
