var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,da=Object.assign({},g),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja,ka;
if(ca){var fs=require("fs"),la=require("path");k=__dirname+"/";ia=(a,b)=>{a=ma(a)?new URL(a):la.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ka=a=>{a=ia(a,!0);a.buffer||(a=new Uint8Array(a));return a};ja=(a,b,c)=>{a=ma(a)?new URL(a):la.normalize(a);fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})};!g.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);process.on("uncaughtException",a=>{if(!("unwind"===
a||a instanceof na||a.context instanceof na))throw a;});ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?"":k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ja=(a,b,c)=>{if(ma(a)){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)}else fetch(a,{credentials:"same-origin"}).then(e=>e.ok?e.arrayBuffer():Promise.reject(Error(e.status+" : "+e.url))).then(b,c)};var oa=g.print||console.log.bind(console),m=g.printErr||console.error.bind(console);Object.assign(g,da);da=null;g.arguments&&(ea=g.arguments);g.thisProgram&&(fa=g.thisProgram);
g.quit&&(ha=g.quit);var q;g.wasmBinary&&(q=g.wasmBinary);var pa,t=!1,u,qa,w,ra,sa,x,y,z,A;function ta(){var a=pa.buffer;g.HEAP8=qa=new Int8Array(a);g.HEAP16=ra=new Int16Array(a);g.HEAPU8=w=new Uint8Array(a);g.HEAPU16=sa=new Uint16Array(a);g.HEAP32=x=new Int32Array(a);g.HEAPU32=y=new Uint32Array(a);g.HEAPF32=z=new Float32Array(a);g.HEAPF64=A=new Float64Array(a)}var ua=[],va=[],wa=[],xa=[];function ya(){var a=g.preRun.shift();ua.unshift(a)}var B=0,za=null,C=null;
function Aa(a){g.onAbort?.(a);a="Aborted("+a+")";m(a);t=!0;u=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ba=a=>a.startsWith("data:application/octet-stream;base64,"),ma=a=>a.startsWith("file://"),Ca;function Da(a){if(a==Ca&&q)return new Uint8Array(q);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}
function Ea(a){return q?Promise.resolve().then(()=>Da(a)):new Promise((b,c)=>{ja(a,d=>b(new Uint8Array(d)),()=>{try{b(Da(a))}catch(d){c(d)}})})}function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{m(`failed to asynchronously prepare wasm: ${d}`);Aa(d)})}
function Ga(a,b){var c=Ca;q||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||ma(c)||ca||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){m(`wasm streaming compile failed: ${e}`);m("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}function na(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ha=a=>{for(;0<a.length;)a.shift()(g)},Ia=g.noExitRuntime||!0,Ja="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,D=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ja)return Ja.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ra=(a,b)=>{Ka=a;La=b;if(E)if(Ma||=!0,0==a)F=function(){var d=Math.max(0,Na+b-Oa())|0;setTimeout(G,d)};else if(1==a)F=function(){Pa(G)};else if(2==a){if("undefined"==typeof Qa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=function(d){c.push(d);ba?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),
postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}else Qa=setImmediate;F=function(){Qa(G)}}},Oa;Oa=()=>performance.now();
var Za=(a,b,c,d,e)=>{E=a;Sa=d;var h=H;Ma=!1;G=function(){if(!t)if(0<Ta.length){var f=Ta.shift();f.Xc(f.Sc);if(Ua){var l=Ua,n=0==l%1?l-1:Math.floor(l);Ua=f.Uc?n:(8*l+(n+.5))/9}g.setStatus&&(f=g.statusMessage||"Please wait...",l=Ua,n=Va.Wc,l?l<n?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(f):g.setStatus(""));h<H||setTimeout(G,0)}else if(!(h<H))if(Wa=Wa+1|0,1==Ka&&1<La&&0!=Wa%La)F();else{0==Ka&&(Na=Oa());if(!(t||g.preMainLoop&&!1===g.preMainLoop())){if(!t)try{if(a(),!Ia)try{u=
f=u,Xa(f)}catch(p){Ya(p)}}catch(p){Ya(p)}g.postMainLoop?.()}h<H||("object"==typeof SDL&&SDL.audio?.ad?.(),F())}};e||(b&&0<b?Ra(0,1E3/b):Ra(1,1),F());if(c)throw"unwind";},Ya=a=>{a instanceof na||"unwind"==a||ha(1,a)},Xa=a=>{u=a;Ia||(g.onExit?.(a),t=!0);ha(a,new na(a))},$a=a=>{u=a;Xa(a)},Ma=!1,F=null,H=0,E=null,Sa=0,Ka=0,La=0,Wa=0,Ta=[];function ab(){F=null;H++}var Va={},Na,G,Ua,I=!1,bb=!1,cb=[];
function db(){function a(){bb=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}if(!eb){eb=!0;var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!bb&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}var fb=!1,gb=void 0,J=void 0;
function hb(){if(!I)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var ib=0;function Pa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ib)ib=b+1E3/60;else for(;b+2>=ib;)ib+=1E3/60;setTimeout(a,Math.max(ib-b,0))}}var jb=[];function kb(){var a=g.canvas;jb.forEach(b=>b(a.width,a.height))}
function lb(a,b,c){b&&c?(a.Qc=b,a.Nc=c):(b=a.Qc,c=a.Nc);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var h=Math.min(screen.width/d,screen.height/e);d=Math.round(d*h);e=Math.round(e*
h)}J?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Qa,eb,mb=0,nb=[];
function ob(){if(navigator.userActivation?navigator.userActivation.isActive:mb&&pb.rc)for(var a=0;a<nb.length;++a){var b=nb[a];nb.splice(a,1);--a;b.ed(...b.Tc)}}var K=[];function qb(a){var b=K[a];b.target.removeEventListener(b.ec,b.yc,b.fc);K.splice(a,1)}function L(a){if(!a.target)return-4;if(a.hc)a.yc=function(c){++mb;pb=a;ob();a.ic(c);ob();--mb},a.target.addEventListener(a.ec,a.yc,a.fc),K.push(a);else for(var b=0;b<K.length;++b)K[b].target==a.target&&K[b].ec==a.ec&&qb(b--);return 0}
function rb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var pb,sb,tb,ub,vb,wb,xb,yb,zb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],M=a=>{a=2<a?a?D(w,a):"":a;return zb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Ab=a=>0>zb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Bb=[],Cb,N=a=>{var b=Bb[a];b||(a>=Bb.length&&(Bb.length=a+1),Bb[a]=b=Cb.get(a));return b},O=(a,b,c)=>{var d=w;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var l=
a.charCodeAt(++h);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},Db=(a,b,c,d,e,h)=>{sb||=P(256);a={target:M(a),ec:h,hc:d,ic:(f=event)=>{var l=f.target.id?f.target.id:"",n=sb;O(rb(f.target),n+0,128);O(l,n+128,128);N(d)(e,n,b)&&f.preventDefault()},fc:c};return L(a)},Eb=(a,
b,c,d,e,h)=>{tb||=P(176);a={target:M(a),ec:h,hc:d,ic:f=>{var l=tb;A[l>>3]=f.timeStamp;var n=l>>2;x[n+2]=f.location;x[n+3]=f.ctrlKey;x[n+4]=f.shiftKey;x[n+5]=f.altKey;x[n+6]=f.metaKey;x[n+7]=f.repeat;x[n+8]=f.charCode;x[n+9]=f.keyCode;x[n+10]=f.which;O(f.key||"",l+44,32);O(f.code||"",l+76,32);O(f.char||"",l+108,32);O(f.locale||"",l+140,32);N(d)(e,l,b)&&f.preventDefault()},fc:c};return L(a)},Fb=(a,b,c)=>{A[a>>3]=b.timeStamp;a>>=2;x[a+2]=b.screenX;x[a+3]=b.screenY;x[a+4]=b.clientX;x[a+5]=b.clientY;x[a+
6]=b.ctrlKey;x[a+7]=b.shiftKey;x[a+8]=b.altKey;x[a+9]=b.metaKey;ra[2*a+20]=b.button;ra[2*a+21]=b.buttons;x[a+11]=b.movementX;x[a+12]=b.movementY;c=Ab(c);x[a+13]=b.clientX-(c.left|0);x[a+14]=b.clientY-(c.top|0)},Gb=(a,b,c,d,e,h)=>{ub||=P(72);a=M(a);return L({target:a,rc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ec:h,hc:d,ic:(f=event)=>{Fb(ub,f,a);N(d)(e,ub,b)&&f.preventDefault()},fc:c})},Hb=(a,b,c,d,e)=>{vb||=P(260);return L({target:a,ec:e,hc:d,ic:(h=event)=>{var f=vb,l=document.pointerLockElement||
document.lc||document.Ac||document.zc;x[f>>2]=!!l;var n=l?.id||"";O(rb(l),f+4,128);O(n,f+132,128);N(d)(20,f,b)&&h.preventDefault()},fc:c})},Ib=(a,b,c,d,e)=>L({target:a,ec:e,hc:d,ic:(h=event)=>{N(d)(38,0,b)&&h.preventDefault()},fc:c}),Jb=(a,b,c,d)=>{wb||=P(36);a=M(a);return L({target:a,ec:"resize",hc:d,ic:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=wb;x[f>>2]=0;x[f+4>>2]=h.clientWidth;x[f+8>>2]=h.clientHeight;x[f+12>>2]=innerWidth;x[f+16>>2]=innerHeight;x[f+20>>2]=outerWidth;x[f+24>>
2]=outerHeight;x[f+28>>2]=pageXOffset|0;x[f+32>>2]=pageYOffset|0;N(d)(10,f,b)&&e.preventDefault()}}},fc:c})},Kb=(a,b,c,d,e,h)=>{xb||=P(1696);a=M(a);return L({target:a,rc:"touchstart"==h||"touchend"==h,ec:h,hc:d,ic:f=>{for(var l,n={},p=f.touches,r=0;r<p.length;++r)l=p[r],l.Bc=l.Cc=0,n[l.identifier]=l;for(r=0;r<f.changedTouches.length;++r)l=f.changedTouches[r],l.Bc=1,n[l.identifier]=l;for(r=0;r<f.targetTouches.length;++r)n[f.targetTouches[r].identifier].Cc=1;p=xb;A[p>>3]=f.timeStamp;var v=p>>2;x[v+
3]=f.ctrlKey;x[v+4]=f.shiftKey;x[v+5]=f.altKey;x[v+6]=f.metaKey;v+=7;var Mb=Ab(a),Nb=0;for(r in n)if(l=n[r],x[v]=l.identifier,x[v+1]=l.screenX,x[v+2]=l.screenY,x[v+3]=l.clientX,x[v+4]=l.clientY,x[v+5]=l.pageX,x[v+6]=l.pageY,x[v+7]=l.Bc,x[v+8]=l.Cc,x[v+9]=l.clientX-(Mb.left|0),x[v+10]=l.clientY-(Mb.top|0),v+=13,31<++Nb)break;x[p+8>>2]=Nb;N(d)(e,p,b)&&f.preventDefault()},fc:c})},Lb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},Ob=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Pb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Qb=a=>{a.Vc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
Rb=a=>{a.Yc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Sb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Tb=1,Ub=[],Q=[],Vb=[],Wb=[],Xb=[],R=[],Yb=[],Zb=[],S=[],$b={},ac=4,bc=0,cc=a=>{for(var b=Tb++,c=a.length;c<b;c++)a[c]=null;return b},dc=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=T[c](),f=h&&cc(d);h?(h.name=f,d[f]=h):U||=1282;x[b+4*e>>2]=f}},fc=(a,b)=>{a.lc||(a.lc=a.getContext,a.getContext=function(d,e){e=a.lc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.tc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?ec(c,b):0},ec=(a,b)=>{var c=cc(Zb),d={handle:c,attributes:b,version:b.tc,nc:a};a.canvas&&(a.canvas.Rc=d);Zb[c]=d;("undefined"==typeof b.xc||b.xc)&&gc(d);return c},hc=a=>{V=Zb[a];g.sc=T=V?.nc;return!(a&&!T)},gc=a=>{a||=V;if(!a.Oc){a.Oc=!0;var b=a.nc;Lb(b);Ob(b);Pb(b);Qb(b);Rb(b);2<=a.version&&(b.wc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.wc)b.wc=b.getExtension("EXT_disjoint_timer_query");b.Pc=b.getExtension("WEBGL_multi_draw");Sb(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},ic={},U,V,jc=(a,b,c,d,e,h)=>{a={target:M(a),ec:h,hc:d,ic:(f=event)=>{N(d)(e,0,b)&&f.preventDefault()},fc:c};L(a)},kc=(a,b,c,d)=>{yb||=P(104);return L({target:a,rc:!0,ec:"wheel",hc:d,ic:(e=event)=>{var h=yb;Fb(h,e,a);A[h+72>>3]=e.deltaX;A[h+80>>3]=e.deltaY;A[h+88>>3]=e.deltaZ;x[h+96>>2]=e.deltaMode;N(d)(9,h,b)&&e.preventDefault()},fc:c})},lc=["default","low-power","high-performance"],mc=[null,[],[]];
function nc(){var a=Sb(T);return a=a.concat(a.map(b=>"GL_"+b))}
var oc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=T.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=nc().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=T.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)x[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}x[b>>2]=c}else U||=1281},pc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},qc=a=>{var b=pc(a)+1,c=P(b);c&&O(a,c,b);return c},rc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),sc=[],tc=a=>{a-=5120;return 0==a?qa:1==a?w:2==a?ra:4==a?x:6==a?z:5==a||28922==a||28520==a||30779==a||30782==a?y:sa},uc=(a,b,c,d,e)=>{a=tc(a);b=d*((bc||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+ac-1&-ac);return a.subarray(e>>>
31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=T.Lc;if(b){var c=b.mc[a];"number"==typeof c&&(b.mc[a]=c=T.getUniformLocation(b,b.Jc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],vc=[],xc=a=>{var b=pc(a)+1,c=wc(b);O(a,c,b);return c},Ac=a=>{var b=yc();a();zc(b)};
g.requestFullscreen=function(a,b){function c(){I=!1;var h=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===h?(d.exitFullscreen=hb,gb&&d.requestPointerLock(),I=!0,J?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]|8388608),lb(g.canvas),kb()):lb(d)):(h.parentNode.insertBefore(d,h),h.parentNode.removeChild(h),J?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>
2]&-8388609),lb(g.canvas),kb()):lb(d));g.onFullScreen?.(I);g.onFullscreen?.(I)}gb=a;J=b;"undefined"==typeof gb&&(gb=!0);"undefined"==typeof J&&(J=!1);var d=g.canvas;fb||(fb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};g.requestAnimationFrame=Pa;g.setCanvasSize=function(a,b,c){lb(g.canvas,a,b);c||kb()};g.pauseMainLoop=ab;g.resumeMainLoop=function(){H++;var a=Ka,b=La,c=E;E=null;Za(c,0,!1,Sa,!0);Ra(a,b);F()};
g.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};g.createContext=function(a,b,c,d){if(b&&g.sc&&a==g.canvas)return g.sc;var e;if(b){var h={antialias:!1,alpha:!1,tc:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var f in d)h[f]=d[f];if("undefined"!=typeof ic&&(e=fc(a,h)))var l=Zb[e].nc}else l=a.getContext("2d");if(!l)return null;c&&(g.sc=l,b&&hc(e),g.gd=b,cb.forEach(n=>n()),db());return l};
for(var T,Y=0;32>Y;++Y)sc.push(Array(Y));var Bc=new Float32Array(288);for(Y=0;288>Y;++Y)X[Y]=Bc.subarray(0,Y);var Cc=new Int32Array(288);for(Y=0;288>Y;++Y)vc[Y]=Cc.subarray(0,Y);
var Mc={ja:function(){return 0},eb:function(){return 0},fb:function(){},gb:()=>{Aa("")},bb:(a,b,c)=>w.copyWithin(a,b,b+c),Ra:()=>{ab();E=null},ea:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ga:(a,b,c)=>{a=M(a);if(!a)return-4;a=Ab(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},Sa:()=>performance.now(),Ya:(a,b)=>{function c(d){N(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ab:a=>{var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/
c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-pa.buffer.byteLength+65535)/65536;try{pa.grow(e);ta();var h=1;break a}catch(f){}h=void 0}if(h)return!0}return!1},O:(a,b,c,d)=>Db(a,b,c,d,12,"blur"),da:(a,b,c)=>{a=M(a);if(!a)return-4;a.width=b;a.height=c;return 0},P:(a,b,c,d)=>Db(a,b,c,d,13,"focus"),Y:(a,b,c,d)=>Eb(a,b,c,d,2,"keydown"),W:(a,b,c,d)=>Eb(a,b,c,d,1,"keypress"),X:(a,b,c,d)=>Eb(a,b,c,d,3,"keyup"),_a:(a,b,c)=>{a=N(a);Za(a,b,c)},
ca:(a,b,c,d)=>Gb(a,b,c,d,5,"mousedown"),$:(a,b,c,d)=>Gb(a,b,c,d,33,"mouseenter"),_:(a,b,c,d)=>Gb(a,b,c,d,34,"mouseleave"),aa:(a,b,c,d)=>Gb(a,b,c,d,8,"mousemove"),ba:(a,b,c,d)=>Gb(a,b,c,d,6,"mouseup"),R:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.lc||document.body.Ac||document.body.zc))return-1;a=M(a);if(!a)return-4;Hb(a,b,c,d,"mozpointerlockchange");Hb(a,b,c,d,"webkitpointerlockchange");Hb(a,b,c,d,"mspointerlockchange");return Hb(a,b,c,d,"pointerlockchange")},
Q:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.lc||document.body.Ac||document.body.zc))return-1;a=M(a);if(!a)return-4;Ib(a,b,c,d,"mozpointerlockerror");Ib(a,b,c,d,"webkitpointerlockerror");Ib(a,b,c,d,"mspointerlockerror");return Ib(a,b,c,d,"pointerlockerror")},fa:(a,b,c,d)=>Jb(a,b,c,d),S:(a,b,c,d)=>Kb(a,b,c,d,25,"touchcancel"),T:(a,b,c,d)=>Kb(a,b,c,d,23,"touchend"),U:(a,b,c,d)=>Kb(a,b,c,d,24,"touchmove"),V:(a,b,c,d)=>Kb(a,b,c,d,22,"touchstart"),N:(a,b,c,d)=>{jc(a,b,
c,d,31,"webglcontextlost");return 0},M:(a,b,c,d)=>{jc(a,b,c,d,32,"webglcontextrestored");return 0},Z:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?kc(a,b,c,d):-1:-4,Xa:(a,b)=>{b>>=2;b={alpha:!!x[b],depth:!!x[b+1],stencil:!!x[b+2],antialias:!!x[b+3],premultipliedAlpha:!!x[b+4],preserveDrawingBuffer:!!x[b+5],powerPreference:lc[x[b+6]],failIfMajorPerformanceCaveat:!!x[b+7],tc:x[b+8],Zc:x[b+9],xc:x[b+10],Mc:x[b+11],$c:x[b+12],bd:x[b+13]};a=M(a);return!a||b.Mc?0:fc(a,b)},Va:(a,b)=>{a=Zb[a];b=b?D(w,
b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Lb(T);"OES_vertex_array_object"==b&&Ob(T);"WEBGL_draw_buffers"==b&&Pb(T);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Qb(T);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Rb(T);"WEBGL_multi_draw"==b&&(T.Pc=T.getExtension("WEBGL_multi_draw"));return!!a.nc.getExtension(b)},Wa:a=>hc(a)?0:-5,ha:()=>52,db:()=>52,$a:function(){return 70},cb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var f=y[b>>2],l=y[b+4>>2];b+=8;for(var n=
0;n<l;n++){var p=w[f+n],r=mc[a];0===p||10===p?((1===a?oa:m)(D(r,0)),r.length=0):r.push(p)}e+=l}y[d>>2]=e;return 0},i:a=>T.activeTexture(a),z:(a,b)=>{T.attachShader(Q[a],R[b])},b:(a,b)=>{35051==a?T.vc=b:35052==a&&(T.jc=b);T.bindBuffer(a,Ub[b])},a:(a,b,c)=>{T.bindBufferBase(a,b,Ub[c])},q:(a,b)=>{T.bindFramebuffer(a,Vb[b])},Da:(a,b)=>{T.bindRenderbuffer(a,Wb[b])},h:(a,b)=>{T.bindSampler(a,S[b])},c:(a,b)=>{T.bindTexture(a,Xb[b])},L:a=>{T.bindVertexArray(Yb[a])},H:(a,b,c,d)=>T.blendColor(a,b,c,d),I:(a,
b)=>T.blendEquationSeparate(a,b),J:(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),kb:(a,b,c,d,e,h,f,l,n,p)=>T.blitFramebuffer(a,b,c,d,e,h,f,l,n,p),Fa:(a,b,c,d)=>{2<=V.version?c&&b?T.bufferData(a,w,d,c,b):T.bufferData(a,b,d):T.bufferData(a,c?w.subarray(c,c+b):b,d)},B:(a,b,c,d)=>{2<=V.version?c&&T.bufferSubData(a,b,w,d,c):T.bufferSubData(a,b,w.subarray(d,d+c))},Db:(a,b,c,d)=>T.clearBufferfi(a,b,c,d),oa:(a,b,c)=>{T.clearBufferfv(a,b,z,c>>2)},Cb:(a,b,c)=>{T.clearBufferiv(a,b,x,c>>2)},m:(a,b,c,d)=>{T.colorMask(!!a,
!!b,!!c,!!d)},Hb:a=>{T.compileShader(R[a])},za:(a,b,c,d,e,h,f,l)=>{2<=V.version?T.jc||!f?T.compressedTexImage2D(a,b,c,d,e,h,f,l):T.compressedTexImage2D(a,b,c,d,e,h,w,l,f):T.compressedTexImage2D(a,b,c,d,e,h,l?w.subarray(l,l+f):null)},xa:(a,b,c,d,e,h,f,l,n)=>{T.jc?T.compressedTexImage3D(a,b,c,d,e,h,f,l,n):T.compressedTexImage3D(a,b,c,d,e,h,f,w,n,l)},ta:()=>{var a=cc(Q),b=T.createProgram();b.name=a;b.qc=b.oc=b.pc=0;b.uc=1;Q[a]=b;return a},Jb:a=>{var b=cc(R);R[b]=T.createShader(a);return b},E:a=>T.cullFace(a),
Ia:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Ub[d];e&&(T.deleteBuffer(e),e.name=0,Ub[d]=null,d==T.vc&&(T.vc=0),d==T.jc&&(T.jc=0))}},k:(a,b)=>{for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=Vb[d];e&&(T.deleteFramebuffer(e),e.name=0,Vb[d]=null)}},t:a=>{if(a){var b=Q[a];b?(T.deleteProgram(b),b.name=0,Q[a]=null):U||=1281}},C:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Wb[d];e&&(T.deleteRenderbuffer(e),e.name=0,Wb[d]=null)}},j:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=S[d];e&&(T.deleteSampler(e),
e.name=0,S[d]=null)}},r:a=>{if(a){var b=R[a];b?(T.deleteShader(b),R[a]=null):U||=1281}},D:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Xb[d];e&&(T.deleteTexture(e),e.name=0,Xb[d]=null)}},Ha:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2];T.deleteVertexArray(Yb[d]);Yb[d]=null}},w:a=>T.depthFunc(a),v:a=>{T.depthMask(!!a)},e:a=>T.disable(a),K:a=>{T.disableVertexAttribArray(a)},mb:(a,b,c)=>{T.drawArrays(a,b,c)},nb:(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},ob:(a,b,c,d)=>{T.drawElements(a,b,c,d)},
pb:(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},g:a=>T.enable(a),zb:a=>{T.enableVertexAttribArray(a)},F:a=>T.frontFace(a),Ga:(a,b)=>{dc(a,b,"createBuffer",Ub)},Ea:(a,b)=>{dc(a,b,"createRenderbuffer",Wb)},ua:(a,b)=>{dc(a,b,"createSampler",S)},Ba:(a,b)=>{dc(a,b,"createTexture",Xb)},Qa:(a,b)=>{dc(a,b,"createVertexArray",Yb)},Fb:(a,b)=>T.getAttribLocation(Q[a],b?D(w,b):""),d:(a,b)=>oc(a,b),ra:(a,b,c,d)=>{a=T.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(x[c>>2]=
b)},y:(a,b,c)=>{if(c)if(a>=Tb)U||=1281;else if(a=Q[a],35716==b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b){if(!a.qc)for(b=0;b<T.getProgramParameter(a,35718);++b)a.qc=Math.max(a.qc,T.getActiveUniform(a,b).name.length+1);x[c>>2]=a.qc}else if(35722==b){if(!a.oc)for(b=0;b<T.getProgramParameter(a,35721);++b)a.oc=Math.max(a.oc,T.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.oc}else if(35381==b){if(!a.pc)for(b=0;b<T.getProgramParameter(a,35382);++b)a.pc=
Math.max(a.pc,T.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.pc}else x[c>>2]=T.getProgramParameter(a,b);else U||=1281},Gb:(a,b,c,d)=>{a=T.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(x[c>>2]=b)},pa:(a,b,c)=>{c?35716==b?(a=T.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=T.getShaderSource(R[a]),x[c>>2]=a?a.length+1:0):x[c>>2]=T.getShaderParameter(R[a],b):U||=1281},Oa:(a,b)=>{if(2>V.version)return U||=1282,0;var c=$b[a];
if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=nc().map(qc),c=$b[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},p:(a,b)=>{b=b?D(w,b):"";if(a=Q[a]){var c=a,d=c.mc,e=c.Kc,h;if(!d)for(c.mc=d={},c.Jc={},h=0;h<T.getProgramParameter(c,35718);++h){var f=T.getActiveUniform(c,h);var l=f.name;f=f.size;var n=rc(l);n=0<n?l.slice(0,n):l;var p=c.uc;c.uc+=f;e[n]=[f,p];for(l=0;l<f;++l)d[p]=l,c.Jc[p++]=n}c=a.mc;d=0;e=b;h=rc(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=
b.slice(0,h));if((e=a.Kc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else U||=1281;return-1},jb:(a,b,c)=>{for(var d=sc[b],e=0;e<b;e++)d[e]=x[c+4*e>>2];T.invalidateFramebuffer(a,d)},sa:a=>{a=Q[a];T.linkProgram(a);a.mc=0;a.Kc={}},Pa:(a,b)=>{3317==a?ac=b:3314==a&&(bc=b);T.pixelStorei(a,b)},G:(a,b)=>T.polygonOffset(a,b),lb:a=>T.readBuffer(a),Ca:(a,b,c,d,e)=>T.renderbufferStorageMultisample(a,b,c,d,e),A:(a,b,c)=>{T.samplerParameterf(S[a],b,c)},f:(a,b,c)=>{T.samplerParameteri(S[a],
b,c)},n:(a,b,c,d)=>T.scissor(a,b,c,d),Ib:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=y[c+4*h>>2])?D(w,f,d?y[d+4*h>>2]:void 0):"";e+=f}T.shaderSource(R[a],e)},Ma:(a,b,c)=>T.stencilFunc(a,b,c),na:(a,b,c,d)=>T.stencilFuncSeparate(a,b,c,d),u:a=>T.stencilMask(a),La:(a,b,c)=>T.stencilOp(a,b,c),ma:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),ya:(a,b,c,d,e,h,f,l,n)=>{if(2<=V.version){if(T.jc){T.texImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var p=tc(l);n>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);T.texImage2D(a,b,c,
d,e,h,f,l,p,n);return}}p=n?uc(l,f,d,e,n):null;T.texImage2D(a,b,c,d,e,h,f,l,p)},wa:(a,b,c,d,e,h,f,l,n,p)=>{if(T.jc)T.texImage3D(a,b,c,d,e,h,f,l,n,p);else if(p){var r=tc(n);T.texImage3D(a,b,c,d,e,h,f,l,n,r,p>>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else T.texImage3D(a,b,c,d,e,h,f,l,n,null)},Aa:(a,b,c)=>T.texParameteri(a,b,c),ib:(a,b,c,d,e,h,f,l,n)=>{if(2<=V.version){if(T.jc){T.texSubImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var p=tc(l);T.texSubImage2D(a,b,c,d,e,h,f,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));
return}}n=n?uc(l,f,e,h,n):null;T.texSubImage2D(a,b,c,d,e,h,f,l,n)},hb:(a,b,c,d,e,h,f,l,n,p,r)=>{if(T.jc)T.texSubImage3D(a,b,c,d,e,h,f,l,n,p,r);else if(r){var v=tc(p);T.texSubImage3D(a,b,c,d,e,h,f,l,n,p,v,r>>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else T.texSubImage3D(a,b,c,d,e,h,f,l,n,p,null)},yb:(a,b,c)=>{if(2<=V.version)b&&T.uniform1fv(W(a),z,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);T.uniform1fv(W(a),d)}},qa:(a,b)=>{T.uniform1i(W(a),b)},ub:(a,
b,c)=>{if(2<=V.version)b&&T.uniform1iv(W(a),x,c>>2,b);else{if(288>=b)for(var d=vc[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);T.uniform1iv(W(a),d)}},xb:(a,b,c)=>{if(2<=V.version)b&&T.uniform2fv(W(a),z,c>>2,2*b);else{if(144>=b)for(var d=X[2*b],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);T.uniform2fv(W(a),d)}},tb:(a,b,c)=>{if(2<=V.version)b&&T.uniform2iv(W(a),x,c>>2,2*b);else{if(144>=b)for(var d=vc[2*b],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],
d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);T.uniform2iv(W(a),d)}},wb:(a,b,c)=>{if(2<=V.version)b&&T.uniform3fv(W(a),z,c>>2,3*b);else{if(96>=b)for(var d=X[3*b],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);T.uniform3fv(W(a),d)}},sb:(a,b,c)=>{if(2<=V.version)b&&T.uniform3iv(W(a),x,c>>2,3*b);else{if(96>=b)for(var d=vc[3*b],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,
c+12*b>>2);T.uniform3iv(W(a),d)}},vb:(a,b,c)=>{if(2<=V.version)b&&T.uniform4fv(W(a),z,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=z;c>>=2;for(var h=0;h<4*b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=z.subarray(c>>2,c+16*b>>2);T.uniform4fv(W(a),d)}},rb:(a,b,c)=>{if(2<=V.version)b&&T.uniform4iv(W(a),x,c>>2,4*b);else{if(72>=b)for(var d=vc[4*b],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*
b>>2);T.uniform4iv(W(a),d)}},qb:(a,b,c,d)=>{if(2<=V.version)b&&T.uniformMatrix4fv(W(a),!!c,z,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=z;d>>=2;for(var f=0;f<16*b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=z.subarray(d>>2,d+64*b>>2);T.uniformMatrix4fv(W(a),!!c,e)}},l:a=>{a=Q[a];T.useProgram(a);
T.Lc=a},Ab:(a,b)=>{T.vertexAttribDivisor(a,b)},Bb:(a,b,c,d,e,h)=>{T.vertexAttribPointer(a,b,c,!!d,e,h)},o:(a,b,c,d)=>T.viewport(a,b,c,d),Mb:function(){g.Dc=a=>{0!=Dc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Dc)},Za:function(){g.Ic=a=>{const b=a.clipboardData.getData("text");Ac(()=>{const c=xc(b);Ec(c)})};window.addEventListener("paste",g.Ic)},Na:function(a){g.cd=[];a=a?D(w,a):"";a=document.getElementById(a);g.Ec=b=>{b.stopPropagation();b.preventDefault()};
g.Fc=b=>{b.stopPropagation();b.preventDefault()};g.Gc=b=>{b.stopPropagation();b.preventDefault()};g.Hc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.dd=c;Fc(c.length);for(let e=0;e<c.length;e++)Ac(()=>{const h=xc(c[e].name);Gc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Hc(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.Ec,!1);a.addEventListener("dragleave",g.Fc,!1);a.addEventListener("dragover",g.Gc,!1);a.addEventListener("drop",
g.Hc,!1)},Kb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ja:function(a){a=a?D(w,a):"";g.kc=document.getElementById(a);g.kc||console.log("sokol_app.h: invalid target:"+a);g.kc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Lb:function(){window.removeEventListener("beforeunload",g.Dc)},Ua:function(){window.removeEventListener("paste",g.Ic)},Ka:function(a){a=a?D(w,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",
g.Ec);a.removeEventListener("dragleave",g.Fc);a.removeEventListener("dragover",g.Gc);a.removeEventListener("drop",g.Hc)},s:function(){g.kc&&g.kc.requestPointerLock&&g.kc.requestPointerLock()},va:function(a,b){if(g.kc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";
break;case 10:a="not-allowed";break;default:a="auto"}g.kc.style.cursor=a}},Eb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(w.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ta:function(a){a=a?D(w,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");
b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},x:function(a,b,c,d,e,h){b=b?D(w,b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const l=0<d;l&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==
XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!l){const n=new Uint8Array(f.response),p=n.length;p<=h?(w.set(n,e),Ic(a,d,p)):Jc(a)}else Kc(a,f.status)};f.send()},la:function(a,b){b=b?D(w,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");Lc(a,d)}else Kc(a,c.status)};c.send()},ka:function(){return navigator.userAgent.includes("Macintosh")?1:0},ia:function(a,b){b=
b?D(w,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;pa=Z.Nb;ta();Cb=Z.ac;va.unshift(Z.Ob);B--;g.monitorRunDependencies?.(B);0==B&&(null!==za&&(clearInterval(za),za=null),C&&(c=C,C=null,c()));return Z}var b={a:Mc};B++;g.monitorRunDependencies?.(B);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return m(`Module.instantiateWasm callback failed with error: ${c}`),
!1}Ca||=Ba("fontstash-sapp-ui.wasm")?"fontstash-sapp-ui.wasm":g.locateFile?g.locateFile("fontstash-sapp-ui.wasm",k):k+"fontstash-sapp-ui.wasm";Ga(b,function(c){a(c.instance)});return{}}(),P=a=>(P=Z.Pb)(a),Ec=g.__sapp_emsc_onpaste=a=>(Ec=g.__sapp_emsc_onpaste=Z.Qb)(a),Dc=g.__sapp_html5_get_ask_leave_site=()=>(Dc=g.__sapp_html5_get_ask_leave_site=Z.Rb)(),Fc=g.__sapp_emsc_begin_drop=a=>(Fc=g.__sapp_emsc_begin_drop=Z.Sb)(a),Gc=g.__sapp_emsc_drop=(a,b)=>(Gc=g.__sapp_emsc_drop=Z.Tb)(a,b),Hc=g.__sapp_emsc_end_drop=
(a,b,c)=>(Hc=g.__sapp_emsc_end_drop=Z.Ub)(a,b,c);g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,f,l)=>(g.__sapp_emsc_invoke_fetch_cb=Z.Vb)(a,b,c,d,e,h,f,l);var Nc=g._main=(a,b)=>(Nc=g._main=Z.Wb)(a,b);g.__saudio_emsc_pull=a=>(g.__saudio_emsc_pull=Z.Xb)(a);
var Lc=g.__sfetch_emsc_head_response=(a,b)=>(Lc=g.__sfetch_emsc_head_response=Z.Yb)(a,b),Ic=g.__sfetch_emsc_get_response=(a,b,c)=>(Ic=g.__sfetch_emsc_get_response=Z.Zb)(a,b,c),Kc=g.__sfetch_emsc_failed_http_status=(a,b)=>(Kc=g.__sfetch_emsc_failed_http_status=Z._b)(a,b),Jc=g.__sfetch_emsc_failed_buffer_too_small=a=>(Jc=g.__sfetch_emsc_failed_buffer_too_small=Z.$b)(a),zc=a=>(zc=Z.bc)(a),wc=a=>(wc=Z.cc)(a),yc=()=>(yc=Z.dc)(),Oc;C=function Pc(){Oc||Qc();Oc||(C=Pc)};
function Rc(a=[]){var b=Nc;a.unshift(fa);var c=a.length,d=wc(4*(c+1)),e=d;a.forEach(f=>{y[e>>2]=xc(f);e+=4});y[e>>2]=0;try{var h=b(c,d);$a(h)}catch(f){Ya(f)}}
function Qc(){var a=ea;function b(){if(!Oc&&(Oc=!0,g.calledRun=!0,!t)){Ha(va);Ha(wa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();Sc&&Rc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();xa.unshift(c)}Ha(xa)}}if(!(0<B)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ya();Ha(ua);0<B||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Sc=!0;g.noInitialRun&&(Sc=!1);Qc();
