var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},g),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs"),ka=require("path");k=__dirname+"/";ja=a=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a)};ia=a=>{a=la(a)?new URL(a):ka.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!g.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&
document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?"":k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=a=>la(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));g.print||console.log.bind(console);var m=g.printErr||console.error.bind(console);Object.assign(g,da);da=null;g.arguments&&(ea=g.arguments);g.thisProgram&&(fa=g.thisProgram);var ma=g.wasmBinary,na,p=!1,oa,r,t,pa,qa,u,v,w,x;
function ra(){var a=na.buffer;g.HEAP8=r=new Int8Array(a);g.HEAP16=pa=new Int16Array(a);g.HEAPU8=t=new Uint8Array(a);g.HEAPU16=qa=new Uint16Array(a);g.HEAP32=u=new Int32Array(a);g.HEAPU32=v=new Uint32Array(a);g.HEAPF32=w=new Float32Array(a);g.HEAPF64=x=new Float64Array(a)}var sa=[],ta=[],ua=[],va=[];function wa(){var a=g.preRun;a&&("function"==typeof a&&(a=[a]),a.forEach(xa));ya(sa)}function xa(a){sa.unshift(a)}function za(a){va.unshift(a)}var z=0,Aa=null,A=null;
function Ba(a){g.onAbort?.(a);a="Aborted("+a+")";m(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ca=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),Da;function Ea(a){if(a==Da&&ma)return new Uint8Array(ma);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}function Fa(a){return ma?Promise.resolve().then(()=>Ea(a)):ia(a).then(b=>new Uint8Array(b),()=>Ea(a))}
function Ga(a,b,c){return Fa(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{m(`failed to asynchronously prepare wasm: ${d}`);Ba(d)})}function Ha(a,b){var c=Da;ma||"function"!=typeof WebAssembly.instantiateStreaming||Ca(c)||la(c)||ca||"function"!=typeof fetch?Ga(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){m(`wasm streaming compile failed: ${e}`);m("falling back to ArrayBuffer instantiation");return Ga(c,a,b)}))}
function Ia(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var ya=a=>{a.forEach(b=>b(g))},Ja=g.noExitRuntime||!0,B={},Ka=a=>{a instanceof Ia||"unwind"==a||ha(1,a)},La=0,Ma=a=>{oa=a;Ja||0<La||(g.onExit?.(a),p=!0);ha(a,new Ia(a))},Na=a=>{oa=a;Ma(a)},Oa=()=>{if(!(Ja||0<La))try{var a=oa;oa=a;Ma(a)}catch(b){Ka(b)}},Pa=a=>{if(!p)try{a(),Oa()}catch(b){Ka(b)}},Wa=(a,b)=>{Qa=a;Ra=b;if(C)if(Sa||=!0,0==a)D=function(){setTimeout(E,Math.max(0,Ta+b-performance.now())|0)};else if(1==a)D=function(){Ua(E)};else if(2==a){if("undefined"==typeof Va)if("undefined"==typeof setImmediate){var c=
[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Va=d=>{c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Va=setImmediate;D=function(){Va(E)}}},eb=(a,b,c,d,e)=>{function h(){return f<Xa?(Oa(),!1):!0}C=a;Ya=d;var f=Xa;Sa=!1;E=function(){if(!p)if(0<Za.length){var l=Za.shift();l.nd(l.bd);if($a){var n=$a,
q=0==n%1?n-1:Math.floor(n);$a=l.dd?q:(8*n+(q+.5))/9}g.setStatus&&(l=g.statusMessage||"Please wait...",n=$a??0,q=ab.ld??0,n?n<q?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(l):g.setStatus(""));h()&&setTimeout(E,0)}else if(h())if(bb=bb+1|0,1==Qa&&1<Ra&&0!=bb%Ra)D();else{0==Qa&&(Ta=performance.now());a:if(!p){for(l of cb)if(!1===l())break a;Pa(a);for(n of db)n()}h()&&D()}};e||(b&&0<b?Wa(0,1E3/b):Wa(1,1),D());if(c)throw"unwind";},Sa=!1,D=null,Xa=0,C=null,Ya=0,Qa=0,Ra=0,bb=
0,Za=[],cb=[],db=[];function fb(){D=null;Xa++}var G=0;function Ua(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===G)G=b+1E3/60;else for(;b+2>=G;)G+=1E3/60;setTimeout(a,Math.max(G-b,0))}}var ab={},Ta,E,Va,$a;function gb(a){var b=H.bc[a];b.target.removeEventListener(b.ac,b.Gc,b.cc);H.bc.splice(a,1)}function hb(){if(navigator.userActivation?navigator.userActivation.isActive:H.sc&&H.Tc.qc){var a=H.hc;H.hc=[];for(var b of a)b.vc(...b.Ac)}}
function I(a){if(!a.target)return-4;if(a.dc)a.Gc=function(c){++H.sc;H.Tc=a;hb();a.ec(c);hb();--H.sc},a.target.addEventListener(a.ac,a.Gc,a.cc),H.bc.push(a);else for(var b=0;b<H.bc.length;++b)H.bc[b].target==a.target&&H.bc[b].ac==a.ac&&gb(b--);return 0}function ib(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var H={cd:0,od:0,tc:0,oc:0,zc:0,xc:0,rc:0,jd:0,rd:0,hd:0,md:0,uc:0,Ad:0,wc:0,td(){for(;H.bc.length;)gb(H.bc.length-1);H.hc=[]},sc:0,hc:[],gd(a,b,c){function d(h,f){if(h.length!=f.length)return!1;for(var l in h)if(h[l]!=f[l])return!1;return!0}for(var e of H.hc)if(e.vc==a&&d(e.Ac,c))return;H.hc.push({vc:a,Kc:b,Ac:c});H.hc.sort((h,f)=>h.Kc<f.Kc)},vd(a){H.hc=H.hc.filter(b=>b.vc!=a)},bc:[],ud:(a,b)=>{for(var c=0;c<H.bc.length;++c)H.bc[c].target!=a||b&&b!=H.bc[c].ac||gb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||
document.webkitFullscreenEnabled}},jb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,J=(a=0,b=NaN)=>{var c=t,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&jb)return jb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=
String.fromCharCode(e)}return d},kb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?J(a):"":a;return kb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},lb=a=>0>kb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},mb=[],nb,L=a=>{var b=mb[a];b||(a>=mb.length&&(mb.length=a+1),mb[a]=b=nb.get(a));return b},M=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var l=
a.charCodeAt(++h);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},ob=(a,b,c,d,e,h)=>{H.rc||(H.rc=N(256));a={target:K(a),ac:h,dc:d,ec:(f=event)=>{var l=f.target.id?f.target.id:"",n=H.rc;M(ib(f.target),n+0,128);M(l,n+128,128);L(d)(e,n,b)&&f.preventDefault()},cc:c};return I(a)},
pb=(a,b,c,d,e,h)=>{H.tc||(H.tc=N(160));a={target:K(a),ac:h,dc:d,ec:f=>{var l=H.tc;x[l>>3]=f.timeStamp;var n=l>>2;u[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;u[n+5]=f.charCode;u[n+6]=f.keyCode;u[n+7]=f.which;M(f.key||"",l+32,32);M(f.code||"",l+64,32);M(f.char||"",l+96,32);M(f.locale||"",l+128,32);L(d)(e,l,b)&&f.preventDefault()},cc:c};return I(a)},qb=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;
u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=lb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,h)=>{H.oc||(H.oc=N(64));a=K(a);return I({target:a,qc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ac:h,dc:d,ec:(f=event)=>{qb(H.oc,f,a);L(d)(e,H.oc,b)&&f.preventDefault()},cc:c})},rb=(a,b,c,d,e)=>{H.uc||(H.uc=N(257));return I({target:a,ac:e,dc:d,ec:(h=
event)=>{var f=H.uc,l=document.pointerLockElement||document.ic||document.Cc||document.Bc;r[f]=!!l;var n=l?.id||"";M(ib(l),f+1,128);M(n,f+129,128);L(d)(20,f,b)&&h.preventDefault()},cc:c})},sb=(a,b,c,d,e)=>I({target:a,ac:e,dc:d,ec:(h=event)=>{L(d)(38,0,b)&&h.preventDefault()},cc:c}),tb=(a,b,c,d)=>{H.xc||(H.xc=N(36));a=K(a);return I({target:a,ac:"resize",dc:d,ec:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=H.xc;u[f>>2]=0;u[f+4>>2]=h.clientWidth;u[f+8>>2]=h.clientHeight;u[f+12>>2]=innerWidth;
u[f+16>>2]=innerHeight;u[f+20>>2]=outerWidth;u[f+24>>2]=outerHeight;u[f+28>>2]=pageXOffset|0;u[f+32>>2]=pageYOffset|0;L(d)(10,f,b)&&e.preventDefault()}}},cc:c})},ub=(a,b,c,d,e,h)=>{H.wc||(H.wc=N(1552));a=K(a);return I({target:a,qc:"touchstart"==h||"touchend"==h,ac:h,dc:d,ec:f=>{var l={},n=f.touches;for(var q of n)q.Hc=q.Jc=0,l[q.identifier]=q;for(var y of f.changedTouches)y.Hc=1,l[y.identifier]=y;for(var P of f.targetTouches)l[P.identifier].Jc=1;n=H.wc;x[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=
f.shiftKey;r[n+14]=f.altKey;r[n+15]=f.metaKey;q=n+16;y=lb(a);P=0;for(let F of Object.values(l))if(l=q>>2,u[l]=F.identifier,u[l+1]=F.screenX,u[l+2]=F.screenY,u[l+3]=F.clientX,u[l+4]=F.clientY,u[l+5]=F.pageX,u[l+6]=F.pageY,r[q+28]=F.Hc,r[q+29]=F.Jc,u[l+8]=F.clientX-(y.left|0),u[l+9]=F.clientY-(y.top|0),q+=48,31<++P)break;u[n+8>>2]=P;L(d)(e,n,b)&&f.preventDefault()},cc:c})},Q,vb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},wb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},xb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},yb=a=>{a.kd=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
zb=a=>{a.pd=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Ab=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Bb=1,Cb=[],R=[],Db=[],Eb=[],Fb=[],S=[],Gb=[],Hb=[],T=[],Ib={},Jb=4,Kb=0,Lb=a=>{for(var b=Bb++,c=a.length;c<b;c++)a[c]=null;return b},Mb=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=Q[c](),f=h&&Lb(d);h?(h.name=f,d[f]=h):U||=1282;u[b+4*e>>2]=f}},Ob=(a,b)=>{a.ic||(a.ic=a.getContext,a.getContext=function(d,e){e=a.ic(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Ic?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?Nb(c,b):0},Nb=(a,b)=>{var c=Lb(Hb),d={handle:c,attributes:b,version:b.Ic,pc:a};a.canvas&&(a.canvas.ad=d);Hb[c]=d;("undefined"==typeof b.Fc||b.Fc)&&Pb(d);return c},Pb=a=>{a||=V;if(!a.Yc){a.Yc=!0;var b=a.pc;b.Zc=b.getExtension("WEBGL_multi_draw");b.Xc=b.getExtension("EXT_polygon_offset_clamp");b.Wc=b.getExtension("EXT_clip_control");b.$c=b.getExtension("WEBGL_polygon_mode");vb(b);wb(b);xb(b);yb(b);zb(b);2<=a.version&&(b.Ec=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||
!b.Ec)b.Ec=b.getExtension("EXT_disjoint_timer_query");Ab(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},U,V,Qb=(a,b,c,d,e,h)=>{a={target:K(a),ac:h,dc:d,ec:(f=event)=>{L(d)(e,0,b)&&f.preventDefault()},cc:c};I(a)},Rb=(a,b,c,d)=>{H.zc||(H.zc=N(96));return I({target:a,qc:!0,ac:"wheel",dc:d,ec:(e=event)=>{var h=H.zc;qb(h,e,a);x[h+64>>3]=e.deltaX;x[h+72>>3]=e.deltaY;x[h+80>>3]=e.deltaZ;u[h+88>>2]=e.deltaMode;L(d)(9,h,b)&&e.preventDefault()},cc:c})},Sb=["default","low-power",
"high-performance"];function Tb(){var a=Ab(Q);return a=a.concat(a.map(b=>"GL_"+b))}
var Ub=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Q.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=Tb().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=Q.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else U||=1281},Vb=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Wb=a=>{var b=Vb(a)+1,c=N(b);c&&M(a,c,b);return c},Xb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Yb=[],Zb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?u:6==a?w:5==a||28922==a||28520==a||30779==a||30782==a?v:qa},$b=(a,b,c,d,e)=>{a=Zb(a);b=d*((Kb||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Jb-1&-Jb);return a.subarray(e>>>31-
Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=Q.Uc;if(b){var c=b.kc[a];"number"==typeof c&&(b.kc[a]=c=Q.getUniformLocation(b,b.Rc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],ac=[],cc=a=>{var b=Vb(a)+1,c=bc(b);M(a,c,b);return c},fc=a=>{var b=dc();a();ec(b)};g.requestAnimationFrame=Ua;g.pauseMainLoop=fb;g.resumeMainLoop=function(){Xa++;var a=Qa,b=Ra,c=C;C=null;eb(c,0,!1,Ya,!0);Wa(a,b);D()};g.preMainLoop&&cb.push(g.preMainLoop);g.postMainLoop&&db.push(g.postMainLoop);
for(var Y=0;32>Y;++Y)Yb.push(Array(Y));var gc=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=gc.subarray(0,Y);var hc=new Int32Array(288);for(Y=0;288>=Y;++Y)ac[Y]=hc.subarray(0,Y);
var sc={db:()=>{Ba("")},cb:(a,b,c)=>t.copyWithin(a,b,b+c),$a:()=>{Ja=!1;La=0},ab:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];Pa(()=>ic(a,performance.now()))},b);B[a]={id:c,zd:b};return 0},Qa:()=>{fb();C=null},ca:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ea:(a,b,c)=>{a=K(a);if(!a)return-4;a=lb(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},Ra:()=>performance.now(),Ya:(a,b)=>{function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
bb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ra();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},M:(a,b,c,d)=>ob(a,b,c,d,12,"blur"),ba:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},N:(a,b,c,d)=>ob(a,b,c,d,13,"focus"),W:(a,b,c,d)=>pb(a,b,c,d,2,"keydown"),U:(a,b,c,d)=>pb(a,b,c,d,1,"keypress"),
V:(a,b,c,d)=>pb(a,b,c,d,3,"keyup"),Za:(a,b,c)=>{a=L(a);eb(a,b,c)},aa:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),Z:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),Y:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),_:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),$:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),P:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.ic||document.body.Cc||document.body.Bc))return-1;a=K(a);if(!a)return-4;rb(a,b,c,d,"mozpointerlockchange");rb(a,b,c,d,"webkitpointerlockchange");rb(a,
b,c,d,"mspointerlockchange");return rb(a,b,c,d,"pointerlockchange")},O:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.ic||document.body.Cc||document.body.Bc))return-1;a=K(a);if(!a)return-4;sb(a,b,c,d,"mozpointerlockerror");sb(a,b,c,d,"webkitpointerlockerror");sb(a,b,c,d,"mspointerlockerror");return sb(a,b,c,d,"pointerlockerror")},da:(a,b,c,d)=>tb(a,b,c,d),Q:(a,b,c,d)=>ub(a,b,c,d,25,"touchcancel"),R:(a,b,c,d)=>ub(a,b,c,d,23,"touchend"),S:(a,b,c,d)=>ub(a,b,c,d,24,"touchmove"),
T:(a,b,c,d)=>ub(a,b,c,d,22,"touchstart"),L:(a,b,c,d)=>{Qb(a,b,c,d,31,"webglcontextlost");return 0},K:(a,b,c,d)=>{Qb(a,b,c,d,32,"webglcontextrestored");return 0},X:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?Rb(a,b,c,d):-1:-4,Xa:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Sb[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Ic:u[c+4],qd:u[c+5],Fc:r[b+24],Vc:r[b+25],sd:u[c+7],wd:r[b+
32]};a=K(a);return!a||b.Vc?0:Ob(a,b)},Ua:(a,b)=>{a=Hb[a];b=b?J(b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&vb(Q);"OES_vertex_array_object"==b&&wb(Q);"WEBGL_draw_buffers"==b&&xb(Q);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&yb(Q);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&zb(Q);"WEBGL_multi_draw"==b&&(Q.Zc=Q.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(Q.Xc=Q.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&
(Q.Wc=Q.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(Q.$c=Q.getExtension("WEBGL_polygon_mode"));return!!a.pc.getExtension(b)},Va:a=>{V=Hb[a];g.ed=Q=V?.pc;return!a||Q?0:-5},i:a=>Q.activeTexture(a),x:(a,b)=>{Q.attachShader(R[a],S[b])},b:(a,b)=>{35051==a?Q.Dc=b:35052==a&&(Q.fc=b);Q.bindBuffer(a,Cb[b])},a:(a,b,c)=>{Q.bindBufferBase(a,b,Cb[c])},n:(a,b)=>{Q.bindFramebuffer(a,Db[b])},Ca:(a,b)=>{Q.bindRenderbuffer(a,Eb[b])},h:(a,b)=>{Q.bindSampler(a,T[b])},c:(a,b)=>{Q.bindTexture(a,Fb[b])},
J:a=>{Q.bindVertexArray(Gb[a])},F:(a,b,c,d)=>Q.blendColor(a,b,c,d),G:(a,b)=>Q.blendEquationSeparate(a,b),H:(a,b,c,d)=>Q.blendFuncSeparate(a,b,c,d),hb:(a,b,c,d,e,h,f,l,n,q)=>Q.blitFramebuffer(a,b,c,d,e,h,f,l,n,q),Fa:(a,b,c,d)=>{2<=V.version?c&&b?Q.bufferData(a,t,d,c,b):Q.bufferData(a,b,d):Q.bufferData(a,c?t.subarray(c,c+b):b,d)},z:(a,b,c,d)=>{2<=V.version?c&&Q.bufferSubData(a,b,t,d,c):Q.bufferSubData(a,b,t.subarray(d,d+c))},Ab:(a,b,c,d)=>Q.clearBufferfi(a,b,c,d),ia:(a,b,c)=>{Q.clearBufferfv(a,b,w,
c>>2)},zb:(a,b,c)=>{Q.clearBufferiv(a,b,u,c>>2)},l:(a,b,c,d)=>{Q.colorMask(!!a,!!b,!!c,!!d)},Db:a=>{Q.compileShader(S[a])},wa:(a,b,c,d,e,h,f,l)=>{2<=V.version?Q.fc||!f?Q.compressedTexImage2D(a,b,c,d,e,h,f,l):Q.compressedTexImage2D(a,b,c,d,e,h,t,l,f):Q.compressedTexImage2D(a,b,c,d,e,h,t.subarray(l,l+f))},ua:(a,b,c,d,e,h,f,l,n)=>{Q.fc?Q.compressedTexImage3D(a,b,c,d,e,h,f,l,n):Q.compressedTexImage3D(a,b,c,d,e,h,f,t,n,l)},qa:()=>{var a=Lb(R),b=Q.createProgram();b.name=a;b.nc=b.lc=b.mc=0;b.yc=1;R[a]=b;
return a},Fb:a=>{var b=Lb(S);S[b]=Q.createShader(a);return b},C:a=>Q.cullFace(a),Ia:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Cb[d];e&&(Q.deleteBuffer(e),e.name=0,Cb[d]=null,d==Q.Dc&&(Q.Dc=0),d==Q.fc&&(Q.fc=0))}},j:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=Db[d];e&&(Q.deleteFramebuffer(e),e.name=0,Db[d]=null)}},p:a=>{if(a){var b=R[a];b?(Q.deleteProgram(b),b.name=0,R[a]=null):U||=1281}},A:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Eb[d];e&&(Q.deleteRenderbuffer(e),e.name=0,Eb[d]=
null)}},q:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=T[d];e&&(Q.deleteSampler(e),e.name=0,T[d]=null)}},o:a=>{if(a){var b=S[a];b?(Q.deleteShader(b),S[a]=null):U||=1281}},B:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Fb[d];e&&(Q.deleteTexture(e),e.name=0,Fb[d]=null)}},Ha:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];Q.deleteVertexArray(Gb[d]);Gb[d]=null}},u:a=>Q.depthFunc(a),t:a=>{Q.depthMask(!!a)},e:a=>Q.disable(a),I:a=>{Q.disableVertexAttribArray(a)},jb:(a,b,c)=>{Q.drawArrays(a,b,c)},
kb:(a,b,c,d)=>{Q.drawArraysInstanced(a,b,c,d)},lb:(a,b,c,d)=>{Q.drawElements(a,b,c,d)},mb:(a,b,c,d,e)=>{Q.drawElementsInstanced(a,b,c,d,e)},g:a=>Q.enable(a),wb:a=>{Q.enableVertexAttribArray(a)},D:a=>Q.frontFace(a),Ga:(a,b)=>{Mb(a,b,"createBuffer",Cb)},Ea:(a,b)=>{Mb(a,b,"createRenderbuffer",Eb)},ra:(a,b)=>{Mb(a,b,"createSampler",T)},Aa:(a,b)=>{Mb(a,b,"createTexture",Fb)},Pa:(a,b)=>{Mb(a,b,"createVertexArray",Gb)},Bb:(a,b)=>Q.getAttribLocation(R[a],b?J(b):""),d:(a,b)=>Ub(a,b),oa:(a,b,c,d)=>{a=Q.getProgramInfoLog(R[a]);
null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},w:(a,b,c)=>{if(c)if(a>=Bb)U||=1281;else if(a=R[a],35716==b)a=Q.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.nc){var d=Q.getProgramParameter(a,35718);for(b=0;b<d;++b)a.nc=Math.max(a.nc,Q.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.nc}else if(35722==b){if(!a.lc)for(d=Q.getProgramParameter(a,35721),b=0;b<d;++b)a.lc=Math.max(a.lc,Q.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.lc}else if(35381==
b){if(!a.mc)for(d=Q.getProgramParameter(a,35382),b=0;b<d;++b)a.mc=Math.max(a.mc,Q.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.mc}else u[c>>2]=Q.getProgramParameter(a,b);else U||=1281},Cb:(a,b,c,d)=>{a=Q.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},la:(a,b,c)=>{c?35716==b?(a=Q.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(S[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=Q.getShaderParameter(S[a],
b):U||=1281},Na:(a,b)=>{if(2>V.version)return U||=1282,0;var c=Ib[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Tb().map(Wb),c=Ib[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},m:(a,b)=>{b=b?J(b):"";if(a=R[a]){var c=a,d=c.kc,e=c.Sc,h;if(!d){c.kc=d={};c.Rc={};var f=Q.getProgramParameter(c,35718);for(h=0;h<f;++h){var l=Q.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Xb(n);q=0<q?n.slice(0,q):n;var y=c.yc;c.yc+=l;e[q]=[l,y];for(n=0;n<l;++n)d[y]=
n,c.Rc[y++]=q}}c=a.kc;d=0;e=b;h=Xb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Sc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||Q.getUniformLocation(a,b)))return d}else U||=1281;return-1},gb:(a,b,c)=>{for(var d=Yb[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];Q.invalidateFramebuffer(a,d)},pa:a=>{a=R[a];Q.linkProgram(a);a.kc=0;a.Sc={}},Oa:(a,b)=>{3317==a?Jb=b:3314==a&&(Kb=b);Q.pixelStorei(a,b)},E:(a,b)=>Q.polygonOffset(a,b),ib:a=>Q.readBuffer(a),Ba:(a,b,c,d,e)=>Q.renderbufferStorageMultisample(a,b,c,d,e),y:(a,
b,c)=>{Q.samplerParameterf(T[a],b,c)},f:(a,b,c)=>{Q.samplerParameteri(T[a],b,c)},ja:(a,b,c,d)=>Q.scissor(a,b,c,d),Eb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=v[c+4*h>>2])?J(f,d?v[d+4*h>>2]:void 0):"";e+=f}Q.shaderSource(S[a],e)},La:(a,b,c)=>Q.stencilFunc(a,b,c),ha:(a,b,c,d)=>Q.stencilFuncSeparate(a,b,c,d),s:a=>Q.stencilMask(a),Ka:(a,b,c)=>Q.stencilOp(a,b,c),ga:(a,b,c,d)=>Q.stencilOpSeparate(a,b,c,d),va:(a,b,c,d,e,h,f,l,n)=>{if(2<=V.version){if(Q.fc){Q.texImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var q=
Zb(l);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);Q.texImage2D(a,b,c,d,e,h,f,l,q,n);return}}q=n?$b(l,f,d,e,n):null;Q.texImage2D(a,b,c,d,e,h,f,l,q)},ta:(a,b,c,d,e,h,f,l,n,q)=>{if(Q.fc)Q.texImage3D(a,b,c,d,e,h,f,l,n,q);else if(q){var y=Zb(n);Q.texImage3D(a,b,c,d,e,h,f,l,n,y,q>>>31-Math.clz32(y.BYTES_PER_ELEMENT))}else Q.texImage3D(a,b,c,d,e,h,f,l,n,null)},za:(a,b,c)=>Q.texParameteri(a,b,c),ya:(a,b,c,d,e)=>Q.texStorage2D(a,b,c,d,e),xa:(a,b,c,d,e,h)=>Q.texStorage3D(a,b,c,d,e,h),fb:(a,b,c,d,e,h,f,l,n)=>{if(2<=
V.version){if(Q.fc){Q.texSubImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var q=Zb(l);Q.texSubImage2D(a,b,c,d,e,h,f,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}n=n?$b(l,f,e,h,n):null;Q.texSubImage2D(a,b,c,d,e,h,f,l,n)},eb:(a,b,c,d,e,h,f,l,n,q,y)=>{if(Q.fc)Q.texSubImage3D(a,b,c,d,e,h,f,l,n,q,y);else if(y){var P=Zb(q);Q.texSubImage3D(a,b,c,d,e,h,f,l,n,q,P,y>>>31-Math.clz32(P.BYTES_PER_ELEMENT))}else Q.texSubImage3D(a,b,c,d,e,h,f,l,n,q,null)},vb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform1fv(W(a),w,c>>
2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);Q.uniform1fv(W(a),d)}},ma:(a,b)=>{Q.uniform1i(W(a),b)},rb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=ac[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);Q.uniform1iv(W(a),d)}},ub:(a,b,c)=>{if(2<=V.version)b&&Q.uniform2fv(W(a),w,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,
c+8*b>>2);Q.uniform2fv(W(a),d)}},qb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=ac[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);Q.uniform2iv(W(a),d)}},tb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform3fv(W(a),w,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);Q.uniform3fv(W(a),d)}},pb:(a,b,c)=>{if(2<=V.version)b&&
Q.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b){b*=3;for(var d=ac[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);Q.uniform3iv(W(a),d)}},sb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform4fv(W(a),w,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=w;c>>=2;b*=4;for(var h=0;h<b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=w.subarray(c>>2,c+16*b>>2);Q.uniform4fv(W(a),d)}},ob:(a,b,c)=>{if(2<=V.version)b&&Q.uniform4iv(W(a),u,c>>
2,4*b);else{if(72>=b){b*=4;for(var d=ac[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);Q.uniform4iv(W(a),d)}},nb:(a,b,c,d)=>{if(2<=V.version)b&&Q.uniformMatrix4fv(W(a),!!c,w,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=w;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+
10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);Q.uniformMatrix4fv(W(a),!!c,e)}},k:a=>{a=R[a];Q.useProgram(a);Q.Uc=a},xb:(a,b)=>{Q.vertexAttribDivisor(a,b)},yb:(a,b,c,d,e,h)=>{Q.vertexAttribPointer(a,b,c,!!d,e,h)},ka:(a,b,c,d)=>Q.viewport(a,b,c,d),_a:Ma,Hb:function(){g.Lc=a=>{0!=jc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Lc)},Wa:function(){g.Qc=a=>{const b=a.clipboardData.getData("text");
fc(()=>{const c=cc(b);kc(c)})};window.addEventListener("paste",g.Qc)},Sa:function(a){g.xd=[];a=a?J(a):"";a=document.getElementById(a);g.Mc=b=>{b.stopPropagation();b.preventDefault()};g.Nc=b=>{b.stopPropagation();b.preventDefault()};g.Oc=b=>{b.stopPropagation();b.preventDefault()};g.Pc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.yd=c;lc(c.length);for(let e=0;e<c.length;e++)fc(()=>{const h=cc(c[e].name);mc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=
4);b.metaKey&&(d|=8);nc(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.Mc,!1);a.addEventListener("dragleave",g.Nc,!1);a.addEventListener("dragover",g.Oc,!1);a.addEventListener("drop",g.Pc,!1)},Da:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ja:function(a){a=a?J(a):"";g.jc=document.getElementById(a);g.jc||console.log("sokol_app.h: invalid target:"+a);g.jc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+
a)},Gb:function(){window.removeEventListener("beforeunload",g.Lc)},Ta:function(){window.removeEventListener("paste",g.Qc)},Ma:function(a){a=a?J(a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.Mc);a.removeEventListener("dragleave",g.Nc);a.removeEventListener("dragover",g.Oc);a.removeEventListener("drop",g.Pc)},r:function(){g.jc&&g.jc.requestPointerLock&&g.jc.requestPointerLock()},sa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),
h=e.createImageData(a,b);h.data.set(t.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},v:function(a,b,c,d,e,h){b=b?J(b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const l=0<d;l&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!l){const n=new Uint8Array(f.response),
q=n.length;q<=h?(t.set(n,e),oc(a,d,q)):pc(a)}else qc(a,f.status)};f.send()},na:function(a,b){b=b?J(b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");rc(a,d)}else qc(a,c.status)};c.send()},fa:function(a,b){b=b?J(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=
c.exports;na=Z.Ib;ra();nb=Z.Yb;ta.unshift(Z.Jb);z--;g.monitorRunDependencies?.(z);0==z&&(null!==Aa&&(clearInterval(Aa),Aa=null),A&&(c=A,A=null,c()));return Z}var b={a:sc};z++;g.monitorRunDependencies?.(z);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return m(`Module.instantiateWasm callback failed with error: ${c}`),!1}Da??=Ca("fontstash-sapp.wasm")?"fontstash-sapp.wasm":g.locateFile?g.locateFile("fontstash-sapp.wasm",k):k+"fontstash-sapp.wasm";Ha(b,function(c){a(c.instance)});
return{}}(),N=a=>(N=Z.Kb)(a),kc=g.__sapp_emsc_onpaste=a=>(kc=g.__sapp_emsc_onpaste=Z.Lb)(a),jc=g.__sapp_html5_get_ask_leave_site=()=>(jc=g.__sapp_html5_get_ask_leave_site=Z.Mb)(),lc=g.__sapp_emsc_begin_drop=a=>(lc=g.__sapp_emsc_begin_drop=Z.Nb)(a),mc=g.__sapp_emsc_drop=(a,b)=>(mc=g.__sapp_emsc_drop=Z.Ob)(a,b),nc=g.__sapp_emsc_end_drop=(a,b,c)=>(nc=g.__sapp_emsc_end_drop=Z.Pb)(a,b,c);g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,f,l)=>(g.__sapp_emsc_invoke_fetch_cb=Z.Qb)(a,b,c,d,e,h,f,l);
var tc=g._main=(a,b)=>(tc=g._main=Z.Rb)(a,b);g.__saudio_emsc_pull=a=>(g.__saudio_emsc_pull=Z.Sb)(a);
var rc=g.__sfetch_emsc_head_response=(a,b)=>(rc=g.__sfetch_emsc_head_response=Z.Tb)(a,b),oc=g.__sfetch_emsc_get_response=(a,b,c)=>(oc=g.__sfetch_emsc_get_response=Z.Ub)(a,b,c),qc=g.__sfetch_emsc_failed_http_status=(a,b)=>(qc=g.__sfetch_emsc_failed_http_status=Z.Vb)(a,b),pc=g.__sfetch_emsc_failed_buffer_too_small=a=>(pc=g.__sfetch_emsc_failed_buffer_too_small=Z.Wb)(a),ic=(a,b)=>(ic=Z.Xb)(a,b),ec=a=>(ec=Z.Zb)(a),bc=a=>(bc=Z._b)(a),dc=()=>(dc=Z.$b)(),uc,vc;A=function wc(){uc||xc();uc||(A=wc)};
function yc(a=[]){var b=tc;a.unshift(fa);var c=a.length,d=bc(4*(c+1)),e=d;a.forEach(f=>{v[e>>2]=cc(f);e+=4});v[e>>2]=0;try{var h=b(c,d);Na(h)}catch(f){Ka(f)}}function xc(){var a=ea;function b(){if(!uc&&(uc=1,g.calledRun=1,!p)){ya(ta);ya(ua);g.onRuntimeInitialized?.();zc&&yc(a);var c=g.postRun;c&&("function"==typeof c&&(c=[c]),c.forEach(za));ya(va)}}if(!(0<z)){if(!vc&&(vc=1,wa(),0<z))return;g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var zc=!0;g.noInitialRun&&(zc=!1);xc();
