var g;g||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},g),ba=[],ca="./this.program",k=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,r,v;
if(ea){var fs=require("fs"),ha=require("path");q=l?ha.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=ia(a)?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};r=(a,b,c,d=!0)=>{a=ia(a)?new URL(a):ha.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,h)=>{e?c(e):b(d?h.buffer:h)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof ja||a.context instanceof ja))throw a;});k=(a,b)=>{process.exitCode=a;throw b;}}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);
return new Uint8Array(b.response)}),r=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};g.print||console.log.bind(console);var w=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(k=g.quit);var x;g.wasmBinary&&(x=g.wasmBinary);"object"!=typeof WebAssembly&&ka("no native wasm support detected");
var la,ma=!1,na,y,oa,pa,z,qa,A,B;function ra(){var a=la.buffer;g.HEAP8=na=new Int8Array(a);g.HEAP16=oa=new Int16Array(a);g.HEAPU8=y=new Uint8Array(a);g.HEAPU16=pa=new Uint16Array(a);g.HEAP32=z=new Int32Array(a);g.HEAPU32=qa=new Uint32Array(a);g.HEAPF32=A=new Float32Array(a);g.HEAPF64=B=new Float64Array(a)}var sa=[],ta=[],ua=[],va=[];function wa(){var a=g.preRun.shift();sa.unshift(a)}var C=0,xa=null,D=null;
function ka(a){g.onAbort?.(a);a="Aborted("+a+")";w(a);ma=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ya=a=>a.startsWith("data:application/octet-stream;base64,"),ia=a=>a.startsWith("file://"),E;E="fontstash-sapp.wasm";if(!ya(E)){var za=E;E=g.locateFile?g.locateFile(za,q):q+za}function Aa(a){if(a==E&&x)return new Uint8Array(x);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}
function Ba(a){if(!x&&(da||l)){if("function"==typeof fetch&&!ia(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Aa(a));if(r)return new Promise((b,c)=>{r(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Aa(a))}function Ca(a,b,c){return Ba(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{w(`failed to asynchronously prepare wasm: ${d}`);ka(d)})}
function Da(a,b){var c=E;x||"function"!=typeof WebAssembly.instantiateStreaming||ya(c)||ia(c)||ea||"function"!=typeof fetch?Ca(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){w(`wasm streaming compile failed: ${e}`);w("falling back to ArrayBuffer instantiation");return Ca(c,a,b)}))}function ja(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ea=a=>{for(;0<a.length;)a.shift()(g)},Fa=g.noExitRuntime||!0,Ia=a=>{var b=Ga();a();Ha(b)},Ja=0,Ka=[];function La(){if(navigator.userActivation?navigator.userActivation.isActive:Ja&&Ma.ec)for(var a=0;a<Ka.length;++a){var b=Ka[a];Ka.splice(a,1);--a;b.Mc.apply(null,b.Dc)}}var F=[];function Na(a){var b=F[a];b.target.removeEventListener(b.Tb,b.mc,b.Ub);F.splice(a,1)}
function G(a){if(!a.target)return-4;if(a.Vb)a.mc=function(c){++Ja;Ma=a;La();a.Wb(c);La();--Ja},a.target.addEventListener(a.Tb,a.mc,a.Ub),F.push(a);else for(var b=0;b<F.length;++b)F[b].target==a.target&&F[b].Tb==a.Tb&&Na(b--);return 0}function Oa(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var Ma,Pa,Qa,Ra,Sa,Ta,Ua,Va,Wa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,H=(a,b)=>{var c=y,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&Wa)return Wa.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Xa=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],I=a=>{a=2<a?a?H(a):"":a;return Xa[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Ya=a=>0>Xa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Za=[],$a,J=a=>{var b=Za[a];b||(a>=Za.length&&(Za.length=a+1),Za[a]=b=$a.get(a));return b},K=(a,b,c)=>{var d=y;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var m=a.charCodeAt(++h);f=65536+((f&
1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},ab=(a,b,c,d,e,h)=>{Pa||=L(256);a={target:I(a),Tb:h,Vb:d,Wb:(f=event)=>{var m=f.target.id?f.target.id:"",n=Pa;K(Oa(f.target),n+0,128);K(m,n+128,128);J(d)(e,n,b)&&f.preventDefault()},Ub:c};return G(a)},bb=(a,b,c,d,e,h)=>{Qa||=L(176);a={target:I(a),
Tb:h,Vb:d,Wb:f=>{var m=Qa;B[m>>3]=f.timeStamp;var n=m>>2;z[n+2]=f.location;z[n+3]=f.ctrlKey;z[n+4]=f.shiftKey;z[n+5]=f.altKey;z[n+6]=f.metaKey;z[n+7]=f.repeat;z[n+8]=f.charCode;z[n+9]=f.keyCode;z[n+10]=f.which;K(f.key||"",m+44,32);K(f.code||"",m+76,32);K(f.char||"",m+108,32);K(f.locale||"",m+140,32);J(d)(e,m,b)&&f.preventDefault()},Ub:c};return G(a)},cb=(a,b,c)=>{B[a>>3]=b.timeStamp;a>>=2;z[a+2]=b.screenX;z[a+3]=b.screenY;z[a+4]=b.clientX;z[a+5]=b.clientY;z[a+6]=b.ctrlKey;z[a+7]=b.shiftKey;z[a+8]=
b.altKey;z[a+9]=b.metaKey;oa[2*a+20]=b.button;oa[2*a+21]=b.buttons;z[a+11]=b.movementX;z[a+12]=b.movementY;c=Ya(c);z[a+13]=b.clientX-c.left;z[a+14]=b.clientY-c.top},M=(a,b,c,d,e,h)=>{Ra||=L(72);a=I(a);return G({target:a,ec:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Tb:h,Vb:d,Wb:(f=event)=>{cb(Ra,f,a);J(d)(e,Ra,b)&&f.preventDefault()},Ub:c})},db=(a,b,c,d,e)=>{Sa||=L(260);return G({target:a,Tb:e,Vb:d,Wb:(h=event)=>{var f=Sa,m=document.pointerLockElement||document.Yb||document.ic||document.hc;
z[f>>2]=!!m;var n=m?.id||"";K(Oa(m),f+4,128);K(n,f+132,128);J(d)(20,f,b)&&h.preventDefault()},Ub:c})},eb=(a,b,c,d,e)=>G({target:a,Tb:e,Vb:d,Wb:(h=event)=>{J(d)(38,0,b)&&h.preventDefault()},Ub:c}),fb=(a,b,c,d)=>{Ta||=L(36);a=I(a);return G({target:a,Tb:"resize",Vb:d,Wb:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=Ta;z[f>>2]=e.detail;z[f+4>>2]=h.clientWidth;z[f+8>>2]=h.clientHeight;z[f+12>>2]=innerWidth;z[f+16>>2]=innerHeight;z[f+20>>2]=outerWidth;z[f+24>>2]=outerHeight;z[f+28>>2]=pageXOffset;
z[f+32>>2]=pageYOffset;J(d)(10,f,b)&&e.preventDefault()}}},Ub:c})},gb=(a,b,c,d,e,h)=>{Ua||=L(1696);a=I(a);return G({target:a,ec:"touchstart"==h||"touchend"==h,Tb:h,Vb:d,Wb:f=>{for(var m,n={},p=f.touches,t=0;t<p.length;++t)m=p[t],m.nc=m.pc=0,n[m.identifier]=m;for(t=0;t<f.changedTouches.length;++t)m=f.changedTouches[t],m.nc=1,n[m.identifier]=m;for(t=0;t<f.targetTouches.length;++t)n[f.targetTouches[t].identifier].pc=1;p=Ua;B[p>>3]=f.timeStamp;var u=p>>2;z[u+3]=f.ctrlKey;z[u+4]=f.shiftKey;z[u+5]=f.altKey;
z[u+6]=f.metaKey;u+=7;var lb=Ya(a),mb=0;for(t in n)if(m=n[t],z[u]=m.identifier,z[u+1]=m.screenX,z[u+2]=m.screenY,z[u+3]=m.clientX,z[u+4]=m.clientY,z[u+5]=m.pageX,z[u+6]=m.pageY,z[u+7]=m.nc,z[u+8]=m.pc,z[u+9]=m.clientX-lb.left,z[u+10]=m.clientY-lb.top,u+=13,31<++mb)break;z[p+8>>2]=mb;J(d)(e,p,b)&&f.preventDefault()},Ub:c})},hb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,
d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},ib=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},jb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},kb=a=>{a.Fc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
nb=a=>{a.Gc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")};
function ob(a){var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");return(a.getSupportedExtensions()||
[]).filter(c=>b.includes(c))}var pb=1,qb=[],N=[],rb=[],sb=[],tb=[],O=[],ub=[],vb=[],P=[],wb={},xb=4;function Q(a){yb||=a}
var zb=a=>{for(var b=pb++,c=a.length;c<b;c++)a[c]=null;return b},Bb=(a,b)=>{a.Yb||(a.Yb=a.getContext,a.getContext=function(d,e){e=a.Yb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.oc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Ab(c,b):0},Ab=(a,b)=>{var c=zb(vb),d={handle:c,attributes:b,version:b.oc,dc:a};a.canvas&&(a.canvas.Cc=d);vb[c]=d;("undefined"==typeof b.lc||b.lc)&&Cb(d);return c},Cb=a=>{a||=R;if(!a.Ac){a.Ac=!0;var b=a.dc;hb(b);ib(b);jb(b);kb(b);
nb(b);2<=a.version&&(b.kc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.kc)b.kc=b.getExtension("EXT_disjoint_timer_query");b.Bc=b.getExtension("WEBGL_multi_draw");ob(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},yb,R,Db=(a,b,c,d,e,h)=>{a={target:I(a),Tb:h,Vb:d,Wb:(f=event)=>{J(d)(e,0,b)&&f.preventDefault()},Ub:c};G(a)},Eb=(a,b,c,d)=>{Va||=L(104);return G({target:a,ec:!0,Tb:"wheel",Vb:d,Wb:(e=event)=>{var h=Va;cb(h,e,a);B[h+72>>3]=e.deltaX;
B[h+80>>3]=e.deltaY;B[h+88>>3]=e.deltaZ;z[h+96>>2]=e.deltaMode;J(d)(9,h,b)&&e.preventDefault()},Ub:c})},Fb=["default","low-power","high-performance"],T=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=S[c](),f=h&&zb(d);h?(h.name=f,d[f]=h):Q(1282);z[b+4*e>>2]=f}};function Gb(){var a=ob(S);return a=a.concat(a.map(b=>"GL_"+b))}
for(var Hb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>R.version){Q(1282);return}c=Gb().length;break;case 33307:case 33308:if(2>R.version){Q(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Q(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:Q(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)z[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Q(1280);w(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:Q(1280);w(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}z[b>>2]=c}else Q(1281)},Ib=a=>
{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Jb=a=>{var b=Ib(a)+1,c=L(b);c&&K(a,c,b);return c},Kb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Lb=[],U=a=>{a-=5120;return 0==a?na:1==a?y:2==a?oa:4==a?z:6==a?A:5==a||28922==a||28520==a||30779==a||30782==a?qa:pa},Mb=(a,b,c,d,e)=>{a=U(a);var h=31-Math.clz32(a.BYTES_PER_ELEMENT),f=xb;return a.subarray(e>>h,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||
1)*(1<<h)+f-1&-f)>>h)},V=a=>{var b=S.yc;if(b){var c=b.$b[a];"number"==typeof c&&(b.$b[a]=c=S.getUniformLocation(b,b.wc[a]+(0<c?`[${c}]`:"")));return c}Q(1282)},W=[],X=[],Nb=a=>{Fa||(g.onExit?.(a),ma=!0);k(a,new ja(a))},Pb=a=>{var b=Ib(a)+1,c=Ob(b);K(a,c,b);return c},S,Y=0;32>Y;++Y)Lb.push(Array(Y));var Qb=new Float32Array(288);for(Y=0;288>Y;++Y)W[Y]=Qb.subarray(0,Y+1);var Rb=new Int32Array(288);for(Y=0;288>Y;++Y)X[Y]=Rb.subarray(0,Y+1);
var ac={g:()=>{ka("")},da:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ea:(a,b,c)=>{a=I(a);if(!a)return-4;a=Ya(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},_a:(a,b,c)=>y.copyWithin(a,b,b+c),Xa:(a,b)=>{function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Za:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-
la.buffer.byteLength+65535)/65536;try{la.grow(e);ra();var h=1;break a}catch(f){}h=void 0}if(h)return!0}return!1},N:(a,b,c,d)=>ab(a,b,c,d,12,"blur"),ca:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},O:(a,b,c,d)=>ab(a,b,c,d,13,"focus"),X:(a,b,c,d)=>bb(a,b,c,d,2,"keydown"),V:(a,b,c,d)=>bb(a,b,c,d,1,"keypress"),W:(a,b,c,d)=>bb(a,b,c,d,3,"keyup"),ba:(a,b,c,d)=>M(a,b,c,d,5,"mousedown"),_:(a,b,c,d)=>M(a,b,c,d,33,"mouseenter"),Z:(a,b,c,d)=>M(a,b,c,d,34,"mouseleave"),$:(a,b,c,d)=>M(a,b,c,d,
8,"mousemove"),aa:(a,b,c,d)=>M(a,b,c,d,6,"mouseup"),Q:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Yb||document.body.ic||document.body.hc))return-1;a=I(a);if(!a)return-4;db(a,b,c,d,"mozpointerlockchange");db(a,b,c,d,"webkitpointerlockchange");db(a,b,c,d,"mspointerlockchange");return db(a,b,c,d,"pointerlockchange")},P:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.Yb||document.body.ic||document.body.hc))return-1;a=I(a);if(!a)return-4;
eb(a,b,c,d,"mozpointerlockerror");eb(a,b,c,d,"webkitpointerlockerror");eb(a,b,c,d,"mspointerlockerror");return eb(a,b,c,d,"pointerlockerror")},Ya:(a,b,c,d)=>fb(a,b,c,d),R:(a,b,c,d)=>gb(a,b,c,d,25,"touchcancel"),S:(a,b,c,d)=>gb(a,b,c,d,23,"touchend"),T:(a,b,c,d)=>gb(a,b,c,d,24,"touchmove"),U:(a,b,c,d)=>gb(a,b,c,d,22,"touchstart"),M:(a,b,c,d)=>{Db(a,b,c,d,31,"webglcontextlost");return 0},L:(a,b,c,d)=>{Db(a,b,c,d,32,"webglcontextrestored");return 0},Y:(a,b,c,d)=>(a=I(a))?"undefined"!=typeof a.onwheel?
Eb(a,b,c,d):-1:-4,Ua:(a,b)=>{b>>=2;b={alpha:!!z[b],depth:!!z[b+1],stencil:!!z[b+2],antialias:!!z[b+3],premultipliedAlpha:!!z[b+4],preserveDrawingBuffer:!!z[b+5],powerPreference:Fb[z[b+6]],failIfMajorPerformanceCaveat:!!z[b+7],oc:z[b+8],Hc:z[b+9],lc:z[b+10],zc:z[b+11],Ic:z[b+12],Jc:z[b+13]};a=I(a);return!a||b.zc?0:Bb(a,b)},Sa:(a,b)=>{a=vb[a];b=b?H(b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&hb(S);"OES_vertex_array_object"==b&&ib(S);"WEBGL_draw_buffers"==b&&jb(S);"WEBGL_draw_instanced_base_vertex_base_instance"==
b&&kb(S);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&nb(S);"WEBGL_multi_draw"==b&&(S.Bc=S.getExtension("WEBGL_multi_draw"));return!!a.dc.getExtension(b)},Wa:a=>{a>>=2;for(var b=0;14>b;++b)z[a+b]=0;z[a]=z[a+1]=z[a+3]=z[a+4]=z[a+8]=z[a+10]=1},Ta:a=>{R=vb[a];g.Ec=S=R?.dc;return!a||S?0:-5},h:function(a){S.activeTexture(a)},y:(a,b)=>{S.attachShader(N[a],O[b])},a:(a,b)=>{35051==a?S.jc=b:35052==a&&(S.Xb=b);S.bindBuffer(a,qb[b])},m:(a,b)=>{S.bindFramebuffer(a,rb[b])},Ca:(a,b)=>{S.bindRenderbuffer(a,
sb[b])},i:(a,b)=>{S.bindSampler(a,P[b])},b:(a,b)=>{S.bindTexture(a,tb[b])},H:a=>{S.bindVertexArray(ub[a])},D:function(a,b,c,d){S.blendColor(a,b,c,d)},E:function(a,b){S.blendEquationSeparate(a,b)},F:function(a,b,c,d){S.blendFuncSeparate(a,b,c,d)},cb:function(a,b,c,d,e,h,f,m,n,p){S.blitFramebuffer(a,b,c,d,e,h,f,m,n,p)},Ea:(a,b,c,d)=>{2<=R.version?c&&b?S.bufferData(a,y,d,c,b):S.bufferData(a,b,d):S.bufferData(a,c?y.subarray(c,c+b):b,d)},o:(a,b,c,d)=>{2<=R.version?c&&S.bufferSubData(a,b,y,d,c):S.bufferSubData(a,
b,y.subarray(d,d+c))},vb:function(a,b,c,d){S.clearBufferfi(a,b,c,d)},ja:(a,b,c)=>{S.clearBufferfv(a,b,A,c>>2)},ub:(a,b,c)=>{S.clearBufferiv(a,b,z,c>>2)},j:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},na:a=>{S.compileShader(O[a])},ya:(a,b,c,d,e,h,f,m)=>{2<=R.version?S.Xb||!f?S.compressedTexImage2D(a,b,c,d,e,h,f,m):S.compressedTexImage2D(a,b,c,d,e,h,y,m,f):S.compressedTexImage2D(a,b,c,d,e,h,m?y.subarray(m,m+f):null)},wa:(a,b,c,d,e,h,f,m,n)=>{S.Xb?S.compressedTexImage3D(a,b,c,d,e,h,f,m,n):S.compressedTexImage3D(a,
b,c,d,e,h,f,y,n,m)},ta:()=>{var a=zb(N),b=S.createProgram();b.name=a;b.cc=b.ac=b.bc=0;b.fc=1;N[a]=b;return a},pa:a=>{var b=zb(O);O[b]=S.createShader(a);return b},A:function(a){S.cullFace(a)},Oa:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=qb[d];e&&(S.deleteBuffer(e),e.name=0,qb[d]=null,d==S.jc&&(S.jc=0),d==S.Xb&&(S.Xb=0))}},k:(a,b)=>{for(var c=0;c<a;++c){var d=z[b+4*c>>2],e=rb[d];e&&(S.deleteFramebuffer(e),e.name=0,rb[d]=null)}},u:a=>{if(a){var b=N[a];b?(S.deleteProgram(b),b.name=0,N[a]=null):
Q(1281)}},J:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=sb[d];e&&(S.deleteRenderbuffer(e),e.name=0,sb[d]=null)}},I:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=P[d];e&&(S.deleteSampler(e),e.name=0,P[d]=null)}},p:a=>{if(a){var b=O[a];b?(S.deleteShader(b),O[a]=null):Q(1281)}},K:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=tb[d];e&&(S.deleteTexture(e),e.name=0,tb[d]=null)}},Ma:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2];S.deleteVertexArray(ub[d]);ub[d]=null}},t:function(a){S.depthFunc(a)},
s:a=>{S.depthMask(!!a)},d:function(a){S.disable(a)},G:a=>{S.disableVertexAttribArray(a)},eb:(a,b,c)=>{S.drawArrays(a,b,c)},fb:(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},gb:(a,b,c,d)=>{S.drawElements(a,b,c,d)},hb:(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},f:function(a){S.enable(a)},rb:a=>{S.enableVertexAttribArray(a)},B:function(a){S.frontFace(a)},Fa:(a,b)=>{T(a,b,"createBuffer",qb)},Da:(a,b)=>{T(a,b,"createRenderbuffer",sb)},ua:(a,b)=>{T(a,b,"createSampler",P)},Aa:(a,b)=>{T(a,b,"createTexture",
tb)},La:function(a,b){T(a,b,"createVertexArray",ub)},wb:(a,b)=>S.getAttribLocation(N[a],b?H(b):""),c:(a,b)=>Hb(a,b),qa:(a,b,c,d)=>{a=S.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(z[c>>2]=b)},x:(a,b,c)=>{if(c)if(a>=pb)Q(1281);else if(a=N[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),z[c>>2]=a.length+1;else if(35719==b){if(!a.cc)for(b=0;b<S.getProgramParameter(a,35718);++b)a.cc=Math.max(a.cc,S.getActiveUniform(a,b).name.length+1);z[c>>2]=a.cc}else if(35722==
b){if(!a.ac)for(b=0;b<S.getProgramParameter(a,35721);++b)a.ac=Math.max(a.ac,S.getActiveAttrib(a,b).name.length+1);z[c>>2]=a.ac}else if(35381==b){if(!a.bc)for(b=0;b<S.getProgramParameter(a,35382);++b)a.bc=Math.max(a.bc,S.getActiveUniformBlockName(a,b).length+1);z[c>>2]=a.bc}else z[c>>2]=S.getProgramParameter(a,b);else Q(1281)},xb:(a,b,c,d)=>{a=S.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(z[c>>2]=b)},ma:(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(O[a]),null===a&&(a=
"(unknown error)"),z[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(O[a]),z[c>>2]=a?a.length+1:0):z[c>>2]=S.getShaderParameter(O[a],b):Q(1281)},Pa:(a,b)=>{if(2>R.version)return Q(1282),0;var c=wb[a];if(c)return 0>b||b>=c.length?(Q(1281),0):c[b];switch(a){case 7939:return c=Gb().map(Jb),c=wb[a]=c,0>b||b>=c.length?(Q(1281),0):c[b];default:return Q(1280),0}},n:(a,b)=>{b=b?H(b):"";if(a=N[a]){var c=a,d=c.$b,e=c.xc,h;if(!d)for(c.$b=d={},c.wc={},h=0;h<S.getProgramParameter(c,35718);++h){var f=S.getActiveUniform(c,
h);var m=f.name;f=f.size;var n=Kb(m);n=0<n?m.slice(0,n):m;var p=c.fc;c.fc+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.wc[p++]=n}c=a.$b;d=0;e=b;h=Kb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.xc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else Q(1281);return-1},bb:(a,b,c)=>{for(var d=Lb[b],e=0;e<b;e++)d[e]=z[c+4*e>>2];S.invalidateFramebuffer(a,d)},ra:a=>{a=N[a];S.linkProgram(a);a.$b=0;a.xc={}},Ka:(a,b)=>{3317==a&&(xb=b);S.pixelStorei(a,b)},C:function(a,b){S.polygonOffset(a,
b)},db:function(a){S.readBuffer(a)},Ba:function(a,b,c,d,e){S.renderbufferStorageMultisample(a,b,c,d,e)},z:(a,b,c)=>{S.samplerParameterf(P[a],b,c)},e:(a,b,c)=>{S.samplerParameteri(P[a],b,c)},ka:function(a,b,c,d){S.scissor(a,b,c,d)},oa:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=d?z[d+4*h>>2]:-1,m=z[c+4*h>>2];f=m?H(m,0>f?void 0:f):"";e+=f}S.shaderSource(O[a],e)},Ia:function(a,b,c){S.stencilFunc(a,b,c)},ia:function(a,b,c,d){S.stencilFuncSeparate(a,b,c,d)},r:function(a){S.stencilMask(a)},Ha:function(a,
b,c){S.stencilOp(a,b,c)},ga:function(a,b,c,d){S.stencilOpSeparate(a,b,c,d)},xa:(a,b,c,d,e,h,f,m,n)=>{if(2<=R.version)if(S.Xb)S.texImage2D(a,b,c,d,e,h,f,m,n);else if(n){var p=U(m);S.texImage2D(a,b,c,d,e,h,f,m,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else S.texImage2D(a,b,c,d,e,h,f,m,null);else S.texImage2D(a,b,c,d,e,h,f,m,n?Mb(m,f,d,e,n):null)},va:(a,b,c,d,e,h,f,m,n,p)=>{if(S.Xb)S.texImage3D(a,b,c,d,e,h,f,m,n,p);else if(p){var t=U(n);S.texImage3D(a,b,c,d,e,h,f,m,n,t,p>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else S.texImage3D(a,
b,c,d,e,h,f,m,n,null)},za:function(a,b,c){S.texParameteri(a,b,c)},ab:(a,b,c,d,e,h,f,m,n)=>{if(2<=R.version)if(S.Xb)S.texSubImage2D(a,b,c,d,e,h,f,m,n);else if(n){var p=U(m);S.texSubImage2D(a,b,c,d,e,h,f,m,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else S.texSubImage2D(a,b,c,d,e,h,f,m,null);else p=null,n&&(p=Mb(m,f,e,h,n)),S.texSubImage2D(a,b,c,d,e,h,f,m,p)},$a:(a,b,c,d,e,h,f,m,n,p,t)=>{if(S.Xb)S.texSubImage3D(a,b,c,d,e,h,f,m,n,p,t);else if(t){var u=U(p);S.texSubImage3D(a,b,c,d,e,h,f,m,n,p,u,t>>31-Math.clz32(u.BYTES_PER_ELEMENT))}else S.texSubImage3D(a,
b,c,d,e,h,f,m,n,p,null)},qb:(a,b,c)=>{if(2<=R.version)b&&S.uniform1fv(V(a),A,c>>2,b);else{if(288>=b)for(var d=W[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);S.uniform1fv(V(a),d)}},w:(a,b)=>{S.uniform1i(V(a),b)},mb:(a,b,c)=>{if(2<=R.version)b&&S.uniform1iv(V(a),z,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);S.uniform1iv(V(a),d)}},pb:(a,b,c)=>{if(2<=R.version)b&&S.uniform2fv(V(a),A,c>>2,2*b);else{if(144>=b)for(var d=W[2*
b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);S.uniform2fv(V(a),d)}},lb:(a,b,c)=>{if(2<=R.version)b&&S.uniform2iv(V(a),z,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);S.uniform2iv(V(a),d)}},ob:(a,b,c)=>{if(2<=R.version)b&&S.uniform3fv(V(a),A,c>>2,3*b);else{if(96>=b)for(var d=W[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=
A.subarray(c>>2,c+12*b>>2);S.uniform3fv(V(a),d)}},kb:(a,b,c)=>{if(2<=R.version)b&&S.uniform3iv(V(a),z,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);S.uniform3iv(V(a),d)}},nb:(a,b,c)=>{if(2<=R.version)b&&S.uniform4fv(V(a),A,c>>2,4*b);else{if(72>=b){var d=W[4*b-1],e=A;c>>=2;for(var h=0;h<4*b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=A.subarray(c>>2,c+16*b>>2);
S.uniform4fv(V(a),d)}},jb:(a,b,c)=>{if(2<=R.version)b&&S.uniform4iv(V(a),z,c>>2,4*b);else{if(72>=b)for(var d=X[4*b-1],e=0;e<4*b;e+=4)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2],d[e+3]=z[c+(4*e+12)>>2];else d=z.subarray(c>>2,c+16*b>>2);S.uniform4iv(V(a),d)}},ib:(a,b,c,d)=>{if(2<=R.version)b&&S.uniformMatrix4fv(V(a),!!c,A,d>>2,16*b);else{if(18>=b){var e=W[16*b-1],h=A;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=h[m];e[f+1]=h[m+1];e[f+2]=h[m+2];e[f+3]=h[m+3];e[f+4]=h[m+4];e[f+5]=
h[m+5];e[f+6]=h[m+6];e[f+7]=h[m+7];e[f+8]=h[m+8];e[f+9]=h[m+9];e[f+10]=h[m+10];e[f+11]=h[m+11];e[f+12]=h[m+12];e[f+13]=h[m+13];e[f+14]=h[m+14];e[f+15]=h[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(V(a),!!c,e)}},l:a=>{a=N[a];S.useProgram(a);S.yc=a},sb:(a,b)=>{S.vertexAttribDivisor(a,b)},tb:(a,b,c,d,e,h)=>{S.vertexAttribPointer(a,b,c,!!d,e,h)},la:function(a,b,c,d){S.viewport(a,b,c,d)},zb:function(){g.qc=a=>{0!=Sb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",
g.qc)},Ra:function(){g.vc=a=>{const b=a.clipboardData.getData("text");Ia(()=>{const c=Pb(b);Tb(c)})};window.addEventListener("paste",g.vc)},Na:function(a){g.Kc=[];a=a?H(a):"";a=document.getElementById(a);g.rc=b=>{b.stopPropagation();b.preventDefault()};g.sc=b=>{b.stopPropagation();b.preventDefault()};g.tc=b=>{b.stopPropagation();b.preventDefault()};g.uc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Lc=c;Ub(c.length);for(let e=0;e<c.length;e++)Ia(()=>{const h=Pb(c[e].name);
Vb(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Wb(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.rc,!1);a.addEventListener("dragleave",g.sc,!1);a.addEventListener("dragover",g.tc,!1);a.addEventListener("drop",g.uc,!1)},sa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ga:function(a){a=a?H(a):"";g.Zb=document.getElementById(a);g.Zb||console.log("sokol_app.h: invalid target:"+a);g.Zb.requestPointerLock||
console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Va:function(){window.removeEventListener("beforeunload",g.qc)},Qa:function(){window.removeEventListener("paste",g.vc)},Ja:function(a){a=a?H(a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.rc);a.removeEventListener("dragleave",g.sc);a.removeEventListener("dragover",g.tc);a.removeEventListener("drop",g.uc)},q:function(){g.Zb&&g.Zb.requestPointerLock&&g.Zb.requestPointerLock()},yb:function(a,b,c){const d=
document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(y.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},v:function(a,b,c,d,e,h){b=b?H(b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const m=0<d;m&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==
XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!m){const n=new Uint8Array(f.response),p=n.length;p<=h?(y.set(n,e),Xb(a,d,p)):Yb(a)}else Zb(a,f.status)};f.send()},ha:function(a,b){b=b?H(b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");$b(a,d)}else Zb(a,c.status)};c.send()},fa:function(a,b){b=b?H(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);
break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;la=Z.Ab;ra();$a=Z.Pb;ta.unshift(Z.Bb);C--;g.monitorRunDependencies?.(C);0==C&&(null!==xa&&(clearInterval(xa),xa=null),D&&(c=D,D=null,c()));return Z}var b={a:ac};C++;g.monitorRunDependencies?.(C);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return w(`Module.instantiateWasm callback failed with error: ${c}`),!1}Da(b,function(c){a(c.instance)});return{}}(),L=a=>(L=Z.Cb)(a),Tb=g.__sapp_emsc_onpaste=
a=>(Tb=g.__sapp_emsc_onpaste=Z.Db)(a),Sb=g.__sapp_html5_get_ask_leave_site=()=>(Sb=g.__sapp_html5_get_ask_leave_site=Z.Eb)(),Ub=g.__sapp_emsc_begin_drop=a=>(Ub=g.__sapp_emsc_begin_drop=Z.Fb)(a),Vb=g.__sapp_emsc_drop=(a,b)=>(Vb=g.__sapp_emsc_drop=Z.Gb)(a,b),Wb=g.__sapp_emsc_end_drop=(a,b,c)=>(Wb=g.__sapp_emsc_end_drop=Z.Hb)(a,b,c);g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,f,m)=>(g.__sapp_emsc_invoke_fetch_cb=Z.Ib)(a,b,c,d,e,h,f,m);var bc=g._main=(a,b)=>(bc=g._main=Z.Jb)(a,b);
g.__saudio_emsc_pull=a=>(g.__saudio_emsc_pull=Z.Kb)(a);var $b=g.__sfetch_emsc_head_response=(a,b)=>($b=g.__sfetch_emsc_head_response=Z.Lb)(a,b),Xb=g.__sfetch_emsc_get_response=(a,b,c)=>(Xb=g.__sfetch_emsc_get_response=Z.Mb)(a,b,c),Zb=g.__sfetch_emsc_failed_http_status=(a,b)=>(Zb=g.__sfetch_emsc_failed_http_status=Z.Nb)(a,b),Yb=g.__sfetch_emsc_failed_buffer_too_small=a=>(Yb=g.__sfetch_emsc_failed_buffer_too_small=Z.Ob)(a),Ga=()=>(Ga=Z.Qb)(),Ha=a=>(Ha=Z.Rb)(a),Ob=a=>(Ob=Z.Sb)(a);g.___start_em_js=7496;
g.___stop_em_js=16717;var cc;D=function dc(){cc||ec();cc||(D=dc)};function fc(a=[]){var b=bc;a.unshift(ca);var c=a.length,d=Ob(4*(c+1)),e=d;a.forEach(f=>{qa[e>>2]=Pb(f);e+=4});qa[e>>2]=0;try{var h=b(c,d);Nb(h)}catch(f){f instanceof ja||"unwind"==f||k(1,f)}}
function ec(){var a=ba;function b(){if(!cc&&(cc=!0,g.calledRun=!0,!ma)){Ea(ta);Ea(ua);if(g.onRuntimeInitialized)g.onRuntimeInitialized();gc&&fc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();va.unshift(c)}Ea(va)}}if(!(0<C)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)wa();Ea(sa);0<C||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var gc=!0;g.noInitialRun&&(gc=!1);ec();
