var g;g||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var k=console.error.bind(console),m,p=!1,ma,la=a=>a.startsWith("file://");
function na(){var a=oa.buffer;r=new Int8Array(a);pa=new Int16Array(a);t=new Uint8Array(a);qa=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function ra(a){g.onAbort?.(a);a=`Aborted(${a})`;k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var sa;
async function ta(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==sa&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function ua(a,b){try{var c=await ta(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ra(d)}}
async function va(a){var b=sa;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ua(b,a)}class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var pa,v,r,x,y,qa,w,t,xa=a=>{for(;0<a.length;)a.shift()(g)},ya=[],za=[],Aa=()=>{var a=g.preRun.shift();za.push(a)},z=0,A=null,Ba=!0,Ca=0,C={},Da=a=>{a instanceof wa||"unwind"==a||fa(1,a)},Ea=a=>{ma=a;Ba||0<Ca||(g.onExit?.(a),p=!0);fa(a,new wa(a))},Fa=()=>{if(!(Ba||0<Ca))try{var a=ma;ma=a;Ea(a)}catch(b){Da(b)}},Ga=a=>{if(!p)try{a()}catch(b){Da(b)}finally{Fa()}},Na=(a,b)=>{Ha=a;Ia=b;if(D)if(Ja||=!0,0==a)E=function(){setTimeout(F,Math.max(0,Ka+b-performance.now())|0)};else if(1==a)E=function(){La(F)};
else{if(!Ma)if(globalThis.setImmediate)Ma=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ma=d=>{c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}E=function(){Ma(F)}}},Wa=(a,b,c,d,e)=>{function h(){return f<Oa?(Fa(),!1):!0}D=a;Pa=d;var f=Oa;Ja=!1;F=function(){if(!p)if(0<Qa.length){var l=
Qa.shift();l.rd(l.dd);if(Ra){var n=Ra,q=0==n%1?n-1:Math.floor(n);Ra=l.hd?q:(8*n+(q+.5))/9}g.setStatus&&(l=g.statusMessage||"Please wait...",n=Ra??0,q=Sa.od??0,n?n<q?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(l):g.setStatus(""));h()&&setTimeout(F,0)}else if(h())if(Ta=Ta+1|0,1==Ha&&1<Ia&&0!=Ta%Ia)E();else{0==Ha&&(Ka=performance.now());a:if(!p){for(l of Ua)if(!1===l())break a;Ga(a);for(n of Va)n()}h()&&E()}};e||(0<b?Na(0,1E3/b):Na(1,1),E());if(c)throw"unwind";},Ja=!1,E=
null,Oa=0,D=null,Pa=0,Ha=0,Ia=0,Ta=0,Qa=[],Ua=[],Va=[];function Xa(){E=null;Oa++}var G=0;function La(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===G)G=b+1E3/60;else for(;b+2>=G;)G+=1E3/60;setTimeout(a,Math.max(G-b,0))}}
var Sa={},Ka,F,Ma,Ra,Ya=globalThis.TextDecoder&&new TextDecoder,H=(a=0,b)=>{var c=t;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&Ya)return Ya.decode(c.subarray(a,d));for(b="";a<d;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))b+=String.fromCharCode((e&31)<<6|h);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|c[a++]&63;65536>e?b+=String.fromCharCode(e):(e-=65536,b+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else b+=String.fromCharCode(e)}return b},
Za=[0,globalThis.document??0,globalThis.window??0],I=a=>{a=2<a?a?H(a):"":a;return Za[a]||globalThis.document?.querySelector(a)},$a=a=>0>Za.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},ab=[],J=a=>{var b=ab[a];b||(ab[a]=b=bb.get(a));return b};function cb(a){var b=K.ec[a];b.target.removeEventListener(b.dc,b.Lc,b.ic);K.ec.splice(a,1)}function db(){if(navigator.userActivation?navigator.userActivation.isActive:K.xc&&K.Yc.uc){var a=K.mc;K.mc=[];for(var b of a)b.Ac(...b.Gc)}}
function L(a){if(!a.target)return-4;if(a.fc)a.Lc=function(c){++K.xc;K.Yc=a;db();a.kc(c);db();--K.xc},a.target.addEventListener(a.dc,a.Lc,a.ic),K.ec.push(a);else for(var b=0;b<K.ec.length;++b)K.ec[b].target==a.target&&K.ec[b].dc==a.dc&&cb(b--);return 0}function eb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var K={ed:0,sd:0,yc:0,sc:0,Ec:0,Cc:0,vc:0,md:0,wd:0,ld:0,wc:0,zc:0,Gd:0,Bc:0,yd(){for(;K.ec.length;)cb(K.ec.length-1);K.mc=[]},xc:0,mc:[],kd(a,b,c){function d(h,f){if(h.length!=f.length)return!1;for(var l in h)if(h[l]!=f[l])return!1;return!0}for(var e of K.mc)if(e.Ac==a&&d(e.Gc,c))return;K.mc.push({Ac:a,Pc:b,Gc:c});K.mc.sort((h,f)=>h.Pc-f.Pc)},Ad(a){K.mc=K.mc.filter(b=>b.Ac!=a)},ec:[],zd:(a,b)=>{for(var c=0;c<K.ec.length;++c)K.ec[c].target!=a||b&&b!=K.ec[c].dc||cb(c--)},Bd(a){let b=!1;for(let c=0;c<
K.ec.length;++c){const d=K.ec[c];d.target===a.target&&d.hc===a.hc&&d.fc===a.fc&&d.jc===a.jc&&(cb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},M=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.codePointAt(h);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&
63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;h++}}d[b]=0;return b-e},fb=(a,b,c,d,e,h)=>{K.vc||(K.vc=O(256));a={target:I(a),dc:h,hc:e,jc:b,fc:d,kc:f=>{var l=f.target.id?f.target.id:"",n=K.vc;M(eb(f.target),n+0,128);M(l,n+128,128);J(d)(e,n,b)&&f.preventDefault()},ic:c};return L(a)},gb=(a,b,c,d,e)=>{K.wc||(K.wc=O(276));return L({target:a,dc:e,hc:19,jc:b,fc:d,kc:h=>{var f=K.wc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!l;r[f]=n;r[f+1]=K.fullscreenEnabled();var q=n?l:K.bd,u=q?.id||"";M(eb(q),f+2,128);M(u,f+130,128);v[f+260>>2]=q?q.clientWidth:0;v[f+264>>2]=q?q.clientHeight:0;v[f+268>>2]=screen.width;v[f+272>>2]=screen.height;n&&(K.bd=l);J(d)(19,f,b)&&h.preventDefault()},ic:c})},hb=(a,b,c,d,e,h)=>{K.yc||(K.yc=O(160));a={target:I(a),dc:h,hc:e,jc:b,fc:d,kc:f=>{var l=K.yc;y[l>>3]=f.timeStamp;var n=l>>2;v[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=
f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;v[n+5]=f.charCode;v[n+6]=f.keyCode;v[n+7]=f.which;M(f.key||"",l+32,32);M(f.code||"",l+64,32);M(f.char||"",l+96,32);M(f.locale||"",l+128,32);J(d)(e,l,b)&&f.preventDefault()},ic:c};return L(a)},ib=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+
9]=b.movementY;a=$a(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},P=(a,b,c,d,e,h)=>{K.sc||(K.sc=O(64));a=I(a);return L({target:a,uc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,dc:h,hc:e,jc:b,fc:d,kc:f=>{ib(K.sc,f,a);J(d)(e,K.sc,b)&&f.preventDefault()},ic:c})},jb=(a,b,c,d)=>{K.zc||(K.zc=O(257));return L({target:a,dc:"pointerlockchange",hc:20,jc:b,fc:d,kc:e=>{var h=K.zc,f=document.pointerLockElement;r[h]=!!f;var l=f?.id||"";M(eb(f),h+1,128);M(l,h+129,128);J(d)(20,h,b)&&e.preventDefault()},
ic:c})},kb=(a,b,c,d)=>L({target:a,dc:"pointerlockerror",hc:38,jc:b,fc:d,kc:e=>{J(d)(38,0,b)&&e.preventDefault()},ic:c}),lb=(a,b,c,d)=>{K.Cc||(K.Cc=O(36));a=I(a);return L({target:a,dc:"resize",hc:10,jc:b,fc:d,kc:e=>{if(e.target==a){var h=document.body;if(h){var f=K.Cc;v[f>>2]=0;v[f+4>>2]=h.clientWidth;v[f+8>>2]=h.clientHeight;v[f+12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+20>>2]=outerWidth;v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|0;v[f+32>>2]=pageYOffset|0;J(d)(10,f,b)&&e.preventDefault()}}},
ic:c})},mb=(a,b,c,d,e,h)=>{K.Bc||(K.Bc=O(1552));a=I(a);return L({target:a,uc:"touchstart"==h||"touchend"==h,dc:h,hc:e,jc:b,fc:d,kc:f=>{var l={},n=f.touches;for(var q of n)q.Mc=q.Oc=0,l[q.identifier]=q;for(var u of f.changedTouches)u.Mc=1,l[u.identifier]=u;for(var N of f.targetTouches)l[N.identifier].Oc=1;n=K.Bc;y[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=f.shiftKey;r[n+14]=f.altKey;r[n+15]=f.metaKey;q=n+16;u=$a(a);N=0;for(let B of Object.values(l))if(l=q>>2,v[l]=B.identifier,v[l+1]=B.screenX,v[l+
2]=B.screenY,v[l+3]=B.clientX,v[l+4]=B.clientY,v[l+5]=B.pageX,v[l+6]=B.pageY,r[q+28]=B.Mc,r[q+29]=B.Oc,v[l+8]=B.clientX-(u.left|0),v[l+9]=B.clientY-(u.top|0),q+=48,31<++N)break;v[n+8>>2]=N;J(d)(e,n,b)&&f.preventDefault()},ic:c})},Q,nb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},ob=
a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},pb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},qb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},rb=1,sb=[],R=[],tb=[],ub=[],S=[],T=[],vb=[],wb=[],U=[],xb={},yb=4,zb=0,Ab=a=>{for(var b=rb++,c=a.length;c<b;c++)a[c]=null;return b},Bb=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=Q[c](),f=h&&Ab(d);h?(h.name=f,d[f]=h):V||=1282;v[b+4*e>>2]=f}},Db=(a,b)=>{a.Ic||(a.Ic=a.getContext,a.getContext=function(d,e){e=a.Ic(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Nc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?Cb(c,b):0},Cb=(a,b)=>{var c=Ab(wb),d={handle:c,attributes:b,version:b.Nc,Fc:a};a.canvas&&(a.canvas.cd=d);wb[c]=d;if("undefined"==typeof b.Kc||b.Kc)if((a=d)||(a=W),!a.ad){a.ad=!0;b=a.Fc;b.vd=b.getExtension("WEBGL_multi_draw");b.qd=b.getExtension("EXT_polygon_offset_clamp");b.pd=b.getExtension("EXT_clip_control");b.Hd=b.getExtension("WEBGL_polygon_mode");nb(b);ob(b);pb(b);b.nd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.td=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Jc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Jc)b.Jc=b.getExtension("EXT_disjoint_timer_query");for(var e of qb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},V,W,Eb=(a,b,c,d,e,h)=>{a={target:I(a),dc:h,hc:e,jc:b,fc:d,kc:f=>{J(d)(e,0,b)&&f.preventDefault()},ic:c};L(a)},Fb=(a,b,c,d)=>{K.Ec||(K.Ec=O(96));return L({target:a,uc:!0,dc:"wheel",hc:9,jc:b,fc:d,kc:e=>{var h=K.Ec;ib(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+
80>>3]=e.deltaZ;v[h+88>>2]=e.deltaMode;J(d)(9,h,b)&&e.preventDefault()},ic:c})},Gb=["default","low-power","high-performance"],Hb=[],Ib=()=>{var a=qb(Q);return a=a.concat(a.map(b=>"GL_"+b))},Jb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Q.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>W.version){V||=1282;return}c=Ib().length;break;case 33307:case 33308:if(2>W.version){V||=1280;return}c=33307==a?3:0}if(void 0===
c)switch(d=Q.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":V||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:V||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=
0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){V||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:V||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else V||=1281},Kb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Lb=a=>{var b=Kb(a)+
1,c=O(b);c&&M(a,c,b);return c},Mb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Nb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?w:qa},X=a=>{var b=Q.Zc;if(b){var c=b.oc[a];"number"==typeof c&&(b.oc[a]=c=Q.getUniformLocation(b,b.Wc[a]+(0<c?`[${c}]`:"")));return c}V||=1282},Y=[],Ob=[],Qb=a=>{var b=Kb(a)+1,c=Pb(b);M(a,c,b);return c},Tb=a=>{var b=Rb();a();Sb(b)};g.requestAnimationFrame=La;g.pauseMainLoop=Xa;
g.resumeMainLoop=function(){Oa++;var a=Ha,b=Ia,c=D;D=null;Wa(c,0,!1,Pa,!0);Na(a,b);E()};g.preMainLoop&&Ua.push(g.preMainLoop);g.postMainLoop&&Va.push(g.postMainLoop);for(let a=0;32>a;++a)Hb.push(Array(a));for(var Ub=new Float32Array(288),Z=0;288>=Z;++Z)Y[Z]=Ub.subarray(0,Z);var Vb=new Int32Array(288);for(Z=0;288>=Z;++Z)Ob[Z]=Vb.subarray(0,Z);g.noExitRuntime&&(Ba=g.noExitRuntime);g.printErr&&(k=g.printErr);g.wasmBinary&&(m=g.wasmBinary);g.arguments&&(da=g.arguments);g.thisProgram&&(ea=g.thisProgram);
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();
var O,Wb,Xb,Yb,Zb,$b,ac,bc,Sb,Pb,Rb,oa,bb,cc={ab:()=>ra(""),$a:()=>{Ba=!1;Ca=0},Ya:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ga(()=>bc(a,performance.now()))},b);C[a]={id:c,Fd:b};return 0},Pa:()=>{Xa();D=null},ja:()=>globalThis.devicePixelRatio??1,la:(a,b,c)=>{a=I(a);if(!a)return-4;a=$a(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Qa:()=>performance.now(),Wa:(a,b)=>{function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
Za:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);na();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},T:(a,b,c,d)=>fb(a,b,c,d,12,"blur"),ia:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},U:(a,b,c,d)=>fb(a,b,c,d,13,"focus"),S:(a,b,c,d)=>{if(!K.fullscreenEnabled())return-1;a=I(a);if(!a)return-4;
gb(a,b,c,d,"webkitfullscreenchange");return gb(a,b,c,d,"fullscreenchange")},ba:(a,b,c,d)=>hb(a,b,c,d,2,"keydown"),$:(a,b,c,d)=>hb(a,b,c,d,1,"keypress"),aa:(a,b,c,d)=>hb(a,b,c,d,3,"keyup"),Xa:(a,b,c)=>{a=J(a);Wa(a,b,c)},ha:(a,b,c,d)=>P(a,b,c,d,5,"mousedown"),ea:(a,b,c,d)=>P(a,b,c,d,33,"mouseenter"),da:(a,b,c,d)=>P(a,b,c,d,34,"mouseleave"),fa:(a,b,c,d)=>P(a,b,c,d,8,"mousemove"),ga:(a,b,c,d)=>P(a,b,c,d,6,"mouseup"),W:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?jb(a,b,c,d):-4:-1,V:(a,b,c,d)=>
document.body?.requestPointerLock?(a=I(a))?kb(a,b,c,d):-4:-1,ka:(a,b,c,d)=>lb(a,b,c,d),X:(a,b,c,d)=>mb(a,b,c,d,25,"touchcancel"),Y:(a,b,c,d)=>mb(a,b,c,d,23,"touchend"),Z:(a,b,c,d)=>mb(a,b,c,d,24,"touchmove"),_:(a,b,c,d)=>mb(a,b,c,d,22,"touchstart"),R:(a,b,c,d)=>{Eb(a,b,c,d,31,"webglcontextlost");return 0},Q:(a,b,c,d)=>{Eb(a,b,c,d,32,"webglcontextrestored");return 0},ca:(a,b,c,d)=>(a=I(a))?"undefined"!=typeof a.onwheel?Fb(a,b,c,d):-1:-4,Va:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+
2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Gb[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Nc:v[c+4],ud:v[c+5],Kc:r[b+24],$c:r[b+25],xd:v[c+7],Cd:r[b+32]};a=I(a);return!a||b.$c?0:Db(a,b)},Ta:a=>{W=wb[a];g.ctx=Q=W?.Fc;return!a||Q?0:-5},o:a=>Q.activeTexture(a),r:(a,b)=>{Q.attachShader(R[a],T[b])},f:(a,b)=>{35051==a?Q.Hc=b:35052==a&&(Q.nc=b);Q.bindBuffer(a,sb[b])},w:(a,b,c)=>{Q.bindBufferBase(a,b,sb[c])},rb:(a,b,c,d,e)=>{Q.bindBufferRange(a,b,sb[c],
d,e)},h:(a,b)=>{Q.bindFramebuffer(a,tb[b])},Db:(a,b)=>{Q.bindRenderbuffer(a,ub[b])},n:(a,b)=>{Q.bindSampler(a,U[b])},b:(a,b)=>{Q.bindTexture(a,S[b])},P:a=>{Q.bindVertexArray(vb[a])},K:(a,b,c,d)=>Q.blendColor(a,b,c,d),L:(a,b)=>Q.blendEquationSeparate(a,b),M:(a,b,c,d)=>Q.blendFuncSeparate(a,b,c,d),cb:(a,b,c,d,e,h,f,l,n,q)=>Q.blitFramebuffer(a,b,c,d,e,h,f,l,n,q),Bb:a=>Q.checkFramebufferStatus(a),xb:(a,b,c,d)=>Q.clearBufferfi(a,b,c,d),pa:(a,b,c)=>{Q.clearBufferfv(a,b,x,c>>2)},wb:(a,b,c)=>{Q.clearBufferiv(a,
b,v,c>>2)},p:(a,b,c,d)=>{Q.colorMask(!!a,!!b,!!c,!!d)},sa:a=>{Q.compileShader(T[a])},t:(a,b,c,d,e,h,f,l,n)=>{2<=W.version?Q.nc||!l?Q.compressedTexSubImage2D(a,b,c,d,e,h,f,l,n):Q.compressedTexSubImage2D(a,b,c,d,e,h,f,t,n,l):Q.compressedTexSubImage2D(a,b,c,d,e,h,f,t.subarray(n,n+l))},Ba:(a,b,c,d,e,h,f,l,n,q,u)=>{Q.nc?Q.compressedTexSubImage3D(a,b,c,d,e,h,f,l,n,q,u):Q.compressedTexSubImage3D(a,b,c,d,e,h,f,l,n,t,u,q)},ya:()=>{var a=Ab(R),b=Q.createProgram();b.name=a;b.rc=b.pc=b.qc=0;b.Dc=1;R[a]=b;return a},
ua:a=>{var b=Ab(T);T[b]=Q.createShader(a);return b},H:a=>Q.cullFace(a),Ha:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=sb[d];e&&(Q.deleteBuffer(e),e.name=0,sb[d]=null,d==Q.Hc&&(Q.Hc=0),d==Q.nc&&(Q.nc=0))}},u:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=tb[d];e&&(Q.deleteFramebuffer(e),e.name=0,tb[d]=null)}},m:a=>{if(a){var b=R[a];b?(Q.deleteProgram(b),b.name=0,R[a]=null):V||=1281}},F:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=ub[d];e&&(Q.deleteRenderbuffer(e),e.name=0,ub[d]=null)}},
G:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=U[d];e&&(Q.deleteSampler(e),e.name=0,U[d]=null)}},k:a=>{if(a){var b=T[a];b?(Q.deleteShader(b),T[a]=null):V||=1281}},i:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(Q.deleteTexture(e),e.name=0,S[d]=null)}},Ga:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];Q.deleteVertexArray(vb[d]);vb[d]=null}},y:a=>Q.depthFunc(a),x:a=>{Q.depthMask(!!a)},c:a=>Q.disable(a),N:a=>{Q.disableVertexAttribArray(a)},eb:(a,b,c)=>{Q.drawArrays(a,b,c)},fb:(a,b,c,
d)=>{Q.drawArraysInstanced(a,b,c,d)},qa:(a,b)=>{for(var c=Hb[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];Q.drawBuffers(c)},gb:(a,b,c,d)=>{Q.drawElements(a,b,c,d)},hb:(a,b,c,d,e)=>{Q.drawElementsInstanced(a,b,c,d,e)},g:a=>Q.enable(a),sb:a=>{Q.enableVertexAttribArray(a)},j:(a,b,c,d)=>{Q.framebufferRenderbuffer(a,b,c,ub[d])},d:(a,b,c,d,e)=>{Q.framebufferTexture2D(a,b,c,S[d],e)},z:(a,b,c,d,e)=>{Q.framebufferTextureLayer(a,b,S[c],d,e)},I:a=>Q.frontFace(a),O:(a,b)=>{Bb(a,b,"createFramebuffer",tb)},Eb:(a,b)=>{Bb(a,
b,"createRenderbuffer",ub)},za:(a,b)=>{Bb(a,b,"createSampler",U)},Fa:(a,b)=>{Bb(a,b,"createTexture",S)},Oa:(a,b)=>{Bb(a,b,"createVertexArray",vb)},Fb:(a,b)=>Q.getAttribLocation(R[a],b?H(b):""),a:(a,b)=>Jb(a,b),wa:(a,b,c,d)=>{a=Q.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(v[c>>2]=b)},C:(a,b,c)=>{if(c)if(a>=rb)V||=1281;else if(a=R[a],35716==b)a=Q.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.rc){var d=Q.getProgramParameter(a,
35718);for(b=0;b<d;++b)a.rc=Math.max(a.rc,Q.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.rc}else if(35722==b){if(!a.pc)for(d=Q.getProgramParameter(a,35721),b=0;b<d;++b)a.pc=Math.max(a.pc,Q.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.pc}else if(35381==b){if(!a.qc)for(d=Q.getProgramParameter(a,35382),b=0;b<d;++b)a.qc=Math.max(a.qc,Q.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.qc}else v[c>>2]=Q.getProgramParameter(a,b);else V||=1281},ra:(a,b,c,d)=>{a=Q.getShaderInfoLog(T[a]);null===a&&(a=
"(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(v[c>>2]=b)},A:(a,b,c)=>{c?35716==b?(a=Q.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(T[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=Q.getShaderParameter(T[a],b):V||=1281},Ma:(a,b)=>{if(2>W.version)return V||=1282,0;var c=xb[a];if(c)return 0>b||b>=c.length?(V||=1281,0):c[b];switch(a){case 7939:return c=Ib().map(Lb),c=xb[a]=c,0>b||b>=c.length?(V||=1281,0):c[b];default:return V||=1280,0}},B:(a,b)=>{b=b?
H(b):"";if(a=R[a]){var c=a,d=c.oc,e=c.Xc,h;if(!d){c.oc=d={};c.Wc={};var f=Q.getProgramParameter(c,35718);for(h=0;h<f;++h){var l=Q.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Mb(n);q=0<q?n.slice(0,q):n;var u=c.Dc;c.Dc+=l;e[q]=[l,u];for(n=0;n<l;++n)d[u]=n,c.Wc[u++]=q}}c=a.oc;d=0;e=b;h=Mb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Xc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||Q.getUniformLocation(a,b)))return d}else V||=1281;return-1},bb:(a,b,c)=>{for(var d=Hb[b],e=0;e<b;e++)d[e]=v[c+
4*e>>2];Q.invalidateFramebuffer(a,d)},D:a=>{a=R[a];Q.linkProgram(a);a.oc=0;a.Xc={}},Na:(a,b)=>{3317==a?yb=b:3314==a&&(zb=b);Q.pixelStorei(a,b)},J:(a,b)=>Q.polygonOffset(a,b),db:a=>Q.readBuffer(a),Cb:(a,b,c,d,e)=>Q.renderbufferStorageMultisample(a,b,c,d,e),E:(a,b,c)=>{Q.samplerParameterf(U[a],b,c)},e:(a,b,c)=>{Q.samplerParameteri(U[a],b,c)},yb:(a,b,c,d)=>Q.scissor(a,b,c,d),ta:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=w[c+4*h>>2])?H(f,d?w[d+4*h>>2]:void 0):"";e+=f}Q.shaderSource(T[a],e)},Ka:(a,
b,c)=>Q.stencilFunc(a,b,c),oa:(a,b,c,d)=>Q.stencilFuncSeparate(a,b,c,d),q:a=>Q.stencilMask(a),Ja:(a,b,c)=>Q.stencilOp(a,b,c),na:(a,b,c,d)=>Q.stencilOpSeparate(a,b,c,d),Ea:(a,b,c,d,e)=>Q.texStorage2D(a,b,c,d,e),Da:(a,b,c,d,e,h)=>Q.texStorage3D(a,b,c,d,e,h),s:(a,b,c,d,e,h,f,l,n)=>{if(2<=W.version){if(Q.nc){Q.texSubImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var q=Nb(l);Q.texSubImage2D(a,b,c,d,e,h,f,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=Nb(l);var u=h*((zb||e)*({5:3,6:4,8:2,29502:3,
29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*q.BYTES_PER_ELEMENT+yb-1&-yb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+u>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;Q.texSubImage2D(a,b,c,d,e,h,f,l,n)},Aa:(a,b,c,d,e,h,f,l,n,q,u)=>{if(Q.nc)Q.texSubImage3D(a,b,c,d,e,h,f,l,n,q,u);else if(u){var N=Nb(q);Q.texSubImage3D(a,b,c,d,e,h,f,l,n,q,N,u>>>31-Math.clz32(N.BYTES_PER_ELEMENT))}else Q.texSubImage3D(a,b,c,d,e,h,f,l,n,q,null)},qb:(a,b,c)=>{if(2<=W.version)b&&Q.uniform1fv(X(a),x,
c>>2,b);else{if(288>=b)for(var d=Y[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);Q.uniform1fv(X(a),d)}},va:(a,b)=>{Q.uniform1i(X(a),b)},mb:(a,b,c)=>{if(2<=W.version)b&&Q.uniform1iv(X(a),v,c>>2,b);else{if(288>=b)for(var d=Ob[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);Q.uniform1iv(X(a),d)}},pb:(a,b,c)=>{if(2<=W.version)b&&Q.uniform2fv(X(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Y[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>
2,c+8*b>>2);Q.uniform2fv(X(a),d)}},lb:(a,b,c)=>{if(2<=W.version)b&&Q.uniform2iv(X(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Ob[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);Q.uniform2iv(X(a),d)}},ob:(a,b,c)=>{if(2<=W.version)b&&Q.uniform3fv(X(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Y[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);Q.uniform3fv(X(a),d)}},kb:(a,b,c)=>{if(2<=W.version)b&&
Q.uniform3iv(X(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Ob[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);Q.uniform3iv(X(a),d)}},nb:(a,b,c)=>{if(2<=W.version)b&&Q.uniform4fv(X(a),x,c>>2,4*b);else{if(72>=b){var d=Y[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);Q.uniform4fv(X(a),d)}},jb:(a,b,c)=>{if(2<=W.version)b&&Q.uniform4iv(X(a),v,c>>
2,4*b);else{if(72>=b){b*=4;for(var d=Ob[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);Q.uniform4iv(X(a),d)}},ib:(a,b,c,d)=>{if(2<=W.version)b&&Q.uniformMatrix4fv(X(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=Y[16*b],h=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+
10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);Q.uniformMatrix4fv(X(a),!!c,e)}},l:a=>{a=R[a];Q.useProgram(a);Q.Zc=a},tb:(a,b)=>{Q.vertexAttribDivisor(a,b)},ub:(a,b,c,d,e)=>{Q.vertexAttribIPointer(a,b,c,d,e)},vb:(a,b,c,d,e,h)=>{Q.vertexAttribPointer(a,b,c,!!d,e,h)},zb:(a,b,c,d)=>Q.viewport(a,b,c,d),_a:Ea,Ib:function(){g.Qc=a=>{0!=Xb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Qc)},Ua:function(){g.Vc=
a=>{const b=a.clipboardData.getData("text");Tb(()=>{const c=Qb(b);Wb(c)})};window.addEventListener("paste",g.Vc)},Ra:function(){g.Dd=[];g.Rc=b=>{b.stopPropagation();b.preventDefault()};g.Sc=b=>{b.stopPropagation();b.preventDefault()};g.Tc=b=>{b.stopPropagation();b.preventDefault()};g.Uc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Ed=c;Yb(c.length);for(let e=0;e<c.length;e++)Tb(()=>{const h=Qb(c[e].name);Zb(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&
(d|=4);b.metaKey&&(d|=8);$b(b.clientX,b.clientY,d)};const a=g.lc;a.addEventListener("dragenter",g.Rc,!1);a.addEventListener("dragleave",g.Sc,!1);a.addEventListener("dragover",g.Tc,!1);a.addEventListener("drop",g.Uc,!1)},Gb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},xa:function(a){g.tc&&(URL.revokeObjectURL(g.tc[a].gd),g.tc[a]=null)},Ia:function(a,b){0!==b&&(document.title=b?H(b):"");a=a?H(a):"";void 0!==g.canvas&&("object"===typeof g.canvas?Za[a]=
g.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));g.lc=I(a);g.lc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);g.lc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Hb:function(){window.removeEventListener("beforeunload",g.Qc)},Sa:function(){window.removeEventListener("paste",g.Vc)},La:function(){const a=g.lc;a.removeEventListener("dragenter",g.Rc);a.removeEventListener("dragleave",g.Sc);a.removeEventListener("dragover",
g.Tc);a.removeEventListener("drop",g.Uc)},v:function(){g.lc&&g.lc.requestPointerLock&&g.lc.requestPointerLock()},Ca:function(a,b,c){if(g.lc){if(0===b)a="none";else if(0!=c)a=g.tc[a].jd;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a=
"auto"}g.lc.style.cursor=a}},Ab:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(t.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},ma:function(a,b){b=b?H(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};
function dc(a=[]){var b=ac;a.unshift(ea);var c=a.length,d=Pb(4*(c+1)),e=d,h;for(h of a)w[e>>2]=Qb(h),e+=4;w[e>>2]=0;try{var f=b(c,d);ma=f;Ea(f)}catch(l){Da(l)}}
function ec(a=da){function b(){g.calledRun=!0;if(!p){fc.Kb();g.onRuntimeInitialized?.();g.noInitialRun||dc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();ya.push(c)}xa(ya)}}if(0<z)A=ec;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Aa();xa(za);0<z?A=ec:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}var fc;
(async function(){function a(c){c=fc=c.exports;O=c.Lb;Wb=g.__sapp_emsc_onpaste=c.Mb;Xb=g.__sapp_html5_get_ask_leave_site=c.Nb;Yb=g.__sapp_emsc_begin_drop=c.Ob;Zb=g.__sapp_emsc_drop=c.Pb;$b=g.__sapp_emsc_end_drop=c.Qb;g.__sapp_emsc_invoke_fetch_cb=c.Rb;g.__sapp_emsc_set_fullscreen_flag=c.Sb;ac=g._main=c.Tb;g.__saudio_emsc_pull=c.Ub;g.__sfetch_emsc_head_response=c.Vb;g.__sfetch_emsc_get_response=c.Wb;g.__sfetch_emsc_failed_http_status=c.Xb;g.__sfetch_emsc_failed_buffer_too_small=c.Yb;g.__sfetch_emsc_failed_other=
c.Zb;bc=c._b;Sb=c.ac;Pb=c.bc;Rb=c.cc;oa=c.Jb;bb=c.$b;na();z--;g.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return fc}z++;g.monitorRunDependencies?.(z);var b={a:cc};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});sa??=g.locateFile?g.locateFile("framebuffer-sapp.wasm",ia):ia+"framebuffer-sapp.wasm";return a((await va(b)).instance)})();ec();
