var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",h=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,r="",fa,t,v;
if(ea){var fs=require("fs"),ha=require("path");r=l?ha.dirname(r)+"/":__dirname+"/";fa=(a,b)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};t=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,k)=>{e?c(e):b(d?k.buffer:k)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&
(module.exports=g);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof ia||a.context instanceof ia))throw a;});h=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(da||l)l?r=self.location.href:"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src),r=0!==r.indexOf("blob:")?r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&
(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),t=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ja=g.print||console.log.bind(console),w=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(h=g.quit);
var x;g.wasmBinary&&(x=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&ka("no native wasm support detected");var la,ma=!1,na,y,oa,pa,z,A,B,C;function qa(){var a=la.buffer;g.HEAP8=na=new Int8Array(a);g.HEAP16=oa=new Int16Array(a);g.HEAP32=z=new Int32Array(a);g.HEAPU8=y=new Uint8Array(a);g.HEAPU16=pa=new Uint16Array(a);g.HEAPU32=A=new Uint32Array(a);g.HEAPF32=B=new Float32Array(a);g.HEAPF64=C=new Float64Array(a)}var ra,sa=[],ta=[],ua=[],va=[],wa=[];
function xa(){var a=g.preRun.shift();sa.unshift(a)}var D=0,ya=null,E=null;function ka(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";w(a);ma=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function za(a){return a.startsWith("data:application/octet-stream;base64,")}var F;F="imgui-sapp.wasm";if(!za(F)){var Aa=F;F=g.locateFile?g.locateFile(Aa,r):r+Aa}
function Ba(a){if(a==F&&x)return new Uint8Array(x);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}function Ca(a){if(!x&&(da||l)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ba(a));if(t)return new Promise((b,c)=>{t(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ba(a))}
function Da(a,b,c){return Ca(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{w("failed to asynchronously prepare wasm: "+d);ka(d)})}
function Ea(a,b){var c=F;x||"function"!=typeof WebAssembly.instantiateStreaming||za(c)||c.startsWith("file://")||ea||"function"!=typeof fetch?Da(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){w("wasm streaming compile failed: "+e);w("falling back to ArrayBuffer instantiation");return Da(c,a,b)}))}function ia(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Fa=a=>{for(;0<a.length;)a.shift()(g)},Ga="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,G=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ga)return Ga.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var k=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|k<<6|f:(e&7)<<18|k<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=
String.fromCharCode(e)}return d},Ja=a=>{var b=Ha();a();Ia(b)},Ka=0;function La(){for(var a=H.length-1;0<=a;--a)Ma(a);H=[];Na=[]}var Na=[];function Oa(){if(navigator.userActivation?navigator.userActivation.isActive:Ka&&Pa.$b)for(var a=0;a<Na.length;++a){var b=Na[a];Na.splice(a,1);--a;b.Mc.apply(null,b.Cc)}}var H=[];function Ma(a){var b=H[a];b.target.removeEventListener(b.Tb,b.yc,b.Ub);H.splice(a,1)}
function I(a){function b(d){++Ka;Pa=a;Oa();a.Wb(d);Oa();--Ka}if(!a.target)return-4;if(a.Vb)a.yc=b,a.target.addEventListener(a.Tb,b,a.Ub),H.push(a),Qa||(va.push(La),Qa=!0);else for(var c=0;c<H.length;++c)H[c].target==a.target&&H[c].Tb==a.Tb&&Ma(c--);return 0}function Ra(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var Qa,Pa,Sa,Ta,Ua,Va,Wa,Xa,Ya,Za=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];
function J(a){a=2<a?a?G(y,a):"":a;return Za[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function $a(a){return 0>Za.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
var ab=[],K=a=>{var b=ab[a];b||(a>=ab.length&&(ab.length=a+1),ab[a]=b=ra.get(a));return b},L=(a,b,c)=>{var d=y;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);if(55296<=f&&57343>=f){var m=a.charCodeAt(++k);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=
0;return b-e};function bb(a,b,c,d,e,k){Sa||(Sa=M(256));a={target:J(a),Tb:k,Vb:d,Wb:function(f=event){var m=f.target.id?f.target.id:"",n=Sa;L(Ra(f.target),n+0,128);L(m,n+128,128);K(d)(e,n,b)&&f.preventDefault()},Ub:c};return I(a)}
function cb(a,b,c,d,e,k){Ta||(Ta=M(176));a={target:J(a),$b:!0,Tb:k,Vb:d,Wb:function(f){var m=Ta;C[m>>3]=f.timeStamp;var n=m>>2;z[n+2]=f.location;z[n+3]=f.ctrlKey;z[n+4]=f.shiftKey;z[n+5]=f.altKey;z[n+6]=f.metaKey;z[n+7]=f.repeat;z[n+8]=f.charCode;z[n+9]=f.keyCode;z[n+10]=f.which;L(f.key||"",m+44,32);L(f.code||"",m+76,32);L(f.char||"",m+108,32);L(f.locale||"",m+140,32);K(d)(e,m,b)&&f.preventDefault()},Ub:c};return I(a)}
function db(a,b,c){C[a>>3]=b.timeStamp;a>>=2;z[a+2]=b.screenX;z[a+3]=b.screenY;z[a+4]=b.clientX;z[a+5]=b.clientY;z[a+6]=b.ctrlKey;z[a+7]=b.shiftKey;z[a+8]=b.altKey;z[a+9]=b.metaKey;oa[2*a+20]=b.button;oa[2*a+21]=b.buttons;z[a+11]=b.movementX;z[a+12]=b.movementY;c=$a(c);z[a+13]=b.clientX-c.left;z[a+14]=b.clientY-c.top}
function O(a,b,c,d,e,k){Ua||(Ua=M(72));a=J(a);return I({target:a,$b:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Tb:k,Vb:d,Wb:function(f=event){db(Ua,f,a);K(d)(e,Ua,b)&&f.preventDefault()},Ub:c})}function eb(a,b,c,d,e){Va||(Va=M(260));return I({target:a,Tb:e,Vb:d,Wb:function(k=event){var f=Va,m=document.pointerLockElement||document.Yb||document.ic||document.hc;z[f>>2]=!!m;var n=m&&m.id?m.id:"";L(Ra(m),f+4,128);L(n,f+132,128);K(d)(20,f,b)&&k.preventDefault()},Ub:c})}
function fb(a,b,c,d,e){return I({target:a,Tb:e,Vb:d,Wb:function(k=event){K(d)(38,0,b)&&k.preventDefault()},Ub:c})}
function gb(a,b,c,d){Wa||(Wa=M(36));a=J(a);return I({target:a,Tb:"resize",Vb:d,Wb:function(e=event){if(e.target==a){var k=document.body;if(k){var f=Wa;z[f>>2]=e.detail;z[f+4>>2]=k.clientWidth;z[f+8>>2]=k.clientHeight;z[f+12>>2]=innerWidth;z[f+16>>2]=innerHeight;z[f+20>>2]=outerWidth;z[f+24>>2]=outerHeight;z[f+28>>2]=pageXOffset;z[f+32>>2]=pageYOffset;K(d)(10,f,b)&&e.preventDefault()}}},Ub:c})}
function hb(a,b,c,d,e,k){Xa||(Xa=M(1696));a=J(a);return I({target:a,$b:"touchstart"==k||"touchend"==k,Tb:k,Vb:d,Wb:function(f){for(var m,n={},p=f.touches,q=0;q<p.length;++q)m=p[q],m.mc=m.oc=0,n[m.identifier]=m;for(q=0;q<f.changedTouches.length;++q)m=f.changedTouches[q],m.mc=1,n[m.identifier]=m;for(q=0;q<f.targetTouches.length;++q)n[f.targetTouches[q].identifier].oc=1;p=Xa;C[p>>3]=f.timeStamp;var u=p>>2;z[u+3]=f.ctrlKey;z[u+4]=f.shiftKey;z[u+5]=f.altKey;z[u+6]=f.metaKey;u+=7;var N=$a(a),V=0;for(q in n)if(m=
n[q],z[u]=m.identifier,z[u+1]=m.screenX,z[u+2]=m.screenY,z[u+3]=m.clientX,z[u+4]=m.clientY,z[u+5]=m.pageX,z[u+6]=m.pageY,z[u+7]=m.mc,z[u+8]=m.oc,z[u+9]=m.clientX-N.left,z[u+10]=m.clientY-N.top,u+=13,31<++V)break;z[p+8>>2]=V;K(d)(e,p,b)&&f.preventDefault()},Ub:c})}
function ib(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,k){b.drawArraysInstancedANGLE(c,d,e,k)},a.drawElementsInstanced=function(c,d,e,k,f){b.drawElementsInstancedANGLE(c,d,e,k,f)})}
function jb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function kb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function lb(a){a.Ec=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function mb(a){a.Fc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function nb(a){a.Hc=a.getExtension("WEBGL_multi_draw")}var ob=1,pb=[],P=[],qb=[],rb=[],sb=[],Q=[],tb=[],ub=[],R=[],vb={},wb=4;function S(a){xb||(xb=a)}function yb(a){for(var b=ob++,c=a.length;c<b;c++)a[c]=null;return b}
function zb(a,b){a.Yb||(a.Yb=a.getContext,a.getContext=function(d,e){e=a.Yb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.nc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Ab(c,b):0}function Ab(a,b){var c=yb(ub),d={handle:c,attributes:b,version:b.nc,ec:a};a.canvas&&(a.canvas.Bc=d);ub[c]=d;("undefined"==typeof b.lc||b.lc)&&Bb(d);return c}
function Bb(a){a||(a=T);if(!a.Ac){a.Ac=!0;var b=a.ec;ib(b);jb(b);kb(b);lb(b);mb(b);2<=a.version&&(b.kc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.kc)b.kc=b.getExtension("EXT_disjoint_timer_query");nb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var xb,T;function Cb(a,b,c,d,e,k){a={target:J(a),Tb:k,Vb:d,Wb:(f=event)=>{K(d)(e,0,b)&&f.preventDefault()},Ub:c};I(a)}
function Db(a,b,c,d){Ya||(Ya=M(104));return I({target:a,$b:!0,Tb:"wheel",Vb:d,Wb:function(e=event){var k=Ya;db(k,e,a);C[k+72>>3]=e.deltaX;C[k+80>>3]=e.deltaY;C[k+88>>3]=e.deltaZ;z[k+96>>2]=e.deltaMode;K(d)(9,k,b)&&e.preventDefault()},Ub:c})}var Eb=["default","low-power","high-performance"],Fb=[null,[],[]];function Gb(a,b,c,d){for(var e=0;e<a;e++){var k=U[c](),f=k&&yb(d);k?(k.name=f,d[f]=k):S(1282);z[b+4*e>>2]=f}}
function Hb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=U.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>T.version){S(1282);return}c=2*(U.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>T.version){S(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=U.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":S(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:S(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)z[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){S(1280);w("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:S(1280);w("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}z[b>>2]=c}else S(1281)}
var Ib=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b};function Jb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}var Kb=[];function Lb(a){a-=5120;return 0==a?na:1==a?y:2==a?oa:4==a?z:6==a?B:5==a||28922==a||28520==a||30779==a||30782==a?A:pa}function W(a){var b=U.xc;if(b){var c=b.Zb[a];"number"==typeof c&&(b.Zb[a]=c=U.getUniformLocation(b,b.vc[a]+(0<c?"["+c+"]":"")));return c}S(1282)}
for(var X=[],Y=[],Mb=a=>{if(!noExitRuntime){if(g.onExit)g.onExit(a);ma=!0}h(a,new ia(a))},Ob=a=>{var b=Ib(a)+1,c=Nb(b);L(a,c,b);return c},U,Z=0;32>Z;++Z)Kb.push(Array(Z));var Pb=new Float32Array(288);for(Z=0;288>Z;++Z)X[Z]=Pb.subarray(0,Z+1);var Qb=new Int32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Qb.subarray(0,Z+1);
var Xb={ka:function(){return 0},cb:function(){return 0},eb:function(){},i:()=>{ka("")},ga:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},ha:function(a,b,c){a=J(a);if(!a)return-4;a=$a(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},$a:(a,b,c)=>y.copyWithin(a,b,b+c),Va:function(a,b){function c(d){K(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},_a:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);
var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,d+(65536-d%65536)%65536)-la.buffer.byteLength+65535>>>16;try{la.grow(e);qa();var k=1;break a}catch(f){}k=void 0}if(k)return!0}return!1},Q:function(a,b,c,d){return bb(a,b,c,d,12,"blur")},fa:function(a,b,c){a=J(a);if(!a)return-4;a.width=b;a.height=c;return 0},R:function(a,b,c,d){return bb(a,b,c,d,13,"focus")},_:function(a,b,c,d){return cb(a,b,c,d,2,"keydown")},Y:function(a,b,c,d){return cb(a,b,c,d,1,"keypress")},Z:function(a,b,c,d){return cb(a,
b,c,d,3,"keyup")},ea:function(a,b,c,d){return O(a,b,c,d,5,"mousedown")},ba:function(a,b,c,d){return O(a,b,c,d,33,"mouseenter")},aa:function(a,b,c,d){return O(a,b,c,d,34,"mouseleave")},ca:function(a,b,c,d){return O(a,b,c,d,8,"mousemove")},da:function(a,b,c,d){return O(a,b,c,d,6,"mouseup")},T:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Yb||document.body.ic||document.body.hc))return-1;a=J(a);if(!a)return-4;eb(a,b,c,d,"mozpointerlockchange");eb(a,
b,c,d,"webkitpointerlockchange");eb(a,b,c,d,"mspointerlockchange");return eb(a,b,c,d,"pointerlockchange")},S:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Yb||document.body.ic||document.body.hc))return-1;a=J(a);if(!a)return-4;fb(a,b,c,d,"mozpointerlockerror");fb(a,b,c,d,"webkitpointerlockerror");fb(a,b,c,d,"mspointerlockerror");return fb(a,b,c,d,"pointerlockerror")},Wa:function(a,b,c,d){return gb(a,b,c,d)},U:function(a,b,c,d){return hb(a,b,c,d,25,"touchcancel")},
V:function(a,b,c,d){return hb(a,b,c,d,23,"touchend")},W:function(a,b,c,d){return hb(a,b,c,d,24,"touchmove")},X:function(a,b,c,d){return hb(a,b,c,d,22,"touchstart")},P:function(a,b,c,d){Cb(a,b,c,d,31,"webglcontextlost");return 0},O:function(a,b,c,d){Cb(a,b,c,d,32,"webglcontextrestored");return 0},$:function(a,b,c,d){return(a=J(a))?"undefined"!=typeof a.onwheel?Db(a,b,c,d):-1:-4},Ta:function(a,b){b>>=2;b={alpha:!!z[b],depth:!!z[b+1],stencil:!!z[b+2],antialias:!!z[b+3],premultipliedAlpha:!!z[b+4],preserveDrawingBuffer:!!z[b+
5],powerPreference:Eb[z[b+6]],failIfMajorPerformanceCaveat:!!z[b+7],nc:z[b+8],Gc:z[b+9],lc:z[b+10],zc:z[b+11],Ic:z[b+12],Jc:z[b+13]};a=J(a);return!a||b.zc?0:zb(a,b)},Ra:function(a,b){a=ub[a];b=b?G(y,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&ib(U);"OES_vertex_array_object"==b&&jb(U);"WEBGL_draw_buffers"==b&&kb(U);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&lb(U);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&mb(U);"WEBGL_multi_draw"==b&&nb(U);return!!a.ec.getExtension(b)},
Ua:function(a){a>>=2;for(var b=0;14>b;++b)z[a+b]=0;z[a]=z[a+1]=z[a+3]=z[a+4]=z[a+8]=z[a+10]=1},Sa:function(a){T=ub[a];g.Dc=U=T&&T.ec;return!a||U?0:-5},ja:()=>52,bb:()=>52,Za:function(){return 70},ab:(a,b,c,d)=>{for(var e=0,k=0;k<c;k++){var f=A[b>>2],m=A[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=y[f+n],q=Fb[a];0===p||10===p?((1===a?ja:w)(G(q,0)),q.length=0):q.push(p)}e+=m}A[d>>2]=e;return 0},f:function(a){U.activeTexture(a)},D:function(a,b){U.attachShader(P[a],Q[b])},b:function(a,b){35051==a?U.jc=b:
35052==a&&(U.ac=b);U.bindBuffer(a,pb[b])},j:function(a,b){U.bindFramebuffer(a,qb[b])},g:function(a,b){U.bindSampler(a,R[b])},a:function(a,b){U.bindTexture(a,sb[b])},M:function(a){U.bindVertexArray(tb[a])},I:function(a,b,c,d){U.blendColor(a,b,c,d)},J:function(a,b){U.blendEquationSeparate(a,b)},K:function(a,b,c,d){U.blendFuncSeparate(a,b,c,d)},gb:function(a,b,c,d,e,k,f,m,n,p){U.blitFramebuffer(a,b,c,d,e,k,f,m,n,p)},Ca:function(a,b,c,d){2<=T.version?c&&b?U.bufferData(a,y,d,c,b):U.bufferData(a,b,d):U.bufferData(a,
c?y.subarray(c,c+b):b,d)},o:function(a,b,c,d){2<=T.version?c&&U.bufferSubData(a,b,y,d,c):U.bufferSubData(a,b,y.subarray(d,d+c))},Ab:function(a,b,c,d){U.clearBufferfi(a,b,c,d)},na:function(a,b,c){U.clearBufferfv(a,b,B,c>>2)},zb:function(a,b,c){U.clearBufferiv(a,b,z,c>>2)},k:function(a,b,c,d){U.colorMask(!!a,!!b,!!c,!!d)},qa:function(a){U.compileShader(Q[a])},wa:function(){var a=yb(P),b=U.createProgram();b.name=a;b.dc=b.bc=b.cc=0;b.fc=1;P[a]=b;return a},sa:function(a){var b=yb(Q);Q[b]=U.createShader(a);
return b},F:function(a){U.cullFace(a)},Oa:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=pb[d];e&&(U.deleteBuffer(e),e.name=0,pb[d]=null,d==U.jc&&(U.jc=0),d==U.ac&&(U.ac=0))}},l:function(a,b){for(var c=0;c<a;++c){var d=z[b+4*c>>2],e=qb[d];e&&(U.deleteFramebuffer(e),e.name=0,qb[d]=null)}},y:function(a){if(a){var b=P[a];b?(U.deleteProgram(b),b.name=0,P[a]=null):S(1281)}},La:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=rb[d];e&&(U.deleteRenderbuffer(e),e.name=0,rb[d]=null)}},N:function(a,
b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=R[d];e&&(U.deleteSampler(e),e.name=0,R[d]=null)}},u:function(a){if(a){var b=Q[a];b?(U.deleteShader(b),Q[a]=null):S(1281)}},Ma:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=sb[d];e&&(U.deleteTexture(e),e.name=0,sb[d]=null)}},Ka:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2];U.deleteVertexArray(tb[d]);tb[d]=null}},x:function(a){U.depthFunc(a)},w:function(a){U.depthMask(!!a)},d:function(a){U.disable(a)},L:function(a){U.disableVertexAttribArray(a)},
ib:function(a,b,c){U.drawArrays(a,b,c)},jb:function(a,b,c,d){U.drawArraysInstanced(a,b,c,d)},kb:function(a,b,c,d){U.drawElements(a,b,c,d)},lb:function(a,b,c,d,e){U.drawElementsInstanced(a,b,c,d,e)},h:function(a){U.enable(a)},vb:function(a){U.enableVertexAttribArray(a)},G:function(a){U.frontFace(a)},Da:function(a,b){Gb(a,b,"createBuffer",pb)},xa:function(a,b){Gb(a,b,"createSampler",R)},Aa:function(a,b){Gb(a,b,"createTexture",sb)},Ia:function(a,b){Gb(a,b,"createVertexArray",tb)},Bb:function(a,b){return U.getAttribLocation(P[a],
b?G(y,b):"")},c:function(a,b){Hb(a,b)},ta:function(a,b,c,d){a=U.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(z[c>>2]=b)},C:function(a,b,c){if(c)if(a>=ob)S(1281);else if(a=P[a],35716==b)a=U.getProgramInfoLog(a),null===a&&(a="(unknown error)"),z[c>>2]=a.length+1;else if(35719==b){if(!a.dc)for(b=0;b<U.getProgramParameter(a,35718);++b)a.dc=Math.max(a.dc,U.getActiveUniform(a,b).name.length+1);z[c>>2]=a.dc}else if(35722==b){if(!a.bc)for(b=0;b<U.getProgramParameter(a,35721);++b)a.bc=
Math.max(a.bc,U.getActiveAttrib(a,b).name.length+1);z[c>>2]=a.bc}else if(35381==b){if(!a.cc)for(b=0;b<U.getProgramParameter(a,35382);++b)a.cc=Math.max(a.cc,U.getActiveUniformBlockName(a,b).length+1);z[c>>2]=a.cc}else z[c>>2]=U.getProgramParameter(a,b);else S(1281)},pa:function(a,b,c,d){a=U.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(z[c>>2]=b)},A:function(a,b,c){c?35716==b?(a=U.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),z[c>>2]=a?a.length+1:0):35720==
b?(a=U.getShaderSource(Q[a]),z[c>>2]=a?a.length+1:0):z[c>>2]=U.getShaderParameter(Q[a],b):S(1281)},Pa:function(a,b){if(2>T.version)return S(1282),0;var c=vb[a];if(c)return 0>b||b>=c.length?(S(1281),0):c[b];switch(a){case 7939:return c=U.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){var e=Ib(d)+1,k=M(e);k&&L(d,k,e);return k}),c=vb[a]=c,0>b||b>=c.length?(S(1281),0):c[b];default:return S(1280),0}},n:function(a,b){b=b?G(y,b):"";if(a=P[a]){var c=a,d=c.Zb,
e=c.wc,k;if(!d)for(c.Zb=d={},c.vc={},k=0;k<U.getProgramParameter(c,35718);++k){var f=U.getActiveUniform(c,k);var m=f.name;f=f.size;var n=Jb(m);n=0<n?m.slice(0,n):m;var p=c.fc;c.fc+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.vc[p++]=n}c=a.Zb;d=0;e=b;k=Jb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.wc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||U.getUniformLocation(a,b)))return d}else S(1281);return-1},fb:function(a,b,c){for(var d=Kb[b],e=0;e<b;e++)d[e]=z[c+4*e>>2];U.invalidateFramebuffer(a,d)},va:function(a){a=
P[a];U.linkProgram(a);a.Zb=0;a.wc={}},Ha:function(a,b){3317==a&&(wb=b);U.pixelStorei(a,b)},H:function(a,b){U.polygonOffset(a,b)},hb:function(a){U.readBuffer(a)},E:function(a,b,c){U.samplerParameterf(R[a],b,c)},e:function(a,b,c){U.samplerParameteri(R[a],b,c)},r:function(a,b,c,d){U.scissor(a,b,c,d)},ra:function(a,b,c,d){for(var e="",k=0;k<b;++k){var f=d?z[d+4*k>>2]:-1,m=z[c+4*k>>2];f=m?G(y,m,0>f?void 0:f):"";e+=f}U.shaderSource(Q[a],e)},Ga:function(a,b,c){U.stencilFunc(a,b,c)},ma:function(a,b,c,d){U.stencilFuncSeparate(a,
b,c,d)},v:function(a){U.stencilMask(a)},Fa:function(a,b,c){U.stencilOp(a,b,c)},la:function(a,b,c,d){U.stencilOpSeparate(a,b,c,d)},za:function(a,b,c,d,e,k,f,m,n){if(2<=T.version)if(U.ac)U.texImage2D(a,b,c,d,e,k,f,m,n);else if(n){var p=Lb(m);U.texImage2D(a,b,c,d,e,k,f,m,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else U.texImage2D(a,b,c,d,e,k,f,m,null);else{p=U;var q=p.texImage2D;if(n){var u=Lb(m),N=31-Math.clz32(u.BYTES_PER_ELEMENT),V=wb;n=u.subarray(n>>N,n+e*(d*({5:3,6:4,8:2,29502:3,29504:4,26917:2,
26918:2,29846:3,29847:4}[f-6402]||1)*(1<<N)+V-1&-V)>>N)}else n=null;q.call(p,a,b,c,d,e,k,f,m,n)}},ya:function(a,b,c,d,e,k,f,m,n,p){if(U.ac)U.texImage3D(a,b,c,d,e,k,f,m,n,p);else if(p){var q=Lb(n);U.texImage3D(a,b,c,d,e,k,f,m,n,q,p>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else U.texImage3D(a,b,c,d,e,k,f,m,n,null)},ub:function(a,b,c){if(2<=T.version)b&&U.uniform1fv(W(a),B,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);U.uniform1fv(W(a),d)}},B:function(a,
b){U.uniform1i(W(a),b)},qb:function(a,b,c){if(2<=T.version)b&&U.uniform1iv(W(a),z,c>>2,b);else{if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);U.uniform1iv(W(a),d)}},tb:function(a,b,c){if(2<=T.version)b&&U.uniform2fv(W(a),B,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);U.uniform2fv(W(a),d)}},pb:function(a,b,c){if(2<=T.version)b&&U.uniform2iv(W(a),z,c>>2,2*b);else{if(144>=
b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);U.uniform2iv(W(a),d)}},sb:function(a,b,c){if(2<=T.version)b&&U.uniform3fv(W(a),B,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);U.uniform3fv(W(a),d)}},ob:function(a,b,c){if(2<=T.version)b&&U.uniform3iv(W(a),z,c>>2,3*b);else{if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],
d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);U.uniform3iv(W(a),d)}},rb:function(a,b,c){if(2<=T.version)b&&U.uniform4fv(W(a),B,c>>2,4*b);else{if(72>=b){var d=X[4*b-1],e=B;c>>=2;for(var k=0;k<4*b;k+=4){var f=c+k;d[k]=e[f];d[k+1]=e[f+1];d[k+2]=e[f+2];d[k+3]=e[f+3]}}else d=B.subarray(c>>2,c+16*b>>2);U.uniform4fv(W(a),d)}},nb:function(a,b,c){if(2<=T.version)b&&U.uniform4iv(W(a),z,c>>2,4*b);else{if(72>=b)for(var d=Y[4*b-1],e=0;e<4*b;e+=4)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*
e+4)>>2],d[e+2]=z[c+(4*e+8)>>2],d[e+3]=z[c+(4*e+12)>>2];else d=z.subarray(c>>2,c+16*b>>2);U.uniform4iv(W(a),d)}},mb:function(a,b,c,d){if(2<=T.version)b&&U.uniformMatrix4fv(W(a),!!c,B,d>>2,16*b);else{if(18>=b){var e=X[16*b-1],k=B;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=k[m];e[f+1]=k[m+1];e[f+2]=k[m+2];e[f+3]=k[m+3];e[f+4]=k[m+4];e[f+5]=k[m+5];e[f+6]=k[m+6];e[f+7]=k[m+7];e[f+8]=k[m+8];e[f+9]=k[m+9];e[f+10]=k[m+10];e[f+11]=k[m+11];e[f+12]=k[m+12];e[f+13]=k[m+13];e[f+14]=k[m+14];e[f+15]=k[m+15]}}else e=
B.subarray(d>>2,d+64*b>>2);U.uniformMatrix4fv(W(a),!!c,e)}},m:function(a){a=P[a];U.useProgram(a);U.xc=a},wb:function(a,b){U.vertexAttribDivisor(a,b)},yb:function(a,b,c,d,e,k){U.vertexAttribPointer(a,b,c,!!d,e,k)},s:function(a,b,c,d){U.viewport(a,b,c,d)},Qa:function(){g.pc=a=>{0!=Rb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.pc)},Ja:function(){g.uc=a=>{const b=a.clipboardData.getData("text");Ja(()=>{const c=Ob(b);Sb(c)})};window.addEventListener("paste",g.uc)},
ua:function(a){g.Kc=[];a=a?G(y,a):"";a=document.getElementById(a);g.qc=b=>{b.stopPropagation();b.preventDefault()};g.rc=b=>{b.stopPropagation();b.preventDefault()};g.sc=b=>{b.stopPropagation();b.preventDefault()};g.tc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Lc=c;Tb(c.length);for(let e=0;e<c.length;e++)Ja(()=>{const k=Ob(c[e].name);Ub(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Vb(b.clientX,b.clientY,d)};a.addEventListener("dragenter",
g.qc,!1);a.addEventListener("dragleave",g.rc,!1);a.addEventListener("dragover",g.sc,!1);a.addEventListener("drop",g.tc,!1)},Ya:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},t:function(){const a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Wb()});document.body.append(a)},q:function(){document.getElementById("_sokol_app_input_element").focus()},xb:function(a){a=
a?G(y,a):"";g.Xb=document.getElementById(a);g.Xb||console.log("sokol_app.h: invalid target:"+a);g.Xb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Na:function(){window.removeEventListener("beforeunload",g.pc)},Ea:function(){window.removeEventListener("paste",g.uc)},Cb:function(a){a=a?G(y,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.qc);a.removeEventListener("dragleave",g.rc);a.removeEventListener("dragover",g.sc);a.removeEventListener("drop",
g.tc)},z:function(){g.Xb&&g.Xb.requestPointerLock&&g.Xb.requestPointerLock()},db:function(a,b){if(g.Xb){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.Xb.style.cursor=a}},Xa:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(y.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},p:function(){document.getElementById("_sokol_app_input_element").blur()},Ba:function(a){a=a?G(y,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize",
"off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},oa:function(){return navigator.userAgent.includes("Macintosh")?1:0},ia:function(a,b){b=b?G(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};
(function(){function a(c){c=c.exports;g.asm=c;la=g.asm.Db;qa();ra=g.asm.Pb;ta.unshift(g.asm.Eb);D--;g.monitorRunDependencies&&g.monitorRunDependencies(D);if(0==D&&(null!==ya&&(clearInterval(ya),ya=null),E)){var d=E;E=null;d()}return c}var b={a:Xb};D++;g.monitorRunDependencies&&g.monitorRunDependencies(D);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return w("Module.instantiateWasm callback failed with error: "+c),!1}Ea(b,function(c){a(c.instance)});return{}})();
function M(){return(M=g.asm.Fb).apply(null,arguments)}
var Wb=g.__sapp_emsc_notify_keyboard_hidden=function(){return(Wb=g.__sapp_emsc_notify_keyboard_hidden=g.asm.Gb).apply(null,arguments)},Sb=g.__sapp_emsc_onpaste=function(){return(Sb=g.__sapp_emsc_onpaste=g.asm.Hb).apply(null,arguments)},Rb=g.__sapp_html5_get_ask_leave_site=function(){return(Rb=g.__sapp_html5_get_ask_leave_site=g.asm.Ib).apply(null,arguments)},Tb=g.__sapp_emsc_begin_drop=function(){return(Tb=g.__sapp_emsc_begin_drop=g.asm.Jb).apply(null,arguments)},Ub=g.__sapp_emsc_drop=function(){return(Ub=
g.__sapp_emsc_drop=g.asm.Kb).apply(null,arguments)},Vb=g.__sapp_emsc_end_drop=function(){return(Vb=g.__sapp_emsc_end_drop=g.asm.Lb).apply(null,arguments)};g.__sapp_emsc_invoke_fetch_cb=function(){return(g.__sapp_emsc_invoke_fetch_cb=g.asm.Mb).apply(null,arguments)};var Yb=g._main=function(){return(Yb=g._main=g.asm.Nb).apply(null,arguments)};g.__saudio_emsc_pull=function(){return(g.__saudio_emsc_pull=g.asm.Ob).apply(null,arguments)};function Ha(){return(Ha=g.asm.Qb).apply(null,arguments)}
function Ia(){return(Ia=g.asm.Rb).apply(null,arguments)}function Nb(){return(Nb=g.asm.Sb).apply(null,arguments)}g.___start_em_js=117220;g.___stop_em_js=125545;var Zb;E=function $b(){Zb||ac();Zb||(E=$b)};function bc(a=[]){var b=Yb;a.unshift(ca);var c=a.length,d=Nb(4*(c+1)),e=d>>2;a.forEach(f=>{z[e++]=Ob(f)});z[e]=0;try{var k=b(c,d);Mb(k)}catch(f){f instanceof ia||"unwind"==f||h(1,f)}}
function ac(){var a=ba;function b(){if(!Zb&&(Zb=!0,g.calledRun=!0,!ma)){Fa(ta);Fa(ua);if(g.onRuntimeInitialized)g.onRuntimeInitialized();cc&&bc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();wa.unshift(c)}Fa(wa)}}if(!(0<D)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)xa();Fa(sa);0<D||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var cc=!0;g.noInitialRun&&(cc=!1);ac();
