var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,da=Object.assign({},g),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},h="",ia,ja;
if(ca){var fs=require("fs"),ka=require("path");h=__dirname+"/";ja=a=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a)};ia=a=>{a=la(a)?new URL(a):ka.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!g.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?h=self.location.href:"undefined"!=typeof document&&
document.currentScript&&(h=document.currentScript.src),h=h.startsWith("blob:")?"":h.substr(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=a=>la(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));g.print||console.log.bind(console);var m=g.printErr||console.error.bind(console);Object.assign(g,da);da=null;g.arguments&&(ea=g.arguments);g.thisProgram&&(fa=g.thisProgram);var ma=g.wasmBinary,na,q=!1,r,t,u,oa,pa,v,w,x,y;
function qa(){var a=na.buffer;g.HEAP8=t=new Int8Array(a);g.HEAP16=oa=new Int16Array(a);g.HEAPU8=u=new Uint8Array(a);g.HEAPU16=pa=new Uint16Array(a);g.HEAP32=v=new Int32Array(a);g.HEAPU32=w=new Uint32Array(a);g.HEAPF32=x=new Float32Array(a);g.HEAPF64=y=new Float64Array(a)}var ra=[],sa=[],ta=[],ua=[];function va(){var a=g.preRun.shift();ra.unshift(a)}var z=0,wa=null,A=null;
function xa(a){g.onAbort?.(a);a="Aborted("+a+")";m(a);q=!0;r=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var za=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),Aa;function Ba(a){if(a==Aa&&ma)return new Uint8Array(ma);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}function Ca(a){return ma?Promise.resolve().then(()=>Ba(a)):ia(a).then(b=>new Uint8Array(b),()=>Ba(a))}
function Da(a,b,c){return Ca(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{m(`failed to asynchronously prepare wasm: ${d}`);xa(d)})}function Ea(a,b){var c=Aa;ma||"function"!=typeof WebAssembly.instantiateStreaming||za(c)||la(c)||ca||"function"!=typeof fetch?Da(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){m(`wasm streaming compile failed: ${e}`);m("falling back to ArrayBuffer instantiation");return Da(c,a,b)}))}
function Fa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Ga=a=>{for(;0<a.length;)a.shift()(g)},Ha=g.noExitRuntime||!0,B={},Ia=a=>{a instanceof Fa||"unwind"==a||ha(1,a)},Ja=0,Ka=a=>{r=a;Ha||0<Ja||(g.onExit?.(a),q=!0);ha(a,new Fa(a))},La=a=>{r=a;Ka(a)},Ma=a=>{if(!q)try{if(a(),!(Ha||0<Ja))try{r=a=r,Ka(a)}catch(b){Ia(b)}}catch(b){Ia(b)}},Na;Na=()=>performance.now();
var Ua=(a,b)=>{Oa=a;Pa=b;if(C)if(Qa||=!0,0==a)F=function(){var d=Math.max(0,Ra+b-Na())|0;setTimeout(G,d)};else if(1==a)F=function(){Sa(G)};else if(2==a){if("undefined"==typeof Ta)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ta=function(d){c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate",
"*")}}else Ta=setImmediate;F=function(){Ta(G)}}},$a=(a,b,c,d,e)=>{C=a;Va=d;var k=H;Qa=!1;G=function(){if(!q)if(0<Wa.length){var f=Wa.shift();f.Lc(f.Gc);if(Xa){var l=Xa,n=0==l%1?l-1:Math.floor(l);Xa=f.Ic?n:(8*l+(n+.5))/9}g.setStatus&&(f=g.statusMessage||"Please wait...",l=Xa,n=Ya.Kc,l?l<n?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(f):g.setStatus(""));k<H||setTimeout(G,0)}else k<H||(Za=Za+1|0,1==Oa&&1<Pa&&0!=Za%Pa?F():(0==Oa&&(Ra=Na()),q||g.preMainLoop&&!1===g.preMainLoop()||
(Ma(a),g.postMainLoop?.()),k<H||("object"==typeof SDL&&SDL.audio?.Pc?.(),F())))};e||(b&&0<b?Ua(0,1E3/b):Ua(1,1),F());if(c)throw"unwind";},Qa=!1,F=null,H=0,C=null,Va=0,Oa=0,Pa=0,Za=0,Wa=[];function ab(){F=null;H++}var Ya={},Ra,G,Xa,bb=!1,cb=!1,db=[];
function eb(){function a(){cb=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}if(!fb){fb=!0;var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!cb&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}var gb=!1,hb=void 0,I=void 0;
function ib(){if(!bb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var jb=0;function Sa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===jb)jb=b+1E3/60;else for(;b+2>=jb;)jb+=1E3/60;setTimeout(a,Math.max(jb-b,0))}}var kb=[];function lb(){var a=g.canvas;kb.forEach(b=>b(a.width,a.height))}
function mb(a,b,c){b&&c?(a.Ec=b,a.Bc=c):(b=a.Ec,c=a.Bc);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var k=Math.min(screen.width/d,screen.height/e);d=Math.round(d*k);e=Math.round(e*
k)}I?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Ta,fb,nb=0,ob=[];
function pb(){if(navigator.userActivation?navigator.userActivation.isActive:nb&&qb.ec){var a=ob;ob=[];for(var b of a)b.Tc(...b.Hc)}}var J=[];function rb(a){var b=J[a];b.target.removeEventListener(b.Tb,b.oc,b.Ub);J.splice(a,1)}function K(a){if(!a.target)return-4;if(a.Vb)a.oc=function(c){++nb;qb=a;pb();a.Wb(c);pb();--nb},a.target.addEventListener(a.Tb,a.oc,a.Ub),J.push(a);else for(var b=0;b<J.length;++b)J[b].target==a.target&&J[b].Tb==a.Tb&&rb(b--);return 0}
function sb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var qb,tb,ub,vb,wb,xb,yb,zb,Ab="undefined"!=typeof TextDecoder?new TextDecoder:void 0,L=(a,b)=>{var c=u,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&Ab)return Ab.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var k=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|k<<6|f:(e&7)<<18|k<<12|f<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],M=a=>{a=2<a?a?L(a):"":a;return Bb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Cb=a=>0>Bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Db=[],Eb,N=a=>{var b=Db[a];b||(a>=Db.length&&(Db.length=a+1),Db[a]=b=Eb.get(a));return b},O=(a,b,c)=>{var d=u;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);if(55296<=f&&57343>=f){var l=a.charCodeAt(++k);f=65536+((f&
1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},Fb=(a,b,c,d,e,k)=>{tb||=P(256);a={target:M(a),Tb:k,Vb:d,Wb:(f=event)=>{var l=f.target.id?f.target.id:"",n=tb;O(sb(f.target),n+0,128);O(l,n+128,128);N(d)(e,n,b)&&f.preventDefault()},Ub:c};return K(a)},Gb=(a,b,c,d,e,k)=>{ub||=P(160);a={target:M(a),
Tb:k,Vb:d,Wb:f=>{var l=ub;y[l>>3]=f.timeStamp;var n=l>>2;v[n+2]=f.location;t[l+12]=f.ctrlKey;t[l+13]=f.shiftKey;t[l+14]=f.altKey;t[l+15]=f.metaKey;t[l+16]=f.repeat;v[n+5]=f.charCode;v[n+6]=f.keyCode;v[n+7]=f.which;O(f.key||"",l+32,32);O(f.code||"",l+64,32);O(f.char||"",l+96,32);O(f.locale||"",l+128,32);N(d)(e,l,b)&&f.preventDefault()},Ub:c};return K(a)},Hb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;t[a+24]=b.ctrlKey;t[a+25]=b.shiftKey;
t[a+26]=b.altKey;t[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=Cb(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},Ib=(a,b,c,d,e,k)=>{vb||=P(64);a=M(a);return K({target:a,ec:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Tb:k,Vb:d,Wb:(f=event)=>{Hb(vb,f,a);N(d)(e,vb,b)&&f.preventDefault()},Ub:c})},Jb=(a,b,c,d,e)=>{wb||=P(257);return K({target:a,Tb:e,Vb:d,Wb:(k=event)=>{var f=wb,l=document.pointerLockElement||document.Xb||document.kc||
document.jc;t[f]=!!l;var n=l?.id||"";O(sb(l),f+1,128);O(n,f+129,128);N(d)(20,f,b)&&k.preventDefault()},Ub:c})},Kb=(a,b,c,d,e)=>K({target:a,Tb:e,Vb:d,Wb:(k=event)=>{N(d)(38,0,b)&&k.preventDefault()},Ub:c}),Lb=(a,b,c,d)=>{xb||=P(36);a=M(a);return K({target:a,Tb:"resize",Vb:d,Wb:(e=event)=>{if(e.target==a){var k=document.body;if(k){var f=xb;v[f>>2]=0;v[f+4>>2]=k.clientWidth;v[f+8>>2]=k.clientHeight;v[f+12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+20>>2]=outerWidth;v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|
0;v[f+32>>2]=pageYOffset|0;N(d)(10,f,b)&&e.preventDefault()}}},Ub:c})},Mb=(a,b,c,d,e,k)=>{yb||=P(1552);a=M(a);return K({target:a,ec:"touchstart"==k||"touchend"==k,Tb:k,Vb:d,Wb:f=>{var l={},n=f.touches;for(var p of n)p.pc=p.qc=0,l[p.identifier]=p;for(var D of f.changedTouches)D.pc=1,l[D.identifier]=D;for(var ya of f.targetTouches)l[ya.identifier].qc=1;n=yb;y[n>>3]=f.timeStamp;t[n+12]=f.ctrlKey;t[n+13]=f.shiftKey;t[n+14]=f.altKey;t[n+15]=f.metaKey;p=n+16;D=Cb(a);ya=0;for(let E of Object.values(l))if(l=
p>>2,v[l]=E.identifier,v[l+1]=E.screenX,v[l+2]=E.screenY,v[l+3]=E.clientX,v[l+4]=E.clientY,v[l+5]=E.pageX,v[l+6]=E.pageY,t[p+28]=E.pc,t[p+29]=E.qc,v[l+8]=E.clientX-(D.left|0),v[l+9]=E.clientY-(D.top|0),p+=48,31<++ya)break;v[n+8>>2]=ya;N(d)(e,n,b)&&f.preventDefault()},Ub:c})},Q,Nb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=(c,d,e,k,f)=>
b.drawElementsInstancedANGLE(c,d,e,k,f))},Ob=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Pb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Qb=a=>{a.Jc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},Rb=a=>{a.Mc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},
Sb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Tb=1,Ub=[],R=[],Vb=[],Wb=[],Xb=[],S=[],Yb=[],Zb=[],T=[],$b={},ac=4,bc=0,cc=a=>{for(var b=Tb++,c=a.length;c<b;c++)a[c]=null;return b},dc=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=Q[c](),f=k&&cc(d);k?(k.name=f,d[f]=k):U||=1282;v[b+4*e>>2]=f}},fc=(a,b)=>{a.Xb||(a.Xb=a.getContext,a.getContext=function(d,e){e=a.Xb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.hc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?ec(c,b):0},ec=(a,b)=>{var c=cc(Zb),d={handle:c,attributes:b,version:b.hc,$b:a};a.canvas&&(a.canvas.Fc=d);Zb[c]=d;("undefined"==typeof b.nc||b.nc)&&gc(d);return c},hc=a=>{V=Zb[a];g.fc=Q=V?.$b;return!(a&&!Q)},gc=a=>{a||=V;if(!a.Cc){a.Cc=!0;var b=a.$b;Nb(b);Ob(b);Pb(b);Qb(b);Rb(b);2<=a.version&&(b.mc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.mc)b.mc=b.getExtension("EXT_disjoint_timer_query");b.Dc=b.getExtension("WEBGL_multi_draw");Sb(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},ic={},U,V,jc=(a,b,c,d,e,k)=>{a={target:M(a),Tb:k,Vb:d,Wb:(f=event)=>{N(d)(e,0,b)&&f.preventDefault()},Ub:c};K(a)},kc=(a,b,c,d)=>{zb||=P(96);return K({target:a,ec:!0,Tb:"wheel",Vb:d,Wb:(e=event)=>{var k=zb;Hb(k,e,a);y[k+64>>3]=e.deltaX;y[k+72>>3]=e.deltaY;y[k+80>>3]=e.deltaZ;v[k+88>>2]=e.deltaMode;N(d)(9,k,b)&&e.preventDefault()},Ub:c})},lc=["default","low-power","high-performance"];function mc(){var a=Sb(Q);return a=a.concat(a.map(b=>"GL_"+b))}
var nc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Q.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=mc().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=Q.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else U||=1281},oc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},pc=a=>{var b=oc(a)+1,c=P(b);c&&O(a,c,b);return c},qc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),rc=[],sc=a=>{a-=5120;return 0==a?t:1==a?u:2==a?oa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?w:pa},W=a=>{var b=Q.zc;if(b){var c=b.Zb[a];"number"==typeof c&&(b.Zb[a]=c=Q.getUniformLocation(b,b.xc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],tc=[],vc=a=>{var b=oc(a)+
1,c=uc(b);O(a,c,b);return c},yc=a=>{var b=wc();a();xc(b)};
g.requestFullscreen=function(a,b){function c(){bb=!1;var k=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===k?(d.exitFullscreen=ib,hb&&d.requestPointerLock(),bb=!0,I?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=w[SDL.screen>>2]|8388608),mb(g.canvas),lb()):mb(d)):(k.parentNode.insertBefore(d,k),k.parentNode.removeChild(k),I?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=w[SDL.screen>>
2]&-8388609),mb(g.canvas),lb()):mb(d));g.onFullScreen?.(bb);g.onFullscreen?.(bb)}hb=a;I=b;"undefined"==typeof hb&&(hb=!0);"undefined"==typeof I&&(I=!1);var d=g.canvas;gb||(gb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};g.requestAnimationFrame=Sa;g.setCanvasSize=function(a,b,c){mb(g.canvas,a,b);c||lb()};g.pauseMainLoop=ab;g.resumeMainLoop=function(){H++;var a=Oa,b=Pa,c=C;C=null;$a(c,0,!1,Va,!0);Ua(a,b);F()};
g.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};g.createContext=function(a,b,c,d){if(b&&g.fc&&a==g.canvas)return g.fc;var e;if(b){var k={antialias:!1,alpha:!1,hc:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var f in d)k[f]=d[f];if("undefined"!=typeof ic&&(e=fc(a,k)))var l=Zb[e].$b}else l=a.getContext("2d");if(!l)return null;c&&(g.fc=l,b&&hc(e),db.forEach(n=>n()),eb());return l};
for(var Y=0;32>Y;++Y)rc.push(Array(Y));var zc=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=zc.subarray(0,Y);var Ac=new Int32Array(288);for(Y=0;288>=Y;++Y)tc[Y]=Ac.subarray(0,Y);
var Lc={$a:()=>{xa("")},_a:(a,b,c)=>u.copyWithin(a,b,b+c),Xa:()=>{Ha=!1;Ja=0},Ya:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];Ma(()=>Bc(a,Na()))},b);B[a]={id:c,Uc:b};return 0},Ma:()=>{ab();C=null},aa:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ca:(a,b,c)=>{a=M(a);if(!a)return-4;a=Cb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Na:()=>performance.now(),Ua:(a,b)=>{function c(d){N(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
Za:a=>{var b=u.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536;try{na.grow(d);qa();var e=1;break a}catch(k){}e=void 0}if(e)return!0}return!1},K:(a,b,c,d)=>Fb(a,b,c,d,12,"blur"),$:(a,b,c)=>{a=M(a);if(!a)return-4;a.width=b;a.height=c;return 0},L:(a,b,c,d)=>Fb(a,b,c,d,13,"focus"),U:(a,b,c,d)=>Gb(a,b,c,d,2,"keydown"),S:(a,b,c,d)=>Gb(a,b,c,d,1,"keypress"),
T:(a,b,c,d)=>Gb(a,b,c,d,3,"keyup"),Va:(a,b,c)=>{a=N(a);$a(a,b,c)},_:(a,b,c,d)=>Ib(a,b,c,d,5,"mousedown"),X:(a,b,c,d)=>Ib(a,b,c,d,33,"mouseenter"),W:(a,b,c,d)=>Ib(a,b,c,d,34,"mouseleave"),Y:(a,b,c,d)=>Ib(a,b,c,d,8,"mousemove"),Z:(a,b,c,d)=>Ib(a,b,c,d,6,"mouseup"),N:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Xb||document.body.kc||document.body.jc))return-1;a=M(a);if(!a)return-4;Jb(a,b,c,d,"mozpointerlockchange");Jb(a,b,c,d,"webkitpointerlockchange");
Jb(a,b,c,d,"mspointerlockchange");return Jb(a,b,c,d,"pointerlockchange")},M:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.Xb||document.body.kc||document.body.jc))return-1;a=M(a);if(!a)return-4;Kb(a,b,c,d,"mozpointerlockerror");Kb(a,b,c,d,"webkitpointerlockerror");Kb(a,b,c,d,"mspointerlockerror");return Kb(a,b,c,d,"pointerlockerror")},ba:(a,b,c,d)=>Lb(a,b,c,d),O:(a,b,c,d)=>Mb(a,b,c,d,25,"touchcancel"),P:(a,b,c,d)=>Mb(a,b,c,d,23,"touchend"),Q:(a,b,c,d)=>Mb(a,b,c,d,24,"touchmove"),
R:(a,b,c,d)=>Mb(a,b,c,d,22,"touchstart"),J:(a,b,c,d)=>{jc(a,b,c,d,31,"webglcontextlost");return 0},I:(a,b,c,d)=>{jc(a,b,c,d,32,"webglcontextrestored");return 0},V:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?kc(a,b,c,d):-1:-4,Ta:(a,b)=>{var c=b>>2;b={alpha:!!t[b+0],depth:!!t[b+1],stencil:!!t[b+2],antialias:!!t[b+3],premultipliedAlpha:!!t[b+4],preserveDrawingBuffer:!!t[b+5],powerPreference:lc[v[c+2]],failIfMajorPerformanceCaveat:!!t[b+12],hc:v[c+4],Nc:v[c+5],nc:t[b+24],Ac:t[b+25],Oc:v[c+7],Qc:t[b+
32]};a=M(a);return!a||b.Ac?0:fc(a,b)},Qa:(a,b)=>{a=Zb[a];b=b?L(b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Nb(Q);"OES_vertex_array_object"==b&&Ob(Q);"WEBGL_draw_buffers"==b&&Pb(Q);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Qb(Q);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Rb(Q);"WEBGL_multi_draw"==b&&(Q.Dc=Q.getExtension("WEBGL_multi_draw"));return!!a.$b.getExtension(b)},Ra:a=>hc(a)?0:-5,i:a=>Q.activeTexture(a),x:(a,b)=>{Q.attachShader(R[a],S[b])},
c:(a,b)=>{35051==a?Q.lc=b:35052==a&&(Q.ac=b);Q.bindBuffer(a,Ub[b])},a:(a,b,c)=>{Q.bindBufferBase(a,b,Ub[c])},n:(a,b)=>{Q.bindFramebuffer(a,Vb[b])},h:(a,b)=>{Q.bindSampler(a,T[b])},b:(a,b)=>{Q.bindTexture(a,Xb[b])},H:a=>{Q.bindVertexArray(Yb[a])},D:(a,b,c,d)=>Q.blendColor(a,b,c,d),E:(a,b)=>Q.blendEquationSeparate(a,b),F:(a,b,c,d)=>Q.blendFuncSeparate(a,b,c,d),bb:(a,b,c,d,e,k,f,l,n,p)=>Q.blitFramebuffer(a,b,c,d,e,k,f,l,n,p),ya:(a,b,c,d)=>{2<=V.version?c&&b?Q.bufferData(a,u,d,c,b):Q.bufferData(a,b,d):
Q.bufferData(a,c?u.subarray(c,c+b):b,d)},xa:(a,b,c,d)=>{2<=V.version?c&&Q.bufferSubData(a,b,u,d,c):Q.bufferSubData(a,b,u.subarray(d,d+c))},ub:(a,b,c,d)=>Q.clearBufferfi(a,b,c,d),ga:(a,b,c)=>{Q.clearBufferfv(a,b,x,c>>2)},tb:(a,b,c)=>{Q.clearBufferiv(a,b,v,c>>2)},k:(a,b,c,d)=>{Q.colorMask(!!a,!!b,!!c,!!d)},ka:a=>{Q.compileShader(S[a])},qa:()=>{var a=cc(R),b=Q.createProgram();b.name=a;b.dc=b.bc=b.cc=0;b.ic=1;R[a]=b;return a},ma:a=>{var b=cc(S);S[b]=Q.createShader(a);return b},A:a=>Q.cullFace(a),Ea:(a,
b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Ub[d];e&&(Q.deleteBuffer(e),e.name=0,Ub[d]=null,d==Q.lc&&(Q.lc=0),d==Q.ac&&(Q.ac=0))}},j:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=Vb[d];e&&(Q.deleteFramebuffer(e),e.name=0,Vb[d]=null)}},z:a=>{if(a){var b=R[a];b?(Q.deleteProgram(b),b.name=0,R[a]=null):U||=1281}},Ca:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Wb[d];e&&(Q.deleteRenderbuffer(e),e.name=0,Wb[d]=null)}},Ba:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=T[d];e&&(Q.deleteSampler(e),
e.name=0,T[d]=null)}},o:a=>{if(a){var b=S[a];b?(Q.deleteShader(b),S[a]=null):U||=1281}},Da:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Xb[d];e&&(Q.deleteTexture(e),e.name=0,Xb[d]=null)}},Aa:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];Q.deleteVertexArray(Yb[d]);Yb[d]=null}},s:a=>Q.depthFunc(a),r:a=>{Q.depthMask(!!a)},e:a=>Q.disable(a),G:a=>{Q.disableVertexAttribArray(a)},db:(a,b,c)=>{Q.drawArrays(a,b,c)},eb:(a,b,c,d)=>{Q.drawArraysInstanced(a,b,c,d)},fb:(a,b,c,d)=>{Q.drawElements(a,b,c,d)},
gb:(a,b,c,d,e)=>{Q.drawElementsInstanced(a,b,c,d,e)},g:a=>Q.enable(a),qb:a=>{Q.enableVertexAttribArray(a)},B:a=>Q.frontFace(a),za:(a,b)=>{dc(a,b,"createBuffer",Ub)},ra:(a,b)=>{dc(a,b,"createSampler",T)},wa:(a,b)=>{dc(a,b,"createTexture",Xb)},La:(a,b)=>{dc(a,b,"createVertexArray",Yb)},ia:(a,b)=>Q.getAttribLocation(R[a],b?L(b):""),d:(a,b)=>nc(a,b),na:(a,b,c,d)=>{a=Q.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(v[c>>2]=b)},w:(a,b,c)=>{if(c)if(a>=Tb)U||=1281;else if(a=
R[a],35716==b)a=Q.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.dc)for(b=0;b<Q.getProgramParameter(a,35718);++b)a.dc=Math.max(a.dc,Q.getActiveUniform(a,b).name.length+1);v[c>>2]=a.dc}else if(35722==b){if(!a.bc)for(b=0;b<Q.getProgramParameter(a,35721);++b)a.bc=Math.max(a.bc,Q.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.bc}else if(35381==b){if(!a.cc)for(b=0;b<Q.getProgramParameter(a,35382);++b)a.cc=Math.max(a.cc,Q.getActiveUniformBlockName(a,b).length+
1);v[c>>2]=a.cc}else v[c>>2]=Q.getProgramParameter(a,b);else U||=1281},ja:(a,b,c,d)=>{a=Q.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(v[c>>2]=b)},u:(a,b,c)=>{c?35716==b?(a=Q.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(S[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=Q.getShaderParameter(S[a],b):U||=1281},Ja:(a,b)=>{if(2>V.version)return U||=1282,0;var c=$b[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=
mc().map(pc),c=$b[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},l:(a,b)=>{b=b?L(b):"";if(a=R[a]){var c=a,d=c.Zb,e=c.yc,k;if(!d)for(c.Zb=d={},c.xc={},k=0;k<Q.getProgramParameter(c,35718);++k){var f=Q.getActiveUniform(c,k);var l=f.name;f=f.size;var n=qc(l);n=0<n?l.slice(0,n):l;var p=c.ic;c.ic+=f;e[n]=[f,p];for(l=0;l<f;++l)d[p]=l,c.xc[p++]=n}c=a.Zb;d=0;e=b;k=qc(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.yc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||Q.getUniformLocation(a,
b)))return d}else U||=1281;return-1},ab:(a,b,c)=>{for(var d=rc[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];Q.invalidateFramebuffer(a,d)},pa:a=>{a=R[a];Q.linkProgram(a);a.Zb=0;a.yc={}},Ka:(a,b)=>{3317==a?ac=b:3314==a&&(bc=b);Q.pixelStorei(a,b)},C:(a,b)=>Q.polygonOffset(a,b),cb:a=>Q.readBuffer(a),y:(a,b,c)=>{Q.samplerParameterf(T[a],b,c)},f:(a,b,c)=>{Q.samplerParameteri(T[a],b,c)},vb:(a,b,c,d)=>Q.scissor(a,b,c,d),la:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var f=(f=w[c+4*k>>2])?L(f,d?w[d+4*k>>2]:void 0):"";e+=f}Q.shaderSource(S[a],
e)},Ha:(a,b,c)=>Q.stencilFunc(a,b,c),fa:(a,b,c,d)=>Q.stencilFuncSeparate(a,b,c,d),q:a=>Q.stencilMask(a),Ga:(a,b,c)=>Q.stencilOp(a,b,c),ea:(a,b,c,d)=>Q.stencilOpSeparate(a,b,c,d),ta:(a,b,c,d,e,k,f,l,n)=>{if(2<=V.version){if(Q.ac){Q.texImage2D(a,b,c,d,e,k,f,l,n);return}if(n){var p=sc(l);n>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);Q.texImage2D(a,b,c,d,e,k,f,l,p,n);return}}if(n){p=sc(l);var D=e*((bc||d)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*p.BYTES_PER_ELEMENT+ac-1&-ac);
n=p.subarray(n>>>31-Math.clz32(p.BYTES_PER_ELEMENT),n+D>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else n=null;Q.texImage2D(a,b,c,d,e,k,f,l,n)},sa:(a,b,c,d,e,k,f,l,n,p)=>{if(Q.ac)Q.texImage3D(a,b,c,d,e,k,f,l,n,p);else if(p){var D=sc(n);Q.texImage3D(a,b,c,d,e,k,f,l,n,D,p>>>31-Math.clz32(D.BYTES_PER_ELEMENT))}else Q.texImage3D(a,b,c,d,e,k,f,l,n,null)},ua:(a,b,c)=>Q.texParameteri(a,b,c),pb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];
else d=x.subarray(c>>2,c+4*b>>2);Q.uniform1fv(W(a),d)}},v:(a,b)=>{Q.uniform1i(W(a),b)},lb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=tc[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);Q.uniform1iv(W(a),d)}},ob:(a,b,c)=>{if(2<=V.version)b&&Q.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b)for(var d=X[2*b],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);Q.uniform2fv(W(a),d)}},kb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform2iv(W(a),
v,c>>2,2*b);else{if(144>=b)for(var d=tc[2*b],e=0;e<2*b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2];else d=v.subarray(c>>2,c+8*b>>2);Q.uniform2iv(W(a),d)}},nb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b)for(var d=X[3*b],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);Q.uniform3fv(W(a),d)}},jb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=b)for(var d=tc[3*b],e=0;e<3*b;e+=3)d[e]=v[c+
4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2];else d=v.subarray(c>>2,c+12*b>>2);Q.uniform3iv(W(a),d)}},mb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;for(var k=0;k<4*b;k+=4){var f=c+k;d[k]=e[f];d[k+1]=e[f+1];d[k+2]=e[f+2];d[k+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);Q.uniform4fv(W(a),d)}},ib:(a,b,c)=>{if(2<=V.version)b&&Q.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b)for(var d=tc[4*b],e=0;e<4*b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>
2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2];else d=v.subarray(c>>2,c+16*b>>2);Q.uniform4iv(W(a),d)}},hb:(a,b,c,d)=>{if(2<=V.version)b&&Q.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],k=x;d>>=2;for(var f=0;f<16*b;f+=16){var l=d+f;e[f]=k[l];e[f+1]=k[l+1];e[f+2]=k[l+2];e[f+3]=k[l+3];e[f+4]=k[l+4];e[f+5]=k[l+5];e[f+6]=k[l+6];e[f+7]=k[l+7];e[f+8]=k[l+8];e[f+9]=k[l+9];e[f+10]=k[l+10];e[f+11]=k[l+11];e[f+12]=k[l+12];e[f+13]=k[l+13];e[f+14]=k[l+14];e[f+15]=k[l+15]}}else e=x.subarray(d>>
2,d+64*b>>2);Q.uniformMatrix4fv(W(a),!!c,e)}},m:a=>{a=R[a];Q.useProgram(a);Q.zc=a},rb:(a,b)=>{Q.vertexAttribDivisor(a,b)},sb:(a,b,c,d,e,k)=>{Q.vertexAttribPointer(a,b,c,!!d,e,k)},wb:(a,b,c,d)=>Q.viewport(a,b,c,d),Wa:Ka,yb:function(){g.rc=a=>{0!=Cc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.rc)},Sa:function(){g.wc=a=>{const b=a.clipboardData.getData("text");yc(()=>{const c=vc(b);Dc(c)})};window.addEventListener("paste",g.wc)},Oa:function(a){g.Rc=[];a=a?L(a):
"";a=document.getElementById(a);g.sc=b=>{b.stopPropagation();b.preventDefault()};g.tc=b=>{b.stopPropagation();b.preventDefault()};g.uc=b=>{b.stopPropagation();b.preventDefault()};g.vc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Sc=c;Ec(c.length);for(let e=0;e<c.length;e++)yc(()=>{const k=vc(c[e].name);Fc(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Gc(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.sc,!1);a.addEventListener("dragleave",
g.tc,!1);a.addEventListener("dragover",g.uc,!1);a.addEventListener("drop",g.vc,!1)},va:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Fa:function(a){a=a?L(a):"";g.Yb=document.getElementById(a);g.Yb||console.log("sokol_app.h: invalid target:"+a);g.Yb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},xb:function(){window.removeEventListener("beforeunload",g.rc)},Pa:function(){window.removeEventListener("paste",
g.wc)},Ia:function(a){a=a?L(a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.sc);a.removeEventListener("dragleave",g.tc);a.removeEventListener("dragover",g.uc);a.removeEventListener("drop",g.vc)},p:function(){g.Yb&&g.Yb.requestPointerLock&&g.Yb.requestPointerLock()},oa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(u.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");
a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},t:function(a,b,c,d,e,k){b=b?L(b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const l=0<d;l&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!l){const n=new Uint8Array(f.response),p=n.length;p<=k?(u.set(n,e),Hc(a,d,p)):Ic(a)}else Jc(a,f.status)};f.send()},ha:function(a,
b){b=b?L(b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");Kc(a,d)}else Jc(a,c.status)};c.send()},da:function(a,b){b=b?L(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;na=Z.zb;qa();Eb=Z.Ob;sa.unshift(Z.Ab);z--;g.monitorRunDependencies?.(z);0==z&&
(null!==wa&&(clearInterval(wa),wa=null),A&&(c=A,A=null,c()));return Z}var b={a:Lc};z++;g.monitorRunDependencies?.(z);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return m(`Module.instantiateWasm callback failed with error: ${c}`),!1}Aa||=za("loadpng-sapp.wasm")?"loadpng-sapp.wasm":g.locateFile?g.locateFile("loadpng-sapp.wasm",h):h+"loadpng-sapp.wasm";Ea(b,function(c){a(c.instance)});return{}}(),Dc=g.__sapp_emsc_onpaste=a=>(Dc=g.__sapp_emsc_onpaste=Z.Bb)(a),Cc=g.__sapp_html5_get_ask_leave_site=
()=>(Cc=g.__sapp_html5_get_ask_leave_site=Z.Cb)(),Ec=g.__sapp_emsc_begin_drop=a=>(Ec=g.__sapp_emsc_begin_drop=Z.Db)(a),Fc=g.__sapp_emsc_drop=(a,b)=>(Fc=g.__sapp_emsc_drop=Z.Eb)(a,b),Gc=g.__sapp_emsc_end_drop=(a,b,c)=>(Gc=g.__sapp_emsc_end_drop=Z.Fb)(a,b,c);g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,k,f,l)=>(g.__sapp_emsc_invoke_fetch_cb=Z.Gb)(a,b,c,d,e,k,f,l);var Mc=g._main=(a,b)=>(Mc=g._main=Z.Hb)(a,b);g.__saudio_emsc_pull=a=>(g.__saudio_emsc_pull=Z.Ib)(a);
var Kc=g.__sfetch_emsc_head_response=(a,b)=>(Kc=g.__sfetch_emsc_head_response=Z.Jb)(a,b),Hc=g.__sfetch_emsc_get_response=(a,b,c)=>(Hc=g.__sfetch_emsc_get_response=Z.Kb)(a,b,c),Jc=g.__sfetch_emsc_failed_http_status=(a,b)=>(Jc=g.__sfetch_emsc_failed_http_status=Z.Lb)(a,b),Ic=g.__sfetch_emsc_failed_buffer_too_small=a=>(Ic=g.__sfetch_emsc_failed_buffer_too_small=Z.Mb)(a),P=a=>(P=Z.Nb)(a),Bc=(a,b)=>(Bc=Z.Pb)(a,b),xc=a=>(xc=Z.Qb)(a),uc=a=>(uc=Z.Rb)(a),wc=()=>(wc=Z.Sb)(),Nc;
A=function Oc(){Nc||Pc();Nc||(A=Oc)};function Qc(a=[]){var b=Mc;a.unshift(fa);var c=a.length,d=uc(4*(c+1)),e=d;a.forEach(f=>{w[e>>2]=vc(f);e+=4});w[e>>2]=0;try{var k=b(c,d);La(k)}catch(f){Ia(f)}}
function Pc(){var a=ea;function b(){if(!Nc&&(Nc=!0,g.calledRun=!0,!q)){Ga(sa);Ga(ta);g.onRuntimeInitialized?.();Rc&&Qc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();ua.unshift(c)}Ga(ua)}}if(!(0<z)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)va();Ga(ra);0<z||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Rc=!0;g.noInitialRun&&(Rc=!1);Pc();
