var f;f||(f=typeof Module !== 'undefined' ? Module : {});var g={},k;for(k in f)f.hasOwnProperty(k)&&(g[k]=f[k]);f.arguments=[];f.thisProgram="./this.program";f.quit=function(a,b){throw b;};f.preRun=[];f.postRun=[];var m=!1,q=!1,aa=!1,ba=!1,ca=!1;m="object"===typeof window;q="function"===typeof importScripts;aa=(ba="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!m&&!q;ca=!m&&!aa&&!q;var u="",da,v;
if(aa){u=__dirname+"/";var ea,fa;da=function(a,b){ea||(ea=require("fs"));fa||(fa=require("path"));a=fa.normalize(a);a=ea.readFileSync(a);return b?a:a.toString()};v=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||w("Assertion failed: undefined");return a};1<process.argv.length&&(f.thisProgram=process.argv[1].replace(/\\/g,"/"));f.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=f);process.on("uncaughtException",function(a){if(!(a instanceof x))throw a;});
process.on("unhandledRejection",w);f.quit=function(a){process.exit(a)};f.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(da=function(a){return read(a)}),v=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||w("Assertion failed: undefined");return a},"undefined"!=typeof scriptArgs?f.arguments=scriptArgs:"undefined"!=typeof arguments&&(f.arguments=arguments),"function"===typeof quit&&
(f.quit=function(a){quit(a)});else if(m||q)q?u=self.location.href:document.currentScript&&(u=document.currentScript.src),u=0!==u.indexOf("blob:")?u.substr(0,u.lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},q&&(v=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var ha=f.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),z=f.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ha);for(k in g)g.hasOwnProperty(k)&&(f[k]=g[k]);g=void 0;"object"!==typeof WebAssembly&&z("no native wasm support detected");var A,ia=!1,ja="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function B(a,b){if(a){var c=C,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&ja)a=ja.decode(c.subarray(a,b));else{for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var l=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|l:(e&7)<<18|h<<12|l<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}a=d}}else a="";return a}
function D(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var l=a.charCodeAt(h);if(55296<=l&&57343>=l){var n=a.charCodeAt(++h);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function ka(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function la(a){var b=ka(a)+1,c=ma(b);D(a,E,c,b);return c}function na(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,E,C,F,oa,G,pa,H,I;
function qa(){f.HEAP8=E=new Int8Array(buffer);f.HEAP16=F=new Int16Array(buffer);f.HEAP32=G=new Int32Array(buffer);f.HEAPU8=C=new Uint8Array(buffer);f.HEAPU16=oa=new Uint16Array(buffer);f.HEAPU32=pa=new Uint32Array(buffer);f.HEAPF32=H=new Float32Array(buffer);f.HEAPF64=I=new Float64Array(buffer)}var ra=f.TOTAL_MEMORY||33554432;5242880>ra&&z("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+ra+"! (TOTAL_STACK=5242880)");f.wasmMemory?A=f.wasmMemory:A=new WebAssembly.Memory({initial:ra/65536});
A&&(buffer=A.buffer);ra=buffer.byteLength;qa();G[73164]=5535552;function sa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Pb;"number"===typeof c?void 0===b.Gb?f.dynCall_v(c):f.dynCall_vi(c,b.Gb):c(void 0===b.Gb?null:b.Gb)}}}var ta=[],ua=[],va=[],wa=[],xa=[];function ya(){var a=f.preRun.shift();ta.unshift(a)}var za=Math.abs,Aa=Math.sqrt,Ba=Math.floor,J=0,Ca=null,K=null;f.preloadedImages={};f.preloadedAudios={};
function Da(){var a=L;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var L="loadpng-sapp.wasm";if(!Da()){var Ea=L;L=f.locateFile?f.locateFile(Ea,u):u+Ea}function Ga(){try{if(f.wasmBinary)return new Uint8Array(f.wasmBinary);if(v)return v(L);throw"both async and sync fetching of the wasm failed";}catch(a){w(a)}}
function Ha(){return f.wasmBinary||!m&&!q||"function"!==typeof fetch?new Promise(function(a){a(Ga())}):fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ga()})}
function Ia(a){function b(a){f.asm=a.exports;J--;f.monitorRunDependencies&&f.monitorRunDependencies(J);0==J&&(null!==Ca&&(clearInterval(Ca),Ca=null),K&&(a=K,K=null,a()))}function c(a){b(a.instance)}function d(a){return Ha().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){z("failed to asynchronously prepare wasm: "+a);w(a)})}var e={env:a};J++;f.monitorRunDependencies&&f.monitorRunDependencies(J);if(f.instantiateWasm)try{return f.instantiateWasm(e,b)}catch(h){return z("Module.instantiateWasm callback failed with error: "+
h),!1}(function(){if(f.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Da()||"function"!==typeof fetch)return d(c);fetch(L,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,e).then(c,function(a){z("wasm streaming compile failed: "+a);z("falling back to ArrayBuffer instantiation");d(c)})})})();return{}}f.asm=function(a,b){b.memory=A;b.table=new WebAssembly.Table({initial:25,maximum:25,element:"anyfunc"});return Ia(b)};ua.push({Pb:function(){Ja()}});
var Ka=0,La=0,M=0,Ma=0,Na=0,Oa=null,Pa=null,Qa=!1;function Ra(){for(var a=N.length-1;0<=a;--a)Sa(a);N=[];Ta=[]}var Ta=[];function Ua(){if(Va&&Wa.yb)for(var a=0;a<Ta.length;++a){var b=Ta[a];Ta.splice(a,1);--a;b.Zb.apply(this,b.Tb)}}var Va=0,Wa=null,N=[];function Xa(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function Sa(a){var b=N[a];b.target.removeEventListener(b.xb,b.Nb,b.zb);N.splice(a,1)}
function O(a){function b(b){++Va;Wa=a;Ua();a.Cb(b);Ua();--Va}if(a.Ab)a.Nb=b,a.target.addEventListener(a.xb,b,a.zb),N.push(a),Qa||(wa.push(Ra),Qa=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].xb==a.xb&&Sa(c--)}var Ya=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function P(a){try{if(!a)return window;"number"===typeof a&&(a=Ya[a]||B(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?f.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function Za(a){"number"===typeof a&&(a=B(a));return a&&"#canvas"!==a?"undefined"!==typeof $a&&ab[a]?ab[a]:P(a):"undefined"!==typeof $a&&ab.canvas?ab.canvas:f.canvas}
function bb(a,b,c,d,e,h){Ka||(Ka=Q(164));a={target:P(a),yb:Xa()?!1:!0,xb:h,Ab:d,Cb:function(a){a=a||window.event;var c=Ka;D(a.key?a.key:"",C,c+0,32);D(a.code?a.code:"",C,c+32,32);G[c+64>>2]=a.location;G[c+68>>2]=a.ctrlKey;G[c+72>>2]=a.shiftKey;G[c+76>>2]=a.altKey;G[c+80>>2]=a.metaKey;G[c+84>>2]=a.repeat;D(a.locale?a.locale:"",C,c+88,32);D(a.char?a.char:"",C,c+120,32);G[c+152>>2]=a.charCode;G[c+156>>2]=a.keyCode;G[c+160>>2]=a.which;R(d,e,c,b)&&a.preventDefault()},zb:c};O(a)}
function cb(a,b,c){I[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();G[a+8>>2]=b.screenX;G[a+12>>2]=b.screenY;G[a+16>>2]=b.clientX;G[a+20>>2]=b.clientY;G[a+24>>2]=b.ctrlKey;G[a+28>>2]=b.shiftKey;G[a+32>>2]=b.altKey;G[a+36>>2]=b.metaKey;F[a+40>>1]=b.button;F[a+42>>1]=b.buttons;G[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-Oa;G[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-Pa;if(f.canvas){var d=f.canvas.getBoundingClientRect();
G[a+60>>2]=b.clientX-d.left;G[a+64>>2]=b.clientY-d.top}else G[a+60>>2]=0,G[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},G[a+52>>2]=b.clientX-d.left,G[a+56>>2]=b.clientY-d.top):(G[a+52>>2]=0,G[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(Oa=b.screenX,Pa=b.screenY)}
function S(a,b,c,d,e,h){La||(La=Q(72));a=P(a);c={target:a,yb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,xb:h,Ab:d,Cb:function(c){c=c||window.event;cb(La,c,a);R(d,e,La,b)&&c.preventDefault()},zb:c};Xa()&&"mousedown"==h&&(c.yb=!1);O(c)}
function db(a,b,c,d){Ma||(Ma=Q(36));a=P(a);O({target:a,yb:!1,xb:"resize",Ab:d,Cb:function(c){c=c||window.event;if(c.target==a){var e=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],l=Ma;G[l>>2]=c.detail;G[l+4>>2]=document.body.clientWidth;
G[l+8>>2]=document.body.clientHeight;G[l+12>>2]=window.innerWidth;G[l+16>>2]=window.innerHeight;G[l+20>>2]=window.outerWidth;G[l+24>>2]=window.outerHeight;G[l+28>>2]=e[0];G[l+32>>2]=e[1];R(d,10,l,b)&&c.preventDefault()}},zb:c})}
function eb(a,b,c,d,e,h){Na||(Na=Q(1684));a=P(a);O({target:a,yb:"touchstart"==h||"touchend"==h,xb:h,Ab:d,Cb:function(c){c=c||window.event;for(var h={},l=0;l<c.touches.length;++l){var r=c.touches[l];r.Ib=!1;h[r.identifier]=r}for(l=0;l<c.changedTouches.length;++l)r=c.changedTouches[l],h[r.identifier]=r,r.Ib=!0;for(l=0;l<c.targetTouches.length;++l)r=c.targetTouches[l],h[r.identifier].Rb=!0;var t=r=Na;G[t+4>>2]=c.ctrlKey;G[t+8>>2]=c.shiftKey;G[t+12>>2]=c.altKey;G[t+16>>2]=c.metaKey;t+=20;var Fa=f.canvas?
f.canvas.getBoundingClientRect():void 0,gb=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},hb=0;for(l in h){var y=h[l];G[t>>2]=y.identifier;G[t+4>>2]=y.screenX;G[t+8>>2]=y.screenY;G[t+12>>2]=y.clientX;G[t+16>>2]=y.clientY;G[t+20>>2]=y.pageX;G[t+24>>2]=y.pageY;G[t+28>>2]=y.Ib;G[t+32>>2]=y.Rb;Fa?(G[t+44>>2]=y.clientX-Fa.left,G[t+48>>2]=y.clientY-Fa.top):(G[t+44>>2]=0,G[t+48>>2]=0);G[t+36>>2]=y.clientX-gb.left;G[t+40>>2]=y.clientY-gb.top;t+=52;if(32<=++hb)break}G[r>>2]=hb;R(d,e,r,b)&&
c.preventDefault()},zb:c})}function fb(a,b,c,d,e,h){a||(a=f.canvas);a={target:P(a),yb:!1,xb:h,Ab:d,Cb:function(a){a=a||window.event;R(d,e,0,b)&&a.preventDefault()},zb:c};O(a)}
function ib(a,b,c,d,e){function h(c){c=c||window.event;cb(M,c,a);I[M+72>>3]=c.wheelDeltaX||0;I[M+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);I[M+88>>3]=0;G[M+96>>2]=0;R(d,9,M,b)&&c.preventDefault()}function l(c){c=c||window.event;var e=M;cb(e,c,a);I[e+72>>3]=c.deltaX;I[e+80>>3]=c.deltaY;I[e+88>>3]=c.deltaZ;G[e+96>>2]=c.deltaMode;R(d,9,e,b)&&c.preventDefault()}M||(M=Q(104));O({target:a,yb:!0,xb:e,Ab:d,Cb:"wheel"==e?l:h,zb:c})}
var jb=1,kb=0,lb=[],T=[],mb=[],nb=[],ob=[],U=[],V=[],pb=[],qb={},W=null,ab={},rb={},sb={};function X(a){kb||(kb=a)}function tb(a){for(var b=jb++,c=a.length;c<b;c++)a[c]=null;return b}var ub=null,Y=[0];function vb(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=Q(8),e={handle:d,attributes:b,version:b.Lb,Fb:a};e.wb=2<=e.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.Sb=e);qb[d]=e;("undefined"===typeof b.Kb||b.Kb)&&wb(e);return d}
function wb(a){a||(a=W);if(!a.Qb){a.Qb=!0;var b=a.Fb;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,e){c.drawArraysInstancedANGLE(a,b,d,e)},b.drawElementsInstanced=function(a,b,d,e,h){c.drawElementsInstancedANGLE(a,b,d,e,h)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var e=b.getExtension("WEBGL_draw_buffers");e&&(b.drawBuffers=function(a,b){e.drawBuffersWEBGL(a,b)})}b.Vb=b.getExtension("EXT_disjoint_timer_query");var h="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=h.indexOf(a)&&b.getExtension(a)})}}var $a={},xb,yb,zb=["default","low-power","high-performance"],Ab=[];function Bb(a,b,c,d){for(var e=0;e<a;e++){var h=Z[c](),l=h&&tb(d);h?(h.name=l,d[l]=h):X(1282);G[b+4*e>>2]=l}}
function Cb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>W.version){X(1282);return}d=Z.getSupportedExtensions();c=null===d?0:2*d.length;break;case 33307:case 33308:if(2>W.version){X(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":X(1280);return;case "object":if(null===
d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=0;break;default:X(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)G[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){X(1280);z("GL_INVALID_ENUM in glGetIntegerv: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:X(1280);return}G[b>>2]=c}else X(1281)}
function Db(a){var b=ka(a)+1,c=Q(b);D(a,C,c,b);return c}var Eb={6402:1,6403:1,6406:1,6407:3,6408:4,6409:1,6410:2,33319:2,33320:2,35904:3,35906:4,36244:1,36248:3,36249:4},Fb={5120:1,5121:1,5122:2,5123:2,5124:4,5125:4,5126:4,5131:2,32819:2,32820:2,33635:2,33640:4,34042:4,35899:4,35902:4,36193:2};
function Gb(a,b,c,d,e){if(b=Eb[b]*Fb[a])switch(c=e+d*(c*b+4-1&-4),a){case 5120:return E.subarray(e,c);case 5121:return C.subarray(e,c);case 5122:return F.subarray(e>>1,c>>1);case 5124:return G.subarray(e>>2,c>>2);case 5126:return H.subarray(e>>2,c>>2);case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return pa.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return oa.subarray(e>>1,c>>1);default:X(1280)}else X(1280)}
function Hb(a){switch(a){case 5120:return E;case 5121:return C;case 5122:return F;case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return oa;case 5124:return G;case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return pa;case 5126:return H}}var Ib={5122:1,5123:1,5124:2,5125:2,5126:2,5131:1,32819:1,32820:1,33635:1,33640:2,34042:2,35899:2,35902:2,36193:1};function Jb(){f.___errno_location&&(G[f.___errno_location()>>2]=12)}
function Kb(a){a=na(a);var b=buffer.byteLength;try{return-1!==A.grow((a-b)/65536)?(buffer=A.buffer,!0):!1}catch(c){return!1}}var Z;ub=new Float32Array(256);for(var Lb=0;256>Lb;Lb++)Y[Lb]=ub.subarray(0,Lb+1);for(var Mb=0;32>Mb;Mb++)Ab.push(Array(Mb));
var Ub=f.asm({},{W:function(){return window.devicePixelRatio||1},Y:function(a,b,c){a=a?P(a):f.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),I[b>>3]=a.right-a.left,I[c>>3]=a.bottom-a.top):(I[b>>3]=a.clientWidth,I[c>>3]=a.clientHeight);return 0},Wa:function(a,b,c){C.set(C.subarray(b,b+c),a)},Ka:function(a,b){function c(d){Nb(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},U:function(a,b,c){a=Za(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ta:function(a,
b,c,d){bb(a,b,c,d,2,"keydown");return 0},Ra:function(a,b,c,d){bb(a,b,c,d,1,"keypress");return 0},Sa:function(a,b,c,d){bb(a,b,c,d,3,"keyup");return 0},la:function(a,b,c,d){S(a,b,c,d,5,"mousedown");return 0},Za:function(a,b,c,d){S(a,b,c,d,33,"mouseenter");return 0},Va:function(a,b,c,d){S(a,b,c,d,34,"mouseleave");return 0},eb:function(a,b,c,d){S(a,b,c,d,8,"mousemove");return 0},ea:function(a,b,c,d){S(a,b,c,d,6,"mouseup");return 0},fb:function(a,b,c,d){db(a,b,c,d);return 0},Na:function(a,b,c,d){eb(a,
b,c,d,25,"touchcancel");return 0},Oa:function(a,b,c,d){eb(a,b,c,d,23,"touchend");return 0},Pa:function(a,b,c,d){eb(a,b,c,d,24,"touchmove");return 0},Qa:function(a,b,c,d){eb(a,b,c,d,22,"touchstart");return 0},Ma:function(a,b,c,d){fb(a,b,c,d,31,"webglcontextlost");return 0},La:function(a,b,c,d){fb(a,b,c,d,32,"webglcontextrestored");return 0},Ua:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(ib(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(ib(a,b,c,d,"mousewheel"),0):-1},K:function(a,
b){var c={};b>>=2;c.alpha=!!G[b];c.depth=!!G[b+1];c.stencil=!!G[b+2];c.antialias=!!G[b+3];c.premultipliedAlpha=!!G[b+4];c.preserveDrawingBuffer=!!G[b+5];c.powerPreference=zb[G[b+6]];c.failIfMajorPerformanceCaveat=!!G[b+7];c.Lb=G[b+8];c.Wb=G[b+9];c.Kb=G[b+10];c.Ob=G[b+11];c.Xb=G[b+12];c.Yb=G[b+13];a=Za(a);!a||c.Ob?c=0:c=(a=1<c.Lb?a.getContext("webgl2",c):a.getContext("webgl",c)||a.getContext("experimental-webgl",c))?vb(a,c):0;return c},na:function(a,b){a=qb[a];b=B(b);0==b.indexOf("GL_")&&(b=b.substr(3));
return!!a.Fb.getExtension(b)},Da:function(a){a>>=2;for(var b=0;14>b;++b)G[a+b]=0;G[a]=G[a+1]=G[a+3]=G[a+4]=G[a+8]=G[a+10]=1},sa:function(a){W=qb[a];f.Ub=Z=W&&W.Fb;return!a||Z?0:-5},Xa:za,_a:Ba,k:function(a){Z.activeTexture(a)},J:function(a,b){Z.attachShader(T[a],V[b])},d:function(a,b){35051==a?Z.Jb=b:35052==a&&(Z.Bb=b);Z.bindBuffer(a,lb[b])},g:function(a,b){Z.bindFramebuffer(a,mb[b])},N:function(a,b){Z.bindRenderbuffer(a,nb[b])},b:function(a,b){Z.bindTexture(a,ob[b])},V:function(a){Z.bindVertexArray(pb[a])},
C:function(a,b,c,d){Z.blendColor(a,b,c,d)},D:function(a,b){Z.blendEquationSeparate(a,b)},E:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},l:function(a,b,c,d,e,h,l,n,p,r){Z.blitFramebuffer(a,b,c,d,e,h,l,n,p,r)},Q:function(a,b,c,d){W.wb?c?Z.bufferData(a,C,d,c,b):Z.bufferData(a,b,d):Z.bufferData(a,c?C.subarray(c,c+b):b,d)},P:function(a,b,c,d){W.wb?Z.bufferSubData(a,b,C,d,c):Z.bufferSubData(a,b,C.subarray(d,d+c))},H:function(a){Z.clear(a)},pa:function(a,b,c,d){Z.clearColor(a,b,c,d)},oa:function(a){Z.clearDepth(a)},
ma:function(a){Z.clearStencil(a)},u:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},ab:function(a){Z.compileShader(V[a])},Ba:function(a,b,c,d,e,h,l,n){W.wb?Z.Bb?Z.compressedTexImage2D(a,b,c,d,e,h,l,n):Z.compressedTexImage2D(a,b,c,d,e,h,C,n,l):Z.compressedTexImage2D(a,b,c,d,e,h,n?C.subarray(n,n+l):null)},za:function(a,b,c,d,e,h,l,n,p){W.wb?Z.Bb?Z.compressedTexImage3D(a,b,c,d,e,h,l,n,p):Z.compressedTexImage3D(a,b,c,d,e,h,l,C,p,n):Z.compressedTexImage3D(a,b,c,d,e,h,l,p?C.subarray(p,p+n):null)},wa:function(){var a=
tb(T),b=Z.createProgram();b.name=a;T[a]=b;return a},cb:function(a){var b=tb(V);V[b]=Z.createShader(a);return b},B:function(a){Z.cullFace(a)},Fa:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],e=lb[d];e&&(Z.deleteBuffer(e),e.name=0,lb[d]=null,d==xb&&(xb=0),d==yb&&(yb=0),d==Z.Jb&&(Z.Jb=0),d==Z.Bb&&(Z.Bb=0))}},i:function(a,b){for(var c=0;c<a;++c){var d=G[b+4*c>>2],e=mb[d];e&&(Z.deleteFramebuffer(e),e.name=0,mb[d]=null)}},S:function(a){if(a){var b=T[a];b?(Z.deleteProgram(b),b.name=0,T[a]=null,rb[a]=
null):X(1281)}},T:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],e=nb[d];e&&(Z.deleteRenderbuffer(e),e.name=0,nb[d]=null)}},v:function(a){if(a){var b=V[a];b?(Z.deleteShader(b),V[a]=null):X(1281)}},Ea:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],e=ob[d];e&&(Z.deleteTexture(e),e.name=0,ob[d]=null)}},Ga:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2];Z.deleteVertexArray(pb[d]);pb[d]=null}},s:function(a){Z.depthFunc(a)},t:function(a){Z.depthMask(!!a)},c:function(a){Z.disable(a)},a:function(a){Z.disableVertexAttribArray(a)},
$:function(a,b,c){Z.drawArrays(a,b,c)},n:function(a,b){for(var c=Ab[a],d=0;d<a;d++)c[d]=G[b+4*d>>2];Z.drawBuffers(c)},aa:function(a,b,c,d){Z.drawElements(a,b,c,d)},e:function(a){Z.enable(a)},ha:function(a){Z.enableVertexAttribArray(a)},A:function(a){Z.frontFace(a)},R:function(a,b){Bb(a,b,"createBuffer",lb)},O:function(a,b){Bb(a,b,"createRenderbuffer",nb)},Ca:function(a,b){Bb(a,b,"createTexture",ob)},Ha:function(a,b){Bb(a,b,"createVertexArray",pb)},ta:function(a,b){return Z.getAttribLocation(T[a],
B(b))},w:function(a,b){Cb(a,b)},ua:function(a,b,c,d){a=Z.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");0<b&&d?(b=D(a,C,d,b),c&&(G[c>>2]=b)):c&&(G[c>>2]=0)},I:function(a,b,c){if(c)if(a>=jb)X(1281);else{var d=rb[a];if(d)if(35716==b)a=Z.getProgramInfoLog(T[a]),null===a&&(a="(unknown error)"),G[c>>2]=a.length+1;else if(35719==b)G[c>>2]=d.Hb;else if(35722==b){if(-1==d.Db){a=T[a];var e=Z.getProgramParameter(a,35721);for(b=d.Db=0;b<e;++b)d.Db=Math.max(d.Db,Z.getActiveAttrib(a,b).name.length+1)}G[c>>
2]=d.Db}else if(35381==b){if(-1==d.Eb)for(a=T[a],e=Z.getProgramParameter(a,35382),b=d.Eb=0;b<e;++b)d.Eb=Math.max(d.Eb,Z.getActiveUniformBlockName(a,b).length+1);G[c>>2]=d.Eb}else G[c>>2]=Z.getProgramParameter(T[a],b);else X(1282)}else X(1281)},$a:function(a,b,c,d){a=Z.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");0<b&&d?(b=D(a,C,d,b),c&&(G[c>>2]=b)):c&&(G[c>>2]=0)},X:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),G[c>>2]=a.length+1):35720==b?(a=Z.getShaderSource(V[a]),
G[c>>2]=null===a||0==a.length?0:a.length+1):G[c>>2]=Z.getShaderParameter(V[a],b):X(1281)},Ia:function(a){if(sb[a])return sb[a];switch(a){case 7939:var b=Z.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=Db(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||X(1280);b=Db(b);break;case 7938:b=Z.getParameter(Z.VERSION);b=2<=W.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Db(b);break;case 35724:b=Z.getParameter(Z.SHADING_LANGUAGE_VERSION);
c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Db(b);break;default:return X(1280),0}return sb[a]=b},j:function(a,b){b=B(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=rb[a]&&rb[a].Mb[b])&&0<=c&&c<a[0]?a[1]+c:-1},va:function(a){Z.linkProgram(T[a]);var b=T[a];a=rb[a]={Mb:{},Hb:0,Db:-1,Eb:-1};for(var c=a.Mb,d=Z.getProgramParameter(b,35718),
e=0;e<d;++e){var h=Z.getActiveUniform(b,e),l=h.name;a.Hb=Math.max(a.Hb,l.length+1);"]"==l.slice(-1)&&(l=l.slice(0,l.lastIndexOf("[")));var n=Z.getUniformLocation(b,l);if(n){var p=tb(U);c[l]=[h.size,p];U[p]=n;for(var r=1;r<h.size;++r)n=Z.getUniformLocation(b,l+"["+r+"]"),p=tb(U),U[p]=n}}},z:function(a,b){Z.polygonOffset(a,b)},m:function(a){Z.readBuffer(a)},xa:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},M:function(a,b,c,d,e){Z.renderbufferStorageMultisample(a,b,c,d,e)},qa:function(a,b,c,d){Z.scissor(a,
b,c,d)},bb:function(a,b,c,d){for(var e="",h=0;h<b;++h){var l=d?G[d+4*h>>2]:-1;e+=B(G[c+4*h>>2],0>l?void 0:l)}Z.shaderSource(V[a],e)},_:function(a,b,c){Z.stencilFunc(a,b,c)},G:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},r:function(a){Z.stencilMask(a)},Z:function(a,b,c){Z.stencilOp(a,b,c)},F:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},Aa:function(a,b,c,d,e,h,l,n,p){W.wb?Z.Bb?Z.texImage2D(a,b,c,d,e,h,l,n,p):0!=p?Z.texImage2D(a,b,c,d,e,h,l,n,Hb(n),p>>(Ib[n]|0)):Z.texImage2D(a,b,c,d,e,h,l,n,
null):Z.texImage2D(a,b,c,d,e,h,l,n,p?Gb(n,l,d,e,p):null)},ya:function(a,b,c,d,e,h,l,n,p,r){Z.Bb?Z.texImage3D(a,b,c,d,e,h,l,n,p,r):0!=r?Z.texImage3D(a,b,c,d,e,h,l,n,p,Hb(p),r>>(Ib[p]|0)):Z.texImage3D(a,b,c,d,e,h,l,n,p,null)},L:function(a,b,c){Z.texParameterf(a,b,c)},f:function(a,b,c){Z.texParameteri(a,b,c)},ga:function(a,b,c){if(W.wb)Z.uniform1fv(U[a],H,c>>2,b);else{if(256>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=H[c+4*e>>2];else d=H.subarray(c>>2,c+4*b>>2);Z.uniform1fv(U[a],d)}},y:function(a,b){Z.uniform1i(U[a],
b)},fa:function(a,b,c){if(W.wb)Z.uniform2fv(U[a],H,c>>2,2*b);else{if(256>=2*b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=H[c+4*e>>2],d[e+1]=H[c+(4*e+4)>>2];else d=H.subarray(c>>2,c+8*b>>2);Z.uniform2fv(U[a],d)}},da:function(a,b,c){if(W.wb)Z.uniform3fv(U[a],H,c>>2,3*b);else{if(256>=3*b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=H[c+4*e>>2],d[e+1]=H[c+(4*e+4)>>2],d[e+2]=H[c+(4*e+8)>>2];else d=H.subarray(c>>2,c+12*b>>2);Z.uniform3fv(U[a],d)}},ca:function(a,b,c){if(W.wb)Z.uniform4fv(U[a],H,c>>2,4*b);else{if(256>=
4*b)for(var d=Y[4*b-1],e=0;e<4*b;e+=4)d[e]=H[c+4*e>>2],d[e+1]=H[c+(4*e+4)>>2],d[e+2]=H[c+(4*e+8)>>2],d[e+3]=H[c+(4*e+12)>>2];else d=H.subarray(c>>2,c+16*b>>2);Z.uniform4fv(U[a],d)}},ba:function(a,b,c,d){if(W.wb)Z.uniformMatrix4fv(U[a],!!c,H,d>>2,16*b);else{if(256>=16*b)for(var e=Y[16*b-1],h=0;h<16*b;h+=16)e[h]=H[d+4*h>>2],e[h+1]=H[d+(4*h+4)>>2],e[h+2]=H[d+(4*h+8)>>2],e[h+3]=H[d+(4*h+12)>>2],e[h+4]=H[d+(4*h+16)>>2],e[h+5]=H[d+(4*h+20)>>2],e[h+6]=H[d+(4*h+24)>>2],e[h+7]=H[d+(4*h+28)>>2],e[h+8]=H[d+
(4*h+32)>>2],e[h+9]=H[d+(4*h+36)>>2],e[h+10]=H[d+(4*h+40)>>2],e[h+11]=H[d+(4*h+44)>>2],e[h+12]=H[d+(4*h+48)>>2],e[h+13]=H[d+(4*h+52)>>2],e[h+14]=H[d+(4*h+56)>>2],e[h+15]=H[d+(4*h+60)>>2];else e=H.subarray(d>>2,d+64*b>>2);Z.uniformMatrix4fv(U[a],!!c,e)}},ka:function(a){Z.useProgram(T[a])},ia:function(a,b){Z.vertexAttribDivisor(a,b)},ja:function(a,b,c,d,e,h){Z.vertexAttribPointer(a,b,c,!!d,e,h)},ra:function(a,b,c,d){Z.viewport(a,b,c,d)},q:function(){var a=document.createElement("input");a.type="text";
a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Ob()});document.body.append(a)},p:function(){document.getElementById("_sokol_app_input_element").focus()},Ja:function(){window.addEventListener("beforeunload",function(a){0!=Pb()&&(a.preventDefault(),a.returnValue=" ")})},o:function(){document.getElementById("_sokol_app_input_element").blur()},h:function(a){a|=0;var b=E.length|0;var c=G[73164]|0;var d=c+a|0;if(0<(a|0)&(d|0)<(c|0)|0>(d|0))return w("OOM"),
0,Jb(),-1;if(a=(d|0)>(b|0)){a=d|0;if(2147418112<a)a=!1;else{for(b=Math.max(E.length,16777216);b<a;)536870912>=b?b=na(2*b):b=Math.min(na((3*b+2147483648)/4),2147418112);Kb(b)?(qa(),a=!0):a=!1}a=!(a|0)}if(a)return Jb(),-1;G[73164]=d|0;return c|0},x:function(a,b,c,d,e,h){b=B(b);var l=new XMLHttpRequest;l.open("GET",b);l.responseType="arraybuffer";var n=0<d;n&&l.setRequestHeader("Range","bytes="+c+"-"+(c+d));l.onreadystatechange=function(){if(this.readyState==this.DONE)if(206==this.status||200==this.status&&
!n){var b=new Uint8Array(l.response),c=b.length;c<=h?(C.set(b,e),Qb(a,d,c)):Rb(a)}else Sb(a,this.status)};l.send()},db:function(a,b){b=B(b);var c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(this.readyState==this.DONE)if(200==this.status){var b=this.getResponseHeader("Content-Length");Tb(a,b)}else Sb(a,this.status)};c.send()},Ya:Aa},buffer);f.asm=Ub;
var Ja=f.___wasm_call_ctors=function(){return f.asm.gb.apply(null,arguments)},Ob=f.__sapp_emsc_notify_keyboard_hidden=function(){return f.asm.hb.apply(null,arguments)},Pb=f.__sapp_html5_get_ask_leave_site=function(){return f.asm.ib.apply(null,arguments)};f._main=function(){return f.asm.jb.apply(null,arguments)};var Q=f._malloc=function(){return f.asm.kb.apply(null,arguments)};f._free=function(){return f.asm.lb.apply(null,arguments)};f.__saudio_emsc_pull=function(){return f.asm.mb.apply(null,arguments)};
var Tb=f.__sfetch_emsc_head_response=function(){return f.asm.nb.apply(null,arguments)},Qb=f.__sfetch_emsc_get_response=function(){return f.asm.ob.apply(null,arguments)},Sb=f.__sfetch_emsc_failed_http_status=function(){return f.asm.pb.apply(null,arguments)},Rb=f.__sfetch_emsc_failed_buffer_too_small=function(){return f.asm.qb.apply(null,arguments)},ma=f.stackAlloc=function(){return f.asm.rb.apply(null,arguments)};f.dynCall_vi=function(){return f.asm.sb.apply(null,arguments)};
f.dynCall_v=function(){return f.asm.tb.apply(null,arguments)};var R=f.dynCall_iiii=function(){return f.asm.ub.apply(null,arguments)},Nb=f.dynCall_idi=function(){return f.asm.vb.apply(null,arguments)};f.asm=Ub;function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}x.prototype=Error();x.prototype.constructor=x;K=function Vb(){f.calledRun||Wb();f.calledRun||(K=Vb)};
f.callMain=function(a){a=a||[];var b=a.length+1,c=ma(4*(b+1));G[c>>2]=la(f.thisProgram);for(var d=1;d<b;d++)G[(c>>2)+d]=la(a[d-1]);G[(c>>2)+b]=0;try{var e=f._main(b,c);if(!f.noExitRuntime||0!==e){if(!f.noExitRuntime&&(ia=!0,f.onExit))f.onExit(e);f.quit(e,new x(e))}}catch(h){h instanceof x||("SimulateInfiniteLoop"==h?f.noExitRuntime=!0:((a=h)&&"object"===typeof h&&h.stack&&(a=[h,h.stack]),z("exception thrown: "+a),f.quit(1,h)))}finally{}};
function Wb(a){function b(){if(!f.calledRun&&(f.calledRun=!0,!ia)){sa(ua);sa(va);if(f.onRuntimeInitialized)f.onRuntimeInitialized();f._main&&Xb&&f.callMain(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();xa.unshift(b)}sa(xa)}}a=a||f.arguments;if(!(0<J)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ya();sa(ta);0<J||f.calledRun||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},
1);b()},1)):b())}}f.run=Wb;function w(a){if(f.onAbort)f.onAbort(a);ha(a);z(a);ia=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}f.abort=w;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Xb=!0;f.noInitialRun&&(Xb=!1);f.noExitRuntime=!0;Wb();
