var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,l="undefined"!=typeof WorkerGlobalScope,ba="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,ca={...e},da=[],m="./this.program",ea=(a,b)=>{throw b;},n="",fa,q;
if(ba){var fs=require("fs");require("path");n=__dirname+"/";q=a=>{a=t(a)?new URL(a):a;return fs.readFileSync(a)};fa=async a=>{a=t(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!e.thisProgram&&1<process.argv.length&&(m=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);ea=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||l)l?n=self.location.href:"undefined"!=typeof document&&document.currentScript&&(n=document.currentScript.src),n=n.startsWith("blob:")?
"":n.slice(0,n.replace(/[?#].*/,"").lastIndexOf("/")+1),l&&(q=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),fa=async a=>{if(t(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var ha=e.print||console.log.bind(console),u=e.printErr||console.error.bind(console);Object.assign(e,ca);ca=null;e.arguments&&(da=e.arguments);e.thisProgram&&(m=e.thisProgram);var v=e.wasmBinary,w,y=!1,ia,A,B,ja,C,D,ka,E,t=a=>a.startsWith("file://");
function la(){var a=w.buffer;e.HEAP8=A=new Int8Array(a);e.HEAP16=ja=new Int16Array(a);e.HEAPU8=B=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAP32=C=new Int32Array(a);e.HEAPU32=D=new Uint32Array(a);e.HEAPF32=ka=new Float32Array(a);e.HEAPF64=E=new Float64Array(a);e.HEAP64=new BigInt64Array(a);e.HEAPU64=new BigUint64Array(a)}var F=0,G=null;function ma(a){e.onAbort?.(a);a="Aborted("+a+")";u(a);y=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var na;
async function oa(a){if(!v)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==na&&v)a=new Uint8Array(v);else if(q)a=q(a);else throw"both async and sync fetching of the wasm failed";return a}async function pa(a,b){try{var c=await oa(a);return await WebAssembly.instantiate(c,b)}catch(d){u(`failed to asynchronously prepare wasm: ${d}`),ma(d)}}
async function qa(a){var b=na;if(!v&&"function"==typeof WebAssembly.instantiateStreaming&&!t(b)&&!ba)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){u(`wasm streaming compile failed: ${d}`),u("falling back to ArrayBuffer instantiation")}return pa(b,a)}class ra{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var sa=a=>{for(;0<a.length;)a.shift()(e)},ta=[],ua=[],va=()=>{var a=e.preRun.shift();ua.unshift(a)},wa=e.noExitRuntime||!0,xa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,I=(a,b=0)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&xa)return xa.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):
(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},ya=0,J={},za=a=>{a instanceof ra||"unwind"==a||ea(1,a)},Aa=a=>{ia=a;wa||0<ya||(e.onExit?.(a),y=!0);ea(a,new ra(a))},Ba=a=>{ia=a;Aa(a)},Ca=()=>{if(!(wa||0<ya))try{var a=ia;ia=a;Aa(a)}catch(b){za(b)}},Da=a=>{if(!y)try{a(),Ca()}catch(b){za(b)}},Ka=(a,b)=>{Ea=a;Fa=b;if(K)if(Ga||=!0,0==a)L=function(){setTimeout(M,Math.max(0,Ha+b-performance.now())|0)};else if(1==a)L=function(){Ia(M)};else if(2==a){if("undefined"==
typeof Ja)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ja=d=>{c.push(d);if(l){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ja=setImmediate;L=function(){Ja(M)}}},Ta=(a,b,c,d,f)=>{function g(){return h<La?(Ca(),!1):!0}K=a;Ma=d;var h=La;Ga=!1;M=function(){if(!y)if(0<Na.length){var k=
Na.shift();k.sc(k.fc);if(Oa){var p=Oa,r=0==p%1?p-1:Math.floor(p);Oa=k.ic?r:(8*p+(r+.5))/9}e.setStatus&&(k=e.statusMessage||"Please wait...",p=Oa??0,r=Pa.oc??0,p?p<r?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(k):e.setStatus(""));g()&&setTimeout(M,0)}else if(g())if(Qa=Qa+1|0,1==Ea&&1<Fa&&0!=Qa%Fa)L();else{0==Ea&&(Ha=performance.now());a:if(!y){for(k of Ra)if(!1===k())break a;Da(a);for(p of Sa)p()}g()&&L()}};f||(0<b?Ka(0,1E3/b):Ka(1,1),L());if(c)throw"unwind";},Ga=!1,L=
null,La=0,K=null,Ma=0,Ea=0,Fa=0,Qa=0,Na=[],Ra=[],Sa=[];function Ua(){L=null;La++}var N=0;function Ia(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===N)N=b+1E3/60;else for(;b+2>=N;)N+=1E3/60;setTimeout(a,Math.max(N-b,0))}}
var Pa={},Ha,M,Ja,Oa,Va=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],O=a=>{a=2<a?a?I(B,a):"":a;return Va[a]||("undefined"!=typeof document?document.querySelector(a):null)},Wa=a=>0>Va.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Xa=[],Ya,P=a=>{var b=Xa[a];b||(Xa[a]=b=Ya.get(a));return b};function Za(a){var b=Q.rb[a];b.target.removeEventListener(b.qb,b.Pb,b.sb);Q.rb.splice(a,1)}
function $a(){if(navigator.userActivation?navigator.userActivation.isActive:Q.Cb&&Q.bc.Ab){var a=Q.wb;Q.wb=[];for(var b of a)b.Fb(...b.Kb)}}function R(a){if(!a.target)return-4;if(a.tb)a.Pb=function(c){++Q.Cb;Q.bc=a;$a();a.ub(c);$a();--Q.Cb},a.target.addEventListener(a.qb,a.Pb,a.sb),Q.rb.push(a);else for(var b=0;b<Q.rb.length;++b)Q.rb[b].target==a.target&&Q.rb[b].qb==a.qb&&Za(b--);return 0}function ab(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var Q={hc:0,tc:0,Db:0,zb:0,Ib:0,Hb:0,Bb:0,mc:0,yc:0,lc:0,rc:0,Eb:0,Hc:0,Gb:0,vc(a,b,c){A.set(A.subarray(b,b+c),a)},Ac(){for(;Q.rb.length;)Za(Q.rb.length-1);Q.wb=[]},Cb:0,wb:[],kc(a,b,c){function d(g,h){if(g.length!=h.length)return!1;for(var k in g)if(g[k]!=h[k])return!1;return!0}for(var f of Q.wb)if(f.Fb==a&&d(f.Kb,c))return;Q.wb.push({Fb:a,Tb:b,Kb:c});Q.wb.sort((g,h)=>g.Tb<h.Tb)},Cc(a){Q.wb=Q.wb.filter(b=>b.Fb!=a)},rb:[],Bc:(a,b)=>{for(var c=0;c<Q.rb.length;++c)Q.rb[c].target!=a||b&&b!=Q.rb[c].qb||
Za(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},S=(a,b,c)=>{var d=B;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}},bb=
(a,b,c,d,f,g)=>{Q.Bb||(Q.Bb=T(256));a={target:O(a),qb:g,tb:d,ub:(h=event)=>{var k=h.target.id?h.target.id:"",p=Q.Bb;S(ab(h.target),p+0,128);S(k,p+128,128);P(d)(f,p,b)&&h.preventDefault()},sb:c};return R(a)},cb=(a,b,c,d,f,g)=>{Q.Db||(Q.Db=T(160));a={target:O(a),qb:g,tb:d,ub:h=>{var k=Q.Db;E[k>>3]=h.timeStamp;var p=k>>2;C[p+2]=h.location;A[k+12]=h.ctrlKey;A[k+13]=h.shiftKey;A[k+14]=h.altKey;A[k+15]=h.metaKey;A[k+16]=h.repeat;C[p+5]=h.charCode;C[p+6]=h.keyCode;C[p+7]=h.which;S(h.key||"",k+32,32);S(h.code||
"",k+64,32);S(h.char||"",k+96,32);S(h.locale||"",k+128,32);P(d)(f,k,b)&&h.preventDefault()},sb:c};return R(a)},db=(a,b,c)=>{E[a>>3]=b.timeStamp;var d=a>>2;C[d+2]=b.screenX;C[d+3]=b.screenY;C[d+4]=b.clientX;C[d+5]=b.clientY;A[a+24]=b.ctrlKey;A[a+25]=b.shiftKey;A[a+26]=b.altKey;A[a+27]=b.metaKey;ja[2*d+14]=b.button;ja[2*d+15]=b.buttons;C[d+8]=b.movementX;C[d+9]=b.movementY;a=Wa(c);C[d+10]=b.clientX-(a.left|0);C[d+11]=b.clientY-(a.top|0)},U=(a,b,c,d,f,g)=>{Q.zb||(Q.zb=T(64));a=O(a);return R({target:a,
Ab:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,qb:g,tb:d,ub:(h=event)=>{db(Q.zb,h,a);P(d)(f,Q.zb,b)&&h.preventDefault()},sb:c})},eb=(a,b,c,d,f)=>{Q.Eb||(Q.Eb=T(257));return R({target:a,qb:f,tb:d,ub:(g=event)=>{var h=Q.Eb,k=document.pointerLockElement||document.yb||document.Vb||document.Ub;A[h]=!!k;var p=k?.id||"";S(ab(k),h+1,128);S(p,h+129,128);P(d)(20,h,b)&&g.preventDefault()},sb:c})},fb=(a,b,c,d,f)=>R({target:a,qb:f,tb:d,ub:(g=event)=>{P(d)(38,0,b)&&g.preventDefault()},sb:c}),gb=(a,b,c,d)=>
{Q.Hb||(Q.Hb=T(36));a=O(a);return R({target:a,qb:"resize",tb:d,ub:(f=event)=>{if(f.target==a){var g=document.body;if(g){var h=Q.Hb;C[h>>2]=0;C[h+4>>2]=g.clientWidth;C[h+8>>2]=g.clientHeight;C[h+12>>2]=innerWidth;C[h+16>>2]=innerHeight;C[h+20>>2]=outerWidth;C[h+24>>2]=outerHeight;C[h+28>>2]=pageXOffset|0;C[h+32>>2]=pageYOffset|0;P(d)(10,h,b)&&f.preventDefault()}}},sb:c})},hb=(a,b,c,d,f,g)=>{Q.Gb||(Q.Gb=T(1552));a=O(a);return R({target:a,Ab:"touchstart"==g||"touchend"==g,qb:g,tb:d,ub:h=>{var k={},p=
h.touches;for(var r of p)r.Qb=r.Sb=0,k[r.identifier]=r;for(var z of h.changedTouches)z.Qb=1,k[z.identifier]=z;for(var H of h.targetTouches)k[H.identifier].Sb=1;p=Q.Gb;E[p>>3]=h.timeStamp;A[p+12]=h.ctrlKey;A[p+13]=h.shiftKey;A[p+14]=h.altKey;A[p+15]=h.metaKey;r=p+16;z=Wa(a);H=0;for(let x of Object.values(k))if(k=r>>2,C[k]=x.identifier,C[k+1]=x.screenX,C[k+2]=x.screenY,C[k+3]=x.clientX,C[k+4]=x.clientY,C[k+5]=x.pageX,C[k+6]=x.pageY,A[r+28]=x.Qb,A[r+29]=x.Sb,C[k+8]=x.clientX-(z.left|0),C[k+9]=x.clientY-
(z.top|0),r+=48,31<++H)break;C[p+8>>2]=H;P(d)(f,p,b)&&h.preventDefault()},sb:c})},V,ib=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,f,g)=>b.drawArraysInstancedANGLE(c,d,f,g),a.drawElementsInstanced=(c,d,f,g,h)=>b.drawElementsInstancedANGLE(c,d,f,g,h))},jb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},kb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},lb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},mb=1,nb=[],ob=[],pb=[],qb=[],rb=[],W=[],sb=[],tb=[],ub={},vb=a=>{for(var b=mb++,c=a.length;c<b;c++)a[c]=null;return b},xb=(a,b)=>{a.yb||(a.yb=a.getContext,a.getContext=function(d,f){f=a.yb(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=1<b.Rb?a.getContext("webgl2",b):a.getContext("webgl",b);return c?wb(c,b):0},wb=(a,b)=>{var c=vb(sb),d={handle:c,attributes:b,version:b.Rb,Jb:a};a.canvas&&(a.canvas.ec=d);sb[c]=
d;("undefined"==typeof b.Ob||b.Ob)&&yb(d);return c},yb=a=>{a||=X;if(!a.dc){a.dc=!0;var b=a.Jb;b.xc=b.getExtension("WEBGL_multi_draw");b.qc=b.getExtension("EXT_polygon_offset_clamp");b.pc=b.getExtension("EXT_clip_control");b.Ic=b.getExtension("WEBGL_polygon_mode");ib(b);jb(b);kb(b);b.nc=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.uc=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Nb=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>
a.version||!b.Nb)b.Nb=b.getExtension("EXT_disjoint_timer_query");lb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},Y,X,zb=(a,b,c,d,f,g)=>{a={target:O(a),qb:g,tb:d,ub:(h=event)=>{P(d)(f,0,b)&&h.preventDefault()},sb:c};R(a)},Ab=(a,b,c,d)=>{Q.Ib||(Q.Ib=T(96));return R({target:a,Ab:!0,qb:"wheel",tb:d,ub:(f=event)=>{var g=Q.Ib;db(g,f,a);E[g+64>>3]=f.deltaX;E[g+72>>3]=f.deltaY;E[g+80>>3]=f.deltaZ;C[g+88>>2]=f.deltaMode;P(d)(9,g,b)&&f.preventDefault()},sb:c})},Bb=["default",
"low-power","high-performance"],Cb={},Eb=()=>{if(!Db){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:m||"./this.program"},b;for(b in Cb)void 0===Cb[b]?delete a[b]:a[b]=Cb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Db=c}return Db},Db,Fb=[null,[],[]],Gb=()=>{var a=lb(V);return a=a.concat(a.map(b=>"GL_"+b))},Hb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=
1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=V.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>X.version){Y||=1282;return}c=Gb().length;break;case 33307:case 33308:if(2>X.version){Y||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=V.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:Y||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)C[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){Y||=1280;u(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:Y||=1280;u(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}C[b>>2]=c}else Y||=1281},Ib=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Jb=a=>{var b=Ib(a)+1,c=T(b);c&&S(a,c,b);return c},Kb=[],Mb=a=>{var b=Ib(a)+1,c=Lb(b);S(a,c,b);return c},Pb=a=>{var b=Nb();a();Ob(b)};e.requestAnimationFrame=Ia;e.pauseMainLoop=Ua;e.resumeMainLoop=function(){La++;var a=Ea,b=Fa,c=K;K=null;Ta(c,0,!1,Ma,!0);Ka(a,b);L()};e.preMainLoop&&Ra.push(e.preMainLoop);e.postMainLoop&&Sa.push(e.postMainLoop);for(let a=0;32>a;++a)Kb.push(Array(a));
var Xb={o:function(){return 0},_:function(){return 0},aa:function(){},ca:()=>ma(""),Ta:()=>{wa=!1;ya=0},T:(a,b)=>{J[a]&&(clearTimeout(J[a].id),delete J[a]);if(!b)return 0;var c=setTimeout(()=>{delete J[a];Da(()=>Qb(a,performance.now()))},b);J[a]={id:c,Gc:b};return 0},Ga:()=>{Ua();K=null},ba:()=>Date.now(),O:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,Q:(a,b,c)=>{a=O(a);if(!a)return-4;a=Wa(a);E[b>>3]=a.width;E[c>>3]=a.height;return 0},m:()=>performance.now(),Ha:()=>performance.now(),
Ma:(a,b)=>{function c(d){P(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},U:a=>{var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-w.buffer.byteLength+65535)/65536|0;try{w.grow(d);la();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},w:(a,b,c,d)=>bb(a,b,c,d,12,"blur"),N:(a,b,c)=>{a=O(a);if(!a)return-4;a.width=b;a.height=c;return 0},x:(a,b,c,d)=>
bb(a,b,c,d,13,"focus"),G:(a,b,c,d)=>cb(a,b,c,d,2,"keydown"),E:(a,b,c,d)=>cb(a,b,c,d,1,"keypress"),F:(a,b,c,d)=>cb(a,b,c,d,3,"keyup"),Na:(a,b,c)=>{a=P(a);Ta(a,b,c)},M:(a,b,c,d)=>U(a,b,c,d,5,"mousedown"),J:(a,b,c,d)=>U(a,b,c,d,33,"mouseenter"),I:(a,b,c,d)=>U(a,b,c,d,34,"mouseleave"),K:(a,b,c,d)=>U(a,b,c,d,8,"mousemove"),L:(a,b,c,d)=>U(a,b,c,d,6,"mouseup"),z:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.yb||document.body.Vb||document.body.Ub))return-1;a=
O(a);if(!a)return-4;eb(a,b,c,d,"mozpointerlockchange");eb(a,b,c,d,"webkitpointerlockchange");eb(a,b,c,d,"mspointerlockchange");return eb(a,b,c,d,"pointerlockchange")},y:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.yb||document.body.Vb||document.body.Ub))return-1;a=O(a);if(!a)return-4;fb(a,b,c,d,"mozpointerlockerror");fb(a,b,c,d,"webkitpointerlockerror");fb(a,b,c,d,"mspointerlockerror");return fb(a,b,c,d,"pointerlockerror")},P:(a,b,c,d)=>gb(a,b,c,d),A:(a,b,c,d)=>hb(a,
b,c,d,25,"touchcancel"),B:(a,b,c,d)=>hb(a,b,c,d,23,"touchend"),C:(a,b,c,d)=>hb(a,b,c,d,24,"touchmove"),D:(a,b,c,d)=>hb(a,b,c,d,22,"touchstart"),v:(a,b,c,d)=>{zb(a,b,c,d,31,"webglcontextlost");return 0},u:(a,b,c,d)=>{zb(a,b,c,d,32,"webglcontextrestored");return 0},H:(a,b,c,d)=>(a=O(a))?"undefined"!=typeof a.onwheel?Ab(a,b,c,d):-1:-4,La:(a,b)=>{var c=b>>2;b={alpha:!!A[b+0],depth:!!A[b+1],stencil:!!A[b+2],antialias:!!A[b+3],premultipliedAlpha:!!A[b+4],preserveDrawingBuffer:!!A[b+5],powerPreference:Bb[C[c+
2]],failIfMajorPerformanceCaveat:!!A[b+12],Rb:C[c+4],wc:C[c+5],Ob:A[b+24],cc:A[b+25],zc:C[c+7],Dc:A[b+32]};a=O(a);return!a||b.cc?0:xb(a,b)},Ka:a=>{X=sb[a];e.ctx=V=X?.Jb;return!a||V?0:-5},W:(a,b)=>{var c=0;Eb().forEach((d,f)=>{var g=b+c;f=D[a+4*f>>2]=g;for(g=0;g<d.length;++g)A[f++]=d.charCodeAt(g);A[f]=0;c+=d.length+1});return 0},X:(a,b)=>{var c=Eb();D[a>>2]=c.length;var d=0;c.forEach(f=>d+=f.length+1);D[b>>2]=d;return 0},n:()=>52,Z:()=>52,V:function(){return 70},Y:(a,b,c,d)=>{for(var f=0,g=0;g<c;g++){var h=
D[b>>2],k=D[b+4>>2];b+=8;for(var p=0;p<k;p++){var r=a,z=B[h+p],H=Fb[r];0===z||10===z?((1===r?ha:u)(I(H)),H.length=0):H.push(z)}f+=k}D[d>>2]=f;return 0},i:a=>V.activeTexture(a),d:(a,b)=>{35051==a?V.Lb=b:35052==a&&(V.Mb=b);V.bindBuffer(a,nb[b])},a:(a,b,c)=>{V.bindBufferBase(a,b,nb[c])},g:(a,b)=>{V.bindFramebuffer(a,pb[b])},h:(a,b)=>{V.bindSampler(a,tb[b])},c:(a,b)=>{V.bindTexture(a,rb[b])},t:a=>{V.bindVertexArray(W[a])},va:(a,b,c,d)=>V.blendColor(a,b,c,d),xa:(a,b)=>V.blendEquationSeparate(a,b),ya:(a,
b,c,d)=>V.blendFuncSeparate(a,b,c,d),ea:(a,b,c,d,f,g,h,k,p,r)=>V.blitFramebuffer(a,b,c,d,f,g,h,k,p,r),ha:(a,b,c,d)=>V.clearBufferfi(a,b,c,d),p:(a,b,c)=>{V.clearBufferfv(a,b,ka,c>>2)},ga:(a,b,c)=>{V.clearBufferiv(a,b,C,c>>2)},j:(a,b,c,d)=>{V.colorMask(!!a,!!b,!!c,!!d)},sa:a=>V.cullFace(a),ra:(a,b)=>{for(var c=0;c<a;c++){var d=C[b+4*c>>2],f=nb[d];f&&(V.deleteBuffer(f),f.name=0,nb[d]=null,d==V.Lb&&(V.Lb=0),d==V.Mb&&(V.Mb=0))}},f:(a,b)=>{for(var c=0;c<a;++c){var d=C[b+4*c>>2],f=pb[d];f&&(V.deleteFramebuffer(f),
f.name=0,pb[d]=null)}},na:a=>{if(a){var b=ob[a];b?(V.deleteProgram(b),b.name=0,ob[a]=null):Y||=1281}},pa:(a,b)=>{for(var c=0;c<a;c++){var d=C[b+4*c>>2],f=qb[d];f&&(V.deleteRenderbuffer(f),f.name=0,qb[d]=null)}},oa:(a,b)=>{for(var c=0;c<a;c++){var d=C[b+4*c>>2],f=tb[d];f&&(V.deleteSampler(f),f.name=0,tb[d]=null)}},qa:(a,b)=>{for(var c=0;c<a;c++){var d=C[b+4*c>>2],f=rb[d];f&&(V.deleteTexture(f),f.name=0,rb[d]=null)}},la:(a,b)=>{for(var c=0;c<a;c++){var d=C[b+4*c>>2];V.deleteVertexArray(W[d]);W[d]=null}},
s:a=>V.depthFunc(a),r:a=>{V.depthMask(!!a)},e:a=>V.disable(a),Ba:a=>{V.disableVertexAttribArray(a)},l:a=>V.enable(a),ta:a=>V.frontFace(a),Fa:(a,b)=>{for(var c=0;c<a;c++){var d=V.createVertexArray(),f=d&&vb(W);d?(d.name=f,W[f]=d):Y||=1282;C[b+4*c>>2]=f}},b:(a,b)=>Hb(a,b),Da:(a,b)=>{if(2>X.version)return Y||=1282,0;var c=ub[a];if(c)return 0>b||b>=c.length?(Y||=1281,0):c[b];switch(a){case 7939:return c=Gb().map(Jb),c=ub[a]=c,0>b||b>=c.length?(Y||=1281,0):c[b];default:return Y||=1280,0}},da:(a,b,c)=>
{for(var d=Kb[b],f=0;f<b;f++)d[f]=C[c+4*f>>2];V.invalidateFramebuffer(a,d)},Ea:(a,b)=>{V.pixelStorei(a,b)},ua:(a,b)=>V.polygonOffset(a,b),fa:a=>V.readBuffer(a),ia:(a,b,c,d)=>V.scissor(a,b,c,d),Aa:(a,b,c)=>V.stencilFunc(a,b,c),q:a=>V.stencilMask(a),za:(a,b,c)=>V.stencilOp(a,b,c),ma:a=>{a=ob[a];V.useProgram(a);V.jc=a},ka:(a,b,c,d)=>V.viewport(a,b,c,d),Sa:Aa,Va:function(){e.Wb=a=>{0!=Rb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Wb)},Oa:function(){e.ac=a=>{const b=
a.clipboardData.getData("text");Pb(()=>{const c=Mb(b);Sb(c)})};window.addEventListener("paste",e.ac)},Ia:function(){e.Ec=[];e.Xb=b=>{b.stopPropagation();b.preventDefault()};e.Yb=b=>{b.stopPropagation();b.preventDefault()};e.Zb=b=>{b.stopPropagation();b.preventDefault()};e.$b=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.Fc=c;Tb(c.length);for(let f=0;f<c.length;f++)Pb(()=>{const g=Mb(c[f].name);Ub(f,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&
(d|=8);Vb(b.clientX,b.clientY,d)};const a=e.xb;a.addEventListener("dragenter",e.Xb,!1);a.addEventListener("dragleave",e.Yb,!1);a.addEventListener("dragover",e.Zb,!1);a.addEventListener("drop",e.$b,!1)},ja:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},wa:function(a,b){0!==b&&(document.title=b?I(B,b):"");a=a?I(B,a):"";void 0!==e.canvas&&("object"===typeof e.canvas?Va[a]=e.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
e.xb=O(a);e.xb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);e.xb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ua:function(){window.removeEventListener("beforeunload",e.Wb)},Ja:function(){window.removeEventListener("paste",e.ac)},Ca:function(){const a=e.xb;a.removeEventListener("dragenter",e.Xb);a.removeEventListener("dragleave",e.Yb);a.removeEventListener("dragover",e.Zb);a.removeEventListener("drop",e.$b)},k:function(){e.xb&&
e.xb.requestPointerLock&&e.xb.requestPointerLock()},$:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),g=f.createImageData(a,b);g.data.set(B.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Pa:function(){return e.vb?e.vb.bufferSize:0},Ra:function(a,b,c){e.pb=null;e.vb=null;"undefined"!==typeof AudioContext?e.pb=new AudioContext({sampleRate:a,
latencyHint:"interactive"}):(e.pb=null,console.log("sokol_audio.h: no WebAudio support"));return e.pb?(console.log("sokol_audio.h: sample rate ",e.pb.sampleRate),e.vb=e.pb.createScriptProcessor(c,0,b),e.vb.onaudioprocess=d=>{const f=d.outputBuffer.length,g=Wb(f);if(g){const h=d.outputBuffer.numberOfChannels;for(let k=0;k<h;k++){const p=d.outputBuffer.getChannelData(k);for(let r=0;r<f;r++)p[r]=ka[(g>>2)+(h*r+k)]}}},e.vb.connect(e.pb.destination),a=()=>{e.pb&&"suspended"===e.pb.state&&e.pb.resume()},
document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},Qa:function(){return e.pb?e.pb.sampleRate:0},S:function(){const a=e.pb;null!==a&&(e.vb&&e.vb.disconnect(),a.close(),e.pb=null,e.vb=null)},R:function(a,b){b=b?I(B,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;w=Z.Wa;la();Ya=Z.kb;F--;e.monitorRunDependencies?.(F);0==F&&G&&(c=G,G=null,c());return Z}F++;e.monitorRunDependencies?.(F);var b={a:Xb};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{a(d,f);c(d.exports)})});na??=e.locateFile?e.locateFile("modplay-sapp.wasm",n):n+"modplay-sapp.wasm";return a((await qa(b)).instance)})();
var Sb=e.__sapp_emsc_onpaste=a=>(Sb=e.__sapp_emsc_onpaste=Z.Ya)(a),Rb=e.__sapp_html5_get_ask_leave_site=()=>(Rb=e.__sapp_html5_get_ask_leave_site=Z.Za)(),Tb=e.__sapp_emsc_begin_drop=a=>(Tb=e.__sapp_emsc_begin_drop=Z._a)(a),Ub=e.__sapp_emsc_drop=(a,b)=>(Ub=e.__sapp_emsc_drop=Z.$a)(a,b),Vb=e.__sapp_emsc_end_drop=(a,b,c)=>(Vb=e.__sapp_emsc_end_drop=Z.ab)(a,b,c);e.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,f,g,h,k)=>(e.__sapp_emsc_invoke_fetch_cb=Z.bb)(a,b,c,d,f,g,h,k);
var Yb=e._main=(a,b)=>(Yb=e._main=Z.cb)(a,b),Wb=e.__saudio_emsc_pull=a=>(Wb=e.__saudio_emsc_pull=Z.db)(a);e.__sfetch_emsc_head_response=(a,b)=>(e.__sfetch_emsc_head_response=Z.eb)(a,b);e.__sfetch_emsc_get_response=(a,b,c)=>(e.__sfetch_emsc_get_response=Z.fb)(a,b,c);e.__sfetch_emsc_failed_http_status=(a,b)=>(e.__sfetch_emsc_failed_http_status=Z.gb)(a,b);e.__sfetch_emsc_failed_buffer_too_small=a=>(e.__sfetch_emsc_failed_buffer_too_small=Z.hb)(a);
e.__sfetch_emsc_failed_other=a=>(e.__sfetch_emsc_failed_other=Z.ib)(a);var T=a=>(T=Z.jb)(a),Qb=(a,b)=>(Qb=Z.lb)(a,b),Ob=a=>(Ob=Z.mb)(a),Lb=a=>(Lb=Z.nb)(a),Nb=()=>(Nb=Z.ob)();function Zb(a=[]){var b=Yb;a.unshift(m);var c=a.length,d=Lb(4*(c+1)),f=d;a.forEach(h=>{D[f>>2]=Mb(h);f+=4});D[f>>2]=0;try{var g=b(c,d);Ba(g)}catch(h){za(h)}}
function $b(a=da){function b(){e.calledRun=!0;if(!y){Z.Xa();e.onRuntimeInitialized?.();e.noInitialRun||Zb(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();ta.unshift(c)}sa(ta)}}if(0<F)G=$b;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)va();sa(ua);0<F?G=$b:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b()}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();$b();
