var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,k="function"==typeof importScripts,ba="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ca=Object.assign({},e),da=[],m="./this.program",ea=(a,b)=>{throw b;},p="",fa,ha;
if(ba){var fs=require("fs"),ia=require("path");p=__dirname+"/";ha=a=>{a=ja(a)?new URL(a):ia.normalize(a);return fs.readFileSync(a)};fa=a=>{a=ja(a)?new URL(a):ia.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,f)=>{d?c(d):b(f.buffer)})})};!e.thisProgram&&1<process.argv.length&&(m=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);ea=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||k)k?p=self.location.href:"undefined"!=typeof document&&
document.currentScript&&(p=document.currentScript.src),p=p.startsWith("blob:")?"":p.substr(0,p.replace(/[?#].*/,"").lastIndexOf("/")+1),k&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),fa=a=>ja(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var ka=e.print||console.log.bind(console),r=e.printErr||console.error.bind(console);Object.assign(e,ca);ca=null;e.arguments&&(da=e.arguments);e.thisProgram&&(m=e.thisProgram);var la=e.wasmBinary,ma,t=!1,na,u,v,oa,w,x,pa,z;
function ra(){var a=ma.buffer;e.HEAP8=u=new Int8Array(a);e.HEAP16=oa=new Int16Array(a);e.HEAPU8=v=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAP32=w=new Int32Array(a);e.HEAPU32=x=new Uint32Array(a);e.HEAPF32=pa=new Float32Array(a);e.HEAPF64=z=new Float64Array(a)}var sa=[],ta=[],ua=[],va=[];function wa(){var a=e.preRun.shift();sa.unshift(a)}var B=0,xa=null,C=null;
function ya(a){e.onAbort?.(a);a="Aborted("+a+")";r(a);t=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var za=a=>a.startsWith("data:application/octet-stream;base64,"),ja=a=>a.startsWith("file://"),Aa;function Ba(a){if(a==Aa&&la)return new Uint8Array(la);if(ha)return ha(a);throw"both async and sync fetching of the wasm failed";}function Ca(a){return la?Promise.resolve().then(()=>Ba(a)):fa(a).then(b=>new Uint8Array(b),()=>Ba(a))}
function Da(a,b,c){return Ca(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{r(`failed to asynchronously prepare wasm: ${d}`);ya(d)})}function Ea(a,b){var c=Aa;la||"function"!=typeof WebAssembly.instantiateStreaming||za(c)||ja(c)||ba||"function"!=typeof fetch?Da(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(f){r(`wasm streaming compile failed: ${f}`);r("falling back to ArrayBuffer instantiation");return Da(c,a,b)}))}
function Fa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ga=a=>{for(;0<a.length;)a.shift()(e)},Ha=e.noExitRuntime||!0,Ia="undefined"!=typeof TextDecoder?new TextDecoder:void 0,D=(a,b)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ia)return Ia.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|
f&1023))}}else c+=String.fromCharCode(f)}return c},E={},Ja=a=>{a instanceof Fa||"unwind"==a||ea(1,a)},Ka=0,La=a=>{na=a;Ha||0<Ka||(e.onExit?.(a),t=!0);ea(a,new Fa(a))},Ma=a=>{na=a;La(a)},Na=()=>{if(!(Ha||0<Ka))try{var a=na;na=a;La(a)}catch(b){Ja(b)}},Oa=a=>{if(!t)try{a(),Na()}catch(b){Ja(b)}},F;F=()=>performance.now();
var Va=(a,b)=>{Pa=a;Qa=b;if(G)if(Ra||=!0,0==a)H=function(){var d=Math.max(0,Sa+b-F())|0;setTimeout(I,d)};else if(1==a)H=function(){Ta(I)};else if(2==a){if("undefined"==typeof Ua)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ua=d=>{c.push(d);if(k){let f;(f=e).setImmediates??(f.setImmediates=[]);e.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate",
"*")}}else Ua=setImmediate;H=function(){Ua(I)}}},bb=(a,b,c,d,f)=>{function g(){return h<Wa?(Na(),!1):!0}G=a;Xa=d;var h=Wa;Ra=!1;I=function(){if(!t)if(0<Ya.length){var l=Ya.shift();l.fc(l.$b);if(Za){var n=Za,q=0==n%1?n-1:Math.floor(n);Za=l.bc?q:(8*n+(q+.5))/9}e.setStatus&&(l=e.statusMessage||"Please wait...",n=Za,q=$a.ec,n?n<q?e.setStatus("{message} ({expected - remaining}/{expected})"):e.setStatus(l):e.setStatus(""));g()&&setTimeout(I,0)}else g()&&(ab=ab+1|0,1==Pa&&1<Qa&&0!=ab%Qa?H():(0==Pa&&(Sa=
F()),t||e.preMainLoop&&!1===e.preMainLoop()||(Oa(a),e.postMainLoop?.()),g()&&("object"==typeof SDL&&SDL.audio?.kc?.(),H())))};f||(b&&0<b?Va(0,1E3/b):Va(1,1),H());if(c)throw"unwind";},Ra=!1,H=null,Wa=0,G=null,Xa=0,Pa=0,Qa=0,ab=0,Ya=[];function cb(){H=null;Wa++}var $a={},Sa,I,Za,J=!1,db=!1,eb=[];
function fb(){function a(){db=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}if(!gb){gb=!0;var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&b.addEventListener("click",c=>{!db&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),c.preventDefault())},!1))}}var hb=!1,ib=void 0,K=void 0;
function jb(){if(!J)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var L=0;function Ta(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===L)L=b+1E3/60;else for(;b+2>=L;)L+=1E3/60;setTimeout(a,Math.max(L-b,0))}}var kb=[];function lb(){var a=e.canvas;kb.forEach(b=>b(a.width,a.height))}
function M(a,b,c){b&&c?(a.Yb=b,a.Ub=c):(b=a.Yb,c=a.Ub);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*
g)}K?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Ua,gb,mb=0,nb=[];
function ob(){if(navigator.userActivation?navigator.userActivation.isActive:mb&&pb.zb){var a=nb;nb=[];for(var b of a)b.oc(...b.ac)}}var N=[];function qb(a){var b=N[a];b.target.removeEventListener(b.rb,b.Gb,b.sb);N.splice(a,1)}function O(a){if(!a.target)return-4;if(a.tb)a.Gb=function(c){++mb;pb=a;ob();a.ub(c);ob();--mb},a.target.addEventListener(a.rb,a.Gb,a.sb),N.push(a);else for(var b=0;b<N.length;++b)N[b].target==a.target&&N[b].rb==a.rb&&qb(b--);return 0}
function rb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var pb,sb,tb,ub,vb,wb,xb,yb,zb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],P=a=>{a=2<a?a?D(v,a):"":a;return zb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Ab=a=>0>zb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Bb=[],Cb,Q=a=>{var b=Bb[a];b||(a>=Bb.length&&(Bb.length=a+1),Bb[a]=b=Cb.get(a));return b},R=(a,b,c)=>{var d=v;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);
g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}},Db=(a,b,c,d,f,g)=>{sb||=S(256);a={target:P(a),rb:g,tb:d,ub:(h=event)=>{var l=h.target.id?h.target.id:"",n=sb;R(rb(h.target),n+0,128);R(l,n+128,128);Q(d)(f,n,b)&&h.preventDefault()},sb:c};return O(a)},Eb=(a,b,c,d,f,g)=>{tb||=S(160);a={target:P(a),
rb:g,tb:d,ub:h=>{var l=tb;z[l>>3]=h.timeStamp;var n=l>>2;w[n+2]=h.location;u[l+12]=h.ctrlKey;u[l+13]=h.shiftKey;u[l+14]=h.altKey;u[l+15]=h.metaKey;u[l+16]=h.repeat;w[n+5]=h.charCode;w[n+6]=h.keyCode;w[n+7]=h.which;R(h.key||"",l+32,32);R(h.code||"",l+64,32);R(h.char||"",l+96,32);R(h.locale||"",l+128,32);Q(d)(f,l,b)&&h.preventDefault()},sb:c};return O(a)},Fb=(a,b,c)=>{z[a>>3]=b.timeStamp;var d=a>>2;w[d+2]=b.screenX;w[d+3]=b.screenY;w[d+4]=b.clientX;w[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;
u[a+26]=b.altKey;u[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;w[d+8]=b.movementX;w[d+9]=b.movementY;a=Ab(c);w[d+10]=b.clientX-(a.left|0);w[d+11]=b.clientY-(a.top|0)},T=(a,b,c,d,f,g)=>{ub||=S(64);a=P(a);return O({target:a,zb:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,rb:g,tb:d,ub:(h=event)=>{Fb(ub,h,a);Q(d)(f,ub,b)&&h.preventDefault()},sb:c})},Gb=(a,b,c,d,f)=>{vb||=S(257);return O({target:a,rb:f,tb:d,ub:(g=event)=>{var h=vb,l=document.pointerLockElement||document.wb||document.Kb||
document.Jb;u[h]=!!l;var n=l?.id||"";R(rb(l),h+1,128);R(n,h+129,128);Q(d)(20,h,b)&&g.preventDefault()},sb:c})},Hb=(a,b,c,d,f)=>O({target:a,rb:f,tb:d,ub:(g=event)=>{Q(d)(38,0,b)&&g.preventDefault()},sb:c}),Ib=(a,b,c,d)=>{wb||=S(36);a=P(a);return O({target:a,rb:"resize",tb:d,ub:(f=event)=>{if(f.target==a){var g=document.body;if(g){var h=wb;w[h>>2]=0;w[h+4>>2]=g.clientWidth;w[h+8>>2]=g.clientHeight;w[h+12>>2]=innerWidth;w[h+16>>2]=innerHeight;w[h+20>>2]=outerWidth;w[h+24>>2]=outerHeight;w[h+28>>2]=pageXOffset|
0;w[h+32>>2]=pageYOffset|0;Q(d)(10,h,b)&&f.preventDefault()}}},sb:c})},Jb=(a,b,c,d,f,g)=>{xb||=S(1552);a=P(a);return O({target:a,zb:"touchstart"==g||"touchend"==g,rb:g,tb:d,ub:h=>{var l={},n=h.touches;for(var q of n)q.Hb=q.Ib=0,l[q.identifier]=q;for(var A of h.changedTouches)A.Hb=1,l[A.identifier]=A;for(var qa of h.targetTouches)l[qa.identifier].Ib=1;n=xb;z[n>>3]=h.timeStamp;u[n+12]=h.ctrlKey;u[n+13]=h.shiftKey;u[n+14]=h.altKey;u[n+15]=h.metaKey;q=n+16;A=Ab(a);qa=0;for(let y of Object.values(l))if(l=
q>>2,w[l]=y.identifier,w[l+1]=y.screenX,w[l+2]=y.screenY,w[l+3]=y.clientX,w[l+4]=y.clientY,w[l+5]=y.pageX,w[l+6]=y.pageY,u[q+28]=y.Hb,u[q+29]=y.Ib,w[l+8]=y.clientX-(A.left|0),w[l+9]=y.clientY-(A.top|0),q+=48,31<++qa)break;w[n+8>>2]=qa;Q(d)(f,n,b)&&h.preventDefault()},sb:c})},U,Kb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,f,g)=>b.drawArraysInstancedANGLE(c,d,f,g),a.drawElementsInstanced=(c,d,f,g,h)=>
b.drawElementsInstancedANGLE(c,d,f,g,h))},Lb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Mb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Nb=a=>{a.dc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},Ob=a=>{a.hc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},
Pb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Qb=1,Rb=[],Sb=[],Tb=[],Ub=[],Vb=[],V=[],W=[],Wb=[],Xb={},Yb=a=>{for(var b=Qb++,c=a.length;c<b;c++)a[c]=null;return b},$b=(a,b)=>{a.wb||(a.wb=a.getContext,a.getContext=function(d,f){f=a.wb(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=1<b.Bb?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Zb(c,b):0},Zb=(a,b)=>{var c=Yb(W),d={handle:c,attributes:b,version:b.Bb,yb:a};a.canvas&&(a.canvas.Zb=d);W[c]=d;
("undefined"==typeof b.Fb||b.Fb)&&ac(d);return c},bc=a=>{X=W[a];e.Ab=U=X?.yb;return!(a&&!U)},ac=a=>{a||=X;if(!a.Vb){a.Vb=!0;var b=a.yb;b.Wb=b.getExtension("WEBGL_multi_draw");b.Tb=b.getExtension("EXT_polygon_offset_clamp");b.Sb=b.getExtension("EXT_clip_control");b.Xb=b.getExtension("WEBGL_polygon_mode");Kb(b);Lb(b);Mb(b);Nb(b);Ob(b);2<=a.version&&(b.Eb=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Eb)b.Eb=b.getExtension("EXT_disjoint_timer_query");Pb(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},cc={},Y,X,dc=(a,b,c,d,f,g)=>{a={target:P(a),rb:g,tb:d,ub:(h=event)=>{Q(d)(f,0,b)&&h.preventDefault()},sb:c};O(a)},ec=(a,b,c,d)=>{yb||=S(96);return O({target:a,zb:!0,rb:"wheel",tb:d,ub:(f=event)=>{var g=yb;Fb(g,f,a);z[g+64>>3]=f.deltaX;z[g+72>>3]=f.deltaY;z[g+80>>3]=f.deltaZ;w[g+88>>2]=f.deltaMode;Q(d)(9,g,b)&&f.preventDefault()},sb:c})},fc=["default","low-power","high-performance"],gc={},ic=()=>{if(!hc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",
PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:m||"./this.program"},b;for(b in gc)void 0===gc[b]?delete a[b]:a[b]=gc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);hc=c}return hc},hc,jc=[null,[],[]];function kc(){var a=Pb(U);return a=a.concat(a.map(b=>"GL_"+b))}
var lc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=U.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>X.version){Y||=1282;return}c=kc().length;break;case 33307:case 33308:if(2>X.version){Y||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=U.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:Y||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){Y||=1280;r(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:Y||=1280;r(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}w[b>>2]=c}else Y||=1281},mc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},nc=a=>{var b=mc(a)+1,c=S(b);c&&R(a,c,b);return c},oc=[],qc=a=>{var b=mc(a)+1,c=pc(b);R(a,c,b);return c},tc=a=>{var b=rc();a();sc(b)};
e.requestFullscreen=function(a,b){function c(){J=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=jb,ib&&d.requestPointerLock(),J=!0,K?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]|8388608),M(e.canvas),lb()):M(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),K?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>
2]&-8388609),M(e.canvas),lb()):M(d));e.onFullScreen?.(J);e.onFullscreen?.(J)}ib=a;K=b;"undefined"==typeof ib&&(ib=!0);"undefined"==typeof K&&(K=!1);var d=e.canvas;hb||(hb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var f=document.createElement("div");d.parentNode.insertBefore(f,d);f.appendChild(d);f.requestFullscreen=f.requestFullscreen||
f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?()=>f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(f.webkitRequestFullScreen?()=>f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);f.requestFullscreen()};e.requestAnimationFrame=Ta;e.setCanvasSize=function(a,b,c){M(e.canvas,a,b);c||lb()};e.pauseMainLoop=cb;e.resumeMainLoop=function(){Wa++;var a=Pa,b=Qa,c=G;G=null;bb(c,0,!1,Xa,!0);Va(a,b);H()};
e.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};e.createContext=function(a,b,c,d){if(b&&e.Ab&&a==e.canvas)return e.Ab;var f;if(b){var g={antialias:!1,alpha:!1,Bb:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!=typeof cc&&(f=$b(a,g)))var l=W[f].yb}else l=a.getContext("2d");if(!l)return null;c&&(e.Ab=l,b&&bc(f),eb.forEach(n=>n()),fb());return l};
for(var uc=0;32>uc;++uc)oc.push(Array(uc));
var Cc={o:function(){return 0},Y:function(){return 0},Z:function(){},ba:()=>{ya("")},_:(a,b,c)=>v.copyWithin(a,b,b+c),Ua:()=>{Ha=!1;Ka=0},Va:(a,b)=>{E[a]&&(clearTimeout(E[a].id),delete E[a]);if(!b)return 0;var c=setTimeout(()=>{delete E[a];Oa(()=>vc(a,F()))},b);E[a]={id:c,pc:b};return 0},Fa:()=>{cb();G=null},aa:()=>Date.now(),O:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,Q:(a,b,c)=>{a=P(a);if(!a)return-4;a=Ab(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},m:F,Ga:()=>performance.now(),
Ma:(a,b)=>{function c(d){Q(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},T:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ma.buffer.byteLength+65535)/65536;try{ma.grow(d);ra();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},w:(a,b,c,d)=>Db(a,b,c,d,12,"blur"),N:(a,b,c)=>{a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},x:(a,b,c,d)=>
Db(a,b,c,d,13,"focus"),G:(a,b,c,d)=>Eb(a,b,c,d,2,"keydown"),E:(a,b,c,d)=>Eb(a,b,c,d,1,"keypress"),F:(a,b,c,d)=>Eb(a,b,c,d,3,"keyup"),Na:(a,b,c)=>{a=Q(a);bb(a,b,c)},M:(a,b,c,d)=>T(a,b,c,d,5,"mousedown"),J:(a,b,c,d)=>T(a,b,c,d,33,"mouseenter"),I:(a,b,c,d)=>T(a,b,c,d,34,"mouseleave"),K:(a,b,c,d)=>T(a,b,c,d,8,"mousemove"),L:(a,b,c,d)=>T(a,b,c,d,6,"mouseup"),z:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.wb||document.body.Kb||document.body.Jb))return-1;a=
P(a);if(!a)return-4;Gb(a,b,c,d,"mozpointerlockchange");Gb(a,b,c,d,"webkitpointerlockchange");Gb(a,b,c,d,"mspointerlockchange");return Gb(a,b,c,d,"pointerlockchange")},y:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.wb||document.body.Kb||document.body.Jb))return-1;a=P(a);if(!a)return-4;Hb(a,b,c,d,"mozpointerlockerror");Hb(a,b,c,d,"webkitpointerlockerror");Hb(a,b,c,d,"mspointerlockerror");return Hb(a,b,c,d,"pointerlockerror")},P:(a,b,c,d)=>Ib(a,b,c,d),A:(a,b,c,d)=>Jb(a,
b,c,d,25,"touchcancel"),B:(a,b,c,d)=>Jb(a,b,c,d,23,"touchend"),C:(a,b,c,d)=>Jb(a,b,c,d,24,"touchmove"),D:(a,b,c,d)=>Jb(a,b,c,d,22,"touchstart"),v:(a,b,c,d)=>{dc(a,b,c,d,31,"webglcontextlost");return 0},u:(a,b,c,d)=>{dc(a,b,c,d,32,"webglcontextrestored");return 0},H:(a,b,c,d)=>(a=P(a))?"undefined"!=typeof a.onwheel?ec(a,b,c,d):-1:-4,La:(a,b)=>{var c=b>>2;b={alpha:!!u[b+0],depth:!!u[b+1],stencil:!!u[b+2],antialias:!!u[b+3],premultipliedAlpha:!!u[b+4],preserveDrawingBuffer:!!u[b+5],powerPreference:fc[w[c+
2]],failIfMajorPerformanceCaveat:!!u[b+12],Bb:w[c+4],ic:w[c+5],Fb:u[b+24],Rb:u[b+25],jc:w[c+7],lc:u[b+32]};a=P(a);return!a||b.Rb?0:$b(a,b)},Ja:(a,b)=>{a=W[a];b=b?D(v,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Kb(U);"OES_vertex_array_object"==b&&Lb(U);"WEBGL_draw_buffers"==b&&Mb(U);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Nb(U);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Ob(U);"WEBGL_multi_draw"==b&&(U.Wb=U.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==
b&&(U.Tb=U.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&(U.Sb=U.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(U.Xb=U.getExtension("WEBGL_polygon_mode"));return!!a.yb.getExtension(b)},Ka:a=>bc(a)?0:-5,U:(a,b)=>{var c=0;ic().forEach((d,f)=>{var g=b+c;f=x[a+4*f>>2]=g;for(g=0;g<d.length;++g)u[f++]=d.charCodeAt(g);u[f]=0;c+=d.length+1});return 0},V:(a,b)=>{var c=ic();x[a>>2]=c.length;var d=0;c.forEach(f=>d+=f.length+1);x[b>>2]=d;return 0},n:()=>52,X:()=>52,Sa:function(){return 70},
W:(a,b,c,d)=>{for(var f=0,g=0;g<c;g++){var h=x[b>>2],l=x[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=v[h+n],A=jc[a];0===q||10===q?((1===a?ka:r)(D(A,0)),A.length=0):A.push(q)}f+=l}x[d>>2]=f;return 0},i:a=>U.activeTexture(a),d:(a,b)=>{35051==a?U.Cb=b:35052==a&&(U.Db=b);U.bindBuffer(a,Rb[b])},a:(a,b,c)=>{U.bindBufferBase(a,b,Rb[c])},g:(a,b)=>{U.bindFramebuffer(a,Tb[b])},h:(a,b)=>{U.bindSampler(a,Wb[b])},c:(a,b)=>{U.bindTexture(a,Vb[b])},t:a=>{U.bindVertexArray(V[a])},ua:(a,b,c,d)=>U.blendColor(a,b,c,d),
va:(a,b)=>U.blendEquationSeparate(a,b),xa:(a,b,c,d)=>U.blendFuncSeparate(a,b,c,d),da:(a,b,c,d,f,g,h,l,n,q)=>U.blitFramebuffer(a,b,c,d,f,g,h,l,n,q),ga:(a,b,c,d)=>U.clearBufferfi(a,b,c,d),p:(a,b,c)=>{U.clearBufferfv(a,b,pa,c>>2)},fa:(a,b,c)=>{U.clearBufferiv(a,b,w,c>>2)},j:(a,b,c,d)=>{U.colorMask(!!a,!!b,!!c,!!d)},ra:a=>U.cullFace(a),qa:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],f=Rb[d];f&&(U.deleteBuffer(f),f.name=0,Rb[d]=null,d==U.Cb&&(U.Cb=0),d==U.Db&&(U.Db=0))}},f:(a,b)=>{for(var c=0;c<a;++c){var d=
w[b+4*c>>2],f=Tb[d];f&&(U.deleteFramebuffer(f),f.name=0,Tb[d]=null)}},ma:a=>{if(a){var b=Sb[a];b?(U.deleteProgram(b),b.name=0,Sb[a]=null):Y||=1281}},oa:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],f=Ub[d];f&&(U.deleteRenderbuffer(f),f.name=0,Ub[d]=null)}},na:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],f=Wb[d];f&&(U.deleteSampler(f),f.name=0,Wb[d]=null)}},pa:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],f=Vb[d];f&&(U.deleteTexture(f),f.name=0,Vb[d]=null)}},ka:(a,b)=>{for(var c=0;c<a;c++){var d=
w[b+4*c>>2];U.deleteVertexArray(V[d]);V[d]=null}},s:a=>U.depthFunc(a),r:a=>{U.depthMask(!!a)},e:a=>U.disable(a),Aa:a=>{U.disableVertexAttribArray(a)},l:a=>U.enable(a),sa:a=>U.frontFace(a),Ea:(a,b)=>{for(var c=0;c<a;c++){var d=U.createVertexArray(),f=d&&Yb(V);d?(d.name=f,V[f]=d):Y||=1282;w[b+4*c>>2]=f}},b:(a,b)=>lc(a,b),Ba:(a,b)=>{if(2>X.version)return Y||=1282,0;var c=Xb[a];if(c)return 0>b||b>=c.length?(Y||=1281,0):c[b];switch(a){case 7939:return c=kc().map(nc),c=Xb[a]=c,0>b||b>=c.length?(Y||=1281,
0):c[b];default:return Y||=1280,0}},ca:(a,b,c)=>{for(var d=oc[b],f=0;f<b;f++)d[f]=w[c+4*f>>2];U.invalidateFramebuffer(a,d)},Da:(a,b)=>{U.pixelStorei(a,b)},ta:(a,b)=>U.polygonOffset(a,b),ea:a=>U.readBuffer(a),ha:(a,b,c,d)=>U.scissor(a,b,c,d),za:(a,b,c)=>U.stencilFunc(a,b,c),q:a=>U.stencilMask(a),ya:(a,b,c)=>U.stencilOp(a,b,c),la:a=>{a=Sb[a];U.useProgram(a);U.cc=a},ia:(a,b,c,d)=>U.viewport(a,b,c,d),Ta:La,Xa:function(){e.Lb=a=>{0!=wc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",
e.Lb)},Oa:function(){e.Qb=a=>{const b=a.clipboardData.getData("text");tc(()=>{const c=qc(b);xc(c)})};window.addEventListener("paste",e.Qb)},Ha:function(a){e.mc=[];a=a?D(v,a):"";a=document.getElementById(a);e.Mb=b=>{b.stopPropagation();b.preventDefault()};e.Nb=b=>{b.stopPropagation();b.preventDefault()};e.Ob=b=>{b.stopPropagation();b.preventDefault()};e.Pb=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;e.nc=c;yc(c.length);for(let f=0;f<c.length;f++)tc(()=>{const g=qc(c[f].name);
zc(f,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Ac(b.clientX,b.clientY,d)};a.addEventListener("dragenter",e.Mb,!1);a.addEventListener("dragleave",e.Nb,!1);a.addEventListener("dragover",e.Ob,!1);a.addEventListener("drop",e.Pb,!1)},ja:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},wa:function(a){a=a?D(v,a):"";e.xb=document.getElementById(a);e.xb||console.log("sokol_app.h: invalid target:"+a);e.xb.requestPointerLock||
console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Wa:function(){window.removeEventListener("beforeunload",e.Lb)},Ia:function(){window.removeEventListener("paste",e.Qb)},Ca:function(a){a=a?D(v,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",e.Mb);a.removeEventListener("dragleave",e.Nb);a.removeEventListener("dragover",e.Ob);a.removeEventListener("drop",e.Pb)},k:function(){e.xb&&e.xb.requestPointerLock&&e.xb.requestPointerLock()},$:function(a,b,c){const d=
document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),g=f.createImageData(a,b);g.data.set(v.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Pa:function(){return e.vb?e.vb.bufferSize:0},Ra:function(a,b,c){e.qb=null;e.vb=null;"undefined"!==typeof AudioContext?e.qb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(e.qb=null,console.log("sokol_audio.h: no WebAudio support"));
return e.qb?(console.log("sokol_audio.h: sample rate ",e.qb.sampleRate),e.vb=e.qb.createScriptProcessor(c,0,b),e.vb.onaudioprocess=d=>{const f=d.outputBuffer.length,g=Bc(f);if(g){const h=d.outputBuffer.numberOfChannels;for(let l=0;l<h;l++){const n=d.outputBuffer.getChannelData(l);for(let q=0;q<f;q++)n[q]=pa[(g>>2)+(h*q+l)]}}},e.vb.connect(e.qb.destination),a=()=>{e.qb&&"suspended"===e.qb.state&&e.qb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),
document.addEventListener("keydown",a,{once:!0}),1):0},Qa:function(){return e.qb?e.qb.sampleRate:0},S:function(){const a=e.qb;null!==a&&(e.vb&&e.vb.disconnect(),a.close(),e.qb=null,e.vb=null)},R:function(a,b){b=b?D(v,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;ma=Z.Ya;ra();Cb=Z.lb;ta.unshift(Z.Za);B--;e.monitorRunDependencies?.(B);0==B&&(null!==xa&&(clearInterval(xa),xa=null),
C&&(c=C,C=null,c()));return Z}var b={a:Cc};B++;e.monitorRunDependencies?.(B);if(e.instantiateWasm)try{return e.instantiateWasm(b,a)}catch(c){return r(`Module.instantiateWasm callback failed with error: ${c}`),!1}Aa||=za("modplay-sapp.wasm")?"modplay-sapp.wasm":e.locateFile?e.locateFile("modplay-sapp.wasm",p):p+"modplay-sapp.wasm";Ea(b,function(c){a(c.instance)});return{}}(),xc=e.__sapp_emsc_onpaste=a=>(xc=e.__sapp_emsc_onpaste=Z._a)(a),wc=e.__sapp_html5_get_ask_leave_site=()=>(wc=e.__sapp_html5_get_ask_leave_site=
Z.$a)(),yc=e.__sapp_emsc_begin_drop=a=>(yc=e.__sapp_emsc_begin_drop=Z.ab)(a),zc=e.__sapp_emsc_drop=(a,b)=>(zc=e.__sapp_emsc_drop=Z.bb)(a,b),Ac=e.__sapp_emsc_end_drop=(a,b,c)=>(Ac=e.__sapp_emsc_end_drop=Z.cb)(a,b,c);e.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,f,g,h,l)=>(e.__sapp_emsc_invoke_fetch_cb=Z.db)(a,b,c,d,f,g,h,l);var Dc=e._main=(a,b)=>(Dc=e._main=Z.eb)(a,b),Bc=e.__saudio_emsc_pull=a=>(Bc=e.__saudio_emsc_pull=Z.fb)(a);e.__sfetch_emsc_head_response=(a,b)=>(e.__sfetch_emsc_head_response=Z.gb)(a,b);
e.__sfetch_emsc_get_response=(a,b,c)=>(e.__sfetch_emsc_get_response=Z.hb)(a,b,c);e.__sfetch_emsc_failed_http_status=(a,b)=>(e.__sfetch_emsc_failed_http_status=Z.ib)(a,b);e.__sfetch_emsc_failed_buffer_too_small=a=>(e.__sfetch_emsc_failed_buffer_too_small=Z.jb)(a);var S=a=>(S=Z.kb)(a),vc=(a,b)=>(vc=Z.mb)(a,b),sc=a=>(sc=Z.nb)(a),pc=a=>(pc=Z.ob)(a),rc=()=>(rc=Z.pb)(),Ec;C=function Fc(){Ec||Gc();Ec||(C=Fc)};
function Hc(a=[]){var b=Dc;a.unshift(m);var c=a.length,d=pc(4*(c+1)),f=d;a.forEach(h=>{x[f>>2]=qc(h);f+=4});x[f>>2]=0;try{var g=b(c,d);Ma(g)}catch(h){Ja(h)}}
function Gc(){var a=da;function b(){if(!Ec&&(Ec=!0,e.calledRun=!0,!t)){Ga(ta);Ga(ua);e.onRuntimeInitialized?.();Ic&&Hc(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();va.unshift(c)}Ga(va)}}if(!(0<B)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)wa();Ga(sa);0<B||(e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);b()},1)):b())}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Ic=!0;e.noInitialRun&&(Ic=!1);Gc();
