
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign,ba=aa({},e),ca=[],h="./this.program";function l(a,b){throw b;}var da="object"===typeof window,t="function"===typeof importScripts,ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,u="",fa,v,w,fs,ha,ia;
if(ea)u=t?require("path").dirname(u)+"/":__dirname+"/",ia=function(){fs||(fs=require("fs"),ha=require("path"))},fa=function(a,b){ia();a=ha.normalize(a);return fs.readFileSync(a,b?null:"utf8")},w=function(a){a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a},v=function(a,b,c){ia();a=ha.normalize(a);fs.readFile(a,function(d,f){d?c(d):b(f.buffer)})},1<process.argv.length&&(h=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",
function(a){if(!(a instanceof x))throw a;}),process.on("unhandledRejection",function(a){throw a;}),l=function(a,b){if(noExitRuntime||0<ja)throw process.exitCode=a,b;b instanceof x||y("exiting due to exception: "+b);process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(da||t)t?u=self.location.href:"undefined"!==typeof document&&document.currentScript&&(u=document.currentScript.src),u=0!==u.indexOf("blob:")?u.substr(0,u.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(w=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),v=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ka=e.print||console.log.bind(console),y=e.printErr||console.warn.bind(console);aa(e,ba);
ba=null;e.arguments&&(ca=e.arguments);e.thisProgram&&(h=e.thisProgram);e.quit&&(l=e.quit);var z;e.wasmBinary&&(z=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var la,ma=!1;
function na(a,b,c){var d={string:function(n){var p=0;if(null!==n&&void 0!==n&&0!==n){var q=(n.length<<2)+1;p=B(q);C(n,D,p,q)}return p},array:function(n){var p=B(n.length);E.set(n,p);return p}};a=e["_"+a];var f=[],g=0;if(c)for(var k=0;k<c.length;k++){var m=d[b[k]];m?(0===g&&(g=oa()),f[k]=m(c[k])):f[k]=c[k]}b=a.apply(null,f);b=function(n){0!==g&&pa(g);return n}(b)}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ra(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&qa)return qa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function F(a){return a?ra(D,a,void 0):""}
function C(a,b,c,d){if(0<d){d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ta(a){var b=sa(a)+1,c=B(b);C(a,E,c,b);return c}var ua,E,D,va,G,wa,H;
function xa(){var a=la.buffer;ua=a;e.HEAP8=E=new Int8Array(a);e.HEAP16=va=new Int16Array(a);e.HEAP32=G=new Int32Array(a);e.HEAPU8=D=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAPU32=new Uint32Array(a);e.HEAPF32=wa=new Float32Array(a);e.HEAPF64=H=new Float64Array(a)}var ya,za=[],Aa=[],Ba=[],Ca=[],Da=[],ja=0;function Ea(){var a=e.preRun.shift();za.unshift(a)}var I=0,Fa=null,J=null;e.preloadedImages={};e.preloadedAudios={};
function A(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";y(a);ma=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ga(){return K.startsWith("data:application/octet-stream;base64,")}var K;K="modplay-sapp.wasm";if(!Ga()){var Ha=K;K=e.locateFile?e.locateFile(Ha,u):u+Ha}function Ia(){var a=K;try{if(a==K&&z)return new Uint8Array(z);if(w)return w(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function Ja(){if(!z&&(da||t)){if("function"===typeof fetch&&!K.startsWith("file://"))return fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Ia()});if(v)return new Promise(function(a,b){v(K,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ia()})}
function L(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Ub;"number"===typeof c?void 0===b.tb?M(c)():M(c)(b.tb):c(void 0===b.tb?null:b.tb)}}}var N=[];function M(a){var b=N[a];b||(a>=N.length&&(N.length=a+1),N[a]=b=ya.get(a));return b}var Ka=[null,[],[]],La={},Ma=0;function Na(){for(var a=O.length-1;0<=a;--a)Oa(a);O=[];P=[]}var P=[];function Pa(){if(Ma&&Qa.rb)for(var a=0;a<P.length;++a){var b=P[a];P.splice(a,1);--a;b.dc.apply(null,b.Pb)}}var O=[];
function Oa(a){var b=O[a];b.target.removeEventListener(b.lb,b.Lb,b.mb);O.splice(a,1)}function Q(a){function b(d){++Ma;Qa=a;Pa();a.ob(d);Pa();--Ma}if(a.nb)a.Lb=b,a.target.addEventListener(a.lb,b,a.mb),O.push(a),Ra||(Ca.push(Na),Ra=!0);else for(var c=0;c<O.length;++c)O[c].target==a.target&&O[c].lb==a.lb&&Oa(c--)}function Sa(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Ra,Qa,Ta,Ua,R,Va,Wa,Xa,Ya,Za=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function S(a){a=2<a?F(a):a;return Za[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function $a(a){return 0>Za.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function ab(a,b,c,d,f,g){Ta||(Ta=T(256));a={target:S(a),lb:g,nb:d,ob:function(k){k=k||event;var m=k.target.id?k.target.id:"",n=Ta;C(Sa(k.target),D,n+0,128);C(m,D,n+128,128);M(d)(f,n,b)&&k.preventDefault()},mb:c};Q(a)}
function bb(a,b,c,d,f,g){Ua||(Ua=T(176));a={target:S(a),rb:!0,lb:g,nb:d,ob:function(k){var m=Ua;H[m>>3]=k.timeStamp;var n=m>>2;G[n+2]=k.location;G[n+3]=k.ctrlKey;G[n+4]=k.shiftKey;G[n+5]=k.altKey;G[n+6]=k.metaKey;G[n+7]=k.repeat;G[n+8]=k.charCode;G[n+9]=k.keyCode;G[n+10]=k.which;C(k.key||"",D,m+44,32);C(k.code||"",D,m+76,32);C(k.char||"",D,m+108,32);C(k.locale||"",D,m+140,32);M(d)(f,m,b)&&k.preventDefault()},mb:c};Q(a)}
function cb(a,b,c){H[a>>3]=b.timeStamp;a>>=2;G[a+2]=b.screenX;G[a+3]=b.screenY;G[a+4]=b.clientX;G[a+5]=b.clientY;G[a+6]=b.ctrlKey;G[a+7]=b.shiftKey;G[a+8]=b.altKey;G[a+9]=b.metaKey;va[2*a+20]=b.button;va[2*a+21]=b.buttons;G[a+11]=b.movementX;G[a+12]=b.movementY;c=$a(c);G[a+13]=b.clientX-c.left;G[a+14]=b.clientY-c.top}
function U(a,b,c,d,f,g){R||(R=T(72));a=S(a);Q({target:a,rb:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,lb:g,nb:d,ob:function(k){k=k||event;cb(R,k,a);M(d)(f,R,b)&&k.preventDefault()},mb:c})}function db(a,b,c,d,f){Va||(Va=T(260));Q({target:a,lb:f,nb:d,ob:function(g){g=g||event;var k=Va,m=document.pointerLockElement||document.Ab||document.Db||document.Bb;G[k>>2]=!!m;var n=m&&m.id?m.id:"";C(Sa(m),D,k+4,128);C(n,D,k+132,128);M(d)(20,k,b)&&g.preventDefault()},mb:c})}
function eb(a,b,c,d,f){Q({target:a,lb:f,nb:d,ob:function(g){g=g||event;M(d)(38,0,b)&&g.preventDefault()},mb:c})}
function fb(a,b,c,d){Wa||(Wa=T(36));a=S(a);Q({target:a,lb:"resize",nb:d,ob:function(f){f=f||event;if(f.target==a){var g=document.body;if(g){var k=Wa;G[k>>2]=f.detail;G[k+4>>2]=g.clientWidth;G[k+8>>2]=g.clientHeight;G[k+12>>2]=innerWidth;G[k+16>>2]=innerHeight;G[k+20>>2]=outerWidth;G[k+24>>2]=outerHeight;G[k+28>>2]=pageXOffset;G[k+32>>2]=pageYOffset;M(d)(10,k,b)&&f.preventDefault()}}},mb:c})}
function gb(a,b,c,d,f,g){Xa||(Xa=T(1696));a=S(a);Q({target:a,rb:"touchstart"==g||"touchend"==g,lb:g,nb:d,ob:function(k){for(var m,n={},p=k.touches,q=0;q<p.length;++q)m=p[q],m.zb=m.Eb=0,n[m.identifier]=m;for(q=0;q<k.changedTouches.length;++q)m=k.changedTouches[q],m.zb=1,n[m.identifier]=m;for(q=0;q<k.targetTouches.length;++q)n[k.targetTouches[q].identifier].Eb=1;p=Xa;H[p>>3]=k.timeStamp;var r=p>>2;G[r+3]=k.ctrlKey;G[r+4]=k.shiftKey;G[r+5]=k.altKey;G[r+6]=k.metaKey;r+=7;var ib=$a(a),jb=0;for(q in n)if(m=
n[q],G[r]=m.identifier,G[r+1]=m.screenX,G[r+2]=m.screenY,G[r+3]=m.clientX,G[r+4]=m.clientY,G[r+5]=m.pageX,G[r+6]=m.pageY,G[r+7]=m.zb,G[r+8]=m.Eb,G[r+9]=m.clientX-ib.left,G[r+10]=m.clientY-ib.top,r+=13,31<++jb)break;G[p+8>>2]=jb;M(d)(f,p,b)&&k.preventDefault()},mb:c})}function hb(a,b,c,d,f,g){a={target:S(a),lb:g,nb:d,ob:function(k){k=k||event;M(d)(f,0,b)&&k.preventDefault()},mb:c};Q(a)}
function kb(a,b,c,d){Ya||(Ya=T(104));Q({target:a,rb:!0,lb:"wheel",nb:d,ob:function(f){f=f||event;var g=Ya;cb(g,f,a);H[g+72>>3]=f.deltaX;H[g+80>>3]=f.deltaY;H[g+88>>3]=f.deltaZ;G[g+96>>2]=f.deltaMode;M(d)(9,g,b)&&f.preventDefault()},mb:c})}
function lb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,k){b.drawElementsInstancedANGLE(c,d,f,g,k)})}
function mb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function nb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function ob(a){a.Sb=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function pb(a){a.Xb=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function qb(a){a.Zb=a.getExtension("WEBGL_multi_draw")}var rb=1,sb=[],tb=[],ub=[],vb=[],wb=[],V=[],xb=[],yb={},zb={};function W(a){Ab||(Ab=a)}function Bb(a){for(var b=rb++,c=a.length;c<b;c++)a[c]=null;return b}
function Cb(a,b){a.yb||(a.yb=a.getContext,a.getContext=function(d,f){f=a.yb(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=1<b.Cb?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Db(c,b):0}function Db(a,b){var c=Bb(xb),d={Wb:c,attributes:b,version:b.Cb,sb:a};a.canvas&&(a.canvas.Ob=d);xb[c]=d;("undefined"===typeof b.xb||b.xb)&&Eb(d);return c}
function Eb(a){a||(a=X);if(!a.Nb){a.Nb=!0;var b=a.sb;lb(b);mb(b);nb(b);ob(b);pb(b);2<=a.version&&(b.wb=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.wb)b.wb=b.getExtension("EXT_disjoint_timer_query");qb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Ab,X,Fb=["default","low-power","high-performance"],Gb={};
function Hb(){if(!Ib){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:h||"./this.program"},b;for(b in Gb)void 0===Gb[b]?delete a[b]:a[b]=Gb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ib=c}return Ib}var Ib;
function Jb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Y.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>X.version){W(1282);return}c=2*(Y.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>X.version){W(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=Y.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:W(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)G[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){W(1280);y("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:W(1280);y("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}G[b>>2]=c}else W(1281)}
function Z(a){var b=sa(a)+1,c=T(b);C(a,D,c,b);return c}
var Y,Pb={p:function(){return 0},aa:function(){return 0},da:function(){},Y:function(){A("")},z:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},K:function(a,b,c){a=S(a);if(!a)return-4;a=$a(a);H[b>>3]=a.width;H[c>>3]=a.height;return 0},U:ea?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()},W:function(a,b,c){D.copyWithin(a,b,b+c)},xa:function(a,b){function c(d){M(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
X:function(a){var b=D.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{la.grow(Math.min(2147483648,d)-ua.byteLength+65535>>>16);xa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},C:function(a,b,c,d){ab(a,b,c,d,12,"blur");return 0},x:function(a,b,c){a=S(a);if(!a)return-4;a.width=b;a.height=c;return 0},D:function(a,b,c,d){ab(a,b,c,d,13,"focus");return 0},N:function(a,b,c,d){bb(a,
b,c,d,2,"keydown");return 0},L:function(a,b,c,d){bb(a,b,c,d,1,"keypress");return 0},M:function(a,b,c,d){bb(a,b,c,d,3,"keyup");return 0},T:function(a,b,c,d){U(a,b,c,d,5,"mousedown");return 0},Q:function(a,b,c,d){U(a,b,c,d,33,"mouseenter");return 0},P:function(a,b,c,d){U(a,b,c,d,34,"mouseleave");return 0},R:function(a,b,c,d){U(a,b,c,d,8,"mousemove");return 0},S:function(a,b,c,d){U(a,b,c,d,6,"mouseup");return 0},F:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Ab||
document.body.Db||document.body.Bb))return-1;a=S(a);if(!a)return-4;db(a,b,c,d,"pointerlockchange");db(a,b,c,d,"mozpointerlockchange");db(a,b,c,d,"webkitpointerlockchange");db(a,b,c,d,"mspointerlockchange");return 0},E:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Ab||document.body.Db||document.body.Bb))return-1;a=S(a);if(!a)return-4;eb(a,b,c,d,"pointerlockerror");eb(a,b,c,d,"mozpointerlockerror");eb(a,b,c,d,"webkitpointerlockerror");eb(a,b,c,d,"mspointerlockerror");
return 0},Na:function(a,b,c,d){fb(a,b,c,d);return 0},G:function(a,b,c,d){gb(a,b,c,d,25,"touchcancel");return 0},H:function(a,b,c,d){gb(a,b,c,d,23,"touchend");return 0},I:function(a,b,c,d){gb(a,b,c,d,24,"touchmove");return 0},J:function(a,b,c,d){gb(a,b,c,d,22,"touchstart");return 0},B:function(a,b,c,d){hb(a,b,c,d,31,"webglcontextlost");return 0},A:function(a,b,c,d){hb(a,b,c,d,32,"webglcontextrestored");return 0},O:function(a,b,c,d){a=S(a);return"undefined"!==typeof a.onwheel?(kb(a,b,c,d),0):-1},s:function(a,
b){b>>=2;b={alpha:!!G[b],depth:!!G[b+1],stencil:!!G[b+2],antialias:!!G[b+3],premultipliedAlpha:!!G[b+4],preserveDrawingBuffer:!!G[b+5],powerPreference:Fb[G[b+6]],failIfMajorPerformanceCaveat:!!G[b+7],Cb:G[b+8],Yb:G[b+9],xb:G[b+10],Mb:G[b+11],$b:G[b+12],ac:G[b+13]};a=S(a);return!a||b.Mb?0:Cb(a,b)},Qa:function(a,b){a=xb[a];b=F(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&lb(Y);"OES_vertex_array_object"==b&&mb(Y);"WEBGL_draw_buffers"==b&&nb(Y);"WEBGL_draw_instanced_base_vertex_base_instance"==
b&&ob(Y);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&pb(Y);"WEBGL_multi_draw"==b&&qb(Y);return!!a.sb.getExtension(b)},qa:function(a){a>>=2;for(var b=0;14>b;++b)G[a+b]=0;G[a]=G[a+1]=G[a+3]=G[a+4]=G[a+8]=G[a+10]=1},ba:function(a){X=xb[a];e.Qb=Y=X&&X.sb;return!a||Y?0:-5},Z:function(a,b){var c=0;Hb().forEach(function(d,f){var g=b+c;f=G[a+4*f>>2]=g;for(g=0;g<d.length;++g)E[f++>>0]=d.charCodeAt(g);E[f>>0]=0;c+=d.length+1});return 0},_:function(a,b){var c=Hb();G[a>>2]=c.length;var d=0;c.forEach(function(f){d+=
f.length+1});G[b>>2]=d;return 0},q:function(){return 0},$:function(a,b,c,d){a=La.Vb(a);b=La.Tb(a,b,c);G[d>>2]=b;return 0},V:function(){},ca:function(a,b,c,d){for(var f=0,g=0;g<c;g++){var k=G[b>>2],m=G[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=D[k+n],q=Ka[a];0===p||10===p?((1===a?ka:y)(ra(q,0)),q.length=0):q.push(p)}f+=m}G[d>>2]=f;return 0},b:function(a){Y.activeTexture(a)},g:function(a,b){35051==a?Y.ub=b:35052==a&&(Y.vb=b);Y.bindBuffer(a,sb[b])},d:function(a,b){Y.bindFramebuffer(a,ub[b])},a:function(a,
b){Y.bindTexture(a,wb[b])},w:function(a){Y.bindVertexArray(V[a])},sa:function(a,b,c,d){Y.blendColor(a,b,c,d)},ta:function(a,b){Y.blendEquationSeparate(a,b)},ua:function(a,b,c,d){Y.blendFuncSeparate(a,b,c,d)},h:function(a,b,c,d,f,g,k,m,n,p){Y.blitFramebuffer(a,b,c,d,f,g,k,m,n,p)},ia:function(a){Y.clear(a)},la:function(a,b,c,d){Y.clearColor(a,b,c,d)},ka:function(a){Y.clearDepth(a)},ja:function(a){Y.clearStencil(a)},m:function(a,b,c,d){Y.colorMask(!!a,!!b,!!c,!!d)},oa:function(a){Y.cullFace(a)},Ea:function(a,
b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],f=sb[d];f&&(Y.deleteBuffer(f),f.name=0,sb[d]=null,d==Y.ub&&(Y.ub=0),d==Y.vb&&(Y.vb=0))}},f:function(a,b){for(var c=0;c<a;++c){var d=G[b+4*c>>2],f=ub[d];f&&(Y.deleteFramebuffer(f),f.name=0,ub[d]=null)}},Ca:function(a){if(a){var b=tb[a];b?(Y.deleteProgram(b),b.name=0,tb[a]=null):W(1281)}},y:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],f=vb[d];f&&(Y.deleteRenderbuffer(f),f.name=0,vb[d]=null)}},Da:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],f=
wb[d];f&&(Y.deleteTexture(f),f.name=0,wb[d]=null)}},Aa:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2];Y.deleteVertexArray(V[d]);V[d]=null}},v:function(a){Y.depthFunc(a)},u:function(a){Y.depthMask(!!a)},e:function(a){Y.disable(a)},ya:function(a){Y.disableVertexAttribArray(a)},n:function(a){Y.enable(a)},pa:function(a){Y.frontFace(a)},za:function(a,b){for(var c=0;c<a;c++){var d=Y.createVertexArray(),f=d&&Bb(V);d?(d.name=f,V[f]=d):W(1282);G[b+4*c>>2]=f}},c:function(a,b){Jb(a,b)},Ga:function(a){var b=
yb[a];if(!b){switch(a){case 7939:b=Y.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Z(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Y.getParameter(a))||W(1280);b=b&&Z(b);break;case 7938:b=Y.getParameter(7938);b=2<=X.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Z(b);break;case 35724:b=Y.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+
b+")");b=Z(b);break;default:W(1280)}yb[a]=b}return b},Fa:function(a,b){if(2>X.version)return W(1282),0;var c=zb[a];if(c)return 0>b||b>=c.length?(W(1281),0):c[b];switch(a){case 7939:return c=Y.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Z(d)}),c=zb[a]=c,0>b||b>=c.length?(W(1281),0):c[b];default:return W(1280),0}},ra:function(a,b){Y.polygonOffset(a,b)},i:function(a){Y.readBuffer(a)},ma:function(a,b,c,d){Y.scissor(a,b,c,d)},wa:function(a,b,c){Y.stencilFunc(a,
b,c)},t:function(a){Y.stencilMask(a)},va:function(a,b,c){Y.stencilOp(a,b,c)},Ba:function(a){a=tb[a];Y.useProgram(a);Y.Rb=a},na:function(a,b,c,d){Y.viewport(a,b,c,d)},Pa:function(){e.Fb=function(a){0!=Kb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Fb)},Oa:function(){e.Kb=function(a){a=a.clipboardData.getData("text");na("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",e.Kb)},Ma:function(a){e.bc=[];a=F(a);a=document.getElementById(a);e.Gb=
function(b){b.stopPropagation();b.preventDefault()};e.Hb=function(b){b.stopPropagation();b.preventDefault()};e.Ib=function(b){b.stopPropagation();b.preventDefault()};e.Jb=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;e.cc=c;Lb(c.length);var d;for(d=0;d<c.length;d++)na("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Mb(b.clientX,b.clientY)};a.addEventListener("dragenter",e.Gb,!1);a.addEventListener("dragleave",e.Hb,!1);a.addEventListener("dragover",e.Ib,!1);a.addEventListener("drop",
e.Jb,!1)},Ia:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},l:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Nb()});document.body.append(a)},k:function(){document.getElementById("_sokol_app_input_element").focus()},Ra:function(a){a=F(a);e.qb=document.getElementById(a);e.qb||console.log("sokol_app.h: invalid target:"+a);e.qb.requestPointerLock||
console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},La:function(){window.removeEventListener("beforeunload",e.Fb)},Ka:function(){window.removeEventListener("paste",e.Kb)},Ja:function(a){a=F(a);a=document.getElementById(a);a.removeEventListener("dragenter",e.Gb);a.removeEventListener("dragleave",e.Hb);a.removeEventListener("dragover",e.Ib);a.removeEventListener("drop",e.Jb)},o:function(){e.qb&&e.qb.requestPointerLock&&e.qb.requestPointerLock()},Ha:function(a,b,c){var d=document.createElement("canvas");
d.width=a;d.height=b;var f=d.getContext("2d"),g=f.createImageData(a,b);g.data.set(D.subarray(c,c+a*b*4));f.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},j:function(){document.getElementById("_sokol_app_input_element").blur()},fa:function(){return e.pb?e.pb.bufferSize:0},ha:function(a,b,c){e.kb=null;e.pb=null;"undefined"!==typeof AudioContext?e.kb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):
"undefined"!==typeof webkitAudioContext?e.kb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(e.kb=null,console.log("sokol_audio.h: no WebAudio support"));return e.kb?(console.log("sokol_audio.h: sample rate ",e.kb.sampleRate),e.pb=e.kb.createScriptProcessor(c,0,b),e.pb.onaudioprocess=function(d){var f=d.outputBuffer.length,g=Ob(f);if(g)for(var k=d.outputBuffer.numberOfChannels,m=0;m<k;m++)for(var n=d.outputBuffer.getChannelData(m),p=0;p<f;p++)n[p]=wa[(g>>2)+(k*p+m)]},e.pb.connect(e.kb.destination),
a=function(){e.kb&&"suspended"===e.kb.state&&e.kb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},ga:function(){return e.kb?e.kb.sampleRate:0},r:function(){null!==e.kb&&(e.pb&&e.pb.disconnect(),e.kb.close(),e.kb=null,e.pb=null)},ea:function(a){var b=Date.now()/1E3|0;a&&(G[a>>2]=b);return b}};
(function(){function a(f){e.asm=f.exports;la=e.asm.Sa;xa();ya=e.asm.jb;Aa.unshift(e.asm.Ta);I--;e.monitorRunDependencies&&e.monitorRunDependencies(I);0==I&&(null!==Fa&&(clearInterval(Fa),Fa=null),J&&(f=J,J=null,f()))}function b(f){a(f.instance)}function c(f){return Ja().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(f,function(g){y("failed to asynchronously prepare wasm: "+g);A(g)})}var d={a:Pb};I++;e.monitorRunDependencies&&e.monitorRunDependencies(I);if(e.instantiateWasm)try{return e.instantiateWasm(d,
a)}catch(f){return y("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return z||"function"!==typeof WebAssembly.instantiateStreaming||Ga()||K.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){y("wasm streaming compile failed: "+g);y("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.Ta).apply(null,arguments)};var Nb=e.__sapp_emsc_notify_keyboard_hidden=function(){return(Nb=e.__sapp_emsc_notify_keyboard_hidden=e.asm.Ua).apply(null,arguments)};e.__sapp_emsc_onpaste=function(){return(e.__sapp_emsc_onpaste=e.asm.Va).apply(null,arguments)};
var Kb=e.__sapp_html5_get_ask_leave_site=function(){return(Kb=e.__sapp_html5_get_ask_leave_site=e.asm.Wa).apply(null,arguments)},Lb=e.__sapp_emsc_begin_drop=function(){return(Lb=e.__sapp_emsc_begin_drop=e.asm.Xa).apply(null,arguments)};e.__sapp_emsc_drop=function(){return(e.__sapp_emsc_drop=e.asm.Ya).apply(null,arguments)};var Mb=e.__sapp_emsc_end_drop=function(){return(Mb=e.__sapp_emsc_end_drop=e.asm.Za).apply(null,arguments)};
e.__sapp_emsc_invoke_fetch_cb=function(){return(e.__sapp_emsc_invoke_fetch_cb=e.asm._a).apply(null,arguments)};e._main=function(){return(e._main=e.asm.$a).apply(null,arguments)};var Ob=e.__saudio_emsc_pull=function(){return(Ob=e.__saudio_emsc_pull=e.asm.ab).apply(null,arguments)};e.__sfetch_emsc_head_response=function(){return(e.__sfetch_emsc_head_response=e.asm.bb).apply(null,arguments)};e.__sfetch_emsc_get_response=function(){return(e.__sfetch_emsc_get_response=e.asm.cb).apply(null,arguments)};
e.__sfetch_emsc_failed_http_status=function(){return(e.__sfetch_emsc_failed_http_status=e.asm.db).apply(null,arguments)};e.__sfetch_emsc_failed_buffer_too_small=function(){return(e.__sfetch_emsc_failed_buffer_too_small=e.asm.eb).apply(null,arguments)};
var T=e._malloc=function(){return(T=e._malloc=e.asm.fb).apply(null,arguments)},oa=e.stackSave=function(){return(oa=e.stackSave=e.asm.gb).apply(null,arguments)},pa=e.stackRestore=function(){return(pa=e.stackRestore=e.asm.hb).apply(null,arguments)},B=e.stackAlloc=function(){return(B=e.stackAlloc=e.asm.ib).apply(null,arguments)},Qb;function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}J=function Rb(){Qb||Sb();Qb||(J=Rb)};
function Sb(a){function b(){if(!Qb&&(Qb=!0,e.calledRun=!0,!ma)){L(Aa);L(Ba);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Tb){var c=a,d=e._main;c=c||[];var f=c.length+1,g=B(4*(f+1));G[g>>2]=ta(h);for(var k=1;k<f;k++)G[(g>>2)+k]=ta(c[k-1]);G[(g>>2)+f]=0;try{var m=d(f,g);if(!(noExitRuntime||0<ja)){if(e.onExit)e.onExit(m);ma=!0}l(m,new x(m))}catch(n){n instanceof x||"unwind"==n||l(1,n)}finally{}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),
Da.unshift(c);L(Da)}}a=a||ca;if(!(0<I)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ea();L(za);0<I||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=Sb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Tb=!0;e.noInitialRun&&(Tb=!1);Sb();
