var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},h="",ia,ja;
if(ca){var fs=require("fs");require("path");h=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?h=self.location.href:"undefined"!=typeof document&&document.currentScript&&(h=document.currentScript.src),h=h.startsWith("blob:")?
"":h.slice(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};f.print||console.log.bind(console);var l=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);var la=f.wasmBinary,ma,n=!1,na,q,t,oa,u,v,w,x,pa=a=>a.startsWith("data:application/octet-stream;base64,"),ka=a=>a.startsWith("file://");
function ra(){var a=ma.buffer;f.HEAP8=q=new Int8Array(a);f.HEAP16=oa=new Int16Array(a);f.HEAPU8=t=new Uint8Array(a);f.HEAPU16=new Uint16Array(a);f.HEAP32=u=new Int32Array(a);f.HEAPU32=v=new Uint32Array(a);f.HEAPF32=w=new Float32Array(a);f.HEAPF64=x=new Float64Array(a);f.HEAP64=new BigInt64Array(a);f.HEAPU64=new BigUint64Array(a)}var sa=[],ta=[],ua=[],va=[];function wa(){var a=f.preRun.shift();sa.unshift(a)}var y=0,z=null;
function xa(a){f.onAbort?.(a);a="Aborted("+a+")";l(a);n=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ya;async function za(a){if(!la)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==ya&&la)a=new Uint8Array(la);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Aa(a,b){try{var c=await za(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),xa(d)}}async function Ba(a){var b=ya;if(!(la||"function"!=typeof WebAssembly.instantiateStreaming||pa(b)||ka(b)||ca))try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return Aa(b,a)}
class Ca{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Da=a=>{for(;0<a.length;)a.shift()(f)},Ea=f.noExitRuntime||!0,Fa=0,A={},Ga=a=>{a instanceof Ca||"unwind"==a||ha(1,a)},Ha=a=>{na=a;Ea||0<Fa||(f.onExit?.(a),n=!0);ha(a,new Ca(a))},Ia=a=>{na=a;Ha(a)},Ja=()=>{if(!(Ea||0<Fa))try{var a=na;na=a;Ha(a)}catch(b){Ga(b)}},Ka=a=>{if(!n)try{a(),Ja()}catch(b){Ga(b)}},Ra=(a,b)=>{La=a;Ma=b;if(B)if(Na||=!0,0==a)D=function(){setTimeout(E,Math.max(0,Oa+b-performance.now())|0)};else if(1==a)D=function(){Pa(E)};else if(2==a){if("undefined"==typeof Qa)if("undefined"==
typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Qa=setImmediate;D=function(){Qa(E)}}},$a=(a,b,c,d,e)=>{function k(){return g<Sa?(Ja(),!1):!0}B=a;Ta=d;var g=Sa;Na=!1;E=function(){if(!n)if(0<Ua.length){var m=Ua.shift();
m.Pc(m.Gc);if(Va){var p=Va,r=0==p%1?p-1:Math.floor(p);Va=m.Ic?r:(8*p+(r+.5))/9}f.setStatus&&(m=f.statusMessage||"Please wait...",p=Va??0,r=Wa.Nc??0,p?p<r?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(m):f.setStatus(""));k()&&setTimeout(E,0)}else if(k())if(Xa=Xa+1|0,1==La&&1<Ma&&0!=Xa%Ma)D();else{0==La&&(Oa=performance.now());a:if(!n){for(m of Ya)if(!1===m())break a;Ka(a);for(p of Za)p()}k()&&D()}};e||(0<b?Ra(0,1E3/b):Ra(1,1),D());if(c)throw"unwind";},Na=!1,D=null,Sa=0,B=
null,Ta=0,La=0,Ma=0,Xa=0,Ua=[],Ya=[],Za=[];function ab(){D=null;Sa++}var G=0;function Pa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===G)G=b+1E3/60;else for(;b+2>=G;)G+=1E3/60;setTimeout(a,Math.max(G-b,0))}}var Wa={},Oa,E,Qa,Va;function bb(a){var b=H.Gb[a];b.target.removeEventListener(b.Fb,b.kc,b.Hb);H.Gb.splice(a,1)}
function cb(){if(navigator.userActivation?navigator.userActivation.isActive:H.Vb&&H.xc.Tb){var a=H.Kb;H.Kb=[];for(var b of a)b.Yb(...b.ec)}}function I(a){if(!a.target)return-4;if(a.Ib)a.kc=function(c){++H.Vb;H.xc=a;cb();a.Jb(c);cb();--H.Vb},a.target.addEventListener(a.Fb,a.kc,a.Hb),H.Gb.push(a);else for(var b=0;b<H.Gb.length;++b)H.Gb[b].target==a.target&&H.Gb[b].Fb==a.Fb&&bb(b--);return 0}function db(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var H={Hc:0,Qc:0,Wb:0,Rb:0,bc:0,$b:0,Ub:0,Lc:0,Uc:0,Kc:0,Oc:0,Xb:0,cd:0,Zb:0,Sc(a,b,c){q.set(q.subarray(b,b+c),a)},Wc(){for(;H.Gb.length;)bb(H.Gb.length-1);H.Kb=[]},Vb:0,Kb:[],Jc(a,b,c){function d(k,g){if(k.length!=g.length)return!1;for(var m in k)if(k[m]!=g[m])return!1;return!0}for(var e of H.Kb)if(e.Yb==a&&d(e.ec,c))return;H.Kb.push({Yb:a,oc:b,ec:c});H.Kb.sort((k,g)=>k.oc<g.oc)},Yc(a){H.Kb=H.Kb.filter(b=>b.Yb!=a)},Gb:[],Xc:(a,b)=>{for(var c=0;c<H.Gb.length;++c)H.Gb[c].target!=a||b&&b!=H.Gb[c].Fb||
bb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},eb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,J=(a=0,b=NaN)=>{var c=t,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&eb)return eb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var k=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var g=c[a++]&63;e=224==(e&240)?(e&15)<<12|k<<6|g:(e&7)<<18|k<<12|g<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=
65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},fb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?J(a):"":a;return fb[a]||("undefined"!=typeof document?document.querySelector(a):null)},gb=a=>0>fb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},hb=[],ib,L=a=>{var b=hb[a];b||(a>=hb.length&&(hb.length=a+1),hb[a]=b=ib.get(a));return b},M=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<
a.length;++k){var g=a.charCodeAt(k);if(55296<=g&&57343>=g){var m=a.charCodeAt(++k);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},jb=(a,b,c,d,e,k)=>{H.Ub||(H.Ub=N(256));a={target:K(a),Fb:k,Ib:d,Jb:(g=event)=>{var m=g.target.id?g.target.id:"",p=H.Ub;M(db(g.target),p+0,128);
M(m,p+128,128);L(d)(e,p,b)&&g.preventDefault()},Hb:c};return I(a)},kb=(a,b,c,d,e,k)=>{H.Wb||(H.Wb=N(160));a={target:K(a),Fb:k,Ib:d,Jb:g=>{var m=H.Wb;x[m>>3]=g.timeStamp;var p=m>>2;u[p+2]=g.location;q[m+12]=g.ctrlKey;q[m+13]=g.shiftKey;q[m+14]=g.altKey;q[m+15]=g.metaKey;q[m+16]=g.repeat;u[p+5]=g.charCode;u[p+6]=g.keyCode;u[p+7]=g.which;M(g.key||"",m+32,32);M(g.code||"",m+64,32);M(g.char||"",m+96,32);M(g.locale||"",m+128,32);L(d)(e,m,b)&&g.preventDefault()},Hb:c};return I(a)},lb=(a,b,c)=>{x[a>>3]=b.timeStamp;
var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;q[a+24]=b.ctrlKey;q[a+25]=b.shiftKey;q[a+26]=b.altKey;q[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=gb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,k)=>{H.Rb||(H.Rb=N(64));a=K(a);return I({target:a,Tb:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Fb:k,Ib:d,Jb:(g=event)=>{lb(H.Rb,g,a);L(d)(e,H.Rb,b)&&g.preventDefault()},Hb:c})},mb=(a,b,
c,d,e)=>{H.Xb||(H.Xb=N(257));return I({target:a,Fb:e,Ib:d,Jb:(k=event)=>{var g=H.Xb,m=document.pointerLockElement||document.Mb||document.dc||document.cc;q[g]=!!m;var p=m?.id||"";M(db(m),g+1,128);M(p,g+129,128);L(d)(20,g,b)&&k.preventDefault()},Hb:c})},nb=(a,b,c,d,e)=>I({target:a,Fb:e,Ib:d,Jb:(k=event)=>{L(d)(38,0,b)&&k.preventDefault()},Hb:c}),ob=(a,b,c,d)=>{H.$b||(H.$b=N(36));a=K(a);return I({target:a,Fb:"resize",Ib:d,Jb:(e=event)=>{if(e.target==a){var k=document.body;if(k){var g=H.$b;u[g>>2]=0;
u[g+4>>2]=k.clientWidth;u[g+8>>2]=k.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;L(d)(10,g,b)&&e.preventDefault()}}},Hb:c})},pb=(a,b,c,d,e,k)=>{H.Zb||(H.Zb=N(1552));a=K(a);return I({target:a,Tb:"touchstart"==k||"touchend"==k,Fb:k,Ib:d,Jb:g=>{var m={},p=g.touches;for(var r of p)r.lc=r.nc=0,m[r.identifier]=r;for(var F of g.changedTouches)F.lc=1,m[F.identifier]=F;for(var qa of g.targetTouches)m[qa.identifier].nc=
1;p=H.Zb;x[p>>3]=g.timeStamp;q[p+12]=g.ctrlKey;q[p+13]=g.shiftKey;q[p+14]=g.altKey;q[p+15]=g.metaKey;r=p+16;F=gb(a);qa=0;for(let C of Object.values(m))if(m=r>>2,u[m]=C.identifier,u[m+1]=C.screenX,u[m+2]=C.screenY,u[m+3]=C.clientX,u[m+4]=C.clientY,u[m+5]=C.pageX,u[m+6]=C.pageY,q[r+28]=C.lc,q[r+29]=C.nc,u[m+8]=C.clientX-(F.left|0),u[m+9]=C.clientY-(F.top|0),r+=48,31<++qa)break;u[p+8>>2]=qa;L(d)(e,p,b)&&g.preventDefault()},Hb:c})},P,qb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=
(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=(c,d,e,k,g)=>b.drawElementsInstancedANGLE(c,d,e,k,g))},rb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},sb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,
d)=>b.drawBuffersWEBGL(c,d))},tb=a=>{a.Mc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},ub=a=>{a.Rc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},vb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},wb=1,Q=[],R=[],xb=[],yb=[],zb=[],S=[],Ab=[],Bb=[],Cb=[],Db={},Eb=a=>{for(var b=wb++,c=a.length;c<b;c++)a[c]=null;return b},Fb=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=P[c](),g=k&&Eb(d);k?(k.name=g,d[g]=k):T||=1282;u[b+4*e>>2]=g}},Hb=(a,b)=>{a.Mb||(a.Mb=a.getContext,a.getContext=function(d,e){e=a.Mb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.mc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Gb(c,b):0},Gb=(a,b)=>{var c=Eb(Bb),d={handle:c,attributes:b,version:b.mc,Sb:a};a.canvas&&(a.canvas.Fc=d);Bb[c]=d;("undefined"==typeof b.jc||b.jc)&&Ib(d);return c},Ib=a=>{a||=U;if(!a.Cc){a.Cc=!0;var b=a.Sb;b.Dc=b.getExtension("WEBGL_multi_draw");b.Bc=b.getExtension("EXT_polygon_offset_clamp");b.Ac=b.getExtension("EXT_clip_control");b.Ec=b.getExtension("WEBGL_polygon_mode");qb(b);rb(b);sb(b);tb(b);ub(b);2<=a.version&&(b.ic=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.ic)b.ic=
b.getExtension("EXT_disjoint_timer_query");vb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,U,Jb=(a,b,c,d,e,k)=>{a={target:K(a),Fb:k,Ib:d,Jb:(g=event)=>{L(d)(e,0,b)&&g.preventDefault()},Hb:c};I(a)},Kb=(a,b,c,d)=>{H.bc||(H.bc=N(96));return I({target:a,Tb:!0,Fb:"wheel",Ib:d,Jb:(e=event)=>{var k=H.bc;lb(k,e,a);x[k+64>>3]=e.deltaX;x[k+72>>3]=e.deltaY;x[k+80>>3]=e.deltaZ;u[k+88>>2]=e.deltaMode;L(d)(9,k,b)&&e.preventDefault()},Hb:c})},Lb=["default","low-power",
"high-performance"],Mb=()=>{var a=vb(P);return a=a.concat(a.map(b=>"GL_"+b))},Nb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>U.version){T||=1282;return}c=Mb().length;break;case 33307:case 33308:if(2>U.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=P.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=
1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;l(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);
return}}break;default:T||=1280;l(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else T||=1281},Ob=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Pb=a=>{var b=Ob(a)+1,c=N(b);c&&M(a,c,b);return c},Qb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Rb=[],V=a=>{var b=P.yc;if(b){var c=b.Nb[a];"number"==typeof c&&(b.Nb[a]=c=P.getUniformLocation(b,b.vc[a]+
(0<c?`[${c}]`:"")));return c}T||=1282},W=[],X=[],Tb=a=>{var b=Ob(a)+1,c=Sb(b);M(a,c,b);return c},Wb=a=>{var b=Ub();a();Vb(b)};f.requestAnimationFrame=Pa;f.pauseMainLoop=ab;f.resumeMainLoop=function(){Sa++;var a=La,b=Ma,c=B;B=null;$a(c,0,!1,Ta,!0);Ra(a,b);D()};f.preMainLoop&&Ya.push(f.preMainLoop);f.postMainLoop&&Za.push(f.postMainLoop);for(var Y=0;32>Y;++Y)Rb.push(Array(Y));var Xb=new Float32Array(288);for(Y=0;288>=Y;++Y)W[Y]=Xb.subarray(0,Y);var Yb=new Int32Array(288);
for(Y=0;288>=Y;++Y)X[Y]=Yb.subarray(0,Y);
var ec={Wa:()=>xa(""),Ta:()=>{Ea=!1;Fa=0},Ua:(a,b)=>{A[a]&&(clearTimeout(A[a].id),delete A[a]);if(!b)return 0;var c=setTimeout(()=>{delete A[a];Ka(()=>Zb(a,performance.now()))},b);A[a]={id:c,bd:b};return 0},Ia:()=>{ab();B=null},$:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ba:(a,b,c)=>{a=K(a);if(!a)return-4;a=gb(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},Ja:()=>performance.now(),Qa:(a,b)=>{function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Va:a=>{var b=
t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ma.buffer.byteLength+65535)/65536|0;try{ma.grow(d);ra();var e=1;break a}catch(k){}e=void 0}if(e)return!0}return!1},J:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),_:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},K:(a,b,c,d)=>jb(a,b,c,d,13,"focus"),T:(a,b,c,d)=>kb(a,b,c,d,2,"keydown"),R:(a,b,c,d)=>kb(a,b,c,d,1,"keypress"),S:(a,
b,c,d)=>kb(a,b,c,d,3,"keyup"),Ra:(a,b,c)=>{a=L(a);$a(a,b,c)},Z:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),W:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),V:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),X:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),Y:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),M:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Mb||document.body.dc||document.body.cc))return-1;a=K(a);if(!a)return-4;mb(a,b,c,d,"mozpointerlockchange");mb(a,b,c,d,"webkitpointerlockchange");mb(a,b,c,d,
"mspointerlockchange");return mb(a,b,c,d,"pointerlockchange")},L:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.Mb||document.body.dc||document.body.cc))return-1;a=K(a);if(!a)return-4;nb(a,b,c,d,"mozpointerlockerror");nb(a,b,c,d,"webkitpointerlockerror");nb(a,b,c,d,"mspointerlockerror");return nb(a,b,c,d,"pointerlockerror")},aa:(a,b,c,d)=>ob(a,b,c,d),N:(a,b,c,d)=>pb(a,b,c,d,25,"touchcancel"),O:(a,b,c,d)=>pb(a,b,c,d,23,"touchend"),P:(a,b,c,d)=>pb(a,b,c,d,24,"touchmove"),
Q:(a,b,c,d)=>pb(a,b,c,d,22,"touchstart"),I:(a,b,c,d)=>{Jb(a,b,c,d,31,"webglcontextlost");return 0},H:(a,b,c,d)=>{Jb(a,b,c,d,32,"webglcontextrestored");return 0},U:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?Kb(a,b,c,d):-1:-4,Pa:(a,b)=>{var c=b>>2;b={alpha:!!q[b+0],depth:!!q[b+1],stencil:!!q[b+2],antialias:!!q[b+3],premultipliedAlpha:!!q[b+4],preserveDrawingBuffer:!!q[b+5],powerPreference:Lb[u[c+2]],failIfMajorPerformanceCaveat:!!q[b+12],mc:u[c+4],Tc:u[c+5],jc:q[b+24],zc:q[b+25],Vc:u[c+7],Zc:q[b+
32]};a=K(a);return!a||b.zc?0:Hb(a,b)},Ma:(a,b)=>{a=Bb[a];b=b?J(b):"";b.startsWith("GL_")&&(b=b.slice(3));"ANGLE_instanced_arrays"==b&&qb(P);"OES_vertex_array_object"==b&&rb(P);"WEBGL_draw_buffers"==b&&sb(P);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&tb(P);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&ub(P);"WEBGL_multi_draw"==b&&(P.Dc=P.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(P.Bc=P.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&(P.Ac=
P.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(P.Ec=P.getExtension("WEBGL_polygon_mode"));return!!a.Sb.getExtension(b)},Oa:a=>{U=Bb[a];f.ctx=P=U?.Sb;return!a||P?0:-5},i:a=>P.activeTexture(a),x:(a,b)=>{P.attachShader(R[a],S[b])},b:(a,b)=>{35051==a?P.fc=b:35052==a&&(P.hc=b);P.bindBuffer(a,Q[b])},a:(a,b,c)=>{P.bindBufferBase(a,b,Q[c])},k:(a,b)=>{P.bindFramebuffer(a,xb[b])},h:(a,b)=>{P.bindSampler(a,Cb[b])},c:(a,b)=>{P.bindTexture(a,zb[b])},G:a=>{P.bindVertexArray(Ab[a])},C:(a,b,c,d)=>
P.blendColor(a,b,c,d),D:(a,b)=>P.blendEquationSeparate(a,b),E:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),Ya:(a,b,c,d,e,k,g,m,p,r)=>P.blitFramebuffer(a,b,c,d,e,k,g,m,p,r),ua:(a,b,c,d)=>{2<=U.version?c&&b?P.bufferData(a,t,d,c,b):P.bufferData(a,b,d):P.bufferData(a,c?t.subarray(c,c+b):b,d)},ta:(a,b,c,d)=>{2<=U.version?c&&P.bufferSubData(a,b,t,d,c):P.bufferSubData(a,b,t.subarray(d,d+c))},fa:(a,b,c,d)=>P.clearBufferfi(a,b,c,d),t:(a,b,c)=>{P.clearBufferfv(a,b,w,c>>2)},ea:(a,b,c)=>{P.clearBufferiv(a,b,u,c>>
2)},j:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},la:a=>{P.compileShader(S[a])},sa:()=>{var a=Eb(R),b=P.createProgram();b.name=a;b.Qb=b.Ob=b.Pb=0;b.ac=1;R[a]=b;return a},na:a=>{var b=Eb(S);S[b]=P.createShader(a);return b},z:a=>P.cullFace(a),Aa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(P.deleteBuffer(e),e.name=0,Q[d]=null,d==P.fc&&(P.fc=0),d==P.hc&&(P.hc=0))}},g:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=xb[d];e&&(P.deleteFramebuffer(e),e.name=0,xb[d]=null)}},y:a=>{if(a){var b=
R[a];b?(P.deleteProgram(b),b.name=0,R[a]=null):T||=1281}},ya:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=yb[d];e&&(P.deleteRenderbuffer(e),e.name=0,yb[d]=null)}},xa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Cb[d];e&&(P.deleteSampler(e),e.name=0,Cb[d]=null)}},m:a=>{if(a){var b=S[a];b?(P.deleteShader(b),S[a]=null):T||=1281}},za:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=zb[d];e&&(P.deleteTexture(e),e.name=0,zb[d]=null)}},wa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];P.deleteVertexArray(Ab[d]);
Ab[d]=null}},q:a=>P.depthFunc(a),p:a=>{P.depthMask(!!a)},e:a=>P.disable(a),F:a=>{P.disableVertexAttribArray(a)},_a:(a,b,c)=>{P.drawArrays(a,b,c)},$a:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},ab:(a,b,c,d)=>{P.drawElements(a,b,c,d)},bb:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},f:a=>P.enable(a),lb:a=>{P.enableVertexAttribArray(a)},A:a=>P.frontFace(a),va:(a,b)=>{Fb(a,b,"createBuffer",Q)},Ha:(a,b)=>{Fb(a,b,"createVertexArray",Ab)},ia:(a,b)=>P.getAttribLocation(R[a],b?J(b):""),d:(a,b)=>Nb(a,b),
pa:(a,b,c,d)=>{a=P.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},w:(a,b,c)=>{if(c)if(a>=wb)T||=1281;else if(a=R[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.Qb){var d=P.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Qb=Math.max(a.Qb,P.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.Qb}else if(35722==b){if(!a.Ob)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.Ob=Math.max(a.Ob,P.getActiveAttrib(a,
b).name.length+1);u[c>>2]=a.Ob}else if(35381==b){if(!a.Pb)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.Pb=Math.max(a.Pb,P.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Pb}else u[c>>2]=P.getProgramParameter(a,b);else T||=1281},ka:(a,b,c,d)=>{a=P.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},u:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(S[a]),u[c>>2]=a?a.length+
1:0):u[c>>2]=P.getShaderParameter(S[a],b):T||=1281},Fa:(a,b)=>{if(2>U.version)return T||=1282,0;var c=Db[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Mb().map(Pb),c=Db[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},v:(a,b)=>{b=b?J(b):"";if(a=R[a]){var c=a,d=c.Nb,e=c.wc,k;if(!d){c.Nb=d={};c.vc={};var g=P.getProgramParameter(c,35718);for(k=0;k<g;++k){var m=P.getActiveUniform(c,k);var p=m.name;m=m.size;var r=Qb(p);r=0<r?p.slice(0,r):p;var F=c.ac;
c.ac+=m;e[r]=[m,F];for(p=0;p<m;++p)d[F]=p,c.vc[F++]=r}}c=a.Nb;d=0;e=b;k=Qb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.wc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else T||=1281;return-1},Xa:(a,b,c)=>{for(var d=Rb[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];P.invalidateFramebuffer(a,d)},ra:a=>{a=R[a];P.linkProgram(a);a.Nb=0;a.wc={}},Ga:(a,b)=>{P.pixelStorei(a,b)},B:(a,b)=>P.polygonOffset(a,b),Za:a=>P.readBuffer(a),ga:(a,b,c,d)=>P.scissor(a,b,c,d),ma:(a,b,c,d)=>{for(var e=
"",k=0;k<b;++k){var g=(g=v[c+4*k>>2])?J(g,d?v[d+4*k>>2]:void 0):"";e+=g}P.shaderSource(S[a],e)},Da:(a,b,c)=>P.stencilFunc(a,b,c),s:(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),o:a=>P.stencilMask(a),Ca:(a,b,c)=>P.stencilOp(a,b,c),r:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),kb:(a,b,c)=>{if(2<=U.version)b&&P.uniform1fv(V(a),w,c>>2,b);else{if(288>=b)for(var d=W[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);P.uniform1fv(V(a),d)}},oa:(a,b)=>{P.uniform1i(V(a),b)},gb:(a,b,c)=>{if(2<=U.version)b&&
P.uniform1iv(V(a),u,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);P.uniform1iv(V(a),d)}},jb:(a,b,c)=>{if(2<=U.version)b&&P.uniform2fv(V(a),w,c>>2,2*b);else{if(144>=b){b*=2;for(var d=W[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);P.uniform2fv(V(a),d)}},fb:(a,b,c)=>{if(2<=U.version)b&&P.uniform2iv(V(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=
u.subarray(c>>2,c+8*b>>2);P.uniform2iv(V(a),d)}},ib:(a,b,c)=>{if(2<=U.version)b&&P.uniform3fv(V(a),w,c>>2,3*b);else{if(96>=b){b*=3;for(var d=W[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);P.uniform3fv(V(a),d)}},eb:(a,b,c)=>{if(2<=U.version)b&&P.uniform3iv(V(a),u,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);P.uniform3iv(V(a),
d)}},hb:(a,b,c)=>{if(2<=U.version)b&&P.uniform4fv(V(a),w,c>>2,4*b);else{if(72>=b){var d=W[4*b],e=w;c>>=2;b*=4;for(var k=0;k<b;k+=4){var g=c+k;d[k]=e[g];d[k+1]=e[g+1];d[k+2]=e[g+2];d[k+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);P.uniform4fv(V(a),d)}},db:(a,b,c)=>{if(2<=U.version)b&&P.uniform4iv(V(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=X[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);P.uniform4iv(V(a),
d)}},cb:(a,b,c,d)=>{if(2<=U.version)b&&P.uniformMatrix4fv(V(a),!!c,w,d>>2,16*b);else{if(18>=b){var e=W[16*b],k=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var m=d+g;e[g]=k[m];e[g+1]=k[m+1];e[g+2]=k[m+2];e[g+3]=k[m+3];e[g+4]=k[m+4];e[g+5]=k[m+5];e[g+6]=k[m+6];e[g+7]=k[m+7];e[g+8]=k[m+8];e[g+9]=k[m+9];e[g+10]=k[m+10];e[g+11]=k[m+11];e[g+12]=k[m+12];e[g+13]=k[m+13];e[g+14]=k[m+14];e[g+15]=k[m+15]}}else e=w.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(V(a),!!c,e)}},l:a=>{a=R[a];P.useProgram(a);P.yc=a},mb:(a,
b)=>{P.vertexAttribDivisor(a,b)},da:(a,b,c,d,e,k)=>{P.vertexAttribPointer(a,b,c,!!d,e,k)},ha:(a,b,c,d)=>P.viewport(a,b,c,d),Sa:Ha,ob:function(){f.pc=a=>{0!=$b()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.pc)},Na:function(){f.uc=a=>{const b=a.clipboardData.getData("text");Wb(()=>{const c=Tb(b);ac(c)})};window.addEventListener("paste",f.uc)},Ka:function(){f.$c=[];f.qc=b=>{b.stopPropagation();b.preventDefault()};f.rc=b=>{b.stopPropagation();b.preventDefault()};
f.sc=b=>{b.stopPropagation();b.preventDefault()};f.tc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.ad=c;bc(c.length);for(let e=0;e<c.length;e++)Wb(()=>{const k=Tb(c[e].name);cc(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);dc(b.clientX,b.clientY,d)};const a=f.Lb;a.addEventListener("dragenter",f.qc,!1);a.addEventListener("dragleave",f.rc,!1);a.addEventListener("dragover",f.sc,!1);a.addEventListener("drop",f.tc,!1)},qa:function(){const a=
document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ba:function(a,b){0!==b&&(document.title=b?J(b):"");a=a?J(a):"";void 0!==f.canvas&&("object"===typeof f.canvas?fb[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.Lb=K(a);f.Lb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.Lb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},nb:function(){window.removeEventListener("beforeunload",
f.pc)},La:function(){window.removeEventListener("paste",f.uc)},Ea:function(){const a=f.Lb;a.removeEventListener("dragenter",f.qc);a.removeEventListener("dragleave",f.rc);a.removeEventListener("dragover",f.sc);a.removeEventListener("drop",f.tc)},n:function(){f.Lb&&f.Lb.requestPointerLock&&f.Lb.requestPointerLock()},ja:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(t.subarray(c,c+a*b*4));e.putImageData(k,0,
0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},ca:function(a,b){b=b?J(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;ma=Z.pb;ra();ib=Z.Bb;ta.unshift(Z.qb);y--;f.monitorRunDependencies?.(y);0==y&&z&&(c=z,z=null,c());return Z}y++;f.monitorRunDependencies?.(y);var b={a:ec};if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return l(`Module.instantiateWasm callback failed with error: ${c}`),!1}ya??=pa("noentry-sapp.wasm")?"noentry-sapp.wasm":f.locateFile?f.locateFile("noentry-sapp.wasm",h):h+"noentry-sapp.wasm";return a((await Ba(b)).instance)})();
var fc=f._main=(a,b)=>(fc=f._main=Z.rb)(a,b),ac=f.__sapp_emsc_onpaste=a=>(ac=f.__sapp_emsc_onpaste=Z.sb)(a),$b=f.__sapp_html5_get_ask_leave_site=()=>($b=f.__sapp_html5_get_ask_leave_site=Z.tb)(),bc=f.__sapp_emsc_begin_drop=a=>(bc=f.__sapp_emsc_begin_drop=Z.ub)(a),cc=f.__sapp_emsc_drop=(a,b)=>(cc=f.__sapp_emsc_drop=Z.vb)(a,b),dc=f.__sapp_emsc_end_drop=(a,b,c)=>(dc=f.__sapp_emsc_end_drop=Z.wb)(a,b,c);
f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,k,g,m)=>(f.__sapp_emsc_invoke_fetch_cb=Z.xb)(a,b,c,d,e,k,g,m);f.__saudio_emsc_pull=a=>(f.__saudio_emsc_pull=Z.yb)(a);var N=a=>(N=Z.zb)(a),Zb=(a,b)=>(Zb=Z.Ab)(a,b),Vb=a=>(Vb=Z.Cb)(a),Sb=a=>(Sb=Z.Db)(a),Ub=()=>(Ub=Z.Eb)();function gc(a=[]){var b=fc;a.unshift(fa);var c=a.length,d=Sb(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=Tb(g);e+=4});v[e>>2]=0;try{var k=b(c,d);Ia(k)}catch(g){Ga(g)}}
function hc(a=ea){function b(){f.calledRun=!0;if(!n){Da(ta);Da(ua);f.onRuntimeInitialized?.();f.noInitialRun||gc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();va.unshift(c)}Da(va)}}if(0<y)z=hc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)wa();Da(sa);0<y?z=hc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();hc();
