var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs"),ka=require("path");k=__dirname+"/";ja=a=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a)};ia=a=>{a=la(a)?new URL(a):ka.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&
document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?"":k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=a=>la(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var ma=f.print||console.log.bind(console),m=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);var na=f.wasmBinary,oa,p=!1,pa,r,t,qa,ra,u,v,x,y;
function sa(){var a=oa.buffer;f.HEAP8=r=new Int8Array(a);f.HEAP16=qa=new Int16Array(a);f.HEAPU8=t=new Uint8Array(a);f.HEAPU16=ra=new Uint16Array(a);f.HEAP32=u=new Int32Array(a);f.HEAPU32=v=new Uint32Array(a);f.HEAPF32=x=new Float32Array(a);f.HEAPF64=y=new Float64Array(a)}var ta=[],va=[],wa=[],xa=[];function ya(){var a=f.preRun.shift();ta.unshift(a)}var z=0,za=null,A=null;
function Aa(a){f.onAbort?.(a);a="Aborted("+a+")";m(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ba=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),Ca;function Da(a){if(a==Ca&&na)return new Uint8Array(na);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}function Ea(a){return na?Promise.resolve().then(()=>Da(a)):ia(a).then(b=>new Uint8Array(b),()=>Da(a))}
function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{m(`failed to asynchronously prepare wasm: ${d}`);Aa(d)})}function Ga(a,b){var c=Ca;na||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||la(c)||ca||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){m(`wasm streaming compile failed: ${e}`);m("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}
class Ha{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ia=a=>{for(;0<a.length;)a.shift()(f)},Ja=f.noExitRuntime||!0,Ka="undefined"!=typeof TextDecoder?new TextDecoder:void 0,B=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>
10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},La=0,Ma=[0,31,60,91,121,152,182,213,244,274,305,335],Na=[0,31,59,90,120,151,181,212,243,273,304,334],C={},Oa=a=>{a instanceof Ha||"unwind"==a||ha(1,a)},Pa=a=>{pa=a;Ja||0<La||(f.onExit?.(a),p=!0);ha(a,new Ha(a))},Qa=a=>{pa=a;Pa(a)},Ra=()=>{if(!(Ja||0<La))try{var a=pa;pa=a;Pa(a)}catch(b){Oa(b)}},Sa=a=>{if(!p)try{a(),Ra()}catch(b){Oa(b)}},D=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);
if(55296<=g&&57343>=g){var l=a.charCodeAt(++h);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},Za=(a,b)=>{Ta=a;Ua=b;if(E)if(Va||=!0,0==a)G=function(){setTimeout(H,Math.max(0,Wa+b-performance.now())|0)};else if(1==a)G=function(){Xa(H)};else if(2==a){if("undefined"==typeof Ya)if("undefined"==
typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ya=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ya=setImmediate;G=function(){Ya(H)}}},hb=(a,b,c,d,e)=>{function h(){return g<$a?(Ra(),!1):!0}E=a;ab=d;var g=$a;Va=!1;H=function(){if(!p)if(0<bb.length){var l=bb.shift();
l.yd(l.od);if(cb){var n=cb,q=0==n%1?n-1:Math.floor(n);cb=l.qd?q:(8*n+(q+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",n=cb??0,q=db.wd??0,n?n<q?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));h()&&setTimeout(H,0)}else if(h())if(eb=eb+1|0,1==Ta&&1<Ua&&0!=eb%Ua)G();else{0==Ta&&(Wa=performance.now());a:if(!p){for(l of fb)if(!1===l())break a;Sa(a);for(n of gb)n()}h()&&G()}};e||(b&&0<b?Za(0,1E3/b):Za(1,1),G());if(c)throw"unwind";},Va=!1,G=null,$a=
0,E=null,ab=0,Ta=0,Ua=0,eb=0,bb=[],fb=[],gb=[];function ib(){G=null;$a++}var I=0;function Xa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===I)I=b+1E3/60;else for(;b+2>=I;)I+=1E3/60;setTimeout(a,Math.max(I-b,0))}}var db={},Wa,H,Ya,cb;function jb(a){var b=J.nc[a];b.target.removeEventListener(b.mc,b.Pc,b.oc);J.nc.splice(a,1)}
function kb(){if(navigator.userActivation?navigator.userActivation.isActive:J.Dc&&J.dd.Bc){var a=J.sc;J.sc=[];for(var b of a)b.Gc(...b.Lc)}}function K(a){if(!a.target)return-4;if(a.pc)a.Pc=function(c){++J.Dc;J.dd=a;kb();a.qc(c);kb();--J.Dc},a.target.addEventListener(a.mc,a.Pc,a.oc),J.nc.push(a);else for(var b=0;b<J.nc.length;++b)J.nc[b].target==a.target&&J.nc[b].mc==a.mc&&jb(b--);return 0}function lb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var J={pd:0,zd:0,Ec:0,zc:0,Kc:0,Ic:0,Cc:0,ud:0,Dd:0,td:0,xd:0,Fc:0,Md:0,Hc:0,Bd(a,b,c){r.set(r.subarray(b,b+c),a)},Fd(){for(;J.nc.length;)jb(J.nc.length-1);J.sc=[]},Dc:0,sc:[],sd(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var l in h)if(h[l]!=g[l])return!1;return!0}for(var e of J.sc)if(e.Gc==a&&d(e.Lc,c))return;J.sc.push({Gc:a,Vc:b,Lc:c});J.sc.sort((h,g)=>h.Vc<g.Vc)},Hd(a){J.sc=J.sc.filter(b=>b.Gc!=a)},nc:[],Gd:(a,b)=>{for(var c=0;c<J.nc.length;++c)J.nc[c].target!=a||b&&b!=J.nc[c].mc||
jb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},mb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],L=a=>{a=2<a?a?B(t,a):"":a;return mb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},nb=a=>0>mb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},ob=[],pb,M=a=>{var b=ob[a];b||(a>=ob.length&&(ob.length=a+1),ob[a]=b=pb.get(a));return b},qb=(a,b,c,d,e,h)=>{J.Cc||(J.Cc=N(256));a={target:L(a),mc:h,pc:d,
qc:(g=event)=>{var l=g.target.id?g.target.id:"",n=J.Cc;D(lb(g.target),n+0,128);D(l,n+128,128);M(d)(e,n,b)&&g.preventDefault()},oc:c};return K(a)},rb=(a,b,c,d,e,h)=>{J.Ec||(J.Ec=N(160));a={target:L(a),mc:h,pc:d,qc:g=>{var l=J.Ec;y[l>>3]=g.timeStamp;var n=l>>2;u[n+2]=g.location;r[l+12]=g.ctrlKey;r[l+13]=g.shiftKey;r[l+14]=g.altKey;r[l+15]=g.metaKey;r[l+16]=g.repeat;u[n+5]=g.charCode;u[n+6]=g.keyCode;u[n+7]=g.which;D(g.key||"",l+32,32);D(g.code||"",l+64,32);D(g.char||"",l+96,32);D(g.locale||"",l+128,
32);M(d)(e,l,b)&&g.preventDefault()},oc:c};return K(a)},sb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;qa[2*d+14]=b.button;qa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=nb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,h)=>{J.zc||(J.zc=N(64));a=L(a);return K({target:a,Bc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,mc:h,
pc:d,qc:(g=event)=>{sb(J.zc,g,a);M(d)(e,J.zc,b)&&g.preventDefault()},oc:c})},tb=(a,b,c,d,e)=>{J.Fc||(J.Fc=N(257));return K({target:a,mc:e,pc:d,qc:(h=event)=>{var g=J.Fc,l=document.pointerLockElement||document.uc||document.Tc||document.Sc;r[g]=!!l;var n=l?.id||"";D(lb(l),g+1,128);D(n,g+129,128);M(d)(20,g,b)&&h.preventDefault()},oc:c})},ub=(a,b,c,d,e)=>K({target:a,mc:e,pc:d,qc:(h=event)=>{M(d)(38,0,b)&&h.preventDefault()},oc:c}),vb=(a,b,c,d)=>{J.Ic||(J.Ic=N(36));a=L(a);return K({target:a,mc:"resize",
pc:d,qc:(e=event)=>{if(e.target==a){var h=document.body;if(h){var g=J.Ic;u[g>>2]=0;u[g+4>>2]=h.clientWidth;u[g+8>>2]=h.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;M(d)(10,g,b)&&e.preventDefault()}}},oc:c})},wb=(a,b,c,d,e,h)=>{J.Hc||(J.Hc=N(1552));a=L(a);return K({target:a,Bc:"touchstart"==h||"touchend"==h,mc:h,pc:d,qc:g=>{var l={},n=g.touches;for(var q of n)q.Qc=q.Uc=0,l[q.identifier]=q;for(var w of g.changedTouches)w.Qc=
1,l[w.identifier]=w;for(var ua of g.targetTouches)l[ua.identifier].Uc=1;n=J.Hc;y[n>>3]=g.timeStamp;r[n+12]=g.ctrlKey;r[n+13]=g.shiftKey;r[n+14]=g.altKey;r[n+15]=g.metaKey;q=n+16;w=nb(a);ua=0;for(let F of Object.values(l))if(l=q>>2,u[l]=F.identifier,u[l+1]=F.screenX,u[l+2]=F.screenY,u[l+3]=F.clientX,u[l+4]=F.clientY,u[l+5]=F.pageX,u[l+6]=F.pageY,r[q+28]=F.Qc,r[q+29]=F.Uc,u[l+8]=F.clientX-(w.left|0),u[l+9]=F.clientY-(w.top|0),q+=48,31<++ua)break;u[n+8>>2]=ua;M(d)(e,n,b)&&g.preventDefault()},oc:c})},
P,xb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,d,e,h,g))},yb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},
zb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Ab=a=>{a.vd=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},Bb=a=>{a.Ad=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Cb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Db=1,Q=[],R=[],Eb=[],Fb=[],Gb=[],S=[],Hb=[],Ib=[],T=[],Jb={},Kb=4,Lb=0,Mb=a=>{for(var b=Db++,c=a.length;c<b;c++)a[c]=null;return b},Nb=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=P[c](),g=h&&Mb(d);h?(h.name=g,d[g]=h):U||=1282;u[b+4*e>>2]=g}},Pb=(a,b)=>{a.uc||(a.uc=a.getContext,a.getContext=function(d,e){e=a.uc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Rc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?Ob(c,b):0},Ob=(a,b)=>{var c=Mb(Ib),d={handle:c,attributes:b,version:b.Rc,Ac:a};a.canvas&&(a.canvas.nd=d);Ib[c]=d;("undefined"==typeof b.Oc||b.Oc)&&Qb(d);return c},Qb=a=>{a||=V;if(!a.kd){a.kd=!0;var b=a.Ac;b.ld=b.getExtension("WEBGL_multi_draw");b.jd=b.getExtension("EXT_polygon_offset_clamp");b.hd=b.getExtension("EXT_clip_control");b.md=b.getExtension("WEBGL_polygon_mode");xb(b);yb(b);zb(b);Ab(b);Bb(b);2<=a.version&&(b.Nc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||
!b.Nc)b.Nc=b.getExtension("EXT_disjoint_timer_query");Cb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},U,V,Rb=(a,b,c,d,e,h)=>{a={target:L(a),mc:h,pc:d,qc:(g=event)=>{M(d)(e,0,b)&&g.preventDefault()},oc:c};K(a)},Sb=(a,b,c,d)=>{J.Kc||(J.Kc=N(96));return K({target:a,Bc:!0,mc:"wheel",pc:d,qc:(e=event)=>{var h=J.Kc;sb(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+80>>3]=e.deltaZ;u[h+88>>2]=e.deltaMode;M(d)(9,h,b)&&e.preventDefault()},oc:c})},Tb=["default","low-power",
"high-performance"],Ub={},Wb=()=>{if(!Vb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in Ub)void 0===Ub[b]?delete a[b]:a[b]=Ub[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Vb=c}return Vb},Vb,Xb=[null,[],[]];function Yb(){var a=Cb(P);return a=a.concat(a.map(b=>"GL_"+b))}
var Zb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=Yb().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=P.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else U||=1281},$b=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ac=a=>{var b=$b(a)+1,c=N(b);c&&D(a,c,b);return c},bc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),cc=[],dc=a=>{a-=5120;return 0==a?r:1==a?t:2==a?qa:4==a?u:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?v:ra},W=a=>{var b=P.ed;if(b){var c=b.vc[a];"number"==typeof c&&(b.vc[a]=c=P.getUniformLocation(b,b.bd[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],ec=[],gc=a=>{var b=$b(a)+
1,c=fc(b);D(a,c,b);return c},jc=a=>{var b=hc();a();ic(b)};f.requestAnimationFrame=Xa;f.pauseMainLoop=ib;f.resumeMainLoop=function(){$a++;var a=Ta,b=Ua,c=E;E=null;hb(c,0,!1,ab,!0);Za(a,b);G()};f.preMainLoop&&fb.push(f.preMainLoop);f.postMainLoop&&gb.push(f.postMainLoop);for(var Y=0;32>Y;++Y)cc.push(Array(Y));var kc=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=kc.subarray(0,Y);var lc=new Int32Array(288);for(Y=0;288>=Y;++Y)ec[Y]=lc.subarray(0,Y);
var sc={fa:function(){return 0},ib:function(){return 0},jb:function(){},ob:()=>{Aa("")},mb:(a,b,c)=>t.copyWithin(a,b,b+c),cb:()=>{Ja=!1;La=0},$a:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));u[c>>2]=a.getSeconds();u[c+4>>2]=a.getMinutes();u[c+8>>2]=a.getHours();u[c+12>>2]=a.getDate();u[c+16>>2]=a.getMonth();u[c+20>>2]=a.getFullYear()-1900;u[c+24>>2]=a.getDay();b=a.getFullYear();u[c+28>>2]=(0!==b%4||0===b%100&&0!==b%400?Na:Ma)[a.getMonth()]+a.getDate()-1|0;u[c+
36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();u[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},db:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Sa(()=>mc(a,performance.now()))},b);C[a]={id:c,Ld:b};return 0},fb:(a,b,c,d)=>{var e=(new Date).getFullYear(),h=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();v[a>>
2]=60*Math.max(h,e);u[b>>2]=Number(h!=e);b=g=>{var l=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(h);b=b(e);e<h?(D(a,c,17),D(b,d,17)):(D(a,d,17),D(b,c,17))},Ra:()=>{ib();E=null},nb:()=>Date.now(),ca:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ga:(a,b,c)=>{a=L(a);if(!a)return-4;a=nb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Sa:()=>performance.now(),Za:(a,b)=>{function c(d){M(a)(d,b)&&requestAnimationFrame(c)}
return requestAnimationFrame(c)},eb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},M:(a,b,c,d)=>qb(a,b,c,d,12,"blur"),ba:(a,b,c)=>{a=L(a);if(!a)return-4;a.width=b;a.height=c;return 0},N:(a,b,c,d)=>qb(a,b,c,d,13,"focus"),W:(a,b,c,d)=>rb(a,b,c,d,2,"keydown"),
U:(a,b,c,d)=>rb(a,b,c,d,1,"keypress"),V:(a,b,c,d)=>rb(a,b,c,d,3,"keyup"),_a:(a,b,c)=>{a=M(a);hb(a,b,c)},aa:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),Z:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),Y:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),_:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),$:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),P:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.uc||document.body.Tc||document.body.Sc))return-1;a=L(a);if(!a)return-4;tb(a,b,c,d,"mozpointerlockchange");tb(a,
b,c,d,"webkitpointerlockchange");tb(a,b,c,d,"mspointerlockchange");return tb(a,b,c,d,"pointerlockchange")},O:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.uc||document.body.Tc||document.body.Sc))return-1;a=L(a);if(!a)return-4;ub(a,b,c,d,"mozpointerlockerror");ub(a,b,c,d,"webkitpointerlockerror");ub(a,b,c,d,"mspointerlockerror");return ub(a,b,c,d,"pointerlockerror")},da:(a,b,c,d)=>vb(a,b,c,d),Q:(a,b,c,d)=>wb(a,b,c,d,25,"touchcancel"),R:(a,b,c,d)=>wb(a,b,c,d,23,"touchend"),
S:(a,b,c,d)=>wb(a,b,c,d,24,"touchmove"),T:(a,b,c,d)=>wb(a,b,c,d,22,"touchstart"),L:(a,b,c,d)=>{Rb(a,b,c,d,31,"webglcontextlost");return 0},K:(a,b,c,d)=>{Rb(a,b,c,d,32,"webglcontextrestored");return 0},X:(a,b,c,d)=>(a=L(a))?"undefined"!=typeof a.onwheel?Sb(a,b,c,d):-1:-4,Xa:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Tb[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Rc:u[c+4],Cd:u[c+
5],Oc:r[b+24],gd:r[b+25],Ed:u[c+7],Id:r[b+32]};a=L(a);return!a||b.gd?0:Pb(a,b)},Va:(a,b)=>{a=Ib[a];b=b?B(t,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&xb(P);"OES_vertex_array_object"==b&&yb(P);"WEBGL_draw_buffers"==b&&zb(P);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Ab(P);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Bb(P);"WEBGL_multi_draw"==b&&(P.ld=P.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(P.jd=P.getExtension("EXT_polygon_offset_clamp"));
"EXT_clip_control"==b&&(P.hd=P.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(P.md=P.getExtension("WEBGL_polygon_mode"));return!!a.Ac.getExtension(b)},Wa:a=>{V=Ib[a];f.rd=P=V?.Ac;return!a||P?0:-5},kb:(a,b)=>{var c=0;Wb().forEach((d,e)=>{var h=b+c;e=v[a+4*e>>2]=h;for(h=0;h<d.length;++h)r[e++]=d.charCodeAt(h);r[e]=0;c+=d.length+1});return 0},lb:(a,b)=>{var c=Wb();v[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);v[b>>2]=d;return 0},ea:()=>52,hb:()=>52,ab:function(){return 70},gb:(a,
b,c,d)=>{for(var e=0,h=0;h<c;h++){var g=v[b>>2],l=v[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=t[g+n],w=Xb[a];0===q||10===q?((1===a?ma:m)(B(w)),w.length=0):w.push(q)}e+=l}v[d>>2]=e;return 0},m:a=>P.activeTexture(a),x:(a,b)=>{P.attachShader(R[a],S[b])},b:(a,b)=>{35051==a?P.Mc=b:35052==a&&(P.tc=b);P.bindBuffer(a,Q[b])},a:(a,b,c)=>{P.bindBufferBase(a,b,Q[c])},p:(a,b)=>{P.bindFramebuffer(a,Eb[b])},Ca:(a,b)=>{P.bindRenderbuffer(a,Fb[b])},l:(a,b)=>{P.bindSampler(a,T[b])},c:(a,b)=>{P.bindTexture(a,Gb[b])},
J:a=>{P.bindVertexArray(Hb[a])},F:(a,b,c,d)=>P.blendColor(a,b,c,d),G:(a,b)=>P.blendEquationSeparate(a,b),H:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),qb:(a,b,c,d,e,h,g,l,n,q)=>P.blitFramebuffer(a,b,c,d,e,h,g,l,n,q),Fa:(a,b,c,d)=>{2<=V.version?c&&b?P.bufferData(a,t,d,c,b):P.bufferData(a,b,d):P.bufferData(a,c?t.subarray(c,c+b):b,d)},z:(a,b,c,d)=>{2<=V.version?c&&P.bufferSubData(a,b,t,d,c):P.bufferSubData(a,b,t.subarray(d,d+c))},Kb:(a,b,c,d)=>P.clearBufferfi(a,b,c,d),la:(a,b,c)=>{P.clearBufferfv(a,b,x,
c>>2)},Jb:(a,b,c)=>{P.clearBufferiv(a,b,u,c>>2)},n:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},Ob:a=>{P.compileShader(S[a])},wa:(a,b,c,d,e,h,g,l)=>{2<=V.version?P.tc||!g?P.compressedTexImage2D(a,b,c,d,e,h,g,l):P.compressedTexImage2D(a,b,c,d,e,h,t,l,g):P.compressedTexImage2D(a,b,c,d,e,h,t.subarray(l,l+g))},ua:(a,b,c,d,e,h,g,l,n)=>{P.tc?P.compressedTexImage3D(a,b,c,d,e,h,g,l,n):P.compressedTexImage3D(a,b,c,d,e,h,g,t,n,l)},ra:()=>{var a=Mb(R),b=P.createProgram();b.name=a;b.yc=b.wc=b.xc=0;b.Jc=1;R[a]=b;
return a},Qb:a=>{var b=Mb(S);S[b]=P.createShader(a);return b},C:a=>P.cullFace(a),Ja:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(P.deleteBuffer(e),e.name=0,Q[d]=null,d==P.Mc&&(P.Mc=0),d==P.tc&&(P.tc=0))}},j:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=Eb[d];e&&(P.deleteFramebuffer(e),e.name=0,Eb[d]=null)}},s:a=>{if(a){var b=R[a];b?(P.deleteProgram(b),b.name=0,R[a]=null):U||=1281}},A:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Fb[d];e&&(P.deleteRenderbuffer(e),e.name=0,Fb[d]=
null)}},i:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=T[d];e&&(P.deleteSampler(e),e.name=0,T[d]=null)}},q:a=>{if(a){var b=S[a];b?(P.deleteShader(b),S[a]=null):U||=1281}},B:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Gb[d];e&&(P.deleteTexture(e),e.name=0,Gb[d]=null)}},Ha:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];P.deleteVertexArray(Hb[d]);Hb[d]=null}},v:a=>P.depthFunc(a),u:a=>{P.depthMask(!!a)},e:a=>P.disable(a),I:a=>{P.disableVertexAttribArray(a)},sb:(a,b,c)=>{P.drawArrays(a,b,c)},
tb:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},ub:(a,b,c,d)=>{P.drawElements(a,b,c,d)},vb:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},g:a=>P.enable(a),Gb:a=>{P.enableVertexAttribArray(a)},D:a=>P.frontFace(a),Ga:(a,b)=>{Nb(a,b,"createBuffer",Q)},Da:(a,b)=>{Nb(a,b,"createRenderbuffer",Fb)},sa:(a,b)=>{Nb(a,b,"createSampler",T)},Aa:(a,b)=>{Nb(a,b,"createTexture",Gb)},Qa:(a,b)=>{Nb(a,b,"createVertexArray",Hb)},Mb:(a,b)=>P.getAttribLocation(R[a],b?B(t,b):""),d:(a,b)=>Zb(a,b),pa:(a,b,c,d)=>{a=P.getProgramInfoLog(R[a]);
null===a&&(a="(unknown error)");b=0<b&&d?D(a,d,b):0;c&&(u[c>>2]=b)},w:(a,b,c)=>{if(c)if(a>=Db)U||=1281;else if(a=R[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.yc){var d=P.getProgramParameter(a,35718);for(b=0;b<d;++b)a.yc=Math.max(a.yc,P.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.yc}else if(35722==b){if(!a.wc)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.wc=Math.max(a.wc,P.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.wc}else if(35381==
b){if(!a.xc)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.xc=Math.max(a.xc,P.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.xc}else u[c>>2]=P.getProgramParameter(a,b);else U||=1281},Nb:(a,b,c,d)=>{a=P.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,d,b):0;c&&(u[c>>2]=b)},ma:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(S[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=P.getShaderParameter(S[a],
b):U||=1281},Oa:(a,b)=>{if(2>V.version)return U||=1282,0;var c=Jb[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Yb().map(ac),c=Jb[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},na:(a,b)=>{b=b?B(t,b):"";if(a=R[a]){var c=a,d=c.vc,e=c.cd,h;if(!d){c.vc=d={};c.bd={};var g=P.getProgramParameter(c,35718);for(h=0;h<g;++h){var l=P.getActiveUniform(c,h);var n=l.name;l=l.size;var q=bc(n);q=0<q?n.slice(0,q):n;var w=c.Jc;c.Jc+=l;e[q]=[l,w];for(n=0;n<l;++n)d[w]=
n,c.bd[w++]=q}}c=a.vc;d=0;e=b;h=bc(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.cd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else U||=1281;return-1},pb:(a,b,c)=>{for(var d=cc[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];P.invalidateFramebuffer(a,d)},qa:a=>{a=R[a];P.linkProgram(a);a.vc=0;a.cd={}},Pa:(a,b)=>{3317==a?Kb=b:3314==a&&(Lb=b);P.pixelStorei(a,b)},E:(a,b)=>P.polygonOffset(a,b),rb:a=>P.readBuffer(a),Ba:(a,b,c,d,e)=>P.renderbufferStorageMultisample(a,b,c,d,e),y:(a,
b,c)=>{P.samplerParameterf(T[a],b,c)},f:(a,b,c)=>{P.samplerParameteri(T[a],b,c)},h:(a,b,c,d)=>P.scissor(a,b,c,d),Pb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var g=(g=v[c+4*h>>2])?B(t,g,d?v[d+4*h>>2]:void 0):"";e+=g}P.shaderSource(S[a],e)},Ma:(a,b,c)=>P.stencilFunc(a,b,c),ka:(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),t:a=>P.stencilMask(a),La:(a,b,c)=>P.stencilOp(a,b,c),ja:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),va:(a,b,c,d,e,h,g,l,n)=>{if(2<=V.version){if(P.tc){P.texImage2D(a,b,c,d,e,h,g,l,n);return}if(n){var q=
dc(l);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);P.texImage2D(a,b,c,d,e,h,g,l,q,n);return}}if(n){q=dc(l);var w=e*((Lb||d)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT+Kb-1&-Kb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+w>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;P.texImage2D(a,b,c,d,e,h,g,l,n)},ta:(a,b,c,d,e,h,g,l,n,q)=>{if(P.tc)P.texImage3D(a,b,c,d,e,h,g,l,n,q);else if(q){var w=dc(n);P.texImage3D(a,b,c,d,e,h,g,l,n,w,q>>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else P.texImage3D(a,
b,c,d,e,h,g,l,n,null)},za:(a,b,c)=>P.texParameteri(a,b,c),ya:(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),xa:(a,b,c,d,e,h)=>P.texStorage3D(a,b,c,d,e,h),Fb:(a,b,c)=>{if(2<=V.version)b&&P.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);P.uniform1fv(W(a),d)}},Rb:(a,b)=>{P.uniform1i(W(a),b)},Ab:(a,b,c)=>{if(2<=V.version)b&&P.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=ec[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>
2);P.uniform1iv(W(a),d)}},Db:(a,b,c)=>{if(2<=V.version)b&&P.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);P.uniform2fv(W(a),d)}},zb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=ec[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);P.uniform2iv(W(a),d)}},Cb:(a,b,c)=>{if(2<=V.version)b&&P.uniform3fv(W(a),x,c>>2,3*b);
else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);P.uniform3fv(W(a),d)}},yb:(a,b,c)=>{if(2<=V.version)b&&P.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b){b*=3;for(var d=ec[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);P.uniform3iv(W(a),d)}},Bb:(a,b,c)=>{if(2<=V.version)b&&P.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=
4;for(var h=0;h<b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);P.uniform4fv(W(a),d)}},xb:(a,b,c)=>{if(2<=V.version)b&&P.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=ec[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);P.uniform4iv(W(a),d)}},wb:(a,b,c,d)=>{if(2<=V.version)b&&P.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],
h=x;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(W(a),!!c,e)}},k:a=>{a=R[a];P.useProgram(a);P.ed=a},Hb:(a,b)=>{P.vertexAttribDivisor(a,b)},Ib:(a,b,c,d,e,h)=>{P.vertexAttribPointer(a,b,c,!!d,e,h)},o:(a,b,c,d)=>P.viewport(a,
b,c,d),bb:Pa,Sb:function(){f.Wc=a=>{0!=nc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Wc)},Ua:function(){f.ad=a=>{const b=a.clipboardData.getData("text");jc(()=>{const c=gc(b);oc(c)})};window.addEventListener("paste",f.ad)},Ka:function(){f.Jd=[];f.Xc=b=>{b.stopPropagation();b.preventDefault()};f.Yc=b=>{b.stopPropagation();b.preventDefault()};f.Zc=b=>{b.stopPropagation();b.preventDefault()};f.$c=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;
f.Kd=c;pc(c.length);for(let e=0;e<c.length;e++)jc(()=>{const h=gc(c[e].name);qc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);rc(b.clientX,b.clientY,d)};const a=f.rc;a.addEventListener("dragenter",f.Xc,!1);a.addEventListener("dragleave",f.Yc,!1);a.addEventListener("dragover",f.Zc,!1);a.addEventListener("drop",f.$c,!1)},Lb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ea:function(a){a=a?B(t,a):"";void 0!==f.canvas&&
("object"===typeof f.canvas?mb[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.rc=L(a);f.rc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.rc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ya:function(){window.removeEventListener("beforeunload",f.Wc)},Ta:function(){window.removeEventListener("paste",f.ad)},Ia:function(){const a=f.rc;a.removeEventListener("dragenter",f.Xc);a.removeEventListener("dragleave",
f.Yc);a.removeEventListener("dragover",f.Zc);a.removeEventListener("drop",f.$c)},r:function(){f.rc&&f.rc.requestPointerLock&&f.rc.requestPointerLock()},oa:function(a,b){if(f.rc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;
default:a="auto"}f.rc.style.cursor=a}},Eb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(t.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Na:function(a){a=a?B(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");
b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},ha:function(){return navigator.userAgent.includes("Macintosh")?1:0},ia:function(a,b){b=b?B(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Tb:function(){return navigator.userAgent.includes("Macintosh")?
1:0}},Z=function(){function a(c){Z=c.exports;oa=Z.Ub;sa();pb=Z.hc;va.unshift(Z.Vb);z--;f.monitorRunDependencies?.(z);0==z&&(null!==za&&(clearInterval(za),za=null),A&&(c=A,A=null,c()));return Z}z++;f.monitorRunDependencies?.(z);var b={a:sc};if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return m(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ca??=Ba("nuklear-sapp-ui.wasm")?"nuklear-sapp-ui.wasm":f.locateFile?f.locateFile("nuklear-sapp-ui.wasm",k):k+"nuklear-sapp-ui.wasm";
Ga(b,function(c){a(c.instance)});return{}}(),N=a=>(N=Z.Wb)(a),oc=f.__sapp_emsc_onpaste=a=>(oc=f.__sapp_emsc_onpaste=Z.Xb)(a),nc=f.__sapp_html5_get_ask_leave_site=()=>(nc=f.__sapp_html5_get_ask_leave_site=Z.Yb)(),pc=f.__sapp_emsc_begin_drop=a=>(pc=f.__sapp_emsc_begin_drop=Z.Zb)(a),qc=f.__sapp_emsc_drop=(a,b)=>(qc=f.__sapp_emsc_drop=Z._b)(a,b),rc=f.__sapp_emsc_end_drop=(a,b,c)=>(rc=f.__sapp_emsc_end_drop=Z.$b)(a,b,c);
f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,g,l)=>(f.__sapp_emsc_invoke_fetch_cb=Z.ac)(a,b,c,d,e,h,g,l);var tc=f._main=(a,b)=>(tc=f._main=Z.bc)(a,b);f.__saudio_emsc_pull=a=>(f.__saudio_emsc_pull=Z.cc)(a);f.__sfetch_emsc_head_response=(a,b)=>(f.__sfetch_emsc_head_response=Z.dc)(a,b);f.__sfetch_emsc_get_response=(a,b,c)=>(f.__sfetch_emsc_get_response=Z.ec)(a,b,c);f.__sfetch_emsc_failed_http_status=(a,b)=>(f.__sfetch_emsc_failed_http_status=Z.fc)(a,b);
f.__sfetch_emsc_failed_buffer_too_small=a=>(f.__sfetch_emsc_failed_buffer_too_small=Z.gc)(a);var mc=(a,b)=>(mc=Z.ic)(a,b),ic=a=>(ic=Z.jc)(a),fc=a=>(fc=Z.kc)(a),hc=()=>(hc=Z.lc)(),uc;A=function vc(){uc||wc();uc||(A=vc)};function xc(a=[]){var b=tc;a.unshift(fa);var c=a.length,d=fc(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=gc(g);e+=4});v[e>>2]=0;try{var h=b(c,d);Qa(h)}catch(g){Oa(g)}}
function wc(){var a=ea;function b(){if(!uc&&(uc=!0,f.calledRun=!0,!p)){Ia(va);Ia(wa);f.onRuntimeInitialized?.();yc&&xc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();xa.unshift(c)}Ia(xa)}}if(!(0<z)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ya();Ia(ta);0<z||(f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var yc=!0;f.noInitialRun&&(yc=!1);wc();
