var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,da=Object.assign({},g),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja,ka;
if(ca){var fs=require("fs"),la=require("path");k=__dirname+"/";ia=(a,b)=>{a=ma(a)?new URL(a):la.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ka=a=>{a=ia(a,!0);a.buffer||(a=new Uint8Array(a));return a};ja=(a,b,c)=>{a=ma(a)?new URL(a):la.normalize(a);fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})};!g.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);process.on("uncaughtException",a=>{if(!("unwind"===
a||a instanceof na||a.context instanceof na))throw a;});ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?"":k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ja=(a,b,c)=>{if(ma(a)){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)}else fetch(a,{credentials:"same-origin"}).then(e=>e.ok?e.arrayBuffer():Promise.reject(Error(e.status+" : "+e.url))).then(b,c)};var oa=g.print||console.log.bind(console),l=g.printErr||console.error.bind(console);Object.assign(g,da);da=null;g.arguments&&(ea=g.arguments);g.thisProgram&&(fa=g.thisProgram);
g.quit&&(ha=g.quit);var q;g.wasmBinary&&(q=g.wasmBinary);var pa,t=!1,u,qa,v,ra,sa,w,x,z,A;function ta(){var a=pa.buffer;g.HEAP8=qa=new Int8Array(a);g.HEAP16=ra=new Int16Array(a);g.HEAPU8=v=new Uint8Array(a);g.HEAPU16=sa=new Uint16Array(a);g.HEAP32=w=new Int32Array(a);g.HEAPU32=x=new Uint32Array(a);g.HEAPF32=z=new Float32Array(a);g.HEAPF64=A=new Float64Array(a)}var ua=[],va=[],wa=[],xa=[];function ya(){var a=g.preRun.shift();ua.unshift(a)}var B=0,za=null,C=null;
function Aa(a){g.onAbort?.(a);a="Aborted("+a+")";l(a);t=!0;u=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ba=a=>a.startsWith("data:application/octet-stream;base64,"),ma=a=>a.startsWith("file://"),Ca;function Da(a){if(a==Ca&&q)return new Uint8Array(q);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}
function Ea(a){return q?Promise.resolve().then(()=>Da(a)):new Promise((b,c)=>{ja(a,d=>b(new Uint8Array(d)),()=>{try{b(Da(a))}catch(d){c(d)}})})}function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{l(`failed to asynchronously prepare wasm: ${d}`);Aa(d)})}
function Ga(a,b){var c=Ca;q||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||ma(c)||ca||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){l(`wasm streaming compile failed: ${e}`);l("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}function na(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ha=a=>{for(;0<a.length;)a.shift()(g)},Ia=g.noExitRuntime||!0,Ja="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,D=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ja)return Ja.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ka=[0,31,60,91,121,152,182,213,244,274,305,335],La=[0,31,59,90,120,151,181,212,243,273,304,334],E=(a,b,c)=>{var d=v;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var m=a.charCodeAt(++h);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=
240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},Ta=(a,b)=>{Ma=a;Na=b;if(F)if(Oa||=!0,0==a)G=function(){var d=Math.max(0,Pa+b-Qa())|0;setTimeout(H,d)};else if(1==a)G=function(){Ra(H)};else if(2==a){if("undefined"==typeof Sa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Sa=function(d){c.push(d);ba?(void 0===g.setImmediates&&(g.setImmediates=
[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}else Sa=setImmediate;G=function(){Sa(H)}}},Qa;Qa=()=>performance.now();
var ab=(a,b,c,d,e)=>{F=a;Ua=d;var h=I;Oa=!1;H=function(){if(!t)if(0<Va.length){var f=Va.shift();f.Xc(f.Sc);if(Wa){var m=Wa,n=0==m%1?m-1:Math.floor(m);Wa=f.Uc?n:(8*m+(n+.5))/9}g.setStatus&&(f=g.statusMessage||"Please wait...",m=Wa,n=Xa.Wc,m?m<n?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(f):g.setStatus(""));h<I||setTimeout(H,0)}else if(!(h<I))if(Ya=Ya+1|0,1==Ma&&1<Na&&0!=Ya%Na)G();else{0==Ma&&(Pa=Qa());if(!(t||g.preMainLoop&&!1===g.preMainLoop())){if(!t)try{if(a(),!Ia)try{u=
f=u,Za(f)}catch(p){$a(p)}}catch(p){$a(p)}g.postMainLoop?.()}h<I||("object"==typeof SDL&&SDL.audio?.ad?.(),G())}};e||(b&&0<b?Ta(0,1E3/b):Ta(1,1),G());if(c)throw"unwind";},$a=a=>{a instanceof na||"unwind"==a||ha(1,a)},Za=a=>{u=a;Ia||(g.onExit?.(a),t=!0);ha(a,new na(a))},bb=a=>{u=a;Za(a)},Oa=!1,G=null,I=0,F=null,Ua=0,Ma=0,Na=0,Ya=0,Va=[];function cb(){G=null;I++}var Xa={},Pa,H,Wa,J=!1,db=!1,eb=[];
function fb(){function a(){db=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}if(!gb){gb=!0;var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!db&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}var hb=!1,ib=void 0,K=void 0;
function jb(){if(!J)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var kb=0;function Ra(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===kb)kb=b+1E3/60;else for(;b+2>=kb;)kb+=1E3/60;setTimeout(a,Math.max(kb-b,0))}}var lb=[];function mb(){var a=g.canvas;lb.forEach(b=>b(a.width,a.height))}
function nb(a,b,c){b&&c?(a.Qc=b,a.Nc=c):(b=a.Qc,c=a.Nc);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var h=Math.min(screen.width/d,screen.height/e);d=Math.round(d*h);e=Math.round(e*
h)}K?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Sa,gb,ob=0,pb=[];
function qb(){if(navigator.userActivation?navigator.userActivation.isActive:ob&&rb.rc)for(var a=0;a<pb.length;++a){var b=pb[a];pb.splice(a,1);--a;b.ed(...b.Tc)}}var L=[];function sb(a){var b=L[a];b.target.removeEventListener(b.ec,b.yc,b.fc);L.splice(a,1)}function M(a){if(!a.target)return-4;if(a.hc)a.yc=function(c){++ob;rb=a;qb();a.ic(c);qb();--ob},a.target.addEventListener(a.ec,a.yc,a.fc),L.push(a);else for(var b=0;b<L.length;++b)L[b].target==a.target&&L[b].ec==a.ec&&sb(b--);return 0}
function tb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var rb,ub,vb,wb,xb,yb,zb,Ab,Bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],N=a=>{a=2<a?a?D(v,a):"":a;return Bb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Cb=a=>0>Bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Db=[],Eb,O=a=>{var b=Db[a];b||(a>=Db.length&&(Db.length=a+1),Db[a]=b=Eb.get(a));return b},Fb=(a,b,c,d,e,h)=>{ub||=P(256);a={target:N(a),ec:h,hc:d,ic:(f=event)=>{var m=f.target.id?f.target.id:"",n=ub;E(tb(f.target),n+0,128);
E(m,n+128,128);O(d)(e,n,b)&&f.preventDefault()},fc:c};return M(a)},Gb=(a,b,c,d,e,h)=>{vb||=P(176);a={target:N(a),ec:h,hc:d,ic:f=>{var m=vb;A[m>>3]=f.timeStamp;var n=m>>2;w[n+2]=f.location;w[n+3]=f.ctrlKey;w[n+4]=f.shiftKey;w[n+5]=f.altKey;w[n+6]=f.metaKey;w[n+7]=f.repeat;w[n+8]=f.charCode;w[n+9]=f.keyCode;w[n+10]=f.which;E(f.key||"",m+44,32);E(f.code||"",m+76,32);E(f.char||"",m+108,32);E(f.locale||"",m+140,32);O(d)(e,m,b)&&f.preventDefault()},fc:c};return M(a)},Hb=(a,b,c)=>{A[a>>3]=b.timeStamp;a>>=
2;w[a+2]=b.screenX;w[a+3]=b.screenY;w[a+4]=b.clientX;w[a+5]=b.clientY;w[a+6]=b.ctrlKey;w[a+7]=b.shiftKey;w[a+8]=b.altKey;w[a+9]=b.metaKey;ra[2*a+20]=b.button;ra[2*a+21]=b.buttons;w[a+11]=b.movementX;w[a+12]=b.movementY;c=Cb(c);w[a+13]=b.clientX-(c.left|0);w[a+14]=b.clientY-(c.top|0)},Ib=(a,b,c,d,e,h)=>{wb||=P(72);a=N(a);return M({target:a,rc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ec:h,hc:d,ic:(f=event)=>{Hb(wb,f,a);O(d)(e,wb,b)&&f.preventDefault()},fc:c})},Jb=(a,b,c,d,e)=>{xb||=P(260);return M({target:a,
ec:e,hc:d,ic:(h=event)=>{var f=xb,m=document.pointerLockElement||document.lc||document.Ac||document.zc;w[f>>2]=!!m;var n=m?.id||"";E(tb(m),f+4,128);E(n,f+132,128);O(d)(20,f,b)&&h.preventDefault()},fc:c})},Kb=(a,b,c,d,e)=>M({target:a,ec:e,hc:d,ic:(h=event)=>{O(d)(38,0,b)&&h.preventDefault()},fc:c}),Nb=(a,b,c,d)=>{yb||=P(36);a=N(a);return M({target:a,ec:"resize",hc:d,ic:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=yb;w[f>>2]=0;w[f+4>>2]=h.clientWidth;w[f+8>>2]=h.clientHeight;w[f+12>>
2]=innerWidth;w[f+16>>2]=innerHeight;w[f+20>>2]=outerWidth;w[f+24>>2]=outerHeight;w[f+28>>2]=pageXOffset|0;w[f+32>>2]=pageYOffset|0;O(d)(10,f,b)&&e.preventDefault()}}},fc:c})},Ob=(a,b,c,d,e,h)=>{zb||=P(1696);a=N(a);return M({target:a,rc:"touchstart"==h||"touchend"==h,ec:h,hc:d,ic:f=>{for(var m,n={},p=f.touches,r=0;r<p.length;++r)m=p[r],m.Bc=m.Cc=0,n[m.identifier]=m;for(r=0;r<f.changedTouches.length;++r)m=f.changedTouches[r],m.Bc=1,n[m.identifier]=m;for(r=0;r<f.targetTouches.length;++r)n[f.targetTouches[r].identifier].Cc=
1;p=zb;A[p>>3]=f.timeStamp;var y=p>>2;w[y+3]=f.ctrlKey;w[y+4]=f.shiftKey;w[y+5]=f.altKey;w[y+6]=f.metaKey;y+=7;var Lb=Cb(a),Mb=0;for(r in n)if(m=n[r],w[y]=m.identifier,w[y+1]=m.screenX,w[y+2]=m.screenY,w[y+3]=m.clientX,w[y+4]=m.clientY,w[y+5]=m.pageX,w[y+6]=m.pageY,w[y+7]=m.Bc,w[y+8]=m.Cc,w[y+9]=m.clientX-(Lb.left|0),w[y+10]=m.clientY-(Lb.top|0),y+=13,31<++Mb)break;w[p+8>>2]=Mb;O(d)(e,p,b)&&f.preventDefault()},fc:c})},Pb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=
(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},Qb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Rb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,
d)=>b.drawBuffersWEBGL(c,d))},Sb=a=>{a.Vc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},Tb=a=>{a.Yc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Ub=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Vb=1,Wb=[],Q=[],Xb=[],Yb=[],Zb=[],R=[],$b=[],ac=[],S=[],bc={},cc=4,dc=0,ec=a=>{for(var b=Vb++,c=a.length;c<b;c++)a[c]=null;return b},fc=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=T[c](),f=h&&ec(d);h?(h.name=f,d[f]=h):U||=1282;w[b+4*e>>2]=f}},hc=(a,b)=>{a.lc||(a.lc=a.getContext,a.getContext=function(d,e){e=a.lc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.tc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?gc(c,b):0},gc=(a,b)=>{var c=ec(ac),d={handle:c,attributes:b,version:b.tc,nc:a};a.canvas&&(a.canvas.Rc=d);ac[c]=d;("undefined"==typeof b.xc||b.xc)&&ic(d);return c},jc=a=>{V=ac[a];g.sc=T=V?.nc;return!(a&&!T)},ic=a=>{a||=V;if(!a.Oc){a.Oc=!0;var b=a.nc;Pb(b);Qb(b);Rb(b);Sb(b);Tb(b);2<=a.version&&(b.wc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.wc)b.wc=b.getExtension("EXT_disjoint_timer_query");b.Pc=b.getExtension("WEBGL_multi_draw");Ub(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},kc={},U,V,lc=(a,b,c,d,e,h)=>{a={target:N(a),ec:h,hc:d,ic:(f=event)=>{O(d)(e,0,b)&&f.preventDefault()},fc:c};M(a)},mc=(a,b,c,d)=>{Ab||=P(104);return M({target:a,rc:!0,ec:"wheel",hc:d,ic:(e=event)=>{var h=Ab;Hb(h,e,a);A[h+72>>3]=e.deltaX;A[h+80>>3]=e.deltaY;A[h+88>>3]=e.deltaZ;w[h+96>>2]=e.deltaMode;O(d)(9,h,b)&&e.preventDefault()},fc:c})},nc=["default","low-power","high-performance"],oc=[null,[],[]];
function pc(){var a=Ub(T);return a=a.concat(a.map(b=>"GL_"+b))}
var qc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=T.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=pc().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=T.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;l(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;l(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}w[b>>2]=c}else U||=1281},rc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},sc=a=>{var b=rc(a)+1,c=P(b);c&&E(a,c,b);return c},tc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),uc=[],vc=a=>{a-=5120;return 0==a?qa:1==a?v:2==a?ra:4==a?w:6==a?z:5==a||28922==a||28520==a||30779==a||30782==a?x:sa},W=a=>{var b=T.Lc;if(b){var c=b.mc[a];"number"==typeof c&&(b.mc[a]=c=T.getUniformLocation(b,b.Jc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],wc=[],yc=a=>{var b=rc(a)+
1,c=xc(b);E(a,c,b);return c},Bc=a=>{var b=zc();a();Ac(b)};
g.requestFullscreen=function(a,b){function c(){J=!1;var h=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===h?(d.exitFullscreen=jb,ib&&d.requestPointerLock(),J=!0,K?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]|8388608),nb(g.canvas),mb()):nb(d)):(h.parentNode.insertBefore(d,h),h.parentNode.removeChild(h),K?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>
2]&-8388609),nb(g.canvas),mb()):nb(d));g.onFullScreen?.(J);g.onFullscreen?.(J)}ib=a;K=b;"undefined"==typeof ib&&(ib=!0);"undefined"==typeof K&&(K=!1);var d=g.canvas;hb||(hb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};g.requestAnimationFrame=Ra;g.setCanvasSize=function(a,b,c){nb(g.canvas,a,b);c||mb()};g.pauseMainLoop=cb;g.resumeMainLoop=function(){I++;var a=Ma,b=Na,c=F;F=null;ab(c,0,!1,Ua,!0);Ta(a,b);G()};
g.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};g.createContext=function(a,b,c,d){if(b&&g.sc&&a==g.canvas)return g.sc;var e;if(b){var h={antialias:!1,alpha:!1,tc:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var f in d)h[f]=d[f];if("undefined"!=typeof kc&&(e=hc(a,h)))var m=ac[e].nc}else m=a.getContext("2d");if(!m)return null;c&&(g.sc=m,b&&jc(e),g.gd=b,eb.forEach(n=>n()),fb());return m};
for(var T,Y=0;32>Y;++Y)uc.push(Array(Y));var Cc=new Float32Array(288);for(Y=0;288>Y;++Y)X[Y]=Cc.subarray(0,Y);var Dc=new Int32Array(288);for(Y=0;288>Y;++Y)wc[Y]=Dc.subarray(0,Y);
var Jc={ia:function(){return 0},eb:function(){return 0},fb:function(){},hb:()=>{Aa("")},bb:(a,b,c)=>v.copyWithin(a,b,b+c),Za:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));w[c>>2]=a.getSeconds();w[c+4>>2]=a.getMinutes();w[c+8>>2]=a.getHours();w[c+12>>2]=a.getDate();w[c+16>>2]=a.getMonth();w[c+20>>2]=a.getFullYear()-1900;w[c+24>>2]=a.getDay();b=a.getFullYear();w[c+28>>2]=(0!==b%4||0===b%100&&0!==b%400?La:Ka)[a.getMonth()]+a.getDate()-1|0;w[c+36>>2]=-(60*a.getTimezoneOffset());
b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();w[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},ab:(a,b,c,d)=>{var e=(new Date).getFullYear(),h=new Date(e,0,1),f=new Date(e,6,1);e=h.getTimezoneOffset();var m=f.getTimezoneOffset();x[a>>2]=60*Math.max(e,m);w[b>>2]=Number(e!=m);a=n=>n.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];h=a(h);f=a(f);m<e?(E(h,c,17),E(f,d,17)):(E(h,d,17),E(f,c,17))},Pa:()=>
{cb();F=null},gb:()=>Date.now(),ea:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ha:(a,b,c)=>{a=N(a);if(!a)return-4;a=Cb(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},Qa:()=>performance.now(),Xa:(a,b)=>{function c(d){O(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},$a:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-
pa.buffer.byteLength+65535)/65536;try{pa.grow(e);ta();var h=1;break a}catch(f){}h=void 0}if(h)return!0}return!1},O:(a,b,c,d)=>Fb(a,b,c,d,12,"blur"),da:(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},P:(a,b,c,d)=>Fb(a,b,c,d,13,"focus"),Y:(a,b,c,d)=>Gb(a,b,c,d,2,"keydown"),W:(a,b,c,d)=>Gb(a,b,c,d,1,"keypress"),X:(a,b,c,d)=>Gb(a,b,c,d,3,"keyup"),Ya:(a,b,c)=>{a=O(a);ab(a,b,c)},ca:(a,b,c,d)=>Ib(a,b,c,d,5,"mousedown"),$:(a,b,c,d)=>Ib(a,b,c,d,33,"mouseenter"),_:(a,b,c,d)=>Ib(a,b,c,d,34,"mouseleave"),
aa:(a,b,c,d)=>Ib(a,b,c,d,8,"mousemove"),ba:(a,b,c,d)=>Ib(a,b,c,d,6,"mouseup"),R:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.lc||document.body.Ac||document.body.zc))return-1;a=N(a);if(!a)return-4;Jb(a,b,c,d,"mozpointerlockchange");Jb(a,b,c,d,"webkitpointerlockchange");Jb(a,b,c,d,"mspointerlockchange");return Jb(a,b,c,d,"pointerlockchange")},Q:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.lc||document.body.Ac||document.body.zc))return-1;
a=N(a);if(!a)return-4;Kb(a,b,c,d,"mozpointerlockerror");Kb(a,b,c,d,"webkitpointerlockerror");Kb(a,b,c,d,"mspointerlockerror");return Kb(a,b,c,d,"pointerlockerror")},fa:(a,b,c,d)=>Nb(a,b,c,d),S:(a,b,c,d)=>Ob(a,b,c,d,25,"touchcancel"),T:(a,b,c,d)=>Ob(a,b,c,d,23,"touchend"),U:(a,b,c,d)=>Ob(a,b,c,d,24,"touchmove"),V:(a,b,c,d)=>Ob(a,b,c,d,22,"touchstart"),N:(a,b,c,d)=>{lc(a,b,c,d,31,"webglcontextlost");return 0},M:(a,b,c,d)=>{lc(a,b,c,d,32,"webglcontextrestored");return 0},Z:(a,b,c,d)=>(a=N(a))?"undefined"!=
typeof a.onwheel?mc(a,b,c,d):-1:-4,Va:(a,b)=>{b>>=2;b={alpha:!!w[b],depth:!!w[b+1],stencil:!!w[b+2],antialias:!!w[b+3],premultipliedAlpha:!!w[b+4],preserveDrawingBuffer:!!w[b+5],powerPreference:nc[w[b+6]],failIfMajorPerformanceCaveat:!!w[b+7],tc:w[b+8],Zc:w[b+9],xc:w[b+10],Mc:w[b+11],$c:w[b+12],bd:w[b+13]};a=N(a);return!a||b.Mc?0:hc(a,b)},Ta:(a,b)=>{a=ac[a];b=b?D(v,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Pb(T);"OES_vertex_array_object"==b&&Qb(T);"WEBGL_draw_buffers"==
b&&Rb(T);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Sb(T);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Tb(T);"WEBGL_multi_draw"==b&&(T.Pc=T.getExtension("WEBGL_multi_draw"));return!!a.nc.getExtension(b)},Ua:a=>jc(a)?0:-5,ga:()=>52,db:()=>52,_a:function(){return 70},cb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var f=x[b>>2],m=x[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=v[f+n],r=oc[a];0===p||10===p?((1===a?oa:l)(D(r,0)),r.length=0):r.push(p)}e+=m}x[d>>2]=e;return 0},i:a=>T.activeTexture(a),
z:(a,b)=>{T.attachShader(Q[a],R[b])},b:(a,b)=>{35051==a?T.vc=b:35052==a&&(T.kc=b);T.bindBuffer(a,Wb[b])},a:(a,b,c)=>{T.bindBufferBase(a,b,Wb[c])},q:(a,b)=>{T.bindFramebuffer(a,Xb[b])},Aa:(a,b)=>{T.bindRenderbuffer(a,Yb[b])},h:(a,b)=>{T.bindSampler(a,S[b])},c:(a,b)=>{T.bindTexture(a,Zb[b])},L:a=>{T.bindVertexArray($b[a])},H:(a,b,c,d)=>T.blendColor(a,b,c,d),I:(a,b)=>T.blendEquationSeparate(a,b),J:(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),jb:(a,b,c,d,e,h,f,m,n,p)=>T.blitFramebuffer(a,b,c,d,e,h,f,m,n,p),
Da:(a,b,c,d)=>{2<=V.version?c&&b?T.bufferData(a,v,d,c,b):T.bufferData(a,b,d):T.bufferData(a,c?v.subarray(c,c+b):b,d)},B:(a,b,c,d)=>{2<=V.version?c&&T.bufferSubData(a,b,v,d,c):T.bufferSubData(a,b,v.subarray(d,d+c))},Db:(a,b,c,d)=>T.clearBufferfi(a,b,c,d),na:(a,b,c)=>{T.clearBufferfv(a,b,z,c>>2)},Cb:(a,b,c)=>{T.clearBufferiv(a,b,w,c>>2)},n:(a,b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},Hb:a=>{T.compileShader(R[a])},wa:(a,b,c,d,e,h,f,m)=>{2<=V.version?T.kc||!f?T.compressedTexImage2D(a,b,c,d,e,h,f,m):T.compressedTexImage2D(a,
b,c,d,e,h,v,m,f):T.compressedTexImage2D(a,b,c,d,e,h,m?v.subarray(m,m+f):null)},ua:(a,b,c,d,e,h,f,m,n)=>{T.kc?T.compressedTexImage3D(a,b,c,d,e,h,f,m,n):T.compressedTexImage3D(a,b,c,d,e,h,f,v,n,m)},ra:()=>{var a=ec(Q),b=T.createProgram();b.name=a;b.qc=b.oc=b.pc=0;b.uc=1;Q[a]=b;return a},Jb:a=>{var b=ec(R);R[b]=T.createShader(a);return b},E:a=>T.cullFace(a),Ha:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Wb[d];e&&(T.deleteBuffer(e),e.name=0,Wb[d]=null,d==T.vc&&(T.vc=0),d==T.kc&&(T.kc=0))}},l:(a,
b)=>{for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=Xb[d];e&&(T.deleteFramebuffer(e),e.name=0,Xb[d]=null)}},t:a=>{if(a){var b=Q[a];b?(T.deleteProgram(b),b.name=0,Q[a]=null):U||=1281}},C:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Yb[d];e&&(T.deleteRenderbuffer(e),e.name=0,Yb[d]=null)}},k:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=S[d];e&&(T.deleteSampler(e),e.name=0,S[d]=null)}},r:a=>{if(a){var b=R[a];b?(T.deleteShader(b),R[a]=null):U||=1281}},D:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],
e=Zb[d];e&&(T.deleteTexture(e),e.name=0,Zb[d]=null)}},Fa:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2];T.deleteVertexArray($b[d]);$b[d]=null}},w:a=>T.depthFunc(a),v:a=>{T.depthMask(!!a)},e:a=>T.disable(a),K:a=>{T.disableVertexAttribArray(a)},lb:(a,b,c)=>{T.drawArrays(a,b,c)},mb:(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},nb:(a,b,c,d)=>{T.drawElements(a,b,c,d)},ob:(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},g:a=>T.enable(a),zb:a=>{T.enableVertexAttribArray(a)},F:a=>T.frontFace(a),Ea:(a,b)=>
{fc(a,b,"createBuffer",Wb)},Ba:(a,b)=>{fc(a,b,"createRenderbuffer",Yb)},sa:(a,b)=>{fc(a,b,"createSampler",S)},ya:(a,b)=>{fc(a,b,"createTexture",Zb)},Oa:(a,b)=>{fc(a,b,"createVertexArray",$b)},Fb:(a,b)=>T.getAttribLocation(Q[a],b?D(v,b):""),d:(a,b)=>qc(a,b),pa:(a,b,c,d)=>{a=T.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(w[c>>2]=b)},y:(a,b,c)=>{if(c)if(a>=Vb)U||=1281;else if(a=Q[a],35716==b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+
1;else if(35719==b){if(!a.qc)for(b=0;b<T.getProgramParameter(a,35718);++b)a.qc=Math.max(a.qc,T.getActiveUniform(a,b).name.length+1);w[c>>2]=a.qc}else if(35722==b){if(!a.oc)for(b=0;b<T.getProgramParameter(a,35721);++b)a.oc=Math.max(a.oc,T.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.oc}else if(35381==b){if(!a.pc)for(b=0;b<T.getProgramParameter(a,35382);++b)a.pc=Math.max(a.pc,T.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.pc}else w[c>>2]=T.getProgramParameter(a,b);else U||=1281},Gb:(a,b,c,d)=>
{a=T.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(w[c>>2]=b)},oa:(a,b,c)=>{c?35716==b?(a=T.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=T.getShaderSource(R[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=T.getShaderParameter(R[a],b):U||=1281},Ma:(a,b)=>{if(2>V.version)return U||=1282,0;var c=bc[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=pc().map(sc),c=bc[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];
default:return U||=1280,0}},p:(a,b)=>{b=b?D(v,b):"";if(a=Q[a]){var c=a,d=c.mc,e=c.Kc,h;if(!d)for(c.mc=d={},c.Jc={},h=0;h<T.getProgramParameter(c,35718);++h){var f=T.getActiveUniform(c,h);var m=f.name;f=f.size;var n=tc(m);n=0<n?m.slice(0,n):m;var p=c.uc;c.uc+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.Jc[p++]=n}c=a.mc;d=0;e=b;h=tc(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Kc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else U||=1281;return-1},ib:(a,b,c)=>{for(var d=
uc[b],e=0;e<b;e++)d[e]=w[c+4*e>>2];T.invalidateFramebuffer(a,d)},qa:a=>{a=Q[a];T.linkProgram(a);a.mc=0;a.Kc={}},Na:(a,b)=>{3317==a?cc=b:3314==a&&(dc=b);T.pixelStorei(a,b)},G:(a,b)=>T.polygonOffset(a,b),kb:a=>T.readBuffer(a),za:(a,b,c,d,e)=>T.renderbufferStorageMultisample(a,b,c,d,e),A:(a,b,c)=>{T.samplerParameterf(S[a],b,c)},f:(a,b,c)=>{T.samplerParameteri(S[a],b,c)},j:(a,b,c,d)=>T.scissor(a,b,c,d),Ib:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=x[c+4*h>>2])?D(v,f,d?x[d+4*h>>2]:void 0):"";e+=f}T.shaderSource(R[a],
e)},Ka:(a,b,c)=>T.stencilFunc(a,b,c),ma:(a,b,c,d)=>T.stencilFuncSeparate(a,b,c,d),u:a=>T.stencilMask(a),Ja:(a,b,c)=>T.stencilOp(a,b,c),la:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),va:(a,b,c,d,e,h,f,m,n)=>{if(2<=V.version){if(T.kc){T.texImage2D(a,b,c,d,e,h,f,m,n);return}if(n){var p=vc(m);n>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);T.texImage2D(a,b,c,d,e,h,f,m,p,n);return}}if(n){p=vc(m);var r=e*((dc||d)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*p.BYTES_PER_ELEMENT+cc-1&-cc);
n=p.subarray(n>>>31-Math.clz32(p.BYTES_PER_ELEMENT),n+r>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else n=null;T.texImage2D(a,b,c,d,e,h,f,m,n)},ta:(a,b,c,d,e,h,f,m,n,p)=>{if(T.kc)T.texImage3D(a,b,c,d,e,h,f,m,n,p);else if(p){var r=vc(n);T.texImage3D(a,b,c,d,e,h,f,m,n,r,p>>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else T.texImage3D(a,b,c,d,e,h,f,m,n,null)},xa:(a,b,c)=>T.texParameteri(a,b,c),yb:(a,b,c)=>{if(2<=V.version)b&&T.uniform1fv(W(a),z,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=z[c+4*e>>2];
else d=z.subarray(c>>2,c+4*b>>2);T.uniform1fv(W(a),d)}},x:(a,b)=>{T.uniform1i(W(a),b)},tb:(a,b,c)=>{if(2<=V.version)b&&T.uniform1iv(W(a),w,c>>2,b);else{if(288>=b)for(var d=wc[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);T.uniform1iv(W(a),d)}},xb:(a,b,c)=>{if(2<=V.version)b&&T.uniform2fv(W(a),z,c>>2,2*b);else{if(144>=b)for(var d=X[2*b],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);T.uniform2fv(W(a),d)}},sb:(a,b,c)=>{if(2<=V.version)b&&T.uniform2iv(W(a),
w,c>>2,2*b);else{if(144>=b)for(var d=wc[2*b],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);T.uniform2iv(W(a),d)}},wb:(a,b,c)=>{if(2<=V.version)b&&T.uniform3fv(W(a),z,c>>2,3*b);else{if(96>=b)for(var d=X[3*b],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);T.uniform3fv(W(a),d)}},rb:(a,b,c)=>{if(2<=V.version)b&&T.uniform3iv(W(a),w,c>>2,3*b);else{if(96>=b)for(var d=wc[3*b],e=0;e<3*b;e+=3)d[e]=w[c+
4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);T.uniform3iv(W(a),d)}},ub:(a,b,c)=>{if(2<=V.version)b&&T.uniform4fv(W(a),z,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=z;c>>=2;for(var h=0;h<4*b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=z.subarray(c>>2,c+16*b>>2);T.uniform4fv(W(a),d)}},qb:(a,b,c)=>{if(2<=V.version)b&&T.uniform4iv(W(a),w,c>>2,4*b);else{if(72>=b)for(var d=wc[4*b],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>
2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);T.uniform4iv(W(a),d)}},pb:(a,b,c,d)=>{if(2<=V.version)b&&T.uniformMatrix4fv(W(a),!!c,z,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=z;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=h[m];e[f+1]=h[m+1];e[f+2]=h[m+2];e[f+3]=h[m+3];e[f+4]=h[m+4];e[f+5]=h[m+5];e[f+6]=h[m+6];e[f+7]=h[m+7];e[f+8]=h[m+8];e[f+9]=h[m+9];e[f+10]=h[m+10];e[f+11]=h[m+11];e[f+12]=h[m+12];e[f+13]=h[m+13];e[f+14]=h[m+14];e[f+15]=h[m+15]}}else e=z.subarray(d>>
2,d+64*b>>2);T.uniformMatrix4fv(W(a),!!c,e)}},m:a=>{a=Q[a];T.useProgram(a);T.Lc=a},Ab:(a,b)=>{T.vertexAttribDivisor(a,b)},Bb:(a,b,c,d,e,h)=>{T.vertexAttribPointer(a,b,c,!!d,e,h)},o:(a,b,c,d)=>T.viewport(a,b,c,d),Lb:function(){g.Dc=a=>{0!=Ec()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Dc)},Sa:function(){g.Ic=a=>{const b=a.clipboardData.getData("text");Bc(()=>{const c=yc(b);Fc(c)})};window.addEventListener("paste",g.Ic)},Ia:function(a){g.cd=[];a=a?D(v,a):"";a=
document.getElementById(a);g.Ec=b=>{b.stopPropagation();b.preventDefault()};g.Fc=b=>{b.stopPropagation();b.preventDefault()};g.Gc=b=>{b.stopPropagation();b.preventDefault()};g.Hc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.dd=c;Gc(c.length);for(let e=0;e<c.length;e++)Bc(()=>{const h=yc(c[e].name);Hc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Ic(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.Ec,!1);a.addEventListener("dragleave",
g.Fc,!1);a.addEventListener("dragover",g.Gc,!1);a.addEventListener("drop",g.Hc,!1)},Eb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ca:function(a){a=a?D(v,a):"";g.jc=document.getElementById(a);g.jc||console.log("sokol_app.h: invalid target:"+a);g.jc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Wa:function(){window.removeEventListener("beforeunload",g.Dc)},Ra:function(){window.removeEventListener("paste",
g.Ic)},Ga:function(a){a=a?D(v,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.Ec);a.removeEventListener("dragleave",g.Fc);a.removeEventListener("dragover",g.Gc);a.removeEventListener("drop",g.Hc)},s:function(){g.jc&&g.jc.requestPointerLock&&g.jc.requestPointerLock()},Kb:function(a,b){if(g.jc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a=
"ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.jc.style.cursor=a}},vb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(v.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},La:function(a){a=
a?D(v,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},ja:function(){return navigator.userAgent.includes("Macintosh")?1:0},ka:function(a,b){b=b?D(v,b):"";switch(a){case 0:console.error(b);
break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Mb:function(){return navigator.userAgent.includes("Macintosh")?1:0}},Z=function(){function a(c){Z=c.exports;pa=Z.Nb;ta();Eb=Z.ac;va.unshift(Z.Ob);B--;g.monitorRunDependencies?.(B);0==B&&(null!==za&&(clearInterval(za),za=null),C&&(c=C,C=null,c()));return Z}var b={a:Jc};B++;g.monitorRunDependencies?.(B);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return l(`Module.instantiateWasm callback failed with error: ${c}`),
!1}Ca||=Ba("nuklear-sapp-ui.wasm")?"nuklear-sapp-ui.wasm":g.locateFile?g.locateFile("nuklear-sapp-ui.wasm",k):k+"nuklear-sapp-ui.wasm";Ga(b,function(c){a(c.instance)});return{}}(),P=a=>(P=Z.Pb)(a),Fc=g.__sapp_emsc_onpaste=a=>(Fc=g.__sapp_emsc_onpaste=Z.Qb)(a),Ec=g.__sapp_html5_get_ask_leave_site=()=>(Ec=g.__sapp_html5_get_ask_leave_site=Z.Rb)(),Gc=g.__sapp_emsc_begin_drop=a=>(Gc=g.__sapp_emsc_begin_drop=Z.Sb)(a),Hc=g.__sapp_emsc_drop=(a,b)=>(Hc=g.__sapp_emsc_drop=Z.Tb)(a,b),Ic=g.__sapp_emsc_end_drop=
(a,b,c)=>(Ic=g.__sapp_emsc_end_drop=Z.Ub)(a,b,c);g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,f,m)=>(g.__sapp_emsc_invoke_fetch_cb=Z.Vb)(a,b,c,d,e,h,f,m);var Kc=g._main=(a,b)=>(Kc=g._main=Z.Wb)(a,b);g.__saudio_emsc_pull=a=>(g.__saudio_emsc_pull=Z.Xb)(a);g.__sfetch_emsc_head_response=(a,b)=>(g.__sfetch_emsc_head_response=Z.Yb)(a,b);g.__sfetch_emsc_get_response=(a,b,c)=>(g.__sfetch_emsc_get_response=Z.Zb)(a,b,c);g.__sfetch_emsc_failed_http_status=(a,b)=>(g.__sfetch_emsc_failed_http_status=Z._b)(a,b);
g.__sfetch_emsc_failed_buffer_too_small=a=>(g.__sfetch_emsc_failed_buffer_too_small=Z.$b)(a);var Ac=a=>(Ac=Z.bc)(a),xc=a=>(xc=Z.cc)(a),zc=()=>(zc=Z.dc)(),Lc;C=function Mc(){Lc||Nc();Lc||(C=Mc)};function Oc(a=[]){var b=Kc;a.unshift(fa);var c=a.length,d=xc(4*(c+1)),e=d;a.forEach(f=>{x[e>>2]=yc(f);e+=4});x[e>>2]=0;try{var h=b(c,d);bb(h)}catch(f){$a(f)}}
function Nc(){var a=ea;function b(){if(!Lc&&(Lc=!0,g.calledRun=!0,!t)){Ha(va);Ha(wa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();Pc&&Oc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();xa.unshift(c)}Ha(xa)}}if(!(0<B)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ya();Ha(ua);0<B||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Pc=!0;g.noInitialRun&&(Pc=!1);Nc();
