var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs"),ka=require("path");k=__dirname+"/";ja=a=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a)};ia=a=>{a=la(a)?new URL(a):ka.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&
document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?"":k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=a=>la(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var ma=f.print||console.log.bind(console),m=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);var na=f.wasmBinary,oa,p=!1,pa,r,t,qa,ra,u,v,x,y;
function sa(){var a=oa.buffer;f.HEAP8=r=new Int8Array(a);f.HEAP16=qa=new Int16Array(a);f.HEAPU8=t=new Uint8Array(a);f.HEAPU16=ra=new Uint16Array(a);f.HEAP32=u=new Int32Array(a);f.HEAPU32=v=new Uint32Array(a);f.HEAPF32=x=new Float32Array(a);f.HEAPF64=y=new Float64Array(a)}var ua=[],va=[],wa=[],xa=[];function ya(){var a=f.preRun;a&&("function"==typeof a&&(a=[a]),a.forEach(za));Aa(ua)}function za(a){ua.unshift(a)}function Ba(a){xa.unshift(a)}var z=0,Ca=null,A=null;
function Da(a){f.onAbort?.(a);a="Aborted("+a+")";m(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ea=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),Fa;function Ga(a){if(a==Fa&&na)return new Uint8Array(na);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}function Ha(a){return na?Promise.resolve().then(()=>Ga(a)):ia(a).then(b=>new Uint8Array(b),()=>Ga(a))}
function Ia(a,b,c){return Ha(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{m(`failed to asynchronously prepare wasm: ${d}`);Da(d)})}function Ja(a,b){var c=Fa;na||"function"!=typeof WebAssembly.instantiateStreaming||Ea(c)||la(c)||ca||"function"!=typeof fetch?Ia(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){m(`wasm streaming compile failed: ${e}`);m("falling back to ArrayBuffer instantiation");return Ia(c,a,b)}))}
function Ka(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Aa=a=>{a.forEach(b=>b(f))},La=f.noExitRuntime||!0,Ma=[0,31,60,91,121,152,182,213,244,274,305,335],Na=[0,31,59,90,120,151,181,212,243,273,304,334],B={},Oa=a=>{a instanceof Ka||"unwind"==a||ha(1,a)},Pa=0,Qa=a=>{pa=a;La||0<Pa||(f.onExit?.(a),p=!0);ha(a,new Ka(a))},Ra=a=>{pa=a;Qa(a)},Sa=()=>{if(!(La||0<Pa))try{var a=pa;pa=a;Qa(a)}catch(b){Oa(b)}},Ta=a=>{if(!p)try{a(),Sa()}catch(b){Oa(b)}},C=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=
g&&57343>=g){var l=a.charCodeAt(++h);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},$a=(a,b)=>{Ua=a;Va=b;if(D)if(Wa||=!0,0==a)E=function(){setTimeout(G,Math.max(0,Xa+b-performance.now())|0)};else if(1==a)E=function(){Ya(G)};else if(2==a){if("undefined"==typeof Za)if("undefined"==
typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Za=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Za=setImmediate;E=function(){Za(G)}}},ib=(a,b,c,d,e)=>{function h(){return g<ab?(Sa(),!1):!0}D=a;bb=d;var g=ab;Wa=!1;G=function(){if(!p)if(0<cb.length){var l=cb.shift();
l.pd(l.dd);if(db){var n=db,q=0==n%1?n-1:Math.floor(n);db=l.gd?q:(8*n+(q+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",n=db??0,q=eb.nd??0,n?n<q?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));h()&&setTimeout(G,0)}else if(h())if(fb=fb+1|0,1==Ua&&1<Va&&0!=fb%Va)E();else{0==Ua&&(Xa=performance.now());a:if(!p){for(l of gb)if(!1===l())break a;Ta(a);for(n of hb)n()}h()&&E()}};e||(b&&0<b?$a(0,1E3/b):$a(1,1),E());if(c)throw"unwind";},Wa=!1,E=null,ab=
0,D=null,bb=0,Ua=0,Va=0,fb=0,cb=[],gb=[],hb=[];function jb(){E=null;ab++}var H=0;function Ya(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===H)H=b+1E3/60;else for(;b+2>=H;)H+=1E3/60;setTimeout(a,Math.max(H-b,0))}}var eb={},Xa,G,Za,db;function kb(a){var b=I.dc[a];b.target.removeEventListener(b.cc,b.Ic,b.ec);I.dc.splice(a,1)}
function lb(){if(navigator.userActivation?navigator.userActivation.isActive:I.uc&&I.Vc.sc){var a=I.ic;I.ic=[];for(var b of a)b.xc(...b.Cc)}}function J(a){if(!a.target)return-4;if(a.fc)a.Ic=function(c){++I.uc;I.Vc=a;lb();a.hc(c);lb();--I.uc},a.target.addEventListener(a.cc,a.Ic,a.ec),I.dc.push(a);else for(var b=0;b<I.dc.length;++b)I.dc[b].target==a.target&&I.dc[b].cc==a.cc&&kb(b--);return 0}function mb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var I={ed:0,qd:0,vc:0,qc:0,Bc:0,zc:0,tc:0,ld:0,td:0,kd:0,od:0,wc:0,Cd:0,yc:0,vd(){for(;I.dc.length;)kb(I.dc.length-1);I.ic=[]},uc:0,ic:[],jd(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var l in h)if(h[l]!=g[l])return!1;return!0}for(var e of I.ic)if(e.xc==a&&d(e.Cc,c))return;I.ic.push({xc:a,Mc:b,Cc:c});I.ic.sort((h,g)=>h.Mc<g.Mc)},xd(a){I.ic=I.ic.filter(b=>b.xc!=a)},dc:[],wd:(a,b)=>{for(var c=0;c<I.dc.length;++c)I.dc[c].target!=a||b&&b!=I.dc[c].cc||kb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||
document.webkitFullscreenEnabled}},nb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,K=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&nb)return nb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
ob=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],L=a=>{a=2<a?a?K(t,a):"":a;return ob[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},pb=a=>0>ob.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},qb=[],rb,M=a=>{var b=qb[a];b||(a>=qb.length&&(qb.length=a+1),qb[a]=b=rb.get(a));return b},sb=(a,b,c,d,e,h)=>{I.tc||(I.tc=N(256));a={target:L(a),cc:h,fc:d,hc:(g=event)=>{var l=g.target.id?g.target.id:"",n=I.tc;C(mb(g.target),n+0,128);C(l,n+128,128);M(d)(e,
n,b)&&g.preventDefault()},ec:c};return J(a)},tb=(a,b,c,d,e,h)=>{I.vc||(I.vc=N(160));a={target:L(a),cc:h,fc:d,hc:g=>{var l=I.vc;y[l>>3]=g.timeStamp;var n=l>>2;u[n+2]=g.location;r[l+12]=g.ctrlKey;r[l+13]=g.shiftKey;r[l+14]=g.altKey;r[l+15]=g.metaKey;r[l+16]=g.repeat;u[n+5]=g.charCode;u[n+6]=g.keyCode;u[n+7]=g.which;C(g.key||"",l+32,32);C(g.code||"",l+64,32);C(g.char||"",l+96,32);C(g.locale||"",l+128,32);M(d)(e,l,b)&&g.preventDefault()},ec:c};return J(a)},ub=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;
u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;qa[2*d+14]=b.button;qa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=pb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,h)=>{I.qc||(I.qc=N(64));a=L(a);return J({target:a,sc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,cc:h,fc:d,hc:(g=event)=>{ub(I.qc,g,a);M(d)(e,I.qc,b)&&g.preventDefault()},ec:c})},vb=(a,b,c,d,e)=>{I.wc||
(I.wc=N(257));return J({target:a,cc:e,fc:d,hc:(h=event)=>{var g=I.wc,l=document.pointerLockElement||document.kc||document.Gc||document.Ec;r[g]=!!l;var n=l?.id||"";C(mb(l),g+1,128);C(n,g+129,128);M(d)(20,g,b)&&h.preventDefault()},ec:c})},wb=(a,b,c,d,e)=>J({target:a,cc:e,fc:d,hc:(h=event)=>{M(d)(38,0,b)&&h.preventDefault()},ec:c}),xb=(a,b,c,d)=>{I.zc||(I.zc=N(36));a=L(a);return J({target:a,cc:"resize",fc:d,hc:(e=event)=>{if(e.target==a){var h=document.body;if(h){var g=I.zc;u[g>>2]=0;u[g+4>>2]=h.clientWidth;
u[g+8>>2]=h.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;M(d)(10,g,b)&&e.preventDefault()}}},ec:c})},yb=(a,b,c,d,e,h)=>{I.yc||(I.yc=N(1552));a=L(a);return J({target:a,sc:"touchstart"==h||"touchend"==h,cc:h,fc:d,hc:g=>{var l={},n=g.touches;for(var q of n)q.Jc=q.Lc=0,l[q.identifier]=q;for(var w of g.changedTouches)w.Jc=1,l[w.identifier]=w;for(var ta of g.targetTouches)l[ta.identifier].Lc=1;n=
I.yc;y[n>>3]=g.timeStamp;r[n+12]=g.ctrlKey;r[n+13]=g.shiftKey;r[n+14]=g.altKey;r[n+15]=g.metaKey;q=n+16;w=pb(a);ta=0;for(let F of Object.values(l))if(l=q>>2,u[l]=F.identifier,u[l+1]=F.screenX,u[l+2]=F.screenY,u[l+3]=F.clientX,u[l+4]=F.clientY,u[l+5]=F.pageX,u[l+6]=F.pageY,r[q+28]=F.Jc,r[q+29]=F.Lc,u[l+8]=F.clientX-(w.left|0),u[l+9]=F.clientY-(w.top|0),q+=48,31<++ta)break;u[n+8>>2]=ta;M(d)(e,n,b)&&g.preventDefault()},ec:c})},P,zb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=
(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,d,e,h,g))},Ab=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Bb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,
d)=>b.drawBuffersWEBGL(c,d))},Cb=a=>{a.md=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},Db=a=>{a.rd=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Eb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Fb=1,Q=[],R=[],Gb=[],Hb=[],Ib=[],S=[],Jb=[],Kb=[],T=[],Lb={},Mb=4,Nb=0,Ob=a=>{for(var b=Fb++,c=a.length;c<b;c++)a[c]=null;return b},Pb=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=P[c](),g=h&&Ob(d);h?(h.name=g,d[g]=h):U||=1282;u[b+4*e>>2]=g}},Rb=(a,b)=>{a.kc||(a.kc=a.getContext,a.getContext=function(d,e){e=a.kc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Kc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?Qb(c,b):0},Qb=(a,b)=>{var c=Ob(Kb),d={handle:c,attributes:b,version:b.Kc,rc:a};a.canvas&&(a.canvas.cd=d);Kb[c]=d;("undefined"==typeof b.Hc||b.Hc)&&Sb(d);return c},Sb=a=>{a||=V;if(!a.$c){a.$c=!0;var b=a.rc;b.ad=b.getExtension("WEBGL_multi_draw");b.Zc=b.getExtension("EXT_polygon_offset_clamp");b.Yc=b.getExtension("EXT_clip_control");b.bd=b.getExtension("WEBGL_polygon_mode");zb(b);Ab(b);Bb(b);Cb(b);Db(b);2<=a.version&&(b.Fc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||
!b.Fc)b.Fc=b.getExtension("EXT_disjoint_timer_query");Eb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},U,V,Tb=(a,b,c,d,e,h)=>{a={target:L(a),cc:h,fc:d,hc:(g=event)=>{M(d)(e,0,b)&&g.preventDefault()},ec:c};J(a)},Ub=(a,b,c,d)=>{I.Bc||(I.Bc=N(96));return J({target:a,sc:!0,cc:"wheel",fc:d,hc:(e=event)=>{var h=I.Bc;ub(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+80>>3]=e.deltaZ;u[h+88>>2]=e.deltaMode;M(d)(9,h,b)&&e.preventDefault()},ec:c})},Vb=["default","low-power",
"high-performance"],Wb=[null,[],[]];function Xb(){var a=Eb(P);return a=a.concat(a.map(b=>"GL_"+b))}
var Yb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=Xb().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=P.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else U||=1281},Zb=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},$b=a=>{var b=Zb(a)+1,c=N(b);c&&C(a,c,b);return c},ac=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),bc=[],cc=a=>{a-=5120;return 0==a?r:1==a?t:2==a?qa:4==a?u:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?v:ra},W=a=>{var b=P.Wc;if(b){var c=b.mc[a];"number"==typeof c&&(b.mc[a]=c=P.getUniformLocation(b,b.Tc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],dc=[],fc=a=>{var b=Zb(a)+
1,c=ec(b);C(a,c,b);return c},ic=a=>{var b=gc();a();hc(b)};f.requestAnimationFrame=Ya;f.pauseMainLoop=jb;f.resumeMainLoop=function(){ab++;var a=Ua,b=Va,c=D;D=null;ib(c,0,!1,bb,!0);$a(a,b);E()};f.preMainLoop&&gb.push(f.preMainLoop);f.postMainLoop&&hb.push(f.postMainLoop);for(var Y=0;32>Y;++Y)bc.push(Array(Y));var jc=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=jc.subarray(0,Y);var kc=new Int32Array(288);for(Y=0;288>=Y;++Y)dc[Y]=kc.subarray(0,Y);
var rc={fb:()=>{Da("")},cb:(a,b,c)=>t.copyWithin(a,b,b+c),_a:()=>{La=!1;Pa=0},Ya:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));u[c>>2]=a.getSeconds();u[c+4>>2]=a.getMinutes();u[c+8>>2]=a.getHours();u[c+12>>2]=a.getDate();u[c+16>>2]=a.getMonth();u[c+20>>2]=a.getFullYear()-1900;u[c+24>>2]=a.getDay();b=a.getFullYear();u[c+28>>2]=(0!==b%4||0===b%100&&0!==b%400?Na:Ma)[a.getMonth()]+a.getDate()-1|0;u[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),
6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();u[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},$a:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];Ta(()=>lc(a,performance.now()))},b);B[a]={id:c,Bd:b};return 0},bb:(a,b,c,d)=>{var e=(new Date).getFullYear(),h=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();v[a>>2]=60*Math.max(h,e);u[b>>2]=Number(h!=e);b=g=>{var l=Math.abs(g);
return`UTC${0<=g?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(h);b=b(e);e<h?(C(a,c,17),C(b,d,17)):(C(a,d,17),C(b,c,17))},Oa:()=>{jb();D=null},eb:()=>Date.now(),ca:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ea:(a,b,c)=>{a=L(a);if(!a)return-4;a=pb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Pa:()=>performance.now(),Wa:(a,b)=>{function c(d){M(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ab:a=>{var b=t.length;a>>>=0;if(2147483648<
a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},M:(a,b,c,d)=>sb(a,b,c,d,12,"blur"),ba:(a,b,c)=>{a=L(a);if(!a)return-4;a.width=b;a.height=c;return 0},N:(a,b,c,d)=>sb(a,b,c,d,13,"focus"),W:(a,b,c,d)=>tb(a,b,c,d,2,"keydown"),U:(a,b,c,d)=>tb(a,b,c,d,1,"keypress"),V:(a,b,c,d)=>tb(a,b,c,d,3,"keyup"),
Xa:(a,b,c)=>{a=M(a);ib(a,b,c)},aa:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),Z:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),Y:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),_:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),$:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),P:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.kc||document.body.Gc||document.body.Ec))return-1;a=L(a);if(!a)return-4;vb(a,b,c,d,"mozpointerlockchange");vb(a,b,c,d,"webkitpointerlockchange");vb(a,b,c,d,"mspointerlockchange");return vb(a,
b,c,d,"pointerlockchange")},O:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.kc||document.body.Gc||document.body.Ec))return-1;a=L(a);if(!a)return-4;wb(a,b,c,d,"mozpointerlockerror");wb(a,b,c,d,"webkitpointerlockerror");wb(a,b,c,d,"mspointerlockerror");return wb(a,b,c,d,"pointerlockerror")},da:(a,b,c,d)=>xb(a,b,c,d),Q:(a,b,c,d)=>yb(a,b,c,d,25,"touchcancel"),R:(a,b,c,d)=>yb(a,b,c,d,23,"touchend"),S:(a,b,c,d)=>yb(a,b,c,d,24,"touchmove"),T:(a,b,c,d)=>yb(a,b,c,d,22,"touchstart"),
L:(a,b,c,d)=>{Tb(a,b,c,d,31,"webglcontextlost");return 0},K:(a,b,c,d)=>{Tb(a,b,c,d,32,"webglcontextrestored");return 0},X:(a,b,c,d)=>(a=L(a))?"undefined"!=typeof a.onwheel?Ub(a,b,c,d):-1:-4,Va:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Vb[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Kc:u[c+4],sd:u[c+5],Hc:r[b+24],Xc:r[b+25],ud:u[c+7],yd:r[b+32]};a=L(a);return!a||b.Xc?0:Rb(a,b)},
Sa:(a,b)=>{a=Kb[a];b=b?K(t,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&zb(P);"OES_vertex_array_object"==b&&Ab(P);"WEBGL_draw_buffers"==b&&Bb(P);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Cb(P);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Db(P);"WEBGL_multi_draw"==b&&(P.ad=P.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(P.Zc=P.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&(P.Yc=P.getExtension("EXT_clip_control"));
"WEBGL_polygon_mode"==b&&(P.bd=P.getExtension("WEBGL_polygon_mode"));return!!a.rc.getExtension(b)},Ta:a=>{V=Kb[a];f.hd=P=V?.rc;return!a||P?0:-5},db:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var g=v[b>>2],l=v[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=t[g+n],w=Wb[a];0===q||10===q?((1===a?ma:m)(K(w)),w.length=0):w.push(q)}e+=l}v[d>>2]=e;return 0},i:a=>P.activeTexture(a),x:(a,b)=>{P.attachShader(R[a],S[b])},b:(a,b)=>{35051==a?P.Dc=b:35052==a&&(P.jc=b);P.bindBuffer(a,Q[b])},a:(a,b,c)=>{P.bindBufferBase(a,b,Q[c])},
o:(a,b)=>{P.bindFramebuffer(a,Gb[b])},za:(a,b)=>{P.bindRenderbuffer(a,Hb[b])},h:(a,b)=>{P.bindSampler(a,T[b])},c:(a,b)=>{P.bindTexture(a,Ib[b])},J:a=>{P.bindVertexArray(Jb[a])},F:(a,b,c,d)=>P.blendColor(a,b,c,d),G:(a,b)=>P.blendEquationSeparate(a,b),H:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),hb:(a,b,c,d,e,h,g,l,n,q)=>P.blitFramebuffer(a,b,c,d,e,h,g,l,n,q),Ca:(a,b,c,d)=>{2<=V.version?c&&b?P.bufferData(a,t,d,c,b):P.bufferData(a,b,d):P.bufferData(a,c?t.subarray(c,c+b):b,d)},z:(a,b,c,d)=>{2<=V.version?
c&&P.bufferSubData(a,b,t,d,c):P.bufferSubData(a,b,t.subarray(d,d+c))},Ab:(a,b,c,d)=>P.clearBufferfi(a,b,c,d),ia:(a,b,c)=>{P.clearBufferfv(a,b,x,c>>2)},zb:(a,b,c)=>{P.clearBufferiv(a,b,u,c>>2)},l:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},Eb:a=>{P.compileShader(S[a])},ta:(a,b,c,d,e,h,g,l)=>{2<=V.version?P.jc||!g?P.compressedTexImage2D(a,b,c,d,e,h,g,l):P.compressedTexImage2D(a,b,c,d,e,h,t,l,g):P.compressedTexImage2D(a,b,c,d,e,h,t.subarray(l,l+g))},ra:(a,b,c,d,e,h,g,l,n)=>{P.jc?P.compressedTexImage3D(a,
b,c,d,e,h,g,l,n):P.compressedTexImage3D(a,b,c,d,e,h,g,t,n,l)},oa:()=>{var a=Ob(R),b=P.createProgram();b.name=a;b.pc=b.nc=b.oc=0;b.Ac=1;R[a]=b;return a},Gb:a=>{var b=Ob(S);S[b]=P.createShader(a);return b},C:a=>P.cullFace(a),Ga:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(P.deleteBuffer(e),e.name=0,Q[d]=null,d==P.Dc&&(P.Dc=0),d==P.jc&&(P.jc=0))}},j:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=Gb[d];e&&(P.deleteFramebuffer(e),e.name=0,Gb[d]=null)}},r:a=>{if(a){var b=R[a];b?(P.deleteProgram(b),
b.name=0,R[a]=null):U||=1281}},A:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Hb[d];e&&(P.deleteRenderbuffer(e),e.name=0,Hb[d]=null)}},s:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=T[d];e&&(P.deleteSampler(e),e.name=0,T[d]=null)}},p:a=>{if(a){var b=S[a];b?(P.deleteShader(b),S[a]=null):U||=1281}},B:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Ib[d];e&&(P.deleteTexture(e),e.name=0,Ib[d]=null)}},Ea:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];P.deleteVertexArray(Jb[d]);Jb[d]=null}},v:a=>
P.depthFunc(a),u:a=>{P.depthMask(!!a)},e:a=>P.disable(a),I:a=>{P.disableVertexAttribArray(a)},jb:(a,b,c)=>{P.drawArrays(a,b,c)},kb:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},lb:(a,b,c,d)=>{P.drawElements(a,b,c,d)},mb:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},g:a=>P.enable(a),wb:a=>{P.enableVertexAttribArray(a)},D:a=>P.frontFace(a),Da:(a,b)=>{Pb(a,b,"createBuffer",Q)},Ba:(a,b)=>{Pb(a,b,"createRenderbuffer",Hb)},pa:(a,b)=>{Pb(a,b,"createSampler",T)},xa:(a,b)=>{Pb(a,b,"createTexture",Ib)},Na:(a,
b)=>{Pb(a,b,"createVertexArray",Jb)},Cb:(a,b)=>P.getAttribLocation(R[a],b?K(t,b):""),d:(a,b)=>Yb(a,b),ma:(a,b,c,d)=>{a=P.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,d,b):0;c&&(u[c>>2]=b)},w:(a,b,c)=>{if(c)if(a>=Fb)U||=1281;else if(a=R[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.pc){var d=P.getProgramParameter(a,35718);for(b=0;b<d;++b)a.pc=Math.max(a.pc,P.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.pc}else if(35722==
b){if(!a.nc)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.nc=Math.max(a.nc,P.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.nc}else if(35381==b){if(!a.oc)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.oc=Math.max(a.oc,P.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.oc}else u[c>>2]=P.getProgramParameter(a,b);else U||=1281},Db:(a,b,c,d)=>{a=P.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,d,b):0;c&&(u[c>>2]=b)},ka:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(S[a]),null===
a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(S[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=P.getShaderParameter(S[a],b):U||=1281},La:(a,b)=>{if(2>V.version)return U||=1282,0;var c=Lb[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Xb().map($b),c=Lb[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},m:(a,b)=>{b=b?K(t,b):"";if(a=R[a]){var c=a,d=c.mc,e=c.Uc,h;if(!d){c.mc=d={};c.Tc={};var g=P.getProgramParameter(c,35718);for(h=
0;h<g;++h){var l=P.getActiveUniform(c,h);var n=l.name;l=l.size;var q=ac(n);q=0<q?n.slice(0,q):n;var w=c.Ac;c.Ac+=l;e[q]=[l,w];for(n=0;n<l;++n)d[w]=n,c.Tc[w++]=q}}c=a.mc;d=0;e=b;h=ac(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Uc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else U||=1281;return-1},gb:(a,b,c)=>{for(var d=bc[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];P.invalidateFramebuffer(a,d)},na:a=>{a=R[a];P.linkProgram(a);a.mc=0;a.Uc={}},Ma:(a,b)=>{3317==a?Mb=b:3314==
a&&(Nb=b);P.pixelStorei(a,b)},E:(a,b)=>P.polygonOffset(a,b),ib:a=>P.readBuffer(a),ya:(a,b,c,d,e)=>P.renderbufferStorageMultisample(a,b,c,d,e),y:(a,b,c)=>{P.samplerParameterf(T[a],b,c)},f:(a,b,c)=>{P.samplerParameteri(T[a],b,c)},n:(a,b,c,d)=>P.scissor(a,b,c,d),Fb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var g=(g=v[c+4*h>>2])?K(t,g,d?v[d+4*h>>2]:void 0):"";e+=g}P.shaderSource(S[a],e)},Ja:(a,b,c)=>P.stencilFunc(a,b,c),ha:(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),t:a=>P.stencilMask(a),Ia:(a,b,c)=>P.stencilOp(a,
b,c),ga:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),sa:(a,b,c,d,e,h,g,l,n)=>{if(2<=V.version){if(P.jc){P.texImage2D(a,b,c,d,e,h,g,l,n);return}if(n){var q=cc(l);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);P.texImage2D(a,b,c,d,e,h,g,l,q,n);return}}if(n){q=cc(l);var w=e*((Nb||d)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT+Mb-1&-Mb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+w>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;P.texImage2D(a,b,c,d,
e,h,g,l,n)},qa:(a,b,c,d,e,h,g,l,n,q)=>{if(P.jc)P.texImage3D(a,b,c,d,e,h,g,l,n,q);else if(q){var w=cc(n);P.texImage3D(a,b,c,d,e,h,g,l,n,w,q>>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else P.texImage3D(a,b,c,d,e,h,g,l,n,null)},wa:(a,b,c)=>P.texParameteri(a,b,c),va:(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),ua:(a,b,c,d,e,h)=>P.texStorage3D(a,b,c,d,e,h),vb:(a,b,c)=>{if(2<=V.version)b&&P.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);P.uniform1fv(W(a),
d)}},la:(a,b)=>{P.uniform1i(W(a),b)},rb:(a,b,c)=>{if(2<=V.version)b&&P.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=dc[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);P.uniform1iv(W(a),d)}},ub:(a,b,c)=>{if(2<=V.version)b&&P.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);P.uniform2fv(W(a),d)}},qb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=
2;for(var d=dc[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);P.uniform2iv(W(a),d)}},tb:(a,b,c)=>{if(2<=V.version)b&&P.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);P.uniform3fv(W(a),d)}},pb:(a,b,c)=>{if(2<=V.version)b&&P.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b){b*=3;for(var d=dc[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+
4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);P.uniform3iv(W(a),d)}},sb:(a,b,c)=>{if(2<=V.version)b&&P.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);P.uniform4fv(W(a),d)}},ob:(a,b,c)=>{if(2<=V.version)b&&P.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=dc[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+
8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);P.uniform4iv(W(a),d)}},nb:(a,b,c,d)=>{if(2<=V.version)b&&P.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=x;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=x.subarray(d>>2,d+64*
b>>2);P.uniformMatrix4fv(W(a),!!c,e)}},k:a=>{a=R[a];P.useProgram(a);P.Wc=a},xb:(a,b)=>{P.vertexAttribDivisor(a,b)},yb:(a,b,c,d,e,h)=>{P.vertexAttribPointer(a,b,c,!!d,e,h)},ja:(a,b,c,d)=>P.viewport(a,b,c,d),Za:Qa,Ib:function(){f.Nc=a=>{0!=mc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Nc)},Ra:function(){f.Sc=a=>{const b=a.clipboardData.getData("text");ic(()=>{const c=fc(b);nc(c)})};window.addEventListener("paste",f.Sc)},Ha:function(a){f.zd=[];a=a?K(t,a):"";a=
document.getElementById(a);f.Oc=b=>{b.stopPropagation();b.preventDefault()};f.Pc=b=>{b.stopPropagation();b.preventDefault()};f.Qc=b=>{b.stopPropagation();b.preventDefault()};f.Rc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Ad=c;oc(c.length);for(let e=0;e<c.length;e++)ic(()=>{const h=fc(c[e].name);pc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);qc(b.clientX,b.clientY,d)};a.addEventListener("dragenter",f.Oc,!1);a.addEventListener("dragleave",
f.Pc,!1);a.addEventListener("dragover",f.Qc,!1);a.addEventListener("drop",f.Rc,!1)},Hb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Aa:function(a){a=a?K(t,a):"";f.lc=document.getElementById(a);f.lc||console.log("sokol_app.h: invalid target:"+a);f.lc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Ua:function(){window.removeEventListener("beforeunload",f.Nc)},Qa:function(){window.removeEventListener("paste",
f.Sc)},Fa:function(a){a=a?K(t,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",f.Oc);a.removeEventListener("dragleave",f.Pc);a.removeEventListener("dragover",f.Qc);a.removeEventListener("drop",f.Rc)},q:function(){f.lc&&f.lc.requestPointerLock&&f.lc.requestPointerLock()},Bb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(t.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");
a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ka:function(a){a=a?K(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},
fa:function(a,b){b=b?K(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Jb:function(){return navigator.userAgent.includes("Macintosh")?1:0}},Z=function(){function a(c){Z=c.exports;oa=Z.Kb;sa();rb=Z.Zb;va.unshift(Z.Lb);z--;f.monitorRunDependencies?.(z);0==z&&(null!==Ca&&(clearInterval(Ca),Ca=null),A&&(c=A,A=null,c()));return Z}var b={a:rc};z++;f.monitorRunDependencies?.(z);if(f.instantiateWasm)try{return f.instantiateWasm(b,
a)}catch(c){return m(`Module.instantiateWasm callback failed with error: ${c}`),!1}Fa??=Ea("nuklear-sapp.wasm")?"nuklear-sapp.wasm":f.locateFile?f.locateFile("nuklear-sapp.wasm",k):k+"nuklear-sapp.wasm";Ja(b,function(c){a(c.instance)});return{}}(),N=a=>(N=Z.Mb)(a),nc=f.__sapp_emsc_onpaste=a=>(nc=f.__sapp_emsc_onpaste=Z.Nb)(a),mc=f.__sapp_html5_get_ask_leave_site=()=>(mc=f.__sapp_html5_get_ask_leave_site=Z.Ob)(),oc=f.__sapp_emsc_begin_drop=a=>(oc=f.__sapp_emsc_begin_drop=Z.Pb)(a),pc=f.__sapp_emsc_drop=
(a,b)=>(pc=f.__sapp_emsc_drop=Z.Qb)(a,b),qc=f.__sapp_emsc_end_drop=(a,b,c)=>(qc=f.__sapp_emsc_end_drop=Z.Rb)(a,b,c);f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,g,l)=>(f.__sapp_emsc_invoke_fetch_cb=Z.Sb)(a,b,c,d,e,h,g,l);var sc=f._main=(a,b)=>(sc=f._main=Z.Tb)(a,b);f.__saudio_emsc_pull=a=>(f.__saudio_emsc_pull=Z.Ub)(a);f.__sfetch_emsc_head_response=(a,b)=>(f.__sfetch_emsc_head_response=Z.Vb)(a,b);f.__sfetch_emsc_get_response=(a,b,c)=>(f.__sfetch_emsc_get_response=Z.Wb)(a,b,c);
f.__sfetch_emsc_failed_http_status=(a,b)=>(f.__sfetch_emsc_failed_http_status=Z.Xb)(a,b);f.__sfetch_emsc_failed_buffer_too_small=a=>(f.__sfetch_emsc_failed_buffer_too_small=Z.Yb)(a);var lc=(a,b)=>(lc=Z._b)(a,b),hc=a=>(hc=Z.$b)(a),ec=a=>(ec=Z.ac)(a),gc=()=>(gc=Z.bc)(),tc,uc;A=function vc(){tc||wc();tc||(A=vc)};function xc(a=[]){var b=sc;a.unshift(fa);var c=a.length,d=ec(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=fc(g);e+=4});v[e>>2]=0;try{var h=b(c,d);Ra(h)}catch(g){Oa(g)}}
function wc(){var a=ea;function b(){if(!tc&&(tc=1,f.calledRun=1,!p)){Aa(va);Aa(wa);f.onRuntimeInitialized?.();yc&&xc(a);var c=f.postRun;c&&("function"==typeof c&&(c=[c]),c.forEach(Ba));Aa(xa)}}if(!(0<z)){if(!uc&&(uc=1,ya(),0<z))return;f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var yc=!0;f.noInitialRun&&(yc=!1);wc();
