var h;h||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),m,p=!1,na,la=a=>a.startsWith("file://"),r,u,oa,pa,v,w,x,y;
function qa(){var a=ra.buffer;r=new Int8Array(a);oa=new Int16Array(a);u=new Uint8Array(a);pa=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function sa(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(h)},za=[],Aa=[],Ba=()=>{var a=h.preRun.shift();Aa.push(a)},z=0,A=null,Ca=!0,Da=globalThis.TextDecoder&&new TextDecoder,B=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Da)return Da.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,
c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Ea=0,Fa=[0,31,60,91,121,152,182,213,244,274,305,335],Ga=[0,31,59,90,120,151,181,212,243,273,304,334],C={},Ha=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Ia=a=>{na=a;Ca||0<Ea||(h.onExit?.(a),p=!0);fa(a,new xa(a))},Ja=()=>{if(!(Ca||0<Ea))try{var a=na;na=a;Ia(a)}catch(b){Ha(b)}},Ka=a=>{if(!p)try{a()}catch(b){Ha(b)}finally{Ja()}},F=(a,b,c)=>{var d=u;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=
a.codePointAt(g);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;g++}}d[b]=0;return b-e},Ra=(a,b)=>{La=a;Ma=b;if(G)if(Na||=!0,0==a)H=function(){setTimeout(I,Math.max(0,Oa+b-performance.now())|0)};else if(1==a)H=function(){Pa(I)};else if(2==a){if(!Qa)if(globalThis.setImmediate)Qa=
setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}H=function(){Qa(I)}}},$a=(a,b,c,d,e)=>{function g(){return f<Sa?(Ja(),!1):!0}G=a;Ta=d;var f=Sa;Na=!1;I=function(){if(!p)if(0<Ua.length){var l=Ua.shift();l.Id(l.wd);if(Va){var n=
Va,q=0==n%1?n-1:Math.floor(n);Va=l.zd?q:(8*n+(q+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=Va??0,q=Wa.Fd??0,n?n<q?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));g()&&setTimeout(I,0)}else if(g())if(Xa=Xa+1|0,1==La&&1<Ma&&0!=Xa%Ma)H();else{0==La&&(Oa=performance.now());a:if(!p){for(l of Ya)if(!1===l())break a;Ka(a);for(n of Za)n()}g()&&H()}};e||(0<b?Ra(0,1E3/b):Ra(1,1),H());if(c)throw"unwind";},Na=!1,H=null,Sa=0,G=null,Ta=0,La=0,Ma=0,Xa=
0,Ua=[],Ya=[],Za=[];function ab(){H=null;Sa++}var bb=0;function Pa(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===bb)bb=b+1E3/60;else for(;b+2>=bb;)bb+=1E3/60;setTimeout(a,Math.max(bb-b,0))}}var Wa={},Oa,I,Qa,Va,cb=[0,globalThis.document??0,globalThis.window??0],J=a=>{a=2<a?a?B(u,a):"":a;return cb[a]||globalThis.document?.querySelector(a)},db=a=>0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},eb=[],K=a=>{var b=eb[a];b||(eb[a]=b=fb.get(a));return b};
function gb(a){var b=L.wc[a];b.target.removeEventListener(b.vc,b.ad,b.zc);L.wc.splice(a,1)}function hb(){if(navigator.userActivation?navigator.userActivation.isActive:L.Oc&&L.qd.Lc){var a=L.Dc;L.Dc=[];for(var b of a)b.Rc(...b.Xc)}}function M(a){if(!a.target)return-4;if(a.xc)a.ad=function(c){++L.Oc;L.qd=a;hb();a.Bc(c);hb();--L.Oc},a.target.addEventListener(a.vc,a.ad,a.zc),L.wc.push(a);else for(var b=0;b<L.wc.length;++b)L.wc[b].target==a.target&&L.wc[b].vc==a.vc&&gb(b--);return 0}
function ib(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var L={xd:0,Jd:0,Pc:0,Jc:0,Vc:0,Tc:0,Mc:0,Dd:0,Nd:0,Cd:0,Nc:0,Qc:0,Xd:0,Sc:0,Pd(){for(;L.wc.length;)gb(L.wc.length-1);L.Dc=[]},Oc:0,Dc:[],Bd(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of L.Dc)if(e.Rc==a&&d(e.Xc,c))return;L.Dc.push({Rc:a,ed:b,Xc:c});L.Dc.sort((g,f)=>g.ed<f.ed)},Rd(a){L.Dc=L.Dc.filter(b=>b.Rc!=a)},wc:[],Qd:(a,b)=>{for(var c=0;c<L.wc.length;++c)L.wc[c].target!=a||b&&b!=L.wc[c].vc||gb(c--)},Sd(a){let b=!1;for(let c=0;c<
L.wc.length;++c){const d=L.wc[c];d.target===a.target&&d.yc===a.yc&&d.xc===a.xc&&d.Ac===a.Ac&&(gb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},jb=(a,b,c,d,e,g)=>{L.Mc||(L.Mc=N(256));a={target:J(a),vc:g,yc:e,Ac:b,xc:d,Bc:f=>{var l=f.target.id?f.target.id:"",n=L.Mc;F(ib(f.target),n+0,128);F(l,n+128,128);K(d)(e,n,b)&&f.preventDefault()},zc:c};return M(a)},kb=(a,b,c,d,e)=>{L.Nc||(L.Nc=N(276));return M({target:a,vc:e,yc:19,Ac:b,xc:d,
Bc:g=>{var f=L.Nc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!l;r[f]=n;r[f+1]=L.fullscreenEnabled();var q=n?l:L.ud,t=q?.id||"";F(ib(q),f+2,128);F(t,f+130,128);v[f+260>>2]=q?q.clientWidth:0;v[f+264>>2]=q?q.clientHeight:0;v[f+268>>2]=screen.width;v[f+272>>2]=screen.height;n&&(L.ud=l);K(d)(19,f,b)&&g.preventDefault()},zc:c})},lb=(a,b,c,d,e,g)=>{L.Pc||(L.Pc=N(160));a={target:J(a),
vc:g,yc:e,Ac:b,xc:d,Bc:f=>{var l=L.Pc;y[l>>3]=f.timeStamp;var n=l>>2;v[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;v[n+5]=f.charCode;v[n+6]=f.keyCode;v[n+7]=f.which;F(f.key||"",l+32,32);F(f.code||"",l+64,32);F(f.char||"",l+96,32);F(f.locale||"",l+128,32);K(d)(e,l,b)&&f.preventDefault()},zc:c};return M(a)},mb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+
25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=db(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},nb=(a,b,c,d,e,g)=>{L.Jc||(L.Jc=N(64));a=J(a);return M({target:a,Lc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,vc:g,yc:e,Ac:b,xc:d,Bc:f=>{mb(L.Jc,f,a);K(d)(e,L.Jc,b)&&f.preventDefault()},zc:c})},ob=(a,b,c,d)=>{L.Qc||(L.Qc=N(257));return M({target:a,vc:"pointerlockchange",yc:20,Ac:b,xc:d,Bc:e=>{var g=
L.Qc,f=document.pointerLockElement;r[g]=!!f;var l=f?.id||"";F(ib(f),g+1,128);F(l,g+129,128);K(d)(20,g,b)&&e.preventDefault()},zc:c})},pb=(a,b,c,d)=>M({target:a,vc:"pointerlockerror",yc:38,Ac:b,xc:d,Bc:e=>{K(d)(38,0,b)&&e.preventDefault()},zc:c}),qb=(a,b,c,d)=>{L.Tc||(L.Tc=N(36));a=J(a);return M({target:a,vc:"resize",yc:10,Ac:b,xc:d,Bc:e=>{if(e.target==a){var g=document.body;if(g){var f=L.Tc;v[f>>2]=0;v[f+4>>2]=g.clientWidth;v[f+8>>2]=g.clientHeight;v[f+12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+
20>>2]=outerWidth;v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|0;v[f+32>>2]=pageYOffset|0;K(d)(10,f,b)&&e.preventDefault()}}},zc:c})},rb=(a,b,c,d,e,g)=>{L.Sc||(L.Sc=N(1552));a=J(a);return M({target:a,Lc:"touchstart"==g||"touchend"==g,vc:g,yc:e,Ac:b,xc:d,Bc:f=>{var l={},n=f.touches;for(var q of n)q.bd=q.dd=0,l[q.identifier]=q;for(var t of f.changedTouches)t.bd=1,l[t.identifier]=t;for(var D of f.targetTouches)l[D.identifier].dd=1;n=L.Sc;y[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=f.shiftKey;r[n+
14]=f.altKey;r[n+15]=f.metaKey;q=n+16;t=db(a);D=0;for(let E of Object.values(l))if(l=q>>2,v[l]=E.identifier,v[l+1]=E.screenX,v[l+2]=E.screenY,v[l+3]=E.clientX,v[l+4]=E.clientY,v[l+5]=E.pageX,v[l+6]=E.pageY,r[q+28]=E.bd,r[q+29]=E.dd,v[l+8]=E.clientX-(t.left|0),v[l+9]=E.clientY-(t.top|0),q+=48,31<++D)break;v[n+8>>2]=D;K(d)(e,n,b)&&f.preventDefault()},zc:c})},O,sb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},tb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},ub=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},vb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},wb=1,P=[],Q=[],xb=[],yb=[],R=[],S=[],zb=[],Ab=[],T=[],Bb={},Cb=4,Db=0,Eb=a=>{for(var b=wb++,c=a.length;c<b;c++)a[c]=null;return b},V=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=O[c](),f=g&&Eb(d);g?(g.name=f,d[f]=g):U||=1282;v[b+4*e>>2]=f}},Gb=(a,b)=>{a.pd||(a.pd=a.getContext,a.getContext=function(d,e){e=a.pd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.cd?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Fb(c,b):0},Fb=(a,b)=>{var c=Eb(Ab),d={handle:c,attributes:b,version:b.cd,Wc:a};a.canvas&&(a.canvas.vd=d);Ab[c]=d;if("undefined"==typeof b.$c||b.$c)if((a=d)||(a=W),!a.td){a.td=!0;b=a.Wc;b.Md=b.getExtension("WEBGL_multi_draw");b.Hd=b.getExtension("EXT_polygon_offset_clamp");b.Gd=b.getExtension("EXT_clip_control");b.Yd=b.getExtension("WEBGL_polygon_mode");sb(b);tb(b);ub(b);b.Ed=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Kd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Zc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Zc)b.Zc=b.getExtension("EXT_disjoint_timer_query");for(var e of vb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},U,W,Hb=(a,b,c,d,e,g)=>{a={target:J(a),vc:g,yc:e,Ac:b,xc:d,Bc:f=>{K(d)(e,0,b)&&f.preventDefault()},zc:c};M(a)},Ib=(a,b,c,d)=>{L.Vc||(L.Vc=N(96));return M({target:a,Lc:!0,vc:"wheel",yc:9,Ac:b,xc:d,Bc:e=>{var g=L.Vc;mb(g,e,a);y[g+64>>3]=e.deltaX;y[g+72>>3]=e.deltaY;y[g+
80>>3]=e.deltaZ;v[g+88>>2]=e.deltaMode;K(d)(9,g,b)&&e.preventDefault()},zc:c})},Jb=["default","low-power","high-performance"],Kb={},Mb=()=>{if(!Lb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Kb)void 0===Kb[b]?delete a[b]:a[b]=Kb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Lb=c}return Lb},Lb,Nb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=
d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ob=[null,[],[]],Pb=[],Qb=()=>{var a=vb(O);return a=a.concat(a.map(b=>"GL_"+b))},Rb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=O.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>W.version){U||=1282;return}c=Qb().length;break;case 33307:case 33308:if(2>W.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=O.getParameter(a),typeof d){case "number":c=
d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){U||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else U||=1281},Sb=a=>{var b=Nb(a)+1,c=N(b);c&&F(a,c,b);return c},Tb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ub=a=>{a-=5120;return 0==a?r:1==a?u:2==a?oa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==
a?w:pa},X=a=>{var b=O.rd;if(b){var c=b.Fc[a];"number"==typeof c&&(b.Fc[a]=c=O.getUniformLocation(b,b.nd[a]+(0<c?`[${c}]`:"")));return c}U||=1282},Y=[],Vb=[],Xb=a=>{var b=Nb(a)+1,c=Wb(b);F(a,c,b);return c},$b=a=>{var b=Yb();a();Zb(b)};h.requestAnimationFrame=Pa;h.pauseMainLoop=ab;h.resumeMainLoop=function(){Sa++;var a=La,b=Ma,c=G;G=null;$a(c,0,!1,Ta,!0);Ra(a,b);H()};h.preMainLoop&&Ya.push(h.preMainLoop);h.postMainLoop&&Za.push(h.postMainLoop);for(let a=0;32>a;++a)Pb.push(Array(a));
for(var ac=new Float32Array(288),Z=0;288>=Z;++Z)Y[Z]=ac.subarray(0,Z);var bc=new Int32Array(288);for(Z=0;288>=Z;++Z)Vb[Z]=bc.subarray(0,Z);h.noExitRuntime&&(Ca=h.noExitRuntime);h.print&&(ma=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(m=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();
var N,cc,dc,ec,fc,gc,hc,ic,Zb,Wb,Yb,ra,fb,jc={qa:function(){return 0},kb:function(){return 0},lb:function(){},pb:()=>sa(""),cb:()=>{Ca=!1;Ea=0},fb:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);v[b>>2]=a.getSeconds();v[b+4>>2]=a.getMinutes();v[b+8>>2]=a.getHours();v[b+12>>2]=a.getDate();v[b+16>>2]=a.getMonth();v[b+20>>2]=a.getFullYear()-1900;v[b+24>>2]=a.getDay();var c=a.getFullYear();v[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Ga:Fa)[a.getMonth()]+a.getDate()-
1|0;v[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();v[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},db:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ka(()=>ic(a,performance.now()))},b);C[a]={id:c,Wd:b};return 0},gb:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();
w[a>>2]=60*Math.max(g,e);v[b>>2]=Number(g!=e);b=f=>{var l=Math.abs(f);return`UTC${0<=f?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(F(a,c,17),F(b,d,17)):(F(a,d,17),F(b,c,17))},Ua:()=>{ab();G=null},ob:()=>Date.now(),ma:()=>globalThis.devicePixelRatio??1,pa:(a,b,c)=>{a=J(a);if(!a)return-4;a=db(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Va:()=>performance.now(),_a:(a,b)=>{function c(d){K(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
eb:a=>{var b=u.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ra.buffer.byteLength+65535)/65536|0;try{ra.grow(d);qa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},W:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),la:(a,b,c)=>{a=J(a);if(!a)return-4;a.width=b;a.height=c;return 0},X:(a,b,c,d)=>jb(a,b,c,d,13,"focus"),V:(a,b,c,d)=>{if(!L.fullscreenEnabled())return-1;a=J(a);if(!a)return-4;
kb(a,b,c,d,"webkitfullscreenchange");return kb(a,b,c,d,"fullscreenchange")},ea:(a,b,c,d)=>lb(a,b,c,d,2,"keydown"),ca:(a,b,c,d)=>lb(a,b,c,d,1,"keypress"),da:(a,b,c,d)=>lb(a,b,c,d,3,"keyup"),ab:(a,b,c)=>{a=K(a);$a(a,b,c)},ka:(a,b,c,d)=>nb(a,b,c,d,5,"mousedown"),ha:(a,b,c,d)=>nb(a,b,c,d,33,"mouseenter"),ga:(a,b,c,d)=>nb(a,b,c,d,34,"mouseleave"),ia:(a,b,c,d)=>nb(a,b,c,d,8,"mousemove"),ja:(a,b,c,d)=>nb(a,b,c,d,6,"mouseup"),Z:(a,b,c,d)=>document.body?.requestPointerLock?(a=J(a))?ob(a,b,c,d):-4:-1,Y:(a,
b,c,d)=>document.body?.requestPointerLock?(a=J(a))?pb(a,b,c,d):-4:-1,na:(a,b,c,d)=>qb(a,b,c,d),_:(a,b,c,d)=>rb(a,b,c,d,25,"touchcancel"),$:(a,b,c,d)=>rb(a,b,c,d,23,"touchend"),aa:(a,b,c,d)=>rb(a,b,c,d,24,"touchmove"),ba:(a,b,c,d)=>rb(a,b,c,d,22,"touchstart"),U:(a,b,c,d)=>{Hb(a,b,c,d,31,"webglcontextlost");return 0},T:(a,b,c,d)=>{Hb(a,b,c,d,32,"webglcontextrestored");return 0},fa:(a,b,c,d)=>(a=J(a))?"undefined"!=typeof a.onwheel?Ib(a,b,c,d):-1:-4,Za:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+
1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Jb[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],cd:v[c+4],Ld:v[c+5],$c:r[b+24],sd:r[b+25],Od:v[c+7],Td:r[b+32]};a=J(a);return!a||b.sd?0:Gb(a,b)},Ya:a=>{W=Ab[a];h.ctx=O=W?.Wc;return!a||O?0:-5},mb:(a,b)=>{var c=0,d=0,e;for(e of Mb()){var g=b+c;w[a+d>>2]=g;c+=F(e,g,Infinity)+1;d+=4}return 0},nb:(a,b)=>{var c=Mb();w[a>>2]=c.length;a=0;for(var d of c)a+=Nb(d)+1;w[b>>2]=a;return 0},oa:()=>
52,jb:()=>52,hb:function(){return 70},ib:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=w[b>>2],l=w[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=a,t=u[f+n],D=Ob[q];0===t||10===t?((1===q?ma:k)(B(D)),D.length=0):D.push(t)}e+=l}w[d>>2]=e;return 0},p:a=>O.activeTexture(a),t:(a,b)=>{O.attachShader(Q[a],S[b])},a:(a,b)=>{35051==a?O.Yc=b:35052==a&&(O.Ec=b);O.bindBuffer(a,P[b])},y:(a,b,c)=>{O.bindBufferBase(a,b,P[c])},Hb:(a,b,c,d,e)=>{O.bindBufferRange(a,b,P[c],d,e)},i:(a,b)=>{O.bindFramebuffer(a,xb[b])},Sb:(a,b)=>
{O.bindRenderbuffer(a,yb[b])},o:(a,b)=>{O.bindSampler(a,T[b])},c:(a,b)=>{O.bindTexture(a,R[b])},S:a=>{O.bindVertexArray(zb[a])},N:(a,b,c,d)=>O.blendColor(a,b,c,d),O:(a,b)=>O.blendEquationSeparate(a,b),P:(a,b,c,d)=>O.blendFuncSeparate(a,b,c,d),rb:(a,b,c,d,e,g,f,l,n,q)=>O.blitFramebuffer(a,b,c,d,e,g,f,l,n,q),Ha:(a,b,c,d)=>{2<=W.version?c&&b?O.bufferData(a,u,d,c,b):O.bufferData(a,b,d):O.bufferData(a,c?u.subarray(c,c+b):b,d)},H:(a,b,c,d)=>{2<=W.version?c&&O.bufferSubData(a,b,u,d,c):O.bufferSubData(a,
b,u.subarray(d,d+c))},Pb:a=>O.checkFramebufferStatus(a),Ob:(a,b,c,d)=>O.clearBufferfi(a,b,c,d),va:(a,b,c)=>{O.clearBufferfv(a,b,x,c>>2)},Nb:(a,b,c)=>{O.clearBufferiv(a,b,v,c>>2)},q:(a,b,c,d)=>{O.colorMask(!!a,!!b,!!c,!!d)},Wb:a=>{O.compileShader(S[a])},w:(a,b,c,d,e,g,f,l,n)=>{2<=W.version?O.Ec||!l?O.compressedTexSubImage2D(a,b,c,d,e,g,f,l,n):O.compressedTexSubImage2D(a,b,c,d,e,g,f,u,n,l):O.compressedTexSubImage2D(a,b,c,d,e,g,f,u.subarray(n,n+l))},Da:(a,b,c,d,e,g,f,l,n,q,t)=>{O.Ec?O.compressedTexSubImage3D(a,
b,c,d,e,g,f,l,n,q,t):O.compressedTexSubImage3D(a,b,c,d,e,g,f,l,n,u,t,q)},Aa:()=>{var a=Eb(Q),b=O.createProgram();b.name=a;b.Ic=b.Gc=b.Hc=0;b.Uc=1;Q[a]=b;return a},Yb:a=>{var b=Eb(S);S[b]=O.createShader(a);return b},K:a=>O.cullFace(a),La:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=P[d];e&&(O.deleteBuffer(e),e.name=0,P[d]=null,d==O.Yc&&(O.Yc=0),d==O.Ec&&(O.Ec=0))}},x:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=xb[d];e&&(O.deleteFramebuffer(e),e.name=0,xb[d]=null)}},n:a=>{if(a){var b=Q[a];
b?(O.deleteProgram(b),b.name=0,Q[a]=null):U||=1281}},I:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=yb[d];e&&(O.deleteRenderbuffer(e),e.name=0,yb[d]=null)}},J:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=T[d];e&&(O.deleteSampler(e),e.name=0,T[d]=null)}},l:a=>{if(a){var b=S[a];b?(O.deleteShader(b),S[a]=null):U||=1281}},j:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=R[d];e&&(O.deleteTexture(e),e.name=0,R[d]=null)}},Ka:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];O.deleteVertexArray(zb[d]);
zb[d]=null}},A:a=>O.depthFunc(a),z:a=>{O.depthMask(!!a)},d:a=>O.disable(a),Q:a=>{O.disableVertexAttribArray(a)},tb:(a,b,c)=>{O.drawArrays(a,b,c)},ub:(a,b,c,d)=>{O.drawArraysInstanced(a,b,c,d)},wa:(a,b)=>{for(var c=Pb[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];O.drawBuffers(c)},vb:(a,b,c,d)=>{O.drawElements(a,b,c,d)},wb:(a,b,c,d,e)=>{O.drawElementsInstanced(a,b,c,d,e)},g:a=>O.enable(a),Ib:a=>{O.enableVertexAttribArray(a)},k:(a,b,c,d)=>{O.framebufferRenderbuffer(a,b,c,yb[d])},e:(a,b,c,d,e)=>{O.framebufferTexture2D(a,
b,c,R[d],e)},B:(a,b,c,d,e)=>{O.framebufferTextureLayer(a,b,R[c],d,e)},L:a=>O.frontFace(a),Ja:(a,b)=>{V(a,b,"createBuffer",P)},R:(a,b)=>{V(a,b,"createFramebuffer",xb)},Tb:(a,b)=>{V(a,b,"createRenderbuffer",yb)},Ba:(a,b)=>{V(a,b,"createSampler",T)},Ga:(a,b)=>{V(a,b,"createTexture",R)},Ta:(a,b)=>{V(a,b,"createVertexArray",zb)},Ub:(a,b)=>O.getAttribLocation(Q[a],b?B(u,b):""),b:(a,b)=>Rb(a,b),za:(a,b,c,d)=>{a=O.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,d,b):0;c&&(v[c>>2]=b)},
E:(a,b,c)=>{if(c)if(a>=wb)U||=1281;else if(a=Q[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.Ic){var d=O.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Ic=Math.max(a.Ic,O.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.Ic}else if(35722==b){if(!a.Gc)for(d=O.getProgramParameter(a,35721),b=0;b<d;++b)a.Gc=Math.max(a.Gc,O.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.Gc}else if(35381==b){if(!a.Hc)for(d=O.getProgramParameter(a,35382),b=0;b<
d;++b)a.Hc=Math.max(a.Hc,O.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Hc}else v[c>>2]=O.getProgramParameter(a,b);else U||=1281},Vb:(a,b,c,d)=>{a=O.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,d,b):0;c&&(v[c>>2]=b)},xa:(a,b,c)=>{c?35716==b?(a=O.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(S[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=O.getShaderParameter(S[a],b):U||=1281},Qa:(a,b)=>{if(2>W.version)return U||=1282,
0;var c=Bb[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Qb().map(Sb),c=Bb[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},D:(a,b)=>{b=b?B(u,b):"";if(a=Q[a]){var c=a,d=c.Fc,e=c.od,g;if(!d){c.Fc=d={};c.nd={};var f=O.getProgramParameter(c,35718);for(g=0;g<f;++g){var l=O.getActiveUniform(c,g);var n=l.name;l=l.size;var q=Tb(n);q=0<q?n.slice(0,q):n;var t=c.Uc;c.Uc+=l;e[q]=[l,t];for(n=0;n<l;++n)d[t]=n,c.nd[t++]=q}}c=a.Fc;d=0;e=b;g=Tb(b);0<g&&(d=parseInt(b.slice(g+
1))>>>0,e=b.slice(0,g));if((e=a.od[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else U||=1281;return-1},qb:(a,b,c)=>{for(var d=Pb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];O.invalidateFramebuffer(a,d)},F:a=>{a=Q[a];O.linkProgram(a);a.Fc=0;a.od={}},Sa:(a,b)=>{3317==a?Cb=b:3314==a&&(Db=b);O.pixelStorei(a,b)},M:(a,b)=>O.polygonOffset(a,b),sb:a=>O.readBuffer(a),Rb:(a,b,c,d,e)=>O.renderbufferStorageMultisample(a,b,c,d,e),G:(a,b,c)=>{O.samplerParameterf(T[a],b,c)},f:(a,b,c)=>{O.samplerParameteri(T[a],
b,c)},h:(a,b,c,d)=>O.scissor(a,b,c,d),Xb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=w[c+4*g>>2])?B(u,f,d?w[d+4*g>>2]:void 0):"";e+=f}O.shaderSource(S[a],e)},Pa:(a,b,c)=>O.stencilFunc(a,b,c),ua:(a,b,c,d)=>O.stencilFuncSeparate(a,b,c,d),s:a=>O.stencilMask(a),Oa:(a,b,c)=>O.stencilOp(a,b,c),ta:(a,b,c,d)=>O.stencilOpSeparate(a,b,c,d),Fa:(a,b,c,d,e)=>O.texStorage2D(a,b,c,d,e),Ea:(a,b,c,d,e,g)=>O.texStorage3D(a,b,c,d,e,g),v:(a,b,c,d,e,g,f,l,n)=>{if(2<=W.version){if(O.Ec){O.texSubImage2D(a,b,c,d,e,g,
f,l,n);return}if(n){var q=Ub(l);O.texSubImage2D(a,b,c,d,e,g,f,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=Ub(l);var t=g*((Db||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*q.BYTES_PER_ELEMENT+Cb-1&-Cb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+t>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;O.texSubImage2D(a,b,c,d,e,g,f,l,n)},Ca:(a,b,c,d,e,g,f,l,n,q,t)=>{if(O.Ec)O.texSubImage3D(a,b,c,d,e,g,f,l,n,q,t);else if(t){var D=Ub(q);O.texSubImage3D(a,
b,c,d,e,g,f,l,n,q,D,t>>>31-Math.clz32(D.BYTES_PER_ELEMENT))}else O.texSubImage3D(a,b,c,d,e,g,f,l,n,q,null)},Gb:(a,b,c)=>{if(2<=W.version)b&&O.uniform1fv(X(a),x,c>>2,b);else{if(288>=b)for(var d=Y[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);O.uniform1fv(X(a),d)}},ya:(a,b)=>{O.uniform1i(X(a),b)},Bb:(a,b,c)=>{if(2<=W.version)b&&O.uniform1iv(X(a),v,c>>2,b);else{if(288>=b)for(var d=Vb[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);O.uniform1iv(X(a),d)}},Fb:(a,b,c)=>
{if(2<=W.version)b&&O.uniform2fv(X(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Y[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);O.uniform2fv(X(a),d)}},Ab:(a,b,c)=>{if(2<=W.version)b&&O.uniform2iv(X(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Vb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);O.uniform2iv(X(a),d)}},Eb:(a,b,c)=>{if(2<=W.version)b&&O.uniform3fv(X(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Y[b],e=
0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);O.uniform3fv(X(a),d)}},zb:(a,b,c)=>{if(2<=W.version)b&&O.uniform3iv(X(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Vb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);O.uniform3iv(X(a),d)}},Cb:(a,b,c)=>{if(2<=W.version)b&&O.uniform4fv(X(a),x,c>>2,4*b);else{if(72>=b){var d=Y[4*b],e=x;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=
e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);O.uniform4fv(X(a),d)}},yb:(a,b,c)=>{if(2<=W.version)b&&O.uniform4iv(X(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Vb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);O.uniform4iv(X(a),d)}},xb:(a,b,c,d)=>{if(2<=W.version)b&&O.uniformMatrix4fv(X(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=Y[16*b],g=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=
d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(X(a),!!c,e)}},m:a=>{a=Q[a];O.useProgram(a);O.rd=a},Jb:(a,b)=>{O.vertexAttribDivisor(a,b)},Kb:(a,b,c,d,e)=>{O.vertexAttribIPointer(a,b,c,d,e)},Lb:(a,b,c,d,e,g)=>{O.vertexAttribPointer(a,b,c,!!d,e,g)},r:(a,b,c,d)=>
O.viewport(a,b,c,d),bb:Ia,Zb:function(){h.gd=a=>{0!=dc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.gd)},Xa:function(){h.md=a=>{const b=a.clipboardData.getData("text");$b(()=>{const c=Xb(b);cc(c)})};window.addEventListener("paste",h.md)},Na:function(){h.Ud=[];h.hd=b=>{b.stopPropagation();b.preventDefault()};h.jd=b=>{b.stopPropagation();b.preventDefault()};h.kd=b=>{b.stopPropagation();b.preventDefault()};h.ld=b=>{b.stopPropagation();b.preventDefault();const c=
b.dataTransfer.files;h.Vd=c;ec(c.length);for(let e=0;e<c.length;e++)$b(()=>{const g=Xb(c[e].name);fc(e,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);gc(b.clientX,b.clientY,d)};const a=h.Cc;a.addEventListener("dragenter",h.hd,!1);a.addEventListener("dragleave",h.jd,!1);a.addEventListener("dragover",h.kd,!1);a.addEventListener("drop",h.ld,!1)},Mb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Qb:function(a){h.Kc&&
(URL.revokeObjectURL(h.Kc[a].yd),h.Kc[a]=null)},Ia:function(a,b){0!==b&&(document.title=b?B(u,b):"");a=a?B(u,a):"";void 0!==h.canvas&&("object"===typeof h.canvas?cb[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.Cc=J(a);h.Cc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Cc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},$a:function(){window.removeEventListener("beforeunload",h.gd)},Wa:function(){window.removeEventListener("paste",
h.md)},Ma:function(){const a=h.Cc;a.removeEventListener("dragenter",h.hd);a.removeEventListener("dragleave",h.jd);a.removeEventListener("dragover",h.kd);a.removeEventListener("drop",h.ld)},u:function(){h.Cc&&h.Cc.requestPointerLock&&h.Cc.requestPointerLock()},C:function(a,b,c){if(h.Cc){if(0===b)a="none";else if(0!=c)a=h.Kc[a].Ad;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a=
"ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.Cc.style.cursor=a}},Db:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,b);g.data.set(u.subarray(c,c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ra:function(a){a=
a?B(u,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},ra:function(){return navigator.userAgent.includes("Macintosh")?1:0},sa:function(a,b){b=b?B(u,b):"";switch(a){case 0:console.error(b);
break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},_b:function(){return navigator.userAgent.includes("Macintosh")?1:0}};function kc(a=[]){var b=hc;a.unshift(ea);var c=a.length,d=Wb(4*(c+1)),e=d,g;for(g of a)w[e>>2]=Xb(g),e+=4;w[e>>2]=0;try{var f=b(c,d);na=f;Ia(f)}catch(l){Ha(l)}}
function lc(a=da){function b(){h.calledRun=!0;if(!p){mc.ac();h.onRuntimeInitialized?.();h.noInitialRun||kc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();za.push(c)}ya(za)}}if(0<z)A=lc;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ba();ya(Aa);0<z?A=lc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var mc;
(async function(){function a(c){c=mc=c.exports;N=c.bc;cc=h.__sapp_emsc_onpaste=c.cc;dc=h.__sapp_html5_get_ask_leave_site=c.dc;ec=h.__sapp_emsc_begin_drop=c.ec;fc=h.__sapp_emsc_drop=c.fc;gc=h.__sapp_emsc_end_drop=c.gc;h.__sapp_emsc_invoke_fetch_cb=c.hc;h.__sapp_emsc_set_fullscreen_flag=c.ic;hc=h._main=c.jc;h.__saudio_emsc_pull=c.kc;h.__sfetch_emsc_head_response=c.lc;h.__sfetch_emsc_get_response=c.mc;h.__sfetch_emsc_failed_http_status=c.nc;h.__sfetch_emsc_failed_buffer_too_small=c.oc;h.__sfetch_emsc_failed_other=
c.pc;ic=c.rc;Zb=c.sc;Wb=c.tc;Yb=c.uc;ra=c.$b;fb=c.qc;qa();z--;h.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return mc}z++;h.monitorRunDependencies?.(z);var b={a:jc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ta??=h.locateFile?h.locateFile("nuklear-sapp-ui.wasm",ia):ia+"nuklear-sapp-ui.wasm";return a((await wa(b)).instance)})();lc();
