var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},g),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},h="",ia,ja;
if(ca){var fs=require("fs"),ka=require("path");h=__dirname+"/";ja=a=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a)};ia=a=>{a=la(a)?new URL(a):ka.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!g.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?h=self.location.href:"undefined"!=typeof document&&
document.currentScript&&(h=document.currentScript.src),h=h.startsWith("blob:")?"":h.substr(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=a=>la(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));g.print||console.log.bind(console);var m=g.printErr||console.error.bind(console);Object.assign(g,da);da=null;g.arguments&&(ea=g.arguments);g.thisProgram&&(fa=g.thisProgram);var ma=g.wasmBinary,na,q=!1,oa,r,t,pa,qa,u,v,w,x;
function ra(){var a=na.buffer;g.HEAP8=r=new Int8Array(a);g.HEAP16=pa=new Int16Array(a);g.HEAPU8=t=new Uint8Array(a);g.HEAPU16=qa=new Uint16Array(a);g.HEAP32=u=new Int32Array(a);g.HEAPU32=v=new Uint32Array(a);g.HEAPF32=w=new Float32Array(a);g.HEAPF64=x=new Float64Array(a)}var sa=[],ta=[],ua=[],va=[];function wa(){var a=g.preRun.shift();sa.unshift(a)}var z=0,xa=null,A=null;
function ya(a){g.onAbort?.(a);a="Aborted("+a+")";m(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var za=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),Aa;function Ba(a){if(a==Aa&&ma)return new Uint8Array(ma);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}function Ca(a){return ma?Promise.resolve().then(()=>Ba(a)):ia(a).then(b=>new Uint8Array(b),()=>Ba(a))}
function Da(a,b,c){return Ca(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{m(`failed to asynchronously prepare wasm: ${d}`);ya(d)})}function Ea(a,b){var c=Aa;ma||"function"!=typeof WebAssembly.instantiateStreaming||za(c)||la(c)||ca||"function"!=typeof fetch?Da(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){m(`wasm streaming compile failed: ${e}`);m("falling back to ArrayBuffer instantiation");return Da(c,a,b)}))}
class Fa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ga=a=>{for(;0<a.length;)a.shift()(g)},Ha=g.noExitRuntime||!0,Ia=0,B={},Ja=a=>{a instanceof Fa||"unwind"==a||ha(1,a)},Ka=a=>{oa=a;Ha||0<Ia||(g.onExit?.(a),q=!0);ha(a,new Fa(a))},La=a=>{oa=a;Ka(a)},Ma=()=>{if(!(Ha||0<Ia))try{var a=oa;oa=a;Ka(a)}catch(b){Ja(b)}},Na=a=>{if(!q)try{a(),Ma()}catch(b){Ja(b)}},Ua=(a,b)=>{Oa=a;Pa=b;if(C)if(Qa||=!0,0==a)D=function(){setTimeout(E,Math.max(0,Ra+b-performance.now())|0)};else if(1==a)D=function(){Sa(E)};else if(2==a){if("undefined"==typeof Ta)if("undefined"==
typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ta=d=>{c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ta=setImmediate;D=function(){Ta(E)}}},cb=(a,b,c,d,e)=>{function k(){return f<Va?(Ma(),!1):!0}C=a;Wa=d;var f=Va;Qa=!1;E=function(){if(!q)if(0<Xa.length){var l=Xa.shift();
l.td(l.jd);if(Ya){var n=Ya,p=0==n%1?n-1:Math.floor(n);Ya=l.ld?p:(8*n+(p+.5))/9}g.setStatus&&(l=g.statusMessage||"Please wait...",n=Ya??0,p=Za.rd??0,n?n<p?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(l):g.setStatus(""));k()&&setTimeout(E,0)}else if(k())if($a=$a+1|0,1==Oa&&1<Pa&&0!=$a%Pa)D();else{0==Oa&&(Ra=performance.now());a:if(!q){for(l of ab)if(!1===l())break a;Na(a);for(n of bb)n()}k()&&D()}};e||(b&&0<b?Ua(0,1E3/b):Ua(1,1),D());if(c)throw"unwind";},Qa=!1,D=null,Va=
0,C=null,Wa=0,Oa=0,Pa=0,$a=0,Xa=[],ab=[],bb=[];function db(){D=null;Va++}var G=0;function Sa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===G)G=b+1E3/60;else for(;b+2>=G;)G+=1E3/60;setTimeout(a,Math.max(G-b,0))}}var Za={},Ra,E,Ta,Ya;function eb(a){var b=H.hc[a];b.target.removeEventListener(b.fc,b.Kc,b.ic);H.hc.splice(a,1)}
function fb(){if(navigator.userActivation?navigator.userActivation.isActive:H.yc&&H.Zc.wc){var a=H.nc;H.nc=[];for(var b of a)b.Bc(...b.Gc)}}function I(a){if(!a.target)return-4;if(a.jc)a.Kc=function(c){++H.yc;H.Zc=a;fb();a.kc(c);fb();--H.yc},a.target.addEventListener(a.fc,a.Kc,a.ic),H.hc.push(a);else for(var b=0;b<H.hc.length;++b)H.hc[b].target==a.target&&H.hc[b].fc==a.fc&&eb(b--);return 0}function gb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var H={kd:0,ud:0,zc:0,uc:0,Fc:0,Dc:0,xc:0,pd:0,xd:0,od:0,sd:0,Ac:0,Gd:0,Cc:0,zd(){for(;H.hc.length;)eb(H.hc.length-1);H.nc=[]},yc:0,nc:[],nd(a,b,c){function d(k,f){if(k.length!=f.length)return!1;for(var l in k)if(k[l]!=f[l])return!1;return!0}for(var e of H.nc)if(e.Bc==a&&d(e.Gc,c))return;H.nc.push({Bc:a,Qc:b,Gc:c});H.nc.sort((k,f)=>k.Qc<f.Qc)},Bd(a){H.nc=H.nc.filter(b=>b.Bc!=a)},hc:[],Ad:(a,b)=>{for(var c=0;c<H.hc.length;++c)H.hc[c].target!=a||b&&b!=H.hc[c].fc||eb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||
document.webkitFullscreenEnabled}},hb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,J=(a=0,b=NaN)=>{var c=t,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&hb)return hb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var k=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|k<<6|f:(e&7)<<18|k<<12|f<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=
String.fromCharCode(e)}return d},ib=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?J(a):"":a;return ib[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},jb=a=>0>ib.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},kb=[],lb,L=a=>{var b=kb[a];b||(a>=kb.length&&(kb.length=a+1),kb[a]=b=lb.get(a));return b},M=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);if(55296<=f&&57343>=f){var l=
a.charCodeAt(++k);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},mb=(a,b,c,d,e,k)=>{H.xc||(H.xc=N(256));a={target:K(a),fc:k,jc:d,kc:(f=event)=>{var l=f.target.id?f.target.id:"",n=H.xc;M(gb(f.target),n+0,128);M(l,n+128,128);L(d)(e,n,b)&&f.preventDefault()},ic:c};return I(a)},
nb=(a,b,c,d,e,k)=>{H.zc||(H.zc=N(160));a={target:K(a),fc:k,jc:d,kc:f=>{var l=H.zc;x[l>>3]=f.timeStamp;var n=l>>2;u[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;u[n+5]=f.charCode;u[n+6]=f.keyCode;u[n+7]=f.which;M(f.key||"",l+32,32);M(f.code||"",l+64,32);M(f.char||"",l+96,32);M(f.locale||"",l+128,32);L(d)(e,l,b)&&f.preventDefault()},ic:c};return I(a)},ob=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;
u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=jb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,k)=>{H.uc||(H.uc=N(64));a=K(a);return I({target:a,wc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,fc:k,jc:d,kc:(f=event)=>{ob(H.uc,f,a);L(d)(e,H.uc,b)&&f.preventDefault()},ic:c})},pb=(a,b,c,d,e)=>{H.Ac||(H.Ac=N(257));return I({target:a,fc:e,jc:d,kc:(k=
event)=>{var f=H.Ac,l=document.pointerLockElement||document.oc||document.Mc||document.Lc;r[f]=!!l;var n=l?.id||"";M(gb(l),f+1,128);M(n,f+129,128);L(d)(20,f,b)&&k.preventDefault()},ic:c})},qb=(a,b,c,d,e)=>I({target:a,fc:e,jc:d,kc:(k=event)=>{L(d)(38,0,b)&&k.preventDefault()},ic:c}),rb=(a,b,c,d)=>{H.Dc||(H.Dc=N(36));a=K(a);return I({target:a,fc:"resize",jc:d,kc:(e=event)=>{if(e.target==a){var k=document.body;if(k){var f=H.Dc;u[f>>2]=0;u[f+4>>2]=k.clientWidth;u[f+8>>2]=k.clientHeight;u[f+12>>2]=innerWidth;
u[f+16>>2]=innerHeight;u[f+20>>2]=outerWidth;u[f+24>>2]=outerHeight;u[f+28>>2]=pageXOffset|0;u[f+32>>2]=pageYOffset|0;L(d)(10,f,b)&&e.preventDefault()}}},ic:c})},sb=(a,b,c,d,e,k)=>{H.Cc||(H.Cc=N(1552));a=K(a);return I({target:a,wc:"touchstart"==k||"touchend"==k,fc:k,jc:d,kc:f=>{var l={},n=f.touches;for(var p of n)p.Nc=p.Pc=0,l[p.identifier]=p;for(var y of f.changedTouches)y.Nc=1,l[y.identifier]=y;for(var P of f.targetTouches)l[P.identifier].Pc=1;n=H.Cc;x[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=
f.shiftKey;r[n+14]=f.altKey;r[n+15]=f.metaKey;p=n+16;y=jb(a);P=0;for(let F of Object.values(l))if(l=p>>2,u[l]=F.identifier,u[l+1]=F.screenX,u[l+2]=F.screenY,u[l+3]=F.clientX,u[l+4]=F.clientY,u[l+5]=F.pageX,u[l+6]=F.pageY,r[p+28]=F.Nc,r[p+29]=F.Pc,u[l+8]=F.clientX-(y.left|0),u[l+9]=F.clientY-(y.top|0),p+=48,31<++P)break;u[n+8>>2]=P;L(d)(e,n,b)&&f.preventDefault()},ic:c})},Q,tb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=(c,d,e,k,f)=>b.drawElementsInstancedANGLE(c,d,e,k,f))},ub=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},vb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},wb=a=>{a.qd=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
xb=a=>{a.vd=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},yb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},zb=1,Ab=[],R=[],Bb=[],Cb=[],Db=[],S=[],Eb=[],Fb=[],T=[],Gb={},Hb=4,Ib=0,Jb=a=>{for(var b=zb++,c=a.length;c<b;c++)a[c]=null;return b},Kb=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=Q[c](),f=k&&Jb(d);k?(k.name=f,d[f]=k):U||=1282;u[b+4*e>>2]=f}},Mb=(a,b)=>{a.oc||(a.oc=a.getContext,a.getContext=function(d,e){e=a.oc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Oc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?Lb(c,b):0},Lb=(a,b)=>{var c=Jb(Fb),d={handle:c,attributes:b,version:b.Oc,vc:a};a.canvas&&(a.canvas.hd=d);Fb[c]=d;("undefined"==typeof b.Jc||b.Jc)&&Nb(d);return c},Nb=a=>{a||=V;if(!a.dd){a.dd=!0;var b=a.vc;b.ed=b.getExtension("WEBGL_multi_draw");b.cd=b.getExtension("EXT_polygon_offset_clamp");b.bd=b.getExtension("EXT_clip_control");b.gd=b.getExtension("WEBGL_polygon_mode");tb(b);ub(b);vb(b);wb(b);xb(b);2<=a.version&&(b.Ic=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||
!b.Ic)b.Ic=b.getExtension("EXT_disjoint_timer_query");yb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},U,V,Ob=(a,b,c,d,e,k)=>{a={target:K(a),fc:k,jc:d,kc:(f=event)=>{L(d)(e,0,b)&&f.preventDefault()},ic:c};I(a)},Pb=(a,b,c,d)=>{H.Fc||(H.Fc=N(96));return I({target:a,wc:!0,fc:"wheel",jc:d,kc:(e=event)=>{var k=H.Fc;ob(k,e,a);x[k+64>>3]=e.deltaX;x[k+72>>3]=e.deltaY;x[k+80>>3]=e.deltaZ;u[k+88>>2]=e.deltaMode;L(d)(9,k,b)&&e.preventDefault()},ic:c})},Qb=["default","low-power",
"high-performance"];function Rb(){var a=yb(Q);return a=a.concat(a.map(b=>"GL_"+b))}
var Sb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Q.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=Rb().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=Q.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else U||=1281},Tb=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ub=a=>{var b=Tb(a)+1,c=N(b);c&&M(a,c,b);return c},Vb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Wb=[],Xb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?u:6==a?w:5==a||28922==a||28520==a||30779==a||30782==a?v:qa},Yb=(a,b,c,d,e)=>{a=Xb(a);b=d*((Ib||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Hb-1&-Hb);return a.subarray(e>>>31-
Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=Q.$c;if(b){var c=b.qc[a];"number"==typeof c&&(b.qc[a]=c=Q.getUniformLocation(b,b.Xc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],Zb=[],ac=a=>{var b=Tb(a)+1,c=$b(b);M(a,c,b);return c},dc=a=>{var b=bc();a();cc(b)};g.requestAnimationFrame=Sa;g.pauseMainLoop=db;g.resumeMainLoop=function(){Va++;var a=Oa,b=Pa,c=C;C=null;cb(c,0,!1,Wa,!0);Ua(a,b);D()};g.preMainLoop&&ab.push(g.preMainLoop);g.postMainLoop&&bb.push(g.postMainLoop);
for(var Y=0;32>Y;++Y)Wb.push(Array(Y));var ec=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=ec.subarray(0,Y);var fc=new Int32Array(288);for(Y=0;288>=Y;++Y)Zb[Y]=fc.subarray(0,Y);
var rc={$a:()=>{ya("")},_a:(a,b,c)=>t.copyWithin(a,b,b+c),Xa:()=>{Ha=!1;Ia=0},Ya:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];Na(()=>gc(a,performance.now()))},b);B[a]={id:c,Fd:b};return 0},Ma:()=>{db();C=null},_:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,aa:(a,b,c)=>{a=K(a);if(!a)return-4;a=jb(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},Na:()=>performance.now(),Ta:(a,b)=>{function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
Za:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ra();var e=1;break a}catch(k){}e=void 0}if(e)return!0}return!1},I:(a,b,c,d)=>mb(a,b,c,d,12,"blur"),Z:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},J:(a,b,c,d)=>mb(a,b,c,d,13,"focus"),S:(a,b,c,d)=>nb(a,b,c,d,2,"keydown"),Q:(a,b,c,d)=>nb(a,b,c,d,1,"keypress"),
R:(a,b,c,d)=>nb(a,b,c,d,3,"keyup"),Ua:(a,b,c)=>{a=L(a);cb(a,b,c)},Y:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),V:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),U:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),W:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),X:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),L:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.oc||document.body.Mc||document.body.Lc))return-1;a=K(a);if(!a)return-4;pb(a,b,c,d,"mozpointerlockchange");pb(a,b,c,d,"webkitpointerlockchange");pb(a,
b,c,d,"mspointerlockchange");return pb(a,b,c,d,"pointerlockchange")},K:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.oc||document.body.Mc||document.body.Lc))return-1;a=K(a);if(!a)return-4;qb(a,b,c,d,"mozpointerlockerror");qb(a,b,c,d,"webkitpointerlockerror");qb(a,b,c,d,"mspointerlockerror");return qb(a,b,c,d,"pointerlockerror")},$:(a,b,c,d)=>rb(a,b,c,d),M:(a,b,c,d)=>sb(a,b,c,d,25,"touchcancel"),N:(a,b,c,d)=>sb(a,b,c,d,23,"touchend"),O:(a,b,c,d)=>sb(a,b,c,d,24,"touchmove"),
P:(a,b,c,d)=>sb(a,b,c,d,22,"touchstart"),H:(a,b,c,d)=>{Ob(a,b,c,d,31,"webglcontextlost");return 0},G:(a,b,c,d)=>{Ob(a,b,c,d,32,"webglcontextrestored");return 0},T:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?Pb(a,b,c,d):-1:-4,Sa:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Qb[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Oc:u[c+4],wd:u[c+5],Jc:r[b+24],ad:r[b+25],yd:u[c+7],Cd:r[b+
32]};a=K(a);return!a||b.ad?0:Mb(a,b)},Qa:(a,b)=>{a=Fb[a];b=b?J(b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&tb(Q);"OES_vertex_array_object"==b&&ub(Q);"WEBGL_draw_buffers"==b&&vb(Q);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&wb(Q);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&xb(Q);"WEBGL_multi_draw"==b&&(Q.ed=Q.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(Q.cd=Q.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&
(Q.bd=Q.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(Q.gd=Q.getExtension("WEBGL_polygon_mode"));return!!a.vc.getExtension(b)},Ra:a=>{V=Fb[a];g.md=Q=V?.vc;return!a||Q?0:-5},j:a=>Q.activeTexture(a),t:(a,b)=>{Q.attachShader(R[a],S[b])},b:(a,b)=>{35051==a?Q.Hc=b:35052==a&&(Q.mc=b);Q.bindBuffer(a,Ab[b])},a:(a,b,c)=>{Q.bindBufferBase(a,b,Ab[c])},m:(a,b)=>{Q.bindFramebuffer(a,Bb[b])},wa:(a,b)=>{Q.bindRenderbuffer(a,Cb[b])},i:(a,b)=>{Q.bindSampler(a,T[b])},c:(a,b)=>{Q.bindTexture(a,Db[b])},
F:a=>{Q.bindVertexArray(Eb[a])},B:(a,b,c,d)=>Q.blendColor(a,b,c,d),C:(a,b)=>Q.blendEquationSeparate(a,b),D:(a,b,c,d)=>Q.blendFuncSeparate(a,b,c,d),db:(a,b,c,d,e,k,f,l,n,p)=>Q.blitFramebuffer(a,b,c,d,e,k,f,l,n,p),za:(a,b,c,d)=>{2<=V.version?c&&b?Q.bufferData(a,t,d,c,b):Q.bufferData(a,b,d):Q.bufferData(a,c?t.subarray(c,c+b):b,d)},ya:(a,b,c,d)=>{2<=V.version?c&&Q.bufferSubData(a,b,t,d,c):Q.bufferSubData(a,b,t.subarray(d,d+c))},yb:(a,b,c,d)=>Q.clearBufferfi(a,b,c,d),fa:(a,b,c)=>{Q.clearBufferfv(a,b,w,
c>>2)},xb:(a,b,c)=>{Q.clearBufferiv(a,b,u,c>>2)},k:(a,b,c,d)=>{Q.colorMask(!!a,!!b,!!c,!!d)},Eb:a=>{Q.compileShader(S[a])},pa:(a,b,c,d,e,k,f,l)=>{2<=V.version?Q.mc||!f?Q.compressedTexImage2D(a,b,c,d,e,k,f,l):Q.compressedTexImage2D(a,b,c,d,e,k,t,l,f):Q.compressedTexImage2D(a,b,c,d,e,k,t.subarray(l,l+f))},na:(a,b,c,d,e,k,f,l,n)=>{Q.mc?Q.compressedTexImage3D(a,b,c,d,e,k,f,l,n):Q.compressedTexImage3D(a,b,c,d,e,k,f,t,n,l)},ka:()=>{var a=Jb(R),b=Q.createProgram();b.name=a;b.tc=b.rc=b.sc=0;b.Ec=1;R[a]=b;
return a},Gb:a=>{var b=Jb(S);S[b]=Q.createShader(a);return b},y:a=>Q.cullFace(a),Ea:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Ab[d];e&&(Q.deleteBuffer(e),e.name=0,Ab[d]=null,d==Q.Hc&&(Q.Hc=0),d==Q.mc&&(Q.mc=0))}},h:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=Bb[d];e&&(Q.deleteFramebuffer(e),e.name=0,Bb[d]=null)}},v:a=>{if(a){var b=R[a];b?(Q.deleteProgram(b),b.name=0,R[a]=null):U||=1281}},w:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Cb[d];e&&(Q.deleteRenderbuffer(e),e.name=0,Cb[d]=
null)}},Da:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=T[d];e&&(Q.deleteSampler(e),e.name=0,T[d]=null)}},s:a=>{if(a){var b=S[a];b?(Q.deleteShader(b),S[a]=null):U||=1281}},x:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Db[d];e&&(Q.deleteTexture(e),e.name=0,Db[d]=null)}},Ca:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];Q.deleteVertexArray(Eb[d]);Eb[d]=null}},q:a=>Q.depthFunc(a),p:a=>{Q.depthMask(!!a)},e:a=>Q.disable(a),E:a=>{Q.disableVertexAttribArray(a)},fb:(a,b,c)=>{Q.drawArrays(a,b,c)},
gb:(a,b,c,d)=>{Q.drawArraysInstanced(a,b,c,d)},hb:(a,b,c,d)=>{Q.drawElements(a,b,c,d)},ib:(a,b,c,d,e)=>{Q.drawElementsInstanced(a,b,c,d,e)},g:a=>Q.enable(a),tb:a=>{Q.enableVertexAttribArray(a)},z:a=>Q.frontFace(a),Aa:(a,b)=>{Kb(a,b,"createBuffer",Ab)},xa:(a,b)=>{Kb(a,b,"createRenderbuffer",Cb)},la:(a,b)=>{Kb(a,b,"createSampler",T)},ua:(a,b)=>{Kb(a,b,"createTexture",Db)},La:(a,b)=>{Kb(a,b,"createVertexArray",Eb)},Bb:(a,b)=>Q.getAttribLocation(R[a],b?J(b):""),d:(a,b)=>Sb(a,b),Ib:(a,b,c,d)=>{a=Q.getProgramInfoLog(R[a]);
null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},ia:(a,b,c)=>{if(c)if(a>=zb)U||=1281;else if(a=R[a],35716==b)a=Q.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.tc){var d=Q.getProgramParameter(a,35718);for(b=0;b<d;++b)a.tc=Math.max(a.tc,Q.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.tc}else if(35722==b){if(!a.rc)for(d=Q.getProgramParameter(a,35721),b=0;b<d;++b)a.rc=Math.max(a.rc,Q.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.rc}else if(35381==
b){if(!a.sc)for(d=Q.getProgramParameter(a,35382),b=0;b<d;++b)a.sc=Math.max(a.sc,Q.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.sc}else u[c>>2]=Q.getProgramParameter(a,b);else U||=1281},Db:(a,b,c,d)=>{a=Q.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},ga:(a,b,c)=>{c?35716==b?(a=Q.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(S[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=Q.getShaderParameter(S[a],
b):U||=1281},Ia:(a,b)=>{if(2>V.version)return U||=1282,0;var c=Gb[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Rb().map(Ub),c=Gb[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},ha:(a,b)=>{b=b?J(b):"";if(a=R[a]){var c=a,d=c.qc,e=c.Yc,k;if(!d){c.qc=d={};c.Xc={};var f=Q.getProgramParameter(c,35718);for(k=0;k<f;++k){var l=Q.getActiveUniform(c,k);var n=l.name;l=l.size;var p=Vb(n);p=0<p?n.slice(0,p):n;var y=c.Ec;c.Ec+=l;e[p]=[l,y];for(n=0;n<l;++n)d[y]=
n,c.Xc[y++]=p}}c=a.qc;d=0;e=b;k=Vb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.Yc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||Q.getUniformLocation(a,b)))return d}else U||=1281;return-1},cb:(a,b,c)=>{for(var d=Wb[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];Q.invalidateFramebuffer(a,d)},ja:a=>{a=R[a];Q.linkProgram(a);a.qc=0;a.Yc={}},Ja:(a,b)=>{3317==a?Hb=b:3314==a&&(Ib=b);Q.pixelStorei(a,b)},A:(a,b)=>Q.polygonOffset(a,b),eb:a=>Q.readBuffer(a),va:(a,b,c,d,e)=>Q.renderbufferStorageMultisample(a,b,c,d,e),u:(a,
b,c)=>{Q.samplerParameterf(T[a],b,c)},f:(a,b,c)=>{Q.samplerParameteri(T[a],b,c)},zb:(a,b,c,d)=>Q.scissor(a,b,c,d),Fb:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var f=(f=v[c+4*k>>2])?J(f,d?v[d+4*k>>2]:void 0):"";e+=f}Q.shaderSource(S[a],e)},Ha:(a,b,c)=>Q.stencilFunc(a,b,c),ea:(a,b,c,d)=>Q.stencilFuncSeparate(a,b,c,d),o:a=>Q.stencilMask(a),Ga:(a,b,c)=>Q.stencilOp(a,b,c),da:(a,b,c,d)=>Q.stencilOpSeparate(a,b,c,d),oa:(a,b,c,d,e,k,f,l,n)=>{if(2<=V.version){if(Q.mc){Q.texImage2D(a,b,c,d,e,k,f,l,n);return}if(n){var p=
Xb(l);n>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);Q.texImage2D(a,b,c,d,e,k,f,l,p,n);return}}p=n?Yb(l,f,d,e,n):null;Q.texImage2D(a,b,c,d,e,k,f,l,p)},ma:(a,b,c,d,e,k,f,l,n,p)=>{if(Q.mc)Q.texImage3D(a,b,c,d,e,k,f,l,n,p);else if(p){var y=Xb(n);Q.texImage3D(a,b,c,d,e,k,f,l,n,y,p>>>31-Math.clz32(y.BYTES_PER_ELEMENT))}else Q.texImage3D(a,b,c,d,e,k,f,l,n,null)},ta:(a,b,c)=>Q.texParameteri(a,b,c),sa:(a,b,c,d,e)=>Q.texStorage2D(a,b,c,d,e),ra:(a,b,c,d,e,k)=>Q.texStorage3D(a,b,c,d,e,k),bb:(a,b,c,d,e,k,f,l,n)=>{if(2<=
V.version){if(Q.mc){Q.texSubImage2D(a,b,c,d,e,k,f,l,n);return}if(n){var p=Xb(l);Q.texSubImage2D(a,b,c,d,e,k,f,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}n=n?Yb(l,f,e,k,n):null;Q.texSubImage2D(a,b,c,d,e,k,f,l,n)},ab:(a,b,c,d,e,k,f,l,n,p,y)=>{if(Q.mc)Q.texSubImage3D(a,b,c,d,e,k,f,l,n,p,y);else if(y){var P=Xb(p);Q.texSubImage3D(a,b,c,d,e,k,f,l,n,p,P,y>>>31-Math.clz32(P.BYTES_PER_ELEMENT))}else Q.texSubImage3D(a,b,c,d,e,k,f,l,n,p,null)},sb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform1fv(W(a),w,c>>
2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);Q.uniform1fv(W(a),d)}},Hb:(a,b)=>{Q.uniform1i(W(a),b)},ob:(a,b,c)=>{if(2<=V.version)b&&Q.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=Zb[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);Q.uniform1iv(W(a),d)}},rb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform2fv(W(a),w,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,
c+8*b>>2);Q.uniform2fv(W(a),d)}},nb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Zb[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);Q.uniform2iv(W(a),d)}},qb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform3fv(W(a),w,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);Q.uniform3fv(W(a),d)}},mb:(a,b,c)=>{if(2<=V.version)b&&
Q.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Zb[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);Q.uniform3iv(W(a),d)}},pb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform4fv(W(a),w,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=w;c>>=2;b*=4;for(var k=0;k<b;k+=4){var f=c+k;d[k]=e[f];d[k+1]=e[f+1];d[k+2]=e[f+2];d[k+3]=e[f+3]}}else d=w.subarray(c>>2,c+16*b>>2);Q.uniform4fv(W(a),d)}},lb:(a,b,c)=>{if(2<=V.version)b&&Q.uniform4iv(W(a),u,c>>
2,4*b);else{if(72>=b){b*=4;for(var d=Zb[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);Q.uniform4iv(W(a),d)}},jb:(a,b,c,d)=>{if(2<=V.version)b&&Q.uniformMatrix4fv(W(a),!!c,w,d>>2,16*b);else{if(18>=b){var e=X[16*b],k=w;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=k[l];e[f+1]=k[l+1];e[f+2]=k[l+2];e[f+3]=k[l+3];e[f+4]=k[l+4];e[f+5]=k[l+5];e[f+6]=k[l+6];e[f+7]=k[l+7];e[f+8]=k[l+8];e[f+9]=k[l+9];e[f+10]=k[l+
10];e[f+11]=k[l+11];e[f+12]=k[l+12];e[f+13]=k[l+13];e[f+14]=k[l+14];e[f+15]=k[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);Q.uniformMatrix4fv(W(a),!!c,e)}},l:a=>{a=R[a];Q.useProgram(a);Q.$c=a},ub:(a,b)=>{Q.vertexAttribDivisor(a,b)},wb:(a,b,c,d,e,k)=>{Q.vertexAttribPointer(a,b,c,!!d,e,k)},Ab:(a,b,c,d)=>Q.viewport(a,b,c,d),Wa:Ka,Lb:function(){g.Rc=a=>{0!=hc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Rc)},Va:function(){g.Wc=a=>{const b=a.clipboardData.getData("text");
dc(()=>{const c=ac(b);ic(c)})};window.addEventListener("paste",g.Wc)},Oa:function(a){g.Dd=[];a=a?J(a):"";a=document.getElementById(a);g.Sc=b=>{b.stopPropagation();b.preventDefault()};g.Tc=b=>{b.stopPropagation();b.preventDefault()};g.Uc=b=>{b.stopPropagation();b.preventDefault()};g.Vc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Ed=c;jc(c.length);for(let e=0;e<c.length;e++)dc(()=>{const k=ac(c[e].name);kc(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=
4);b.metaKey&&(d|=8);lc(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.Sc,!1);a.addEventListener("dragleave",g.Tc,!1);a.addEventListener("dragover",g.Uc,!1);a.addEventListener("drop",g.Vc,!1)},Ba:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Fa:function(a){a=a?J(a):"";g.pc=document.getElementById(a);g.pc||console.log("sokol_app.h: invalid target:"+a);g.pc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+
a)},Kb:function(){window.removeEventListener("beforeunload",g.Rc)},Pa:function(){window.removeEventListener("paste",g.Wc)},Ka:function(a){a=a?J(a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.Sc);a.removeEventListener("dragleave",g.Tc);a.removeEventListener("dragover",g.Uc);a.removeEventListener("drop",g.Vc)},n:function(){g.pc&&g.pc.requestPointerLock&&g.pc.requestPointerLock()},qa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),
k=e.createImageData(a,b);k.data.set(t.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},kb:function(){return g.lc?g.lc.bufferSize:0},Jb:function(a,b,c){g.ec=null;g.lc=null;"undefined"!==typeof AudioContext?g.ec=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.ec=null,console.log("sokol_audio.h: no WebAudio support"));return g.ec?(console.log("sokol_audio.h: sample rate ",
g.ec.sampleRate),g.lc=g.ec.createScriptProcessor(c,0,b),g.lc.onaudioprocess=d=>{const e=d.outputBuffer.length,k=mc(e);if(k){const f=d.outputBuffer.numberOfChannels;for(let l=0;l<f;l++){const n=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)n[p]=w[(k>>2)+(f*p+l)]}}},g.lc.connect(g.ec.destination),a=()=>{g.ec&&"suspended"===g.ec.state&&g.ec.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),
1):0},vb:function(){return g.ec?g.ec.sampleRate:0},Cb:function(){const a=g.ec;null!==a&&(g.lc&&g.lc.disconnect(),a.close(),g.ec=null,g.lc=null)},r:function(a,b,c,d,e,k){b=b?J(b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const l=0<d;l&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!l){const n=new Uint8Array(f.response),p=n.length;p<=k?(t.set(n,e),nc(a,d,p)):oc(a)}else pc(a,
f.status)};f.send()},ca:function(a,b){b=b?J(b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");qc(a,d)}else pc(a,c.status)};c.send()},ba:function(a,b){b=b?J(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;na=Z.Mb;ra();lb=Z.$b;ta.unshift(Z.Nb);z--;
g.monitorRunDependencies?.(z);0==z&&(null!==xa&&(clearInterval(xa),xa=null),A&&(c=A,A=null,c()));return Z}var b={a:rc};z++;g.monitorRunDependencies?.(z);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return m(`Module.instantiateWasm callback failed with error: ${c}`),!1}Aa??=za("plmpeg-sapp.wasm")?"plmpeg-sapp.wasm":g.locateFile?g.locateFile("plmpeg-sapp.wasm",h):h+"plmpeg-sapp.wasm";Ea(b,function(c){a(c.instance)});return{}}(),N=a=>(N=Z.Ob)(a),ic=g.__sapp_emsc_onpaste=a=>(ic=g.__sapp_emsc_onpaste=
Z.Pb)(a),hc=g.__sapp_html5_get_ask_leave_site=()=>(hc=g.__sapp_html5_get_ask_leave_site=Z.Qb)(),jc=g.__sapp_emsc_begin_drop=a=>(jc=g.__sapp_emsc_begin_drop=Z.Rb)(a),kc=g.__sapp_emsc_drop=(a,b)=>(kc=g.__sapp_emsc_drop=Z.Sb)(a,b),lc=g.__sapp_emsc_end_drop=(a,b,c)=>(lc=g.__sapp_emsc_end_drop=Z.Tb)(a,b,c);g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,k,f,l)=>(g.__sapp_emsc_invoke_fetch_cb=Z.Ub)(a,b,c,d,e,k,f,l);
var sc=g._main=(a,b)=>(sc=g._main=Z.Vb)(a,b),mc=g.__saudio_emsc_pull=a=>(mc=g.__saudio_emsc_pull=Z.Wb)(a),qc=g.__sfetch_emsc_head_response=(a,b)=>(qc=g.__sfetch_emsc_head_response=Z.Xb)(a,b),nc=g.__sfetch_emsc_get_response=(a,b,c)=>(nc=g.__sfetch_emsc_get_response=Z.Yb)(a,b,c),pc=g.__sfetch_emsc_failed_http_status=(a,b)=>(pc=g.__sfetch_emsc_failed_http_status=Z.Zb)(a,b),oc=g.__sfetch_emsc_failed_buffer_too_small=a=>(oc=g.__sfetch_emsc_failed_buffer_too_small=Z._b)(a),gc=(a,b)=>(gc=Z.ac)(a,b),cc=a=>
(cc=Z.bc)(a),$b=a=>($b=Z.cc)(a),bc=()=>(bc=Z.dc)(),tc;A=function uc(){tc||vc();tc||(A=uc)};function wc(a=[]){var b=sc;a.unshift(fa);var c=a.length,d=$b(4*(c+1)),e=d;a.forEach(f=>{v[e>>2]=ac(f);e+=4});v[e>>2]=0;try{var k=b(c,d);La(k)}catch(f){Ja(f)}}
function vc(){var a=ea;function b(){if(!tc&&(tc=!0,g.calledRun=!0,!q)){Ga(ta);Ga(ua);g.onRuntimeInitialized?.();xc&&wc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();va.unshift(c)}Ga(va)}}if(!(0<z)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)wa();Ga(sa);0<z||(g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b())}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var xc=!0;g.noInitialRun&&(xc=!1);vc();
