var g;g||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer",da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;typeof __filename!="undefined"?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.length>1&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);typeof module!="undefined"&&(module.exports=g);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{e.status==200||e.status==0&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var k=console.error.bind(console),m=!1,ma,la=a=>a.startsWith("file://");
function na(){if(!p?.buffer?.resizable){var a=oa.buffer;p=new Int8Array(a);pa=new Int16Array(a);r=new Uint8Array(a);qa=new Uint16Array(a);u=new Int32Array(a);v=new Uint32Array(a);w=new Float32Array(a);x=new Float64Array(a)}}function ra(){var a=g.preRun;a&&(typeof a=="function"&&(a=[a]),sa.push(...a));for(a=sa;a.length>0;)a.shift()(g)}function ta(){var a=g.postRun;a&&(typeof a=="function"&&(a=[a]),ua.push(...a));for(a=ua;a.length>0;)a.shift()(g)}
function va(a){g.onAbort?.(a);a=`Aborted(${a})`;k(a);m=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var wa;async function xa(a){try{var b=await ja(a);return new Uint8Array(b)}catch{}if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function ya(a,b){try{var c=await xa(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),va(d)}}
async function za(a){var b=wa;if(!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ya(b,a)}class Aa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var p,ua=[],sa=[],Ba=!0,Ca=0,y={},Da=a=>{a instanceof Aa||a=="unwind"||fa(1,a)},Ea=a=>{ma=a;Ba||Ca>0||(g.onExit?.(a),m=!0);fa(a,new Aa(a))},Fa=()=>{if(!(Ba||Ca>0))try{var a=ma;ma=a;Ea(a)}catch(b){Da(b)}},Ga=a=>{if(!m)try{a()}catch(b){Da(b)}finally{Fa()}},La=(a,b)=>{Ha=a;Ia=b;if(z)if(a==0)A=function(){setTimeout(B,Math.max(0,Ja+b-performance.now())|0)};else if(a==1)A=function(){Ka(B)};else{if(!D)if(globalThis.scheduler)D=scheduler.postTask.bind(scheduler);else if(globalThis.setImmediate)D=setImmediate;
else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);D=d=>{c.push(d);ba?postMessage("setimmediate"):postMessage("setimmediate","*")}}A=function(){D(B)}}},Ua=(a,b,c,d,e)=>{function h(){return f<Ma?(Fa(),!1):!0}z=a;Na=d;var f=Ma;B=function(){if(!m)if(Oa.length>0){var l=Oa.shift();l.Cd(l.qd);if(Pa){var n=Pa,q=n%1==0?n-1:Math.floor(n);Pa=l.td?q:(8*n+(q+.5))/9}g.setStatus&&(l=g.statusMessage||"Please wait...",n=Pa??0,q=Qa.zd??0,n?n<q?g.setStatus("{message} ({expected - remaining}/{expected})"):
g.setStatus(l):g.setStatus(""));h()&&setTimeout(B,0)}else if(h())if(Ra=Ra+1|0,Ha==1&&Ia>1&&Ra%Ia!=0)A();else{Ha==0&&(Ja=performance.now());a:if(!m){for(l of Sa)if(l()===!1)break a;Ga(a);for(n of Ta)n()}h()&&A()}};e||(b>0?La(0,1E3/b):La(1,1),A());if(c)throw"unwind";},z=null,A=null,Ma=0,Na=0,Ha=0,Ia=0,Ra=0,Oa=[],Sa=[],Ta=[];function Va(){A&&(A=null,Ma++)}var E=0;
function Ka(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(E)for(;b+2>=E;)E+=1E3/60;else E=b+1E3/60;setTimeout(a,Math.max(E-b,0))}}
var Qa={},Ja,B,D,Pa,Wa=globalThis.TextDecoder&&new TextDecoder,F=(a=0,b)=>{var c=r;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(d-a>16&&c.buffer&&Wa)return Wa.decode(c.subarray(a,d));for(b="";a<d;){var e=c[a++];if(e&128){var h=c[a++]&63;if((e&224)==192)b+=String.fromCharCode((e&31)<<6|h);else{var f=c[a++]&63;e=(e&240)==224?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|c[a++]&63;e<65536?b+=String.fromCharCode(e):(e-=65536,b+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else b+=String.fromCharCode(e)}return b},
r,Xa=[0,globalThis.document??0,globalThis.window??0],G=a=>{a=a>2?a?F(a):"":a;return Xa[a]||globalThis.document?.querySelector(a)},Ya=a=>Xa.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},x,Za=[],H=a=>{var b=Za[a];b||(Za[a]=b=$a.get(a));return b};function ab(a){var b=I.oc[a];b.target.removeEventListener(b.nc,b.Vc,b.sc);I.oc.splice(a,1)}function bb(){if(navigator.userActivation?navigator.userActivation.isActive:I.Ic&&I.kd.Fc){var a=I.xc;I.xc=[];for(var b of a)b.Lc(...b.Rc)}}
function J(a){if(!a.target)return-4;if(a.qc)a.Vc=function(c){++I.Ic;I.kd=a;bb();a.uc(c);bb();--I.Ic},a.target.addEventListener(a.nc,a.Vc,a.sc),I.oc.push(a);else for(var b=0;b<I.oc.length;++b)I.oc[b].target==a.target&&I.oc[b].nc==a.nc&&ab(b--);return 0}function cb(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var I={rd:0,Dd:0,Jc:0,Dc:0,Pc:0,Nc:0,Gc:0,xd:0,Hd:0,wd:0,Hc:0,Kc:0,Rd:0,Mc:0,Jd(){for(;I.oc.length;)ab(I.oc.length-1);I.xc=[]},Ic:0,xc:[],vd(a,b,c){function d(h,f){if(h.length!=f.length)return!1;for(var l=0;l<h.length;l++)if(h[l]!=f[l])return!1;return!0}for(var e of I.xc)if(e.Lc==a&&d(e.Rc,c))return;I.xc.push({Lc:a,$c:b,Rc:c});I.xc.sort((h,f)=>h.$c-f.$c)},Ld(a){I.xc=I.xc.filter(b=>b.Lc!=a)},oc:[],Kd:(a,b)=>{for(var c=0;c<I.oc.length;++c)I.oc[c].target!=a||b&&b!=I.oc[c].nc||ab(c--)},Md(a){var b=!1;
for(let c=0;c<I.oc.length;++c){let d=I.oc[c];d.target===a.target&&d.rc===a.rc&&d.qc===a.qc&&d.tc===a.tc&&(ab(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled??document.webkitFullscreenEnabled}},K=(a,b,c)=>{var d=r;if(!(c>0))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.codePointAt(h);if(f<=127){if(b>=c)break;d[b++]=f}else if(f<=2047){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(f<=65535){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=
128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;h++}}d[b]=0;return b-e},db=(a,b,c,d,e,h)=>{I.Gc||(I.Gc=L(256));a={target:G(a),nc:h,rc:e,tc:b,qc:d,uc:f=>{var l=f.target.id??"",n=I.Gc;K(cb(f.target),n+0,128);K(l,n+128,128);H(d)(e,n,b)&&f.preventDefault()},sc:c};return J(a)},u,eb=(a,b,c,d,e)=>{I.Hc||(I.Hc=L(276));return J({target:a,nc:e,rc:19,tc:b,qc:d,uc:h=>{var f=I.Hc,l=document.fullscreenElement??document.webkitFullscreenElement,n=!!l;p[f]=n;p[f+
1]=I.fullscreenEnabled();var q=n?l:I.od,t=q?.id??"";K(cb(q),f+2,128);K(t,f+130,128);u[f+260>>2]=q?.clientWidth??0;u[f+264>>2]=q?.clientHeight??0;u[f+268>>2]=screen.width;u[f+272>>2]=screen.height;n&&(I.od=l);H(d)(19,f,b)&&h.preventDefault()},sc:c})},fb=(a,b,c,d,e,h)=>{I.Jc||(I.Jc=L(160));a={target:G(a),nc:h,rc:e,tc:b,qc:d,uc:f=>{var l=I.Jc;x[l>>3]=f.timeStamp;var n=l>>2;u[n+2]=f.location;p[l+12]=f.ctrlKey;p[l+13]=f.shiftKey;p[l+14]=f.altKey;p[l+15]=f.metaKey;p[l+16]=f.repeat;u[n+5]=f.charCode;u[n+
6]=f.keyCode;u[n+7]=f.which;K(f.key??"",l+32,32);K(f.code??"",l+64,32);K(f.char??"",l+96,32);K(f.locale??"",l+128,32);H(d)(e,l,b)&&f.preventDefault()},sc:c};return J(a)},pa,gb=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;p[a+24]=b.ctrlKey;p[a+25]=b.shiftKey;p[a+26]=b.altKey;p[a+27]=b.metaKey;pa[d*2+14]=b.button;pa[d*2+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=Ya(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},
hb=(a,b,c,d,e,h)=>{I.Dc||(I.Dc=L(64));a=G(a);return J({target:a,Fc:h!="mousemove"&&h!="mouseenter"&&h!="mouseleave",nc:h,rc:e,tc:b,qc:d,uc:f=>{gb(I.Dc,f,a);H(d)(e,I.Dc,b)&&f.preventDefault()},sc:c})},ib=(a,b,c,d)=>{I.Kc||(I.Kc=L(257));return J({target:a,nc:"pointerlockchange",rc:20,tc:b,qc:d,uc:e=>{var h=I.Kc,f=document.pointerLockElement;p[h]=!!f;var l=f?.id??"";K(cb(f),h+1,128);K(l,h+129,128);H(d)(20,h,b)&&e.preventDefault()},sc:c})},jb=(a,b,c,d)=>J({target:a,nc:"pointerlockerror",rc:38,tc:b,qc:d,
uc:e=>{H(d)(38,0,b)&&e.preventDefault()},sc:c}),kb=(a,b,c,d)=>{I.Nc||(I.Nc=L(36));a=G(a);return J({target:a,nc:"resize",rc:10,tc:b,qc:d,uc:e=>{if(e.target==a){var h=document.body;if(h){var f=I.Nc;u[f>>2]=0;u[f+4>>2]=h.clientWidth;u[f+8>>2]=h.clientHeight;u[f+12>>2]=innerWidth;u[f+16>>2]=innerHeight;u[f+20>>2]=outerWidth;u[f+24>>2]=outerHeight;u[f+28>>2]=pageXOffset|0;u[f+32>>2]=pageYOffset|0;H(d)(10,f,b)&&e.preventDefault()}}},sc:c})},lb=(a,b,c,d,e,h)=>{I.Mc||(I.Mc=L(1552));a=G(a);return J({target:a,
Fc:h=="touchstart"||h=="touchend",nc:h,rc:e,tc:b,qc:d,uc:f=>{var l={},n=f.touches;for(var q of n)q.Wc=q.Zc=0,l[q.identifier]=q;for(var t of f.changedTouches)t.Wc=1,l[t.identifier]=t;for(var M of f.targetTouches)l[M.identifier].Zc=1;n=I.Mc;x[n>>3]=f.timeStamp;p[n+12]=f.ctrlKey;p[n+13]=f.shiftKey;p[n+14]=f.altKey;p[n+15]=f.metaKey;q=n+16;t=Ya(a);M=0;for(let C of Object.values(l))if(l=q>>2,u[l]=C.identifier,u[l+1]=C.screenX,u[l+2]=C.screenY,u[l+3]=C.clientX,u[l+4]=C.clientY,u[l+5]=C.pageX,u[l+6]=C.pageY,
p[q+28]=C.Wc,p[q+29]=C.Zc,u[l+8]=C.clientX-(t.left|0),u[l+9]=C.clientY-(t.top|0),q+=48,++M>31)break;u[n+8>>2]=M;H(d)(e,n,b)&&f.preventDefault()},sc:c})},N,mb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},nb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=
()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},ob=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},pb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},v,qb=1,O=[],P=[],rb=[],sb=[],Q=[],R=[],tb=[],ub=[],S=[],vb={},wb=4,xb=0,yb=a=>{for(var b=qb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=N[c](),f=h&&yb(d);h?(h.name=f,d[f]=h):T||=1282;u[b+e*4>>2]=f}},Ab=(a,b)=>{a.Yc||(a.Yc=a.getContext,a.getContext=function(d,e){e=a.Yc(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=b.Xc>1?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?zb(c,b):0},zb=(a,b)=>{var c=yb(ub),d={handle:c,attributes:b,version:b.Xc,Qc:a};a.canvas&&(a.canvas.pd=d);ub[c]=d;if(typeof b.Uc=="undefined"||b.Uc)if((a=d)||(a=V),!a.nd){a.nd=!0;b=a.Qc;b.Gd=b.getExtension("WEBGL_multi_draw");b.Bd=b.getExtension("EXT_polygon_offset_clamp");b.Ad=b.getExtension("EXT_clip_control");b.Sd=b.getExtension("WEBGL_polygon_mode");mb(b);nb(b);ob(b);b.yd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Ed=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
a.version>=2&&(b.Tc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(a.version<2||!b.Tc)b.Tc=b.getExtension("EXT_disjoint_timer_query");for(var e of pb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},T,V,Bb=(a,b,c,d,e,h)=>{a={target:G(a),nc:h,rc:e,tc:b,qc:d,uc:f=>{H(d)(e,0,b)&&f.preventDefault()},sc:c};J(a)},Cb=(a,b,c,d)=>{I.Pc||(I.Pc=L(96));return J({target:a,Fc:!0,nc:"wheel",rc:9,tc:b,qc:d,uc:e=>{var h=I.Pc;gb(h,e,a);x[h+64>>3]=e.deltaX;x[h+72>>3]=e.deltaY;x[h+
80>>3]=e.deltaZ;u[h+88>>2]=e.deltaMode;H(d)(9,h,b)&&e.preventDefault()},sc:c})},Db=["default","low-power","high-performance"],w,Eb=[],Fb=()=>{var a=pb(N);return a=a.concat(a.map(b=>"GL_"+b))},Gb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=N.getParameter(34467);c=d?d.length:0;break;case 33309:if(V.version<2){T||=1282;return}c=Fb().length;break;case 33307:case 33308:if(V.version<2){T||=1280;return}c=a==33307?3:0}if(c===
void 0)switch(d=N.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(d===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof
Array){for(a=0;a<d.length;++a)u[b+a*4>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;k(`GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;k(`GL_INVALID_ENUM in glGet0v: Native code calling glGet0v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else T||=1281},Hb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},Ib=a=>{var b=
Hb(a)+1,c=L(b);c&&K(a,c,b);return c},Jb=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),qa,Kb=a=>{a-=5120;return a==0?p:a==1?r:a==2?pa:a==4?u:a==6?w:a==5||a==28922||a==28520||a==30779||a==30782?v:qa},W=a=>{var b=N.ld;if(b){var c=b.zc[a];typeof c=="number"&&(b.zc[a]=c=N.getUniformLocation(b,b.hd[a]+(c>0?`[${c}]`:"")));return c}T||=1282},X=[],Lb=[],Nb=a=>{var b=Hb(a)+1,c=Mb(b);K(a,c,b);return c},Qb=a=>{var b=Ob();a();Pb(b)};g.requestAnimationFrame=Ka;g.pauseMainLoop=Va;
g.resumeMainLoop=function(){Ma++;var a=Ha,b=Ia,c=z;z=null;Ua(c,0,!1,Na,!0);La(a,b);A()};for(let a=0;a<32;++a)Eb.push(Array(a));for(var Rb=new Float32Array(288),Y=0;Y<=288;++Y)X[Y]=Rb.subarray(0,Y);var Sb=new Int32Array(288);for(Y=0;Y<=288;++Y)Lb[Y]=Sb.subarray(0,Y);g.noExitRuntime&&(Ba=g.noExitRuntime);g.printErr&&(k=g.printErr);g.arguments&&(da=g.arguments);g.thisProgram&&(ea=g.thisProgram);var Z=g.preInit;if(Z)for(typeof Z=="function"&&(g.preInit=Z=[Z]);Z.length>0;)Z.shift()();
var L,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,Pb,Mb,Ob,oa,$a,fc={ab:()=>va(""),$a:()=>{Ba=!1;Ca=0},Xa:(a,b)=>{y[a]&&(clearTimeout(y[a].id),delete y[a]);if(!b)return 0;var c=setTimeout(()=>{delete y[a];Ga(()=>ec(a,performance.now()))},b);y[a]={id:c,Qd:b};return 0},Oa:()=>{Va();z=null},ja:()=>globalThis.devicePixelRatio??1,la:(a,b,c)=>{a=G(a);if(!a)return-4;a=Ya(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},Pa:()=>performance.now(),Ua:(a,b)=>{function c(d){H(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
Ya:a=>{var b=r.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);na();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},T:(a,b,c,d)=>db(a,b,c,d,12,"blur"),ia:(a,b,c)=>{a=G(a);if(!a)return-4;a.width=b;a.height=c;return 0},U:(a,b,c,d)=>db(a,b,c,d,13,"focus"),S:(a,b,c,d)=>{if(!I.fullscreenEnabled())return-1;a=G(a);if(!a)return-4;
eb(a,b,c,d,"webkitfullscreenchange");return eb(a,b,c,d,"fullscreenchange")},ba:(a,b,c,d)=>fb(a,b,c,d,2,"keydown"),$:(a,b,c,d)=>fb(a,b,c,d,1,"keypress"),aa:(a,b,c,d)=>fb(a,b,c,d,3,"keyup"),Va:(a,b,c)=>{a=H(a);Ua(a,b,c)},ha:(a,b,c,d)=>hb(a,b,c,d,5,"mousedown"),ea:(a,b,c,d)=>hb(a,b,c,d,33,"mouseenter"),da:(a,b,c,d)=>hb(a,b,c,d,34,"mouseleave"),fa:(a,b,c,d)=>hb(a,b,c,d,8,"mousemove"),ga:(a,b,c,d)=>hb(a,b,c,d,6,"mouseup"),W:(a,b,c,d)=>document.body?.requestPointerLock?(a=G(a))?ib(a,b,c,d):-4:-1,V:(a,b,
c,d)=>document.body?.requestPointerLock?(a=G(a))?jb(a,b,c,d):-4:-1,ka:(a,b,c,d)=>kb(a,b,c,d),X:(a,b,c,d)=>lb(a,b,c,d,25,"touchcancel"),Y:(a,b,c,d)=>lb(a,b,c,d,23,"touchend"),Z:(a,b,c,d)=>lb(a,b,c,d,24,"touchmove"),_:(a,b,c,d)=>lb(a,b,c,d,22,"touchstart"),R:(a,b,c,d)=>{Bb(a,b,c,d,31,"webglcontextlost");return 0},Q:(a,b,c,d)=>{Bb(a,b,c,d,32,"webglcontextrestored");return 0},ca:(a,b,c,d)=>(a=G(a))?typeof a.onwheel!="undefined"?Cb(a,b,c,d):-1:-4,Ta:(a,b)=>{var c=b>>2;b={alpha:!!p[b+0],depth:!!p[b+1],
stencil:!!p[b+2],antialias:!!p[b+3],premultipliedAlpha:!!p[b+4],preserveDrawingBuffer:!!p[b+5],powerPreference:Db[u[c+2]],failIfMajorPerformanceCaveat:!!p[b+12],desynchronized:!!p[b+33],Xc:u[c+4],Fd:u[c+5],Uc:p[b+24],md:p[b+25],Id:u[c+7],Nd:p[b+32]};a=G(a);return!a||b.md?0:Ab(a,b)},Sa:a=>{V=ub[a];g.ctx=N=V?.Qc;return!a||N?0:-5},o:a=>N.activeTexture(a),t:(a,b)=>{N.attachShader(P[a],R[b])},b:(a,b)=>{a==35051?N.Sc=b:a==35052&&(N.yc=b);N.bindBuffer(a,O[b])},w:(a,b,c)=>{N.bindBufferBase(a,b,O[c])},sb:(a,
b,c,d,e)=>{N.bindBufferRange(a,b,O[c],d,e)},j:(a,b)=>{N.bindFramebuffer(a,rb[b])},Fb:(a,b)=>{N.bindRenderbuffer(a,sb[b])},n:(a,b)=>{N.bindSampler(a,S[b])},c:(a,b)=>{N.bindTexture(a,Q[b])},P:a=>{N.bindVertexArray(tb[a])},K:(a,b,c,d)=>N.blendColor(a,b,c,d),L:(a,b)=>N.blendEquationSeparate(a,b),M:(a,b,c,d)=>N.blendFuncSeparate(a,b,c,d),cb:(a,b,c,d,e,h,f,l,n,q)=>N.blitFramebuffer(a,b,c,d,e,h,f,l,n,q),Ca:(a,b,c,d)=>{V.version>=2?c&&b?N.bufferData(a,r,d,c,b):N.bufferData(a,b,d):N.bufferData(a,c?r.subarray(c,
c+b):b,d)},Ba:(a,b,c,d)=>{var e=r;V.version>=2?c&&N.bufferSubData(a,b,e,d,c):N.bufferSubData(a,b,e.subarray(d,d+c))},Db:a=>N.checkFramebufferStatus(a),zb:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),qa:(a,b,c)=>{N.clearBufferfv(a,b,w,c>>2)},yb:(a,b,c)=>{N.clearBufferiv(a,b,u,c>>2)},p:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},Kb:a=>{N.compileShader(R[a])},h:(a,b,c,d,e,h,f,l,n)=>{V.version>=2?N.yc||!l?N.compressedTexSubImage2D(a,b,c,d,e,h,f,l,n):N.compressedTexSubImage2D(a,b,c,d,e,h,f,r,n,l):N.compressedTexSubImage2D(a,
b,c,d,e,h,f,r.subarray(n,n+l))},F:(a,b,c,d,e,h,f,l,n,q,t)=>{N.yc?N.compressedTexSubImage3D(a,b,c,d,e,h,f,l,n,q,t):N.compressedTexSubImage3D(a,b,c,d,e,h,f,l,n,r,t,q)},va:()=>{var a=yb(P),b=N.createProgram();b.name=a;b.Cc=b.Ac=b.Bc=0;b.Oc=1;P[a]=b;return a},Mb:a=>{var b=yb(R);R[b]=N.createShader(a);return b},H:a=>N.cullFace(a),Ha:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=O[d];e&&(N.deleteBuffer(e),e.name=0,O[d]=null,d==N.Sc&&(N.Sc=0),d==N.yc&&(N.yc=0))}},u:(a,b)=>{for(var c=0;c<a;++c){var d=
u[b+c*4>>2],e=rb[d];e&&(N.deleteFramebuffer(e),e.name=0,rb[d]=null)}},v:a=>{if(a){var b=P[a];b?(N.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},G:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=sb[d];e&&(N.deleteRenderbuffer(e),e.name=0,sb[d]=null)}},Ga:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=S[d];e&&(N.deleteSampler(e),e.name=0,S[d]=null)}},m:a=>{if(a){var b=R[a];b?(N.deleteShader(b),R[a]=null):T||=1281}},k:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=Q[d];e&&(N.deleteTexture(e),
e.name=0,Q[d]=null)}},Ea:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2];N.deleteVertexArray(tb[d]);tb[d]=null}},z:a=>N.depthFunc(a),y:a=>{N.depthMask(!!a)},d:a=>N.disable(a),N:a=>{N.disableVertexAttribArray(a)},eb:(a,b,c)=>{N.drawArrays(a,b,c)},fb:(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},ra:(a,b)=>{for(var c=Eb[a],d=0;d<a;d++)c[d]=u[b+d*4>>2];N.drawBuffers(c)},gb:(a,b,c,d)=>{N.drawElements(a,b,c,d)},hb:(a,b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},i:a=>N.enable(a),ub:a=>{N.enableVertexAttribArray(a)},
l:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,sb[d])},e:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,Q[d],e)},B:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,Q[c],d,e)},I:a=>N.frontFace(a),Da:(a,b)=>{U(a,b,"createBuffer",O)},O:(a,b)=>{U(a,b,"createFramebuffer",rb)},Gb:(a,b)=>{U(a,b,"createRenderbuffer",sb)},wa:(a,b)=>{U(a,b,"createSampler",S)},Aa:(a,b)=>{U(a,b,"createTexture",Q)},Ma:(a,b)=>{U(a,b,"createVertexArray",tb)},Ib:(a,b)=>N.getAttribLocation(P[a],b?F(b):""),a:(a,b)=>Gb(a,b),Ob:(a,b,c,d)=>{a=
N.getProgramInfoLog(P[a]);a===null&&(a="(unknown error)");b=b>0&&d?K(a,d,b):0;c&&(u[c>>2]=b)},ua:(a,b,c)=>{if(c)if(a>=qb)T||=1281;else if(a=P[a],b==35716)a=N.getProgramInfoLog(a),a===null&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(b==35719){if(!a.Cc){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Cc=Math.max(a.Cc,N.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.Cc}else if(b==35722){if(!a.Ac)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.Ac=Math.max(a.Ac,N.getActiveAttrib(a,b).name.length+
1);u[c>>2]=a.Ac}else if(b==35381){if(!a.Bc)for(d=N.getProgramParameter(a,35382),b=0;b<d;++b)a.Bc=Math.max(a.Bc,N.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Bc}else u[c>>2]=N.getProgramParameter(a,b);else T||=1281},Jb:(a,b,c,d)=>{a=N.getShaderInfoLog(R[a]);a===null&&(a="(unknown error)");b=b>0&&d?K(a,d,b):0;c&&(u[c>>2]=b)},sa:(a,b,c)=>{c?b==35716?(a=N.getShaderInfoLog(R[a]),a===null&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):b==35720?(a=N.getShaderSource(R[a]),u[c>>2]=a?a.length+1:0):u[c>>
2]=N.getShaderParameter(R[a],b):T||=1281},La:(a,b)=>{if(V.version<2)return T||=1282,0;var c=vb[a];if(c)return b<0||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Fb().map(Ib),c=vb[a]=c,b<0||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},ta:(a,b)=>{b=b?F(b):"";if(a=P[a]){var c=a,d=c.zc,e=c.jd,h;if(!d){c.zc=d={};c.hd={};var f=N.getProgramParameter(c,35718);for(h=0;h<f;++h){var l=N.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Jb(n);q=q>0?n.slice(0,q):n;var t=c.Oc;c.Oc+=l;
e[q]=[l,t];for(n=0;n<l;++n)d[t]=n,c.hd[t++]=q}}c=a.zc;d=0;h=b;e=Jb(b);e>0&&(d=b.slice(e+1),d=parseInt(d)>>>0,h=b.slice(0,e));if((e=a.jd[h])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T||=1281;return-1},bb:(a,b,c)=>{for(var d=Eb[b],e=0;e<b;e++)d[e]=u[c+e*4>>2];N.invalidateFramebuffer(a,d)},C:a=>{a=P[a];N.linkProgram(a);a.zc=0;a.jd={}},q:(a,b)=>{a==3317?wb=b:a==3314&&(xb=b);N.pixelStorei(a,b)},J:(a,b)=>N.polygonOffset(a,b),db:a=>N.readBuffer(a),Eb:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,
b,c,d,e),D:(a,b,c)=>{N.samplerParameterf(S[a],b,c)},f:(a,b,c)=>{N.samplerParameteri(S[a],b,c)},Ab:(a,b,c,d)=>N.scissor(a,b,c,d),Lb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=v[c+h*4>>2])?F(f,d?v[d+h*4>>2]:void 0):"";e+=f}N.shaderSource(R[a],e)},Ja:(a,b,c)=>N.stencilFunc(a,b,c),pa:(a,b,c,d)=>N.stencilFuncSeparate(a,b,c,d),s:a=>N.stencilMask(a),Ia:(a,b,c)=>N.stencilOp(a,b,c),oa:(a,b,c,d)=>N.stencilOpSeparate(a,b,c,d),za:(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),ya:(a,b,c,d,e,h)=>N.texStorage3D(a,b,
c,d,e,h),g:(a,b,c,d,e,h,f,l,n)=>{if(V.version>=2){if(N.yc){N.texSubImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var q=Kb(l);N.texSubImage2D(a,b,c,d,e,h,f,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=Kb(l);var t=h*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*q.BYTES_PER_ELEMENT*(xb||e)+wb-1&-wb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+t>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;N.texSubImage2D(a,b,c,d,e,h,f,l,n)},E:(a,b,c,d,e,h,f,l,n,q,
t)=>{if(N.yc)N.texSubImage3D(a,b,c,d,e,h,f,l,n,q,t);else if(t){var M=Kb(q);N.texSubImage3D(a,b,c,d,e,h,f,l,n,q,M,t>>>31-Math.clz32(M.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,b,c,d,e,h,f,l,n,q,null)},rb:(a,b,c)=>{if(V.version>=2)b&&N.uniform1fv(W(a),w,c>>2,b);else{if(b<=288)for(var d=X[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+b*4>>2);N.uniform1fv(W(a),d)}},Nb:(a,b)=>{N.uniform1i(W(a),b)},nb:(a,b,c)=>{if(V.version>=2)b&&N.uniform1iv(W(a),u,c>>2,b);else{if(b<=288)for(var d=Lb[b],e=
0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+b*4>>2);N.uniform1iv(W(a),d)}},qb:(a,b,c)=>{if(V.version>=2)b&&N.uniform2fv(W(a),w,c>>2,b*2);else{if(b<=144){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+b*8>>2);N.uniform2fv(W(a),d)}},mb:(a,b,c)=>{if(V.version>=2)b&&N.uniform2iv(W(a),u,c>>2,b*2);else{if(b<=144){b*=2;for(var d=Lb[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+b*8>>2);N.uniform2iv(W(a),d)}},pb:(a,
b,c)=>{if(V.version>=2)b&&N.uniform3fv(W(a),w,c>>2,b*3);else{if(b<=96){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+b*12>>2);N.uniform3fv(W(a),d)}},lb:(a,b,c)=>{if(V.version>=2)b&&N.uniform3iv(W(a),u,c>>2,b*3);else{if(b<=96){b*=3;for(var d=Lb[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+b*12>>2);N.uniform3iv(W(a),d)}},ob:(a,b,c)=>{if(V.version>=2)b&&N.uniform4fv(W(a),
w,c>>2,b*4);else{if(b<=72){var d=X[4*b],e=w;c>>=2;b*=4;for(var h=0;h<b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=w.subarray(c>>2,c+b*16>>2);N.uniform4fv(W(a),d)}},kb:(a,b,c)=>{if(V.version>=2)b&&N.uniform4iv(W(a),u,c>>2,b*4);else{if(b<=72){b*=4;for(var d=Lb[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+b*16>>2);N.uniform4iv(W(a),d)}},jb:(a,b,c,d)=>{if(V.version>=2)b&&N.uniformMatrix4fv(W(a),
!!c,w,d>>2,b*16);else{if(b<=18){var e=X[16*b],h=w;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=w.subarray(d>>2,d+b*64>>2);N.uniformMatrix4fv(W(a),!!c,e)}},r:a=>{a=P[a];N.useProgram(a);N.ld=a},vb:(a,b)=>{N.vertexAttribDivisor(a,b)},wb:(a,b,c,d,e)=>{N.vertexAttribIPointer(a,
b,c,d,e)},xb:(a,b,c,d,e,h)=>{N.vertexAttribPointer(a,b,c,!!d,e,h)},Cb:(a,b,c,d)=>N.viewport(a,b,c,d),_a:Ea,Rb:function(){g.ad=a=>{Ub()!=0&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.ad)},Wa:function(){g.gd=a=>{var b=a.clipboardData.getData("text");Qb(()=>{var c=Nb(b);Tb(c)})};window.addEventListener("paste",g.gd)},Qa:function(){g.Od=[];g.bd=b=>{b.stopPropagation();b.preventDefault()};g.cd=b=>{b.stopPropagation();b.preventDefault()};g.dd=b=>{b.stopPropagation();
b.preventDefault()};g.ed=b=>{b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;g.Pd=c;Vb(c.length);for(let e=0;e<c.length;e++)Qb(()=>{var h=Nb(c[e].name);Wb(e,h)});var d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Xb(b.clientX,b.clientY,d)};var a=g.vc;a.addEventListener("dragenter",g.bd,!1);a.addEventListener("dragleave",g.cd,!1);a.addEventListener("dragover",g.dd,!1);a.addEventListener("drop",g.ed,!1)},Pb:function(){var a=document.getElementById("sokol-app-favicon");
a&&document.head.removeChild(a)},xa:function(a){g.Ec&&(URL.revokeObjectURL(g.Ec[a].sd),g.Ec[a]=null)},Ka:function(a,b){b!==0&&(document.title=b?F(b):"");a=a?F(a):"";g.canvas!==void 0&&(typeof g.canvas==="object"?Xa[a]=g.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));g.vc=G(a);g.vc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);g.vc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Qb:function(){window.removeEventListener("beforeunload",
g.ad)},Ra:function(){window.removeEventListener("paste",g.gd)},Na:function(){var a=g.vc;a.removeEventListener("dragenter",g.bd);a.removeEventListener("dragleave",g.cd);a.removeEventListener("dragover",g.dd);a.removeEventListener("drop",g.ed)},x:function(){g.vc&&g.vc.requestPointerLock&&g.vc.requestPointerLock()},Fa:function(a,b,c){if(g.vc){if(b===0)a="none";else if(c!=0)a=g.Ec[a].ud;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a=
"pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.vc.style.cursor=a}},Hb:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(r.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();
document.head.appendChild(a)},Za:function(){return g.wc?g.wc.bufferSize:0},Bb:function(a,b,c){g.mc=null;g.wc=null;typeof AudioContext!=="undefined"?g.mc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.mc=null,console.log("sokol_audio.h: no WebAudio support"));if(g.mc){console.log("sokol_audio.h: sample rate ",g.mc.sampleRate);g.wc=g.mc.createScriptProcessor(c,0,b);g.wc.onaudioprocess=e=>{var h=e.outputBuffer.length,f=Zb(h);if(f){let l=e.outputBuffer.numberOfChannels;for(let n=0;n<l;n++){let q=
e.outputBuffer.getChannelData(n);for(let t=0;t<h;t++)q[t]=w[(f>>2)+(l*t+n)]}}};g.wc.connect(g.mc.destination);let d=()=>{if(g.mc){let e=g.mc.state;e!=="suspended"&&e!=="interrupted"||g.mc.resume().catch(()=>{console.warn("sokol_audio.h: webaudio resume failed")})}};g.mc.onstatechange=d;document.addEventListener("visibilitychange",()=>{document.visibilityState==="visible"&&d()});document.addEventListener("click",d,{once:!0});document.addEventListener("touchend",d,{once:!0});document.addEventListener("keydown",
d,{once:!0});return 1}return 0},ib:function(){return g.mc?g.mc.sampleRate:0},tb:function(){var a=g.mc;a!==null&&(g.wc&&g.wc.disconnect(),a.close(),g.mc=null,g.wc=null)},A:function(a,b,c,d,e,h){var f=b?F(b):"";b=new Headers;d>0&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(f,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(n=>{n=new Uint8Array(n);n.length<=h?(r.set(n,e),ac(a,d,n.length)):cc(a)}).catch(n=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,n);dc(a)}):bc(a,l.status)}).catch(l=>
{console.error(`sokol_fetch.h: GET ${f} failed with: `,l);dc(a)})},na:function(a,b){var c=b?F(b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),d===null?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),dc(a)):$b(a,Number(d))):bc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);dc(a)})},ma:function(a,b){b=b?F(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;
default:console.info(b)}}};function hc(a=[]){var b=Yb;a.unshift(ea);var c=a.length,d=Mb((c+1)*4),e=d,h;for(h of a)v[e>>2]=Nb(h),e+=4;v[e>>2]=0;try{var f=b(c,d);ma=f;Ea(f)}catch(l){Da(l)}}async function ic(){var a=da;ra();var b=g.setStatus;b&&(b("Running..."),await new Promise(c=>setTimeout(c,1)),setTimeout(b,1,""));m||(jc.Tb(),g.onRuntimeInitialized?.(),g.noInitialRun||hc(a),ta())}var jc;
(async function(){function a(d){d=jc=d.exports;L=d.Ub;Tb=g.__sapp_emsc_onpaste=d.Vb;Ub=g.__sapp_html5_get_ask_leave_site=d.Wb;Vb=g.__sapp_emsc_begin_drop=d.Xb;Wb=g.__sapp_emsc_drop=d.Yb;Xb=g.__sapp_emsc_end_drop=d.Zb;g.__sapp_emsc_invoke_fetch_cb=d._b;g.__sapp_emsc_set_fullscreen_flag=d.$b;Yb=g._main=d.ac;Zb=g.__saudio_emsc_pull=d.bc;$b=g.__sfetch_emsc_head_response=d.cc;ac=g.__sfetch_emsc_get_response=d.dc;bc=g.__sfetch_emsc_failed_http_status=d.ec;cc=g.__sfetch_emsc_failed_buffer_too_small=d.fc;
dc=g.__sfetch_emsc_failed_other=d.gc;ec=d.ic;Pb=d.jc;Mb=d.kc;Ob=d.lc;oa=d.Sb;$a=d.hc;na();return jc}var b={a:fc},c=g.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});wa??=g.locateFile?g.locateFile("plmpeg-sapp.wasm",ia):ia+"plmpeg-sapp.wasm";return function(d){return a(d.instance)}(await za(b))})().then(()=>ic());
