
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign,ba=aa({},f),ca=[],da="./this.program",k=(a,b)=>{throw b;},ea="object"===typeof window,m="function"===typeof importScripts,r="",fa,t,u,fs,w,ha;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)r=m?require("path").dirname(r)+"/":__dirname+"/",ha=function(){w||(fs=require("fs"),w=require("path"))},fa=function(a,b){ha();a=w.normalize(a);return fs.readFileSync(a,b?null:"utf8")},u=function(a){a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a},t=function(a,b,c){ha();a=w.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,
"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof x))throw a;}),process.on("unhandledRejection",function(a){throw a;}),k=(a,b)=>{if(noExitRuntime||0<ia)throw process.exitCode=a,b;b instanceof x||y("exiting due to exception: "+b);process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ea||m)m?r=self.location.href:"undefined"!==typeof document&&document.currentScript&&(r=document.currentScript.src),
r=0!==r.indexOf("blob:")?r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(u=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),t=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};
var ja=f.print||console.log.bind(console),y=f.printErr||console.warn.bind(console);aa(f,ba);ba=null;f.arguments&&(ca=f.arguments);f.thisProgram&&(da=f.thisProgram);f.quit&&(k=f.quit);var z;f.wasmBinary&&(z=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&ka("no native wasm support detected");var la,ma=!1;
function na(a,b,c){var d={string:function(n){var p=0;if(null!==n&&void 0!==n&&0!==n){var q=(n.length<<2)+1;p=A(q);B(n,C,p,q)}return p},array:function(n){var p=A(n.length);oa.set(n,p);return p}};a=f["_"+a];var e=[],h=0;if(c)for(var g=0;g<c.length;g++){var l=d[b[g]];l?(0===h&&(h=pa()),e[g]=l(c[g])):e[g]=c[g]}b=a.apply(null,e);b=function(n){0!==h&&qa(h);return n}(b)}var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a,b){return a?sa(C,a,b):""}
function B(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var l=a.charCodeAt(++h);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ua(a){var b=ta(a)+1,c=A(b);B(a,oa,c,b);return c}var va,oa,C,wa,xa,E,ya,F,G;
function za(){var a=la.buffer;va=a;f.HEAP8=oa=new Int8Array(a);f.HEAP16=wa=new Int16Array(a);f.HEAP32=E=new Int32Array(a);f.HEAPU8=C=new Uint8Array(a);f.HEAPU16=xa=new Uint16Array(a);f.HEAPU32=ya=new Uint32Array(a);f.HEAPF32=F=new Float32Array(a);f.HEAPF64=G=new Float64Array(a)}var Aa,Ba=[],Ca=[],Da=[],Ea=[],Fa=[],ia=0;function Ga(){var a=f.preRun.shift();Ba.unshift(a)}var H=0,Ha=null,I=null;f.preloadedImages={};f.preloadedAudios={};
function ka(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";y(a);ma=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ia(){return J.startsWith("data:application/octet-stream;base64,")}var J;J="plmpeg-sapp-ui.wasm";if(!Ia()){var Ja=J;J=f.locateFile?f.locateFile(Ja,r):r+Ja}function Ka(){var a=J;try{if(a==J&&z)return new Uint8Array(z);if(u)return u(a);throw"both async and sync fetching of the wasm failed";}catch(b){ka(b)}}
function La(){if(!z&&(ea||m)){if("function"===typeof fetch&&!J.startsWith("file://"))return fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Ka()});if(t)return new Promise(function(a,b){t(J,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ka()})}
function Ma(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Rc;"number"===typeof c?void 0===b.oc?K(c)():K(c)(b.oc):c(void 0===b.oc?null:b.oc)}}}var Na=[];function K(a){var b=Na[a];b||(a>=Na.length&&(Na.length=a+1),Na[a]=b=Aa.get(a));return b}var Oa=[null,[],[]],Pa={},Qa=0;function Ra(){for(var a=L.length-1;0<=a;--a)Sa(a);L=[];Ta=[]}var Ta=[];function Ua(){if(Qa&&Va.jc)for(var a=0;a<Ta.length;++a){var b=Ta[a];Ta.splice(a,1);--a;b.ad.apply(null,b.Nc)}}var L=[];
function Sa(a){var b=L[a];b.target.removeEventListener(b.ac,b.Jc,b.bc);L.splice(a,1)}function M(a){function b(d){++Qa;Va=a;Ua();a.dc(d);Ua();--Qa}if(a.cc)a.Jc=b,a.target.addEventListener(a.ac,b,a.bc),L.push(a),Wa||(Ea.push(Ra),Wa=!0);else for(var c=0;c<L.length;++c)L[c].target==a.target&&L[c].ac==a.ac&&Sa(c--)}function Xa(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Wa,Va,Ya,Za,$a,ab,bb,cb,db,eb=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function N(a){a=2<a?D(a):a;return eb[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function fb(a){return 0>eb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function gb(a,b,c,d,e,h){Ya||(Ya=O(256));a={target:N(a),ac:h,cc:d,dc:function(g){g=g||event;var l=g.target.id?g.target.id:"",n=Ya;B(Xa(g.target),C,n+0,128);B(l,C,n+128,128);K(d)(e,n,b)&&g.preventDefault()},bc:c};M(a)}
function hb(a,b,c,d,e,h){Za||(Za=O(176));a={target:N(a),jc:!0,ac:h,cc:d,dc:function(g){var l=Za;G[l>>3]=g.timeStamp;var n=l>>2;E[n+2]=g.location;E[n+3]=g.ctrlKey;E[n+4]=g.shiftKey;E[n+5]=g.altKey;E[n+6]=g.metaKey;E[n+7]=g.repeat;E[n+8]=g.charCode;E[n+9]=g.keyCode;E[n+10]=g.which;B(g.key||"",C,l+44,32);B(g.code||"",C,l+76,32);B(g.char||"",C,l+108,32);B(g.locale||"",C,l+140,32);K(d)(e,l,b)&&g.preventDefault()},bc:c};M(a)}
function ib(a,b,c){G[a>>3]=b.timeStamp;a>>=2;E[a+2]=b.screenX;E[a+3]=b.screenY;E[a+4]=b.clientX;E[a+5]=b.clientY;E[a+6]=b.ctrlKey;E[a+7]=b.shiftKey;E[a+8]=b.altKey;E[a+9]=b.metaKey;wa[2*a+20]=b.button;wa[2*a+21]=b.buttons;E[a+11]=b.movementX;E[a+12]=b.movementY;c=fb(c);E[a+13]=b.clientX-c.left;E[a+14]=b.clientY-c.top}
function P(a,b,c,d,e,h){$a||($a=O(72));a=N(a);M({target:a,jc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ac:h,cc:d,dc:function(g){g=g||event;ib($a,g,a);K(d)(e,$a,b)&&g.preventDefault()},bc:c})}function jb(a,b,c,d,e){ab||(ab=O(260));M({target:a,ac:e,cc:d,dc:function(h){h=h||event;var g=ab,l=document.pointerLockElement||document.qc||document.sc||document.rc;E[g>>2]=!!l;var n=l&&l.id?l.id:"";B(Xa(l),C,g+4,128);B(n,C,g+132,128);K(d)(20,g,b)&&h.preventDefault()},bc:c})}
function kb(a,b,c,d,e){M({target:a,ac:e,cc:d,dc:function(h){h=h||event;K(d)(38,0,b)&&h.preventDefault()},bc:c})}
function lb(a,b,c,d){bb||(bb=O(36));a=N(a);M({target:a,ac:"resize",cc:d,dc:function(e){e=e||event;if(e.target==a){var h=document.body;if(h){var g=bb;E[g>>2]=e.detail;E[g+4>>2]=h.clientWidth;E[g+8>>2]=h.clientHeight;E[g+12>>2]=innerWidth;E[g+16>>2]=innerHeight;E[g+20>>2]=outerWidth;E[g+24>>2]=outerHeight;E[g+28>>2]=pageXOffset;E[g+32>>2]=pageYOffset;K(d)(10,g,b)&&e.preventDefault()}}},bc:c})}
function mb(a,b,c,d,e,h){cb||(cb=O(1696));a=N(a);M({target:a,jc:"touchstart"==h||"touchend"==h,ac:h,cc:d,dc:function(g){for(var l,n={},p=g.touches,q=0;q<p.length;++q)l=p[q],l.xc=l.zc=0,n[l.identifier]=l;for(q=0;q<g.changedTouches.length;++q)l=g.changedTouches[q],l.xc=1,n[l.identifier]=l;for(q=0;q<g.targetTouches.length;++q)n[g.targetTouches[q].identifier].zc=1;p=cb;G[p>>3]=g.timeStamp;var v=p>>2;E[v+3]=g.ctrlKey;E[v+4]=g.shiftKey;E[v+5]=g.altKey;E[v+6]=g.metaKey;v+=7;var rb=fb(a),sb=0;for(q in n)if(l=
n[q],E[v]=l.identifier,E[v+1]=l.screenX,E[v+2]=l.screenY,E[v+3]=l.clientX,E[v+4]=l.clientY,E[v+5]=l.pageX,E[v+6]=l.pageY,E[v+7]=l.xc,E[v+8]=l.zc,E[v+9]=l.clientX-rb.left,E[v+10]=l.clientY-rb.top,v+=13,31<++sb)break;E[p+8>>2]=sb;K(d)(e,p,b)&&g.preventDefault()},bc:c})}function nb(a,b,c,d,e,h){a={target:N(a),ac:h,cc:d,dc:function(g){g=g||event;K(d)(e,0,b)&&g.preventDefault()},bc:c};M(a)}
function ob(a,b,c,d){db||(db=O(104));M({target:a,jc:!0,ac:"wheel",cc:d,dc:function(e){e=e||event;var h=db;ib(h,e,a);G[h+72>>3]=e.deltaX;G[h+80>>3]=e.deltaY;G[h+88>>3]=e.deltaZ;E[h+96>>2]=e.deltaMode;K(d)(9,h,b)&&e.preventDefault()},bc:c})}
function pb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function qb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function tb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function ub(a){a.Pc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function vb(a){a.Uc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function wb(a){a.Wc=a.getExtension("WEBGL_multi_draw")}var xb=1,yb=[],Q=[],zb=[],Ab=[],Bb=[],R=[],Cb=[],Db=[],Eb={},Fb={};function S(a){Gb||(Gb=a)}function Hb(a){for(var b=xb++,c=a.length;c<b;c++)a[c]=null;return b}
function Ib(a,b){a.wc||(a.wc=a.getContext,a.getContext=function(d,e){e=a.wc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.yc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Jb(c,b):0}function Jb(a,b){var c=Hb(Db),d={Tc:c,attributes:b,version:b.yc,nc:a};a.canvas&&(a.canvas.Mc=d);Db[c]=d;("undefined"===typeof b.vc||b.vc)&&Kb(d);return c}
function Kb(a){a||(a=T);if(!a.Lc){a.Lc=!0;var b=a.nc;pb(b);qb(b);tb(b);ub(b);vb(b);2<=a.version&&(b.uc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.uc)b.uc=b.getExtension("EXT_disjoint_timer_query");wb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Gb,T,Lb=["default","low-power","high-performance"];
function Mb(a,b,c,d){for(var e=0;e<a;e++){var h=U[c](),g=h&&Hb(d);h?(h.name=g,d[g]=h):S(1282);E[b+4*e>>2]=g}}
function Nb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=U.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>T.version){S(1282);return}c=2*(U.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>T.version){S(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=U.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":S(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:S(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)E[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){S(1280);y("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:S(1280);y("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}E[b>>2]=c}else S(1281)}
function V(a){var b=ta(a)+1,c=O(b);B(a,C,c,b);return c}function Ob(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function W(a){a-=5120;return 0==a?oa:1==a?C:2==a?wa:4==a?E:6==a?F:5==a||28922==a||28520==a||30779==a||30782==a?ya:xa}function X(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Pb(a,b,c,d,e){a=W(a);var h=X(a);return a.subarray(e>>h,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<h)+4-1&-4)>>h)}
function Y(a){var b=U.Ic;if(b){var c=b.ic[a];"number"===typeof c&&(b.ic[a]=c=U.getUniformLocation(b,b.Gc[a]+(0<c?"["+c+"]":"")));return c}S(1282)}for(var Z=[],U,Qb=new Float32Array(288),Rb=0;288>Rb;++Rb)Z[Rb]=Qb.subarray(0,Rb+1);
var ac={ma:function(){return 0},ib:function(){return 0},jb:function(){},V:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},ea:function(a,b,c){a=N(a);if(!a)return-4;a=fb(a);G[b>>3]=a.width;G[c>>3]=a.height;return 0},eb:function(a,b,c){C.copyWithin(a,b,b+c)},Oa:function(a,b){function c(d){K(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},fb:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);
d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{la.grow(Math.min(2147483648,d)-va.byteLength+65535>>>16);za();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},Y:function(a,b,c,d){gb(a,b,c,d,12,"blur");return 0},T:function(a,b,c){a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},Z:function(a,b,c,d){gb(a,b,c,d,13,"focus");return 0},ha:function(a,b,c,d){hb(a,b,c,d,2,"keydown");return 0},fa:function(a,b,c,d){hb(a,b,c,d,1,"keypress");return 0},ga:function(a,b,c,d){hb(a,b,c,d,3,"keyup");
return 0},ra:function(a,b,c,d){P(a,b,c,d,5,"mousedown");return 0},ka:function(a,b,c,d){P(a,b,c,d,33,"mouseenter");return 0},ja:function(a,b,c,d){P(a,b,c,d,34,"mouseleave");return 0},pa:function(a,b,c,d){P(a,b,c,d,8,"mousemove");return 0},qa:function(a,b,c,d){P(a,b,c,d,6,"mouseup");return 0},$:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.qc||document.body.sc||document.body.rc))return-1;a=N(a);if(!a)return-4;jb(a,b,c,d,"pointerlockchange");jb(a,b,
c,d,"mozpointerlockchange");jb(a,b,c,d,"webkitpointerlockchange");jb(a,b,c,d,"mspointerlockchange");return 0},_:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.qc||document.body.sc||document.body.rc))return-1;a=N(a);if(!a)return-4;kb(a,b,c,d,"pointerlockerror");kb(a,b,c,d,"mozpointerlockerror");kb(a,b,c,d,"webkitpointerlockerror");kb(a,b,c,d,"mspointerlockerror");return 0},ab:function(a,b,c,d){lb(a,b,c,d);return 0},aa:function(a,b,c,d){mb(a,b,c,d,25,"touchcancel");
return 0},ba:function(a,b,c,d){mb(a,b,c,d,23,"touchend");return 0},ca:function(a,b,c,d){mb(a,b,c,d,24,"touchmove");return 0},da:function(a,b,c,d){mb(a,b,c,d,22,"touchstart");return 0},X:function(a,b,c,d){nb(a,b,c,d,31,"webglcontextlost");return 0},W:function(a,b,c,d){nb(a,b,c,d,32,"webglcontextrestored");return 0},ia:function(a,b,c,d){a=N(a);return"undefined"!==typeof a.onwheel?(ob(a,b,c,d),0):-1},H:function(a,b){b>>=2;b={alpha:!!E[b],depth:!!E[b+1],stencil:!!E[b+2],antialias:!!E[b+3],premultipliedAlpha:!!E[b+
4],preserveDrawingBuffer:!!E[b+5],powerPreference:Lb[E[b+6]],failIfMajorPerformanceCaveat:!!E[b+7],yc:E[b+8],Vc:E[b+9],vc:E[b+10],Kc:E[b+11],Xc:E[b+12],Yc:E[b+13]};a=N(a);return!a||b.Kc?0:Ib(a,b)},Fb:function(a,b){a=Db[a];b=D(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&pb(U);"OES_vertex_array_object"==b&&qb(U);"WEBGL_draw_buffers"==b&&tb(U);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&ub(U);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&vb(U);"WEBGL_multi_draw"==
b&&wb(U);return!!a.nc.getExtension(b)},La:function(a){a>>=2;for(var b=0;14>b;++b)E[a+b]=0;E[a]=E[a+1]=E[a+3]=E[a+4]=E[a+8]=E[a+10]=1},Aa:function(a){T=Db[a];f.Oc=U=T&&T.nc;return!a||U?0:-5},la:function(){return 0},hb:function(a,b,c,d){a=Pa.Sc(a);b=Pa.Qc(a,b,c);E[d>>2]=b;return 0},db:function(){},gb:function(a,b,c,d){for(var e=0,h=0;h<c;h++){var g=E[b>>2],l=E[b+4>>2];b+=8;for(var n=0;n<l;n++){var p=C[g+n],q=Oa[a];0===p||10===p?((1===a?ja:y)(sa(q,0)),q.length=0):q.push(p)}e+=l}E[d>>2]=e;return 0},b:function(a){U.activeTexture(a)},
F:function(a,b){U.attachShader(Q[a],R[b])},c:function(a,b){35051==a?U.tc=b:35052==a&&(U.fc=b);U.bindBuffer(a,yb[b])},h:function(a,b){U.bindFramebuffer(a,zb[b])},J:function(a,b){U.bindRenderbuffer(a,Ab[b])},a:function(a,b){U.bindTexture(a,Bb[b])},S:function(a){U.bindVertexArray(Cb[a])},O:function(a,b,c,d){U.blendColor(a,b,c,d)},P:function(a,b){U.blendEquationSeparate(a,b)},Q:function(a,b,c,d){U.blendFuncSeparate(a,b,c,d)},q:function(a,b,c,d,e,h,g,l,n,p){U.blitFramebuffer(a,b,c,d,e,h,g,l,n,p)},Ja:function(a,
b,c,d){2<=T.version?c?U.bufferData(a,C,d,c,b):U.bufferData(a,b,d):U.bufferData(a,c?C.subarray(c,c+b):b,d)},m:function(a,b,c,d){2<=T.version?U.bufferSubData(a,b,C,d,c):U.bufferSubData(a,b,C.subarray(d,d+c))},Cb:function(a){U.clear(a)},ua:function(a,b,c,d){U.clearColor(a,b,c,d)},A:function(a){U.clearDepth(a)},Db:function(a){U.clearStencil(a)},j:function(a,b,c,d){U.colorMask(!!a,!!b,!!c,!!d)},wa:function(a){U.compileShader(R[a])},Ga:function(a,b,c,d,e,h,g,l){2<=T.version?U.fc?U.compressedTexImage2D(a,
b,c,d,e,h,g,l):U.compressedTexImage2D(a,b,c,d,e,h,C,l,g):U.compressedTexImage2D(a,b,c,d,e,h,l?C.subarray(l,l+g):null)},Ea:function(a,b,c,d,e,h,g,l,n){U.fc?U.compressedTexImage3D(a,b,c,d,e,h,g,l,n):U.compressedTexImage3D(a,b,c,d,e,h,g,C,n,l)},Ca:function(){var a=Hb(Q),b=U.createProgram();b.name=a;b.mc=b.kc=b.lc=0;b.pc=1;Q[a]=b;return a},ya:function(a){var b=Hb(R);R[b]=U.createShader(a);return b},L:function(a){U.cullFace(a)},Sa:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=yb[d];e&&(U.deleteBuffer(e),
e.name=0,yb[d]=null,d==U.tc&&(U.tc=0),d==U.fc&&(U.fc=0))}},i:function(a,b){for(var c=0;c<a;++c){var d=E[b+4*c>>2],e=zb[d];e&&(U.deleteFramebuffer(e),e.name=0,zb[d]=null)}},y:function(a){if(a){var b=Q[a];b?(U.deleteProgram(b),b.name=0,Q[a]=null):S(1281)}},U:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=Ab[d];e&&(U.deleteRenderbuffer(e),e.name=0,Ab[d]=null)}},u:function(a){if(a){var b=R[a];b?(U.deleteShader(b),R[a]=null):S(1281)}},Ra:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=Bb[d];
e&&(U.deleteTexture(e),e.name=0,Bb[d]=null)}},Qa:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2];U.deleteVertexArray(Cb[d]);Cb[d]=null}},x:function(a){U.depthFunc(a)},w:function(a){U.depthMask(!!a)},e:function(a){U.disable(a)},R:function(a){U.disableVertexAttribArray(a)},qb:function(a,b,c){U.drawArrays(a,b,c)},rb:function(a,b,c,d){U.drawArraysInstanced(a,b,c,d)},sb:function(a,b,c,d){U.drawElements(a,b,c,d)},tb:function(a,b,c,d,e){U.drawElementsInstanced(a,b,c,d,e)},g:function(a){U.enable(a)},
zb:function(a){U.enableVertexAttribArray(a)},M:function(a){U.frontFace(a)},Ka:function(a,b){Mb(a,b,"createBuffer",yb)},K:function(a,b){Mb(a,b,"createRenderbuffer",Ab)},Ha:function(a,b){Mb(a,b,"createTexture",Bb)},Pa:function(a,b){Mb(a,b,"createVertexArray",Cb)},Eb:function(a,b){return U.getAttribLocation(Q[a],D(b))},d:function(a,b){Nb(a,b)},za:function(a,b,c,d){a=U.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,C,d,b):0;c&&(E[c>>2]=b)},E:function(a,b,c){if(c)if(a>=xb)S(1281);
else if(a=Q[a],35716==b)a=U.getProgramInfoLog(a),null===a&&(a="(unknown error)"),E[c>>2]=a.length+1;else if(35719==b){if(!a.mc)for(b=0;b<U.getProgramParameter(a,35718);++b)a.mc=Math.max(a.mc,U.getActiveUniform(a,b).name.length+1);E[c>>2]=a.mc}else if(35722==b){if(!a.kc)for(b=0;b<U.getProgramParameter(a,35721);++b)a.kc=Math.max(a.kc,U.getActiveAttrib(a,b).name.length+1);E[c>>2]=a.kc}else if(35381==b){if(!a.lc)for(b=0;b<U.getProgramParameter(a,35382);++b)a.lc=Math.max(a.lc,U.getActiveUniformBlockName(a,
b).length+1);E[c>>2]=a.lc}else E[c>>2]=U.getProgramParameter(a,b);else S(1281)},va:function(a,b,c,d){a=U.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,C,d,b):0;c&&(E[c>>2]=b)},C:function(a,b,c){c?35716==b?(a=U.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),E[c>>2]=a?a.length+1:0):35720==b?(a=U.getShaderSource(R[a]),E[c>>2]=a?a.length+1:0):E[c>>2]=U.getShaderParameter(R[a],b):S(1281)},Ua:function(a){var b=Eb[a];if(!b){switch(a){case 7939:b=U.getSupportedExtensions()||
[];b=b.concat(b.map(function(d){return"GL_"+d}));b=V(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=U.getParameter(a))||S(1280);b=b&&V(b);break;case 7938:b=U.getParameter(7938);b=2<=T.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=V(b);break;case 35724:b=U.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=V(b);break;default:S(1280)}Eb[a]=b}return b},Ta:function(a,
b){if(2>T.version)return S(1282),0;var c=Fb[a];if(c)return 0>b||b>=c.length?(S(1281),0):c[b];switch(a){case 7939:return c=U.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return V(d)}),c=Fb[a]=c,0>b||b>=c.length?(S(1281),0):c[b];default:return S(1280),0}},l:function(a,b){b=D(b);if(a=Q[a]){var c=a,d=c.ic,e=c.Hc,h;if(!d)for(c.ic=d={},c.Gc={},h=0;h<U.getProgramParameter(c,35718);++h){var g=U.getActiveUniform(c,h);var l=g.name;g=g.size;var n=Ob(l);n=0<n?
l.slice(0,n):l;var p=c.pc;c.pc+=g;e[n]=[g,p];for(l=0;l<g;++l)d[p]=l,c.Gc[p++]=n}c=a.ic;d=0;e=b;h=Ob(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Hc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||U.getUniformLocation(a,b)))return d}else S(1281);return-1},Ba:function(a){a=Q[a];U.linkProgram(a);a.ic=0;a.Hc={}},N:function(a,b){U.polygonOffset(a,b)},r:function(a){U.readBuffer(a)},Ia:function(a,b,c,d){U.renderbufferStorage(a,b,c,d)},I:function(a,b,c,d,e){U.renderbufferStorageMultisample(a,b,c,d,e)},
s:function(a,b,c,d){U.scissor(a,b,c,d)},xa:function(a,b,c,d){for(var e="",h=0;h<b;++h){var g=d?E[d+4*h>>2]:-1;e+=D(E[c+4*h>>2],0>g?void 0:g)}U.shaderSource(R[a],e)},Na:function(a,b,c){U.stencilFunc(a,b,c)},ta:function(a,b,c,d){U.stencilFuncSeparate(a,b,c,d)},v:function(a){U.stencilMask(a)},Ma:function(a,b,c){U.stencilOp(a,b,c)},sa:function(a,b,c,d){U.stencilOpSeparate(a,b,c,d)},Fa:function(a,b,c,d,e,h,g,l,n){if(2<=T.version)if(U.fc)U.texImage2D(a,b,c,d,e,h,g,l,n);else if(n){var p=W(l);U.texImage2D(a,
b,c,d,e,h,g,l,p,n>>X(p))}else U.texImage2D(a,b,c,d,e,h,g,l,null);else U.texImage2D(a,b,c,d,e,h,g,l,n?Pb(l,g,d,e,n):null)},Da:function(a,b,c,d,e,h,g,l,n,p){if(U.fc)U.texImage3D(a,b,c,d,e,h,g,l,n,p);else if(p){var q=W(n);U.texImage3D(a,b,c,d,e,h,g,l,n,q,p>>X(q))}else U.texImage3D(a,b,c,d,e,h,g,l,n,null)},G:function(a,b,c){U.texParameterf(a,b,c)},f:function(a,b,c){U.texParameteri(a,b,c)},pb:function(a,b,c,d,e,h,g,l,n){if(2<=T.version)if(U.fc)U.texSubImage2D(a,b,c,d,e,h,g,l,n);else if(n){var p=W(l);U.texSubImage2D(a,
b,c,d,e,h,g,l,p,n>>X(p))}else U.texSubImage2D(a,b,c,d,e,h,g,l,null);else p=null,n&&(p=Pb(l,g,e,h,n)),U.texSubImage2D(a,b,c,d,e,h,g,l,p)},ob:function(a,b,c,d,e,h,g,l,n,p,q){if(U.fc)U.texSubImage3D(a,b,c,d,e,h,g,l,n,p,q);else if(q){var v=W(p);U.texSubImage3D(a,b,c,d,e,h,g,l,n,p,v,q>>X(v))}else U.texSubImage3D(a,b,c,d,e,h,g,l,n,p,null)},yb:function(a,b,c){if(2<=T.version)U.uniform1fv(Y(a),F,c>>2,b);else{if(288>=b)for(var d=Z[b-1],e=0;e<b;++e)d[e]=F[c+4*e>>2];else d=F.subarray(c>>2,c+4*b>>2);U.uniform1fv(Y(a),
d)}},D:function(a,b){U.uniform1i(Y(a),b)},xb:function(a,b,c){if(2<=T.version)U.uniform2fv(Y(a),F,c>>2,2*b);else{if(144>=b)for(var d=Z[2*b-1],e=0;e<2*b;e+=2)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2];else d=F.subarray(c>>2,c+8*b>>2);U.uniform2fv(Y(a),d)}},wb:function(a,b,c){if(2<=T.version)U.uniform3fv(Y(a),F,c>>2,3*b);else{if(96>=b)for(var d=Z[3*b-1],e=0;e<3*b;e+=3)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2];else d=F.subarray(c>>2,c+12*b>>2);U.uniform3fv(Y(a),d)}},vb:function(a,b,
c){if(2<=T.version)U.uniform4fv(Y(a),F,c>>2,4*b);else{if(72>=b){var d=Z[4*b-1],e=F;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=F.subarray(c>>2,c+16*b>>2);U.uniform4fv(Y(a),d)}},ub:function(a,b,c,d){if(2<=T.version)U.uniformMatrix4fv(Y(a),!!c,F,d>>2,16*b);else{if(18>=b){var e=Z[16*b-1],h=F;d>>=2;for(var g=0;g<16*b;g+=16){var l=d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=
h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=F.subarray(d>>2,d+64*b>>2);U.uniformMatrix4fv(Y(a),!!c,e)}},k:function(a){a=Q[a];U.useProgram(a);U.Ic=a},Ab:function(a,b){U.vertexAttribDivisor(a,b)},Bb:function(a,b,c,d,e,h){U.vertexAttribPointer(a,b,c,!!d,e,h)},t:function(a,b,c,d){U.viewport(a,b,c,d)},cb:function(){f.Ac=function(a){0!=Sb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Ac)},
bb:function(){f.Fc=function(a){a=a.clipboardData.getData("text");na("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",f.Fc)},$a:function(a){f.Zc=[];a=D(a);a=document.getElementById(a);f.Bc=function(b){b.stopPropagation();b.preventDefault()};f.Cc=function(b){b.stopPropagation();b.preventDefault()};f.Dc=function(b){b.stopPropagation();b.preventDefault()};f.Ec=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;f.$c=c;Tb(c.length);var d;for(d=0;d<c.length;d++)na("_sapp_emsc_drop",
["number","string"],[d,c[d].name]);Ub(b.clientX,b.clientY)};a.addEventListener("dragenter",f.Bc,!1);a.addEventListener("dragleave",f.Cc,!1);a.addEventListener("dragover",f.Dc,!1);a.addEventListener("drop",f.Ec,!1)},Wa:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},p:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Vb()});document.body.append(a)},
o:function(){document.getElementById("_sokol_app_input_element").focus()},Gb:function(a){a=D(a);f.hc=document.getElementById(a);f.hc||console.log("sokol_app.h: invalid target:"+a);f.hc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},_a:function(){window.removeEventListener("beforeunload",f.Ac)},Za:function(){window.removeEventListener("paste",f.Fc)},Ya:function(a){a=D(a);a=document.getElementById(a);a.removeEventListener("dragenter",f.Bc);a.removeEventListener("dragleave",
f.Cc);a.removeEventListener("dragover",f.Dc);a.removeEventListener("drop",f.Ec)},z:function(){f.hc&&f.hc.requestPointerLock&&f.hc.requestPointerLock()},Va:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(C.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},n:function(){document.getElementById("_sokol_app_input_element").blur()},
Xa:function(a){a=D(a);var b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},lb:function(){return f.ec?f.ec.bufferSize:0},nb:function(a,b,c){f.$b=null;f.ec=null;"undefined"!==typeof AudioContext?
f.$b=new AudioContext({sampleRate:a,latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?f.$b=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(f.$b=null,console.log("sokol_audio.h: no WebAudio support"));return f.$b?(console.log("sokol_audio.h: sample rate ",f.$b.sampleRate),f.ec=f.$b.createScriptProcessor(c,0,b),f.ec.onaudioprocess=function(d){var e=d.outputBuffer.length,h=Wb(e);if(h)for(var g=d.outputBuffer.numberOfChannels,l=0;l<g;l++)for(var n=d.outputBuffer.getChannelData(l),
p=0;p<e;p++)n[p]=F[(h>>2)+(g*p+l)]},f.ec.connect(f.$b.destination),a=function(){f.$b&&"suspended"===f.$b.state&&f.$b.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},mb:function(){return f.$b?f.$b.sampleRate:0},kb:function(){null!==f.$b&&(f.ec&&f.ec.disconnect(),f.$b.close(),f.$b=null,f.ec=null)},B:function(a,b,c,d,e,h){b=D(b);var g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";
var l=0<d;l&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(this.readyState==this.DONE)if(206==this.status||200==this.status&&!l){var n=new Uint8Array(g.response),p=n.length;p<=h?(C.set(n,e),Xb(a,d,p)):Yb(a)}else Zb(a,this.status)};g.send()},oa:function(a,b){b=D(b);var c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(this.readyState==this.DONE)if(200==this.status){var d=this.getResponseHeader("Content-Length");$b(a,d)}else Zb(a,this.status)};
c.send()},na:function(){return navigator.userAgent.includes("Macintosh")?1:0}};
(function(){function a(e){f.asm=e.exports;la=f.asm.Hb;za();Aa=f.asm._b;Ca.unshift(f.asm.Ib);H--;f.monitorRunDependencies&&f.monitorRunDependencies(H);0==H&&(null!==Ha&&(clearInterval(Ha),Ha=null),I&&(e=I,I=null,e()))}function b(e){a(e.instance)}function c(e){return La().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(e,function(h){y("failed to asynchronously prepare wasm: "+h);ka(h)})}var d={a:ac};H++;f.monitorRunDependencies&&f.monitorRunDependencies(H);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return y("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return z||"function"!==typeof WebAssembly.instantiateStreaming||Ia()||J.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(h){y("wasm streaming compile failed: "+h);y("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.Ib).apply(null,arguments)};var O=f._malloc=function(){return(O=f._malloc=f.asm.Jb).apply(null,arguments)},Vb=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Vb=f.__sapp_emsc_notify_keyboard_hidden=f.asm.Kb).apply(null,arguments)};f.__sapp_emsc_onpaste=function(){return(f.__sapp_emsc_onpaste=f.asm.Lb).apply(null,arguments)};
var Sb=f.__sapp_html5_get_ask_leave_site=function(){return(Sb=f.__sapp_html5_get_ask_leave_site=f.asm.Mb).apply(null,arguments)},Tb=f.__sapp_emsc_begin_drop=function(){return(Tb=f.__sapp_emsc_begin_drop=f.asm.Nb).apply(null,arguments)};f.__sapp_emsc_drop=function(){return(f.__sapp_emsc_drop=f.asm.Ob).apply(null,arguments)};var Ub=f.__sapp_emsc_end_drop=function(){return(Ub=f.__sapp_emsc_end_drop=f.asm.Pb).apply(null,arguments)};
f.__sapp_emsc_invoke_fetch_cb=function(){return(f.__sapp_emsc_invoke_fetch_cb=f.asm.Qb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Rb).apply(null,arguments)};
var Wb=f.__saudio_emsc_pull=function(){return(Wb=f.__saudio_emsc_pull=f.asm.Sb).apply(null,arguments)},$b=f.__sfetch_emsc_head_response=function(){return($b=f.__sfetch_emsc_head_response=f.asm.Tb).apply(null,arguments)},Xb=f.__sfetch_emsc_get_response=function(){return(Xb=f.__sfetch_emsc_get_response=f.asm.Ub).apply(null,arguments)},Zb=f.__sfetch_emsc_failed_http_status=function(){return(Zb=f.__sfetch_emsc_failed_http_status=f.asm.Vb).apply(null,arguments)},Yb=f.__sfetch_emsc_failed_buffer_too_small=
function(){return(Yb=f.__sfetch_emsc_failed_buffer_too_small=f.asm.Wb).apply(null,arguments)},pa=f.stackSave=function(){return(pa=f.stackSave=f.asm.Xb).apply(null,arguments)},qa=f.stackRestore=function(){return(qa=f.stackRestore=f.asm.Yb).apply(null,arguments)},A=f.stackAlloc=function(){return(A=f.stackAlloc=f.asm.Zb).apply(null,arguments)},bc;function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}I=function cc(){bc||dc();bc||(I=cc)};
function dc(a){function b(){if(!bc&&(bc=!0,f.calledRun=!0,!ma)){Ma(Ca);Ma(Da);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(ec){var c=a,d=f._main;c=c||[];var e=c.length+1,h=A(4*(e+1));E[h>>2]=ua(da);for(var g=1;g<e;g++)E[(h>>2)+g]=ua(c[g-1]);E[(h>>2)+e]=0;try{var l=d(e,h);if(!(noExitRuntime||0<ia)){if(f.onExit)f.onExit(l);ma=!0}k(l,new x(l))}catch(n){n instanceof x||"unwind"==n||k(1,n)}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),
Fa.unshift(c);Ma(Fa)}}a=a||ca;if(!(0<H)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ga();Ma(Ba);0<H||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=dc;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var ec=!0;f.noInitialRun&&(ec=!1);dc();
