var g;g||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},g),ba=[],ca="./this.program",k=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,r,v;
if(ea){var fs=require("fs"),ha=require("path");q=l?ha.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=ia(a)?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};r=(a,b,c,d=!0)=>{a=ia(a)?new URL(a):ha.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,h)=>{e?c(e):b(d?h.buffer:h)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof ja||a.context instanceof ja))throw a;});k=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);
b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),r=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};g.print||console.log.bind(console);var w=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(k=g.quit);var x;g.wasmBinary&&(x=g.wasmBinary);
"object"!=typeof WebAssembly&&ka("no native wasm support detected");var la,ma=!1,na,y,oa,pa,z,qa,A,B;function ra(){var a=la.buffer;g.HEAP8=na=new Int8Array(a);g.HEAP16=oa=new Int16Array(a);g.HEAPU8=y=new Uint8Array(a);g.HEAPU16=pa=new Uint16Array(a);g.HEAP32=z=new Int32Array(a);g.HEAPU32=qa=new Uint32Array(a);g.HEAPF32=A=new Float32Array(a);g.HEAPF64=B=new Float64Array(a)}var sa=[],ta=[],ua=[],va=[],wa=[];function xa(){var a=g.preRun.shift();sa.unshift(a)}var C=0,ya=null,D=null;
function ka(a){g.onAbort?.(a);a="Aborted("+a+")";w(a);ma=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var za=a=>a.startsWith("data:application/octet-stream;base64,"),ia=a=>a.startsWith("file://"),E;E="plmpeg-sapp.wasm";if(!za(E)){var Aa=E;E=g.locateFile?g.locateFile(Aa,q):q+Aa}function Ba(a){if(a==E&&x)return new Uint8Array(x);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}
function Ca(a){if(!x&&(da||l)){if("function"==typeof fetch&&!ia(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ba(a));if(r)return new Promise((b,c)=>{r(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ba(a))}function Da(a,b,c){return Ca(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{w(`failed to asynchronously prepare wasm: ${d}`);ka(d)})}
function Ea(a,b){var c=E;x||"function"!=typeof WebAssembly.instantiateStreaming||za(c)||ia(c)||ea||"function"!=typeof fetch?Da(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){w(`wasm streaming compile failed: ${e}`);w("falling back to ArrayBuffer instantiation");return Da(c,a,b)}))}function ja(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Fa=a=>{for(;0<a.length;)a.shift()(g)},Ga=g.noExitRuntime||!0,Ja=a=>{var b=Ha();a();Ia(b)},Ka=0;function La(){for(var a=F.length-1;0<=a;--a)Ma(a);F=[];Na=[]}var Na=[];function Oa(){if(navigator.userActivation?navigator.userActivation.isActive:Ka&&Pa.lc)for(var a=0;a<Na.length;++a){var b=Na[a];Na.splice(a,1);--a;b.Sc.apply(null,b.Jc)}}var F=[];function Ma(a){var b=F[a];b.target.removeEventListener(b.Yb,b.Ec,b.Zb);F.splice(a,1)}
function G(a){function b(d){++Ka;Pa=a;Oa();a.ac(d);Oa();--Ka}if(!a.target)return-4;if(a.$b)a.Ec=b,a.target.addEventListener(a.Yb,b,a.Zb),F.push(a),Qa||(va.push(La),Qa=!0);else for(var c=0;c<F.length;++c)F[c].target==a.target&&F[c].Yb==a.Yb&&Ma(c--);return 0}function Ra(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var Qa,Pa,Sa,Ta,Ua,Va,Wa,Xa,Ya,Za="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,H=(a,b)=>{var c=y,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&Za)return Za.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
$a=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],I=a=>{a=2<a?a?H(a):"":a;return $a[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},ab=a=>0>$a.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},bb=[],cb,J=a=>{var b=bb[a];b||(a>=bb.length&&(bb.length=a+1),bb[a]=b=cb.get(a));return b},K=(a,b,c)=>{var d=y;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var m=a.charCodeAt(++h);f=65536+((f&
1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},db=(a,b,c,d,e,h)=>{Sa||=L(256);a={target:I(a),Yb:h,$b:d,ac:(f=event)=>{var m=f.target.id?f.target.id:"",n=Sa;K(Ra(f.target),n+0,128);K(m,n+128,128);J(d)(e,n,b)&&f.preventDefault()},Zb:c};return G(a)},eb=(a,b,c,d,e,h)=>{Ta||=L(176);a={target:I(a),
Yb:h,$b:d,ac:f=>{var m=Ta;B[m>>3]=f.timeStamp;var n=m>>2;z[n+2]=f.location;z[n+3]=f.ctrlKey;z[n+4]=f.shiftKey;z[n+5]=f.altKey;z[n+6]=f.metaKey;z[n+7]=f.repeat;z[n+8]=f.charCode;z[n+9]=f.keyCode;z[n+10]=f.which;K(f.key||"",m+44,32);K(f.code||"",m+76,32);K(f.char||"",m+108,32);K(f.locale||"",m+140,32);J(d)(e,m,b)&&f.preventDefault()},Zb:c};return G(a)},fb=(a,b,c)=>{B[a>>3]=b.timeStamp;a>>=2;z[a+2]=b.screenX;z[a+3]=b.screenY;z[a+4]=b.clientX;z[a+5]=b.clientY;z[a+6]=b.ctrlKey;z[a+7]=b.shiftKey;z[a+8]=
b.altKey;z[a+9]=b.metaKey;oa[2*a+20]=b.button;oa[2*a+21]=b.buttons;z[a+11]=b.movementX;z[a+12]=b.movementY;c=ab(c);z[a+13]=b.clientX-c.left;z[a+14]=b.clientY-c.top},M=(a,b,c,d,e,h)=>{Ua||=L(72);a=I(a);return G({target:a,lc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Yb:h,$b:d,ac:(f=event)=>{fb(Ua,f,a);J(d)(e,Ua,b)&&f.preventDefault()},Zb:c})},gb=(a,b,c,d,e)=>{Va||=L(260);return G({target:a,Yb:e,$b:d,ac:(h=event)=>{var f=Va,m=document.pointerLockElement||document.dc||document.oc||document.nc;
z[f>>2]=!!m;var n=m?.id||"";K(Ra(m),f+4,128);K(n,f+132,128);J(d)(20,f,b)&&h.preventDefault()},Zb:c})},hb=(a,b,c,d,e)=>G({target:a,Yb:e,$b:d,ac:(h=event)=>{J(d)(38,0,b)&&h.preventDefault()},Zb:c}),ib=(a,b,c,d)=>{Wa||=L(36);a=I(a);return G({target:a,Yb:"resize",$b:d,ac:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=Wa;z[f>>2]=e.detail;z[f+4>>2]=h.clientWidth;z[f+8>>2]=h.clientHeight;z[f+12>>2]=innerWidth;z[f+16>>2]=innerHeight;z[f+20>>2]=outerWidth;z[f+24>>2]=outerHeight;z[f+28>>2]=pageXOffset;
z[f+32>>2]=pageYOffset;J(d)(10,f,b)&&e.preventDefault()}}},Zb:c})},jb=(a,b,c,d,e,h)=>{Xa||=L(1696);a=I(a);return G({target:a,lc:"touchstart"==h||"touchend"==h,Yb:h,$b:d,ac:f=>{for(var m,n={},p=f.touches,t=0;t<p.length;++t)m=p[t],m.sc=m.uc=0,n[m.identifier]=m;for(t=0;t<f.changedTouches.length;++t)m=f.changedTouches[t],m.sc=1,n[m.identifier]=m;for(t=0;t<f.targetTouches.length;++t)n[f.targetTouches[t].identifier].uc=1;p=Xa;B[p>>3]=f.timeStamp;var u=p>>2;z[u+3]=f.ctrlKey;z[u+4]=f.shiftKey;z[u+5]=f.altKey;
z[u+6]=f.metaKey;u+=7;var nb=ab(a),ob=0;for(t in n)if(m=n[t],z[u]=m.identifier,z[u+1]=m.screenX,z[u+2]=m.screenY,z[u+3]=m.clientX,z[u+4]=m.clientY,z[u+5]=m.pageX,z[u+6]=m.pageY,z[u+7]=m.sc,z[u+8]=m.uc,z[u+9]=m.clientX-nb.left,z[u+10]=m.clientY-nb.top,u+=13,31<++ob)break;z[p+8>>2]=ob;J(d)(e,p,b)&&f.preventDefault()},Zb:c})},kb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,
d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},lb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},mb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},pb=a=>{a.Lc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
qb=a=>{a.Mc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},rb=1,sb=[],N=[],tb=[],ub=[],vb=[],O=[],wb=[],xb=[],P=[],yb={},zb=4;function Q(a){Ab||=a}
var Bb=a=>{for(var b=rb++,c=a.length;c<b;c++)a[c]=null;return b},Db=(a,b)=>{a.dc||(a.dc=a.getContext,a.getContext=function(d,e){e=a.dc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.tc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Cb(c,b):0},Cb=(a,b)=>{var c=Bb(xb),d={handle:c,attributes:b,version:b.tc,kc:a};a.canvas&&(a.canvas.Ic=d);xb[c]=d;("undefined"==typeof b.rc||b.rc)&&Eb(d);return c},Eb=a=>{a||=R;if(!a.Gc){a.Gc=!0;var b=a.kc;kb(b);lb(b);mb(b);pb(b);
qb(b);2<=a.version&&(b.qc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.qc)b.qc=b.getExtension("EXT_disjoint_timer_query");b.Hc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}};function Fb(){var a=S.getSupportedExtensions()||[];return a=a.concat(a.map(b=>"GL_"+b))}
for(var Ab,R,Gb=(a,b,c,d,e,h)=>{a={target:I(a),Yb:h,$b:d,ac:(f=event)=>{J(d)(e,0,b)&&f.preventDefault()},Zb:c};G(a)},Hb=(a,b,c,d)=>{Ya||=L(104);return G({target:a,lc:!0,Yb:"wheel",$b:d,ac:(e=event)=>{var h=Ya;fb(h,e,a);B[h+72>>3]=e.deltaX;B[h+80>>3]=e.deltaY;B[h+88>>3]=e.deltaZ;z[h+96>>2]=e.deltaMode;J(d)(9,h,b)&&e.preventDefault()},Zb:c})},Ib=["default","low-power","high-performance"],T=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=S[c](),f=h&&Bb(d);h?(h.name=f,d[f]=h):Q(1282);z[b+4*e>>2]=f}},Jb=(a,b)=>
{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>R.version){Q(1282);return}c=2*(S.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>R.version){Q(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Q(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:Q(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)z[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Q(1280);w(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:Q(1280);w(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}z[b>>2]=c}else Q(1281)},Kb=a=>
{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Lb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Mb=[],U=a=>{a-=5120;return 0==a?na:1==a?y:2==a?oa:4==a?z:6==a?A:5==a||28922==a||28520==a||30779==a||30782==a?qa:pa},Nb=(a,b,c,d,e)=>{a=U(a);var h=31-Math.clz32(a.BYTES_PER_ELEMENT),f=zb;return a.subarray(e>>h,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<h)+f-1&-f)>>h)},V=a=>{var b=S.Dc;if(b){var c=
b.fc[a];"number"==typeof c&&(b.fc[a]=c=S.getUniformLocation(b,b.Bc[a]+(0<c?`[${c}]`:"")));return c}Q(1282)},W=[],X=[],Ob=a=>{Ga||(g.onExit?.(a),ma=!0);k(a,new ja(a))},Qb=a=>{var b=Kb(a)+1,c=Pb(b);K(a,c,b);return c},S,Y=0;32>Y;++Y)Mb.push(Array(Y));var Rb=new Float32Array(288);for(Y=0;288>Y;++Y)W[Y]=Rb.subarray(0,Y+1);var Sb=new Int32Array(288);for(Y=0;288>Y;++Y)X[Y]=Sb.subarray(0,Y+1);
var cc={i:()=>{ka("")},aa:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ba:(a,b,c)=>{a=I(a);if(!a)return-4;a=ab(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},Va:(a,b,c)=>y.copyWithin(a,b,b+c),Ra:(a,b)=>{function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ua:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-
la.buffer.byteLength+65535)/65536;try{la.grow(e);ra();var h=1;break a}catch(f){}h=void 0}if(h)return!0}return!1},K:(a,b,c,d)=>db(a,b,c,d,12,"blur"),$:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},L:(a,b,c,d)=>db(a,b,c,d,13,"focus"),U:(a,b,c,d)=>eb(a,b,c,d,2,"keydown"),S:(a,b,c,d)=>eb(a,b,c,d,1,"keypress"),T:(a,b,c,d)=>eb(a,b,c,d,3,"keyup"),_:(a,b,c,d)=>M(a,b,c,d,5,"mousedown"),X:(a,b,c,d)=>M(a,b,c,d,33,"mouseenter"),W:(a,b,c,d)=>M(a,b,c,d,34,"mouseleave"),Y:(a,b,c,d)=>M(a,b,c,d,8,
"mousemove"),Z:(a,b,c,d)=>M(a,b,c,d,6,"mouseup"),N:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.dc||document.body.oc||document.body.nc))return-1;a=I(a);if(!a)return-4;gb(a,b,c,d,"mozpointerlockchange");gb(a,b,c,d,"webkitpointerlockchange");gb(a,b,c,d,"mspointerlockchange");return gb(a,b,c,d,"pointerlockchange")},M:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.dc||document.body.oc||document.body.nc))return-1;a=I(a);if(!a)return-4;
hb(a,b,c,d,"mozpointerlockerror");hb(a,b,c,d,"webkitpointerlockerror");hb(a,b,c,d,"mspointerlockerror");return hb(a,b,c,d,"pointerlockerror")},Ta:(a,b,c,d)=>ib(a,b,c,d),O:(a,b,c,d)=>jb(a,b,c,d,25,"touchcancel"),P:(a,b,c,d)=>jb(a,b,c,d,23,"touchend"),Q:(a,b,c,d)=>jb(a,b,c,d,24,"touchmove"),R:(a,b,c,d)=>jb(a,b,c,d,22,"touchstart"),J:(a,b,c,d)=>{Gb(a,b,c,d,31,"webglcontextlost");return 0},I:(a,b,c,d)=>{Gb(a,b,c,d,32,"webglcontextrestored");return 0},V:(a,b,c,d)=>(a=I(a))?"undefined"!=typeof a.onwheel?
Hb(a,b,c,d):-1:-4,Pa:(a,b)=>{b>>=2;b={alpha:!!z[b],depth:!!z[b+1],stencil:!!z[b+2],antialias:!!z[b+3],premultipliedAlpha:!!z[b+4],preserveDrawingBuffer:!!z[b+5],powerPreference:Ib[z[b+6]],failIfMajorPerformanceCaveat:!!z[b+7],tc:z[b+8],Nc:z[b+9],rc:z[b+10],Fc:z[b+11],Oc:z[b+12],Pc:z[b+13]};a=I(a);return!a||b.Fc?0:Db(a,b)},Na:(a,b)=>{a=xb[a];b=b?H(b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&kb(S);"OES_vertex_array_object"==b&&lb(S);"WEBGL_draw_buffers"==b&&mb(S);"WEBGL_draw_instanced_base_vertex_base_instance"==
b&&pb(S);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&qb(S);"WEBGL_multi_draw"==b&&(S.Hc=S.getExtension("WEBGL_multi_draw"));return!!a.kc.getExtension(b)},Qa:a=>{a>>=2;for(var b=0;14>b;++b)z[a+b]=0;z[a]=z[a+1]=z[a+3]=z[a+4]=z[a+8]=z[a+10]=1},Oa:a=>{R=xb[a];g.Kc=S=R?.kc;return!a||S?0:-5},g:function(a){S.activeTexture(a)},v:(a,b)=>{S.attachShader(N[a],O[b])},b:(a,b)=>{35051==a?S.pc=b:35052==a&&(S.cc=b);S.bindBuffer(a,sb[b])},l:(a,b)=>{S.bindFramebuffer(a,tb[b])},va:(a,b)=>{S.bindRenderbuffer(a,
ub[b])},h:(a,b)=>{S.bindSampler(a,P[b])},a:(a,b)=>{S.bindTexture(a,vb[b])},E:a=>{S.bindVertexArray(wb[a])},A:function(a,b,c,d){S.blendColor(a,b,c,d)},B:function(a,b){S.blendEquationSeparate(a,b)},C:function(a,b,c,d){S.blendFuncSeparate(a,b,c,d)},Za:function(a,b,c,d,e,h,f,m,n,p){S.blitFramebuffer(a,b,c,d,e,h,f,m,n,p)},za:(a,b,c,d)=>{2<=R.version?c&&b?S.bufferData(a,y,d,c,b):S.bufferData(a,b,d):S.bufferData(a,c?y.subarray(c,c+b):b,d)},xa:(a,b,c,d)=>{2<=R.version?c&&S.bufferSubData(a,b,y,d,c):S.bufferSubData(a,
b,y.subarray(d,d+c))},sb:function(a,b,c,d){S.clearBufferfi(a,b,c,d)},ga:(a,b,c)=>{S.clearBufferfv(a,b,A,c>>2)},rb:(a,b,c)=>{S.clearBufferiv(a,b,z,c>>2)},j:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},yb:a=>{S.compileShader(O[a])},ra:(a,b,c,d,e,h,f,m)=>{2<=R.version?S.cc||!f?S.compressedTexImage2D(a,b,c,d,e,h,f,m):S.compressedTexImage2D(a,b,c,d,e,h,y,m,f):S.compressedTexImage2D(a,b,c,d,e,h,m?y.subarray(m,m+f):null)},pa:(a,b,c,d,e,h,f,m,n)=>{S.cc?S.compressedTexImage3D(a,b,c,d,e,h,f,m,n):S.compressedTexImage3D(a,
b,c,d,e,h,f,y,n,m)},la:()=>{var a=Bb(N),b=S.createProgram();b.name=a;b.jc=b.hc=b.ic=0;b.mc=1;N[a]=b;return a},Ab:a=>{var b=Bb(O);O[b]=S.createShader(a);return b},x:function(a){S.cullFace(a)},Ja:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=sb[d];e&&(S.deleteBuffer(e),e.name=0,sb[d]=null,d==S.pc&&(S.pc=0),d==S.cc&&(S.cc=0))}},k:(a,b)=>{for(var c=0;c<a;++c){var d=z[b+4*c>>2],e=tb[d];e&&(S.deleteFramebuffer(e),e.name=0,tb[d]=null)}},F:a=>{if(a){var b=N[a];b?(S.deleteProgram(b),b.name=0,N[a]=null):
Q(1281)}},G:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=ub[d];e&&(S.deleteRenderbuffer(e),e.name=0,ub[d]=null)}},Ha:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=P[d];e&&(S.deleteSampler(e),e.name=0,P[d]=null)}},o:a=>{if(a){var b=O[a];b?(S.deleteShader(b),O[a]=null):Q(1281)}},H:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=vb[d];e&&(S.deleteTexture(e),e.name=0,vb[d]=null)}},Ga:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2];S.deleteVertexArray(wb[d]);wb[d]=null}},s:function(a){S.depthFunc(a)},
r:a=>{S.depthMask(!!a)},d:function(a){S.disable(a)},D:a=>{S.disableVertexAttribArray(a)},$a:(a,b,c)=>{S.drawArrays(a,b,c)},bb:(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},cb:(a,b,c,d)=>{S.drawElements(a,b,c,d)},db:(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},f:function(a){S.enable(a)},ob:a=>{S.enableVertexAttribArray(a)},y:function(a){S.frontFace(a)},Aa:(a,b)=>{T(a,b,"createBuffer",sb)},wa:(a,b)=>{T(a,b,"createRenderbuffer",ub)},ma:(a,b)=>{T(a,b,"createSampler",P)},ta:(a,b)=>{T(a,b,"createTexture",
vb)},Ea:function(a,b){T(a,b,"createVertexArray",wb)},wb:(a,b)=>S.getAttribLocation(N[a],b?H(b):""),c:(a,b)=>Jb(a,b),ja:(a,b,c,d)=>{a=S.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(z[c>>2]=b)},u:(a,b,c)=>{if(c)if(a>=rb)Q(1281);else if(a=N[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),z[c>>2]=a.length+1;else if(35719==b){if(!a.jc)for(b=0;b<S.getProgramParameter(a,35718);++b)a.jc=Math.max(a.jc,S.getActiveUniform(a,b).name.length+1);z[c>>2]=a.jc}else if(35722==
b){if(!a.hc)for(b=0;b<S.getProgramParameter(a,35721);++b)a.hc=Math.max(a.hc,S.getActiveAttrib(a,b).name.length+1);z[c>>2]=a.hc}else if(35381==b){if(!a.ic)for(b=0;b<S.getProgramParameter(a,35382);++b)a.ic=Math.max(a.ic,S.getActiveUniformBlockName(a,b).length+1);z[c>>2]=a.ic}else z[c>>2]=S.getProgramParameter(a,b);else Q(1281)},xb:(a,b,c,d)=>{a=S.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(z[c>>2]=b)},ha:(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(O[a]),null===a&&(a=
"(unknown error)"),z[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(O[a]),z[c>>2]=a?a.length+1:0):z[c>>2]=S.getShaderParameter(O[a],b):Q(1281)},Ka:(a,b)=>{if(2>R.version)return Q(1282),0;var c=yb[a];if(c)return 0>b||b>=c.length?(Q(1281),0):c[b];switch(a){case 7939:return c=Fb().map(d=>{var e=Kb(d)+1,h=L(e);h&&K(d,h,e);return h}),c=yb[a]=c,0>b||b>=c.length?(Q(1281),0):c[b];default:return Q(1280),0}},m:(a,b)=>{b=b?H(b):"";if(a=N[a]){var c=a,d=c.fc,e=c.Cc,h;if(!d)for(c.fc=d={},c.Bc={},h=0;h<S.getProgramParameter(c,
35718);++h){var f=S.getActiveUniform(c,h);var m=f.name;f=f.size;var n=Lb(m);n=0<n?m.slice(0,n):m;var p=c.mc;c.mc+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.Bc[p++]=n}c=a.fc;d=0;e=b;h=Lb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Cc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else Q(1281);return-1},Ya:(a,b,c)=>{for(var d=Mb[b],e=0;e<b;e++)d[e]=z[c+4*e>>2];S.invalidateFramebuffer(a,d)},ka:a=>{a=N[a];S.linkProgram(a);a.fc=0;a.Cc={}},Da:(a,b)=>{3317==a&&(zb=b);
S.pixelStorei(a,b)},z:function(a,b){S.polygonOffset(a,b)},_a:function(a){S.readBuffer(a)},ua:function(a,b,c,d,e){S.renderbufferStorageMultisample(a,b,c,d,e)},w:(a,b,c)=>{S.samplerParameterf(P[a],b,c)},e:(a,b,c)=>{S.samplerParameteri(P[a],b,c)},ub:function(a,b,c,d){S.scissor(a,b,c,d)},zb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=d?z[d+4*h>>2]:-1,m=z[c+4*h>>2];f=m?H(m,0>f?void 0:f):"";e+=f}S.shaderSource(O[a],e)},Ca:function(a,b,c){S.stencilFunc(a,b,c)},fa:function(a,b,c,d){S.stencilFuncSeparate(a,
b,c,d)},p:function(a){S.stencilMask(a)},Ba:function(a,b,c){S.stencilOp(a,b,c)},ea:function(a,b,c,d){S.stencilOpSeparate(a,b,c,d)},qa:(a,b,c,d,e,h,f,m,n)=>{if(2<=R.version)if(S.cc)S.texImage2D(a,b,c,d,e,h,f,m,n);else if(n){var p=U(m);S.texImage2D(a,b,c,d,e,h,f,m,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else S.texImage2D(a,b,c,d,e,h,f,m,null);else S.texImage2D(a,b,c,d,e,h,f,m,n?Nb(m,f,d,e,n):null)},oa:(a,b,c,d,e,h,f,m,n,p)=>{if(S.cc)S.texImage3D(a,b,c,d,e,h,f,m,n,p);else if(p){var t=U(n);S.texImage3D(a,
b,c,d,e,h,f,m,n,t,p>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else S.texImage3D(a,b,c,d,e,h,f,m,n,null)},sa:function(a,b,c){S.texParameteri(a,b,c)},Xa:(a,b,c,d,e,h,f,m,n)=>{if(2<=R.version)if(S.cc)S.texSubImage2D(a,b,c,d,e,h,f,m,n);else if(n){var p=U(m);S.texSubImage2D(a,b,c,d,e,h,f,m,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else S.texSubImage2D(a,b,c,d,e,h,f,m,null);else p=null,n&&(p=Nb(m,f,e,h,n)),S.texSubImage2D(a,b,c,d,e,h,f,m,p)},Wa:(a,b,c,d,e,h,f,m,n,p,t)=>{if(S.cc)S.texSubImage3D(a,b,c,d,e,h,f,
m,n,p,t);else if(t){var u=U(p);S.texSubImage3D(a,b,c,d,e,h,f,m,n,p,u,t>>31-Math.clz32(u.BYTES_PER_ELEMENT))}else S.texSubImage3D(a,b,c,d,e,h,f,m,n,p,null)},nb:(a,b,c)=>{if(2<=R.version)b&&S.uniform1fv(V(a),A,c>>2,b);else{if(288>=b)for(var d=W[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);S.uniform1fv(V(a),d)}},ia:(a,b)=>{S.uniform1i(V(a),b)},ib:(a,b,c)=>{if(2<=R.version)b&&S.uniform1iv(V(a),z,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>
2,c+4*b>>2);S.uniform1iv(V(a),d)}},mb:(a,b,c)=>{if(2<=R.version)b&&S.uniform2fv(V(a),A,c>>2,2*b);else{if(144>=b)for(var d=W[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);S.uniform2fv(V(a),d)}},hb:(a,b,c)=>{if(2<=R.version)b&&S.uniform2iv(V(a),z,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);S.uniform2iv(V(a),d)}},kb:(a,b,c)=>{if(2<=R.version)b&&S.uniform3fv(V(a),A,
c>>2,3*b);else{if(96>=b)for(var d=W[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);S.uniform3fv(V(a),d)}},gb:(a,b,c)=>{if(2<=R.version)b&&S.uniform3iv(V(a),z,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);S.uniform3iv(V(a),d)}},jb:(a,b,c)=>{if(2<=R.version)b&&S.uniform4fv(V(a),A,c>>2,4*b);else{if(72>=b){var d=W[4*b-1],e=
A;c>>=2;for(var h=0;h<4*b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=A.subarray(c>>2,c+16*b>>2);S.uniform4fv(V(a),d)}},fb:(a,b,c)=>{if(2<=R.version)b&&S.uniform4iv(V(a),z,c>>2,4*b);else{if(72>=b)for(var d=X[4*b-1],e=0;e<4*b;e+=4)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2],d[e+3]=z[c+(4*e+12)>>2];else d=z.subarray(c>>2,c+16*b>>2);S.uniform4iv(V(a),d)}},eb:(a,b,c,d)=>{if(2<=R.version)b&&S.uniformMatrix4fv(V(a),!!c,A,d>>2,16*b);else{if(18>=b){var e=
W[16*b-1],h=A;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=h[m];e[f+1]=h[m+1];e[f+2]=h[m+2];e[f+3]=h[m+3];e[f+4]=h[m+4];e[f+5]=h[m+5];e[f+6]=h[m+6];e[f+7]=h[m+7];e[f+8]=h[m+8];e[f+9]=h[m+9];e[f+10]=h[m+10];e[f+11]=h[m+11];e[f+12]=h[m+12];e[f+13]=h[m+13];e[f+14]=h[m+14];e[f+15]=h[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(V(a),!!c,e)}},n:a=>{a=N[a];S.useProgram(a);S.Dc=a},pb:(a,b)=>{S.vertexAttribDivisor(a,b)},qb:(a,b,c,d,e,h)=>{S.vertexAttribPointer(a,b,c,!!d,e,h)},vb:function(a,
b,c,d){S.viewport(a,b,c,d)},Db:function(){g.vc=a=>{0!=Tb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.vc)},Sa:function(){g.Ac=a=>{const b=a.clipboardData.getData("text");Ja(()=>{const c=Qb(b);Ub(c)})};window.addEventListener("paste",g.Ac)},La:function(a){g.Qc=[];a=a?H(a):"";a=document.getElementById(a);g.wc=b=>{b.stopPropagation();b.preventDefault()};g.xc=b=>{b.stopPropagation();b.preventDefault()};g.yc=b=>{b.stopPropagation();b.preventDefault()};g.zc=b=>{b.stopPropagation();
b.preventDefault();const c=b.dataTransfer.files;g.Rc=c;Vb(c.length);for(let e=0;e<c.length;e++)Ja(()=>{const h=Qb(c[e].name);Wb(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Xb(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.wc,!1);a.addEventListener("dragleave",g.xc,!1);a.addEventListener("dragover",g.yc,!1);a.addEventListener("drop",g.zc,!1)},ya:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Fa:function(a){a=
a?H(a):"";g.ec=document.getElementById(a);g.ec||console.log("sokol_app.h: invalid target:"+a);g.ec.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Cb:function(){window.removeEventListener("beforeunload",g.vc)},Ma:function(){window.removeEventListener("paste",g.Ac)},Ia:function(a){a=a?H(a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.wc);a.removeEventListener("dragleave",g.xc);a.removeEventListener("dragover",g.yc);a.removeEventListener("drop",
g.zc)},q:function(){g.ec&&g.ec.requestPointerLock&&g.ec.requestPointerLock()},na:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(y.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},ab:function(){return g.bc?g.bc.bufferSize:0},Bb:function(a,b,c){g.Xb=null;g.bc=null;"undefined"!==typeof AudioContext?
g.Xb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.Xb=null,console.log("sokol_audio.h: no WebAudio support"));return g.Xb?(console.log("sokol_audio.h: sample rate ",g.Xb.sampleRate),g.bc=g.Xb.createScriptProcessor(c,0,b),g.bc.onaudioprocess=d=>{const e=d.outputBuffer.length,h=Yb(e);if(h){const f=d.outputBuffer.numberOfChannels;for(let m=0;m<f;m++){const n=d.outputBuffer.getChannelData(m);for(let p=0;p<e;p++)n[p]=A[(h>>2)+(f*p+m)]}}},g.bc.connect(g.Xb.destination),a=()=>{g.Xb&&"suspended"===
g.Xb.state&&g.Xb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},lb:function(){return g.Xb?g.Xb.sampleRate:0},tb:function(){const a=g.Xb;null!==a&&(g.bc&&g.bc.disconnect(),a.close(),g.Xb=null,g.bc=null)},t:function(a,b,c,d,e,h){b=b?H(b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const m=0<d;m&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=
function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!m){const n=new Uint8Array(f.response),p=n.length;p<=h?(y.set(n,e),Zb(a,d,p)):$b(a)}else ac(a,f.status)};f.send()},da:function(a,b){b=b?H(b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");bc(a,d)}else ac(a,c.status)};c.send()},ca:function(a,b){b=b?H(b):"";switch(a){case 0:console.error(b);
break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;la=Z.Eb;ra();cb=Z.Tb;ta.unshift(Z.Fb);C--;g.monitorRunDependencies?.(C);0==C&&(null!==ya&&(clearInterval(ya),ya=null),D&&(c=D,D=null,c()));return Z}var b={a:cc};C++;g.monitorRunDependencies?.(C);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return w(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ea(b,function(c){a(c.instance)});return{}}(),
L=a=>(L=Z.Gb)(a),Ub=g.__sapp_emsc_onpaste=a=>(Ub=g.__sapp_emsc_onpaste=Z.Hb)(a),Tb=g.__sapp_html5_get_ask_leave_site=()=>(Tb=g.__sapp_html5_get_ask_leave_site=Z.Ib)(),Vb=g.__sapp_emsc_begin_drop=a=>(Vb=g.__sapp_emsc_begin_drop=Z.Jb)(a),Wb=g.__sapp_emsc_drop=(a,b)=>(Wb=g.__sapp_emsc_drop=Z.Kb)(a,b),Xb=g.__sapp_emsc_end_drop=(a,b,c)=>(Xb=g.__sapp_emsc_end_drop=Z.Lb)(a,b,c);g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,f,m)=>(g.__sapp_emsc_invoke_fetch_cb=Z.Mb)(a,b,c,d,e,h,f,m);
var dc=g._main=(a,b)=>(dc=g._main=Z.Nb)(a,b),Yb=g.__saudio_emsc_pull=a=>(Yb=g.__saudio_emsc_pull=Z.Ob)(a),bc=g.__sfetch_emsc_head_response=(a,b)=>(bc=g.__sfetch_emsc_head_response=Z.Pb)(a,b),Zb=g.__sfetch_emsc_get_response=(a,b,c)=>(Zb=g.__sfetch_emsc_get_response=Z.Qb)(a,b,c),ac=g.__sfetch_emsc_failed_http_status=(a,b)=>(ac=g.__sfetch_emsc_failed_http_status=Z.Rb)(a,b),$b=g.__sfetch_emsc_failed_buffer_too_small=a=>($b=g.__sfetch_emsc_failed_buffer_too_small=Z.Sb)(a),Ha=()=>(Ha=Z.Ub)(),Ia=a=>(Ia=
Z.Vb)(a),Pb=a=>(Pb=Z.Wb)(a);g.___start_em_js=14648;g.___stop_em_js=23869;var ec;D=function fc(){ec||gc();ec||(D=fc)};function hc(a=[]){var b=dc;a.unshift(ca);var c=a.length,d=Pb(4*(c+1)),e=d;a.forEach(f=>{qa[e>>2]=Qb(f);e+=4});qa[e>>2]=0;try{var h=b(c,d);Ob(h)}catch(f){f instanceof ja||"unwind"==f||k(1,f)}}
function gc(){var a=ba;function b(){if(!ec&&(ec=!0,g.calledRun=!0,!ma)){Fa(ta);Fa(ua);if(g.onRuntimeInitialized)g.onRuntimeInitialized();ic&&hc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();wa.unshift(c)}Fa(wa)}}if(!(0<C)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)xa();Fa(sa);0<C||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var ic=!0;g.noInitialRun&&(ic=!1);gc();
