var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},h),ba=[],ca="./this.program",k=(a,b)=>{throw b;},da="object"==typeof window,m="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,t,ha;
if(ea){var fs=require("fs"),ia=require("path");q=m?ia.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=ja(a)?new URL(a):ia.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ha=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};t=(a,b,c,d=!0)=>{a=ja(a)?new URL(a):ia.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,g)=>{e?c(e):b(d?g.buffer:g)})};!h.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof ka||a.context instanceof ka))throw a;});k=(a,b)=>{process.exitCode=a;throw b;};h.inspect=()=>"[Emscripten Module object]"}else if(da||m)m?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);
b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),t=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var la=h.print||console.log.bind(console),u=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);h.quit&&(k=h.quit);var v;h.wasmBinary&&(v=h.wasmBinary);
"object"!=typeof WebAssembly&&ma("no native wasm support detected");var na,oa=!1,pa,x,qa,ra,y,z,A,B;function sa(){var a=na.buffer;h.HEAP8=pa=new Int8Array(a);h.HEAP16=qa=new Int16Array(a);h.HEAPU8=x=new Uint8Array(a);h.HEAPU16=ra=new Uint16Array(a);h.HEAP32=y=new Int32Array(a);h.HEAPU32=z=new Uint32Array(a);h.HEAPF32=A=new Float32Array(a);h.HEAPF64=B=new Float64Array(a)}var ta=[],ua=[],va=[],wa=[],xa=[];function ya(){var a=h.preRun.shift();ta.unshift(a)}var C=0,za=null,D=null;
function ma(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";u(a);oa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Aa=a=>a.startsWith("data:application/octet-stream;base64,"),ja=a=>a.startsWith("file://"),E;E="plmpeg-sapp-ui.wasm";if(!Aa(E)){var Ba=E;E=h.locateFile?h.locateFile(Ba,q):q+Ba}function Ca(a){if(a==E&&v)return new Uint8Array(v);if(ha)return ha(a);throw"both async and sync fetching of the wasm failed";}
function Da(a){if(!v&&(da||m)){if("function"==typeof fetch&&!ja(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ca(a));if(t)return new Promise((b,c)=>{t(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ca(a))}function Ea(a,b,c){return Da(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{u(`failed to asynchronously prepare wasm: ${d}`);ma(d)})}
function Fa(a,b){var c=E;v||"function"!=typeof WebAssembly.instantiateStreaming||Aa(c)||ja(c)||ea||"function"!=typeof fetch?Ea(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){u(`wasm streaming compile failed: ${e}`);u("falling back to ArrayBuffer instantiation");return Ea(c,a,b)}))}function ka(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ga=a=>{for(;0<a.length;)a.shift()(h)},Ha=h.noExitRuntime||!0,Ia="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ia)return Ia.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},La=a=>{var b=Ja();a();Ka(b)},Ma=0;function Na(){for(var a=G.length-1;0<=a;--a)Oa(a);G=[];Pa=[]}var Pa=[];function Qa(){if(navigator.userActivation?navigator.userActivation.isActive:Ma&&Ra.sc)for(var a=0;a<Pa.length;++a){var b=Pa[a];Pa.splice(a,1);--a;b.cd.apply(null,b.Uc)}}var G=[];function Oa(a){var b=G[a];b.target.removeEventListener(b.jc,b.Pc,b.kc);G.splice(a,1)}
function H(a){function b(d){++Ma;Ra=a;Qa();a.mc(d);Qa();--Ma}if(!a.target)return-4;if(a.lc)a.Pc=b,a.target.addEventListener(a.jc,b,a.kc),G.push(a),Sa||(wa.push(Na),Sa=!0);else for(var c=0;c<G.length;++c)G[c].target==a.target&&G[c].jc==a.jc&&Oa(c--);return 0}function Ta(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Sa,Ra,Ua,Va,Wa,Xa,Ya,Za,$a,ab=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],I=a=>{a=2<a?a?F(x,a):"":a;return ab[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},bb=a=>0>ab.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},cb=[],db,J=a=>{var b=cb[a];b||(a>=cb.length&&(cb.length=a+1),cb[a]=b=db.get(a));return b},K=(a,b,c)=>{var d=x;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var l=
a.charCodeAt(++g);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},eb=(a,b,c,d,e,g)=>{Ua||(Ua=L(256));a={target:I(a),jc:g,lc:d,mc:(f=event)=>{var l=f.target.id?f.target.id:"",n=Ua;K(Ta(f.target),n+0,128);K(l,n+128,128);J(d)(e,n,b)&&f.preventDefault()},kc:c};return H(a)},fb=
(a,b,c,d,e,g)=>{Va||(Va=L(176));a={target:I(a),sc:!0,jc:g,lc:d,mc:f=>{var l=Va;B[l>>3]=f.timeStamp;var n=l>>2;y[n+2]=f.location;y[n+3]=f.ctrlKey;y[n+4]=f.shiftKey;y[n+5]=f.altKey;y[n+6]=f.metaKey;y[n+7]=f.repeat;y[n+8]=f.charCode;y[n+9]=f.keyCode;y[n+10]=f.which;K(f.key||"",l+44,32);K(f.code||"",l+76,32);K(f.char||"",l+108,32);K(f.locale||"",l+140,32);J(d)(e,l,b)&&f.preventDefault()},kc:c};return H(a)},gb=(a,b,c)=>{B[a>>3]=b.timeStamp;a>>=2;y[a+2]=b.screenX;y[a+3]=b.screenY;y[a+4]=b.clientX;y[a+5]=
b.clientY;y[a+6]=b.ctrlKey;y[a+7]=b.shiftKey;y[a+8]=b.altKey;y[a+9]=b.metaKey;qa[2*a+20]=b.button;qa[2*a+21]=b.buttons;y[a+11]=b.movementX;y[a+12]=b.movementY;c=bb(c);y[a+13]=b.clientX-c.left;y[a+14]=b.clientY-c.top},M=(a,b,c,d,e,g)=>{Wa||(Wa=L(72));a=I(a);return H({target:a,sc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,jc:g,lc:d,mc:(f=event)=>{gb(Wa,f,a);J(d)(e,Wa,b)&&f.preventDefault()},kc:c})},hb=(a,b,c,d,e)=>{Xa||(Xa=L(260));return H({target:a,jc:e,lc:d,mc:(g=event)=>{var f=Xa,l=document.pointerLockElement||
document.qc||document.Dc||document.Cc;y[f>>2]=!!l;var n=l&&l.id?l.id:"";K(Ta(l),f+4,128);K(n,f+132,128);J(d)(20,f,b)&&g.preventDefault()},kc:c})},ib=(a,b,c,d,e)=>H({target:a,jc:e,lc:d,mc:(g=event)=>{J(d)(38,0,b)&&g.preventDefault()},kc:c}),jb=(a,b,c,d)=>{Ya||(Ya=L(36));a=I(a);return H({target:a,jc:"resize",lc:d,mc:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=Ya;y[f>>2]=e.detail;y[f+4>>2]=g.clientWidth;y[f+8>>2]=g.clientHeight;y[f+12>>2]=innerWidth;y[f+16>>2]=innerHeight;y[f+20>>2]=
outerWidth;y[f+24>>2]=outerHeight;y[f+28>>2]=pageXOffset;y[f+32>>2]=pageYOffset;J(d)(10,f,b)&&e.preventDefault()}}},kc:c})},kb=(a,b,c,d,e,g)=>{Za||(Za=L(1696));a=I(a);return H({target:a,sc:"touchstart"==g||"touchend"==g,jc:g,lc:d,mc:f=>{for(var l,n={},p=f.touches,r=0;r<p.length;++r)l=p[r],l.Bc=l.Fc=0,n[l.identifier]=l;for(r=0;r<f.changedTouches.length;++r)l=f.changedTouches[r],l.Bc=1,n[l.identifier]=l;for(r=0;r<f.targetTouches.length;++r)n[f.targetTouches[r].identifier].Fc=1;p=Za;B[p>>3]=f.timeStamp;
var w=p>>2;y[w+3]=f.ctrlKey;y[w+4]=f.shiftKey;y[w+5]=f.altKey;y[w+6]=f.metaKey;w+=7;var nb=bb(a),ob=0;for(r in n)if(l=n[r],y[w]=l.identifier,y[w+1]=l.screenX,y[w+2]=l.screenY,y[w+3]=l.clientX,y[w+4]=l.clientY,y[w+5]=l.pageX,y[w+6]=l.pageY,y[w+7]=l.Bc,y[w+8]=l.Fc,y[w+9]=l.clientX-nb.left,y[w+10]=l.clientY-nb.top,w+=13,31<++ob)break;y[p+8>>2]=ob;J(d)(e,p,b)&&f.preventDefault()},kc:c})},lb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,
d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},mb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},pb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},qb=a=>
{a.Wc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},rb=a=>{a.Xc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},sb=1,tb=[],N=[],ub=[],vb=[],wb=[],O=[],xb=[],yb=[],P=[],zb={},Ab=4;function Q(a){Bb||(Bb=a)}
for(var Cb=a=>{for(var b=sb++,c=a.length;c<b;c++)a[c]=null;return b},Eb=(a,b)=>{a.qc||(a.qc=a.getContext,a.getContext=function(d,e){e=a.qc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Ec?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Db(c,b):0},Db=(a,b)=>{var c=Cb(yb),d={handle:c,attributes:b,version:b.Ec,wc:a};a.canvas&&(a.canvas.Tc=d);yb[c]=d;("undefined"==typeof b.Ac||b.Ac)&&Fb(d);return c},Fb=a=>{a||(a=R);if(!a.Rc){a.Rc=!0;var b=a.wc;lb(b);mb(b);pb(b);
qb(b);rb(b);2<=a.version&&(b.zc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.zc)b.zc=b.getExtension("EXT_disjoint_timer_query");b.Sc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},Bb,R,Gb=(a,b,c,d,e,g)=>{a={target:I(a),jc:g,lc:d,mc:(f=event)=>{J(d)(e,0,b)&&f.preventDefault()},kc:c};H(a)},Hb=(a,b,c,d)=>{$a||($a=L(104));return H({target:a,sc:!0,jc:"wheel",lc:d,mc:(e=event)=>
{var g=$a;gb(g,e,a);B[g+72>>3]=e.deltaX;B[g+80>>3]=e.deltaY;B[g+88>>3]=e.deltaZ;y[g+96>>2]=e.deltaMode;J(d)(9,g,b)&&e.preventDefault()},kc:c})},Ib=["default","low-power","high-performance"],Jb=[null,[],[]],T=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=S[c](),f=g&&Cb(d);g?(g.name=f,d[f]=g):Q(1282);y[b+4*e>>2]=f}},Kb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>R.version){Q(1282);
return}c=2*(S.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>R.version){Q(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Q(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:Q(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)y[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Q(1280);u("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:Q(1280);u("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}y[b>>2]=c}else Q(1281)},Lb=a=>{for(var b=
0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Mb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Nb=[],U=a=>{a-=5120;return 0==a?pa:1==a?x:2==a?qa:4==a?y:6==a?A:5==a||28922==a||28520==a||30779==a||30782==a?z:ra},Ob=(a,b,c,d,e)=>{a=U(a);var g=31-Math.clz32(a.BYTES_PER_ELEMENT),f=Ab;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<g)+f-1&-f)>>g)},V=a=>{var b=S.Oc;if(b){var c=b.rc[a];
"number"==typeof c&&(b.rc[a]=c=S.getUniformLocation(b,b.Mc[a]+(0<c?"["+c+"]":"")));return c}Q(1282)},W=[],X=[],Pb=a=>{if(!Ha){if(h.onExit)h.onExit(a);oa=!0}k(a,new ka(a))},Rb=a=>{var b=Lb(a)+1,c=Qb(b);K(a,c,b);return c},S,Y=0;32>Y;++Y)Nb.push(Array(Y));var Sb=new Float32Array(288);for(Y=0;288>Y;++Y)W[Y]=Sb.subarray(0,Y+1);var Tb=new Int32Array(288);for(Y=0;288>Y;++Y)X[Y]=Tb.subarray(0,Y+1);
var ec={la:function(){return 0},hb:function(){return 0},ib:function(){},g:()=>{ma("")},ga:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ha:(a,b,c)=>{a=I(a);if(!a)return-4;a=bb(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},eb:(a,b,c)=>x.copyWithin(a,b,b+c),Ya:(a,b)=>{function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},db:a=>{var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,
d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-na.buffer.byteLength+65535)/65536;try{na.grow(e);sa();var g=1;break a}catch(f){}g=void 0}if(g)return!0}return!1},Q:(a,b,c,d)=>eb(a,b,c,d,12,"blur"),fa:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},R:(a,b,c,d)=>eb(a,b,c,d,13,"focus"),_:(a,b,c,d)=>fb(a,b,c,d,2,"keydown"),Y:(a,b,c,d)=>fb(a,b,c,d,1,"keypress"),Z:(a,b,c,d)=>fb(a,b,c,d,3,"keyup"),ea:(a,b,c,d)=>M(a,b,c,d,5,"mousedown"),ba:(a,b,c,d)=>M(a,b,c,d,33,"mouseenter"),aa:(a,
b,c,d)=>M(a,b,c,d,34,"mouseleave"),ca:(a,b,c,d)=>M(a,b,c,d,8,"mousemove"),da:(a,b,c,d)=>M(a,b,c,d,6,"mouseup"),T:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.qc||document.body.Dc||document.body.Cc))return-1;a=I(a);if(!a)return-4;hb(a,b,c,d,"mozpointerlockchange");hb(a,b,c,d,"webkitpointerlockchange");hb(a,b,c,d,"mspointerlockchange");return hb(a,b,c,d,"pointerlockchange")},S:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.qc||
document.body.Dc||document.body.Cc))return-1;a=I(a);if(!a)return-4;ib(a,b,c,d,"mozpointerlockerror");ib(a,b,c,d,"webkitpointerlockerror");ib(a,b,c,d,"mspointerlockerror");return ib(a,b,c,d,"pointerlockerror")},Za:(a,b,c,d)=>jb(a,b,c,d),U:(a,b,c,d)=>kb(a,b,c,d,25,"touchcancel"),V:(a,b,c,d)=>kb(a,b,c,d,23,"touchend"),W:(a,b,c,d)=>kb(a,b,c,d,24,"touchmove"),X:(a,b,c,d)=>kb(a,b,c,d,22,"touchstart"),P:(a,b,c,d)=>{Gb(a,b,c,d,31,"webglcontextlost");return 0},O:(a,b,c,d)=>{Gb(a,b,c,d,32,"webglcontextrestored");
return 0},$:(a,b,c,d)=>(a=I(a))?"undefined"!=typeof a.onwheel?Hb(a,b,c,d):-1:-4,Wa:(a,b)=>{b>>=2;b={alpha:!!y[b],depth:!!y[b+1],stencil:!!y[b+2],antialias:!!y[b+3],premultipliedAlpha:!!y[b+4],preserveDrawingBuffer:!!y[b+5],powerPreference:Ib[y[b+6]],failIfMajorPerformanceCaveat:!!y[b+7],Ec:y[b+8],Yc:y[b+9],Ac:y[b+10],Qc:y[b+11],Zc:y[b+12],$c:y[b+13]};a=I(a);return!a||b.Qc?0:Eb(a,b)},Ta:(a,b)=>{a=yb[a];b=b?F(x,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&lb(S);"OES_vertex_array_object"==
b&&mb(S);"WEBGL_draw_buffers"==b&&pb(S);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&qb(S);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&rb(S);"WEBGL_multi_draw"==b&&(S.Sc=S.getExtension("WEBGL_multi_draw"));return!!a.wc.getExtension(b)},Xa:a=>{a>>=2;for(var b=0;14>b;++b)y[a+b]=0;y[a]=y[a+1]=y[a+3]=y[a+4]=y[a+8]=y[a+10]=1},Ua:a=>{R=yb[a];h.Vc=S=R&&R.wc;return!a||S?0:-5},ka:()=>52,gb:()=>52,cb:function(){return 70},fb:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=z[b>>2],l=z[b+4>>
2];b+=8;for(var n=0;n<l;n++){var p=x[f+n],r=Jb[a];0===p||10===p?((1===a?la:u)(F(r,0)),r.length=0):r.push(p)}e+=l}z[d>>2]=e;return 0},h:function(a){S.activeTexture(a)},B:(a,b)=>{S.attachShader(N[a],O[b])},a:(a,b)=>{35051==a?S.yc=b:35052==a&&(S.oc=b);S.bindBuffer(a,tb[b])},m:(a,b)=>{S.bindFramebuffer(a,ub[b])},Da:(a,b)=>{S.bindRenderbuffer(a,vb[b])},i:(a,b)=>{S.bindSampler(a,P[b])},b:(a,b)=>{S.bindTexture(a,wb[b])},K:a=>{S.bindVertexArray(xb[a])},G:function(a,b,c,d){S.blendColor(a,b,c,d)},H:function(a,
b){S.blendEquationSeparate(a,b)},I:function(a,b,c,d){S.blendFuncSeparate(a,b,c,d)},nb:function(a,b,c,d,e,g,f,l,n,p){S.blitFramebuffer(a,b,c,d,e,g,f,l,n,p)},Fa:(a,b,c,d)=>{2<=R.version?c&&b?S.bufferData(a,x,d,c,b):S.bufferData(a,b,d):S.bufferData(a,c?x.subarray(c,c+b):b,d)},n:(a,b,c,d)=>{2<=R.version?c&&S.bufferSubData(a,b,x,d,c):S.bufferSubData(a,b,x.subarray(d,d+c))},Ib:function(a,b,c,d){S.clearBufferfi(a,b,c,d)},pa:(a,b,c)=>{S.clearBufferfv(a,b,A,c>>2)},Hb:(a,b,c)=>{S.clearBufferiv(a,b,y,c>>2)},
j:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},Lb:a=>{S.compileShader(O[a])},za:(a,b,c,d,e,g,f,l)=>{2<=R.version?S.oc||!f?S.compressedTexImage2D(a,b,c,d,e,g,f,l):S.compressedTexImage2D(a,b,c,d,e,g,x,l,f):S.compressedTexImage2D(a,b,c,d,e,g,l?x.subarray(l,l+f):null)},xa:(a,b,c,d,e,g,f,l,n)=>{S.oc?S.compressedTexImage3D(a,b,c,d,e,g,f,l,n):S.compressedTexImage3D(a,b,c,d,e,g,f,x,n,l)},ua:()=>{var a=Cb(N),b=S.createProgram();b.name=a;b.vc=b.tc=b.uc=0;b.xc=1;N[a]=b;return a},Nb:a=>{var b=Cb(O);O[b]=S.createShader(a);
return b},D:function(a){S.cullFace(a)},Pa:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=tb[d];e&&(S.deleteBuffer(e),e.name=0,tb[d]=null,d==S.yc&&(S.yc=0),d==S.oc&&(S.oc=0))}},k:(a,b)=>{for(var c=0;c<a;++c){var d=y[b+4*c>>2],e=ub[d];e&&(S.deleteFramebuffer(e),e.name=0,ub[d]=null)}},x:a=>{if(a){var b=N[a];b?(S.deleteProgram(b),b.name=0,N[a]=null):Q(1281)}},M:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=vb[d];e&&(S.deleteRenderbuffer(e),e.name=0,vb[d]=null)}},L:(a,b)=>{for(var c=0;c<a;c++){var d=
y[b+4*c>>2],e=P[d];e&&(S.deleteSampler(e),e.name=0,P[d]=null)}},A:a=>{if(a){var b=O[a];b?(S.deleteShader(b),O[a]=null):Q(1281)}},N:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=wb[d];e&&(S.deleteTexture(e),e.name=0,wb[d]=null)}},Na:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2];S.deleteVertexArray(xb[d]);xb[d]=null}},w:function(a){S.depthFunc(a)},v:a=>{S.depthMask(!!a)},d:function(a){S.disable(a)},J:a=>{S.disableVertexAttribArray(a)},pb:(a,b,c)=>{S.drawArrays(a,b,c)},qb:(a,b,c,d)=>{S.drawArraysInstanced(a,
b,c,d)},rb:(a,b,c,d)=>{S.drawElements(a,b,c,d)},sb:(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},f:function(a){S.enable(a)},Db:a=>{S.enableVertexAttribArray(a)},E:function(a){S.frontFace(a)},Ga:(a,b)=>{T(a,b,"createBuffer",tb)},Ea:(a,b)=>{T(a,b,"createRenderbuffer",vb)},va:(a,b)=>{T(a,b,"createSampler",P)},Ba:(a,b)=>{T(a,b,"createTexture",wb)},Ma:function(a,b){T(a,b,"createVertexArray",xb)},Jb:(a,b)=>S.getAttribLocation(N[a],b?F(x,b):""),c:(a,b)=>{Kb(a,b)},Ob:(a,b,c,d)=>{a=S.getProgramInfoLog(N[a]);
null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(y[c>>2]=b)},sa:(a,b,c)=>{if(c)if(a>=sb)Q(1281);else if(a=N[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b){if(!a.vc)for(b=0;b<S.getProgramParameter(a,35718);++b)a.vc=Math.max(a.vc,S.getActiveUniform(a,b).name.length+1);y[c>>2]=a.vc}else if(35722==b){if(!a.tc)for(b=0;b<S.getProgramParameter(a,35721);++b)a.tc=Math.max(a.tc,S.getActiveAttrib(a,b).name.length+1);y[c>>2]=a.tc}else if(35381==
b){if(!a.uc)for(b=0;b<S.getProgramParameter(a,35382);++b)a.uc=Math.max(a.uc,S.getActiveUniformBlockName(a,b).length+1);y[c>>2]=a.uc}else y[c>>2]=S.getProgramParameter(a,b);else Q(1281)},Kb:(a,b,c,d)=>{a=S.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(y[c>>2]=b)},qa:(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),y[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(O[a]),y[c>>2]=a?a.length+1:0):y[c>>2]=S.getShaderParameter(O[a],b):
Q(1281)},Qa:(a,b)=>{if(2>R.version)return Q(1282),0;var c=zb[a];if(c)return 0>b||b>=c.length?(Q(1281),0):c[b];switch(a){case 7939:return c=S.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){var e=Lb(d)+1,g=L(e);g&&K(d,g,e);return g}),c=zb[a]=c,0>b||b>=c.length?(Q(1281),0):c[b];default:return Q(1280),0}},r:(a,b)=>{b=b?F(x,b):"";if(a=N[a]){var c=a,d=c.rc,e=c.Nc,g;if(!d)for(c.rc=d={},c.Mc={},g=0;g<S.getProgramParameter(c,35718);++g){var f=S.getActiveUniform(c,
g);var l=f.name;f=f.size;var n=Mb(l);n=0<n?l.slice(0,n):l;var p=c.xc;c.xc+=f;e[n]=[f,p];for(l=0;l<f;++l)d[p]=l,c.Mc[p++]=n}c=a.rc;d=0;e=b;g=Mb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Nc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else Q(1281);return-1},mb:(a,b,c)=>{for(var d=Nb[b],e=0;e<b;e++)d[e]=y[c+4*e>>2];S.invalidateFramebuffer(a,d)},ta:a=>{a=N[a];S.linkProgram(a);a.rc=0;a.Nc={}},La:(a,b)=>{3317==a&&(Ab=b);S.pixelStorei(a,b)},F:function(a,b){S.polygonOffset(a,
b)},ob:function(a){S.readBuffer(a)},Ca:function(a,b,c,d,e){S.renderbufferStorageMultisample(a,b,c,d,e)},C:(a,b,c)=>{S.samplerParameterf(P[a],b,c)},e:(a,b,c)=>{S.samplerParameteri(P[a],b,c)},p:function(a,b,c,d){S.scissor(a,b,c,d)},Mb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=d?y[d+4*g>>2]:-1,l=y[c+4*g>>2];f=l?F(x,l,0>f?void 0:f):"";e+=f}S.shaderSource(O[a],e)},Ja:function(a,b,c){S.stencilFunc(a,b,c)},oa:function(a,b,c,d){S.stencilFuncSeparate(a,b,c,d)},u:function(a){S.stencilMask(a)},Ia:function(a,
b,c){S.stencilOp(a,b,c)},na:function(a,b,c,d){S.stencilOpSeparate(a,b,c,d)},ya:(a,b,c,d,e,g,f,l,n)=>{if(2<=R.version)if(S.oc)S.texImage2D(a,b,c,d,e,g,f,l,n);else if(n){var p=U(l);S.texImage2D(a,b,c,d,e,g,f,l,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else S.texImage2D(a,b,c,d,e,g,f,l,null);else S.texImage2D(a,b,c,d,e,g,f,l,n?Ob(l,f,d,e,n):null)},wa:(a,b,c,d,e,g,f,l,n,p)=>{if(S.oc)S.texImage3D(a,b,c,d,e,g,f,l,n,p);else if(p){var r=U(n);S.texImage3D(a,b,c,d,e,g,f,l,n,r,p>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else S.texImage3D(a,
b,c,d,e,g,f,l,n,null)},lb:(a,b,c,d,e,g,f,l,n)=>{if(2<=R.version)if(S.oc)S.texSubImage2D(a,b,c,d,e,g,f,l,n);else if(n){var p=U(l);S.texSubImage2D(a,b,c,d,e,g,f,l,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else S.texSubImage2D(a,b,c,d,e,g,f,l,null);else p=null,n&&(p=Ob(l,f,e,g,n)),S.texSubImage2D(a,b,c,d,e,g,f,l,p)},kb:(a,b,c,d,e,g,f,l,n,p,r)=>{if(S.oc)S.texSubImage3D(a,b,c,d,e,g,f,l,n,p,r);else if(r){var w=U(p);S.texSubImage3D(a,b,c,d,e,g,f,l,n,p,w,r>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else S.texSubImage3D(a,
b,c,d,e,g,f,l,n,p,null)},Cb:(a,b,c)=>{if(2<=R.version)b&&S.uniform1fv(V(a),A,c>>2,b);else{if(288>=b)for(var d=W[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);S.uniform1fv(V(a),d)}},ra:(a,b)=>{S.uniform1i(V(a),b)},yb:(a,b,c)=>{if(2<=R.version)b&&S.uniform1iv(V(a),y,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);S.uniform1iv(V(a),d)}},Bb:(a,b,c)=>{if(2<=R.version)b&&S.uniform2fv(V(a),A,c>>2,2*b);else{if(144>=b)for(var d=W[2*
b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);S.uniform2fv(V(a),d)}},xb:(a,b,c)=>{if(2<=R.version)b&&S.uniform2iv(V(a),y,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);S.uniform2iv(V(a),d)}},Ab:(a,b,c)=>{if(2<=R.version)b&&S.uniform3fv(V(a),A,c>>2,3*b);else{if(96>=b)for(var d=W[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=
A.subarray(c>>2,c+12*b>>2);S.uniform3fv(V(a),d)}},wb:(a,b,c)=>{if(2<=R.version)b&&S.uniform3iv(V(a),y,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);S.uniform3iv(V(a),d)}},zb:(a,b,c)=>{if(2<=R.version)b&&S.uniform4fv(V(a),A,c>>2,4*b);else{if(72>=b){var d=W[4*b-1],e=A;c>>=2;for(var g=0;g<4*b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=A.subarray(c>>2,c+16*b>>2);
S.uniform4fv(V(a),d)}},vb:(a,b,c)=>{if(2<=R.version)b&&S.uniform4iv(V(a),y,c>>2,4*b);else{if(72>=b)for(var d=X[4*b-1],e=0;e<4*b;e+=4)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2],d[e+3]=y[c+(4*e+12)>>2];else d=y.subarray(c>>2,c+16*b>>2);S.uniform4iv(V(a),d)}},tb:(a,b,c,d)=>{if(2<=R.version)b&&S.uniformMatrix4fv(V(a),!!c,A,d>>2,16*b);else{if(18>=b){var e=W[16*b-1],g=A;d>>=2;for(var f=0;f<16*b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=
g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=A.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(V(a),!!c,e)}},l:a=>{a=N[a];S.useProgram(a);S.Oc=a},Eb:(a,b)=>{S.vertexAttribDivisor(a,b)},Gb:(a,b,c,d,e,g)=>{S.vertexAttribPointer(a,b,c,!!d,e,g)},q:function(a,b,c,d){S.viewport(a,b,c,d)},Va:function(){h.Gc=a=>{0!=Ub()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",
h.Gc)},Ra:function(){h.Lc=a=>{const b=a.clipboardData.getData("text");La(()=>{const c=Rb(b);Vb(c)})};window.addEventListener("paste",h.Lc)},Ha:function(a){h.ad=[];a=a?F(x,a):"";a=document.getElementById(a);h.Hc=b=>{b.stopPropagation();b.preventDefault()};h.Ic=b=>{b.stopPropagation();b.preventDefault()};h.Jc=b=>{b.stopPropagation();b.preventDefault()};h.Kc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.bd=c;Wb(c.length);for(let e=0;e<c.length;e++)La(()=>{const g=Rb(c[e].name);
Xb(e,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Yb(b.clientX,b.clientY,d)};a.addEventListener("dragenter",h.Hc,!1);a.addEventListener("dragleave",h.Ic,!1);a.addEventListener("dragover",h.Jc,!1);a.addEventListener("drop",h.Kc,!1)},ub:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},t:function(){const a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",
function(){Zb()});document.body.append(a)},s:function(){document.getElementById("_sokol_app_input_element").focus()},Pb:function(a){a=a?F(x,a):"";h.pc=document.getElementById(a);h.pc||console.log("sokol_app.h: invalid target:"+a);h.pc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Sa:function(){window.removeEventListener("beforeunload",h.Gc)},Oa:function(){window.removeEventListener("paste",h.Lc)},Aa:function(a){a=a?F(x,a):"";a=document.getElementById(a);
a.removeEventListener("dragenter",h.Hc);a.removeEventListener("dragleave",h.Ic);a.removeEventListener("dragover",h.Jc);a.removeEventListener("drop",h.Kc)},z:function(){h.pc&&h.pc.requestPointerLock&&h.pc.requestPointerLock()},Fb:function(a,b){if(h.pc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";
break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.pc.style.cursor=a}},jb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,b);g.data.set(x.subarray(c,c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},o:function(){document.getElementById("_sokol_app_input_element").blur()},Ka:function(a){a=
a?F(x,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},_a:function(){return h.nc?h.nc.bufferSize:0},bb:function(a,b,c){h.ic=null;h.nc=null;"undefined"!==typeof AudioContext?
h.ic=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(h.ic=null,console.log("sokol_audio.h: no WebAudio support"));return h.ic?(console.log("sokol_audio.h: sample rate ",h.ic.sampleRate),h.nc=h.ic.createScriptProcessor(c,0,b),h.nc.onaudioprocess=d=>{const e=d.outputBuffer.length,g=$b(e);if(g){const f=d.outputBuffer.numberOfChannels;for(let l=0;l<f;l++){const n=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)n[p]=A[(g>>2)+(f*p+l)]}}},h.nc.connect(h.ic.destination),a=()=>{h.ic&&"suspended"===
h.ic.state&&h.ic.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},$a:function(){return h.ic?h.ic.sampleRate:0},ab:function(){const a=h.ic;null!==a&&(h.nc&&h.nc.disconnect(),a.close(),h.ic=null,h.nc=null)},y:function(a,b,c,d,e,g){b=b?F(x,b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const l=0<d;l&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=
function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!l){const n=new Uint8Array(f.response),p=n.length;p<=g?(x.set(n,e),ac(a,d,p)):bc(a)}else cc(a,f.status)};f.send()},ja:function(a,b){b=b?F(x,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");dc(a,d)}else cc(a,c.status)};c.send()},ma:function(){return navigator.userAgent.includes("Macintosh")?
1:0},ia:function(a,b){b=b?F(x,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;na=Z.Qb;sa();db=Z.ec;ua.unshift(Z.Rb);C--;h.monitorRunDependencies&&h.monitorRunDependencies(C);0==C&&(null!==za&&(clearInterval(za),za=null),D&&(c=D,D=null,c()));return Z}var b={a:ec};C++;h.monitorRunDependencies&&h.monitorRunDependencies(C);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return u(`Module.instantiateWasm callback failed with error: ${c}`),
!1}Fa(b,function(c){a(c.instance)});return{}}(),L=a=>(L=Z.Sb)(a),Zb=h.__sapp_emsc_notify_keyboard_hidden=()=>(Zb=h.__sapp_emsc_notify_keyboard_hidden=Z.Tb)(),Vb=h.__sapp_emsc_onpaste=a=>(Vb=h.__sapp_emsc_onpaste=Z.Ub)(a),Ub=h.__sapp_html5_get_ask_leave_site=()=>(Ub=h.__sapp_html5_get_ask_leave_site=Z.Vb)(),Wb=h.__sapp_emsc_begin_drop=a=>(Wb=h.__sapp_emsc_begin_drop=Z.Wb)(a),Xb=h.__sapp_emsc_drop=(a,b)=>(Xb=h.__sapp_emsc_drop=Z.Xb)(a,b),Yb=h.__sapp_emsc_end_drop=(a,b,c)=>(Yb=h.__sapp_emsc_end_drop=
Z.Yb)(a,b,c);h.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,g,f,l)=>(h.__sapp_emsc_invoke_fetch_cb=Z.Zb)(a,b,c,d,e,g,f,l);
var fc=h._main=(a,b)=>(fc=h._main=Z._b)(a,b),$b=h.__saudio_emsc_pull=a=>($b=h.__saudio_emsc_pull=Z.$b)(a),dc=h.__sfetch_emsc_head_response=(a,b)=>(dc=h.__sfetch_emsc_head_response=Z.ac)(a,b),ac=h.__sfetch_emsc_get_response=(a,b,c)=>(ac=h.__sfetch_emsc_get_response=Z.bc)(a,b,c),cc=h.__sfetch_emsc_failed_http_status=(a,b)=>(cc=h.__sfetch_emsc_failed_http_status=Z.cc)(a,b),bc=h.__sfetch_emsc_failed_buffer_too_small=a=>(bc=h.__sfetch_emsc_failed_buffer_too_small=Z.dc)(a),Ja=()=>(Ja=Z.fc)(),Ka=a=>(Ka=
Z.gc)(a),Qb=a=>(Qb=Z.hc)(a);h.___start_em_js=51480;h.___stop_em_js=61249;var gc;D=function hc(){gc||ic();gc||(D=hc)};function jc(a=[]){var b=fc;a.unshift(ca);var c=a.length,d=Qb(4*(c+1)),e=d;a.forEach(f=>{z[e>>2]=Rb(f);e+=4});z[e>>2]=0;try{var g=b(c,d);Pb(g)}catch(f){f instanceof ka||"unwind"==f||k(1,f)}}
function ic(){var a=ba;function b(){if(!gc&&(gc=!0,h.calledRun=!0,!oa)){Ga(ua);Ga(va);if(h.onRuntimeInitialized)h.onRuntimeInitialized();kc&&jc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();xa.unshift(c)}Ga(xa)}}if(!(0<C)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ya();Ga(ta);0<C||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},
1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var kc=!0;h.noInitialRun&&(kc=!1);ic();
