
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var h={},k;for(k in e)e.hasOwnProperty(k)&&(h[k]=e[k]);var r=[],aa="./this.program";function t(a,b){throw b;}var ba=!1,u=!1,ca=!1,da=!1;ba="object"===typeof window;u="function"===typeof importScripts;ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;da=!ba&&!ca&&!u;var v="",ea,w,fa,ha;
if(ca)v=u?require("path").dirname(v)+"/":__dirname+"/",ea=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,b?null:"utf8")},w=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),r=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;}),process.on("unhandledRejection",
x),t=function(a){process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(da)"undefined"!=typeof read&&(ea=function(a){return read(a)}),w=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?r=scriptArgs:"undefined"!=typeof arguments&&(r=arguments),"function"===typeof quit&&(t=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ba||u)u?v=self.location.href:"undefined"!==typeof document&&document.currentScript&&(v=document.currentScript.src),v=0!==v.indexOf("blob:")?v.substr(0,v.lastIndexOf("/")+1):"",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(w=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
e.print||console.log.bind(console);var z=e.printErr||console.warn.bind(console);for(k in h)h.hasOwnProperty(k)&&(e[k]=h[k]);h=null;e.arguments&&(r=e.arguments);e.thisProgram&&(aa=e.thisProgram);e.quit&&(t=e.quit);var A;e.wasmBinary&&(A=e.wasmBinary);var noExitRuntime;e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&x("no native wasm support detected");var B,ja=!1;function assert(a,b){a||x("Assertion failed: "+b)}
function ka(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}function la(a,b,c){var d={string:function(m){var q=0;if(null!==m&&void 0!==m&&0!==m){var p=(m.length<<2)+1;q=C(p);D(m,E,q,p)}return q},array:function(m){var q=C(m.length);ma.set(m,q);return q}};a=ka(a);var f=[],l=0;if(c)for(var g=0;g<c.length;g++){var n=d[b[g]];n?(0===l&&(l=na()),f[g]=n(c[g])):f[g]=c[g]}a.apply(null,f);0!==l&&oa(l)}
var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function F(a,b){if(a){var c=E,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&pa)a=pa.decode(c.subarray(a,b));else{for(d="";a<b;){var f=c[a++];if(f&128){var l=c[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|l);else{var g=c[a++]&63;f=224==(f&240)?(f&15)<<12|l<<6|g:(f&7)<<18|l<<12|g<<6|c[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}a=d}}else a="";return a}
function D(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var l=0;l<a.length;++l){var g=a.charCodeAt(l);if(55296<=g&&57343>=g){var n=a.charCodeAt(++l);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}
function qa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ra(a){var b=qa(a)+1,c=C(b);D(a,ma,c,b);return c}var G,ma,E,sa,H,I;
function ta(a){G=a;e.HEAP8=ma=new Int8Array(a);e.HEAP16=sa=new Int16Array(a);e.HEAP32=H=new Int32Array(a);e.HEAPU8=E=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAPU32=new Uint32Array(a);e.HEAPF32=new Float32Array(a);e.HEAPF64=I=new Float64Array(a)}var ua=e.INITIAL_MEMORY||33554432;e.wasmMemory?B=e.wasmMemory:B=new WebAssembly.Memory({initial:ua/65536,maximum:32768});B&&(G=B.buffer);ua=G.byteLength;ta(G);var J,va=[],wa=[],xa=[],ya=[],za=[];
function Aa(){var a=e.preRun.shift();va.unshift(a)}var K=0,Ba=null,L=null;e.preloadedImages={};e.preloadedAudios={};function x(a){if(e.onAbort)e.onAbort(a);z(a);ja=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ca(a){var b=M;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Da(){return Ca("data:application/octet-stream;base64,")}var M="quad-sapp.wasm";if(!Da()){var Ea=M;M=e.locateFile?e.locateFile(Ea,v):v+Ea}
function Fa(){try{if(A)return new Uint8Array(A);if(w)return w(M);throw"both async and sync fetching of the wasm failed";}catch(a){x(a)}}function Ga(){return A||!ba&&!u||"function"!==typeof fetch||Ca("file://")?Promise.resolve().then(Fa):fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Fa()})}
function Ha(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.lc;"number"===typeof c?void 0===b.Tb?J.get(c)():J.get(c)(b.Tb):c(void 0===b.Tb?null:b.Tb)}}}var Ia=0;function Ja(){for(var a=N.length-1;0<=a;--a)Ka(a);N=[];La=[]}var La=[];function Ma(){if(Ia&&Na.Rb)for(var a=0;a<La.length;++a){var b=La[a];La.splice(a,1);--a;b.Cc.apply(null,b.qc)}}var N=[];function Ka(a){var b=N[a];b.target.removeEventListener(b.Kb,b.jc,b.Lb);N.splice(a,1)}
function O(a){function b(d){++Ia;Na=a;Ma();a.Nb(d);Ma();--Ia}if(a.Mb)a.jc=b,a.target.addEventListener(a.Kb,b,a.Lb),N.push(a),Oa||(ya.push(Ja),Oa=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Kb==a.Kb&&Ka(c--)}var Oa,Na,Pa,Qa,Ra,Sa,Ta,Ua,Va=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function P(a){a=2<a?F(a):a;return Va[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Wa(a){return 0>Va.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function Xa(a,b,c,d,f,l){Pa||(Pa=Q(164));a={target:P(a),Rb:!0,Kb:l,Mb:d,Nb:function(g){var n=Pa,m=n>>2;H[m]=g.location;H[m+1]=g.ctrlKey;H[m+2]=g.shiftKey;H[m+3]=g.altKey;H[m+4]=g.metaKey;H[m+5]=g.repeat;H[m+6]=g.charCode;H[m+7]=g.keyCode;H[m+8]=g.which;D(g.key||"",E,n+36,32);D(g.code||"",E,n+68,32);D(g.char||"",E,n+100,32);D(g.locale||"",E,n+132,32);J.get(d)(f,n,b)&&g.preventDefault()},Lb:c};O(a)}
function Ya(a,b,c){a>>=2;H[a]=b.screenX;H[a+1]=b.screenY;H[a+2]=b.clientX;H[a+3]=b.clientY;H[a+4]=b.ctrlKey;H[a+5]=b.shiftKey;H[a+6]=b.altKey;H[a+7]=b.metaKey;sa[2*a+16]=b.button;sa[2*a+17]=b.buttons;H[a+9]=b.movementX;H[a+10]=b.movementY;c=Wa(c);H[a+11]=b.clientX-c.left;H[a+12]=b.clientY-c.top}function R(a,b,c,d,f,l){Qa||(Qa=Q(64));a=P(a);O({target:a,Rb:"mousemove"!=l&&"mouseenter"!=l&&"mouseleave"!=l,Kb:l,Mb:d,Nb:function(g){g=g||event;Ya(Qa,g,a);J.get(d)(f,Qa,b)&&g.preventDefault()},Lb:c})}
function Za(a,b,c,d,f){Ra||(Ra=Q(260));O({target:a,Kb:f,Mb:d,Nb:function(l){l=l||event;var g=Ra,n=document.pointerLockElement||document.Vb||document.Xb||document.Wb;H[g>>2]=!!n;var m=n&&n.id?n.id:"";D(n?n==window?"#window":n==screen?"#screen":n&&n.nodeName?n.nodeName:"":"",E,g+4,128);D(m,E,g+132,128);J.get(d)(20,g,b)&&l.preventDefault()},Lb:c})}function $a(a,b,c,d,f){O({target:a,Kb:f,Mb:d,Nb:function(l){l=l||event;J.get(d)(38,0,b)&&l.preventDefault()},Lb:c})}
function ab(a,b,c,d){Sa||(Sa=Q(36));a=P(a);O({target:a,Kb:"resize",Mb:d,Nb:function(f){f=f||event;if(f.target==a){var l=document.body;if(l){var g=Sa;H[g>>2]=f.detail;H[g+4>>2]=l.clientWidth;H[g+8>>2]=l.clientHeight;H[g+12>>2]=innerWidth;H[g+16>>2]=innerHeight;H[g+20>>2]=outerWidth;H[g+24>>2]=outerHeight;H[g+28>>2]=pageXOffset;H[g+32>>2]=pageYOffset;J.get(d)(10,g,b)&&f.preventDefault()}}},Lb:c})}
function bb(a,b,c,d,f,l){Ta||(Ta=Q(1684));a=P(a);O({target:a,Rb:"touchstart"==l||"touchend"==l,Kb:l,Mb:d,Nb:function(g){for(var n={},m=g.touches,q=0;q<m.length;++q){var p=m[q];n[p.identifier]=p}m=g.changedTouches;for(q=0;q<m.length;++q)p=m[q],p.nc=1,n[p.identifier]=p;m=g.targetTouches;for(q=0;q<m.length;++q)n[m[q].identifier].oc=1;m=Ta;p=m>>2;H[p+1]=g.ctrlKey;H[p+2]=g.shiftKey;H[p+3]=g.altKey;H[p+4]=g.metaKey;p+=5;var eb=Wa(a),fb=0;for(q in n){var y=n[q];H[p]=y.identifier;H[p+1]=y.screenX;H[p+2]=
y.screenY;H[p+3]=y.clientX;H[p+4]=y.clientY;H[p+5]=y.pageX;H[p+6]=y.pageY;H[p+7]=y.nc;H[p+8]=y.oc;H[p+9]=y.clientX-eb.left;H[p+10]=y.clientY-eb.top;p+=13;if(31<++fb)break}H[m>>2]=fb;J.get(d)(f,m,b)&&g.preventDefault()},Lb:c})}function cb(a,b,c,d,f,l){a={target:P(a),Kb:l,Mb:d,Nb:function(g){g=g||event;J.get(d)(f,0,b)&&g.preventDefault()},Lb:c};O(a)}
function db(a,b,c,d){Ua||(Ua=Q(96));O({target:a,Rb:!0,Kb:"wheel",Mb:d,Nb:function(f){f=f||event;var l=Ua;Ya(l,f,a);I[l+64>>3]=f.deltaX;I[l+72>>3]=f.deltaY;I[l+80>>3]=f.deltaZ;H[l+88>>2]=f.deltaMode;J.get(d)(9,l,b)&&f.preventDefault()},Lb:c})}
function gb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,l){b.drawArraysInstancedANGLE(c,d,f,l)},a.drawElementsInstanced=function(c,d,f,l,g){b.drawElementsInstancedANGLE(c,d,f,l,g)})}
function hb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function ib(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function jb(a){a.sc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function kb(a){a.vc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function lb(a){a.xc=a.getExtension("WEBGL_multi_draw")}var mb=1,nb=[],S=[],ob=[],pb=[],qb=[],T=[],U=[],rb=[],sb=[],V={},tb={},ub={};function W(a){vb||(vb=a)}function X(a){for(var b=mb++,c=a.length;c<b;c++)a[c]=null;return b}
function wb(a){a||(a=Y);if(!a.mc){a.mc=!0;var b=a.Sb;gb(b);hb(b);ib(b);jb(b);kb(b);b.tc=b.getExtension("EXT_disjoint_timer_query");lb(b);var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var vb,Y,xb=["default","low-power","high-performance"];function yb(a,b,c,d){for(var f=0;f<a;f++){var l=Z[c](),g=l&&X(d);l?(l.name=g,d[g]=l):W(1282);H[b+4*f>>2]=g}}
function zb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Y.version){W(1282);return}c=2*(Z.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>Y.version){W(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:W(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)H[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){W(1280);z("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:W(1280);z("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}H[b>>2]=c}else W(1281)}
function Ab(a){var b=qa(a)+1,c=Q(b);D(a,E,c,b);return c}var Z;wa.push({lc:function(){Bb()}});
var Gb={R:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},ha:function(a,b,c){a=P(a);if(!a)return-4;a=Wa(a);I[b>>3]=a.width;I[c>>3]=a.height;return 0},Ua:function(a,b,c){E.copyWithin(a,b,b+c)},Ga:function(a,b){function c(d){J.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Va:function(a){a>>>=0;var b=E.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);
a:{try{B.grow(Math.min(2147483648,d)-G.byteLength+65535>>>16);ta(B.buffer);var f=1;break a}catch(l){}f=void 0}if(f)return!0}return!1},Q:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},aa:function(a,b,c,d){Xa(a,b,c,d,2,"keydown");return 0},_:function(a,b,c,d){Xa(a,b,c,d,1,"keypress");return 0},$:function(a,b,c,d){Xa(a,b,c,d,3,"keyup");return 0},ga:function(a,b,c,d){R(a,b,c,d,5,"mousedown");return 0},da:function(a,b,c,d){R(a,b,c,d,33,"mouseenter");return 0},ca:function(a,b,c,d){R(a,
b,c,d,34,"mouseleave");return 0},ea:function(a,b,c,d){R(a,b,c,d,8,"mousemove");return 0},fa:function(a,b,c,d){R(a,b,c,d,6,"mouseup");return 0},V:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Vb||document.body.Xb||document.body.Wb))return-1;a=P(a);if(!a)return-4;Za(a,b,c,d,"pointerlockchange");Za(a,b,c,d,"mozpointerlockchange");Za(a,b,c,d,"webkitpointerlockchange");Za(a,b,c,d,"mspointerlockchange");return 0},U:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||
document.body.Vb||document.body.Xb||document.body.Wb))return-1;a=P(a);if(!a)return-4;$a(a,b,c,d,"pointerlockerror");$a(a,b,c,d,"mozpointerlockerror");$a(a,b,c,d,"webkitpointerlockerror");$a(a,b,c,d,"mspointerlockerror");return 0},Ta:function(a,b,c,d){ab(a,b,c,d);return 0},W:function(a,b,c,d){bb(a,b,c,d,25,"touchcancel");return 0},X:function(a,b,c,d){bb(a,b,c,d,23,"touchend");return 0},Y:function(a,b,c,d){bb(a,b,c,d,24,"touchmove");return 0},Z:function(a,b,c,d){bb(a,b,c,d,22,"touchstart");return 0},
T:function(a,b,c,d){cb(a,b,c,d,31,"webglcontextlost");return 0},S:function(a,b,c,d){cb(a,b,c,d,32,"webglcontextrestored");return 0},ba:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(db(a,b,c,d),0):-1},C:function(a,b){var c={};b>>=2;c.alpha=!!H[b];c.depth=!!H[b+1];c.stencil=!!H[b+2];c.antialias=!!H[b+3];c.premultipliedAlpha=!!H[b+4];c.preserveDrawingBuffer=!!H[b+5];c.powerPreference=xb[H[b+6]];c.failIfMajorPerformanceCaveat=!!H[b+7];c.ac=H[b+8];c.wc=H[b+9];c.$b=H[b+10];c.kc=H[b+11];
c.yc=H[b+12];c.zc=H[b+13];a=P(a);if(!a||c.kc)c=0;else if(a=1<c.ac?a.getContext("webgl2",c):a.getContext("webgl",c)){b=X(sb);var d={uc:b,attributes:c,version:c.ac,Sb:a};a.canvas&&(a.canvas.pc=d);sb[b]=d;("undefined"===typeof c.$b||c.$b)&&wb(d);c=b}else c=0;return c},oa:function(a,b){a=sb[a];b=F(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&gb(Z);"OES_vertex_array_object"==b&&hb(Z);"WEBGL_draw_buffers"==b&&ib(Z);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&jb(Z);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==
b&&kb(Z);"WEBGL_multi_draw"==b&&lb(Z);return!!a.Sb.getExtension(b)},Fa:function(a){a>>=2;for(var b=0;14>b;++b)H[a+b]=0;H[a]=H[a+1]=H[a+3]=H[a+4]=H[a+8]=H[a+10]=1},wa:function(a){Y=sb[a];e.rc=Z=Y&&Y.Sb;return!a||Z?0:-5},c:function(a){Z.activeTexture(a)},E:function(a,b){Z.attachShader(S[a],U[b])},d:function(a,b){35051==a?Z.Yb=b:35052==a&&(Z.Zb=b);Z.bindBuffer(a,nb[b])},h:function(a,b){Z.bindFramebuffer(a,ob[b])},b:function(a,b){Z.bindTexture(a,qb[b])},P:function(a){Z.bindVertexArray(rb[a])},L:function(a,
b,c,d){Z.blendColor(a,b,c,d)},M:function(a,b){Z.blendEquationSeparate(a,b)},N:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},j:function(a,b,c,d,f,l,g,n,m,q){Z.blitFramebuffer(a,b,c,d,f,l,g,n,m,q)},G:function(a,b,c,d){2<=Y.version?c?Z.bufferData(a,E,d,c,b):Z.bufferData(a,b,d):Z.bufferData(a,c?E.subarray(c,c+b):b,d)},F:function(a,b,c,d){2<=Y.version?Z.bufferSubData(a,b,E,d,c):Z.bufferSubData(a,b,E.subarray(d,d+c))},na:function(a){Z.clear(a)},ra:function(a,b,c,d){Z.clearColor(a,b,c,d)},qa:function(a){Z.clearDepth(a)},
pa:function(a){Z.clearStencil(a)},r:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},za:function(a){Z.compileShader(U[a])},Ea:function(){var a=X(S),b=Z.createProgram();b.name=a;S[a]=b;return a},Ba:function(a){var b=X(U);U[b]=Z.createShader(a);return b},I:function(a){Z.cullFace(a)},va:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],f=nb[d];f&&(Z.deleteBuffer(f),f.name=0,nb[d]=null,d==Z.Yb&&(Z.Yb=0),d==Z.Zb&&(Z.Zb=0))}},i:function(a,b){for(var c=0;c<a;++c){var d=H[b+4*c>>2],f=ob[d];f&&(Z.deleteFramebuffer(f),
f.name=0,ob[d]=null)}},B:function(a){if(a){var b=S[a];b?(Z.deleteProgram(b),b.name=0,S[a]=null,V[a]=null):W(1281)}},y:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],f=pb[d];f&&(Z.deleteRenderbuffer(f),f.name=0,pb[d]=null)}},q:function(a){if(a){var b=U[a];b?(Z.deleteShader(b),U[a]=null):W(1281)}},ua:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],f=qb[d];f&&(Z.deleteTexture(f),f.name=0,qb[d]=null)}},Ka:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2];Z.deleteVertexArray(rb[d]);rb[d]=
null}},u:function(a){Z.depthFunc(a)},t:function(a){Z.depthMask(!!a)},e:function(a){Z.disable(a)},O:function(a){Z.disableVertexAttribArray(a)},ia:function(a,b,c){Z.drawArrays(a,b,c)},ja:function(a,b,c,d){Z.drawElements(a,b,c,d)},g:function(a){Z.enable(a)},ka:function(a){Z.enableVertexAttribArray(a)},J:function(a){Z.frontFace(a)},H:function(a,b){yb(a,b,"createBuffer",nb)},Ja:function(a,b){yb(a,b,"createVertexArray",rb)},xa:function(a,b){return Z.getAttribLocation(S[a],F(b))},f:function(a,b){zb(a,b)},
Ca:function(a,b,c,d){a=Z.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(H[c>>2]=b)},D:function(a,b,c){if(c)if(a>=mb)W(1281);else{var d=V[a];if(d)if(35716==b)a=Z.getProgramInfoLog(S[a]),null===a&&(a="(unknown error)"),H[c>>2]=a.length+1;else if(35719==b)H[c>>2]=d.Ub;else if(35722==b){if(-1==d.Ob){a=S[a];var f=Z.getProgramParameter(a,35721);for(b=d.Ob=0;b<f;++b)d.Ob=Math.max(d.Ob,Z.getActiveAttrib(a,b).name.length+1)}H[c>>2]=d.Ob}else if(35381==b){if(-1==d.Pb)for(a=
S[a],f=Z.getProgramParameter(a,35382),b=d.Pb=0;b<f;++b)d.Pb=Math.max(d.Pb,Z.getActiveUniformBlockName(a,b).length+1);H[c>>2]=d.Pb}else H[c>>2]=Z.getProgramParameter(S[a],b);else W(1282)}else W(1281)},ya:function(a,b,c,d){a=Z.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(H[c>>2]=b)},z:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),H[c>>2]=a?a.length+1:0):35720==b?(a=Z.getShaderSource(U[a]),H[c>>2]=a?a.length+1:0):H[c>>2]=Z.getShaderParameter(U[a],
b):W(1281)},Ma:function(a){if(tb[a])return tb[a];switch(a){case 7939:var b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Ab(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||W(1280);b=Ab(b);break;case 7938:b=Z.getParameter(7938);b=2<=Y.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Ab(b);break;case 35724:b=Z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+=
"0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Ab(b);break;default:return W(1280),0}return tb[a]=b},La:function(a,b){if(2>Y.version)return W(1282),0;var c=ub[a];if(c)return 0>b||b>=c.length?(W(1281),0):c[b];switch(a){case 7939:return c=Z.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Ab(d)}),c=ub[a]=c,0>b||b>=c.length?(W(1281),0):c[b];default:return W(1280),0}},m:function(a,b){b=F(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=
b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=V[a]&&V[a].ic[b])&&0<=c&&c<a[0]?a[1]+c:-1},Da:function(a){Z.linkProgram(S[a]);var b=S[a];a=V[a]={ic:{},Ub:0,Ob:-1,Pb:-1};for(var c=a.ic,d=Z.getProgramParameter(b,35718),f=0;f<d;++f){var l=Z.getActiveUniform(b,f),g=l.name;a.Ub=Math.max(a.Ub,g.length+1);"]"==g.slice(-1)&&(g=g.slice(0,g.lastIndexOf("[")));var n=Z.getUniformLocation(b,g);if(n){var m=X(T);c[g]=[l.size,m];T[m]=n;for(var q=1;q<l.size;++q)n=Z.getUniformLocation(b,g+"["+q+"]"),m=X(T),
T[m]=n}}},K:function(a,b){Z.polygonOffset(a,b)},k:function(a){Z.readBuffer(a)},sa:function(a,b,c,d){Z.scissor(a,b,c,d)},Aa:function(a,b,c,d){for(var f="",l=0;l<b;++l){var g=d?H[d+4*l>>2]:-1;f+=F(H[c+4*l>>2],0>g?void 0:g)}Z.shaderSource(U[a],f)},Ia:function(a,b,c){Z.stencilFunc(a,b,c)},x:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},s:function(a){Z.stencilMask(a)},Ha:function(a,b,c){Z.stencilOp(a,b,c)},w:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},A:function(a,b){Z.uniform1i(T[a],b)},l:function(a){Z.useProgram(S[a])},
la:function(a,b){Z.vertexAttribDivisor(a,b)},ma:function(a,b,c,d,f,l){Z.vertexAttribPointer(a,b,c,!!d,f,l)},ta:function(a,b,c,d){Z.viewport(a,b,c,d)},a:B,Sa:function(){e.bc=function(a){0!=Cb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.bc)},Ra:function(){e.hc=function(a){a=a.clipboardData.getData("text");la("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",e.hc)},Qa:function(a){e.Ac=[];a=F(a);a=document.getElementById(a);e.cc=function(b){b.stopPropagation();
b.preventDefault()};e.dc=function(b){b.stopPropagation();b.preventDefault()};e.ec=function(b){b.stopPropagation();b.preventDefault()};e.fc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;e.Bc=c;Db(c.length);var d;for(d=0;d<c.length;d++)la("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Eb(b.clientX,b.clientY)};a.addEventListener("dragenter",e.cc,!1);a.addEventListener("dragleave",e.dc,!1);a.addEventListener("dragover",e.ec,!1);a.addEventListener("drop",e.fc,!1)},
p:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Fb()});document.body.append(a)},o:function(){document.getElementById("_sokol_app_input_element").focus()},Wa:function(a){a=F(a);e.Qb=document.getElementById(a);e.Qb||console.log("sokol_app.h: invalid target:"+a);e.Qb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Pa:function(){window.removeEventListener("beforeunload",
e.bc)},Oa:function(){window.removeEventListener("paste",e.hc)},Na:function(a){a=F(a);a=document.getElementById(a);a.removeEventListener("dragenter",e.cc);a.removeEventListener("dragleave",e.dc);a.removeEventListener("dragover",e.ec);a.removeEventListener("drop",e.fc)},v:function(){e.Qb&&e.Qb.requestPointerLock&&e.Qb.requestPointerLock()},n:function(){document.getElementById("_sokol_app_input_element").blur()}};
(function(){function a(f){e.asm=f.exports;J=e.asm.Xa;K--;e.monitorRunDependencies&&e.monitorRunDependencies(K);0==K&&(null!==Ba&&(clearInterval(Ba),Ba=null),L&&(f=L,L=null,f()))}function b(f){a(f.instance)}function c(f){return Ga().then(function(l){return WebAssembly.instantiate(l,d)}).then(f,function(l){z("failed to asynchronously prepare wasm: "+l);x(l)})}var d={a:Gb};K++;e.monitorRunDependencies&&e.monitorRunDependencies(K);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return z("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){return A||"function"!==typeof WebAssembly.instantiateStreaming||Da()||Ca("file://")||"function"!==typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(l){z("wasm streaming compile failed: "+l);z("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Bb=e.___wasm_call_ctors=function(){return(Bb=e.___wasm_call_ctors=e.asm.Ya).apply(null,arguments)},Fb=e.__sapp_emsc_notify_keyboard_hidden=function(){return(Fb=e.__sapp_emsc_notify_keyboard_hidden=e.asm.Za).apply(null,arguments)};e.__sapp_emsc_onpaste=function(){return(e.__sapp_emsc_onpaste=e.asm._a).apply(null,arguments)};
var Cb=e.__sapp_html5_get_ask_leave_site=function(){return(Cb=e.__sapp_html5_get_ask_leave_site=e.asm.$a).apply(null,arguments)},Db=e.__sapp_emsc_begin_drop=function(){return(Db=e.__sapp_emsc_begin_drop=e.asm.ab).apply(null,arguments)};e.__sapp_emsc_drop=function(){return(e.__sapp_emsc_drop=e.asm.bb).apply(null,arguments)};var Eb=e.__sapp_emsc_end_drop=function(){return(Eb=e.__sapp_emsc_end_drop=e.asm.cb).apply(null,arguments)};
e.__sapp_emsc_invoke_fetch_cb=function(){return(e.__sapp_emsc_invoke_fetch_cb=e.asm.db).apply(null,arguments)};e.___em_js__sapp_js_create_textfield=function(){return(e.___em_js__sapp_js_create_textfield=e.asm.eb).apply(null,arguments)};e.___em_js__sapp_js_focus_textfield=function(){return(e.___em_js__sapp_js_focus_textfield=e.asm.fb).apply(null,arguments)};e.___em_js__sapp_js_unfocus_textfield=function(){return(e.___em_js__sapp_js_unfocus_textfield=e.asm.gb).apply(null,arguments)};
e.___em_js__sapp_js_add_beforeunload_listener=function(){return(e.___em_js__sapp_js_add_beforeunload_listener=e.asm.hb).apply(null,arguments)};e.___em_js__sapp_js_remove_beforeunload_listener=function(){return(e.___em_js__sapp_js_remove_beforeunload_listener=e.asm.ib).apply(null,arguments)};e.___em_js__sapp_js_add_clipboard_listener=function(){return(e.___em_js__sapp_js_add_clipboard_listener=e.asm.jb).apply(null,arguments)};
e.___em_js__sapp_js_remove_clipboard_listener=function(){return(e.___em_js__sapp_js_remove_clipboard_listener=e.asm.kb).apply(null,arguments)};e.___em_js__sapp_js_write_clipboard=function(){return(e.___em_js__sapp_js_write_clipboard=e.asm.lb).apply(null,arguments)};e.___em_js__sapp_js_add_dragndrop_listeners=function(){return(e.___em_js__sapp_js_add_dragndrop_listeners=e.asm.mb).apply(null,arguments)};
e.___em_js__sapp_js_dropped_file_size=function(){return(e.___em_js__sapp_js_dropped_file_size=e.asm.nb).apply(null,arguments)};e.___em_js__sapp_js_fetch_dropped_file=function(){return(e.___em_js__sapp_js_fetch_dropped_file=e.asm.ob).apply(null,arguments)};e.___em_js__sapp_js_remove_dragndrop_listeners=function(){return(e.___em_js__sapp_js_remove_dragndrop_listeners=e.asm.pb).apply(null,arguments)};
e.___em_js__sapp_js_pointer_init=function(){return(e.___em_js__sapp_js_pointer_init=e.asm.qb).apply(null,arguments)};e.___em_js__sapp_js_request_pointerlock=function(){return(e.___em_js__sapp_js_request_pointerlock=e.asm.rb).apply(null,arguments)};e.___em_js__sapp_js_exit_pointerlock=function(){return(e.___em_js__sapp_js_exit_pointerlock=e.asm.sb).apply(null,arguments)};e._main=function(){return(e._main=e.asm.tb).apply(null,arguments)};
e.___em_js__stm_js_perfnow=function(){return(e.___em_js__stm_js_perfnow=e.asm.ub).apply(null,arguments)};e.__saudio_emsc_pull=function(){return(e.__saudio_emsc_pull=e.asm.vb).apply(null,arguments)};e.___em_js__saudio_js_init=function(){return(e.___em_js__saudio_js_init=e.asm.wb).apply(null,arguments)};e.___em_js__saudio_js_shutdown=function(){return(e.___em_js__saudio_js_shutdown=e.asm.xb).apply(null,arguments)};
e.___em_js__saudio_js_sample_rate=function(){return(e.___em_js__saudio_js_sample_rate=e.asm.yb).apply(null,arguments)};e.___em_js__saudio_js_buffer_frames=function(){return(e.___em_js__saudio_js_buffer_frames=e.asm.zb).apply(null,arguments)};e.___em_js__sfetch_js_send_head_request=function(){return(e.___em_js__sfetch_js_send_head_request=e.asm.Ab).apply(null,arguments)};e.___em_js__sfetch_js_send_get_request=function(){return(e.___em_js__sfetch_js_send_get_request=e.asm.Bb).apply(null,arguments)};
e.__sfetch_emsc_head_response=function(){return(e.__sfetch_emsc_head_response=e.asm.Cb).apply(null,arguments)};e.__sfetch_emsc_get_response=function(){return(e.__sfetch_emsc_get_response=e.asm.Db).apply(null,arguments)};e.__sfetch_emsc_failed_http_status=function(){return(e.__sfetch_emsc_failed_http_status=e.asm.Eb).apply(null,arguments)};e.__sfetch_emsc_failed_buffer_too_small=function(){return(e.__sfetch_emsc_failed_buffer_too_small=e.asm.Fb).apply(null,arguments)};
var Q=e._malloc=function(){return(Q=e._malloc=e.asm.Gb).apply(null,arguments)},na=e.stackSave=function(){return(na=e.stackSave=e.asm.Hb).apply(null,arguments)},oa=e.stackRestore=function(){return(oa=e.stackRestore=e.asm.Ib).apply(null,arguments)},C=e.stackAlloc=function(){return(C=e.stackAlloc=e.asm.Jb).apply(null,arguments)},Hb;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}L=function Ib(){Hb||Jb();Hb||(L=Ib)};
function Jb(a){function b(){if(!Hb&&(Hb=!0,e.calledRun=!0,!ja)){Ha(wa);Ha(xa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Kb){var c=a,d=e._main;c=c||[];var f=c.length+1,l=C(4*(f+1));H[l>>2]=ra(aa);for(var g=1;g<f;g++)H[(l>>2)+g]=ra(c[g-1]);H[(l>>2)+f]=0;try{var n=d(f,l);if(!noExitRuntime||0!==n){if(!noExitRuntime){if(e.onExit)e.onExit(n);ja=!0}t(n,new ia(n))}}catch(m){m instanceof ia||("unwind"==m?noExitRuntime=!0:((c=m)&&"object"===typeof m&&m.stack&&(c=[m,m.stack]),z("exception thrown: "+
c),t(1,m)))}finally{}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),za.unshift(c);Ha(za)}}a=a||r;if(!(0<K)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Aa();Ha(va);0<K||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=Jb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();
var Kb=!0;e.noInitialRun&&(Kb=!1);noExitRuntime=!0;Jb();
