
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var h={},k;for(k in e)e.hasOwnProperty(k)&&(h[k]=e[k]);var r=[],aa="./this.program";function t(a,b){throw b;}var u=!1,v=!1,ba=!1,ca=!1;u="object"===typeof window;v="function"===typeof importScripts;ba="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ca=!u&&!ba&&!v;var w="",da,ea,x,fa,ha;
if(ba)w=v?require("path").dirname(w)+"/":__dirname+"/",da=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,b?null:"utf8")},x=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),r=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;}),process.on("unhandledRejection",
z),t=function(a){process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=typeof read&&(da=function(a){return read(a)}),x=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?r=scriptArgs:"undefined"!=typeof arguments&&(r=arguments),"function"===typeof quit&&(t=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(u||v)v?w=self.location.href:"undefined"!==typeof document&&document.currentScript&&(w=document.currentScript.src),w=0!==w.indexOf("blob:")?w.substr(0,w.lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(x=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ea=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};e.print||console.log.bind(console);var A=e.printErr||console.warn.bind(console);for(k in h)h.hasOwnProperty(k)&&(e[k]=h[k]);h=null;e.arguments&&(r=e.arguments);e.thisProgram&&(aa=e.thisProgram);e.quit&&(t=e.quit);var B;e.wasmBinary&&(B=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;
"object"!==typeof WebAssembly&&z("no native wasm support detected");var ja,ka=!1;function assert(a,b){a||z("Assertion failed: "+b)}function la(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function ma(a,b,c){var d={string:function(m){var q=0;if(null!==m&&void 0!==m&&0!==m){var p=(m.length<<2)+1;q=C(p);D(m,E,q,p)}return q},array:function(m){var q=C(m.length);na.set(m,q);return q}};a=la(a);var f=[],l=0;if(c)for(var g=0;g<c.length;g++){var n=d[b[g]];n?(0===l&&(l=oa()),f[g]=n(c[g])):f[g]=c[g]}a.apply(null,f);0!==l&&pa(l)}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function F(a,b){if(a){var c=E,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&qa)a=qa.decode(c.subarray(a,b));else{for(d="";a<b;){var f=c[a++];if(f&128){var l=c[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|l);else{var g=c[a++]&63;f=224==(f&240)?(f&15)<<12|l<<6|g:(f&7)<<18|l<<12|g<<6|c[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}a=d}}else a="";return a}
function D(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var l=0;l<a.length;++l){var g=a.charCodeAt(l);if(55296<=g&&57343>=g){var n=a.charCodeAt(++l);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}
function ra(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function sa(a){var b=ra(a)+1,c=C(b);D(a,na,c,b);return c}var ta,na,E,ua,G,H;
function va(){var a=ja.buffer;ta=a;e.HEAP8=na=new Int8Array(a);e.HEAP16=ua=new Int16Array(a);e.HEAP32=G=new Int32Array(a);e.HEAPU8=E=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAPU32=new Uint32Array(a);e.HEAPF32=new Float32Array(a);e.HEAPF64=H=new Float64Array(a)}var I,wa=[],xa=[],ya=[],za=[],Aa=[];xa.push({Pb:function(){Ba()}});function Ca(){var a=e.preRun.shift();wa.unshift(a)}var J=0,Da=null,K=null;e.preloadedImages={};e.preloadedAudios={};
function z(a){if(e.onAbort)e.onAbort(a);A(a);ka=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ea(a){var b=L;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Fa(){return Ea("data:application/octet-stream;base64,")}var L="quad-sapp.wasm";if(!Fa()){var Ga=L;L=e.locateFile?e.locateFile(Ga,w):w+Ga}
function Ha(){var a=L;try{if(a==L&&B)return new Uint8Array(B);if(x)return x(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Ia(){if(!B&&(u||v)){if("function"===typeof fetch&&!Ea("file://"))return fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ha()});if(ea)return new Promise(function(a,b){ea(L,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ha()})}
function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Pb;"number"===typeof c?void 0===b.xb?I.get(c)():I.get(c)(b.xb):c(void 0===b.xb?null:b.xb)}}}var Ka=0;function La(){for(var a=M.length-1;0<=a;--a)Ma(a);M=[];Na=[]}var Na=[];function Oa(){if(Ka&&Pa.vb)for(var a=0;a<Na.length;++a){var b=Na[a];Na.splice(a,1);--a;b.fc.apply(null,b.Ub)}}var M=[];function Ma(a){var b=M[a];b.target.removeEventListener(b.ob,b.Nb,b.pb);M.splice(a,1)}
function N(a){function b(d){++Ka;Pa=a;Oa();a.rb(d);Oa();--Ka}if(a.qb)a.Nb=b,a.target.addEventListener(a.ob,b,a.pb),M.push(a),Qa||(za.push(La),Qa=!0);else for(var c=0;c<M.length;++c)M[c].target==a.target&&M[c].ob==a.ob&&Ma(c--)}var Qa,Pa,Ra,Sa,Ta,Ua,Va,Wa,Xa=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function O(a){a=2<a?F(a):a;return Xa[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Ya(a){return 0>Xa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function Za(a,b,c,d,f,l){Ra||(Ra=P(164));a={target:O(a),vb:!0,ob:l,qb:d,rb:function(g){var n=Ra,m=n>>2;G[m]=g.location;G[m+1]=g.ctrlKey;G[m+2]=g.shiftKey;G[m+3]=g.altKey;G[m+4]=g.metaKey;G[m+5]=g.repeat;G[m+6]=g.charCode;G[m+7]=g.keyCode;G[m+8]=g.which;D(g.key||"",E,n+36,32);D(g.code||"",E,n+68,32);D(g.char||"",E,n+100,32);D(g.locale||"",E,n+132,32);I.get(d)(f,n,b)&&g.preventDefault()},pb:c};N(a)}
function $a(a,b,c){a>>=2;G[a]=b.screenX;G[a+1]=b.screenY;G[a+2]=b.clientX;G[a+3]=b.clientY;G[a+4]=b.ctrlKey;G[a+5]=b.shiftKey;G[a+6]=b.altKey;G[a+7]=b.metaKey;ua[2*a+16]=b.button;ua[2*a+17]=b.buttons;G[a+9]=b.movementX;G[a+10]=b.movementY;c=Ya(c);G[a+11]=b.clientX-c.left;G[a+12]=b.clientY-c.top}function Q(a,b,c,d,f,l){Sa||(Sa=P(64));a=O(a);N({target:a,vb:"mousemove"!=l&&"mouseenter"!=l&&"mouseleave"!=l,ob:l,qb:d,rb:function(g){g=g||event;$a(Sa,g,a);I.get(d)(f,Sa,b)&&g.preventDefault()},pb:c})}
function ab(a,b,c,d,f){Ta||(Ta=P(260));N({target:a,ob:f,qb:d,rb:function(l){l=l||event;var g=Ta,n=document.pointerLockElement||document.Db||document.Fb||document.Eb;G[g>>2]=!!n;var m=n&&n.id?n.id:"";D(n?n==window?"#window":n==screen?"#screen":n&&n.nodeName?n.nodeName:"":"",E,g+4,128);D(m,E,g+132,128);I.get(d)(20,g,b)&&l.preventDefault()},pb:c})}function bb(a,b,c,d,f){N({target:a,ob:f,qb:d,rb:function(l){l=l||event;I.get(d)(38,0,b)&&l.preventDefault()},pb:c})}
function cb(a,b,c,d){Ua||(Ua=P(36));a=O(a);N({target:a,ob:"resize",qb:d,rb:function(f){f=f||event;if(f.target==a){var l=document.body;if(l){var g=Ua;G[g>>2]=f.detail;G[g+4>>2]=l.clientWidth;G[g+8>>2]=l.clientHeight;G[g+12>>2]=innerWidth;G[g+16>>2]=innerHeight;G[g+20>>2]=outerWidth;G[g+24>>2]=outerHeight;G[g+28>>2]=pageXOffset;G[g+32>>2]=pageYOffset;I.get(d)(10,g,b)&&f.preventDefault()}}},pb:c})}
function db(a,b,c,d,f,l){Va||(Va=P(1684));a=O(a);N({target:a,vb:"touchstart"==l||"touchend"==l,ob:l,qb:d,rb:function(g){for(var n={},m=g.touches,q=0;q<m.length;++q){var p=m[q];n[p.identifier]=p}m=g.changedTouches;for(q=0;q<m.length;++q)p=m[q],p.Rb=1,n[p.identifier]=p;m=g.targetTouches;for(q=0;q<m.length;++q)n[m[q].identifier].Sb=1;m=Va;p=m>>2;G[p+1]=g.ctrlKey;G[p+2]=g.shiftKey;G[p+3]=g.altKey;G[p+4]=g.metaKey;p+=5;var fb=Ya(a),gb=0;for(q in n){var y=n[q];G[p]=y.identifier;G[p+1]=y.screenX;G[p+2]=
y.screenY;G[p+3]=y.clientX;G[p+4]=y.clientY;G[p+5]=y.pageX;G[p+6]=y.pageY;G[p+7]=y.Rb;G[p+8]=y.Sb;G[p+9]=y.clientX-fb.left;G[p+10]=y.clientY-fb.top;p+=13;if(31<++gb)break}G[m>>2]=gb;I.get(d)(f,m,b)&&g.preventDefault()},pb:c})}function eb(a,b,c,d,f,l){a={target:O(a),ob:l,qb:d,rb:function(g){g=g||event;I.get(d)(f,0,b)&&g.preventDefault()},pb:c};N(a)}
function hb(a,b,c,d){Wa||(Wa=P(96));N({target:a,vb:!0,ob:"wheel",qb:d,rb:function(f){f=f||event;var l=Wa;$a(l,f,a);H[l+64>>3]=f.deltaX;H[l+72>>3]=f.deltaY;H[l+80>>3]=f.deltaZ;G[l+88>>2]=f.deltaMode;I.get(d)(9,l,b)&&f.preventDefault()},pb:c})}
function ib(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,l){b.drawArraysInstancedANGLE(c,d,f,l)},a.drawElementsInstanced=function(c,d,f,l,g){b.drawElementsInstancedANGLE(c,d,f,l,g)})}
function jb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function kb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function lb(a){a.Wb=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function mb(a){a.Zb=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function nb(a){a.ac=a.getExtension("WEBGL_multi_draw")}var ob=1,pb=[],R=[],qb=[],rb=[],sb=[],S=[],T=[],tb=[],ub=[],U={},vb={},wb={};function V(a){xb||(xb=a)}function W(a){for(var b=ob++,c=a.length;c<b;c++)a[c]=null;return b}
function yb(a){a||(a=X);if(!a.Qb){a.Qb=!0;var b=a.wb;ib(b);jb(b);kb(b);lb(b);mb(b);b.Xb=b.getExtension("EXT_disjoint_timer_query");nb(b);(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var xb,X,zb=["default","low-power","high-performance"];function Ab(a,b,c,d){for(var f=0;f<a;f++){var l=Y[c](),g=l&&W(d);l?(l.name=g,d[g]=l):V(1282);G[b+4*f>>2]=g}}
function Bb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Y.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>X.version){V(1282);return}c=2*(Y.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>X.version){V(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=Y.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":V(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:V(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)G[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){V(1280);A("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:V(1280);A("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}G[b>>2]=c}else V(1281)}
function Z(a){var b=ra(a)+1,c=P(b);D(a,E,c,b);return c}
var Y,Gb={S:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},ia:function(a,b,c){a=O(a);if(!a)return-4;a=Ya(a);H[b>>3]=a.width;H[c>>3]=a.height;return 0},Ta:function(a,b,c){E.copyWithin(a,b,b+c)},Ga:function(a,b){function c(d){I.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ua:function(a){var b=E.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ja.grow(Math.min(2147483648,
d)-ta.byteLength+65535>>>16);va();var f=1;break a}catch(l){}f=void 0}if(f)return!0}return!1},R:function(a,b,c){a=O(a);if(!a)return-4;a.width=b;a.height=c;return 0},ba:function(a,b,c,d){Za(a,b,c,d,2,"keydown");return 0},$:function(a,b,c,d){Za(a,b,c,d,1,"keypress");return 0},aa:function(a,b,c,d){Za(a,b,c,d,3,"keyup");return 0},ha:function(a,b,c,d){Q(a,b,c,d,5,"mousedown");return 0},ea:function(a,b,c,d){Q(a,b,c,d,33,"mouseenter");return 0},da:function(a,b,c,d){Q(a,b,c,d,34,"mouseleave");return 0},fa:function(a,
b,c,d){Q(a,b,c,d,8,"mousemove");return 0},ga:function(a,b,c,d){Q(a,b,c,d,6,"mouseup");return 0},W:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Db||document.body.Fb||document.body.Eb))return-1;a=O(a);if(!a)return-4;ab(a,b,c,d,"pointerlockchange");ab(a,b,c,d,"mozpointerlockchange");ab(a,b,c,d,"webkitpointerlockchange");ab(a,b,c,d,"mspointerlockchange");return 0},V:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Db||
document.body.Fb||document.body.Eb))return-1;a=O(a);if(!a)return-4;bb(a,b,c,d,"pointerlockerror");bb(a,b,c,d,"mozpointerlockerror");bb(a,b,c,d,"webkitpointerlockerror");bb(a,b,c,d,"mspointerlockerror");return 0},Sa:function(a,b,c,d){cb(a,b,c,d);return 0},X:function(a,b,c,d){db(a,b,c,d,25,"touchcancel");return 0},Y:function(a,b,c,d){db(a,b,c,d,23,"touchend");return 0},Z:function(a,b,c,d){db(a,b,c,d,24,"touchmove");return 0},_:function(a,b,c,d){db(a,b,c,d,22,"touchstart");return 0},U:function(a,b,c,
d){eb(a,b,c,d,31,"webglcontextlost");return 0},T:function(a,b,c,d){eb(a,b,c,d,32,"webglcontextrestored");return 0},ca:function(a,b,c,d){a=O(a);return"undefined"!==typeof a.onwheel?(hb(a,b,c,d),0):-1},D:function(a,b){b>>=2;b={alpha:!!G[b],depth:!!G[b+1],stencil:!!G[b+2],antialias:!!G[b+3],premultipliedAlpha:!!G[b+4],preserveDrawingBuffer:!!G[b+5],powerPreference:zb[G[b+6]],failIfMajorPerformanceCaveat:!!G[b+7],Cb:G[b+8],$b:G[b+9],Bb:G[b+10],Ob:G[b+11],bc:G[b+12],cc:G[b+13]};a=O(a);if(!a||b.Ob)b=0;
else if(a=1<b.Cb?a.getContext("webgl2",b):a.getContext("webgl",b)){var c=W(ub),d={Yb:c,attributes:b,version:b.Cb,wb:a};a.canvas&&(a.canvas.Tb=d);ub[c]=d;("undefined"===typeof b.Bb||b.Bb)&&yb(d);b=c}else b=0;return b},pa:function(a,b){a=ub[a];b=F(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&ib(Y);"OES_vertex_array_object"==b&&jb(Y);"WEBGL_draw_buffers"==b&&kb(Y);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&lb(Y);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==
b&&mb(Y);"WEBGL_multi_draw"==b&&nb(Y);return!!a.wb.getExtension(b)},Ca:function(a){a>>=2;for(var b=0;14>b;++b)G[a+b]=0;G[a]=G[a+1]=G[a+3]=G[a+4]=G[a+8]=G[a+10]=1},wa:function(a){X=ub[a];e.Vb=Y=X&&X.wb;return!a||Y?0:-5},b:function(a){Y.activeTexture(a)},C:function(a,b){Y.attachShader(R[a],T[b])},c:function(a,b){35051==a?Y.zb=b:35052==a&&(Y.Ab=b);Y.bindBuffer(a,pb[b])},g:function(a,b){Y.bindFramebuffer(a,qb[b])},a:function(a,b){Y.bindTexture(a,sb[b])},O:function(a){Y.bindVertexArray(tb[a])},K:function(a,
b,c,d){Y.blendColor(a,b,c,d)},L:function(a,b){Y.blendEquationSeparate(a,b)},M:function(a,b,c,d){Y.blendFuncSeparate(a,b,c,d)},j:function(a,b,c,d,f,l,g,n,m,q){Y.blitFramebuffer(a,b,c,d,f,l,g,n,m,q)},F:function(a,b,c,d){2<=X.version?c?Y.bufferData(a,E,d,c,b):Y.bufferData(a,b,d):Y.bufferData(a,c?E.subarray(c,c+b):b,d)},E:function(a,b,c,d){2<=X.version?Y.bufferSubData(a,b,E,d,c):Y.bufferSubData(a,b,E.subarray(d,d+c))},oa:function(a){Y.clear(a)},y:function(a,b,c,d){Y.clearColor(a,b,c,d)},x:function(a){Y.clearDepth(a)},
qa:function(a){Y.clearStencil(a)},i:function(a,b,c,d){Y.colorMask(!!a,!!b,!!c,!!d)},va:function(a){Y.compileShader(T[a])},Ba:function(){var a=W(R),b=Y.createProgram();b.name=a;R[a]=b;return a},ya:function(a){var b=W(T);T[b]=Y.createShader(a);return b},H:function(a){Y.cullFace(a)},Ja:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],f=pb[d];f&&(Y.deleteBuffer(f),f.name=0,pb[d]=null,d==Y.zb&&(Y.zb=0),d==Y.Ab&&(Y.Ab=0))}},h:function(a,b){for(var c=0;c<a;++c){var d=G[b+4*c>>2],f=qb[d];f&&(Y.deleteFramebuffer(f),
f.name=0,qb[d]=null)}},P:function(a){if(a){var b=R[a];b?(Y.deleteProgram(b),b.name=0,R[a]=null,U[a]=null):V(1281)}},Q:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],f=rb[d];f&&(Y.deleteRenderbuffer(f),f.name=0,rb[d]=null)}},q:function(a){if(a){var b=T[a];b?(Y.deleteShader(b),T[a]=null):V(1281)}},Ia:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],f=sb[d];f&&(Y.deleteTexture(f),f.name=0,sb[d]=null)}},Ha:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2];Y.deleteVertexArray(tb[d]);tb[d]=
null}},t:function(a){Y.depthFunc(a)},s:function(a){Y.depthMask(!!a)},d:function(a){Y.disable(a)},N:function(a){Y.disableVertexAttribArray(a)},ja:function(a,b,c){Y.drawArrays(a,b,c)},ka:function(a,b,c,d){Y.drawElements(a,b,c,d)},f:function(a){Y.enable(a)},la:function(a){Y.enableVertexAttribArray(a)},I:function(a){Y.frontFace(a)},G:function(a,b){Ab(a,b,"createBuffer",pb)},Fa:function(a,b){Ab(a,b,"createVertexArray",tb)},ta:function(a,b){return Y.getAttribLocation(R[a],F(b))},e:function(a,b){Bb(a,b)},
za:function(a,b,c,d){a=Y.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(G[c>>2]=b)},B:function(a,b,c){if(c)if(a>=ob)V(1281);else{var d=U[a];if(d)if(35716==b)a=Y.getProgramInfoLog(R[a]),null===a&&(a="(unknown error)"),G[c>>2]=a.length+1;else if(35719==b)G[c>>2]=d.yb;else if(35722==b){if(-1==d.sb){a=R[a];var f=Y.getProgramParameter(a,35721);for(b=d.sb=0;b<f;++b)d.sb=Math.max(d.sb,Y.getActiveAttrib(a,b).name.length+1)}G[c>>2]=d.sb}else if(35381==b){if(-1==d.tb)for(a=
R[a],f=Y.getProgramParameter(a,35382),b=d.tb=0;b<f;++b)d.tb=Math.max(d.tb,Y.getActiveUniformBlockName(a,b).length+1);G[c>>2]=d.tb}else G[c>>2]=Y.getProgramParameter(R[a],b);else V(1282)}else V(1281)},ua:function(a,b,c,d){a=Y.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(G[c>>2]=b)},z:function(a,b,c){c?35716==b?(a=Y.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),G[c>>2]=a?a.length+1:0):35720==b?(a=Y.getShaderSource(T[a]),G[c>>2]=a?a.length+1:0):G[c>>2]=Y.getShaderParameter(T[a],
b):V(1281)},La:function(a){if(vb[a])return vb[a];switch(a){case 7939:var b=Y.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Z(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Y.getParameter(a))||V(1280);b=Z(b);break;case 7938:b=Y.getParameter(7938);b=2<=X.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Z(b);break;case 35724:b=Y.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+=
"0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Z(b);break;default:return V(1280),0}return vb[a]=b},Ka:function(a,b){if(2>X.version)return V(1282),0;var c=wb[a];if(c)return 0>b||b>=c.length?(V(1281),0):c[b];switch(a){case 7939:return c=Y.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Z(d)}),c=wb[a]=c,0>b||b>=c.length?(V(1281),0):c[b];default:return V(1280),0}},l:function(a,b){b=F(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=
b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=U[a]&&U[a].Mb[b])&&0<=c&&c<a[0]?a[1]+c:-1},Aa:function(a){Y.linkProgram(R[a]);var b=R[a];a=U[a]={Mb:{},yb:0,sb:-1,tb:-1};for(var c=a.Mb,d=Y.getProgramParameter(b,35718),f=0;f<d;++f){var l=Y.getActiveUniform(b,f),g=l.name;a.yb=Math.max(a.yb,g.length+1);"]"==g.slice(-1)&&(g=g.slice(0,g.lastIndexOf("[")));var n=Y.getUniformLocation(b,g);if(n){var m=W(S);c[g]=[l.size,m];S[m]=n;for(var q=1;q<l.size;++q)n=Y.getUniformLocation(b,g+"["+q+"]"),m=W(S),
S[m]=n}}},J:function(a,b){Y.polygonOffset(a,b)},k:function(a){Y.readBuffer(a)},ra:function(a,b,c,d){Y.scissor(a,b,c,d)},xa:function(a,b,c,d){for(var f="",l=0;l<b;++l){var g=d?G[d+4*l>>2]:-1;f+=F(G[c+4*l>>2],0>g?void 0:g)}Y.shaderSource(T[a],f)},Ea:function(a,b,c){Y.stencilFunc(a,b,c)},w:function(a,b,c,d){Y.stencilFuncSeparate(a,b,c,d)},r:function(a){Y.stencilMask(a)},Da:function(a,b,c){Y.stencilOp(a,b,c)},v:function(a,b,c,d){Y.stencilOpSeparate(a,b,c,d)},A:function(a,b){Y.uniform1i(S[a],b)},m:function(a){Y.useProgram(R[a])},
ma:function(a,b){Y.vertexAttribDivisor(a,b)},na:function(a,b,c,d,f,l){Y.vertexAttribPointer(a,b,c,!!d,f,l)},sa:function(a,b,c,d){Y.viewport(a,b,c,d)},Ra:function(){e.Gb=function(a){0!=Cb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Gb)},Qa:function(){e.Lb=function(a){a=a.clipboardData.getData("text");ma("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",e.Lb)},Pa:function(a){e.dc=[];a=F(a);a=document.getElementById(a);e.Hb=function(b){b.stopPropagation();
b.preventDefault()};e.Ib=function(b){b.stopPropagation();b.preventDefault()};e.Jb=function(b){b.stopPropagation();b.preventDefault()};e.Kb=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;e.ec=c;Db(c.length);var d;for(d=0;d<c.length;d++)ma("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Eb(b.clientX,b.clientY)};a.addEventListener("dragenter",e.Hb,!1);a.addEventListener("dragleave",e.Ib,!1);a.addEventListener("dragover",e.Jb,!1);a.addEventListener("drop",e.Kb,!1)},
p:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Fb()});document.body.append(a)},o:function(){document.getElementById("_sokol_app_input_element").focus()},Va:function(a){a=F(a);e.ub=document.getElementById(a);e.ub||console.log("sokol_app.h: invalid target:"+a);e.ub.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Oa:function(){window.removeEventListener("beforeunload",
e.Gb)},Na:function(){window.removeEventListener("paste",e.Lb)},Ma:function(a){a=F(a);a=document.getElementById(a);a.removeEventListener("dragenter",e.Hb);a.removeEventListener("dragleave",e.Ib);a.removeEventListener("dragover",e.Jb);a.removeEventListener("drop",e.Kb)},u:function(){e.ub&&e.ub.requestPointerLock&&e.ub.requestPointerLock()},n:function(){document.getElementById("_sokol_app_input_element").blur()}};
(function(){function a(f){e.asm=f.exports;ja=e.asm.Wa;va();I=e.asm.nb;J--;e.monitorRunDependencies&&e.monitorRunDependencies(J);0==J&&(null!==Da&&(clearInterval(Da),Da=null),K&&(f=K,K=null,f()))}function b(f){a(f.instance)}function c(f){return Ia().then(function(l){return WebAssembly.instantiate(l,d)}).then(f,function(l){A("failed to asynchronously prepare wasm: "+l);z(l)})}var d={a:Gb};J++;e.monitorRunDependencies&&e.monitorRunDependencies(J);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return A("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){return B||"function"!==typeof WebAssembly.instantiateStreaming||Fa()||Ea("file://")||"function"!==typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(l){A("wasm streaming compile failed: "+l);A("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Ba=e.___wasm_call_ctors=function(){return(Ba=e.___wasm_call_ctors=e.asm.Xa).apply(null,arguments)},Fb=e.__sapp_emsc_notify_keyboard_hidden=function(){return(Fb=e.__sapp_emsc_notify_keyboard_hidden=e.asm.Ya).apply(null,arguments)};e.__sapp_emsc_onpaste=function(){return(e.__sapp_emsc_onpaste=e.asm.Za).apply(null,arguments)};
var Cb=e.__sapp_html5_get_ask_leave_site=function(){return(Cb=e.__sapp_html5_get_ask_leave_site=e.asm._a).apply(null,arguments)},Db=e.__sapp_emsc_begin_drop=function(){return(Db=e.__sapp_emsc_begin_drop=e.asm.$a).apply(null,arguments)};e.__sapp_emsc_drop=function(){return(e.__sapp_emsc_drop=e.asm.ab).apply(null,arguments)};var Eb=e.__sapp_emsc_end_drop=function(){return(Eb=e.__sapp_emsc_end_drop=e.asm.bb).apply(null,arguments)};
e.__sapp_emsc_invoke_fetch_cb=function(){return(e.__sapp_emsc_invoke_fetch_cb=e.asm.cb).apply(null,arguments)};e._main=function(){return(e._main=e.asm.db).apply(null,arguments)};e.__saudio_emsc_pull=function(){return(e.__saudio_emsc_pull=e.asm.eb).apply(null,arguments)};e.__sfetch_emsc_head_response=function(){return(e.__sfetch_emsc_head_response=e.asm.fb).apply(null,arguments)};e.__sfetch_emsc_get_response=function(){return(e.__sfetch_emsc_get_response=e.asm.gb).apply(null,arguments)};
e.__sfetch_emsc_failed_http_status=function(){return(e.__sfetch_emsc_failed_http_status=e.asm.hb).apply(null,arguments)};e.__sfetch_emsc_failed_buffer_too_small=function(){return(e.__sfetch_emsc_failed_buffer_too_small=e.asm.ib).apply(null,arguments)};
var P=e._malloc=function(){return(P=e._malloc=e.asm.jb).apply(null,arguments)},oa=e.stackSave=function(){return(oa=e.stackSave=e.asm.kb).apply(null,arguments)},pa=e.stackRestore=function(){return(pa=e.stackRestore=e.asm.lb).apply(null,arguments)},C=e.stackAlloc=function(){return(C=e.stackAlloc=e.asm.mb).apply(null,arguments)},Hb;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}K=function Ib(){Hb||Jb();Hb||(K=Ib)};
function Jb(a){function b(){if(!Hb&&(Hb=!0,e.calledRun=!0,!ka)){Ja(xa);Ja(ya);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Kb){var c=a,d=e._main;c=c||[];var f=c.length+1,l=C(4*(f+1));G[l>>2]=sa(aa);for(var g=1;g<f;g++)G[(l>>2)+g]=sa(c[g-1]);G[(l>>2)+f]=0;try{var n=d(f,l);if(!noExitRuntime||0!==n){if(!noExitRuntime){if(e.onExit)e.onExit(n);ka=!0}t(n,new ia(n))}}catch(m){m instanceof ia||("unwind"==m?noExitRuntime=!0:((c=m)&&"object"===typeof m&&m.stack&&(c=[m,m.stack]),A("exception thrown: "+
c),t(1,m)))}finally{}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),Aa.unshift(c);Ja(Aa)}}a=a||r;if(!(0<J)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ca();Ja(wa);0<J||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=Jb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();
var Kb=!0;e.noInitialRun&&(Kb=!1);Jb();
