var e;e||(e=typeof Module !== 'undefined' ? Module : {});var f={},h;for(h in e)e.hasOwnProperty(h)&&(f[h]=e[h]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var p=!1,q=!1,aa=!1,ba=!1,ca=!1;p="object"===typeof window;q="function"===typeof importScripts;aa=(ba="object"===typeof process&&"function"===typeof require)&&!p&&!q;ca=!p&&!aa&&!q;var r="";
if(aa){r=__dirname+"/";var da,ea;e.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||u("Assertion failed: undefined");return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof
w))throw a;});process.on("unhandledRejection",u);e.quit=function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||u("Assertion failed: undefined");return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),
"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(p||q)q?r=self.location.href:document.currentScript&&(r=document.currentScript.src),r=0!==r.indexOf("blob:")?r.substr(0,r.lastIndexOf("/")+1):"",e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},q&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};var fa=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),x=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||fa);for(h in f)f.hasOwnProperty(h)&&(e[h]=f[h]);f=void 0;
"object"!==typeof WebAssembly&&x("no native wasm support detected");var y,ha=!1,ia="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function z(a,b){if(a){var c=A,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&ia)a=ia.decode(c.subarray(a,b));else{for(d="";a<b;){var g=c[a++];if(g&128){var k=c[a++]&63;if(192==(g&224))d+=String.fromCharCode((g&31)<<6|k);else{var l=c[a++]&63;g=224==(g&240)?(g&15)<<12|k<<6|l:(g&7)<<18|k<<12|l<<6|c[a++]&63;65536>g?d+=String.fromCharCode(g):(g-=65536,d+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else d+=String.fromCharCode(g)}a=d}}else a="";return a}
function B(a,b,c,d){if(!(0<d))return 0;var g=c;d=c+d-1;for(var k=0;k<a.length;++k){var l=a.charCodeAt(k);if(55296<=l&&57343>=l){var v=a.charCodeAt(++k);l=65536+((l&1023)<<10)|v&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-g}
function ja(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ka(a){var b=ja(a)+1,c=la(b);B(a,C,c,b);return c}function ma(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,C,A,na,D,E;
function oa(){e.HEAP8=C=new Int8Array(buffer);e.HEAP16=na=new Int16Array(buffer);e.HEAP32=D=new Int32Array(buffer);e.HEAPU8=A=new Uint8Array(buffer);e.HEAPU16=new Uint16Array(buffer);e.HEAPU32=new Uint32Array(buffer);e.HEAPF32=new Float32Array(buffer);e.HEAPF64=E=new Float64Array(buffer)}var F=e.TOTAL_MEMORY||33554432;5242880>F&&x("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+F+"! (TOTAL_STACK=5242880)");
e.buffer?buffer=e.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(y=new WebAssembly.Memory({initial:F/65536}),buffer=y.buffer):buffer=new ArrayBuffer(F);oa();D[5856]=5266336;function G(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.ub;"number"===typeof c?void 0===b.ib?e.dynCall_v(c):e.dynCall_vi(c,b.ib):c(void 0===b.ib?null:b.ib)}}}var pa=[],qa=[],ra=[],sa=[],ta=[];function ua(){var a=e.preRun.shift();pa.unshift(a)}var H=0,wa=null,I=null;
e.preloadedImages={};e.preloadedAudios={};function xa(){var a=J;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var J="quad-sapp.wasm";if(!xa()){var ya=J;J=e.locateFile?e.locateFile(ya,r):r+ya}function za(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(J);throw"both async and sync fetching of the wasm failed";}catch(a){u(a)}}
function Aa(){return e.wasmBinary||!p&&!q||"function"!==typeof fetch?new Promise(function(a){a(za())}):fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return za()})}
function Ba(a){function b(a){e.asm=a.exports;H--;e.monitorRunDependencies&&e.monitorRunDependencies(H);0==H&&(null!==wa&&(clearInterval(wa),wa=null),I&&(a=I,I=null,a()))}function c(a){b(a.instance)}function d(a){return Aa().then(function(a){return WebAssembly.instantiate(a,g)}).then(a,function(a){x("failed to asynchronously prepare wasm: "+a);u(a)})}var g={env:a};H++;e.monitorRunDependencies&&e.monitorRunDependencies(H);if(e.instantiateWasm)try{return e.instantiateWasm(g,b)}catch(k){return x("Module.instantiateWasm callback failed with error: "+
k),!1}(function(){if(e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||xa()||"function"!==typeof fetch)return d(c);fetch(J,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,g).then(c,function(a){x("wasm streaming compile failed: "+a);x("falling back to ArrayBuffer instantiation");d(c)})})})();return{}}e.asm=function(a,b){b.memory=y;b.table=new WebAssembly.Table({initial:16,maximum:16,element:"anyfunc"});return Ba(b)};qa.push({ub:function(){Ca()}});
var Da=0,Ea=0,K=0,Fa=0,Ga=0,Ha=null,Ia=null,Ja=!1;function Ka(){for(var a=L.length-1;0<=a;--a)La(a);L=[];Ma=[]}var Ma=[];function Na(){if(Oa&&Pa.bb)for(var a=0;a<Ma.length;++a){var b=Ma[a];Ma.splice(a,1);--a;b.Eb.apply(this,b.yb)}}var Oa=0,Pa=null,L=[];function Qa(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function La(a){var b=L[a];b.target.removeEventListener(b.ab,b.sb,b.cb);L.splice(a,1)}
function M(a){function b(b){++Oa;Pa=a;Na();a.fb(b);Na();--Oa}if(a.eb)a.sb=b,a.target.addEventListener(a.ab,b,a.cb),L.push(a),Ja||(sa.push(Ka),Ja=!0);else for(var c=0;c<L.length;++c)L[c].target==a.target&&L[c].ab==a.ab&&La(c--)}var Ra=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function N(a){try{if(!a)return window;"number"===typeof a&&(a=Ra[a]||z(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?e.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function Sa(a){"number"===typeof a&&(a=z(a));return a&&"#canvas"!==a?"undefined"!==typeof Ta&&Ua[a]?Ua[a]:N(a):"undefined"!==typeof Ta&&Ua.canvas?Ua.canvas:e.canvas}
function Va(a,b,c,d,g,k){Da||(Da=P(164));a={target:N(a),bb:Qa()?!1:!0,ab:k,eb:d,fb:function(a){a=a||window.event;var c=Da;B(a.key?a.key:"",A,c+0,32);B(a.code?a.code:"",A,c+32,32);D[c+64>>2]=a.location;D[c+68>>2]=a.ctrlKey;D[c+72>>2]=a.shiftKey;D[c+76>>2]=a.altKey;D[c+80>>2]=a.metaKey;D[c+84>>2]=a.repeat;B(a.locale?a.locale:"",A,c+88,32);B(a.char?a.char:"",A,c+120,32);D[c+152>>2]=a.charCode;D[c+156>>2]=a.keyCode;D[c+160>>2]=a.which;Q(d,g,c,b)&&a.preventDefault()},cb:c};M(a)}
function Wa(a,b,c){E[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();D[a+8>>2]=b.screenX;D[a+12>>2]=b.screenY;D[a+16>>2]=b.clientX;D[a+20>>2]=b.clientY;D[a+24>>2]=b.ctrlKey;D[a+28>>2]=b.shiftKey;D[a+32>>2]=b.altKey;D[a+36>>2]=b.metaKey;na[a+40>>1]=b.button;na[a+42>>1]=b.buttons;D[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-Ha;D[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-Ia;if(e.canvas){var d=e.canvas.getBoundingClientRect();
D[a+60>>2]=b.clientX-d.left;D[a+64>>2]=b.clientY-d.top}else D[a+60>>2]=0,D[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},D[a+52>>2]=b.clientX-d.left,D[a+56>>2]=b.clientY-d.top):(D[a+52>>2]=0,D[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(Ha=b.screenX,Ia=b.screenY)}
function R(a,b,c,d,g,k){Ea||(Ea=P(72));a=N(a);c={target:a,bb:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,ab:k,eb:d,fb:function(c){c=c||window.event;Wa(Ea,c,a);Q(d,g,Ea,b)&&c.preventDefault()},cb:c};Qa()&&"mousedown"==k&&(c.bb=!1);M(c)}
function Za(a,b,c,d){Fa||(Fa=P(36));a=N(a);M({target:a,bb:!1,ab:"resize",eb:d,fb:function(c){c=c||window.event;if(c.target==a){var g=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],l=Fa;D[l>>2]=c.detail;D[l+4>>2]=document.body.clientWidth;
D[l+8>>2]=document.body.clientHeight;D[l+12>>2]=window.innerWidth;D[l+16>>2]=window.innerHeight;D[l+20>>2]=window.outerWidth;D[l+24>>2]=window.outerHeight;D[l+28>>2]=g[0];D[l+32>>2]=g[1];Q(d,10,l,b)&&c.preventDefault()}},cb:c})}
function $a(a,b,c,d,g,k){Ga||(Ga=P(1684));a=N(a);M({target:a,bb:"touchstart"==k||"touchend"==k,ab:k,eb:d,fb:function(c){c=c||window.event;for(var l={},k=0;k<c.touches.length;++k){var n=c.touches[k];l[n.identifier]=n}for(k=0;k<c.changedTouches.length;++k)n=c.changedTouches[k],l[n.identifier]=n,n.rb=!0;for(k=0;k<c.targetTouches.length;++k)n=c.targetTouches[k],l[n.identifier].wb=!0;var m=n=Ga;D[m+4>>2]=c.ctrlKey;D[m+8>>2]=c.shiftKey;D[m+12>>2]=c.altKey;D[m+16>>2]=c.metaKey;m+=20;var va=e.canvas?e.canvas.getBoundingClientRect():
void 0,Xa=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},Ya=0;for(k in l){var t=l[k];D[m>>2]=t.identifier;D[m+4>>2]=t.screenX;D[m+8>>2]=t.screenY;D[m+12>>2]=t.clientX;D[m+16>>2]=t.clientY;D[m+20>>2]=t.pageX;D[m+24>>2]=t.pageY;D[m+28>>2]=t.rb;D[m+32>>2]=t.wb;va?(D[m+44>>2]=t.clientX-va.left,D[m+48>>2]=t.clientY-va.top):(D[m+44>>2]=0,D[m+48>>2]=0);D[m+36>>2]=t.clientX-Xa.left;D[m+40>>2]=t.clientY-Xa.top;m+=52;if(32<=++Ya)break}D[n>>2]=Ya;Q(d,g,n,b)&&c.preventDefault()},cb:c})}
function ab(a,b,c,d,g,k){a||(a=e.canvas);a={target:N(a),bb:!1,ab:k,eb:d,fb:function(a){a=a||window.event;Q(d,g,0,b)&&a.preventDefault()},cb:c};M(a)}
function bb(a,b,c,d,g){function k(c){c=c||window.event;Wa(K,c,a);E[K+72>>3]=c.wheelDeltaX||0;E[K+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);E[K+88>>3]=0;D[K+96>>2]=0;Q(d,9,K,b)&&c.preventDefault()}function l(c){c=c||window.event;var g=K;Wa(g,c,a);E[g+72>>3]=c.deltaX;E[g+80>>3]=c.deltaY;E[g+88>>3]=c.deltaZ;D[g+96>>2]=c.deltaMode;Q(d,9,g,b)&&c.preventDefault()}K||(K=P(104));M({target:a,bb:!0,ab:g,eb:d,fb:"wheel"==g?l:k,cb:c})}
var cb=1,db=0,eb=[],S=[],fb=[],gb=[],hb=[],T=[],U=[],ib=[],jb={},V=null,Ua={},W={},kb={};function X(a){db||(db=a)}function Y(a){for(var b=cb++,c=a.length;c<b;c++)a[c]=null;return b}function lb(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=P(8),g={handle:d,attributes:b,version:b.ob,kb:a};g.pb=2<=g.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.xb=g);jb[d]=g;("undefined"===typeof b.nb||b.nb)&&mb(g);return d}
function mb(a){a||(a=V);if(!a.vb){a.vb=!0;var b=a.kb;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,g){c.drawArraysInstancedANGLE(a,b,d,g)},b.drawElementsInstanced=function(a,b,d,g,k){c.drawElementsInstancedANGLE(a,b,d,g,k)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var g=b.getExtension("WEBGL_draw_buffers");g&&(b.drawBuffers=function(a,b){g.drawBuffersWEBGL(a,b)})}b.Ab=b.getExtension("EXT_disjoint_timer_query");var k="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=k.indexOf(a)&&b.getExtension(a)})}}var Ta={},nb,ob,pb=["default","low-power","high-performance"],qb=[];function rb(a,b,c,d){for(var g=0;g<a;g++){var k=Z[c](),l=k&&Y(d);k?(k.name=l,d[l]=k):X(1282);D[b+4*g>>2]=l}}
function sb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){X(1282);return}d=Z.getSupportedExtensions();c=null===d?0:2*d.length;break;case 33307:case 33308:if(2>V.version){X(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":X(1280);return;case "object":if(null===
d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=0;break;default:X(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)D[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(g){X(1280);x("GL_INVALID_ENUM in glGetIntegerv: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:X(1280);return}D[b>>2]=c}else X(1281)}
function tb(a){var b=ja(a)+1,c=P(b);B(a,A,c,b);return c}function ub(){e.___errno_location&&(D[e.___errno_location()>>2]=12)}function vb(a){a=ma(a);var b=buffer.byteLength;try{return-1!==y.grow((a-b)/65536)?(buffer=y.buffer,!0):!1}catch(c){return!1}}for(var Z,wb=0;256>wb;wb++);for(var xb=0;32>xb;xb++)qb.push(Array(xb));
var Db=e.asm({},{R:function(){return window.devicePixelRatio||1},S:function(a,b,c){a=a?N(a):e.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),E[b>>3]=a.right-a.left,E[c>>3]=a.bottom-a.top):(E[b>>3]=a.clientWidth,E[c>>3]=a.clientHeight);return 0},T:function(a,b,c){A.set(A.subarray(b,b+c),a)},za:function(a,b){function c(d){yb(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},P:function(a,b,c){a=Sa(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ia:function(a,
b,c,d){Va(a,b,c,d,2,"keydown");return 0},Ga:function(a,b,c,d){Va(a,b,c,d,1,"keypress");return 0},Ha:function(a,b,c,d){Va(a,b,c,d,3,"keyup");return 0},fa:function(a,b,c,d){R(a,b,c,d,5,"mousedown");return 0},La:function(a,b,c,d){R(a,b,c,d,33,"mouseenter");return 0},Ka:function(a,b,c,d){R(a,b,c,d,34,"mouseleave");return 0},V:function(a,b,c,d){R(a,b,c,d,8,"mousemove");return 0},ba:function(a,b,c,d){R(a,b,c,d,6,"mouseup");return 0},Ma:function(a,b,c,d){Za(a,b,c,d);return 0},Ca:function(a,b,c,d){$a(a,b,
c,d,25,"touchcancel");return 0},Da:function(a,b,c,d){$a(a,b,c,d,23,"touchend");return 0},Ea:function(a,b,c,d){$a(a,b,c,d,24,"touchmove");return 0},Fa:function(a,b,c,d){$a(a,b,c,d,22,"touchstart");return 0},Ba:function(a,b,c,d){ab(a,b,c,d,31,"webglcontextlost");return 0},Aa:function(a,b,c,d){ab(a,b,c,d,32,"webglcontextrestored");return 0},Ja:function(a,b,c,d){a=N(a);return"undefined"!==typeof a.onwheel?(bb(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(bb(a,b,c,d,"mousewheel"),0):-1},J:function(a,
b){var c={};b>>=2;c.alpha=!!D[b];c.depth=!!D[b+1];c.stencil=!!D[b+2];c.antialias=!!D[b+3];c.premultipliedAlpha=!!D[b+4];c.preserveDrawingBuffer=!!D[b+5];c.powerPreference=pb[D[b+6]];c.failIfMajorPerformanceCaveat=!!D[b+7];c.ob=D[b+8];c.Bb=D[b+9];c.nb=D[b+10];c.tb=D[b+11];c.Cb=D[b+12];c.Db=D[b+13];a=Sa(a);!a||c.tb?c=0:c=(a=1<c.ob?a.getContext("webgl2",c):a.getContext("webgl",c)||a.getContext("experimental-webgl",c))&&lb(a,c);return c},qa:function(a){a>>=2;for(var b=0;14>b;++b)D[a+b]=0;D[a]=D[a+1]=
D[a+3]=D[a+4]=D[a+8]=D[a+10]=1},la:function(a){V=jb[a];e.zb=Z=V&&V.kb;return!a||Z?0:-5},o:function(a){Z.activeTexture(a)},y:function(a,b){Z.attachShader(S[a],U[b])},d:function(a,b){35051==a?Z.lb=b:35052==a&&(Z.mb=b);Z.bindBuffer(a,eb[b])},f:function(a,b){Z.bindFramebuffer(a,fb[b])},b:function(a,b){Z.bindTexture(a,hb[b])},Q:function(a){Z.bindVertexArray(ib[a])},G:function(a,b,c,d){Z.blendColor(a,b,c,d)},H:function(a,b){Z.blendEquationSeparate(a,b)},I:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},
m:function(a,b,c,d,g,k,l,v,O,n){Z.blitFramebuffer(a,b,c,d,g,k,l,v,O,n)},z:function(a,b,c,d){V.pb?c?Z.bufferData(a,A,d,c,b):Z.bufferData(a,b,d):Z.bufferData(a,c?A.subarray(c,c+b):b,d)},B:function(a,b,c,d){V.pb?Z.bufferSubData(a,b,A,d,c):Z.bufferSubData(a,b,A.subarray(d,d+c))},M:function(a){Z.clear(a)},pa:function(a,b,c,d){Z.clearColor(a,b,c,d)},oa:function(a){Z.clearDepth(a)},na:function(a){Z.clearStencil(a)},u:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},Z:function(a){Z.compileShader(U[a])},da:function(){var a=
Y(S),b=Z.createProgram();b.name=a;S[a]=b;return a},$:function(a){var b=Y(U);U[b]=Z.createShader(a);return b},F:function(a){Z.cullFace(a)},ua:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],g=eb[d];g&&(Z.deleteBuffer(g),g.name=0,eb[d]=null,d==nb&&(nb=0),d==ob&&(ob=0),d==Z.lb&&(Z.lb=0),d==Z.mb&&(Z.mb=0))}},h:function(a,b){for(var c=0;c<a;++c){var d=D[b+4*c>>2],g=fb[d];g&&(Z.deleteFramebuffer(g),g.name=0,fb[d]=null)}},N:function(a){if(a){var b=S[a];b?(Z.deleteProgram(b),b.name=0,S[a]=null,W[a]=
null):X(1281)}},O:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],g=gb[d];g&&(Z.deleteRenderbuffer(g),g.name=0,gb[d]=null)}},q:function(a){if(a){var b=U[a];b?(Z.deleteShader(b),U[a]=null):X(1281)}},ta:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],g=hb[d];g&&(Z.deleteTexture(g),g.name=0,hb[d]=null)}},va:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2];Z.deleteVertexArray(ib[d]);ib[d]=null}},s:function(a){Z.depthFunc(a)},t:function(a){Z.depthMask(!!a)},c:function(a){Z.disable(a)},a:function(a){Z.disableVertexAttribArray(a)},
ga:function(a,b,c){Z.drawArrays(a,b,c)},p:function(a,b){for(var c=qb[a],d=0;d<a;d++)c[d]=D[b+4*d>>2];Z.drawBuffers(c)},ha:function(a,b,c,d){Z.drawElements(a,b,c,d)},e:function(a){Z.enable(a)},ia:function(a){Z.enableVertexAttribArray(a)},E:function(a){Z.frontFace(a)},A:function(a,b){rb(a,b,"createBuffer",eb)},wa:function(a,b){rb(a,b,"createVertexArray",ib)},X:function(a,b){return Z.getAttribLocation(S[a],z(b))},v:function(a,b){sb(a,b)},aa:function(a,b,c,d){a=Z.getProgramInfoLog(S[a]);null===a&&(a=
"(unknown error)");0<b&&d?(b=B(a,A,d,b),c&&(D[c>>2]=b)):c&&(D[c>>2]=0)},x:function(a,b,c){if(c)if(a>=cb)X(1281);else{var d=W[a];if(d)if(35716==b)a=Z.getProgramInfoLog(S[a]),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b)D[c>>2]=d.jb;else if(35722==b){if(-1==d.gb){a=S[a];var g=Z.getProgramParameter(a,35721);for(b=d.gb=0;b<g;++b)d.gb=Math.max(d.gb,Z.getActiveAttrib(a,b).name.length+1)}D[c>>2]=d.gb}else if(35381==b){if(-1==d.hb)for(a=S[a],g=Z.getProgramParameter(a,35382),b=d.hb=
0;b<g;++b)d.hb=Math.max(d.hb,Z.getActiveUniformBlockName(a,b).length+1);D[c>>2]=d.hb}else D[c>>2]=Z.getProgramParameter(S[a],b);else X(1282)}else X(1281)},Y:function(a,b,c,d){a=Z.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");0<b&&d?(b=B(a,A,d,b),c&&(D[c>>2]=b)):c&&(D[c>>2]=0)},w:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1):35720==b?(a=Z.getShaderSource(U[a]),D[c>>2]=null===a||0==a.length?0:a.length+1):D[c>>2]=Z.getShaderParameter(U[a],
b):X(1281)},xa:function(a){if(kb[a])return kb[a];switch(a){case 7939:var b=Z.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=tb(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||X(1280);b=tb(b);break;case 7938:b=Z.getParameter(Z.VERSION);b=2<=V.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=tb(b);break;case 35724:b=Z.getParameter(Z.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=tb(b);break;default:return X(1280),0}return kb[a]=b},g:function(a,b){b=z(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=W[a]&&W[a].qb[b])&&0<=c&&c<a[0]?a[1]+c:-1},ca:function(a){Z.linkProgram(S[a]);var b=S[a];a=W[a]={qb:{},jb:0,gb:-1,hb:-1};for(var c=a.qb,d=Z.getProgramParameter(b,35718),g=0;g<d;++g){var k=Z.getActiveUniform(b,g),l=k.name;a.jb=
Math.max(a.jb,l.length+1);"]"==l.slice(-1)&&(l=l.slice(0,l.lastIndexOf("[")));var v=Z.getUniformLocation(b,l);if(v){var O=Y(T);c[l]=[k.size,O];T[O]=v;for(var n=1;n<k.size;++n)v=Z.getUniformLocation(b,l+"["+n+"]"),O=Y(T),T[O]=v}}},D:function(a,b){Z.polygonOffset(a,b)},n:function(a){Z.readBuffer(a)},ra:function(a,b,c,d){Z.scissor(a,b,c,d)},_:function(a,b,c,d){for(var g="",k=0;k<b;++k){var l=d?D[d+4*k>>2]:-1;g+=z(D[c+4*k>>2],0>l?void 0:l)}Z.shaderSource(U[a],g)},W:function(a,b,c){Z.stencilFunc(a,b,c)},
L:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},r:function(a){Z.stencilMask(a)},U:function(a,b,c){Z.stencilOp(a,b,c)},K:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},C:function(a,b){Z.uniform1i(T[a],b)},ma:function(a){Z.useProgram(S[a])},ja:function(a,b){Z.vertexAttribDivisor(a,b)},ka:function(a,b,c,d,g,k){Z.vertexAttribPointer(a,b,c,!!d,g,k)},sa:function(a,b,c,d){Z.viewport(a,b,c,d)},l:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize=
"none";a.addEventListener("focusout",function(){zb()});document.body.append(a)},k:function(){document.getElementById("_sokol_app_input_element").focus()},ya:function(){window.addEventListener("beforeunload",function(a){0!=Ab()&&(a.preventDefault(),a.returnValue=" ")})},j:function(){document.getElementById("_sokol_app_input_element").blur()},i:function(a){a|=0;var b=C.length|0;var c=D[5856]|0;var d=c+a|0;if(0<(a|0)&(d|0)<(c|0)|0>(d|0))return u("OOM"),0,ub(),-1;if(a=(d|0)>(b|0)){a=d|0;if(2147418112<
a)a=!1;else{for(b=Math.max(C.length,16777216);b<a;)536870912>=b?b=ma(2*b):b=Math.min(ma((3*b+2147483648)/4),2147418112);vb(b)?(oa(),a=!0):a=!1}a=!(a|0)}if(a)return ub(),-1;D[5856]=d|0;return c|0},ea:function(a,b,c,d,g,k){b=z(b);var l=new XMLHttpRequest;l.open("GET",b);l.responseType="arraybuffer";var v=!(0==c&&d==g);v&&l.setRequestHeader("Range","bytes="+c+"-"+(c+d));l.onreadystatechange=function(){if(this.readyState==this.DONE)if(206==this.status||200==this.status&&!v){var b=new Uint8Array(l.response);
A.set(b,k);Bb(a,d)}else Cb(a)};l.send()}},buffer);e.asm=Db;var Ca=e.___wasm_call_ctors=function(){return e.asm.Na.apply(null,arguments)},zb=e.__sapp_emsc_notify_keyboard_hidden=function(){return e.asm.Oa.apply(null,arguments)},Ab=e.__sapp_html5_get_ask_leave_site=function(){return e.asm.Pa.apply(null,arguments)};e._main=function(){return e.asm.Qa.apply(null,arguments)};var P=e._malloc=function(){return e.asm.Ra.apply(null,arguments)};e._free=function(){return e.asm.Sa.apply(null,arguments)};
e.__saudio_emsc_pull=function(){return e.asm.Ta.apply(null,arguments)};e.__sfetch_emsc_head_response=function(){return e.asm.Ua.apply(null,arguments)};var Bb=e.__sfetch_emsc_range_response=function(){return e.asm.Va.apply(null,arguments)},Cb=e.__sfetch_emsc_failed=function(){return e.asm.Wa.apply(null,arguments)},la=e.stackAlloc=function(){return e.asm.Xa.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.Ya.apply(null,arguments)};e.dynCall_v=function(){return e.asm.Za.apply(null,arguments)};
var Q=e.dynCall_iiii=function(){return e.asm._a.apply(null,arguments)},yb=e.dynCall_idi=function(){return e.asm.$a.apply(null,arguments)};e.asm=Db;function w(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}w.prototype=Error();w.prototype.constructor=w;I=function Eb(){e.calledRun||Fb();e.calledRun||(I=Eb)};
e.callMain=function(a){a=a||[];var b=a.length+1,c=la(4*(b+1));D[c>>2]=ka(e.thisProgram);for(var d=1;d<b;d++)D[(c>>2)+d]=ka(a[d-1]);D[(c>>2)+b]=0;try{var g=e._main(b,c,0);if(!e.noExitRuntime||0!==g){if(!e.noExitRuntime&&(ha=!0,e.onExit))e.onExit(g);e.quit(g,new w(g))}}catch(k){k instanceof w||("SimulateInfiniteLoop"==k?e.noExitRuntime=!0:((a=k)&&"object"===typeof k&&k.stack&&(a=[k,k.stack]),x("exception thrown: "+a),e.quit(1,k)))}finally{}};
function Fb(a){function b(){if(!e.calledRun&&(e.calledRun=!0,!ha)){G(qa);G(ra);if(e.onRuntimeInitialized)e.onRuntimeInitialized();e._main&&Gb&&e.callMain(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();ta.unshift(b)}G(ta)}}a=a||e.arguments;if(!(0<H)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)ua();G(pa);0<H||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);b()},1)):b())}}e.run=Fb;function u(a){if(e.onAbort)e.onAbort(a);void 0!==a?(fa(a),x(a),a='"'+a+'"'):a="";ha=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=u;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Gb=!0;e.noInitialRun&&(Gb=!1);e.noExitRuntime=!0;Fb();
