var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],k="./this.program",ca=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,ha,ia;
if(ea){var fs=require("fs"),ja=require("path");q=l?ja.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=a.startsWith("file://")?new URL(a):ja.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ia=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};ha=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ja.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,h)=>{e?c(e):b(d?h.buffer:h)})};!g.thisProgram&&1<process.argv.length&&(k=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=
typeof module&&(module.exports=g);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof ka||a.context instanceof ka))throw a;});ca=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},
l&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var la=g.print||console.log.bind(console),r=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(k=g.thisProgram);
g.quit&&(ca=g.quit);var u;g.wasmBinary&&(u=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&ma("no native wasm support detected");var na,oa=!1,pa,w,qa,ra,x,y,z,A;function sa(){var a=na.buffer;g.HEAP8=pa=new Int8Array(a);g.HEAP16=qa=new Int16Array(a);g.HEAPU8=w=new Uint8Array(a);g.HEAPU16=ra=new Uint16Array(a);g.HEAP32=x=new Int32Array(a);g.HEAPU32=y=new Uint32Array(a);g.HEAPF32=z=new Float32Array(a);g.HEAPF64=A=new Float64Array(a)}
var ta,ua=[],va=[],wa=[],xa=[],ya=[];function za(){var a=g.preRun.shift();ua.unshift(a)}var B=0,Aa=null,C=null;function ma(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";r(a);oa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ba(a){return a.startsWith("data:application/octet-stream;base64,")}var D;D="restart-sapp.wasm";if(!Ba(D)){var Ca=D;D=g.locateFile?g.locateFile(Ca,q):q+Ca}
function Da(a){if(a==D&&u)return new Uint8Array(u);if(ia)return ia(a);throw"both async and sync fetching of the wasm failed";}function Ea(a){if(!u&&(da||l)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Da(a));if(ha)return new Promise((b,c)=>{ha(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Da(a))}
function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{r(`failed to asynchronously prepare wasm: ${d}`);ma(d)})}
function Ga(a,b){var c=D;u||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||c.startsWith("file://")||ea||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){r(`wasm streaming compile failed: ${e}`);r("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}function ka(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ha=a=>{for(;0<a.length;)a.shift()(g)},Ia="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,E=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ia)return Ia.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=
String.fromCharCode(e)}return d},La=a=>{var b=Ja();a();Ka(b)},Ma=0;function Na(){for(var a=F.length-1;0<=a;--a)Oa(a);F=[];Pa=[]}var Pa=[];function Qa(){if(navigator.userActivation?navigator.userActivation.isActive:Ma&&Ra.rc)for(var a=0;a<Pa.length;++a){var b=Pa[a];Pa.splice(a,1);--a;b.bd.apply(null,b.Tc)}}var F=[];function Oa(a){var b=F[a];b.target.removeEventListener(b.ic,b.Oc,b.jc);F.splice(a,1)}
function G(a){function b(d){++Ma;Ra=a;Qa();a.lc(d);Qa();--Ma}if(!a.target)return-4;if(a.kc)a.Oc=b,a.target.addEventListener(a.ic,b,a.jc),F.push(a),Sa||(xa.push(Na),Sa=!0);else for(var c=0;c<F.length;++c)F[c].target==a.target&&F[c].ic==a.ic&&Oa(c--);return 0}function Ta(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Sa,Ra,Ua,Va,Wa,Xa,Ya,Za,$a,ab=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],H=a=>{a=2<a?a?E(w,a):"":a;return ab[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},bb=a=>0>ab.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},cb=[],I=a=>{var b=cb[a];b||(a>=cb.length&&(cb.length=a+1),cb[a]=b=ta.get(a));return b},J=(a,b,c)=>{var d=w;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var m=
a.charCodeAt(++h);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},db=(a,b,c,d,e,h)=>{Ua||(Ua=K(256));a={target:H(a),ic:h,kc:d,lc:(f=event)=>{var m=f.target.id?f.target.id:"",n=Ua;J(Ta(f.target),n+0,128);J(m,n+128,128);I(d)(e,n,b)&&f.preventDefault()},jc:c};return G(a)},eb=
(a,b,c,d,e,h)=>{Va||(Va=K(176));a={target:H(a),rc:!0,ic:h,kc:d,lc:f=>{var m=Va;A[m>>3]=f.timeStamp;var n=m>>2;x[n+2]=f.location;x[n+3]=f.ctrlKey;x[n+4]=f.shiftKey;x[n+5]=f.altKey;x[n+6]=f.metaKey;x[n+7]=f.repeat;x[n+8]=f.charCode;x[n+9]=f.keyCode;x[n+10]=f.which;J(f.key||"",m+44,32);J(f.code||"",m+76,32);J(f.char||"",m+108,32);J(f.locale||"",m+140,32);I(d)(e,m,b)&&f.preventDefault()},jc:c};return G(a)},fb=(a,b,c)=>{A[a>>3]=b.timeStamp;a>>=2;x[a+2]=b.screenX;x[a+3]=b.screenY;x[a+4]=b.clientX;x[a+5]=
b.clientY;x[a+6]=b.ctrlKey;x[a+7]=b.shiftKey;x[a+8]=b.altKey;x[a+9]=b.metaKey;qa[2*a+20]=b.button;qa[2*a+21]=b.buttons;x[a+11]=b.movementX;x[a+12]=b.movementY;c=bb(c);x[a+13]=b.clientX-c.left;x[a+14]=b.clientY-c.top},L=(a,b,c,d,e,h)=>{Wa||(Wa=K(72));a=H(a);return G({target:a,rc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ic:h,kc:d,lc:(f=event)=>{fb(Wa,f,a);I(d)(e,Wa,b)&&f.preventDefault()},jc:c})},gb=(a,b,c,d,e)=>{Xa||(Xa=K(260));return G({target:a,ic:e,kc:d,lc:(h=event)=>{var f=Xa,m=document.pointerLockElement||
document.oc||document.Cc||document.Ac;x[f>>2]=!!m;var n=m&&m.id?m.id:"";J(Ta(m),f+4,128);J(n,f+132,128);I(d)(20,f,b)&&h.preventDefault()},jc:c})},hb=(a,b,c,d,e)=>G({target:a,ic:e,kc:d,lc:(h=event)=>{I(d)(38,0,b)&&h.preventDefault()},jc:c}),ib=(a,b,c,d)=>{Ya||(Ya=K(36));a=H(a);return G({target:a,ic:"resize",kc:d,lc:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=Ya;x[f>>2]=e.detail;x[f+4>>2]=h.clientWidth;x[f+8>>2]=h.clientHeight;x[f+12>>2]=innerWidth;x[f+16>>2]=innerHeight;x[f+20>>2]=
outerWidth;x[f+24>>2]=outerHeight;x[f+28>>2]=pageXOffset;x[f+32>>2]=pageYOffset;I(d)(10,f,b)&&e.preventDefault()}}},jc:c})},jb=(a,b,c,d,e,h)=>{Za||(Za=K(1696));a=H(a);return G({target:a,rc:"touchstart"==h||"touchend"==h,ic:h,kc:d,lc:f=>{for(var m,n={},p=f.touches,t=0;t<p.length;++t)m=p[t],m.Bc=m.Ec=0,n[m.identifier]=m;for(t=0;t<f.changedTouches.length;++t)m=f.changedTouches[t],m.Bc=1,n[m.identifier]=m;for(t=0;t<f.targetTouches.length;++t)n[f.targetTouches[t].identifier].Ec=1;p=Za;A[p>>3]=f.timeStamp;
var v=p>>2;x[v+3]=f.ctrlKey;x[v+4]=f.shiftKey;x[v+5]=f.altKey;x[v+6]=f.metaKey;v+=7;var P=bb(a),W=0;for(t in n)if(m=n[t],x[v]=m.identifier,x[v+1]=m.screenX,x[v+2]=m.screenY,x[v+3]=m.clientX,x[v+4]=m.clientY,x[v+5]=m.pageX,x[v+6]=m.pageY,x[v+7]=m.Bc,x[v+8]=m.Ec,x[v+9]=m.clientX-P.left,x[v+10]=m.clientY-P.top,v+=13,31<++W)break;x[p+8>>2]=W;I(d)(e,p,b)&&f.preventDefault()},jc:c})},kb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},lb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},mb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},nb=a=>{a.Vc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
ob=a=>{a.Wc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},pb=1,qb=[],M=[],rb=[],sb=[],tb=[],N=[],ub=[],vb=[],O=[],wb={},xb=4;function Q(a){yb||(yb=a)}
for(var zb=a=>{for(var b=pb++,c=a.length;c<b;c++)a[c]=null;return b},Bb=(a,b)=>{a.oc||(a.oc=a.getContext,a.getContext=function(d,e){e=a.oc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Dc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Ab(c,b):0},Ab=(a,b)=>{var c=zb(vb),d={handle:c,attributes:b,version:b.Dc,vc:a};a.canvas&&(a.canvas.Sc=d);vb[c]=d;("undefined"==typeof b.zc||b.zc)&&Cb(d);return c},Cb=a=>{a||(a=R);if(!a.Qc){a.Qc=!0;var b=a.vc;kb(b);lb(b);mb(b);
nb(b);ob(b);2<=a.version&&(b.yc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.yc)b.yc=b.getExtension("EXT_disjoint_timer_query");b.Rc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},yb,R,Db=(a,b,c,d,e,h)=>{a={target:H(a),ic:h,kc:d,lc:(f=event)=>{I(d)(e,0,b)&&f.preventDefault()},jc:c};G(a)},Eb=(a,b,c,d)=>{$a||($a=K(104));return G({target:a,rc:!0,ic:"wheel",kc:d,lc:(e=event)=>
{var h=$a;fb(h,e,a);A[h+72>>3]=e.deltaX;A[h+80>>3]=e.deltaY;A[h+88>>3]=e.deltaZ;x[h+96>>2]=e.deltaMode;I(d)(9,h,b)&&e.preventDefault()},jc:c})},Fb=["default","low-power","high-performance"],Gb={},Ib=()=>{if(!Hb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:k||"./this.program"},b;for(b in Gb)void 0===Gb[b]?delete a[b]:a[b]=Gb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);
Hb=c}return Hb},Hb,Jb=[null,[],[]],T=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=S[c](),f=h&&zb(d);h?(h.name=f,d[f]=h):Q(1282);x[b+4*e>>2]=f}},Kb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>R.version){Q(1282);return}c=2*(S.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>R.version){Q(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),
typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Q(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:Q(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)x[b+
4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Q(1280);r("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:Q(1280);r("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}x[b>>2]=c}else Q(1281)},Lb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Mb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),
Nb=[],Ob=a=>{a-=5120;return 0==a?pa:1==a?w:2==a?qa:4==a?x:6==a?z:5==a||28922==a||28520==a||30779==a||30782==a?y:ra},U=a=>{var b=S.Nc;if(b){var c=b.qc[a];"number"==typeof c&&(b.qc[a]=c=S.getUniformLocation(b,b.Lc[a]+(0<c?"["+c+"]":"")));return c}Q(1282)},V=[],X=[],Pb=a=>{if(!noExitRuntime){if(g.onExit)g.onExit(a);oa=!0}ca(a,new ka(a))},Rb=a=>{var b=Lb(a)+1,c=Qb(b);J(a,c,b);return c},S,Y=0;32>Y;++Y)Nb.push(Array(Y));var Sb=new Float32Array(288);for(Y=0;288>Y;++Y)V[Y]=Sb.subarray(0,Y+1);var Tb=new Int32Array(288);
for(Y=0;288>Y;++Y)X[Y]=Tb.subarray(0,Y+1);
var ec={ia:function(){return 0},hb:function(){return 0},ib:function(){},i:()=>{ma("")},kb:()=>Date.now(),da:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ea:(a,b,c)=>{a=H(a);if(!a)return-4;a=bb(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},ja:()=>performance.now(),jb:(a,b,c)=>w.copyWithin(a,b,b+c),Ya:(a,b)=>{function c(d){I(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},cb:a=>{var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=
Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-na.buffer.byteLength+65535)/65536;try{na.grow(e);sa();var h=1;break a}catch(f){}h=void 0}if(h)return!0}return!1},N:(a,b,c,d)=>db(a,b,c,d,12,"blur"),ca:(a,b,c)=>{a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},O:(a,b,c,d)=>db(a,b,c,d,13,"focus"),X:(a,b,c,d)=>eb(a,b,c,d,2,"keydown"),V:(a,b,c,d)=>eb(a,b,c,d,1,"keypress"),W:(a,b,c,d)=>eb(a,b,c,d,3,"keyup"),ba:(a,b,c,d)=>L(a,b,c,d,5,"mousedown"),
_:(a,b,c,d)=>L(a,b,c,d,33,"mouseenter"),Z:(a,b,c,d)=>L(a,b,c,d,34,"mouseleave"),$:(a,b,c,d)=>L(a,b,c,d,8,"mousemove"),aa:(a,b,c,d)=>L(a,b,c,d,6,"mouseup"),Q:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.oc||document.body.Cc||document.body.Ac))return-1;a=H(a);if(!a)return-4;gb(a,b,c,d,"mozpointerlockchange");gb(a,b,c,d,"webkitpointerlockchange");gb(a,b,c,d,"mspointerlockchange");return gb(a,b,c,d,"pointerlockchange")},P:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||
document.body.oc||document.body.Cc||document.body.Ac))return-1;a=H(a);if(!a)return-4;hb(a,b,c,d,"mozpointerlockerror");hb(a,b,c,d,"webkitpointerlockerror");hb(a,b,c,d,"mspointerlockerror");return hb(a,b,c,d,"pointerlockerror")},Za:(a,b,c,d)=>ib(a,b,c,d),R:(a,b,c,d)=>jb(a,b,c,d,25,"touchcancel"),S:(a,b,c,d)=>jb(a,b,c,d,23,"touchend"),T:(a,b,c,d)=>jb(a,b,c,d,24,"touchmove"),U:(a,b,c,d)=>jb(a,b,c,d,22,"touchstart"),M:(a,b,c,d)=>{Db(a,b,c,d,31,"webglcontextlost");return 0},L:(a,b,c,d)=>{Db(a,b,c,d,32,
"webglcontextrestored");return 0},Y:(a,b,c,d)=>(a=H(a))?"undefined"!=typeof a.onwheel?Eb(a,b,c,d):-1:-4,Wa:(a,b)=>{b>>=2;b={alpha:!!x[b],depth:!!x[b+1],stencil:!!x[b+2],antialias:!!x[b+3],premultipliedAlpha:!!x[b+4],preserveDrawingBuffer:!!x[b+5],powerPreference:Fb[x[b+6]],failIfMajorPerformanceCaveat:!!x[b+7],Dc:x[b+8],Xc:x[b+9],zc:x[b+10],Pc:x[b+11],Yc:x[b+12],Zc:x[b+13]};a=H(a);return!a||b.Pc?0:Bb(a,b)},Ua:(a,b)=>{a=vb[a];b=b?E(w,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==
b&&kb(S);"OES_vertex_array_object"==b&&lb(S);"WEBGL_draw_buffers"==b&&mb(S);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&nb(S);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&ob(S);"WEBGL_multi_draw"==b&&(S.Rc=S.getExtension("WEBGL_multi_draw"));return!!a.vc.getExtension(b)},Xa:a=>{a>>=2;for(var b=0;14>b;++b)x[a+b]=0;x[a]=x[a+1]=x[a+3]=x[a+4]=x[a+8]=x[a+10]=1},Va:a=>{R=vb[a];g.Uc=S=R&&R.vc;return!a||S?0:-5},db:(a,b)=>{var c=0;Ib().forEach((d,e)=>{var h=b+c;e=y[a+4*e>>2]=h;for(h=
0;h<d.length;++h)pa[e++>>0]=d.charCodeAt(h);pa[e>>0]=0;c+=d.length+1});return 0},eb:(a,b)=>{var c=Ib();y[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);y[b>>2]=d;return 0},ha:()=>52,gb:()=>52,bb:function(){return 70},fb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var f=y[b>>2],m=y[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=w[f+n],t=Jb[a];0===p||10===p?((1===a?la:r)(E(t,0)),t.length=0):t.push(p)}e+=m}y[d>>2]=e;return 0},f:function(a){S.activeTexture(a)},A:(a,b)=>{S.attachShader(M[a],N[b])},b:(a,b)=>{35051==
a?S.xc=b:35052==a&&(S.nc=b);S.bindBuffer(a,qb[b])},m:(a,b)=>{S.bindFramebuffer(a,rb[b])},Ca:(a,b)=>{S.bindRenderbuffer(a,sb[b])},g:(a,b)=>{S.bindSampler(a,O[b])},a:(a,b)=>{S.bindTexture(a,tb[b])},J:a=>{S.bindVertexArray(ub[a])},F:function(a,b,c,d){S.blendColor(a,b,c,d)},G:function(a,b){S.blendEquationSeparate(a,b)},H:function(a,b,c,d){S.blendFuncSeparate(a,b,c,d)},mb:function(a,b,c,d,e,h,f,m,n,p){S.blitFramebuffer(a,b,c,d,e,h,f,m,n,p)},Ea:(a,b,c,d)=>{2<=R.version?c&&b?S.bufferData(a,w,d,c,b):S.bufferData(a,
b,d):S.bufferData(a,c?w.subarray(c,c+b):b,d)},n:(a,b,c,d)=>{2<=R.version?c&&S.bufferSubData(a,b,w,d,c):S.bufferSubData(a,b,w.subarray(d,d+c))},Hb:function(a,b,c,d){S.clearBufferfi(a,b,c,d)},ma:(a,b,c)=>{S.clearBufferfv(a,b,z,c>>2)},Gb:(a,b,c)=>{S.clearBufferiv(a,b,x,c>>2)},j:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},Kb:a=>{S.compileShader(N[a])},za:(a,b,c,d,e,h,f,m)=>{2<=R.version?S.nc||!f?S.compressedTexImage2D(a,b,c,d,e,h,f,m):S.compressedTexImage2D(a,b,c,d,e,h,w,m,f):S.compressedTexImage2D(a,b,
c,d,e,h,m?w.subarray(m,m+f):null)},wa:(a,b,c,d,e,h,f,m,n)=>{S.nc?S.compressedTexImage3D(a,b,c,d,e,h,f,m,n):S.compressedTexImage3D(a,b,c,d,e,h,f,w,n,m)},ta:()=>{var a=zb(M),b=S.createProgram();b.name=a;b.uc=b.sc=b.tc=0;b.wc=1;M[a]=b;return a},Mb:a=>{var b=zb(N);N[b]=S.createShader(a);return b},C:function(a){S.cullFace(a)},Qa:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=qb[d];e&&(S.deleteBuffer(e),e.name=0,qb[d]=null,d==S.xc&&(S.xc=0),d==S.nc&&(S.nc=0))}},k:(a,b)=>{for(var c=0;c<a;++c){var d=x[b+
4*c>>2],e=rb[d];e&&(S.deleteFramebuffer(e),e.name=0,rb[d]=null)}},w:a=>{if(a){var b=M[a];b?(S.deleteProgram(b),b.name=0,M[a]=null):Q(1281)}},Oa:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=sb[d];e&&(S.deleteRenderbuffer(e),e.name=0,sb[d]=null)}},K:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=O[d];e&&(S.deleteSampler(e),e.name=0,O[d]=null)}},s:a=>{if(a){var b=N[a];b?(S.deleteShader(b),N[a]=null):Q(1281)}},Pa:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=tb[d];e&&(S.deleteTexture(e),e.name=
0,tb[d]=null)}},Ma:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2];S.deleteVertexArray(ub[d]);ub[d]=null}},v:function(a){S.depthFunc(a)},u:a=>{S.depthMask(!!a)},d:function(a){S.disable(a)},I:a=>{S.disableVertexAttribArray(a)},ob:(a,b,c)=>{S.drawArrays(a,b,c)},pb:(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},qb:(a,b,c,d)=>{S.drawElements(a,b,c,d)},rb:(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},h:function(a){S.enable(a)},Cb:a=>{S.enableVertexAttribArray(a)},D:function(a){S.frontFace(a)},Fa:(a,b)=>
{T(a,b,"createBuffer",qb)},Da:(a,b)=>{T(a,b,"createRenderbuffer",sb)},ua:(a,b)=>{T(a,b,"createSampler",O)},Aa:(a,b)=>{T(a,b,"createTexture",tb)},La:function(a,b){T(a,b,"createVertexArray",ub)},Ib:(a,b)=>S.getAttribLocation(M[a],b?E(w,b):""),c:(a,b)=>{Kb(a,b)},Nb:(a,b,c,d)=>{a=S.getProgramInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?J(a,d,b):0;c&&(x[c>>2]=b)},ra:(a,b,c)=>{if(c)if(a>=pb)Q(1281);else if(a=M[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),x[c>>2]=a.length+
1;else if(35719==b){if(!a.uc)for(b=0;b<S.getProgramParameter(a,35718);++b)a.uc=Math.max(a.uc,S.getActiveUniform(a,b).name.length+1);x[c>>2]=a.uc}else if(35722==b){if(!a.sc)for(b=0;b<S.getProgramParameter(a,35721);++b)a.sc=Math.max(a.sc,S.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.sc}else if(35381==b){if(!a.tc)for(b=0;b<S.getProgramParameter(a,35382);++b)a.tc=Math.max(a.tc,S.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.tc}else x[c>>2]=S.getProgramParameter(a,b);else Q(1281)},Jb:(a,b,c,d)=>
{a=S.getShaderInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?J(a,d,b):0;c&&(x[c>>2]=b)},pa:(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(N[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(N[a]),x[c>>2]=a?a.length+1:0):x[c>>2]=S.getShaderParameter(N[a],b):Q(1281)},Ra:(a,b)=>{if(2>R.version)return Q(1282),0;var c=wb[a];if(c)return 0>b||b>=c.length?(Q(1281),0):c[b];switch(a){case 7939:return c=S.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+
d})),c=c.map(function(d){var e=Lb(d)+1,h=K(e);h&&J(d,h,e);return h}),c=wb[a]=c,0>b||b>=c.length?(Q(1281),0):c[b];default:return Q(1280),0}},q:(a,b)=>{b=b?E(w,b):"";if(a=M[a]){var c=a,d=c.qc,e=c.Mc,h;if(!d)for(c.qc=d={},c.Lc={},h=0;h<S.getProgramParameter(c,35718);++h){var f=S.getActiveUniform(c,h);var m=f.name;f=f.size;var n=Mb(m);n=0<n?m.slice(0,n):m;var p=c.wc;c.wc+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.Lc[p++]=n}c=a.qc;d=0;e=b;h=Mb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Mc[e])&&
d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else Q(1281);return-1},lb:(a,b,c)=>{for(var d=Nb[b],e=0;e<b;e++)d[e]=x[c+4*e>>2];S.invalidateFramebuffer(a,d)},sa:a=>{a=M[a];S.linkProgram(a);a.qc=0;a.Mc={}},Ka:(a,b)=>{3317==a&&(xb=b);S.pixelStorei(a,b)},E:function(a,b){S.polygonOffset(a,b)},nb:function(a){S.readBuffer(a)},Ba:function(a,b,c,d,e){S.renderbufferStorageMultisample(a,b,c,d,e)},B:(a,b,c)=>{S.samplerParameterf(O[a],b,c)},e:(a,b,c)=>{S.samplerParameteri(O[a],b,c)},na:function(a,
b,c,d){S.scissor(a,b,c,d)},Lb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=d?x[d+4*h>>2]:-1,m=x[c+4*h>>2];f=m?E(w,m,0>f?void 0:f):"";e+=f}S.shaderSource(N[a],e)},Ia:function(a,b,c){S.stencilFunc(a,b,c)},la:function(a,b,c,d){S.stencilFuncSeparate(a,b,c,d)},t:function(a){S.stencilMask(a)},Ha:function(a,b,c){S.stencilOp(a,b,c)},ka:function(a,b,c,d){S.stencilOpSeparate(a,b,c,d)},xa:(a,b,c,d,e,h,f,m,n)=>{if(2<=R.version)if(S.nc)S.texImage2D(a,b,c,d,e,h,f,m,n);else if(n){var p=Ob(m);S.texImage2D(a,b,c,d,
e,h,f,m,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else S.texImage2D(a,b,c,d,e,h,f,m,null);else{p=S;var t=p.texImage2D;if(n){var v=Ob(m),P=31-Math.clz32(v.BYTES_PER_ELEMENT),W=xb;n=v.subarray(n>>P,n+e*(d*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*(1<<P)+W-1&-W)>>P)}else n=null;t.call(p,a,b,c,d,e,h,f,m,n)}},va:(a,b,c,d,e,h,f,m,n,p)=>{if(S.nc)S.texImage3D(a,b,c,d,e,h,f,m,n,p);else if(p){var t=Ob(n);S.texImage3D(a,b,c,d,e,h,f,m,n,t,p>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else S.texImage3D(a,
b,c,d,e,h,f,m,n,null)},Bb:(a,b,c)=>{if(2<=R.version)b&&S.uniform1fv(U(a),z,c>>2,b);else{if(288>=b)for(var d=V[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);S.uniform1fv(U(a),d)}},qa:(a,b)=>{S.uniform1i(U(a),b)},xb:(a,b,c)=>{if(2<=R.version)b&&S.uniform1iv(U(a),x,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);S.uniform1iv(U(a),d)}},Ab:(a,b,c)=>{if(2<=R.version)b&&S.uniform2fv(U(a),z,c>>2,2*b);else{if(144>=b)for(var d=V[2*b-
1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);S.uniform2fv(U(a),d)}},wb:(a,b,c)=>{if(2<=R.version)b&&S.uniform2iv(U(a),x,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);S.uniform2iv(U(a),d)}},zb:(a,b,c)=>{if(2<=R.version)b&&S.uniform3fv(U(a),z,c>>2,3*b);else{if(96>=b)for(var d=V[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=
z.subarray(c>>2,c+12*b>>2);S.uniform3fv(U(a),d)}},vb:(a,b,c)=>{if(2<=R.version)b&&S.uniform3iv(U(a),x,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);S.uniform3iv(U(a),d)}},yb:(a,b,c)=>{if(2<=R.version)b&&S.uniform4fv(U(a),z,c>>2,4*b);else{if(72>=b){var d=V[4*b-1],e=z;c>>=2;for(var h=0;h<4*b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=z.subarray(c>>2,c+16*b>>2);
S.uniform4fv(U(a),d)}},ub:(a,b,c)=>{if(2<=R.version)b&&S.uniform4iv(U(a),x,c>>2,4*b);else{if(72>=b)for(var d=X[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*b>>2);S.uniform4iv(U(a),d)}},tb:(a,b,c,d)=>{if(2<=R.version)b&&S.uniformMatrix4fv(U(a),!!c,z,d>>2,16*b);else{if(18>=b){var e=V[16*b-1],h=z;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=h[m];e[f+1]=h[m+1];e[f+2]=h[m+2];e[f+3]=h[m+3];e[f+4]=h[m+4];e[f+5]=
h[m+5];e[f+6]=h[m+6];e[f+7]=h[m+7];e[f+8]=h[m+8];e[f+9]=h[m+9];e[f+10]=h[m+10];e[f+11]=h[m+11];e[f+12]=h[m+12];e[f+13]=h[m+13];e[f+14]=h[m+14];e[f+15]=h[m+15]}}else e=z.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(U(a),!!c,e)}},l:a=>{a=M[a];S.useProgram(a);S.Nc=a},Eb:(a,b)=>{S.vertexAttribDivisor(a,b)},Fb:(a,b,c,d,e,h)=>{S.vertexAttribPointer(a,b,c,!!d,e,h)},oa:function(a,b,c,d){S.viewport(a,b,c,d)},Ta:function(){g.Fc=a=>{0!=Ub()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",
g.Fc)},Na:function(){g.Kc=a=>{const b=a.clipboardData.getData("text");La(()=>{const c=Rb(b);Vb(c)})};window.addEventListener("paste",g.Kc)},Ga:function(a){g.$c=[];a=a?E(w,a):"";a=document.getElementById(a);g.Gc=b=>{b.stopPropagation();b.preventDefault()};g.Hc=b=>{b.stopPropagation();b.preventDefault()};g.Ic=b=>{b.stopPropagation();b.preventDefault()};g.Jc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.ad=c;Wb(c.length);for(let e=0;e<c.length;e++)La(()=>{const h=Rb(c[e].name);
Xb(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Yb(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.Gc,!1);a.addEventListener("dragleave",g.Hc,!1);a.addEventListener("dragover",g.Ic,!1);a.addEventListener("drop",g.Jc,!1)},Db:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},r:function(){const a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",
function(){Zb()});document.body.append(a)},p:function(){document.getElementById("_sokol_app_input_element").focus()},Ob:function(a){a=a?E(w,a):"";g.pc=document.getElementById(a);g.pc||console.log("sokol_app.h: invalid target:"+a);g.pc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Sa:function(){window.removeEventListener("beforeunload",g.Fc)},Ja:function(){window.removeEventListener("paste",g.Kc)},ya:function(a){a=a?E(w,a):"";a=document.getElementById(a);
a.removeEventListener("dragenter",g.Gc);a.removeEventListener("dragleave",g.Hc);a.removeEventListener("dragover",g.Ic);a.removeEventListener("drop",g.Jc)},z:function(){g.pc&&g.pc.requestPointerLock&&g.pc.requestPointerLock()},sb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(w.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=
d.toDataURL();document.head.appendChild(a)},o:function(){document.getElementById("_sokol_app_input_element").blur()},_a:function(){return g.mc?g.mc.bufferSize:0},ab:function(a,b,c){g.hc=null;g.mc=null;"undefined"!==typeof AudioContext?g.hc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.hc=null,console.log("sokol_audio.h: no WebAudio support"));return g.hc?(console.log("sokol_audio.h: sample rate ",g.hc.sampleRate),g.mc=g.hc.createScriptProcessor(c,0,b),g.mc.onaudioprocess=d=>{const e=
d.outputBuffer.length,h=$b(e);if(h){const f=d.outputBuffer.numberOfChannels;for(let m=0;m<f;m++){const n=d.outputBuffer.getChannelData(m);for(let p=0;p<e;p++)n[p]=z[(h>>2)+(f*p+m)]}}},g.mc.connect(g.hc.destination),a=()=>{g.hc&&"suspended"===g.hc.state&&g.hc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},$a:function(){return g.hc?g.hc.sampleRate:0},y:function(){const a=g.hc;null!==a&&
(g.mc&&g.mc.disconnect(),a.close(),g.hc=null,g.mc=null)},x:function(a,b,c,d,e,h){b=b?E(w,b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const m=0<d;m&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!m){const n=new Uint8Array(f.response),p=n.length;p<=h?(w.set(n,e),ac(a,d,p)):bc(a)}else cc(a,f.status)};f.send()},ga:function(a,b){b=b?E(w,b):"";const c=new XMLHttpRequest;
c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");dc(a,d)}else cc(a,c.status)};c.send()},fa:function(a,b){b=b?E(w,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c=c.exports;na=Z.Pb;sa();ta=Z.dc;va.unshift(Z.Qb);B--;g.monitorRunDependencies&&g.monitorRunDependencies(B);if(0==B&&(null!==Aa&&
(clearInterval(Aa),Aa=null),C)){var d=C;C=null;d()}return c}var b={a:ec};B++;g.monitorRunDependencies&&g.monitorRunDependencies(B);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return r(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ga(b,function(c){a(c.instance)});return{}}(),K=a=>(K=Z.Rb)(a),Zb=g.__sapp_emsc_notify_keyboard_hidden=()=>(Zb=g.__sapp_emsc_notify_keyboard_hidden=Z.Sb)(),Vb=g.__sapp_emsc_onpaste=a=>(Vb=g.__sapp_emsc_onpaste=Z.Tb)(a),Ub=g.__sapp_html5_get_ask_leave_site=
()=>(Ub=g.__sapp_html5_get_ask_leave_site=Z.Ub)(),Wb=g.__sapp_emsc_begin_drop=a=>(Wb=g.__sapp_emsc_begin_drop=Z.Vb)(a),Xb=g.__sapp_emsc_drop=(a,b)=>(Xb=g.__sapp_emsc_drop=Z.Wb)(a,b),Yb=g.__sapp_emsc_end_drop=(a,b,c)=>(Yb=g.__sapp_emsc_end_drop=Z.Xb)(a,b,c);g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,f,m)=>(g.__sapp_emsc_invoke_fetch_cb=Z.Yb)(a,b,c,d,e,h,f,m);
var fc=g._main=(a,b)=>(fc=g._main=Z.Zb)(a,b),$b=g.__saudio_emsc_pull=a=>($b=g.__saudio_emsc_pull=Z._b)(a),dc=g.__sfetch_emsc_head_response=(a,b)=>(dc=g.__sfetch_emsc_head_response=Z.$b)(a,b),ac=g.__sfetch_emsc_get_response=(a,b,c)=>(ac=g.__sfetch_emsc_get_response=Z.ac)(a,b,c),cc=g.__sfetch_emsc_failed_http_status=(a,b)=>(cc=g.__sfetch_emsc_failed_http_status=Z.bc)(a,b),bc=g.__sfetch_emsc_failed_buffer_too_small=a=>(bc=g.__sfetch_emsc_failed_buffer_too_small=Z.cc)(a),Ja=()=>(Ja=Z.ec)(),Ka=a=>(Ka=
Z.fc)(a),Qb=a=>(Qb=Z.gc)(a);g.___start_em_js=40768;g.___stop_em_js=50443;var gc;C=function hc(){gc||ic();gc||(C=hc)};function jc(a=[]){var b=fc;a.unshift(k);var c=a.length,d=Qb(4*(c+1)),e=d;a.forEach(f=>{y[e>>2]=Rb(f);e+=4});y[e>>2]=0;try{var h=b(c,d);Pb(h)}catch(f){f instanceof ka||"unwind"==f||ca(1,f)}}
function ic(){var a=ba;function b(){if(!gc&&(gc=!0,g.calledRun=!0,!oa)){Ha(va);Ha(wa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();kc&&jc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();ya.unshift(c)}Ha(ya)}}if(!(0<B)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)za();Ha(ua);0<B||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var kc=!0;g.noInitialRun&&(kc=!1);ic();
