var e;e||(e=typeof Module !== 'undefined' ? Module : {});var f={},l;for(l in e)e.hasOwnProperty(l)&&(f[l]=e[l]);var q=[],aa="./this.program";function u(a,b){throw b;}var v=!1,w=!1,ba=!1,ca=!1,da=!1;v="object"===typeof window;w="function"===typeof importScripts;ba=(ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!v&&!w;da=!v&&!ba&&!w;var x="",y,z,ea,fa;
if(ba)x=__dirname+"/",y=function(a,b){ea||(ea=require("fs"));fa||(fa=require("path"));a=fa.normalize(a);return ea.readFileSync(a,b?null:"utf8")},z=function(a){a=y(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),q=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",function(a){if(!(a instanceof ha))throw a;}),process.on("unhandledRejection",A),u=function(a){process.exit(a)},
e.inspect=function(){return"[Emscripten Module object]"};else if(da)"undefined"!=typeof read&&(y=function(a){return read(a)}),z=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?q=scriptArgs:"undefined"!=typeof arguments&&(q=arguments),"function"===typeof quit&&(u=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=
console.error="undefined"!==typeof printErr?printErr:print);else if(v||w)w?x=self.location.href:document.currentScript&&(x=document.currentScript.src),x=0!==x.indexOf("blob:")?x.substr(0,x.lastIndexOf("/")+1):"",y=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},w&&(z=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var ia=e.print||console.log.bind(console),B=e.printErr||console.warn.bind(console);for(l in f)f.hasOwnProperty(l)&&(e[l]=f[l]);f=null;e.arguments&&(q=e.arguments);e.thisProgram&&(aa=e.thisProgram);e.quit&&(u=e.quit);var C;e.wasmBinary&&(C=e.wasmBinary);var D;e.noExitRuntime&&(D=e.noExitRuntime);"object"!==typeof WebAssembly&&B("no native wasm support detected");var E,ja=new WebAssembly.Table({initial:15,maximum:15,element:"anyfunc"}),ka=!1;function assert(a,b){a||A("Assertion failed: "+b)}
function la(){var a=e.__sapp_emsc_onpaste;assert(a,"Cannot call unknown function _sapp_emsc_onpaste, make sure it is exported");return a}function ma(a){var b=["string"],c={string:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=F(c);G(a,H,b,c)}return b},array:function(a){var b=F(a.length);I.set(a,b);return b}},d=la(),g=[],h=0;if(a)for(var k=0;k<a.length;k++){var p=c[b[k]];p?(0===h&&(h=na()),g[k]=p(a[k])):g[k]=a[k]}d.apply(null,g);0!==h&&oa(h)}
var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a){if(a){for(var b=H,c=a+void 0,d=a;b[d]&&!(d>=c);)++d;if(16<d-a&&b.subarray&&pa)a=pa.decode(b.subarray(a,d));else{for(c="";a<d;){var g=b[a++];if(g&128){var h=b[a++]&63;if(192==(g&224))c+=String.fromCharCode((g&31)<<6|h);else{var k=b[a++]&63;g=224==(g&240)?(g&15)<<12|h<<6|k:(g&7)<<18|h<<12|k<<6|b[a++]&63;65536>g?c+=String.fromCharCode(g):(g-=65536,c+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else c+=String.fromCharCode(g)}a=c}}else a="";return a}
function G(a,b,c,d){if(0<d){d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var k=a.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0}}
function ra(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function sa(a){var b=ra(a)+1,c=F(b);G(a,I,c,b);return c}function ta(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,I,H,ua,J,va,K;
function xa(a){buffer=a;e.HEAP8=I=new Int8Array(a);e.HEAP16=ua=new Int16Array(a);e.HEAP32=J=new Int32Array(a);e.HEAPU8=H=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAPU32=new Uint32Array(a);e.HEAPF32=va=new Float32Array(a);e.HEAPF64=K=new Float64Array(a)}var ya=e.TOTAL_MEMORY||33554432;e.wasmMemory?E=e.wasmMemory:E=new WebAssembly.Memory({initial:ya/65536});E&&(buffer=E.buffer);ya=buffer.byteLength;xa(buffer);J[4844]=5262416;
function za(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.ob;"number"===typeof c?void 0===b.gb?e.dynCall_v(c):e.dynCall_vi(c,b.gb):c(void 0===b.gb?null:b.gb)}}}var Aa=[],Ba=[],Ca=[],Da=[],Ea=[];function Fa(){var a=e.preRun.shift();Aa.unshift(a)}var L=0,Ga=null,M=null;e.preloadedImages={};e.preloadedAudios={};function A(a){if(e.onAbort)e.onAbort(a);ia(a);B(a);ka=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function Ha(){var a=N;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var N="saudio-sapp.wasm";if(!Ha()){var Ia=N;N=e.locateFile?e.locateFile(Ia,x):x+Ia}function Ja(){try{if(C)return new Uint8Array(C);if(z)return z(N);throw"both async and sync fetching of the wasm failed";}catch(a){A(a)}}
function Ka(){return C||!v&&!w||"function"!==typeof fetch?new Promise(function(a){a(Ja())}):fetch(N,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+N+"'";return a.arrayBuffer()}).catch(function(){return Ja()})}Ba.push({ob:function(){La()}});var Ma=0,Na=0,O=0,Oa=0,Pa=0,Qa=null,Ra=null,Sa=!1;function Ta(){for(var a=P.length-1;0<=a;--a)Ua(a);P=[];Va=[]}var Va=[];
function Wa(){if(Xa&&Ya.$a)for(var a=0;a<Va.length;++a){var b=Va[a];Va.splice(a,1);--a;b.zb.apply(this,b.sb)}}var Xa=0,Ya=null,P=[];function Za(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function Ua(a){var b=P[a];b.target.removeEventListener(b.Za,b.mb,b.ab);P.splice(a,1)}
function Q(a){function b(b){++Xa;Ya=a;Wa();a.cb(b);Wa();--Xa}if(a.bb)a.mb=b,a.target.addEventListener(a.Za,b,a.ab),P.push(a),Sa||(Da.push(Ta),Sa=!0);else for(var c=0;c<P.length;++c)P[c].target==a.target&&P[c].Za==a.Za&&Ua(c--)}var $a=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function R(a){try{if(!a)return window;"number"===typeof a&&(a=$a[a]||qa(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?e.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function cb(a){"number"===typeof a&&(a=qa(a));return a&&"#canvas"!==a?"undefined"!==typeof db&&eb[a]?eb[a]:R(a):"undefined"!==typeof db&&eb.canvas?eb.canvas:e.canvas}
function fb(a,b,c,d,g,h){Ma||(Ma=S(164));a={target:R(a),$a:Za()?!1:!0,Za:h,bb:d,cb:function(a){a=a||event;var c=Ma;G(a.key?a.key:"",H,c+0,32);G(a.code?a.code:"",H,c+32,32);J[c+64>>2]=a.location;J[c+68>>2]=a.ctrlKey;J[c+72>>2]=a.shiftKey;J[c+76>>2]=a.altKey;J[c+80>>2]=a.metaKey;J[c+84>>2]=a.repeat;G(a.locale?a.locale:"",H,c+88,32);G(a.char?a.char:"",H,c+120,32);J[c+152>>2]=a.charCode;J[c+156>>2]=a.keyCode;J[c+160>>2]=a.which;T(d,g,c,b)&&a.preventDefault()},ab:c};Q(a)}
function gb(a,b,c){K[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();J[a+8>>2]=b.screenX;J[a+12>>2]=b.screenY;J[a+16>>2]=b.clientX;J[a+20>>2]=b.clientY;J[a+24>>2]=b.ctrlKey;J[a+28>>2]=b.shiftKey;J[a+32>>2]=b.altKey;J[a+36>>2]=b.metaKey;ua[a+40>>1]=b.button;ua[a+42>>1]=b.buttons;J[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-Qa;J[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-Ra;if(e.canvas){var d=e.canvas.getBoundingClientRect();
J[a+60>>2]=b.clientX-d.left;J[a+64>>2]=b.clientY-d.top}else J[a+60>>2]=0,J[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},J[a+52>>2]=b.clientX-d.left,J[a+56>>2]=b.clientY-d.top):(J[a+52>>2]=0,J[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(Qa=b.screenX,Ra=b.screenY)}
function U(a,b,c,d,g,h){Na||(Na=S(72));a=R(a);c={target:a,$a:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Za:h,bb:d,cb:function(c){c=c||event;gb(Na,c,a);T(d,g,Na,b)&&c.preventDefault()},ab:c};Za()&&"mousedown"==h&&(c.$a=!1);Q(c)}
function hb(a,b,c,d){Oa||(Oa=S(36));a=R(a);Q({target:a,$a:!1,Za:"resize",bb:d,cb:function(c){c=c||event;if(c.target==a){var g=0<pageXOffset||0<pageYOffset?[pageXOffset,pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],k=Oa;J[k>>2]=c.detail;J[k+4>>2]=document.body.clientWidth;J[k+8>>2]=document.body.clientHeight;
J[k+12>>2]=innerWidth;J[k+16>>2]=innerHeight;J[k+20>>2]=outerWidth;J[k+24>>2]=outerHeight;J[k+28>>2]=g[0];J[k+32>>2]=g[1];T(d,10,k,b)&&c.preventDefault()}},ab:c})}
function ib(a,b,c,d,g,h){Pa||(Pa=S(1684));a=R(a);Q({target:a,$a:"touchstart"==h||"touchend"==h,Za:h,bb:d,cb:function(c){c=c||event;for(var h={},k=0;k<c.touches.length;++k){var n=c.touches[k];n.hb=!1;h[n.identifier]=n}for(k=0;k<c.changedTouches.length;++k)n=c.changedTouches[k],h[n.identifier]=n,n.hb=!0;for(k=0;k<c.targetTouches.length;++k)n=c.targetTouches[k],h[n.identifier].qb=!0;var m=n=Pa;J[m+4>>2]=c.ctrlKey;J[m+8>>2]=c.shiftKey;J[m+12>>2]=c.altKey;J[m+16>>2]=c.metaKey;m+=20;var wa=e.canvas?e.canvas.getBoundingClientRect():
void 0,ab=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},bb=0;for(k in h){var r=h[k];J[m>>2]=r.identifier;J[m+4>>2]=r.screenX;J[m+8>>2]=r.screenY;J[m+12>>2]=r.clientX;J[m+16>>2]=r.clientY;J[m+20>>2]=r.pageX;J[m+24>>2]=r.pageY;J[m+28>>2]=r.hb;J[m+32>>2]=r.qb;wa?(J[m+44>>2]=r.clientX-wa.left,J[m+48>>2]=r.clientY-wa.top):(J[m+44>>2]=0,J[m+48>>2]=0);J[m+36>>2]=r.clientX-ab.left;J[m+40>>2]=r.clientY-ab.top;m+=52;if(32<=++bb)break}J[n>>2]=bb;T(d,g,n,b)&&c.preventDefault()},ab:c})}
function jb(a,b,c,d,g,h){a||(a=e.canvas);a={target:R(a),$a:!1,Za:h,bb:d,cb:function(a){a=a||event;T(d,g,0,b)&&a.preventDefault()},ab:c};Q(a)}
function kb(a,b,c,d,g){function h(c){c=c||event;gb(O,c,a);K[O+72>>3]=c.wheelDeltaX||0;K[O+80>>3]=-(c.wheelDeltaY||c.wheelDelta);K[O+88>>3]=0;J[O+96>>2]=0;T(d,9,O,b)&&c.preventDefault()}function k(c){c=c||event;var g=O;gb(g,c,a);K[g+72>>3]=c.deltaX;K[g+80>>3]=c.deltaY;K[g+88>>3]=c.deltaZ;J[g+96>>2]=c.deltaMode;T(d,9,g,b)&&c.preventDefault()}O||(O=S(104));Q({target:a,$a:!0,Za:g,bb:d,cb:"wheel"==g?k:h,ab:c})}var lb=1,mb=0,nb=[],ob=[],pb=[],qb=[],rb=[],V=[],sb={},W=null,eb={},tb={},ub={};
function X(a){mb||(mb=a)}function vb(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=S(8),g={handle:d,attributes:b,version:b.lb,fb:a};g.yb=2<=g.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.rb=g);sb[d]=g;("undefined"===typeof b.kb||b.kb)&&wb(g);return d}
function xb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(a,d){b.vertexAttribDivisorANGLE(a,d)},a.drawArraysInstanced=function(a,d,g,h){b.drawArraysInstancedANGLE(a,d,g,h)},a.drawElementsInstanced=function(a,d,g,h,k){b.drawElementsInstancedANGLE(a,d,g,h,k)})}
function yb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(a){b.deleteVertexArrayOES(a)},a.bindVertexArray=function(a){b.bindVertexArrayOES(a)},a.isVertexArray=function(a){return b.isVertexArrayOES(a)})}function zb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(a,d){b.drawBuffersWEBGL(a,d)})}
function wb(a){a||(a=W);if(!a.pb){a.pb=!0;var b=a.fb;2>a.version&&(xb(b),yb(b),zb(b));b.ub=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(a){-1!=c.indexOf(a)&&b.getExtension(a)})}}var db={},Ab,Bb,Cb=["default","low-power","high-performance"],Db=[];
function Eb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Y.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>W.version){X(1282);return}c=2*(Y.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>W.version){X(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=Y.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":X(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=
0;break;default:X(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)J[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(g){X(1280);B("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:X(1280);B("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}J[b>>2]=c}else X(1281)}
function Z(a){var b=ra(a)+1,c=S(b);G(a,H,c,b);return c}for(var Y,Fb=0;256>Fb;Fb++);for(var Gb=0;32>Gb;Gb++)Db.push(Array(Gb));
var Ob={x:function(){return devicePixelRatio||1},y:function(a,b,c){a=a?R(a):e.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),K[b>>3]=a.right-a.left,K[c>>3]=a.bottom-a.top):(K[b>>3]=a.clientWidth,K[c>>3]=a.clientHeight);return 0},B:function(a,b,c){H.set(H.subarray(b,b+c),a)},da:function(a,b){function c(d){Hb(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},C:function(a){if(2147418112<a)return!1;for(var b=Math.max(I.length,16777216);b<a;)536870912>=b?b=ta(2*
b):b=Math.min(ta((3*b+2147483648)/4),2147418112);a:{try{E.grow(b-buffer.byteLength+65535>>16);xa(E.buffer);var c=1;break a}catch(d){}c=void 0}return c?!0:!1},t:function(a,b,c){a=cb(a);if(!a)return-4;a.width=b;a.height=c;return 0},na:function(a,b,c,d){fb(a,b,c,d,2,"keydown");return 0},la:function(a,b,c,d){fb(a,b,c,d,1,"keypress");return 0},ma:function(a,b,c,d){fb(a,b,c,d,3,"keyup");return 0},z:function(a,b,c,d){U(a,b,c,d,5,"mousedown");return 0},qa:function(a,b,c,d){U(a,b,c,d,33,"mouseenter");return 0},
pa:function(a,b,c,d){U(a,b,c,d,34,"mouseleave");return 0},ra:function(a,b,c,d){U(a,b,c,d,8,"mousemove");return 0},sa:function(a,b,c,d){U(a,b,c,d,6,"mouseup");return 0},ia:function(a,b,c,d){hb(a,b,c,d);return 0},ga:function(a,b,c,d){ib(a,b,c,d,25,"touchcancel");return 0},ha:function(a,b,c,d){ib(a,b,c,d,23,"touchend");return 0},ja:function(a,b,c,d){ib(a,b,c,d,24,"touchmove");return 0},ka:function(a,b,c,d){ib(a,b,c,d,22,"touchstart");return 0},fa:function(a,b,c,d){jb(a,b,c,d,31,"webglcontextlost");return 0},
ea:function(a,b,c,d){jb(a,b,c,d,32,"webglcontextrestored");return 0},oa:function(a,b,c,d){a=R(a);return"undefined"!==typeof a.onwheel?(kb(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(kb(a,b,c,d,"mousewheel"),0):-1},n:function(a,b){var c={};b>>=2;c.alpha=!!J[b];c.depth=!!J[b+1];c.stencil=!!J[b+2];c.antialias=!!J[b+3];c.premultipliedAlpha=!!J[b+4];c.preserveDrawingBuffer=!!J[b+5];c.powerPreference=Cb[J[b+6]];c.failIfMajorPerformanceCaveat=!!J[b+7];c.lb=J[b+8];c.vb=J[b+9];c.kb=J[b+10];c.nb=
J[b+11];c.wb=J[b+12];c.xb=J[b+13];a=cb(a);!a||c.nb?c=0:c=(a=1<c.lb?a.getContext("webgl2",c):a.getContext("webgl",c)||a.getContext("experimental-webgl",c))?vb(a,c):0;return c},A:function(a,b){a=sb[a];b=qa(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b?xb(Y):"OES_vertex_array_object"==b?yb(Y):"WEBGL_draw_buffers"==b&&zb(Y);return!!a.fb.getExtension(b)},S:function(a){a>>=2;for(var b=0;14>b;++b)J[a+b]=0;J[a]=J[a+1]=J[a+3]=J[a+4]=J[a+8]=J[a+10]=1},D:function(a){W=sb[a];e.tb=Y=W&&W.fb;
return!a||Y?0:-5},u:function(a){Y.activeTexture(a)},l:function(a,b){35051==a?Y.ib=b:35052==a&&(Y.jb=b);Y.bindBuffer(a,nb[b])},c:function(a,b){Y.bindFramebuffer(a,pb[b])},b:function(a,b){Y.bindTexture(a,rb[b])},w:function(a){Y.bindVertexArray(V[a])},O:function(a,b,c,d){Y.blendColor(a,b,c,d)},P:function(a,b){Y.blendEquationSeparate(a,b)},Q:function(a,b,c,d){Y.blendFuncSeparate(a,b,c,d)},i:function(a,b,c,d,g,h,k,p,t,n){Y.blitFramebuffer(a,b,c,d,g,h,k,p,t,n)},o:function(a){Y.clear(a)},U:function(a,b,
c,d){Y.clearColor(a,b,c,d)},T:function(a){Y.clearDepth(a)},R:function(a){Y.clearStencil(a)},s:function(a,b,c,d){Y.colorMask(!!a,!!b,!!c,!!d)},N:function(a){Y.cullFace(a)},Z:function(a,b){for(var c=0;c<a;c++){var d=J[b+4*c>>2],g=nb[d];g&&(Y.deleteBuffer(g),g.name=0,nb[d]=null,d==Ab&&(Ab=0),d==Bb&&(Bb=0),d==Y.ib&&(Y.ib=0),d==Y.jb&&(Y.jb=0))}},e:function(a,b){for(var c=0;c<a;++c){var d=J[b+4*c>>2],g=pb[d];g&&(Y.deleteFramebuffer(g),g.name=0,pb[d]=null)}},X:function(a){if(a){var b=ob[a];b?(Y.deleteProgram(b),
b.name=0,ob[a]=null):X(1281)}},v:function(a,b){for(var c=0;c<a;c++){var d=J[b+4*c>>2],g=qb[d];g&&(Y.deleteRenderbuffer(g),g.name=0,qb[d]=null)}},Y:function(a,b){for(var c=0;c<a;c++){var d=J[b+4*c>>2],g=rb[d];g&&(Y.deleteTexture(g),g.name=0,rb[d]=null)}},_:function(a,b){for(var c=0;c<a;c++){var d=J[b+4*c>>2];Y.deleteVertexArray(V[d]);V[d]=null}},q:function(a){Y.depthFunc(a)},r:function(a){Y.depthMask(!!a)},d:function(a){Y.disable(a)},K:function(a){Y.disableVertexAttribArray(a)},k:function(a,b){for(var c=
Db[a],d=0;d<a;d++)c[d]=J[b+4*d>>2];Y.drawBuffers(c)},m:function(a){Y.enable(a)},M:function(a){Y.frontFace(a)},$:function(a,b){for(var c=0;c<a;c++){var d=Y.createVertexArray(),g;if(g=d){g=V;for(var h=lb++,k=g.length;k<h;k++)g[k]=null;g=h}d?(d.name=g,V[g]=d):X(1282);J[b+4*c>>2]=g}},a:function(a,b){Eb(a,b)},ba:function(a){if(tb[a])return tb[a];switch(a){case 7939:var b=Y.getSupportedExtensions()||[];b=b.concat(b.map(function(a){return"GL_"+a}));b=Z(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
Y.getParameter(a))||X(1280);b=Z(b);break;case 7938:b=Y.getParameter(Y.VERSION);b=2<=W.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Z(b);break;case 35724:b=Y.getParameter(Y.SHADING_LANGUAGE_VERSION);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Z(b);break;default:return X(1280),0}return tb[a]=b},aa:function(a,b){if(2>W.version)return X(1282),0;var c=ub[a];if(c)return 0>b||b>=c.length?(X(1281),
0):c[b];switch(a){case 7939:return c=Y.getSupportedExtensions()||[],c=c.concat(c.map(function(a){return"GL_"+a})),c=c.map(function(a){return Z(a)}),c=ub[a]=c,0>b||b>=c.length?(X(1281),0):c[b];default:return X(1280),0}},L:function(a,b){Y.polygonOffset(a,b)},j:function(a){Y.readBuffer(a)},V:function(a,b,c,d){Y.scissor(a,b,c,d)},J:function(a,b,c){Y.stencilFunc(a,b,c)},p:function(a){Y.stencilMask(a)},I:function(a,b,c){Y.stencilOp(a,b,c)},W:function(a,b,c,d){Y.viewport(a,b,c,d)},memory:E,h:function(){var a=
document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Ib()});document.body.append(a)},g:function(){document.getElementById("_sokol_app_input_element").focus()},ca:function(){window.addEventListener("beforeunload",function(a){0!=Jb()&&(a.preventDefault(),a.returnValue=" ")})},ta:function(){window.addEventListener("paste",function(a){a=a.clipboardData.getData("text");ma([a])})},f:function(){document.getElementById("_sokol_app_input_element").blur()},
F:function(){return e.eb?e.eb.bufferSize:0},H:function(a,b,c){e.Ya=null;e.eb=null;"undefined"!==typeof AudioContext?(e.Ya=new AudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created AudioContext")):"undefined"!==typeof webkitAudioContext?(e.Ya=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created webkitAudioContext")):(e.Ya=null,console.log("sokol_audio.h: no WebAudio support"));return e.Ya?(console.log("sokol_audio.h: sample rate ",
e.Ya.sampleRate),e.eb=e.Ya.createScriptProcessor(c,0,b),e.eb.onaudioprocess=function(a){var b=a.outputBuffer.length,c=Kb(b);if(c)for(var d=a.outputBuffer.numberOfChannels,p=0;p<d;p++)for(var t=a.outputBuffer.getChannelData(p),n=0;n<b;n++)t[n]=va[(c>>2)+(d*n+p)]},e.eb.connect(e.Ya.destination),a=function(){e.Ya&&"suspended"===e.Ya.state&&e.Ya.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),
1):0},G:function(){return e.Ya?e.Ya.sampleRate:0},E:function(a,b,c,d,g,h){b=qa(b);var k=new XMLHttpRequest;k.open("GET",b);k.responseType="arraybuffer";var p=0<d;p&&k.setRequestHeader("Range","bytes="+c+"-"+(c+d));k.onreadystatechange=function(){if(this.readyState==this.DONE)if(206==this.status||200==this.status&&!p){var b=new Uint8Array(k.response),c=b.length;c<=h?(H.set(b,g),Lb(a,d,c)):Mb(a)}else Nb(a,this.status)};k.send()},table:ja},Pb=function(){function a(a){e.asm=a.exports;L--;e.monitorRunDependencies&&
e.monitorRunDependencies(L);0==L&&(null!==Ga&&(clearInterval(Ga),Ga=null),M&&(a=M,M=null,a()))}function b(b){a(b.instance)}function c(a){return Ka().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){B("failed to asynchronously prepare wasm: "+a);A(a)})}var d={env:Ob,wasi_unstable:Ob};L++;e.monitorRunDependencies&&e.monitorRunDependencies(L);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(g){return B("Module.instantiateWasm callback failed with error: "+g),!1}(function(){if(C||
"function"!==typeof WebAssembly.instantiateStreaming||Ha()||"function"!==typeof fetch)return c(b);fetch(N,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){B("wasm streaming compile failed: "+a);B("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();e.asm=Pb;var La=e.___wasm_call_ctors=function(){return e.asm.ua.apply(null,arguments)},Ib=e.__sapp_emsc_notify_keyboard_hidden=function(){return e.asm.va.apply(null,arguments)};
e.___em_js__sapp_js_create_textfield=function(){return e.asm.wa.apply(null,arguments)};e.___em_js__sapp_js_focus_textfield=function(){return e.asm.xa.apply(null,arguments)};e.___em_js__sapp_js_unfocus_textfield=function(){return e.asm.ya.apply(null,arguments)};e.__sapp_emsc_onpaste=function(){return e.asm.za.apply(null,arguments)};var Jb=e.__sapp_html5_get_ask_leave_site=function(){return e.asm.Aa.apply(null,arguments)};e.___em_js__sapp_js_hook_beforeunload=function(){return e.asm.Ba.apply(null,arguments)};
e.___em_js__sapp_js_init_clipboard=function(){return e.asm.Ca.apply(null,arguments)};e.___em_js__sapp_js_write_clipboard=function(){return e.asm.Da.apply(null,arguments)};e._main=function(){return e.asm.Ea.apply(null,arguments)};var S=e._malloc=function(){return e.asm.Fa.apply(null,arguments)};e._free=function(){return e.asm.Ga.apply(null,arguments)};e.___em_js__stm_js_perfnow=function(){return e.asm.Ha.apply(null,arguments)};var Kb=e.__saudio_emsc_pull=function(){return e.asm.Ia.apply(null,arguments)};
e.___em_js__saudio_js_init=function(){return e.asm.Ja.apply(null,arguments)};e.___em_js__saudio_js_sample_rate=function(){return e.asm.Ka.apply(null,arguments)};e.___em_js__saudio_js_buffer_frames=function(){return e.asm.La.apply(null,arguments)};e.___em_js__sfetch_js_send_head_request=function(){return e.asm.Ma.apply(null,arguments)};e.___em_js__sfetch_js_send_get_request=function(){return e.asm.Na.apply(null,arguments)};e.__sfetch_emsc_head_response=function(){return e.asm.Oa.apply(null,arguments)};
var Lb=e.__sfetch_emsc_get_response=function(){return e.asm.Pa.apply(null,arguments)},Nb=e.__sfetch_emsc_failed_http_status=function(){return e.asm.Qa.apply(null,arguments)},Mb=e.__sfetch_emsc_failed_buffer_too_small=function(){return e.asm.Ra.apply(null,arguments)},na=e.stackSave=function(){return e.asm.Sa.apply(null,arguments)},F=e.stackAlloc=function(){return e.asm.Ta.apply(null,arguments)},oa=e.stackRestore=function(){return e.asm.Ua.apply(null,arguments)};
e.dynCall_v=function(){return e.asm.Va.apply(null,arguments)};var T=e.dynCall_iiii=function(){return e.asm.Wa.apply(null,arguments)},Hb=e.dynCall_idi=function(){return e.asm.Xa.apply(null,arguments)};e.asm=Pb;var Qb;function ha(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}M=function Rb(){Qb||Sb();Qb||(M=Rb)};
function Sb(a){function b(){if(!Qb&&(Qb=!0,!ka)){za(Ba);za(Ca);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Tb){var b=a,d=e._main;b=b||[];var g=b.length+1,h=F(4*(g+1));J[h>>2]=sa(aa);for(var k=1;k<g;k++)J[(h>>2)+k]=sa(b[k-1]);J[(h>>2)+g]=0;try{var p=d(g,h);if(!D||0!==p){if(!D&&(ka=!0,e.onExit))e.onExit(p);u(p,new ha(p))}}catch(t){t instanceof ha||("SimulateInfiniteLoop"==t?D=!0:((b=t)&&"object"===typeof t&&t.stack&&(b=[t,t.stack]),B("exception thrown: "+b),u(1,t)))}finally{}}if(e.postRun)for("function"==
typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)b=e.postRun.shift(),Ea.unshift(b);za(Ea)}}a=a||q;if(!(0<L)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Fa();za(Aa);0<L||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=Sb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Tb=!0;e.noInitialRun&&(Tb=!1);D=!0;Sb();
