
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var k={},l;for(l in f)f.hasOwnProperty(l)&&(k[l]=f[l]);var r=[],aa="./this.program";function t(a,b){throw b;}var ba=!1,u=!1,ca=!1,da=!1;ba="object"===typeof window;u="function"===typeof importScripts;ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;da=!ba&&!ca&&!u;var v="",ea,fa,w,ha,ia;
if(ca)v=u?require("path").dirname(v)+"/":__dirname+"/",ea=function(a,b){ha||(ha=require("fs"));ia||(ia=require("path"));a=ia.normalize(a);return ha.readFileSync(a,b?null:"utf8")},w=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),r=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof ja))throw a;}),process.on("unhandledRejection",
x),t=function(a){process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(da)"undefined"!=typeof read&&(ea=function(a){return read(a)}),w=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?r=scriptArgs:"undefined"!=typeof arguments&&(r=arguments),"function"===typeof quit&&(t=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ba||u)u?v=self.location.href:"undefined"!==typeof document&&document.currentScript&&(v=document.currentScript.src),v=0!==v.indexOf("blob:")?v.substr(0,v.lastIndexOf("/")+1):"",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(w=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
fa=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};f.print||console.log.bind(console);var y=f.printErr||console.warn.bind(console);for(l in k)k.hasOwnProperty(l)&&(f[l]=k[l]);k=null;f.arguments&&(r=f.arguments);f.thisProgram&&(aa=f.thisProgram);f.quit&&(t=f.quit);var z;f.wasmBinary&&(z=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;
"object"!==typeof WebAssembly&&x("no native wasm support detected");var ka,la=!1;function assert(a,b){a||x("Assertion failed: "+b)}function ma(a){var b=f["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function na(a,b,c){var d={string:function(n){var q=0;if(null!==n&&void 0!==n&&0!==n){var p=(n.length<<2)+1;q=A(p);C(n,D,q,p)}return q},array:function(n){var q=A(n.length);oa.set(n,q);return q}};a=ma(a);var e=[],h=0;if(c)for(var g=0;g<c.length;g++){var m=d[b[g]];m?(0===h&&(h=pa()),e[g]=m(c[g])):e[g]=c[g]}a.apply(null,e);0!==h&&qa(h)}var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function E(a,b){if(a){var c=D,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&ra)a=ra.decode(c.subarray(a,b));else{for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}a=d}}else a="";return a}
function C(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ta(a){var b=sa(a)+1,c=A(b);C(a,oa,c,b);return c}var ua,oa,D,va,F,G,H;
function wa(){var a=ka.buffer;ua=a;f.HEAP8=oa=new Int8Array(a);f.HEAP16=va=new Int16Array(a);f.HEAP32=F=new Int32Array(a);f.HEAPU8=D=new Uint8Array(a);f.HEAPU16=new Uint16Array(a);f.HEAPU32=new Uint32Array(a);f.HEAPF32=G=new Float32Array(a);f.HEAPF64=H=new Float64Array(a)}var I,xa=[],ya=[],za=[],Aa=[],Ba=[];function Ca(){var a=f.preRun.shift();xa.unshift(a)}var J=0,Da=null,K=null;f.preloadedImages={};f.preloadedAudios={};
function x(a){if(f.onAbort)f.onAbort(a);y(a);la=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ea(a){var b=L;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Fa(){return Ea("data:application/octet-stream;base64,")}var L="sdf-sapp.wasm";if(!Fa()){var Ga=L;L=f.locateFile?f.locateFile(Ga,v):v+Ga}
function Ha(){var a=L;try{if(a==L&&z)return new Uint8Array(z);if(w)return w(a);throw"both async and sync fetching of the wasm failed";}catch(b){x(b)}}
function Ia(){if(!z&&(ba||u)){if("function"===typeof fetch&&!Ea("file://"))return fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ha()});if(fa)return new Promise(function(a,b){fa(L,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ha()})}
function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.fc;"number"===typeof c?void 0===b.Fb?I.get(c)():I.get(c)(b.Fb):c(void 0===b.Fb?null:b.Fb)}}}var Ka=0;function La(){for(var a=M.length-1;0<=a;--a)Ma(a);M=[];Na=[]}var Na=[];function Oa(){if(Ka&&Pa.Db)for(var a=0;a<Na.length;++a){var b=Na[a];Na.splice(a,1);--a;b.pc.apply(null,b.bc)}}var M=[];function Ma(a){var b=M[a];b.target.removeEventListener(b.wb,b.Wb,b.xb);M.splice(a,1)}
function N(a){function b(d){++Ka;Pa=a;Oa();a.zb(d);Oa();--Ka}if(a.yb)a.Wb=b,a.target.addEventListener(a.wb,b,a.xb),M.push(a),Qa||(Aa.push(La),Qa=!0);else for(var c=0;c<M.length;++c)M[c].target==a.target&&M[c].wb==a.wb&&Ma(c--)}var Qa,Pa,Ra,Sa,Ta,Ua,Va,Wa,Xa=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function O(a){a=2<a?E(a):a;return Xa[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Ya(a){return 0>Xa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function Za(a,b,c,d,e,h){Ra||(Ra=P(164));a={target:O(a),Db:!0,wb:h,yb:d,zb:function(g){var m=Ra,n=m>>2;F[n]=g.location;F[n+1]=g.ctrlKey;F[n+2]=g.shiftKey;F[n+3]=g.altKey;F[n+4]=g.metaKey;F[n+5]=g.repeat;F[n+6]=g.charCode;F[n+7]=g.keyCode;F[n+8]=g.which;C(g.key||"",D,m+36,32);C(g.code||"",D,m+68,32);C(g.char||"",D,m+100,32);C(g.locale||"",D,m+132,32);I.get(d)(e,m,b)&&g.preventDefault()},xb:c};N(a)}
function $a(a,b,c){a>>=2;F[a]=b.screenX;F[a+1]=b.screenY;F[a+2]=b.clientX;F[a+3]=b.clientY;F[a+4]=b.ctrlKey;F[a+5]=b.shiftKey;F[a+6]=b.altKey;F[a+7]=b.metaKey;va[2*a+16]=b.button;va[2*a+17]=b.buttons;F[a+9]=b.movementX;F[a+10]=b.movementY;c=Ya(c);F[a+11]=b.clientX-c.left;F[a+12]=b.clientY-c.top}function Q(a,b,c,d,e,h){Sa||(Sa=P(64));a=O(a);N({target:a,Db:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,wb:h,yb:d,zb:function(g){g=g||event;$a(Sa,g,a);I.get(d)(e,Sa,b)&&g.preventDefault()},xb:c})}
function ab(a,b,c,d,e){Ta||(Ta=P(260));N({target:a,wb:e,yb:d,zb:function(h){h=h||event;var g=Ta,m=document.pointerLockElement||document.Tb||document.Vb||document.Ub;F[g>>2]=!!m;var n=m&&m.id?m.id:"";C(m?m==window?"#window":m==screen?"#screen":m&&m.nodeName?m.nodeName:"":"",D,g+4,128);C(n,D,g+132,128);I.get(d)(20,g,b)&&h.preventDefault()},xb:c})}function bb(a,b,c,d,e){N({target:a,wb:e,yb:d,zb:function(h){h=h||event;I.get(d)(38,0,b)&&h.preventDefault()},xb:c})}
function cb(a,b,c,d){Ua||(Ua=P(36));a=O(a);N({target:a,wb:"resize",yb:d,zb:function(e){e=e||event;if(e.target==a){var h=document.body;if(h){var g=Ua;F[g>>2]=e.detail;F[g+4>>2]=h.clientWidth;F[g+8>>2]=h.clientHeight;F[g+12>>2]=innerWidth;F[g+16>>2]=innerHeight;F[g+20>>2]=outerWidth;F[g+24>>2]=outerHeight;F[g+28>>2]=pageXOffset;F[g+32>>2]=pageYOffset;I.get(d)(10,g,b)&&e.preventDefault()}}},xb:c})}
function db(a,b,c,d,e,h){Va||(Va=P(1684));a=O(a);N({target:a,Db:"touchstart"==h||"touchend"==h,wb:h,yb:d,zb:function(g){for(var m={},n=g.touches,q=0;q<n.length;++q){var p=n[q];m[p.identifier]=p}n=g.changedTouches;for(q=0;q<n.length;++q)p=n[q],p.Zb=1,m[p.identifier]=p;n=g.targetTouches;for(q=0;q<n.length;++q)m[n[q].identifier].$b=1;n=Va;p=n>>2;F[p+1]=g.ctrlKey;F[p+2]=g.shiftKey;F[p+3]=g.altKey;F[p+4]=g.metaKey;p+=5;var hb=Ya(a),ib=0;for(q in m){var B=m[q];F[p]=B.identifier;F[p+1]=B.screenX;F[p+2]=
B.screenY;F[p+3]=B.clientX;F[p+4]=B.clientY;F[p+5]=B.pageX;F[p+6]=B.pageY;F[p+7]=B.Zb;F[p+8]=B.$b;F[p+9]=B.clientX-hb.left;F[p+10]=B.clientY-hb.top;p+=13;if(31<++ib)break}F[n>>2]=ib;I.get(d)(e,n,b)&&g.preventDefault()},xb:c})}function eb(a,b,c,d,e,h){a={target:O(a),wb:h,yb:d,zb:function(g){g=g||event;I.get(d)(e,0,b)&&g.preventDefault()},xb:c};N(a)}
function fb(a,b,c,d){Wa||(Wa=P(96));N({target:a,Db:!0,wb:"wheel",yb:d,zb:function(e){e=e||event;var h=Wa;$a(h,e,a);H[h+64>>3]=e.deltaX;H[h+72>>3]=e.deltaY;H[h+80>>3]=e.deltaZ;F[h+88>>2]=e.deltaMode;I.get(d)(9,h,b)&&e.preventDefault()},xb:c})}
function gb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function jb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function kb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function lb(a){a.dc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function mb(a){a.ic=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function nb(a){a.kc=a.getExtension("WEBGL_multi_draw")}var ob=1,pb=[],R=[],qb=[],rb=[],sb=[],S=[],T=[],tb=[],ub=[],U={},vb={},wb={};function V(a){xb||(xb=a)}function W(a){for(var b=ob++,c=a.length;c<b;c++)a[c]=null;return b}
function yb(a,b){a.Kb||(a.Kb=a.getContext,a.getContext=function(d,e){e=a.Kb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Lb?a.getContext("webgl2",b):a.getContext("webgl",b);return c?zb(c,b):0}function zb(a,b){var c=W(ub),d={hc:c,attributes:b,version:b.Lb,Eb:a};a.canvas&&(a.canvas.ac=d);ub[c]=d;("undefined"===typeof b.Jb||b.Jb)&&Ab(d);return c}
function Ab(a){a||(a=X);if(!a.Yb){a.Yb=!0;var b=a.Eb;gb(b);jb(b);kb(b);lb(b);mb(b);b.ec=b.getExtension("EXT_disjoint_timer_query");nb(b);(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var xb,X,Bb=["default","low-power","high-performance"];function Cb(a,b,c,d){for(var e=0;e<a;e++){var h=Y[c](),g=h&&W(d);h?(h.name=g,d[g]=h):V(1282);F[b+4*e>>2]=g}}
function Db(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Y.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>X.version){V(1282);return}c=2*(Y.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>X.version){V(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=Y.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":V(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:V(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)F[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){V(1280);y("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:V(1280);y("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}F[b>>2]=c}else V(1281)}
function Eb(a){var b=sa(a)+1,c=P(b);C(a,D,c,b);return c}for(var Z=[],Y,Fb=new Float32Array(288),Gb=0;288>Gb;++Gb)Z[Gb]=Fb.subarray(0,Gb+1);
var Lb={S:function(){x()},T:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},ja:function(a,b,c){a=O(a);if(!a)return-4;a=Ya(a);H[b>>3]=a.width;H[c>>3]=a.height;return 0},Va:function(a,b,c){D.copyWithin(a,b,b+c)},Ha:function(a,b){function c(d){I.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Wa:function(a){var b=D.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);
a:{try{ka.grow(Math.min(2147483648,d)-ua.byteLength+65535>>>16);wa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},R:function(a,b,c){a=O(a);if(!a)return-4;a.width=b;a.height=c;return 0},ca:function(a,b,c,d){Za(a,b,c,d,2,"keydown");return 0},aa:function(a,b,c,d){Za(a,b,c,d,1,"keypress");return 0},ba:function(a,b,c,d){Za(a,b,c,d,3,"keyup");return 0},ia:function(a,b,c,d){Q(a,b,c,d,5,"mousedown");return 0},fa:function(a,b,c,d){Q(a,b,c,d,33,"mouseenter");return 0},ea:function(a,b,c,d){Q(a,
b,c,d,34,"mouseleave");return 0},ga:function(a,b,c,d){Q(a,b,c,d,8,"mousemove");return 0},ha:function(a,b,c,d){Q(a,b,c,d,6,"mouseup");return 0},X:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Tb||document.body.Vb||document.body.Ub))return-1;a=O(a);if(!a)return-4;ab(a,b,c,d,"pointerlockchange");ab(a,b,c,d,"mozpointerlockchange");ab(a,b,c,d,"webkitpointerlockchange");ab(a,b,c,d,"mspointerlockchange");return 0},W:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||
document.body.Tb||document.body.Vb||document.body.Ub))return-1;a=O(a);if(!a)return-4;bb(a,b,c,d,"pointerlockerror");bb(a,b,c,d,"mozpointerlockerror");bb(a,b,c,d,"webkitpointerlockerror");bb(a,b,c,d,"mspointerlockerror");return 0},Ua:function(a,b,c,d){cb(a,b,c,d);return 0},Y:function(a,b,c,d){db(a,b,c,d,25,"touchcancel");return 0},Z:function(a,b,c,d){db(a,b,c,d,23,"touchend");return 0},_:function(a,b,c,d){db(a,b,c,d,24,"touchmove");return 0},$:function(a,b,c,d){db(a,b,c,d,22,"touchstart");return 0},
V:function(a,b,c,d){eb(a,b,c,d,31,"webglcontextlost");return 0},U:function(a,b,c,d){eb(a,b,c,d,32,"webglcontextrestored");return 0},da:function(a,b,c,d){a=O(a);return"undefined"!==typeof a.onwheel?(fb(a,b,c,d),0):-1},G:function(a,b){b>>=2;b={alpha:!!F[b],depth:!!F[b+1],stencil:!!F[b+2],antialias:!!F[b+3],premultipliedAlpha:!!F[b+4],preserveDrawingBuffer:!!F[b+5],powerPreference:Bb[F[b+6]],failIfMajorPerformanceCaveat:!!F[b+7],Lb:F[b+8],jc:F[b+9],Jb:F[b+10],Xb:F[b+11],lc:F[b+12],mc:F[b+13]};a=O(a);
return!a||b.Xb?0:yb(a,b)},qa:function(a,b){a=ub[a];b=E(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&gb(Y);"OES_vertex_array_object"==b&&jb(Y);"WEBGL_draw_buffers"==b&&kb(Y);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&lb(Y);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&mb(Y);"WEBGL_multi_draw"==b&&nb(Y);return!!a.Eb.getExtension(b)},Ea:function(a){a>>=2;for(var b=0;14>b;++b)F[a+b]=0;F[a]=F[a+1]=F[a+3]=F[a+4]=F[a+8]=F[a+10]=1},ya:function(a){X=ub[a];f.cc=
Y=X&&X.Eb;return!a||Y?0:-5},b:function(a){Y.activeTexture(a)},C:function(a,b){Y.attachShader(R[a],T[b])},c:function(a,b){35051==a?Y.Hb=b:35052==a&&(Y.Ib=b);Y.bindBuffer(a,pb[b])},g:function(a,b){Y.bindFramebuffer(a,qb[b])},a:function(a,b){Y.bindTexture(a,sb[b])},O:function(a){Y.bindVertexArray(tb[a])},K:function(a,b,c,d){Y.blendColor(a,b,c,d)},L:function(a,b){Y.blendEquationSeparate(a,b)},M:function(a,b,c,d){Y.blendFuncSeparate(a,b,c,d)},o:function(a,b,c,d,e,h,g,m,n,q){Y.blitFramebuffer(a,b,c,d,e,
h,g,m,n,q)},E:function(a,b,c,d){2<=X.version?c?Y.bufferData(a,D,d,c,b):Y.bufferData(a,b,d):Y.bufferData(a,c?D.subarray(c,c+b):b,d)},D:function(a,b,c,d){2<=X.version?Y.bufferSubData(a,b,D,d,c):Y.bufferSubData(a,b,D.subarray(d,d+c))},oa:function(a){Y.clear(a)},y:function(a,b,c,d){Y.clearColor(a,b,c,d)},x:function(a){Y.clearDepth(a)},pa:function(a){Y.clearStencil(a)},i:function(a,b,c,d){Y.colorMask(!!a,!!b,!!c,!!d)},va:function(a){Y.compileShader(T[a])},Ba:function(){var a=W(R),b=Y.createProgram();b.name=
a;R[a]=b;return a},xa:function(a){var b=W(T);T[b]=Y.createShader(a);return b},H:function(a){Y.cullFace(a)},Ja:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],e=pb[d];e&&(Y.deleteBuffer(e),e.name=0,pb[d]=null,d==Y.Hb&&(Y.Hb=0),d==Y.Ib&&(Y.Ib=0))}},h:function(a,b){for(var c=0;c<a;++c){var d=F[b+4*c>>2],e=qb[d];e&&(Y.deleteFramebuffer(e),e.name=0,qb[d]=null)}},P:function(a){if(a){var b=R[a];b?(Y.deleteProgram(b),b.name=0,R[a]=null,U[a]=null):V(1281)}},Q:function(a,b){for(var c=0;c<a;c++){var d=
F[b+4*c>>2],e=rb[d];e&&(Y.deleteRenderbuffer(e),e.name=0,rb[d]=null)}},q:function(a){if(a){var b=T[a];b?(Y.deleteShader(b),T[a]=null):V(1281)}},Ia:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],e=sb[d];e&&(Y.deleteTexture(e),e.name=0,sb[d]=null)}},Ga:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2];Y.deleteVertexArray(tb[d]);tb[d]=null}},t:function(a){Y.depthFunc(a)},s:function(a){Y.depthMask(!!a)},d:function(a){Y.disable(a)},N:function(a){Y.disableVertexAttribArray(a)},Xa:function(a,b,
c){Y.drawArrays(a,b,c)},Ya:function(a,b,c,d){Y.drawElements(a,b,c,d)},f:function(a){Y.enable(a)},la:function(a){Y.enableVertexAttribArray(a)},I:function(a){Y.frontFace(a)},F:function(a,b){Cb(a,b,"createBuffer",pb)},Fa:function(a,b){Cb(a,b,"createVertexArray",tb)},ta:function(a,b){return Y.getAttribLocation(R[a],E(b))},e:function(a,b){Db(a,b)},za:function(a,b,c,d){a=Y.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,D,d,b):0;c&&(F[c>>2]=b)},B:function(a,b,c){if(c)if(a>=ob)V(1281);
else{var d=U[a];if(d)if(35716==b)a=Y.getProgramInfoLog(R[a]),null===a&&(a="(unknown error)"),F[c>>2]=a.length+1;else if(35719==b)F[c>>2]=d.Gb;else if(35722==b){if(-1==d.Ab){a=R[a];var e=Y.getProgramParameter(a,35721);for(b=d.Ab=0;b<e;++b)d.Ab=Math.max(d.Ab,Y.getActiveAttrib(a,b).name.length+1)}F[c>>2]=d.Ab}else if(35381==b){if(-1==d.Bb)for(a=R[a],e=Y.getProgramParameter(a,35382),b=d.Bb=0;b<e;++b)d.Bb=Math.max(d.Bb,Y.getActiveUniformBlockName(a,b).length+1);F[c>>2]=d.Bb}else F[c>>2]=Y.getProgramParameter(R[a],
b);else V(1282)}else V(1281)},ua:function(a,b,c,d){a=Y.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,D,d,b):0;c&&(F[c>>2]=b)},z:function(a,b,c){c?35716==b?(a=Y.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),F[c>>2]=a?a.length+1:0):35720==b?(a=Y.getShaderSource(T[a]),F[c>>2]=a?a.length+1:0):F[c>>2]=Y.getShaderParameter(T[a],b):V(1281)},La:function(a){if(vb[a])return vb[a];switch(a){case 7939:var b=Y.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+
d}));b=Eb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Y.getParameter(a))||V(1280);b=Eb(b);break;case 7938:b=Y.getParameter(7938);b=2<=X.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Eb(b);break;case 35724:b=Y.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Eb(b);break;default:return V(1280),0}return vb[a]=b},Ka:function(a,b){if(2>X.version)return V(1282),
0;var c=wb[a];if(c)return 0>b||b>=c.length?(V(1281),0):c[b];switch(a){case 7939:return c=Y.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Eb(d)}),c=wb[a]=c,0>b||b>=c.length?(V(1281),0):c[b];default:return V(1280),0}},j:function(a,b){b=E(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=U[a]&&U[a].Sb[b])&&0<=c&&c<a[0]?a[1]+c:-1},Aa:function(a){Y.linkProgram(R[a]);var b=R[a];
a=U[a]={Sb:{},Gb:0,Ab:-1,Bb:-1};for(var c=a.Sb,d=Y.getProgramParameter(b,35718),e=0;e<d;++e){var h=Y.getActiveUniform(b,e),g=h.name;a.Gb=Math.max(a.Gb,g.length+1);"]"==g.slice(-1)&&(g=g.slice(0,g.lastIndexOf("[")));var m=Y.getUniformLocation(b,g);if(m){var n=W(S);c[g]=[h.size,n];S[n]=m;for(var q=1;q<h.size;++q)m=Y.getUniformLocation(b,g+"["+q+"]"),n=W(S),S[n]=m}}},J:function(a,b){Y.polygonOffset(a,b)},p:function(a){Y.readBuffer(a)},ra:function(a,b,c,d){Y.scissor(a,b,c,d)},wa:function(a,b,c,d){for(var e=
"",h=0;h<b;++h){var g=d?F[d+4*h>>2]:-1;e+=E(F[c+4*h>>2],0>g?void 0:g)}Y.shaderSource(T[a],e)},Da:function(a,b,c){Y.stencilFunc(a,b,c)},w:function(a,b,c,d){Y.stencilFuncSeparate(a,b,c,d)},r:function(a){Y.stencilMask(a)},Ca:function(a,b,c){Y.stencilOp(a,b,c)},v:function(a,b,c,d){Y.stencilOpSeparate(a,b,c,d)},ka:function(a,b,c){if(2<=X.version)Y.uniform1fv(S[a],G,c>>2,b);else{if(288>=b)for(var d=Z[b-1],e=0;e<b;++e)d[e]=G[c+4*e>>2];else d=G.subarray(c>>2,c+4*b>>2);Y.uniform1fv(S[a],d)}},A:function(a,
b){Y.uniform1i(S[a],b)},ab:function(a,b,c){if(2<=X.version)Y.uniform2fv(S[a],G,c>>2,2*b);else{if(144>=b)for(var d=Z[2*b-1],e=0;e<2*b;e+=2)d[e]=G[c+4*e>>2],d[e+1]=G[c+(4*e+4)>>2];else d=G.subarray(c>>2,c+8*b>>2);Y.uniform2fv(S[a],d)}},$a:function(a,b,c){if(2<=X.version)Y.uniform3fv(S[a],G,c>>2,3*b);else{if(96>=b)for(var d=Z[3*b-1],e=0;e<3*b;e+=3)d[e]=G[c+4*e>>2],d[e+1]=G[c+(4*e+4)>>2],d[e+2]=G[c+(4*e+8)>>2];else d=G.subarray(c>>2,c+12*b>>2);Y.uniform3fv(S[a],d)}},_a:function(a,b,c){if(2<=X.version)Y.uniform4fv(S[a],
G,c>>2,4*b);else{if(72>=b){var d=Z[4*b-1],e=G;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=G.subarray(c>>2,c+16*b>>2);Y.uniform4fv(S[a],d)}},Za:function(a,b,c,d){if(2<=X.version)Y.uniformMatrix4fv(S[a],!!c,G,d>>2,16*b);else{if(18>=b){var e=Z[16*b-1],h=G;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];
e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=h[m+13];e[g+14]=h[m+14];e[g+15]=h[m+15]}}else e=G.subarray(d>>2,d+64*b>>2);Y.uniformMatrix4fv(S[a],!!c,e)}},k:function(a){Y.useProgram(R[a])},ma:function(a,b){Y.vertexAttribDivisor(a,b)},na:function(a,b,c,d,e,h){Y.vertexAttribPointer(a,b,c,!!d,e,h)},sa:function(a,b,c,d){Y.viewport(a,b,c,d)},Ta:function(){f.Mb=function(a){0!=Hb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Mb)},Sa:function(){f.Rb=function(a){a=a.clipboardData.getData("text");
na("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",f.Rb)},Ra:function(a){f.nc=[];a=E(a);a=document.getElementById(a);f.Nb=function(b){b.stopPropagation();b.preventDefault()};f.Ob=function(b){b.stopPropagation();b.preventDefault()};f.Pb=function(b){b.stopPropagation();b.preventDefault()};f.Qb=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;f.oc=c;Ib(c.length);var d;for(d=0;d<c.length;d++)na("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Jb(b.clientX,
b.clientY)};a.addEventListener("dragenter",f.Nb,!1);a.addEventListener("dragleave",f.Ob,!1);a.addEventListener("dragover",f.Pb,!1);a.addEventListener("drop",f.Qb,!1)},Na:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},n:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Kb()});document.body.append(a)},m:function(){document.getElementById("_sokol_app_input_element").focus()},
bb:function(a){a=E(a);f.Cb=document.getElementById(a);f.Cb||console.log("sokol_app.h: invalid target:"+a);f.Cb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Qa:function(){window.removeEventListener("beforeunload",f.Mb)},Pa:function(){window.removeEventListener("paste",f.Rb)},Oa:function(a){a=E(a);a=document.getElementById(a);a.removeEventListener("dragenter",f.Nb);a.removeEventListener("dragleave",f.Ob);a.removeEventListener("dragover",f.Pb);a.removeEventListener("drop",
f.Qb)},u:function(){f.Cb&&f.Cb.requestPointerLock&&f.Cb.requestPointerLock()},Ma:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(D.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},l:function(){document.getElementById("_sokol_app_input_element").blur()}};
(function(){function a(e){f.asm=e.exports;ka=f.asm.cb;wa();I=f.asm.vb;ya.unshift(f.asm.db);J--;f.monitorRunDependencies&&f.monitorRunDependencies(J);0==J&&(null!==Da&&(clearInterval(Da),Da=null),K&&(e=K,K=null,e()))}function b(e){a(e.instance)}function c(e){return Ia().then(function(h){return WebAssembly.instantiate(h,d)}).then(e,function(h){y("failed to asynchronously prepare wasm: "+h);x(h)})}var d={a:Lb};J++;f.monitorRunDependencies&&f.monitorRunDependencies(J);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return y("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return z||"function"!==typeof WebAssembly.instantiateStreaming||Fa()||Ea("file://")||"function"!==typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(h){y("wasm streaming compile failed: "+h);y("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.db).apply(null,arguments)};var Kb=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Kb=f.__sapp_emsc_notify_keyboard_hidden=f.asm.eb).apply(null,arguments)};f.__sapp_emsc_onpaste=function(){return(f.__sapp_emsc_onpaste=f.asm.fb).apply(null,arguments)};
var Hb=f.__sapp_html5_get_ask_leave_site=function(){return(Hb=f.__sapp_html5_get_ask_leave_site=f.asm.gb).apply(null,arguments)},Ib=f.__sapp_emsc_begin_drop=function(){return(Ib=f.__sapp_emsc_begin_drop=f.asm.hb).apply(null,arguments)};f.__sapp_emsc_drop=function(){return(f.__sapp_emsc_drop=f.asm.ib).apply(null,arguments)};var Jb=f.__sapp_emsc_end_drop=function(){return(Jb=f.__sapp_emsc_end_drop=f.asm.jb).apply(null,arguments)};
f.__sapp_emsc_invoke_fetch_cb=function(){return(f.__sapp_emsc_invoke_fetch_cb=f.asm.kb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.lb).apply(null,arguments)};f.__saudio_emsc_pull=function(){return(f.__saudio_emsc_pull=f.asm.mb).apply(null,arguments)};f.__sfetch_emsc_head_response=function(){return(f.__sfetch_emsc_head_response=f.asm.nb).apply(null,arguments)};f.__sfetch_emsc_get_response=function(){return(f.__sfetch_emsc_get_response=f.asm.ob).apply(null,arguments)};
f.__sfetch_emsc_failed_http_status=function(){return(f.__sfetch_emsc_failed_http_status=f.asm.pb).apply(null,arguments)};f.__sfetch_emsc_failed_buffer_too_small=function(){return(f.__sfetch_emsc_failed_buffer_too_small=f.asm.qb).apply(null,arguments)};
var P=f._malloc=function(){return(P=f._malloc=f.asm.rb).apply(null,arguments)},pa=f.stackSave=function(){return(pa=f.stackSave=f.asm.sb).apply(null,arguments)},qa=f.stackRestore=function(){return(qa=f.stackRestore=f.asm.tb).apply(null,arguments)},A=f.stackAlloc=function(){return(A=f.stackAlloc=f.asm.ub).apply(null,arguments)},Mb;function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}K=function Nb(){Mb||Ob();Mb||(K=Nb)};
function Ob(a){function b(){if(!Mb&&(Mb=!0,f.calledRun=!0,!la)){Ja(ya);Ja(za);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Pb){var c=a,d=f._main;c=c||[];var e=c.length+1,h=A(4*(e+1));F[h>>2]=ta(aa);for(var g=1;g<e;g++)F[(h>>2)+g]=ta(c[g-1]);F[(h>>2)+e]=0;try{var m=d(e,h);if(!noExitRuntime||0!==m){if(!noExitRuntime){if(f.onExit)f.onExit(m);la=!0}t(m,new ja(m))}}catch(n){n instanceof ja||"unwind"==n||((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),y("exception thrown: "+c),t(1,n))}finally{}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Ba.unshift(c);Ja(Ba)}}a=a||r;if(!(0<J)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ca();Ja(xa);0<J||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Ob;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Pb=!0;f.noInitialRun&&(Pb=!1);Ob();
