var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var h=console.error.bind(console),l,n=!1,ma,la=a=>a.startsWith("file://"),na,q,t,pa,u,v,w,x;
function qa(){var a=na.buffer;q=new Int8Array(a);pa=new Int16Array(a);t=new Uint8Array(a);new Uint16Array(a);u=new Int32Array(a);v=new Uint32Array(a);w=new Float32Array(a);x=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function ra(a){g.onAbort?.(a);a="Aborted("+a+")";h(a);n=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var sa;
async function ta(a){if(!l)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==sa&&l)a=new Uint8Array(l);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function ua(a,b){try{var c=await ta(a);return await WebAssembly.instantiate(c,b)}catch(d){h(`failed to asynchronously prepare wasm: ${d}`),ra(d)}}
async function va(a){var b=sa;if(!l&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){h(`wasm streaming compile failed: ${d}`),h("falling back to ArrayBuffer instantiation")}return ua(b,a)}class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var xa=a=>{for(;0<a.length;)a.shift()(g)},ya=[],za=[],Aa=()=>{var a=g.preRun.shift();za.push(a)},y=0,z=null,Ba=!0,Ca=0,C={},Da=a=>{a instanceof wa||"unwind"==a||fa(1,a)},Ea=a=>{ma=a;Ba||0<Ca||(g.onExit?.(a),n=!0);fa(a,new wa(a))},Fa=a=>{ma=a;Ea(a)},Ga=()=>{if(!(Ba||0<Ca))try{var a=ma;ma=a;Ea(a)}catch(b){Da(b)}},Ha=a=>{if(!n)try{a(),Ga()}catch(b){Da(b)}},Oa=(a,b)=>{Ia=a;Ja=b;if(D)if(Ka||=!0,0==a)E=function(){setTimeout(F,Math.max(0,La+b-performance.now())|0)};else if(1==a)E=function(){Ma(F)};else if(2==
a){if("undefined"==typeof Na)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Na=d=>{c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Na=setImmediate;E=function(){Na(F)}}},Xa=(a,b,c,d,e)=>{function k(){return f<Pa?(Ga(),!1):!0}D=a;Qa=d;var f=Pa;Ka=!1;F=function(){if(!n)if(0<
Ra.length){var m=Ra.shift();m.ed(m.Tc);if(Sa){var p=Sa,r=0==p%1?p-1:Math.floor(p);Sa=m.Wc?r:(8*p+(r+.5))/9}g.setStatus&&(m=g.statusMessage||"Please wait...",p=Sa??0,r=Ta.bd??0,p?p<r?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(m):g.setStatus(""));k()&&setTimeout(F,0)}else if(k())if(Ua=Ua+1|0,1==Ia&&1<Ja&&0!=Ua%Ja)E();else{0==Ia&&(La=performance.now());a:if(!n){for(m of Va)if(!1===m())break a;Ha(a);for(p of Wa)p()}k()&&E()}};e||(0<b?Oa(0,1E3/b):Oa(1,1),E());if(c)throw"unwind";
},Ka=!1,E=null,Pa=0,D=null,Qa=0,Ia=0,Ja=0,Ua=0,Ra=[],Va=[],Wa=[];function Ya(){E=null;Pa++}var G=0;function Ma(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===G)G=b+1E3/60;else for(;b+2>=G;)G+=1E3/60;setTimeout(a,Math.max(G-b,0))}}
var Ta={},La,F,Na,Sa,Za="undefined"!=typeof TextDecoder?new TextDecoder:void 0,H=(a=0,b)=>{var c=t;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&Za)return Za.decode(c.subarray(a,d));for(b="";a<d;){var e=c[a++];if(e&128){var k=c[a++]&63;if(192==(e&224))b+=String.fromCharCode((e&31)<<6|k);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|k<<6|f:(e&7)<<18|k<<12|f<<6|c[a++]&63;65536>e?b+=String.fromCharCode(e):(e-=65536,b+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else b+=String.fromCharCode(e)}return b},
$a=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],I=a=>{a=2<a?a?H(a):"":a;return $a[a]||("undefined"!=typeof document?document.querySelector(a):null)},ab=a=>0>$a.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},bb=[],cb,J=a=>{var b=bb[a];b||(bb[a]=b=cb.get(a));return b};function db(a){var b=K.Wb[a];b.target.removeEventListener(b.Vb,b.Ac,b.Xb);K.Wb.splice(a,1)}
function eb(){if(navigator.userActivation?navigator.userActivation.isActive:K.lc&&K.Nc.ic){var a=K.ac;K.ac=[];for(var b of a)b.oc(...b.vc)}}function L(a){if(!a.target)return-4;if(a.Yb)a.Ac=function(c){++K.lc;K.Nc=a;eb();a.Zb(c);eb();--K.lc},a.target.addEventListener(a.Vb,a.Ac,a.Xb),K.Wb.push(a);else for(var b=0;b<K.Wb.length;++b)K.Wb[b].target==a.target&&K.Wb[b].Vb==a.Vb&&db(b--);return 0}function fb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var K={Uc:0,gd:0,mc:0,fc:0,sc:0,qc:0,jc:0,$c:0,md:0,Zc:0,kc:0,nc:0,vd:0,pc:0,jd(a,b,c){q.set(q.subarray(b,b+c),a)},od(){for(;K.Wb.length;)db(K.Wb.length-1);K.ac=[]},lc:0,ac:[],Yc(a,b,c){function d(k,f){if(k.length!=f.length)return!1;for(var m in k)if(k[m]!=f[m])return!1;return!0}for(var e of K.ac)if(e.oc==a&&d(e.vc,c))return;K.ac.push({oc:a,Ec:b,vc:c});K.ac.sort((k,f)=>k.Ec<f.Ec)},qd(a){K.ac=K.ac.filter(b=>b.oc!=a)},Wb:[],pd:(a,b)=>{for(var c=0;c<K.Wb.length;++c)K.Wb[c].target!=a||b&&b!=K.Wb[c].Vb||
db(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},M=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var f=a.codePointAt(k);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;k++}}d[b]=0;return b-
e},gb=(a,b,c,d,e,k)=>{K.jc||(K.jc=N(256));a={target:I(a),Vb:k,Yb:d,Zb:(f=event)=>{var m=f.target.id?f.target.id:"",p=K.jc;M(fb(f.target),p+0,128);M(m,p+128,128);J(d)(e,p,b)&&f.preventDefault()},Xb:c};return L(a)},hb=(a,b,c,d,e)=>{K.kc||(K.kc=N(276));return L({target:a,Vb:e,Yb:d,Zb:(k=event)=>{var f=K.kc,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,p=!!m;q[f]=p;q[f+1]=K.fullscreenEnabled();
var r=p?m:K.Rc,A=r?.id||"";M(fb(r),f+2,128);M(A,f+130,128);u[f+260>>2]=r?r.clientWidth:0;u[f+264>>2]=r?r.clientHeight:0;u[f+268>>2]=screen.width;u[f+272>>2]=screen.height;p&&(K.Rc=m);J(d)(19,f,b)&&k.preventDefault()},Xb:c})},ib=(a,b,c,d,e,k)=>{K.mc||(K.mc=N(160));a={target:I(a),Vb:k,Yb:d,Zb:f=>{var m=K.mc;x[m>>3]=f.timeStamp;var p=m>>2;u[p+2]=f.location;q[m+12]=f.ctrlKey;q[m+13]=f.shiftKey;q[m+14]=f.altKey;q[m+15]=f.metaKey;q[m+16]=f.repeat;u[p+5]=f.charCode;u[p+6]=f.keyCode;u[p+7]=f.which;M(f.key||
"",m+32,32);M(f.code||"",m+64,32);M(f.char||"",m+96,32);M(f.locale||"",m+128,32);J(d)(e,m,b)&&f.preventDefault()},Xb:c};return L(a)},jb=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;q[a+24]=b.ctrlKey;q[a+25]=b.shiftKey;q[a+26]=b.altKey;q[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=ab(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,k)=>{K.fc||(K.fc=N(64));a=
I(a);return L({target:a,ic:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Vb:k,Yb:d,Zb:(f=event)=>{jb(K.fc,f,a);J(d)(e,K.fc,b)&&f.preventDefault()},Xb:c})},kb=(a,b,c,d)=>{K.nc||(K.nc=N(257));return L({target:a,Vb:"pointerlockchange",Yb:d,Zb:(e=event)=>{var k=K.nc,f=document.pointerLockElement;q[k]=!!f;var m=f?.id||"";M(fb(f),k+1,128);M(m,k+129,128);J(d)(20,k,b)&&e.preventDefault()},Xb:c})},lb=(a,b,c,d)=>L({target:a,Vb:"pointerlockerror",Yb:d,Zb:(e=event)=>{J(d)(38,0,b)&&e.preventDefault()},Xb:c}),
mb=(a,b,c,d)=>{K.qc||(K.qc=N(36));a=I(a);return L({target:a,Vb:"resize",Yb:d,Zb:(e=event)=>{if(e.target==a){var k=document.body;if(k){var f=K.qc;u[f>>2]=0;u[f+4>>2]=k.clientWidth;u[f+8>>2]=k.clientHeight;u[f+12>>2]=innerWidth;u[f+16>>2]=innerHeight;u[f+20>>2]=outerWidth;u[f+24>>2]=outerHeight;u[f+28>>2]=pageXOffset|0;u[f+32>>2]=pageYOffset|0;J(d)(10,f,b)&&e.preventDefault()}}},Xb:c})},nb=(a,b,c,d,e,k)=>{K.pc||(K.pc=N(1552));a=I(a);return L({target:a,ic:"touchstart"==k||"touchend"==k,Vb:k,Yb:d,Zb:f=>
{var m={},p=f.touches;for(var r of p)r.Bc=r.Dc=0,m[r.identifier]=r;for(var A of f.changedTouches)A.Bc=1,m[A.identifier]=A;for(var oa of f.targetTouches)m[oa.identifier].Dc=1;p=K.pc;x[p>>3]=f.timeStamp;q[p+12]=f.ctrlKey;q[p+13]=f.shiftKey;q[p+14]=f.altKey;q[p+15]=f.metaKey;r=p+16;A=ab(a);oa=0;for(let B of Object.values(m))if(m=r>>2,u[m]=B.identifier,u[m+1]=B.screenX,u[m+2]=B.screenY,u[m+3]=B.clientX,u[m+4]=B.clientY,u[m+5]=B.pageX,u[m+6]=B.pageY,q[r+28]=B.Bc,q[r+29]=B.Dc,u[m+8]=B.clientX-(A.left|0),
u[m+9]=B.clientY-(A.top|0),r+=48,31<++oa)break;u[p+8>>2]=oa;J(d)(e,p,b)&&f.preventDefault()},Xb:c})},P,ob=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=(c,d,e,k,f)=>b.drawElementsInstancedANGLE(c,d,e,k,f))},pb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>
b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},qb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},rb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},sb=1,Q=[],R=[],tb=[],ub=[],S=[],T=[],vb=[],wb=[],xb=[],yb={},zb=a=>{for(var b=sb++,c=a.length;c<b;c++)a[c]=null;return b},Ab=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=P[c](),f=k&&zb(d);k?(k.name=f,d[f]=k):U||=1282;u[b+4*e>>2]=f}},Cb=(a,b)=>{a.uc||(a.uc=a.getContext,a.getContext=function(d,e){e=a.uc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Cc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Bb(c,
b):0},Bb=(a,b)=>{var c=zb(wb),d={handle:c,attributes:b,version:b.Cc,tc:a};a.canvas&&(a.canvas.Sc=d);wb[c]=d;("undefined"==typeof b.zc||b.zc)&&Db(d);return c},Db=a=>{a||=V;if(!a.Qc){a.Qc=!0;var b=a.tc;b.ld=b.getExtension("WEBGL_multi_draw");b.dd=b.getExtension("EXT_polygon_offset_clamp");b.cd=b.getExtension("EXT_clip_control");b.wd=b.getExtension("WEBGL_polygon_mode");ob(b);pb(b);qb(b);b.ad=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.hd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.yc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.yc)b.yc=b.getExtension("EXT_disjoint_timer_query");rb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},U,V,Eb=(a,b,c,d,e,k)=>{a={target:I(a),Vb:k,Yb:d,Zb:(f=event)=>{J(d)(e,0,b)&&f.preventDefault()},Xb:c};L(a)},Fb=(a,b,c,d)=>{K.sc||(K.sc=N(96));return L({target:a,ic:!0,Vb:"wheel",Yb:d,Zb:(e=event)=>{var k=K.sc;jb(k,e,a);x[k+64>>3]=e.deltaX;x[k+72>>3]=e.deltaY;x[k+80>>3]=e.deltaZ;
u[k+88>>2]=e.deltaMode;J(d)(9,k,b)&&e.preventDefault()},Xb:c})},Gb=["default","low-power","high-performance"],Hb=[],Ib=()=>{var a=rb(P);return a=a.concat(a.map(b=>"GL_"+b))},Jb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=Ib().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=P.getParameter(a),
typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+
4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;h(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;h(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else U||=1281},Kb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Lb=a=>{var b=Kb(a)+1,c=N(b);c&&M(a,c,
b);return c},Mb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),W=a=>{var b=P.Oc;if(b){var c=b.bc[a];"number"==typeof c&&(b.bc[a]=c=P.getUniformLocation(b,b.Lc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],Nb=[],Pb=a=>{var b=Kb(a)+1,c=Ob(b);M(a,c,b);return c},Sb=a=>{var b=Qb();a();Rb(b)};g.requestAnimationFrame=Ma;g.pauseMainLoop=Ya;g.resumeMainLoop=function(){Pa++;var a=Ia,b=Ja,c=D;D=null;Xa(c,0,!1,Qa,!0);Oa(a,b);E()};g.preMainLoop&&Va.push(g.preMainLoop);g.postMainLoop&&Wa.push(g.postMainLoop);
for(let a=0;32>a;++a)Hb.push(Array(a));for(var Tb=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=Tb.subarray(0,Y);var Ub=new Int32Array(288);for(Y=0;288>=Y;++Y)Nb[Y]=Ub.subarray(0,Y);g.noExitRuntime&&(Ba=g.noExitRuntime);g.printErr&&(h=g.printErr);g.wasmBinary&&(l=g.wasmBinary);g.arguments&&(da=g.arguments);g.thisProgram&&(ea=g.thisProgram);if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();
var Vb,Wb,Xb,Yb,Zb,$b,N,ac,Rb,Ob,Qb,bc={Xa:()=>ra(""),Ua:()=>{Ba=!1;Ca=0},Va:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ha(()=>ac(a,performance.now()))},b);C[a]={id:c,ud:b};return 0},Ka:()=>{Ya();D=null},ca:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ea:(a,b,c)=>{a=I(a);if(!a)return-4;a=ab(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},La:()=>performance.now(),Ra:(a,b)=>{function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
Wa:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);qa();var e=1;break a}catch(k){}e=void 0}if(e)return!0}return!1},M:(a,b,c,d)=>gb(a,b,c,d,12,"blur"),ba:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},N:(a,b,c,d)=>gb(a,b,c,d,13,"focus"),L:(a,b,c,d)=>{if(!K.fullscreenEnabled())return-1;a=I(a);if(!a)return-4;
hb(a,b,c,d,"webkitfullscreenchange");return hb(a,b,c,d,"fullscreenchange")},W:(a,b,c,d)=>ib(a,b,c,d,2,"keydown"),U:(a,b,c,d)=>ib(a,b,c,d,1,"keypress"),V:(a,b,c,d)=>ib(a,b,c,d,3,"keyup"),Sa:(a,b,c)=>{a=J(a);Xa(a,b,c)},aa:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),Z:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),Y:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),_:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),$:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),P:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?kb(a,b,c,d):-4:-1,O:(a,b,c,d)=>document.body?.requestPointerLock?
(a=I(a))?lb(a,b,c,d):-4:-1,da:(a,b,c,d)=>mb(a,b,c,d),Q:(a,b,c,d)=>nb(a,b,c,d,25,"touchcancel"),R:(a,b,c,d)=>nb(a,b,c,d,23,"touchend"),S:(a,b,c,d)=>nb(a,b,c,d,24,"touchmove"),T:(a,b,c,d)=>nb(a,b,c,d,22,"touchstart"),K:(a,b,c,d)=>{Eb(a,b,c,d,31,"webglcontextlost");return 0},J:(a,b,c,d)=>{Eb(a,b,c,d,32,"webglcontextrestored");return 0},X:(a,b,c,d)=>(a=I(a))?"undefined"!=typeof a.onwheel?Fb(a,b,c,d):-1:-4,Qa:(a,b)=>{var c=b>>2;b={alpha:!!q[b+0],depth:!!q[b+1],stencil:!!q[b+2],antialias:!!q[b+3],premultipliedAlpha:!!q[b+
4],preserveDrawingBuffer:!!q[b+5],powerPreference:Gb[u[c+2]],failIfMajorPerformanceCaveat:!!q[b+12],Cc:u[c+4],kd:u[c+5],zc:q[b+24],Pc:q[b+25],nd:u[c+7],rd:q[b+32]};a=I(a);return!a||b.Pc?0:Cb(a,b)},Oa:a=>{V=wb[a];g.ctx=P=V?.tc;return!a||P?0:-5},i:a=>P.activeTexture(a),o:(a,b)=>{P.attachShader(R[a],T[b])},b:(a,b)=>{35051==a?P.wc=b:35052==a&&(P.xc=b);P.bindBuffer(a,Q[b])},r:(a,b,c)=>{P.bindBufferBase(a,b,Q[c])},mb:(a,b,c,d,e)=>{P.bindBufferRange(a,b,Q[c],d,e)},f:(a,b)=>{P.bindFramebuffer(a,tb[b])},h:(a,
b)=>{P.bindSampler(a,xb[b])},c:(a,b)=>{P.bindTexture(a,S[b])},I:a=>{P.bindVertexArray(vb[a])},E:(a,b,c,d)=>P.blendColor(a,b,c,d),F:(a,b)=>P.blendEquationSeparate(a,b),G:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),Za:(a,b,c,d,e,k,f,m,p,r)=>P.blitFramebuffer(a,b,c,d,e,k,f,m,p,r),wa:(a,b,c,d)=>{2<=V.version?c&&b?P.bufferData(a,t,d,c,b):P.bufferData(a,b,d):P.bufferData(a,c?t.subarray(c,c+b):b,d)},va:(a,b,c,d)=>{2<=V.version?c&&P.bufferSubData(a,b,t,d,c):P.bufferSubData(a,b,t.subarray(d,d+c))},ja:a=>P.checkFramebufferStatus(a),
tb:(a,b,c,d)=>P.clearBufferfi(a,b,c,d),ia:(a,b,c)=>{P.clearBufferfv(a,b,w,c>>2)},sb:(a,b,c)=>{P.clearBufferiv(a,b,u,c>>2)},j:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},na:a=>{P.compileShader(T[a])},ta:()=>{var a=zb(R),b=P.createProgram();b.name=a;b.ec=b.cc=b.dc=0;b.rc=1;R[a]=b;return a},qa:a=>{var b=zb(T);T[b]=P.createShader(a);return b},B:a=>P.cullFace(a),Ba:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(P.deleteBuffer(e),e.name=0,Q[d]=null,d==P.wc&&(P.wc=0),d==P.xc&&(P.xc=0))}},A:(a,b)=>
{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=tb[d];e&&(P.deleteFramebuffer(e),e.name=0,tb[d]=null)}},m:a=>{if(a){var b=R[a];b?(P.deleteProgram(b),b.name=0,R[a]=null):U||=1281}},za:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=ub[d];e&&(P.deleteRenderbuffer(e),e.name=0,ub[d]=null)}},Aa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=xb[d];e&&(P.deleteSampler(e),e.name=0,xb[d]=null)}},g:a=>{if(a){var b=T[a];b?(P.deleteShader(b),T[a]=null):U||=1281}},p:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],
e=S[d];e&&(P.deleteTexture(e),e.name=0,S[d]=null)}},ya:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];P.deleteVertexArray(vb[d]);vb[d]=null}},t:a=>P.depthFunc(a),s:a=>{P.depthMask(!!a)},d:a=>P.disable(a),H:a=>{P.disableVertexAttribArray(a)},$a:(a,b,c)=>{P.drawArrays(a,b,c)},ab:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},ka:(a,b)=>{for(var c=Hb[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];P.drawBuffers(c)},bb:(a,b,c,d)=>{P.drawElements(a,b,c,d)},cb:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},e:a=>P.enable(a),
nb:a=>{P.enableVertexAttribArray(a)},u:(a,b,c,d)=>{P.framebufferRenderbuffer(a,b,c,ub[d])},k:(a,b,c,d,e)=>{P.framebufferTexture2D(a,b,c,S[d],e)},v:(a,b,c,d,e)=>{P.framebufferTextureLayer(a,b,S[c],d,e)},C:a=>P.frontFace(a),xa:(a,b)=>{Ab(a,b,"createBuffer",Q)},Ia:(a,b)=>{Ab(a,b,"createFramebuffer",tb)},Ja:(a,b)=>{Ab(a,b,"createVertexArray",vb)},la:(a,b)=>P.getAttribLocation(R[a],b?H(b):""),a:(a,b)=>Jb(a,b),sa:(a,b,c,d)=>{a=P.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):
0;c&&(u[c>>2]=b)},y:(a,b,c)=>{if(c)if(a>=sb)U||=1281;else if(a=R[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.ec){var d=P.getProgramParameter(a,35718);for(b=0;b<d;++b)a.ec=Math.max(a.ec,P.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.ec}else if(35722==b){if(!a.cc)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.cc=Math.max(a.cc,P.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.cc}else if(35381==b){if(!a.dc)for(d=P.getProgramParameter(a,
35382),b=0;b<d;++b)a.dc=Math.max(a.dc,P.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.dc}else u[c>>2]=P.getProgramParameter(a,b);else U||=1281},ma:(a,b,c,d)=>{a=P.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},w:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(T[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=P.getShaderParameter(T[a],b):U||=1281},Ga:(a,b)=>{if(2>V.version)return U||=
1282,0;var c=yb[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Ib().map(Lb),c=yb[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},x:(a,b)=>{b=b?H(b):"";if(a=R[a]){var c=a,d=c.bc,e=c.Mc,k;if(!d){c.bc=d={};c.Lc={};var f=P.getProgramParameter(c,35718);for(k=0;k<f;++k){var m=P.getActiveUniform(c,k);var p=m.name;m=m.size;var r=Mb(p);r=0<r?p.slice(0,r):p;var A=c.rc;c.rc+=m;e[r]=[m,A];for(p=0;p<m;++p)d[A]=p,c.Lc[A++]=r}}c=a.bc;d=0;e=b;k=Mb(b);0<k&&(d=parseInt(b.slice(k+
1))>>>0,e=b.slice(0,k));if((e=a.Mc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else U||=1281;return-1},Ya:(a,b,c)=>{for(var d=Hb[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];P.invalidateFramebuffer(a,d)},z:a=>{a=R[a];P.linkProgram(a);a.bc=0;a.Mc={}},Ha:(a,b)=>{P.pixelStorei(a,b)},D:(a,b)=>P.polygonOffset(a,b),_a:a=>P.readBuffer(a),ub:(a,b,c,d)=>P.scissor(a,b,c,d),pa:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var f=(f=v[c+4*k>>2])?H(f,d?v[d+4*k>>2]:void 0):"";e+=f}P.shaderSource(T[a],e)},Ea:(a,
b,c)=>P.stencilFunc(a,b,c),ha:(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),n:a=>P.stencilMask(a),Da:(a,b,c)=>P.stencilOp(a,b,c),ga:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),lb:(a,b,c)=>{if(2<=V.version)b&&P.uniform1fv(W(a),w,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);P.uniform1fv(W(a),d)}},ra:(a,b)=>{P.uniform1i(W(a),b)},hb:(a,b,c)=>{if(2<=V.version)b&&P.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=Nb[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=
u.subarray(c>>2,c+4*b>>2);P.uniform1iv(W(a),d)}},kb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2fv(W(a),w,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);P.uniform2fv(W(a),d)}},gb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Nb[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);P.uniform2iv(W(a),d)}},jb:(a,b,c)=>{if(2<=V.version)b&&P.uniform3fv(W(a),
w,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);P.uniform3fv(W(a),d)}},fb:(a,b,c)=>{if(2<=V.version)b&&P.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Nb[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);P.uniform3iv(W(a),d)}},ib:(a,b,c)=>{if(2<=V.version)b&&P.uniform4fv(W(a),w,c>>2,4*b);else{if(72>=b){var d=X[4*b],
e=w;c>>=2;b*=4;for(var k=0;k<b;k+=4){var f=c+k;d[k]=e[f];d[k+1]=e[f+1];d[k+2]=e[f+2];d[k+3]=e[f+3]}}else d=w.subarray(c>>2,c+16*b>>2);P.uniform4fv(W(a),d)}},eb:(a,b,c)=>{if(2<=V.version)b&&P.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Nb[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);P.uniform4iv(W(a),d)}},db:(a,b,c,d)=>{if(2<=V.version)b&&P.uniformMatrix4fv(W(a),!!c,w,d>>2,16*b);else{if(18>=b){var e=
X[16*b],k=w;d>>=2;b*=16;for(var f=0;f<b;f+=16){var m=d+f;e[f]=k[m];e[f+1]=k[m+1];e[f+2]=k[m+2];e[f+3]=k[m+3];e[f+4]=k[m+4];e[f+5]=k[m+5];e[f+6]=k[m+6];e[f+7]=k[m+7];e[f+8]=k[m+8];e[f+9]=k[m+9];e[f+10]=k[m+10];e[f+11]=k[m+11];e[f+12]=k[m+12];e[f+13]=k[m+13];e[f+14]=k[m+14];e[f+15]=k[m+15]}}else e=w.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(W(a),!!c,e)}},l:a=>{a=R[a];P.useProgram(a);P.Oc=a},pb:(a,b)=>{P.vertexAttribDivisor(a,b)},qb:(a,b,c,d,e)=>{P.vertexAttribIPointer(a,b,c,d,e)},rb:(a,b,c,d,e,k)=>
{P.vertexAttribPointer(a,b,c,!!d,e,k)},vb:(a,b,c,d)=>P.viewport(a,b,c,d),Ta:Ea,yb:function(){g.Fc=a=>{0!=Wb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Fc)},Pa:function(){g.Kc=a=>{const b=a.clipboardData.getData("text");Sb(()=>{const c=Pb(b);Vb(c)})};window.addEventListener("paste",g.Kc)},Ma:function(){g.sd=[];g.Gc=b=>{b.stopPropagation();b.preventDefault()};g.Hc=b=>{b.stopPropagation();b.preventDefault()};g.Ic=b=>{b.stopPropagation();b.preventDefault()};g.Jc=
b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.td=c;Xb(c.length);for(let e=0;e<c.length;e++)Sb(()=>{const k=Pb(c[e].name);Yb(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Zb(b.clientX,b.clientY,d)};const a=g.$b;a.addEventListener("dragenter",g.Gc,!1);a.addEventListener("dragleave",g.Hc,!1);a.addEventListener("dragover",g.Ic,!1);a.addEventListener("drop",g.Jc,!1)},wb:function(){const a=document.getElementById("sokol-app-favicon");
a&&document.head.removeChild(a)},oa:function(a){g.hc&&(URL.revokeObjectURL(g.hc[a].Vc),g.hc[a]=null)},Ca:function(a,b){0!==b&&(document.title=b?H(b):"");a=a?H(a):"";void 0!==g.canvas&&("object"===typeof g.canvas?$a[a]=g.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));g.$b=I(a);g.$b||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);g.$b.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},xb:function(){window.removeEventListener("beforeunload",
g.Fc)},Na:function(){window.removeEventListener("paste",g.Kc)},Fa:function(){const a=g.$b;a.removeEventListener("dragenter",g.Gc);a.removeEventListener("dragleave",g.Hc);a.removeEventListener("dragover",g.Ic);a.removeEventListener("drop",g.Jc)},q:function(){g.$b&&g.$b.requestPointerLock&&g.$b.requestPointerLock()},ua:function(a,b,c){if(g.$b){if(0===b)a="none";else if(0!=c)a=g.hc[a].Xc;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a=
"pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.$b.style.cursor=a}},ob:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(t.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=
d.toDataURL();document.head.appendChild(a)},fa:function(a,b){b=b?H(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function cc(a=[]){var b=$b;a.unshift(ea);var c=a.length,d=Ob(4*(c+1)),e=d;a.forEach(f=>{v[e>>2]=Pb(f);e+=4});v[e>>2]=0;try{var k=b(c,d);Fa(k)}catch(f){Da(f)}}
function dc(a=da){function b(){g.calledRun=!0;if(!n){Z.Ab();g.onRuntimeInitialized?.();g.noInitialRun||cc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();ya.push(c)}xa(ya)}}if(0<y)z=dc;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Aa();xa(za);0<y?z=dc:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}var Z;
(async function(){function a(c){Z=c.exports;na=Z.zb;qa();cb=Z.Rb;c=Z;g.__sapp_emsc_onpaste=Vb=c.Bb;g.__sapp_html5_get_ask_leave_site=Wb=c.Cb;g.__sapp_emsc_begin_drop=Xb=c.Db;g.__sapp_emsc_drop=Yb=c.Eb;g.__sapp_emsc_end_drop=Zb=c.Fb;g.__sapp_emsc_invoke_fetch_cb=c.Gb;g.__sapp_emsc_set_fullscreen_flag=c.Hb;g._main=$b=c.Ib;g.__saudio_emsc_pull=c.Jb;g.__sfetch_emsc_head_response=c.Kb;g.__sfetch_emsc_get_response=c.Lb;g.__sfetch_emsc_failed_http_status=c.Mb;g.__sfetch_emsc_failed_buffer_too_small=c.Nb;
g.__sfetch_emsc_failed_other=c.Ob;N=c.Pb;ac=c.Qb;Rb=c.Sb;Ob=c.Tb;Qb=c.Ub;y--;g.monitorRunDependencies?.(y);0==y&&z&&(c=z,z=null,c());return Z}y++;g.monitorRunDependencies?.(y);var b={a:bc};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});sa??=g.locateFile?g.locateFile("sdf-sapp.wasm",ia):ia+"sdf-sapp.wasm";return a((await va(b)).instance)})();dc();
