var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),m,p=!1,na,la=a=>a.startsWith("file://"),oa,r,u,pa,qa,v,w,x,y;
function ra(){var a=oa.buffer;r=new Int8Array(a);pa=new Int16Array(a);u=new Uint8Array(a);qa=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function sa(a){g.onAbort?.(a);a="Aborted("+a+")";k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(g)},za=[],Aa=[],Ba=()=>{var a=g.preRun.shift();Aa.push(a)},z=0,A=null,Ca=!0,Da="undefined"!=typeof TextDecoder?new TextDecoder:void 0,B=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Da)return Da.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):
(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Ea=0,C={},Fa=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Ga=a=>{na=a;Ca||0<Ea||(g.onExit?.(a),p=!0);fa(a,new xa(a))},Ha=a=>{na=a;Ga(a)},Ia=()=>{if(!(Ca||0<Ea))try{var a=na;na=a;Ga(a)}catch(b){Fa(b)}},Ja=a=>{if(!p)try{a(),Ia()}catch(b){Fa(b)}},Ra=(a,b)=>{Ka=a;La=b;if(F)if(Ma||=!0,0==a)G=function(){setTimeout(Na,Math.max(0,Oa+b-performance.now())|0)};else if(1==a)G=function(){Pa(Na)};else if(2==a){if("undefined"==
typeof Qa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Qa=setImmediate;G=function(){Qa(Na)}}},$a=(a,b,c,d,e)=>{function h(){return f<Sa?(Ia(),!1):!0}F=a;Ta=d;var f=Sa;Ma=!1;Na=function(){if(!p)if(0<
Ua.length){var l=Ua.shift();l.Cd(l.qd);if(Va){var n=Va,q=0==n%1?n-1:Math.floor(n);Va=l.td?q:(8*n+(q+.5))/9}g.setStatus&&(l=g.statusMessage||"Please wait...",n=Va??0,q=Wa.zd??0,n?n<q?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(l):g.setStatus(""));h()&&setTimeout(Na,0)}else if(h())if(Xa=Xa+1|0,1==Ka&&1<La&&0!=Xa%La)G();else{0==Ka&&(Oa=performance.now());a:if(!p){for(l of Ya)if(!1===l())break a;Ja(a);for(n of Za)n()}h()&&G()}};e||(0<b?Ra(0,1E3/b):Ra(1,1),G());if(c)throw"unwind";
},Ma=!1,G=null,Sa=0,F=null,Ta=0,Ka=0,La=0,Xa=0,Ua=[],Ya=[],Za=[];function ab(){G=null;Sa++}var bb=0;function Pa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===bb)bb=b+1E3/60;else for(;b+2>=bb;)bb+=1E3/60;setTimeout(a,Math.max(bb-b,0))}}
var Wa={},Oa,Na,Qa,Va,cb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],H=a=>{a=2<a?a?B(u,a):"":a;return cb[a]||("undefined"!=typeof document?document.querySelector(a):null)},db=a=>0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},eb=[],fb,I=a=>{var b=eb[a];b||(eb[a]=b=fb.get(a));return b};function gb(a){var b=J.sc[a];b.target.removeEventListener(b.rc,b.Vc,b.tc);J.sc.splice(a,1)}
function hb(){if(navigator.userActivation?navigator.userActivation.isActive:J.Ic&&J.kd.Fc){var a=J.xc;J.xc=[];for(var b of a)b.Lc(...b.Rc)}}function K(a){if(!a.target)return-4;if(a.uc)a.Vc=function(c){++J.Ic;J.kd=a;hb();a.vc(c);hb();--J.Ic},a.target.addEventListener(a.rc,a.Vc,a.tc),J.sc.push(a);else for(var b=0;b<J.sc.length;++b)J.sc[b].target==a.target&&J.sc[b].rc==a.rc&&gb(b--);return 0}function ib(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var J={rd:0,Dd:0,Jc:0,Dc:0,Pc:0,Nc:0,Gc:0,xd:0,Id:0,wd:0,Hc:0,Kc:0,Rd:0,Mc:0,Fd(a,b,c){r.set(r.subarray(b,b+c),a)},Kd(){for(;J.sc.length;)gb(J.sc.length-1);J.xc=[]},Ic:0,xc:[],vd(a,b,c){function d(h,f){if(h.length!=f.length)return!1;for(var l in h)if(h[l]!=f[l])return!1;return!0}for(var e of J.xc)if(e.Lc==a&&d(e.Rc,c))return;J.xc.push({Lc:a,Zc:b,Rc:c});J.xc.sort((h,f)=>h.Zc<f.Zc)},Md(a){J.xc=J.xc.filter(b=>b.Lc!=a)},sc:[],Ld:(a,b)=>{for(var c=0;c<J.sc.length;++c)J.sc[c].target!=a||b&&b!=J.sc[c].rc||
gb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},L=(a,b,c)=>{var d=u;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.codePointAt(h);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;h++}}d[b]=0;return b-
e},jb=(a,b,c,d,e,h)=>{J.Gc||(J.Gc=M(256));a={target:H(a),rc:h,uc:d,vc:(f=event)=>{var l=f.target.id?f.target.id:"",n=J.Gc;L(ib(f.target),n+0,128);L(l,n+128,128);I(d)(e,n,b)&&f.preventDefault()},tc:c};return K(a)},kb=(a,b,c,d,e)=>{J.Hc||(J.Hc=M(276));return K({target:a,rc:e,uc:d,vc:(h=event)=>{var f=J.Hc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!l;r[f]=n;r[f+1]=J.fullscreenEnabled();
var q=n?l:J.od,t=q?.id||"";L(ib(q),f+2,128);L(t,f+130,128);v[f+260>>2]=q?q.clientWidth:0;v[f+264>>2]=q?q.clientHeight:0;v[f+268>>2]=screen.width;v[f+272>>2]=screen.height;n&&(J.od=l);I(d)(19,f,b)&&h.preventDefault()},tc:c})},lb=(a,b,c,d,e,h)=>{J.Jc||(J.Jc=M(160));a={target:H(a),rc:h,uc:d,vc:f=>{var l=J.Jc;y[l>>3]=f.timeStamp;var n=l>>2;v[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;v[n+5]=f.charCode;v[n+6]=f.keyCode;v[n+7]=f.which;L(f.key||
"",l+32,32);L(f.code||"",l+64,32);L(f.char||"",l+96,32);L(f.locale||"",l+128,32);I(d)(e,l,b)&&f.preventDefault()},tc:c};return K(a)},mb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=db(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},nb=(a,b,c,d,e,h)=>{J.Dc||(J.Dc=M(64));a=
H(a);return K({target:a,Fc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,rc:h,uc:d,vc:(f=event)=>{mb(J.Dc,f,a);I(d)(e,J.Dc,b)&&f.preventDefault()},tc:c})},ob=(a,b,c,d)=>{J.Kc||(J.Kc=M(257));return K({target:a,rc:"pointerlockchange",uc:d,vc:(e=event)=>{var h=J.Kc,f=document.pointerLockElement;r[h]=!!f;var l=f?.id||"";L(ib(f),h+1,128);L(l,h+129,128);I(d)(20,h,b)&&e.preventDefault()},tc:c})},pb=(a,b,c,d)=>K({target:a,rc:"pointerlockerror",uc:d,vc:(e=event)=>{I(d)(38,0,b)&&e.preventDefault()},tc:c}),
qb=(a,b,c,d)=>{J.Nc||(J.Nc=M(36));a=H(a);return K({target:a,rc:"resize",uc:d,vc:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=J.Nc;v[f>>2]=0;v[f+4>>2]=h.clientWidth;v[f+8>>2]=h.clientHeight;v[f+12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+20>>2]=outerWidth;v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|0;v[f+32>>2]=pageYOffset|0;I(d)(10,f,b)&&e.preventDefault()}}},tc:c})},rb=(a,b,c,d,e,h)=>{J.Mc||(J.Mc=M(1552));a=H(a);return K({target:a,Fc:"touchstart"==h||"touchend"==h,rc:h,uc:d,vc:f=>
{var l={},n=f.touches;for(var q of n)q.Wc=q.Yc=0,l[q.identifier]=q;for(var t of f.changedTouches)t.Wc=1,l[t.identifier]=t;for(var D of f.targetTouches)l[D.identifier].Yc=1;n=J.Mc;y[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=f.shiftKey;r[n+14]=f.altKey;r[n+15]=f.metaKey;q=n+16;t=db(a);D=0;for(let E of Object.values(l))if(l=q>>2,v[l]=E.identifier,v[l+1]=E.screenX,v[l+2]=E.screenY,v[l+3]=E.clientX,v[l+4]=E.clientY,v[l+5]=E.pageX,v[l+6]=E.pageY,r[q+28]=E.Wc,r[q+29]=E.Yc,v[l+8]=E.clientX-(t.left|0),v[l+
9]=E.clientY-(t.top|0),q+=48,31<++D)break;v[n+8>>2]=D;I(d)(e,n,b)&&f.preventDefault()},tc:c})},N,sb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},tb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},ub=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},vb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},wb=1,O=[],P=[],xb=[],yb=[],Q=[],R=[],zb=[],Ab=[],S=[],Bb={},Cb=4,Db=0,Eb=a=>{for(var b=wb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=N[c](),f=h&&Eb(d);h?(h.name=f,d[f]=h):T||=1282;v[b+4*e>>2]=f}},Gb=(a,b)=>{a.$c||(a.$c=a.getContext,a.getContext=function(d,e){e=a.$c(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Xc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Fb(c,b):0},Fb=(a,b)=>{var c=Eb(Ab),d={handle:c,attributes:b,version:b.Xc,Qc:a};a.canvas&&(a.canvas.pd=d);Ab[c]=d;("undefined"==typeof b.Uc||b.Uc)&&Hb(d);return c},Hb=a=>{a||=V;if(!a.nd){a.nd=!0;var b=a.Qc;b.Hd=b.getExtension("WEBGL_multi_draw");b.Bd=b.getExtension("EXT_polygon_offset_clamp");b.Ad=b.getExtension("EXT_clip_control");b.Sd=b.getExtension("WEBGL_polygon_mode");sb(b);tb(b);ub(b);b.yd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Ed=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Tc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Tc)b.Tc=b.getExtension("EXT_disjoint_timer_query");vb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Ib=(a,b,c,d,e,h)=>{a={target:H(a),rc:h,uc:d,vc:(f=event)=>{I(d)(e,0,b)&&f.preventDefault()},tc:c};K(a)},Jb=(a,b,c,d)=>{J.Pc||(J.Pc=M(96));return K({target:a,Fc:!0,rc:"wheel",uc:d,vc:(e=event)=>{var h=J.Pc;mb(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+80>>3]=e.deltaZ;
v[h+88>>2]=e.deltaMode;I(d)(9,h,b)&&e.preventDefault()},tc:c})},Kb=["default","low-power","high-performance"],Lb={},Nb=()=>{if(!Mb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Lb)void 0===Lb[b]?delete a[b]:a[b]=Lb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Mb=c}return Mb},Mb,Ob=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=
d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Pb=[null,[],[]],Qb=[],Rb=()=>{var a=vb(N);return a=a.concat(a.map(b=>"GL_"+b))},Sb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=N.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Rb().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=N.getParameter(a),typeof d){case "number":c=
d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else T||=1281},Tb=a=>{var b=Ob(a)+1,c=M(b);c&&L(a,c,b);return c},Ub=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Vb=a=>{a-=5120;return 0==a?r:1==a?u:2==a?pa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==
a?w:qa},W=a=>{var b=N.ld;if(b){var c=b.zc[a];"number"==typeof c&&(b.zc[a]=c=N.getUniformLocation(b,b.hd[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],Wb=[],Yb=a=>{var b=Ob(a)+1,c=Xb(b);L(a,c,b);return c},ac=a=>{var b=Zb();a();$b(b)};g.requestAnimationFrame=Pa;g.pauseMainLoop=ab;g.resumeMainLoop=function(){Sa++;var a=Ka,b=La,c=F;F=null;$a(c,0,!1,Ta,!0);Ra(a,b);G()};g.preMainLoop&&Ya.push(g.preMainLoop);g.postMainLoop&&Za.push(g.postMainLoop);for(let a=0;32>a;++a)Qb.push(Array(a));
for(var bc=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=bc.subarray(0,Y);var cc=new Int32Array(288);for(Y=0;288>=Y;++Y)Wb[Y]=cc.subarray(0,Y);g.noExitRuntime&&(Ca=g.noExitRuntime);g.print&&(ma=g.print);g.printErr&&(k=g.printErr);g.wasmBinary&&(m=g.wasmBinary);g.arguments&&(da=g.arguments);g.thisProgram&&(ea=g.thisProgram);if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();
var dc,ec,fc,gc,hc,ic,M,jc,$b,Xb,Zb,kc={oa:function(){return 0},ib:function(){return 0},jb:function(){},mb:()=>sa(""),cb:()=>{Ca=!1;Ea=0},db:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ja(()=>jc(a,performance.now()))},b);C[a]={id:c,Qd:b};return 0},Ua:()=>{ab();F=null},la:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,qa:(a,b,c)=>{a=H(a);if(!a)return-4;a=db(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Va:()=>performance.now(),$a:(a,
b)=>{function c(d){I(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},eb:a=>{var b=u.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);ra();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},V:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),ka:(a,b,c)=>{a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},W:(a,b,c,d)=>
jb(a,b,c,d,13,"focus"),U:(a,b,c,d)=>{if(!J.fullscreenEnabled())return-1;a=H(a);if(!a)return-4;kb(a,b,c,d,"webkitfullscreenchange");return kb(a,b,c,d,"fullscreenchange")},da:(a,b,c,d)=>lb(a,b,c,d,2,"keydown"),ba:(a,b,c,d)=>lb(a,b,c,d,1,"keypress"),ca:(a,b,c,d)=>lb(a,b,c,d,3,"keyup"),ab:(a,b,c)=>{a=I(a);$a(a,b,c)},ja:(a,b,c,d)=>nb(a,b,c,d,5,"mousedown"),ga:(a,b,c,d)=>nb(a,b,c,d,33,"mouseenter"),fa:(a,b,c,d)=>nb(a,b,c,d,34,"mouseleave"),ha:(a,b,c,d)=>nb(a,b,c,d,8,"mousemove"),ia:(a,b,c,d)=>nb(a,b,c,
d,6,"mouseup"),Y:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?ob(a,b,c,d):-4:-1,X:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?pb(a,b,c,d):-4:-1,na:(a,b,c,d)=>qb(a,b,c,d),Z:(a,b,c,d)=>rb(a,b,c,d,25,"touchcancel"),_:(a,b,c,d)=>rb(a,b,c,d,23,"touchend"),$:(a,b,c,d)=>rb(a,b,c,d,24,"touchmove"),aa:(a,b,c,d)=>rb(a,b,c,d,22,"touchstart"),T:(a,b,c,d)=>{Ib(a,b,c,d,31,"webglcontextlost");return 0},S:(a,b,c,d)=>{Ib(a,b,c,d,32,"webglcontextrestored");return 0},ea:(a,b,c,d)=>(a=H(a))?"undefined"!=
typeof a.onwheel?Jb(a,b,c,d):-1:-4,Za:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Kb[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Xc:v[c+4],Gd:v[c+5],Uc:r[b+24],md:r[b+25],Jd:v[c+7],Nd:r[b+32]};a=H(a);return!a||b.md?0:Gb(a,b)},Ya:a=>{V=Ab[a];g.ctx=N=V?.Qc;return!a||N?0:-5},kb:(a,b)=>{var c=0,d=0,e;for(e of Nb()){var h=b+c;w[a+d>>2]=h;c+=L(e,h,Infinity)+1;d+=4}return 0},lb:(a,b)=>
{var c=Nb();w[a>>2]=c.length;a=0;for(var d of c)a+=Ob(d)+1;w[b>>2]=a;return 0},ma:()=>52,hb:()=>52,fb:function(){return 70},gb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var f=w[b>>2],l=w[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=a,t=u[f+n],D=Pb[q];0===t||10===t?((1===q?ma:k)(B(D)),D.length=0):D.push(t)}e+=l}w[d>>2]=e;return 0},o:a=>N.activeTexture(a),u:(a,b)=>{N.attachShader(P[a],R[b])},b:(a,b)=>{35051==a?N.Sc=b:35052==a&&(N.yc=b);N.bindBuffer(a,O[b])},a:(a,b,c)=>{N.bindBufferBase(a,b,O[c])},Db:(a,b,c,d,
e)=>{N.bindBufferRange(a,b,O[c],d,e)},h:(a,b)=>{N.bindFramebuffer(a,xb[b])},Ob:(a,b)=>{N.bindRenderbuffer(a,yb[b])},n:(a,b)=>{N.bindSampler(a,S[b])},d:(a,b)=>{N.bindTexture(a,Q[b])},R:a=>{N.bindVertexArray(zb[a])},M:(a,b,c,d)=>N.blendColor(a,b,c,d),N:(a,b)=>N.blendEquationSeparate(a,b),O:(a,b,c,d)=>N.blendFuncSeparate(a,b,c,d),ob:(a,b,c,d,e,h,f,l,n,q)=>N.blitFramebuffer(a,b,c,d,e,h,f,l,n,q),Ia:(a,b,c,d)=>{2<=V.version?c&&b?N.bufferData(a,u,d,c,b):N.bufferData(a,b,d):N.bufferData(a,c?u.subarray(c,
c+b):b,d)},H:(a,b,c,d)=>{2<=V.version?c&&N.bufferSubData(a,b,u,d,c):N.bufferSubData(a,b,u.subarray(d,d+c))},Lb:a=>N.checkFramebufferStatus(a),Kb:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),ua:(a,b,c)=>{N.clearBufferfv(a,b,x,c>>2)},Jb:(a,b,c)=>{N.clearBufferiv(a,b,v,c>>2)},p:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},Sb:a=>{N.compileShader(R[a])},w:(a,b,c,d,e,h,f,l,n)=>{2<=V.version?N.yc||!l?N.compressedTexSubImage2D(a,b,c,d,e,h,f,l,n):N.compressedTexSubImage2D(a,b,c,d,e,h,f,u,n,l):N.compressedTexSubImage2D(a,
b,c,d,e,h,f,u.subarray(n,n+l))},Ea:(a,b,c,d,e,h,f,l,n,q,t)=>{N.yc?N.compressedTexSubImage3D(a,b,c,d,e,h,f,l,n,q,t):N.compressedTexSubImage3D(a,b,c,d,e,h,f,l,n,u,t,q)},Ba:()=>{var a=Eb(P),b=N.createProgram();b.name=a;b.Cc=b.Ac=b.Bc=0;b.Oc=1;P[a]=b;return a},ya:a=>{var b=Eb(R);R[b]=N.createShader(a);return b},J:a=>N.cullFace(a),La:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=O[d];e&&(N.deleteBuffer(e),e.name=0,O[d]=null,d==N.Sc&&(N.Sc=0),d==N.yc&&(N.yc=0))}},y:(a,b)=>{for(var c=0;c<a;++c){var d=
v[b+4*c>>2],e=xb[d];e&&(N.deleteFramebuffer(e),e.name=0,xb[d]=null)}},m:a=>{if(a){var b=P[a];b?(N.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},I:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=yb[d];e&&(N.deleteRenderbuffer(e),e.name=0,yb[d]=null)}},r:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(N.deleteSampler(e),e.name=0,S[d]=null)}},k:a=>{if(a){var b=R[a];b?(N.deleteShader(b),R[a]=null):T||=1281}},i:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(N.deleteTexture(e),e.name=
0,Q[d]=null)}},Ka:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];N.deleteVertexArray(zb[d]);zb[d]=null}},A:a=>N.depthFunc(a),z:a=>{N.depthMask(!!a)},e:a=>N.disable(a),P:a=>{N.disableVertexAttribArray(a)},qb:(a,b,c)=>{N.drawArrays(a,b,c)},rb:(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},wa:(a,b)=>{for(var c=Qb[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];N.drawBuffers(c)},sb:(a,b,c,d)=>{N.drawElements(a,b,c,d)},tb:(a,b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},g:a=>N.enable(a),Eb:a=>{N.enableVertexAttribArray(a)},
va:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,yb[d])},j:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,Q[d],e)},B:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,Q[c],d,e)},K:a=>N.frontFace(a),Ja:(a,b)=>{U(a,b,"createBuffer",O)},Q:(a,b)=>{U(a,b,"createFramebuffer",xb)},Pb:(a,b)=>{U(a,b,"createRenderbuffer",yb)},Ca:(a,b)=>{U(a,b,"createSampler",S)},Ha:(a,b)=>{U(a,b,"createTexture",Q)},Ta:(a,b)=>{U(a,b,"createVertexArray",zb)},Qb:(a,b)=>N.getAttribLocation(P[a],b?B(u,b):""),c:(a,b)=>Sb(a,b),Aa:(a,b,c,d)=>
{a=N.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(v[c>>2]=b)},D:(a,b,c)=>{if(c)if(a>=wb)T||=1281;else if(a=P[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.Cc){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Cc=Math.max(a.Cc,N.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.Cc}else if(35722==b){if(!a.Ac)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.Ac=Math.max(a.Ac,N.getActiveAttrib(a,b).name.length+
1);v[c>>2]=a.Ac}else if(35381==b){if(!a.Bc)for(d=N.getProgramParameter(a,35382),b=0;b<d;++b)a.Bc=Math.max(a.Bc,N.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Bc}else v[c>>2]=N.getProgramParameter(a,b);else T||=1281},Rb:(a,b,c,d)=>{a=N.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(v[c>>2]=b)},xa:(a,b,c)=>{c?35716==b?(a=N.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(R[a]),v[c>>2]=a?a.length+1:0):v[c>>
2]=N.getShaderParameter(R[a],b):T||=1281},Ra:(a,b)=>{if(2>V.version)return T||=1282,0;var c=Bb[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Rb().map(Tb),c=Bb[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},C:(a,b)=>{b=b?B(u,b):"";if(a=P[a]){var c=a,d=c.zc,e=c.jd,h;if(!d){c.zc=d={};c.hd={};var f=N.getProgramParameter(c,35718);for(h=0;h<f;++h){var l=N.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Ub(n);q=0<q?n.slice(0,q):n;var t=c.Oc;c.Oc+=l;
e[q]=[l,t];for(n=0;n<l;++n)d[t]=n,c.hd[t++]=q}}c=a.zc;d=0;e=b;h=Ub(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.jd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T||=1281;return-1},nb:(a,b,c)=>{for(var d=Qb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];N.invalidateFramebuffer(a,d)},E:a=>{a=P[a];N.linkProgram(a);a.zc=0;a.jd={}},Sa:(a,b)=>{3317==a?Cb=b:3314==a&&(Db=b);N.pixelStorei(a,b)},L:(a,b)=>N.polygonOffset(a,b),pb:a=>N.readBuffer(a),Nb:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,
b,c,d,e),F:(a,b,c)=>{N.samplerParameterf(S[a],b,c)},f:(a,b,c)=>{N.samplerParameteri(S[a],b,c)},t:(a,b,c,d)=>N.scissor(a,b,c,d),Tb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=w[c+4*h>>2])?B(u,f,d?w[d+4*h>>2]:void 0):"";e+=f}N.shaderSource(R[a],e)},Pa:(a,b,c)=>N.stencilFunc(a,b,c),ta:(a,b,c,d)=>N.stencilFuncSeparate(a,b,c,d),s:a=>N.stencilMask(a),Oa:(a,b,c)=>N.stencilOp(a,b,c),sa:(a,b,c,d)=>N.stencilOpSeparate(a,b,c,d),Ga:(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),Fa:(a,b,c,d,e,h)=>N.texStorage3D(a,
b,c,d,e,h),v:(a,b,c,d,e,h,f,l,n)=>{if(2<=V.version){if(N.yc){N.texSubImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var q=Vb(l);N.texSubImage2D(a,b,c,d,e,h,f,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=Vb(l);var t=h*((Db||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*q.BYTES_PER_ELEMENT+Cb-1&-Cb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+t>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;N.texSubImage2D(a,b,c,d,e,h,f,l,n)},Da:(a,b,c,d,e,h,f,l,
n,q,t)=>{if(N.yc)N.texSubImage3D(a,b,c,d,e,h,f,l,n,q,t);else if(t){var D=Vb(q);N.texSubImage3D(a,b,c,d,e,h,f,l,n,q,D,t>>>31-Math.clz32(D.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,b,c,d,e,h,f,l,n,q,null)},Cb:(a,b,c)=>{if(2<=V.version)b&&N.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);N.uniform1fv(W(a),d)}},za:(a,b)=>{N.uniform1i(W(a),b)},yb:(a,b,c)=>{if(2<=V.version)b&&N.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=Wb[b],
e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);N.uniform1iv(W(a),d)}},Bb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);N.uniform2fv(W(a),d)}},xb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2iv(W(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Wb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);N.uniform2iv(W(a),d)}},Ab:(a,
b,c)=>{if(2<=V.version)b&&N.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);N.uniform3fv(W(a),d)}},wb:(a,b,c)=>{if(2<=V.version)b&&N.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Wb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);N.uniform3iv(W(a),d)}},zb:(a,b,c)=>{if(2<=V.version)b&&N.uniform4fv(W(a),
x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);N.uniform4fv(W(a),d)}},vb:(a,b,c)=>{if(2<=V.version)b&&N.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Wb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);N.uniform4iv(W(a),d)}},ub:(a,b,c,d)=>{if(2<=V.version)b&&N.uniformMatrix4fv(W(a),
!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(W(a),!!c,e)}},l:a=>{a=P[a];N.useProgram(a);N.ld=a},Fb:(a,b)=>{N.vertexAttribDivisor(a,b)},Gb:(a,b,c,d,e)=>{N.vertexAttribIPointer(a,
b,c,d,e)},Hb:(a,b,c,d,e,h)=>{N.vertexAttribPointer(a,b,c,!!d,e,h)},q:(a,b,c,d)=>N.viewport(a,b,c,d),bb:Ga,Wb:function(){g.ad=a=>{0!=ec()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.ad)},_a:function(){g.gd=a=>{const b=a.clipboardData.getData("text");ac(()=>{const c=Yb(b);dc(c)})};window.addEventListener("paste",g.gd)},Qa:function(){g.Od=[];g.bd=b=>{b.stopPropagation();b.preventDefault()};g.cd=b=>{b.stopPropagation();b.preventDefault()};g.dd=b=>{b.stopPropagation();
b.preventDefault()};g.ed=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Pd=c;fc(c.length);for(let e=0;e<c.length;e++)ac(()=>{const h=Yb(c[e].name);gc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);hc(b.clientX,b.clientY,d)};const a=g.wc;a.addEventListener("dragenter",g.bd,!1);a.addEventListener("dragleave",g.cd,!1);a.addEventListener("dragover",g.dd,!1);a.addEventListener("drop",g.ed,!1)},Mb:function(){const a=document.getElementById("sokol-app-favicon");
a&&document.head.removeChild(a)},Ub:function(a){g.Ec&&(URL.revokeObjectURL(g.Ec[a].sd),g.Ec[a]=null)},Ma:function(a,b){0!==b&&(document.title=b?B(u,b):"");a=a?B(u,a):"";void 0!==g.canvas&&("object"===typeof g.canvas?cb[a]=g.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));g.wc=H(a);g.wc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);g.wc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Vb:function(){window.removeEventListener("beforeunload",
g.ad)},Xa:function(){window.removeEventListener("paste",g.gd)},Na:function(){const a=g.wc;a.removeEventListener("dragenter",g.bd);a.removeEventListener("dragleave",g.cd);a.removeEventListener("dragover",g.dd);a.removeEventListener("drop",g.ed)},x:function(){g.wc&&g.wc.requestPointerLock&&g.wc.requestPointerLock()},G:function(a,b,c){if(g.wc){if(0===b)a="none";else if(0!=c)a=g.Ec[a].ud;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a=
"pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.wc.style.cursor=a}},Ib:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(u.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=
d.toDataURL();document.head.appendChild(a)},Wa:function(a){a=a?B(u,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},pa:function(){return navigator.userAgent.includes("Macintosh")?
1:0},ra:function(a,b){b=b?B(u,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function lc(a=[]){var b=ic;a.unshift(ea);var c=a.length,d=Xb(4*(c+1)),e=d;a.forEach(f=>{w[e>>2]=Yb(f);e+=4});w[e>>2]=0;try{var h=b(c,d);Ha(h)}catch(f){Fa(f)}}
function mc(a=da){function b(){g.calledRun=!0;if(!p){Z.Yb();g.onRuntimeInitialized?.();g.noInitialRun||lc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();za.push(c)}ya(za)}}if(0<z)A=mc;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ba();ya(Aa);0<z?A=mc:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}var Z;
(async function(){function a(c){Z=c.exports;oa=Z.Xb;ra();fb=Z.mc;c=Z;g.__sapp_emsc_onpaste=dc=c.Zb;g.__sapp_html5_get_ask_leave_site=ec=c._b;g.__sapp_emsc_begin_drop=fc=c.$b;g.__sapp_emsc_drop=gc=c.ac;g.__sapp_emsc_end_drop=hc=c.bc;g.__sapp_emsc_invoke_fetch_cb=c.cc;g.__sapp_emsc_set_fullscreen_flag=c.dc;g._main=ic=c.ec;g.__saudio_emsc_pull=c.fc;g.__sfetch_emsc_head_response=c.gc;g.__sfetch_emsc_get_response=c.hc;g.__sfetch_emsc_failed_http_status=c.ic;g.__sfetch_emsc_failed_buffer_too_small=c.jc;
g.__sfetch_emsc_failed_other=c.kc;M=c.lc;jc=c.nc;$b=c.oc;Xb=c.pc;Zb=c.qc;z--;g.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;g.monitorRunDependencies?.(z);var b={a:kc};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ta??=g.locateFile?g.locateFile("shadows-sapp-ui.wasm",ia):ia+"shadows-sapp-ui.wasm";return a((await wa(b)).instance)})();mc();
