var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da={...g},ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs");require("path");k=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!g.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?
"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var la=g.print||console.log.bind(console),m=g.printErr||console.error.bind(console);Object.assign(g,da);da=null;g.arguments&&(ea=g.arguments);g.thisProgram&&(fa=g.thisProgram);var ma=g.wasmBinary,na,p=!1,oa,r,t,pa,qa,u,v,x,y,ka=a=>a.startsWith("file://");
function ra(){var a=na.buffer;g.HEAP8=r=new Int8Array(a);g.HEAP16=pa=new Int16Array(a);g.HEAPU8=t=new Uint8Array(a);g.HEAPU16=qa=new Uint16Array(a);g.HEAP32=u=new Int32Array(a);g.HEAPU32=v=new Uint32Array(a);g.HEAPF32=x=new Float32Array(a);g.HEAPF64=y=new Float64Array(a);g.HEAP64=new BigInt64Array(a);g.HEAPU64=new BigUint64Array(a)}var z=0,A=null;function sa(a){g.onAbort?.(a);a="Aborted("+a+")";m(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function va(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==ta&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function xa(a){var b=ta;if(!ma&&"function"==typeof WebAssembly.instantiateStreaming&&!ka(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=a=>{for(;0<a.length;)a.shift()(g)},Aa=[],Ba=[],Ca=()=>{var a=g.preRun.shift();Ba.unshift(a)},Da=g.noExitRuntime||!0,Ea="undefined"!=typeof TextDecoder?new TextDecoder:void 0,B=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ea)return Ea.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):
(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Fa=0,C={},Ga=a=>{a instanceof ya||"unwind"==a||ha(1,a)},Ha=a=>{oa=a;Da||0<Fa||(g.onExit?.(a),p=!0);ha(a,new ya(a))},Ia=a=>{oa=a;Ha(a)},Ja=()=>{if(!(Da||0<Fa))try{var a=oa;oa=a;Ha(a)}catch(b){Ga(b)}},Ka=a=>{if(!p)try{a(),Ja()}catch(b){Ga(b)}},Ra=(a,b)=>{La=a;Ma=b;if(D)if(Na||=!0,0==a)F=function(){setTimeout(G,Math.max(0,Oa+b-performance.now())|0)};else if(1==a)F=function(){Pa(G)};else if(2==a){if("undefined"==
typeof Qa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Qa=setImmediate;F=function(){Qa(G)}}},$a=(a,b,c,d,e)=>{function h(){return f<Sa?(Ja(),!1):!0}D=a;Ta=d;var f=Sa;Na=!1;G=function(){if(!p)if(0<Ua.length){var l=
Ua.shift();l.wd(l.ld);if(Va){var n=Va,q=0==n%1?n-1:Math.floor(n);Va=l.nd?q:(8*n+(q+.5))/9}g.setStatus&&(l=g.statusMessage||"Please wait...",n=Va??0,q=Wa.sd??0,n?n<q?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(l):g.setStatus(""));h()&&setTimeout(G,0)}else if(h())if(Xa=Xa+1|0,1==La&&1<Ma&&0!=Xa%Ma)F();else{0==La&&(Oa=performance.now());a:if(!p){for(l of Ya)if(!1===l())break a;Ka(a);for(n of Za)n()}h()&&F()}};e||(0<b?Ra(0,1E3/b):Ra(1,1),F());if(c)throw"unwind";},Na=!1,F=
null,Sa=0,D=null,Ta=0,La=0,Ma=0,Xa=0,Ua=[],Ya=[],Za=[];function ab(){F=null;Sa++}var H=0;function Pa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===H)H=b+1E3/60;else for(;b+2>=H;)H+=1E3/60;setTimeout(a,Math.max(H-b,0))}}
var Wa={},Oa,G,Qa,Va,bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],I=a=>{a=2<a?a?B(t,a):"":a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):null)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=[],eb,J=a=>{var b=db[a];b||(db[a]=b=eb.get(a));return b};function fb(a){var b=K.oc[a];b.target.removeEventListener(b.nc,b.Qc,b.pc);K.oc.splice(a,1)}
function gb(){if(navigator.userActivation?navigator.userActivation.isActive:K.Dc&&K.ed.Bc){var a=K.tc;K.tc=[];for(var b of a)b.Gc(...b.Mc)}}function L(a){if(!a.target)return-4;if(a.qc)a.Qc=function(c){++K.Dc;K.ed=a;gb();a.rc(c);gb();--K.Dc},a.target.addEventListener(a.nc,a.Qc,a.pc),K.oc.push(a);else for(var b=0;b<K.oc.length;++b)K.oc[b].target==a.target&&K.oc[b].nc==a.nc&&fb(b--);return 0}function hb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var K={md:0,xd:0,Ec:0,Ac:0,Kc:0,Ic:0,Cc:0,qd:0,Cd:0,pd:0,vd:0,Fc:0,Ld:0,Hc:0,zd(a,b,c){r.set(r.subarray(b,b+c),a)},Ed(){for(;K.oc.length;)fb(K.oc.length-1);K.tc=[]},Dc:0,tc:[],od(a,b,c){function d(h,f){if(h.length!=f.length)return!1;for(var l in h)if(h[l]!=f[l])return!1;return!0}for(var e of K.tc)if(e.Gc==a&&d(e.Mc,c))return;K.tc.push({Gc:a,Wc:b,Mc:c});K.tc.sort((h,f)=>h.Wc<f.Wc)},Gd(a){K.tc=K.tc.filter(b=>b.Gc!=a)},oc:[],Fd:(a,b)=>{for(var c=0;c<K.oc.length;++c)K.oc[c].target!=a||b&&b!=K.oc[c].nc||
fb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},M=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var l=a.charCodeAt(++h);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|
f&63}}d[b]=0;return b-e},ib=(a,b,c,d,e,h)=>{K.Cc||(K.Cc=N(256));a={target:I(a),nc:h,qc:d,rc:(f=event)=>{var l=f.target.id?f.target.id:"",n=K.Cc;M(hb(f.target),n+0,128);M(l,n+128,128);J(d)(e,n,b)&&f.preventDefault()},pc:c};return L(a)},jb=(a,b,c,d,e,h)=>{K.Ec||(K.Ec=N(160));a={target:I(a),nc:h,qc:d,rc:f=>{var l=K.Ec;y[l>>3]=f.timeStamp;var n=l>>2;u[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;u[n+5]=f.charCode;u[n+6]=f.keyCode;u[n+7]=f.which;
M(f.key||"",l+32,32);M(f.code||"",l+64,32);M(f.char||"",l+96,32);M(f.locale||"",l+128,32);J(d)(e,l,b)&&f.preventDefault()},pc:c};return L(a)},kb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=cb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},lb=(a,b,c,d,e,h)=>{K.Ac||(K.Ac=
N(64));a=I(a);return L({target:a,Bc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,nc:h,qc:d,rc:(f=event)=>{kb(K.Ac,f,a);J(d)(e,K.Ac,b)&&f.preventDefault()},pc:c})},mb=(a,b,c,d,e)=>{K.Fc||(K.Fc=N(257));return L({target:a,nc:e,qc:d,rc:(h=event)=>{var f=K.Fc,l=document.pointerLockElement||document.vc||document.Vc||document.Tc;r[f]=!!l;var n=l?.id||"";M(hb(l),f+1,128);M(n,f+129,128);J(d)(20,f,b)&&h.preventDefault()},pc:c})},nb=(a,b,c,d,e)=>L({target:a,nc:e,qc:d,rc:(h=event)=>{J(d)(38,0,b)&&h.preventDefault()},
pc:c}),ob=(a,b,c,d)=>{K.Ic||(K.Ic=N(36));a=I(a);return L({target:a,nc:"resize",qc:d,rc:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=K.Ic;u[f>>2]=0;u[f+4>>2]=h.clientWidth;u[f+8>>2]=h.clientHeight;u[f+12>>2]=innerWidth;u[f+16>>2]=innerHeight;u[f+20>>2]=outerWidth;u[f+24>>2]=outerHeight;u[f+28>>2]=pageXOffset|0;u[f+32>>2]=pageYOffset|0;J(d)(10,f,b)&&e.preventDefault()}}},pc:c})},pb=(a,b,c,d,e,h)=>{K.Hc||(K.Hc=N(1552));a=I(a);return L({target:a,Bc:"touchstart"==h||"touchend"==h,nc:h,qc:d,
rc:f=>{var l={},n=f.touches;for(var q of n)q.Rc=q.Uc=0,l[q.identifier]=q;for(var w of f.changedTouches)w.Rc=1,l[w.identifier]=w;for(var ua of f.targetTouches)l[ua.identifier].Uc=1;n=K.Hc;y[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=f.shiftKey;r[n+14]=f.altKey;r[n+15]=f.metaKey;q=n+16;w=cb(a);ua=0;for(let E of Object.values(l))if(l=q>>2,u[l]=E.identifier,u[l+1]=E.screenX,u[l+2]=E.screenY,u[l+3]=E.clientX,u[l+4]=E.clientY,u[l+5]=E.pageX,u[l+6]=E.pageY,r[q+28]=E.Rc,r[q+29]=E.Uc,u[l+8]=E.clientX-(w.left|
0),u[l+9]=E.clientY-(w.top|0),q+=48,31<++ua)break;u[n+8>>2]=ua;J(d)(e,n,b)&&f.preventDefault()},pc:c})},O,qb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},rb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=
c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},sb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},tb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},ub=1,vb=[],P=[],wb=[],xb=[],Q=[],R=[],yb=[],zb=[],S=[],Ab={},Bb=4,Cb=0,Db=a=>{for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=O[c](),f=h&&Db(d);h?(h.name=f,d[f]=h):T||=1282;u[b+4*e>>2]=f}},Fb=(a,b)=>{a.vc||(a.vc=a.getContext,a.getContext=function(d,e){e=a.vc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Sc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Eb(c,b):0},Eb=(a,b)=>{var c=Db(zb),d={handle:c,attributes:b,version:b.Sc,Lc:a};a.canvas&&(a.canvas.kd=d);zb[c]=d;("undefined"==typeof b.Pc||b.Pc)&&Gb(d);return c},Gb=a=>{a||=V;if(!a.jd){a.jd=!0;var b=a.Lc;b.Bd=b.getExtension("WEBGL_multi_draw");b.ud=b.getExtension("EXT_polygon_offset_clamp");b.td=b.getExtension("EXT_clip_control");b.Md=b.getExtension("WEBGL_polygon_mode");qb(b);rb(b);sb(b);b.rd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.yd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Oc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Oc)b.Oc=b.getExtension("EXT_disjoint_timer_query");tb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Hb=(a,b,c,d,e,h)=>{a={target:I(a),nc:h,qc:d,rc:(f=event)=>{J(d)(e,0,b)&&f.preventDefault()},pc:c};L(a)},Ib=(a,b,c,d)=>{K.Kc||(K.Kc=N(96));return L({target:a,Bc:!0,nc:"wheel",qc:d,rc:(e=event)=>{var h=K.Kc;kb(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+80>>3]=e.deltaZ;
u[h+88>>2]=e.deltaMode;J(d)(9,h,b)&&e.preventDefault()},pc:c})},Jb=["default","low-power","high-performance"],Kb={},Mb=()=>{if(!Lb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in Kb)void 0===Kb[b]?delete a[b]:a[b]=Kb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Lb=c}return Lb},Lb,Nb=[null,[],[]],Ob=[],Pb=()=>{var a=tb(O);
return a=a.concat(a.map(b=>"GL_"+b))},Qb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=O.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Pb().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=O.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else T||=1281},Rb=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Sb=a=>{var b=Rb(a)+1,c=N(b);c&&M(a,c,b);return c},Tb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ub=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?u:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?v:qa},W=a=>{var b=O.gd;if(b){var c=b.wc[a];"number"==typeof c&&(b.wc[a]=c=O.getUniformLocation(b,b.cd[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],Vb=[],Xb=a=>{var b=Rb(a)+1,c=
Wb(b);M(a,c,b);return c},$b=a=>{var b=Yb();a();Zb(b)};g.requestAnimationFrame=Pa;g.pauseMainLoop=ab;g.resumeMainLoop=function(){Sa++;var a=La,b=Ma,c=D;D=null;$a(c,0,!1,Ta,!0);Ra(a,b);F()};g.preMainLoop&&Ya.push(g.preMainLoop);g.postMainLoop&&Za.push(g.postMainLoop);for(let a=0;32>a;++a)Ob.push(Array(a));for(var ac=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=ac.subarray(0,Y);var bc=new Int32Array(288);for(Y=0;288>=Y;++Y)Vb[Y]=bc.subarray(0,Y);
var ic={ia:function(){return 0},lb:function(){return 0},mb:function(){},pb:()=>sa(""),fb:()=>{Da=!1;Fa=0},gb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ka(()=>cc(a,performance.now()))},b);C[a]={id:c,Kd:b};return 0},Xa:()=>{ab();D=null},ga:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,la:(a,b,c)=>{a=I(a);if(!a)return-4;a=cb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Ya:()=>performance.now(),cb:(a,b)=>{function c(d){J(a)(d,b)&&
requestAnimationFrame(c)}return requestAnimationFrame(c)},hb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ra();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},Q:(a,b,c,d)=>ib(a,b,c,d,12,"blur"),fa:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},R:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),_:(a,b,
c,d)=>jb(a,b,c,d,2,"keydown"),Y:(a,b,c,d)=>jb(a,b,c,d,1,"keypress"),Z:(a,b,c,d)=>jb(a,b,c,d,3,"keyup"),db:(a,b,c)=>{a=J(a);$a(a,b,c)},ea:(a,b,c,d)=>lb(a,b,c,d,5,"mousedown"),ba:(a,b,c,d)=>lb(a,b,c,d,33,"mouseenter"),aa:(a,b,c,d)=>lb(a,b,c,d,34,"mouseleave"),ca:(a,b,c,d)=>lb(a,b,c,d,8,"mousemove"),da:(a,b,c,d)=>lb(a,b,c,d,6,"mouseup"),T:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.vc||document.body.Vc||document.body.Tc))return-1;a=I(a);if(!a)return-4;
mb(a,b,c,d,"mozpointerlockchange");mb(a,b,c,d,"webkitpointerlockchange");mb(a,b,c,d,"mspointerlockchange");return mb(a,b,c,d,"pointerlockchange")},S:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.vc||document.body.Vc||document.body.Tc))return-1;a=I(a);if(!a)return-4;nb(a,b,c,d,"mozpointerlockerror");nb(a,b,c,d,"webkitpointerlockerror");nb(a,b,c,d,"mspointerlockerror");return nb(a,b,c,d,"pointerlockerror")},ka:(a,b,c,d)=>ob(a,b,c,d),U:(a,b,c,d)=>pb(a,b,c,d,25,"touchcancel"),
V:(a,b,c,d)=>pb(a,b,c,d,23,"touchend"),W:(a,b,c,d)=>pb(a,b,c,d,24,"touchmove"),X:(a,b,c,d)=>pb(a,b,c,d,22,"touchstart"),P:(a,b,c,d)=>{Hb(a,b,c,d,31,"webglcontextlost");return 0},O:(a,b,c,d)=>{Hb(a,b,c,d,32,"webglcontextrestored");return 0},$:(a,b,c,d)=>(a=I(a))?"undefined"!=typeof a.onwheel?Ib(a,b,c,d):-1:-4,bb:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Jb[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+
12],Sc:u[c+4],Ad:u[c+5],Pc:r[b+24],hd:r[b+25],Dd:u[c+7],Hd:r[b+32]};a=I(a);return!a||b.hd?0:Fb(a,b)},$a:a=>{V=zb[a];g.ctx=O=V?.Lc;return!a||O?0:-5},nb:(a,b)=>{var c=0;Mb().forEach((d,e)=>{var h=b+c;e=v[a+4*e>>2]=h;for(h=0;h<d.length;++h)r[e++]=d.charCodeAt(h);r[e]=0;c+=d.length+1});return 0},ob:(a,b)=>{var c=Mb();v[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);v[b>>2]=d;return 0},ha:()=>52,kb:()=>52,ib:function(){return 70},jb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var f=v[b>>2],l=v[b+4>>2];b+=
8;for(var n=0;n<l;n++){var q=t[f+n],w=Nb[a];0===q||10===q?((1===a?la:m)(B(w)),w.length=0):w.push(q)}e+=l}v[d>>2]=e;return 0},o:a=>O.activeTexture(a),t:(a,b)=>{O.attachShader(P[a],R[b])},b:(a,b)=>{35051==a?O.Nc=b:35052==a&&(O.uc=b);O.bindBuffer(a,vb[b])},a:(a,b,c)=>{O.bindBufferBase(a,b,vb[c])},h:(a,b)=>{O.bindFramebuffer(a,wb[b])},Ja:(a,b)=>{O.bindRenderbuffer(a,xb[b])},n:(a,b)=>{O.bindSampler(a,S[b])},d:(a,b)=>{O.bindTexture(a,Q[b])},N:a=>{O.bindVertexArray(yb[a])},J:(a,b,c,d)=>O.blendColor(a,b,
c,d),K:(a,b)=>O.blendEquationSeparate(a,b),L:(a,b,c,d)=>O.blendFuncSeparate(a,b,c,d),rb:(a,b,c,d,e,h,f,l,n,q)=>O.blitFramebuffer(a,b,c,d,e,h,f,l,n,q),La:(a,b,c,d)=>{2<=V.version?c&&b?O.bufferData(a,t,d,c,b):O.bufferData(a,b,d):O.bufferData(a,c?t.subarray(c,c+b):b,d)},D:(a,b,c,d)=>{2<=V.version?c&&O.bufferSubData(a,b,t,d,c):O.bufferSubData(a,b,t.subarray(d,d+c))},ra:a=>O.checkFramebufferStatus(a),Lb:(a,b,c,d)=>O.clearBufferfi(a,b,c,d),pa:(a,b,c)=>{O.clearBufferfv(a,b,x,c>>2)},Kb:(a,b,c)=>{O.clearBufferiv(a,
b,u,c>>2)},p:(a,b,c,d)=>{O.colorMask(!!a,!!b,!!c,!!d)},Pb:a=>{O.compileShader(R[a])},Da:(a,b,c,d,e,h,f,l)=>{2<=V.version?O.uc||!f?O.compressedTexImage2D(a,b,c,d,e,h,f,l):O.compressedTexImage2D(a,b,c,d,e,h,t,l,f):O.compressedTexImage2D(a,b,c,d,e,h,t.subarray(l,l+f))},Ba:(a,b,c,d,e,h,f,l,n)=>{O.uc?O.compressedTexImage3D(a,b,c,d,e,h,f,l,n):O.compressedTexImage3D(a,b,c,d,e,h,f,t,n,l)},xa:()=>{var a=Db(P),b=O.createProgram();b.name=a;b.zc=b.xc=b.yc=0;b.Jc=1;P[a]=b;return a},Rb:a=>{var b=Db(R);R[b]=O.createShader(a);
return b},G:a=>O.cullFace(a),Pa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=vb[d];e&&(O.deleteBuffer(e),e.name=0,vb[d]=null,d==O.Nc&&(O.Nc=0),d==O.uc&&(O.uc=0))}},k:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=wb[d];e&&(O.deleteFramebuffer(e),e.name=0,wb[d]=null)}},m:a=>{if(a){var b=P[a];b?(O.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},E:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=xb[d];e&&(O.deleteRenderbuffer(e),e.name=0,xb[d]=null)}},r:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*
c>>2],e=S[d];e&&(O.deleteSampler(e),e.name=0,S[d]=null)}},j:a=>{if(a){var b=R[a];b?(O.deleteShader(b),R[a]=null):T||=1281}},F:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(O.deleteTexture(e),e.name=0,Q[d]=null)}},Na:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];O.deleteVertexArray(yb[d]);yb[d]=null}},x:a=>O.depthFunc(a),w:a=>{O.depthMask(!!a)},e:a=>O.disable(a),M:a=>{O.disableVertexAttribArray(a)},tb:(a,b,c)=>{O.drawArrays(a,b,c)},ub:(a,b,c,d)=>{O.drawArraysInstanced(a,b,c,d)},qa:(a,
b)=>{for(var c=Ob[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];O.drawBuffers(c)},vb:(a,b,c,d)=>{O.drawElements(a,b,c,d)},wb:(a,b,c,d,e)=>{O.drawElementsInstanced(a,b,c,d,e)},g:a=>O.enable(a),Gb:a=>{O.enableVertexAttribArray(a)},sa:(a,b,c,d)=>{O.framebufferRenderbuffer(a,b,c,xb[d])},i:(a,b,c,d,e)=>{O.framebufferTexture2D(a,b,c,Q[d],e)},y:(a,b,c,d,e)=>{O.framebufferTextureLayer(a,b,Q[c],d,e)},H:a=>O.frontFace(a),Ma:(a,b)=>{U(a,b,"createBuffer",vb)},ta:(a,b)=>{U(a,b,"createFramebuffer",wb)},Ka:(a,b)=>{U(a,b,"createRenderbuffer",
xb)},za:(a,b)=>{U(a,b,"createSampler",S)},Ha:(a,b)=>{U(a,b,"createTexture",Q)},Wa:(a,b)=>{U(a,b,"createVertexArray",yb)},Nb:(a,b)=>O.getAttribLocation(P[a],b?B(t,b):""),c:(a,b)=>Qb(a,b),wa:(a,b,c,d)=>{a=O.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},A:(a,b,c)=>{if(c)if(a>=ub)T||=1281;else if(a=P[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.zc){var d=O.getProgramParameter(a,35718);for(b=
0;b<d;++b)a.zc=Math.max(a.zc,O.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.zc}else if(35722==b){if(!a.xc)for(d=O.getProgramParameter(a,35721),b=0;b<d;++b)a.xc=Math.max(a.xc,O.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.xc}else if(35381==b){if(!a.yc)for(d=O.getProgramParameter(a,35382),b=0;b<d;++b)a.yc=Math.max(a.yc,O.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.yc}else u[c>>2]=O.getProgramParameter(a,b);else T||=1281},Ob:(a,b,c,d)=>{a=O.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");
b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},ua:(a,b,c)=>{c?35716==b?(a=O.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(R[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=O.getShaderParameter(R[a],b):T||=1281},Ua:(a,b)=>{if(2>V.version)return T||=1282,0;var c=Ab[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Pb().map(Sb),c=Ab[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},z:(a,b)=>{b=b?B(t,b):"";if(a=P[a]){var c=
a,d=c.wc,e=c.dd,h;if(!d){c.wc=d={};c.cd={};var f=O.getProgramParameter(c,35718);for(h=0;h<f;++h){var l=O.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Tb(n);q=0<q?n.slice(0,q):n;var w=c.Jc;c.Jc+=l;e[q]=[l,w];for(n=0;n<l;++n)d[w]=n,c.cd[w++]=q}}c=a.wc;d=0;e=b;h=Tb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.dd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else T||=1281;return-1},qb:(a,b,c)=>{for(var d=Ob[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];O.invalidateFramebuffer(a,
d)},B:a=>{a=P[a];O.linkProgram(a);a.wc=0;a.dd={}},Va:(a,b)=>{3317==a?Bb=b:3314==a&&(Cb=b);O.pixelStorei(a,b)},I:(a,b)=>O.polygonOffset(a,b),sb:a=>O.readBuffer(a),Ia:(a,b,c,d,e)=>O.renderbufferStorageMultisample(a,b,c,d,e),C:(a,b,c)=>{O.samplerParameterf(S[a],b,c)},f:(a,b,c)=>{O.samplerParameteri(S[a],b,c)},s:(a,b,c,d)=>O.scissor(a,b,c,d),Qb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=v[c+4*h>>2])?B(t,f,d?v[d+4*h>>2]:void 0):"";e+=f}O.shaderSource(R[a],e)},Sa:(a,b,c)=>O.stencilFunc(a,b,c),oa:(a,
b,c,d)=>O.stencilFuncSeparate(a,b,c,d),v:a=>O.stencilMask(a),Ra:(a,b,c)=>O.stencilOp(a,b,c),na:(a,b,c,d)=>O.stencilOpSeparate(a,b,c,d),Ca:(a,b,c,d,e,h,f,l,n)=>{if(2<=V.version){if(O.uc){O.texImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var q=Ub(l);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);O.texImage2D(a,b,c,d,e,h,f,l,q,n);return}}if(n){q=Ub(l);var w=e*((Cb||d)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*q.BYTES_PER_ELEMENT+Bb-1&-Bb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),
n+w>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;O.texImage2D(a,b,c,d,e,h,f,l,n)},Aa:(a,b,c,d,e,h,f,l,n,q)=>{if(O.uc)O.texImage3D(a,b,c,d,e,h,f,l,n,q);else if(q){var w=Ub(n);O.texImage3D(a,b,c,d,e,h,f,l,n,w,q>>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else O.texImage3D(a,b,c,d,e,h,f,l,n,null)},Ga:(a,b,c)=>O.texParameteri(a,b,c),Fa:(a,b,c,d,e)=>O.texStorage2D(a,b,c,d,e),Ea:(a,b,c,d,e,h)=>O.texStorage3D(a,b,c,d,e,h),Fb:(a,b,c)=>{if(2<=V.version)b&&O.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=
X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);O.uniform1fv(W(a),d)}},va:(a,b)=>{O.uniform1i(W(a),b)},Bb:(a,b,c)=>{if(2<=V.version)b&&O.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=Vb[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);O.uniform1iv(W(a),d)}},Eb:(a,b,c)=>{if(2<=V.version)b&&O.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);O.uniform2fv(W(a),d)}},
Ab:(a,b,c)=>{if(2<=V.version)b&&O.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Vb[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);O.uniform2iv(W(a),d)}},Db:(a,b,c)=>{if(2<=V.version)b&&O.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);O.uniform3fv(W(a),d)}},zb:(a,b,c)=>{if(2<=V.version)b&&O.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=
b){b*=3;for(var d=Vb[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);O.uniform3iv(W(a),d)}},Cb:(a,b,c)=>{if(2<=V.version)b&&O.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);O.uniform4fv(W(a),d)}},yb:(a,b,c)=>{if(2<=V.version)b&&O.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Vb[b],
e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);O.uniform4iv(W(a),d)}},xb:(a,b,c,d)=>{if(2<=V.version)b&&O.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=
h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(W(a),!!c,e)}},l:a=>{a=P[a];O.useProgram(a);O.gd=a},Hb:(a,b)=>{O.vertexAttribDivisor(a,b)},Ib:(a,b,c,d,e)=>{O.vertexAttribIPointer(a,b,c,d,e)},Jb:(a,b,c,d,e,h)=>{O.vertexAttribPointer(a,b,c,!!d,e,h)},q:(a,b,c,d)=>O.viewport(a,b,c,d),eb:Ha,Ub:function(){g.Xc=a=>{0!=dc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Xc)},ab:function(){g.bd=a=>{const b=a.clipboardData.getData("text");
$b(()=>{const c=Xb(b);ec(c)})};window.addEventListener("paste",g.bd)},Ta:function(){g.Id=[];g.Yc=b=>{b.stopPropagation();b.preventDefault()};g.Zc=b=>{b.stopPropagation();b.preventDefault()};g.$c=b=>{b.stopPropagation();b.preventDefault()};g.ad=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Jd=c;fc(c.length);for(let e=0;e<c.length;e++)$b(()=>{const h=Xb(c[e].name);gc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);hc(b.clientX,b.clientY,
d)};const a=g.sc;a.addEventListener("dragenter",g.Yc,!1);a.addEventListener("dragleave",g.Zc,!1);a.addEventListener("dragover",g.$c,!1);a.addEventListener("drop",g.ad,!1)},Sb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Oa:function(a,b){0!==b&&(document.title=b?B(t,b):"");a=a?B(t,a):"";void 0!==g.canvas&&("object"===typeof g.canvas?bb[a]=g.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));g.sc=I(a);g.sc||console.warn("sokol_app.h: can't find html5_canvas_selector ",
a);g.sc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Tb:function(){window.removeEventListener("beforeunload",g.Xc)},_a:function(){window.removeEventListener("paste",g.bd)},Qa:function(){const a=g.sc;a.removeEventListener("dragenter",g.Yc);a.removeEventListener("dragleave",g.Zc);a.removeEventListener("dragover",g.$c);a.removeEventListener("drop",g.ad)},u:function(){g.sc&&g.sc.requestPointerLock&&g.sc.requestPointerLock()},ya:function(a,b){if(g.sc){if(0===
b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.sc.style.cursor=a}},Mb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(t.subarray(c,
c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Za:function(a){a=a?B(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();
document.execCommand("copy");document.body.removeChild(b)},ja:function(){return navigator.userAgent.includes("Macintosh")?1:0},ma:function(a,b){b=b?B(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;na=Z.Vb;ra();eb=Z.ic;z--;g.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;g.monitorRunDependencies?.(z);var b={a:ic};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{a(d,e);c(d.exports)})});ta??=g.locateFile?g.locateFile("shadows-sapp-ui.wasm",k):k+"shadows-sapp-ui.wasm";return a((await xa(b)).instance)})();
var ec=g.__sapp_emsc_onpaste=a=>(ec=g.__sapp_emsc_onpaste=Z.Xb)(a),dc=g.__sapp_html5_get_ask_leave_site=()=>(dc=g.__sapp_html5_get_ask_leave_site=Z.Yb)(),fc=g.__sapp_emsc_begin_drop=a=>(fc=g.__sapp_emsc_begin_drop=Z.Zb)(a),gc=g.__sapp_emsc_drop=(a,b)=>(gc=g.__sapp_emsc_drop=Z._b)(a,b),hc=g.__sapp_emsc_end_drop=(a,b,c)=>(hc=g.__sapp_emsc_end_drop=Z.$b)(a,b,c);g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,f,l)=>(g.__sapp_emsc_invoke_fetch_cb=Z.ac)(a,b,c,d,e,h,f,l);
var jc=g._main=(a,b)=>(jc=g._main=Z.bc)(a,b);g.__saudio_emsc_pull=a=>(g.__saudio_emsc_pull=Z.cc)(a);g.__sfetch_emsc_head_response=(a,b)=>(g.__sfetch_emsc_head_response=Z.dc)(a,b);g.__sfetch_emsc_get_response=(a,b,c)=>(g.__sfetch_emsc_get_response=Z.ec)(a,b,c);g.__sfetch_emsc_failed_http_status=(a,b)=>(g.__sfetch_emsc_failed_http_status=Z.fc)(a,b);g.__sfetch_emsc_failed_buffer_too_small=a=>(g.__sfetch_emsc_failed_buffer_too_small=Z.gc)(a);
var N=a=>(N=Z.hc)(a),cc=(a,b)=>(cc=Z.jc)(a,b),Zb=a=>(Zb=Z.kc)(a),Wb=a=>(Wb=Z.lc)(a),Yb=()=>(Yb=Z.mc)();function kc(a=[]){var b=jc;a.unshift(fa);var c=a.length,d=Wb(4*(c+1)),e=d;a.forEach(f=>{v[e>>2]=Xb(f);e+=4});v[e>>2]=0;try{var h=b(c,d);Ia(h)}catch(f){Ga(f)}}
function lc(a=ea){function b(){g.calledRun=!0;if(!p){Z.Wb();g.onRuntimeInitialized?.();g.noInitialRun||kc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();Aa.unshift(c)}za(Aa)}}if(0<z)A=lc;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ca();za(Ba);0<z?A=lc:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();lc();
