var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs");require("path");k=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?
"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};f.print||console.log.bind(console);var m=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);var la=f.wasmBinary,ma,p=!1,na,r,t,oa,pa,u,v,w,x,ka=a=>a.startsWith("file://");
function qa(){var a=ma.buffer;f.HEAP8=r=new Int8Array(a);f.HEAP16=oa=new Int16Array(a);f.HEAPU8=t=new Uint8Array(a);f.HEAPU16=pa=new Uint16Array(a);f.HEAP32=u=new Int32Array(a);f.HEAPU32=v=new Uint32Array(a);f.HEAPF32=w=new Float32Array(a);f.HEAPF64=x=new Float64Array(a);f.HEAP64=new BigInt64Array(a);f.HEAPU64=new BigUint64Array(a)}var z=0,A=null;function sa(a){f.onAbort?.(a);a="Aborted("+a+")";m(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!la)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==ta&&la)a=new Uint8Array(la);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!la&&"function"==typeof WebAssembly.instantiateStreaming&&!ka(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(f)},za=[],Aa=[],Ba=()=>{var a=f.preRun.shift();Aa.unshift(a)},Ca=f.noExitRuntime||!0,Da=0,B={},Ea=a=>{a instanceof xa||"unwind"==a||ha(1,a)},Fa=a=>{na=a;Ca||0<Da||(f.onExit?.(a),p=!0);ha(a,new xa(a))},Ga=a=>{na=a;Fa(a)},Ha=()=>{if(!(Ca||0<Da))try{var a=na;na=a;Fa(a)}catch(b){Ea(b)}},Ia=a=>{if(!p)try{a(),Ha()}catch(b){Ea(b)}},Pa=(a,b)=>{Ja=a;Ka=b;if(C)if(La||=!0,0==a)D=function(){setTimeout(F,Math.max(0,Ma+b-performance.now())|0)};else if(1==a)D=function(){Na(F)};
else if(2==a){if("undefined"==typeof Oa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Oa=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Oa=setImmediate;D=function(){Oa(F)}}},Ya=(a,b,c,d,e)=>{function h(){return g<Qa?(Ha(),!1):!0}C=a;Ra=d;var g=Qa;La=
!1;F=function(){if(!p)if(0<Sa.length){var l=Sa.shift();l.dd(l.Vc);if(Ta){var n=Ta,q=0==n%1?n-1:Math.floor(n);Ta=l.Xc?q:(8*n+(q+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",n=Ta??0,q=Ua.bd??0,n?n<q?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));h()&&setTimeout(F,0)}else if(h())if(Va=Va+1|0,1==Ja&&1<Ka&&0!=Va%Ka)D();else{0==Ja&&(Ma=performance.now());a:if(!p){for(l of Wa)if(!1===l())break a;Ia(a);for(n of Xa)n()}h()&&D()}};e||(0<b?Pa(0,1E3/b):
Pa(1,1),D());if(c)throw"unwind";},La=!1,D=null,Qa=0,C=null,Ra=0,Ja=0,Ka=0,Va=0,Sa=[],Wa=[],Xa=[];function Za(){D=null;Qa++}var G=0;function Na(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===G)G=b+1E3/60;else for(;b+2>=G;)G+=1E3/60;setTimeout(a,Math.max(G-b,0))}}var Ua={},Ma,F,Oa,Ta;function $a(a){var b=H.Vb[a];b.target.removeEventListener(b.Ub,b.zc,b.Wb);H.Vb.splice(a,1)}
function ab(){if(navigator.userActivation?navigator.userActivation.isActive:H.lc&&H.Mc.jc){var a=H.Zb;H.Zb=[];for(var b of a)b.oc(...b.vc)}}function I(a){if(!a.target)return-4;if(a.Xb)a.zc=function(c){++H.lc;H.Mc=a;ab();a.Yb(c);ab();--H.lc},a.target.addEventListener(a.Ub,a.zc,a.Wb),H.Vb.push(a);else for(var b=0;b<H.Vb.length;++b)H.Vb[b].target==a.target&&H.Vb[b].Ub==a.Ub&&$a(b--);return 0}function bb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var H={Wc:0,ed:0,mc:0,hc:0,sc:0,qc:0,kc:0,$c:0,kd:0,Zc:0,cd:0,nc:0,td:0,pc:0,hd(a,b,c){r.set(r.subarray(b,b+c),a)},md(){for(;H.Vb.length;)$a(H.Vb.length-1);H.Zb=[]},lc:0,Zb:[],Yc(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var l in h)if(h[l]!=g[l])return!1;return!0}for(var e of H.Zb)if(e.oc==a&&d(e.vc,c))return;H.Zb.push({oc:a,Dc:b,vc:c});H.Zb.sort((h,g)=>h.Dc<g.Dc)},od(a){H.Zb=H.Zb.filter(b=>b.oc!=a)},Vb:[],nd:(a,b)=>{for(var c=0;c<H.Vb.length;++c)H.Vb[c].target!=a||b&&b!=H.Vb[c].Ub||
$a(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},cb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,J=(a=0,b=NaN)=>{var c=t,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&cb)return cb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=
65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},db=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?J(a):"":a;return db[a]||("undefined"!=typeof document?document.querySelector(a):null)},eb=a=>0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},fb=[],gb,L=a=>{var b=fb[a];b||(a>=fb.length&&(fb.length=a+1),fb[a]=b=gb.get(a));return b},M=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<
a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var l=a.charCodeAt(++h);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},hb=(a,b,c,d,e,h)=>{H.kc||(H.kc=N(256));a={target:K(a),Ub:h,Xb:d,Yb:(g=event)=>{var l=g.target.id?g.target.id:"",n=H.kc;M(bb(g.target),n+0,128);
M(l,n+128,128);L(d)(e,n,b)&&g.preventDefault()},Wb:c};return I(a)},ib=(a,b,c,d,e,h)=>{H.mc||(H.mc=N(160));a={target:K(a),Ub:h,Xb:d,Yb:g=>{var l=H.mc;x[l>>3]=g.timeStamp;var n=l>>2;u[n+2]=g.location;r[l+12]=g.ctrlKey;r[l+13]=g.shiftKey;r[l+14]=g.altKey;r[l+15]=g.metaKey;r[l+16]=g.repeat;u[n+5]=g.charCode;u[n+6]=g.keyCode;u[n+7]=g.which;M(g.key||"",l+32,32);M(g.code||"",l+64,32);M(g.char||"",l+96,32);M(g.locale||"",l+128,32);L(d)(e,l,b)&&g.preventDefault()},Wb:c};return I(a)},jb=(a,b,c)=>{x[a>>3]=b.timeStamp;
var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=eb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,h)=>{H.hc||(H.hc=N(64));a=K(a);return I({target:a,jc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Ub:h,Xb:d,Yb:(g=event)=>{jb(H.hc,g,a);L(d)(e,H.hc,b)&&g.preventDefault()},Wb:c})},kb=(a,b,
c,d,e)=>{H.nc||(H.nc=N(257));return I({target:a,Ub:e,Xb:d,Yb:(h=event)=>{var g=H.nc,l=document.pointerLockElement||document.bc||document.uc||document.tc;r[g]=!!l;var n=l?.id||"";M(bb(l),g+1,128);M(n,g+129,128);L(d)(20,g,b)&&h.preventDefault()},Wb:c})},lb=(a,b,c,d,e)=>I({target:a,Ub:e,Xb:d,Yb:(h=event)=>{L(d)(38,0,b)&&h.preventDefault()},Wb:c}),mb=(a,b,c,d)=>{H.qc||(H.qc=N(36));a=K(a);return I({target:a,Ub:"resize",Xb:d,Yb:(e=event)=>{if(e.target==a){var h=document.body;if(h){var g=H.qc;u[g>>2]=0;
u[g+4>>2]=h.clientWidth;u[g+8>>2]=h.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;L(d)(10,g,b)&&e.preventDefault()}}},Wb:c})},nb=(a,b,c,d,e,h)=>{H.pc||(H.pc=N(1552));a=K(a);return I({target:a,jc:"touchstart"==h||"touchend"==h,Ub:h,Xb:d,Yb:g=>{var l={},n=g.touches;for(var q of n)q.Ac=q.Cc=0,l[q.identifier]=q;for(var y of g.changedTouches)y.Ac=1,l[y.identifier]=y;for(var ra of g.targetTouches)l[ra.identifier].Cc=
1;n=H.pc;x[n>>3]=g.timeStamp;r[n+12]=g.ctrlKey;r[n+13]=g.shiftKey;r[n+14]=g.altKey;r[n+15]=g.metaKey;q=n+16;y=eb(a);ra=0;for(let E of Object.values(l))if(l=q>>2,u[l]=E.identifier,u[l+1]=E.screenX,u[l+2]=E.screenY,u[l+3]=E.clientX,u[l+4]=E.clientY,u[l+5]=E.pageX,u[l+6]=E.pageY,r[q+28]=E.Ac,r[q+29]=E.Cc,u[l+8]=E.clientX-(y.left|0),u[l+9]=E.clientY-(y.top|0),q+=48,31<++ra)break;u[n+8>>2]=ra;L(d)(e,n,b)&&g.preventDefault()},Wb:c})},P,ob=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=
(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,d,e,h,g))},pb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},qb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,
d)=>b.drawBuffersWEBGL(c,d))},rb=a=>{a.ad=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},sb=a=>{a.gd=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},tb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},ub=1,Q=[],R=[],vb=[],wb=[],xb=[],S=[],yb=[],zb=[],T=[],Ab={},Bb=4,Cb=0,Db=a=>{for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b},Eb=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=P[c](),g=h&&Db(d);h?(h.name=g,d[g]=h):U||=1282;u[b+4*e>>2]=g}},Gb=(a,b)=>{a.bc||(a.bc=a.getContext,a.getContext=function(d,e){e=a.bc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Bc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?Fb(c,b):0},Fb=(a,b)=>{var c=Db(zb),d={handle:c,attributes:b,version:b.Bc,ic:a};a.canvas&&(a.canvas.Uc=d);zb[c]=d;("undefined"==typeof b.yc||b.yc)&&Hb(d);return c},Hb=a=>{a||=V;if(!a.Rc){a.Rc=!0;var b=a.ic;b.Sc=b.getExtension("WEBGL_multi_draw");b.Qc=b.getExtension("EXT_polygon_offset_clamp");b.Pc=b.getExtension("EXT_clip_control");b.Tc=b.getExtension("WEBGL_polygon_mode");ob(b);pb(b);qb(b);rb(b);sb(b);2<=a.version&&(b.xc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||
!b.xc)b.xc=b.getExtension("EXT_disjoint_timer_query");tb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},U,V,Ib=(a,b,c,d,e,h)=>{a={target:K(a),Ub:h,Xb:d,Yb:(g=event)=>{L(d)(e,0,b)&&g.preventDefault()},Wb:c};I(a)},Jb=(a,b,c,d)=>{H.sc||(H.sc=N(96));return I({target:a,jc:!0,Ub:"wheel",Xb:d,Yb:(e=event)=>{var h=H.sc;jb(h,e,a);x[h+64>>3]=e.deltaX;x[h+72>>3]=e.deltaY;x[h+80>>3]=e.deltaZ;u[h+88>>2]=e.deltaMode;L(d)(9,h,b)&&e.preventDefault()},Wb:c})},Kb=["default","low-power",
"high-performance"],Lb=()=>{var a=tb(P);return a=a.concat(a.map(b=>"GL_"+b))},Mb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=Lb().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=P.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=
1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);
return}}break;default:U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else U||=1281},Nb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ob=a=>{var b=Nb(a)+1,c=N(b);c&&M(a,c,b);return c},Pb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Qb=[],Rb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?oa:4==a?u:6==a?w:5==a||28922==a||28520==a||30779==a||30782==
a?v:pa},W=a=>{var b=P.Nc;if(b){var c=b.cc[a];"number"==typeof c&&(b.cc[a]=c=P.getUniformLocation(b,b.Kc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],Sb=[],Ub=a=>{var b=Nb(a)+1,c=Tb(b);M(a,c,b);return c},Xb=a=>{var b=Vb();a();Wb(b)};f.requestAnimationFrame=Na;f.pauseMainLoop=Za;f.resumeMainLoop=function(){Qa++;var a=Ja,b=Ka,c=C;C=null;Ya(c,0,!1,Ra,!0);Pa(a,b);D()};f.preMainLoop&&Wa.push(f.preMainLoop);f.postMainLoop&&Xa.push(f.postMainLoop);for(var Y=0;32>Y;++Y)Qb.push(Array(Y));var Yb=new Float32Array(288);
for(Y=0;288>=Y;++Y)X[Y]=Yb.subarray(0,Y);var Zb=new Int32Array(288);for(Y=0;288>=Y;++Y)Sb[Y]=Zb.subarray(0,Y);
var fc={_a:()=>sa(""),Xa:()=>{Ca=!1;Da=0},Ya:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];Ia(()=>$b(a,performance.now()))},b);B[a]={id:c,sd:b};return 0},Ma:()=>{Za();C=null},$:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ba:(a,b,c)=>{a=K(a);if(!a)return-4;a=eb(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},Na:()=>performance.now(),Ua:(a,b)=>{function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Za:a=>{var b=
t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ma.buffer.byteLength+65535)/65536|0;try{ma.grow(d);qa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},J:(a,b,c,d)=>hb(a,b,c,d,12,"blur"),_:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},K:(a,b,c,d)=>hb(a,b,c,d,13,"focus"),T:(a,b,c,d)=>ib(a,b,c,d,2,"keydown"),R:(a,b,c,d)=>ib(a,b,c,d,1,"keypress"),S:(a,
b,c,d)=>ib(a,b,c,d,3,"keyup"),Va:(a,b,c)=>{a=L(a);Ya(a,b,c)},Z:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),W:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),V:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),X:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),Y:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),M:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.bc||document.body.uc||document.body.tc))return-1;a=K(a);if(!a)return-4;kb(a,b,c,d,"mozpointerlockchange");kb(a,b,c,d,"webkitpointerlockchange");kb(a,b,c,d,
"mspointerlockchange");return kb(a,b,c,d,"pointerlockchange")},L:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.bc||document.body.uc||document.body.tc))return-1;a=K(a);if(!a)return-4;lb(a,b,c,d,"mozpointerlockerror");lb(a,b,c,d,"webkitpointerlockerror");lb(a,b,c,d,"mspointerlockerror");return lb(a,b,c,d,"pointerlockerror")},aa:(a,b,c,d)=>mb(a,b,c,d),N:(a,b,c,d)=>nb(a,b,c,d,25,"touchcancel"),O:(a,b,c,d)=>nb(a,b,c,d,23,"touchend"),P:(a,b,c,d)=>nb(a,b,c,d,24,"touchmove"),
Q:(a,b,c,d)=>nb(a,b,c,d,22,"touchstart"),I:(a,b,c,d)=>{Ib(a,b,c,d,31,"webglcontextlost");return 0},H:(a,b,c,d)=>{Ib(a,b,c,d,32,"webglcontextrestored");return 0},U:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?Jb(a,b,c,d):-1:-4,Ta:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Kb[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Bc:u[c+4],jd:u[c+5],yc:r[b+24],Oc:r[b+25],ld:u[c+7],pd:r[b+
32]};a=K(a);return!a||b.Oc?0:Gb(a,b)},Qa:(a,b)=>{a=zb[a];b=b?J(b):"";b.startsWith("GL_")&&(b=b.slice(3));"ANGLE_instanced_arrays"==b&&ob(P);"OES_vertex_array_object"==b&&pb(P);"WEBGL_draw_buffers"==b&&qb(P);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&rb(P);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&sb(P);"WEBGL_multi_draw"==b&&(P.Sc=P.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(P.Qc=P.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&(P.Pc=
P.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(P.Tc=P.getExtension("WEBGL_polygon_mode"));return!!a.ic.getExtension(b)},Sa:a=>{V=zb[a];f.ctx=P=V?.ic;return!a||P?0:-5},j:a=>P.activeTexture(a),v:(a,b)=>{P.attachShader(R[a],S[b])},b:(a,b)=>{35051==a?P.wc=b:35052==a&&(P.ac=b);P.bindBuffer(a,Q[b])},a:(a,b,c)=>{P.bindBufferBase(a,b,Q[c])},m:(a,b)=>{P.bindFramebuffer(a,vb[b])},i:(a,b)=>{P.bindSampler(a,T[b])},c:(a,b)=>{P.bindTexture(a,xb[b])},G:a=>{P.bindVertexArray(yb[a])},C:(a,b,c,d)=>P.blendColor(a,
b,c,d),D:(a,b)=>P.blendEquationSeparate(a,b),E:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),ab:(a,b,c,d,e,h,g,l,n,q)=>P.blitFramebuffer(a,b,c,d,e,h,g,l,n,q),ya:(a,b,c,d)=>{2<=V.version?c&&b?P.bufferData(a,t,d,c,b):P.bufferData(a,b,d):P.bufferData(a,c?t.subarray(c,c+b):b,d)},x:(a,b,c,d)=>{2<=V.version?c&&P.bufferSubData(a,b,t,d,c):P.bufferSubData(a,b,t.subarray(d,d+c))},tb:(a,b,c,d)=>P.clearBufferfi(a,b,c,d),ea:(a,b,c)=>{P.clearBufferfv(a,b,w,c>>2)},sb:(a,b,c)=>{P.clearBufferiv(a,b,u,c>>2)},k:(a,b,c,d)=>
{P.colorMask(!!a,!!b,!!c,!!d)},ga:a=>{P.compileShader(S[a])},sa:(a,b,c,d,e,h,g,l)=>{2<=V.version?P.ac||!g?P.compressedTexImage2D(a,b,c,d,e,h,g,l):P.compressedTexImage2D(a,b,c,d,e,h,t,l,g):P.compressedTexImage2D(a,b,c,d,e,h,t.subarray(l,l+g))},qa:(a,b,c,d,e,h,g,l,n)=>{P.ac?P.compressedTexImage3D(a,b,c,d,e,h,g,l,n):P.compressedTexImage3D(a,b,c,d,e,h,g,t,n,l)},na:()=>{var a=Db(R),b=P.createProgram();b.name=a;b.fc=b.dc=b.ec=0;b.rc=1;R[a]=b;return a},ia:a=>{var b=Db(S);S[b]=P.createShader(a);return b},
z:a=>P.cullFace(a),Ea:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(P.deleteBuffer(e),e.name=0,Q[d]=null,d==P.wc&&(P.wc=0),d==P.ac&&(P.ac=0))}},h:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=vb[d];e&&(P.deleteFramebuffer(e),e.name=0,vb[d]=null)}},y:a=>{if(a){var b=R[a];b?(P.deleteProgram(b),b.name=0,R[a]=null):U||=1281}},Ca:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=wb[d];e&&(P.deleteRenderbuffer(e),e.name=0,wb[d]=null)}},Ba:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=T[d];
e&&(P.deleteSampler(e),e.name=0,T[d]=null)}},n:a=>{if(a){var b=S[a];b?(P.deleteShader(b),S[a]=null):U||=1281}},Da:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=xb[d];e&&(P.deleteTexture(e),e.name=0,xb[d]=null)}},Aa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];P.deleteVertexArray(yb[d]);yb[d]=null}},r:a=>P.depthFunc(a),q:a=>{P.depthMask(!!a)},e:a=>P.disable(a),F:a=>{P.disableVertexAttribArray(a)},cb:(a,b,c)=>{P.drawArrays(a,b,c)},db:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},eb:(a,b,c,d)=>{P.drawElements(a,
b,c,d)},fb:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},g:a=>P.enable(a),pb:a=>{P.enableVertexAttribArray(a)},A:a=>P.frontFace(a),za:(a,b)=>{Eb(a,b,"createBuffer",Q)},oa:(a,b)=>{Eb(a,b,"createSampler",T)},xa:(a,b)=>{Eb(a,b,"createTexture",xb)},La:(a,b)=>{Eb(a,b,"createVertexArray",yb)},wb:(a,b)=>P.getAttribLocation(R[a],b?J(b):""),d:(a,b)=>Mb(a,b),ka:(a,b,c,d)=>{a=P.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},u:(a,b,c)=>{if(c)if(a>=ub)U||=1281;
else if(a=R[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.fc){var d=P.getProgramParameter(a,35718);for(b=0;b<d;++b)a.fc=Math.max(a.fc,P.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.fc}else if(35722==b){if(!a.dc)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.dc=Math.max(a.dc,P.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.dc}else if(35381==b){if(!a.ec)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.ec=Math.max(a.ec,P.getActiveUniformBlockName(a,
b).length+1);u[c>>2]=a.ec}else u[c>>2]=P.getProgramParameter(a,b);else U||=1281},xb:(a,b,c,d)=>{a=P.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},s:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(S[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=P.getShaderParameter(S[a],b):U||=1281},Ja:(a,b)=>{if(2>V.version)return U||=1282,0;var c=Ab[a];if(c)return 0>b||b>=c.length?(U||=1281,0):
c[b];switch(a){case 7939:return c=Lb().map(Ob),c=Ab[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},t:(a,b)=>{b=b?J(b):"";if(a=R[a]){var c=a,d=c.cc,e=c.Lc,h;if(!d){c.cc=d={};c.Kc={};var g=P.getProgramParameter(c,35718);for(h=0;h<g;++h){var l=P.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Pb(n);q=0<q?n.slice(0,q):n;var y=c.rc;c.rc+=l;e[q]=[l,y];for(n=0;n<l;++n)d[y]=n,c.Kc[y++]=q}}c=a.cc;d=0;e=b;h=Pb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Lc[e])&&d<e[0]&&
(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else U||=1281;return-1},$a:(a,b,c)=>{for(var d=Qb[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];P.invalidateFramebuffer(a,d)},la:a=>{a=R[a];P.linkProgram(a);a.cc=0;a.Lc={}},Ka:(a,b)=>{3317==a?Bb=b:3314==a&&(Cb=b);P.pixelStorei(a,b)},B:(a,b)=>P.polygonOffset(a,b),bb:a=>P.readBuffer(a),w:(a,b,c)=>{P.samplerParameterf(T[a],b,c)},f:(a,b,c)=>{P.samplerParameteri(T[a],b,c)},ub:(a,b,c,d)=>P.scissor(a,b,c,d),ha:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var g=(g=v[c+4*
h>>2])?J(g,d?v[d+4*h>>2]:void 0):"";e+=g}P.shaderSource(S[a],e)},Ha:(a,b,c)=>P.stencilFunc(a,b,c),da:(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),p:a=>P.stencilMask(a),Ga:(a,b,c)=>P.stencilOp(a,b,c),ca:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),ra:(a,b,c,d,e,h,g,l,n)=>{if(2<=V.version){if(P.ac){P.texImage2D(a,b,c,d,e,h,g,l,n);return}if(n){var q=Rb(l);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);P.texImage2D(a,b,c,d,e,h,g,l,q,n);return}}if(n){q=Rb(l);var y=e*((Cb||d)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,
29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT+Bb-1&-Bb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+y>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;P.texImage2D(a,b,c,d,e,h,g,l,n)},pa:(a,b,c,d,e,h,g,l,n,q)=>{if(P.ac)P.texImage3D(a,b,c,d,e,h,g,l,n,q);else if(q){var y=Rb(n);P.texImage3D(a,b,c,d,e,h,g,l,n,y,q>>>31-Math.clz32(y.BYTES_PER_ELEMENT))}else P.texImage3D(a,b,c,d,e,h,g,l,n,null)},wa:(a,b,c)=>P.texParameteri(a,b,c),va:(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),ta:(a,b,c,d,e,h)=>
P.texStorage3D(a,b,c,d,e,h),ob:(a,b,c)=>{if(2<=V.version)b&&P.uniform1fv(W(a),w,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);P.uniform1fv(W(a),d)}},ja:(a,b)=>{P.uniform1i(W(a),b)},kb:(a,b,c)=>{if(2<=V.version)b&&P.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=Sb[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);P.uniform1iv(W(a),d)}},nb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2fv(W(a),w,c>>2,2*b);else{if(144>=b){b*=2;for(var d=
X[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);P.uniform2fv(W(a),d)}},jb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Sb[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);P.uniform2iv(W(a),d)}},mb:(a,b,c)=>{if(2<=V.version)b&&P.uniform3fv(W(a),w,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=
w.subarray(c>>2,c+12*b>>2);P.uniform3fv(W(a),d)}},ib:(a,b,c)=>{if(2<=V.version)b&&P.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Sb[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);P.uniform3iv(W(a),d)}},lb:(a,b,c)=>{if(2<=V.version)b&&P.uniform4fv(W(a),w,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=w;c>>=2;b*=4;for(var h=0;h<b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>
2);P.uniform4fv(W(a),d)}},hb:(a,b,c)=>{if(2<=V.version)b&&P.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Sb[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);P.uniform4iv(W(a),d)}},gb:(a,b,c,d)=>{if(2<=V.version)b&&P.uniformMatrix4fv(W(a),!!c,w,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+
5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(W(a),!!c,e)}},l:a=>{a=R[a];P.useProgram(a);P.Nc=a},qb:(a,b)=>{P.vertexAttribDivisor(a,b)},rb:(a,b,c,d,e,h)=>{P.vertexAttribPointer(a,b,c,!!d,e,h)},vb:(a,b,c,d)=>P.viewport(a,b,c,d),Wa:Fa,zb:function(){f.Ec=a=>{0!=ac()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",
f.Ec)},Ra:function(){f.Jc=a=>{const b=a.clipboardData.getData("text");Xb(()=>{const c=Ub(b);bc(c)})};window.addEventListener("paste",f.Jc)},Oa:function(){f.qd=[];f.Fc=b=>{b.stopPropagation();b.preventDefault()};f.Gc=b=>{b.stopPropagation();b.preventDefault()};f.Hc=b=>{b.stopPropagation();b.preventDefault()};f.Ic=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.rd=c;cc(c.length);for(let e=0;e<c.length;e++)Xb(()=>{const h=Ub(c[e].name);dc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&
(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);ec(b.clientX,b.clientY,d)};const a=f.$b;a.addEventListener("dragenter",f.Fc,!1);a.addEventListener("dragleave",f.Gc,!1);a.addEventListener("dragover",f.Hc,!1);a.addEventListener("drop",f.Ic,!1)},ua:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Fa:function(a,b){0!==b&&(document.title=b?J(b):"");a=a?J(a):"";void 0!==f.canvas&&("object"===typeof f.canvas?db[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
f.$b=K(a);f.$b||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.$b.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},yb:function(){window.removeEventListener("beforeunload",f.Ec)},Pa:function(){window.removeEventListener("paste",f.Jc)},Ia:function(){const a=f.$b;a.removeEventListener("dragenter",f.Fc);a.removeEventListener("dragleave",f.Gc);a.removeEventListener("dragover",f.Hc);a.removeEventListener("drop",f.Ic)},o:function(){f.$b&&
f.$b.requestPointerLock&&f.$b.requestPointerLock()},ma:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(t.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},fa:function(a,b){b=b?J(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},
Z;(async function(){function a(c){Z=c.exports;ma=Z.Ab;qa();gb=Z.Qb;z--;f.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;f.monitorRunDependencies?.(z);var b={a:fc};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{a(d,e);c(d.exports)})});ta??=f.locateFile?f.locateFile("uniformtypes-sapp.wasm",k):k+"uniformtypes-sapp.wasm";return a((await wa(b)).instance)})();
var N=a=>(N=Z.Cb)(a),bc=f.__sapp_emsc_onpaste=a=>(bc=f.__sapp_emsc_onpaste=Z.Db)(a),ac=f.__sapp_html5_get_ask_leave_site=()=>(ac=f.__sapp_html5_get_ask_leave_site=Z.Eb)(),cc=f.__sapp_emsc_begin_drop=a=>(cc=f.__sapp_emsc_begin_drop=Z.Fb)(a),dc=f.__sapp_emsc_drop=(a,b)=>(dc=f.__sapp_emsc_drop=Z.Gb)(a,b),ec=f.__sapp_emsc_end_drop=(a,b,c)=>(ec=f.__sapp_emsc_end_drop=Z.Hb)(a,b,c);f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,g,l)=>(f.__sapp_emsc_invoke_fetch_cb=Z.Ib)(a,b,c,d,e,h,g,l);
var gc=f._main=(a,b)=>(gc=f._main=Z.Jb)(a,b);f.__saudio_emsc_pull=a=>(f.__saudio_emsc_pull=Z.Kb)(a);f.__sfetch_emsc_head_response=(a,b)=>(f.__sfetch_emsc_head_response=Z.Lb)(a,b);f.__sfetch_emsc_get_response=(a,b,c)=>(f.__sfetch_emsc_get_response=Z.Mb)(a,b,c);f.__sfetch_emsc_failed_http_status=(a,b)=>(f.__sfetch_emsc_failed_http_status=Z.Nb)(a,b);f.__sfetch_emsc_failed_buffer_too_small=a=>(f.__sfetch_emsc_failed_buffer_too_small=Z.Ob)(a);
var $b=(a,b)=>($b=Z.Pb)(a,b),Wb=a=>(Wb=Z.Rb)(a),Tb=a=>(Tb=Z.Sb)(a),Vb=()=>(Vb=Z.Tb)();function hc(a=[]){var b=gc;a.unshift(fa);var c=a.length,d=Tb(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=Ub(g);e+=4});v[e>>2]=0;try{var h=b(c,d);Ga(h)}catch(g){Ea(g)}}
function ic(a=ea){function b(){f.calledRun=!0;if(!p){Z.Bb();f.onRuntimeInitialized?.();f.noInitialRun||hc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();za.unshift(c)}ya(za)}}if(0<z)A=ic;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ba();ya(Aa);0<z?A=ic:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();ic();
