var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",h=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,t,u;
if(ea){var fs=require("fs"),ha=require("path");q=l?ha.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};u=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};t=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,k)=>{e?c(e):b(d?k.buffer:k)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&
(module.exports=g);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof v||a.context instanceof v))throw a;});h=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(u=
a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),t=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};g.print||console.log.bind(console);var x=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(h=g.quit);
var y;g.wasmBinary&&(y=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&ia("no native wasm support detected");var ja,ka=!1,la,z,ma,na,A,oa,B,C;function pa(){var a=ja.buffer;g.HEAP8=la=new Int8Array(a);g.HEAP16=ma=new Int16Array(a);g.HEAP32=A=new Int32Array(a);g.HEAPU8=z=new Uint8Array(a);g.HEAPU16=na=new Uint16Array(a);g.HEAPU32=oa=new Uint32Array(a);g.HEAPF32=B=new Float32Array(a);g.HEAPF64=C=new Float64Array(a)}var qa,ra=[],sa=[],ta=[],ua=[],va=[];
function wa(){var a=g.preRun.shift();ra.unshift(a)}var D=0,xa=null,E=null;function ia(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";x(a);ka=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function ya(a){return a.startsWith("data:application/octet-stream;base64,")}var F;F="uvwrap-sapp.wasm";if(!ya(F)){var za=F;F=g.locateFile?g.locateFile(za,q):q+za}
function Aa(a){if(a==F&&y)return new Uint8Array(y);if(u)return u(a);throw"both async and sync fetching of the wasm failed";}function Ba(a){if(!y&&(da||l)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Aa(a));if(t)return new Promise((b,c)=>{t(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Aa(a))}
function Ca(a,b,c){return Ba(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{x("failed to asynchronously prepare wasm: "+d);ia(d)})}
function Da(a,b){var c=F;y||"function"!=typeof WebAssembly.instantiateStreaming||ya(c)||c.startsWith("file://")||ea||"function"!=typeof fetch?Ca(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){x("wasm streaming compile failed: "+e);x("falling back to ArrayBuffer instantiation");return Ca(c,a,b)}))}function v(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ea=a=>{for(;0<a.length;)a.shift()(g)},Ha=a=>{var b=Fa();a();Ga(b)},Ia=0;function Ja(){for(var a=G.length-1;0<=a;--a)Ka(a);G=[];La=[]}var La=[];function Ma(){if(navigator.userActivation?navigator.userActivation.isActive:Ia&&Na.Xb)for(var a=0;a<La.length;++a){var b=La[a];La.splice(a,1);--a;b.Ic.apply(null,b.yc)}}var G=[];function Ka(a){var b=G[a];b.target.removeEventListener(b.Pb,b.uc,b.Qb);G.splice(a,1)}
function H(a){function b(d){++Ia;Na=a;Ma();a.Sb(d);Ma();--Ia}if(!a.target)return-4;if(a.Rb)a.uc=b,a.target.addEventListener(a.Pb,b,a.Qb),G.push(a),Oa||(ua.push(Ja),Oa=!0);else for(var c=0;c<G.length;++c)G[c].target==a.target&&G[c].Pb==a.Pb&&Ka(c--);return 0}function Pa(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Oa,Na,Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,I=(a,b)=>{var c=z,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&Xa)return Xa.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var k=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|k<<6|f:(e&7)<<18|k<<12|f<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ya=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];function J(a){a=2<a?a?I(a):"":a;return Ya[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function Za(a){return 0>Ya.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
var $a=[],K=a=>{var b=$a[a];b||(a>=$a.length&&($a.length=a+1),$a[a]=b=qa.get(a));return b},L=(a,b,c)=>{var d=z;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);if(55296<=f&&57343>=f){var m=a.charCodeAt(++k);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=
0;return b-e};function ab(a,b,c,d,e,k){Qa||(Qa=M(256));a={target:J(a),Pb:k,Rb:d,Sb:function(f=event){var m=f.target.id?f.target.id:"",n=Qa;L(Pa(f.target),n+0,128);L(m,n+128,128);K(d)(e,n,b)&&f.preventDefault()},Qb:c};return H(a)}
function bb(a,b,c,d,e,k){Ra||(Ra=M(176));a={target:J(a),Xb:!0,Pb:k,Rb:d,Sb:function(f){var m=Ra;C[m>>3]=f.timeStamp;var n=m>>2;A[n+2]=f.location;A[n+3]=f.ctrlKey;A[n+4]=f.shiftKey;A[n+5]=f.altKey;A[n+6]=f.metaKey;A[n+7]=f.repeat;A[n+8]=f.charCode;A[n+9]=f.keyCode;A[n+10]=f.which;L(f.key||"",m+44,32);L(f.code||"",m+76,32);L(f.char||"",m+108,32);L(f.locale||"",m+140,32);K(d)(e,m,b)&&f.preventDefault()},Qb:c};return H(a)}
function cb(a,b,c){C[a>>3]=b.timeStamp;a>>=2;A[a+2]=b.screenX;A[a+3]=b.screenY;A[a+4]=b.clientX;A[a+5]=b.clientY;A[a+6]=b.ctrlKey;A[a+7]=b.shiftKey;A[a+8]=b.altKey;A[a+9]=b.metaKey;ma[2*a+20]=b.button;ma[2*a+21]=b.buttons;A[a+11]=b.movementX;A[a+12]=b.movementY;c=Za(c);A[a+13]=b.clientX-c.left;A[a+14]=b.clientY-c.top}
function O(a,b,c,d,e,k){Sa||(Sa=M(72));a=J(a);return H({target:a,Xb:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Pb:k,Rb:d,Sb:function(f=event){cb(Sa,f,a);K(d)(e,Sa,b)&&f.preventDefault()},Qb:c})}function db(a,b,c,d,e){Ta||(Ta=M(260));return H({target:a,Pb:e,Rb:d,Sb:function(k=event){var f=Ta,m=document.pointerLockElement||document.Ub||document.dc||document.cc;A[f>>2]=!!m;var n=m&&m.id?m.id:"";L(Pa(m),f+4,128);L(n,f+132,128);K(d)(20,f,b)&&k.preventDefault()},Qb:c})}
function eb(a,b,c,d,e){return H({target:a,Pb:e,Rb:d,Sb:function(k=event){K(d)(38,0,b)&&k.preventDefault()},Qb:c})}
function fb(a,b,c,d){Ua||(Ua=M(36));a=J(a);return H({target:a,Pb:"resize",Rb:d,Sb:function(e=event){if(e.target==a){var k=document.body;if(k){var f=Ua;A[f>>2]=e.detail;A[f+4>>2]=k.clientWidth;A[f+8>>2]=k.clientHeight;A[f+12>>2]=innerWidth;A[f+16>>2]=innerHeight;A[f+20>>2]=outerWidth;A[f+24>>2]=outerHeight;A[f+28>>2]=pageXOffset;A[f+32>>2]=pageYOffset;K(d)(10,f,b)&&e.preventDefault()}}},Qb:c})}
function gb(a,b,c,d,e,k){Va||(Va=M(1696));a=J(a);return H({target:a,Xb:"touchstart"==k||"touchend"==k,Pb:k,Rb:d,Sb:function(f){for(var m,n={},p=f.touches,w=0;w<p.length;++w)m=p[w],m.ic=m.kc=0,n[m.identifier]=m;for(w=0;w<f.changedTouches.length;++w)m=f.changedTouches[w],m.ic=1,n[m.identifier]=m;for(w=0;w<f.targetTouches.length;++w)n[f.targetTouches[w].identifier].kc=1;p=Va;C[p>>3]=f.timeStamp;var r=p>>2;A[r+3]=f.ctrlKey;A[r+4]=f.shiftKey;A[r+5]=f.altKey;A[r+6]=f.metaKey;r+=7;var N=Za(a),U=0;for(w in n)if(m=
n[w],A[r]=m.identifier,A[r+1]=m.screenX,A[r+2]=m.screenY,A[r+3]=m.clientX,A[r+4]=m.clientY,A[r+5]=m.pageX,A[r+6]=m.pageY,A[r+7]=m.ic,A[r+8]=m.kc,A[r+9]=m.clientX-N.left,A[r+10]=m.clientY-N.top,r+=13,31<++U)break;A[p+8>>2]=U;K(d)(e,p,b)&&f.preventDefault()},Qb:c})}
function hb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,k){b.drawArraysInstancedANGLE(c,d,e,k)},a.drawElementsInstanced=function(c,d,e,k,f){b.drawElementsInstancedANGLE(c,d,e,k,f)})}
function ib(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function jb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function kb(a){a.Ac=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function lb(a){a.Bc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function mb(a){a.Dc=a.getExtension("WEBGL_multi_draw")}var nb=1,ob=[],P=[],pb=[],qb=[],rb=[],Q=[],sb=[],tb=[],R=[],ub={},vb=4;function S(a){wb||(wb=a)}function xb(a){for(var b=nb++,c=a.length;c<b;c++)a[c]=null;return b}
function yb(a,b){a.Ub||(a.Ub=a.getContext,a.getContext=function(d,e){e=a.Ub(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.jc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?zb(c,b):0}function zb(a,b){var c=xb(tb),d={handle:c,attributes:b,version:b.jc,ac:a};a.canvas&&(a.canvas.xc=d);tb[c]=d;("undefined"==typeof b.hc||b.hc)&&Ab(d);return c}
function Ab(a){a||(a=T);if(!a.wc){a.wc=!0;var b=a.ac;hb(b);ib(b);jb(b);kb(b);lb(b);2<=a.version&&(b.fc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.fc)b.fc=b.getExtension("EXT_disjoint_timer_query");mb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var wb,T;function Bb(a,b,c,d,e,k){a={target:J(a),Pb:k,Rb:d,Sb:(f=event)=>{K(d)(e,0,b)&&f.preventDefault()},Qb:c};H(a)}
function Cb(a,b,c,d){Wa||(Wa=M(104));return H({target:a,Xb:!0,Pb:"wheel",Rb:d,Sb:function(e=event){var k=Wa;cb(k,e,a);C[k+72>>3]=e.deltaX;C[k+80>>3]=e.deltaY;C[k+88>>3]=e.deltaZ;A[k+96>>2]=e.deltaMode;K(d)(9,k,b)&&e.preventDefault()},Qb:c})}var Db=["default","low-power","high-performance"];function Eb(a,b,c,d){for(var e=0;e<a;e++){var k=V[c](),f=k&&xb(d);k?(k.name=f,d[f]=k):S(1282);A[b+4*e>>2]=f}}
function Fb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=V.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>T.version){S(1282);return}c=2*(V.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>T.version){S(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=V.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":S(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:S(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)A[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){S(1280);x("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:S(1280);x("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}A[b>>2]=c}else S(1281)}
var Gb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b};function Hb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}var Ib=[];function Jb(a){a-=5120;return 0==a?la:1==a?z:2==a?ma:4==a?A:6==a?B:5==a||28922==a||28520==a||30779==a||30782==a?oa:na}function W(a){var b=V.tc;if(b){var c=b.Wb[a];"number"==typeof c&&(b.Wb[a]=c=V.getUniformLocation(b,b.rc[a]+(0<c?"["+c+"]":"")));return c}S(1282)}
for(var X=[],Y=[],Kb=a=>{if(!noExitRuntime){if(g.onExit)g.onExit(a);ka=!0}h(a,new v(a))},Mb=a=>{var b=Gb(a)+1,c=Lb(b);L(a,c,b);return c},V,Z=0;32>Z;++Z)Ib.push(Array(Z));var Nb=new Float32Array(288);for(Z=0;288>Z;++Z)X[Z]=Nb.subarray(0,Z+1);var Ob=new Int32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Ob.subarray(0,Z+1);
var Vb={l:()=>{ia("")},ca:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},da:function(a,b,c){a=J(a);if(!a)return-4;a=Za(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},Wa:(a,b,c)=>z.copyWithin(a,b,b+c),Ua:function(a,b){function c(d){K(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Xa:a=>{var b=z.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,
d+(65536-d%65536)%65536)-ja.buffer.byteLength+65535>>>16;try{ja.grow(e);pa();var k=1;break a}catch(f){}k=void 0}if(k)return!0}return!1},M:function(a,b,c,d){return ab(a,b,c,d,12,"blur")},ba:function(a,b,c){a=J(a);if(!a)return-4;a.width=b;a.height=c;return 0},N:function(a,b,c,d){return ab(a,b,c,d,13,"focus")},W:function(a,b,c,d){return bb(a,b,c,d,2,"keydown")},U:function(a,b,c,d){return bb(a,b,c,d,1,"keypress")},V:function(a,b,c,d){return bb(a,b,c,d,3,"keyup")},aa:function(a,b,c,d){return O(a,b,c,d,
5,"mousedown")},Z:function(a,b,c,d){return O(a,b,c,d,33,"mouseenter")},Y:function(a,b,c,d){return O(a,b,c,d,34,"mouseleave")},_:function(a,b,c,d){return O(a,b,c,d,8,"mousemove")},$:function(a,b,c,d){return O(a,b,c,d,6,"mouseup")},P:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Ub||document.body.dc||document.body.cc))return-1;a=J(a);if(!a)return-4;db(a,b,c,d,"mozpointerlockchange");db(a,b,c,d,"webkitpointerlockchange");db(a,b,c,d,"mspointerlockchange");
return db(a,b,c,d,"pointerlockchange")},O:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Ub||document.body.dc||document.body.cc))return-1;a=J(a);if(!a)return-4;eb(a,b,c,d,"mozpointerlockerror");eb(a,b,c,d,"webkitpointerlockerror");eb(a,b,c,d,"mspointerlockerror");return eb(a,b,c,d,"pointerlockerror")},Va:function(a,b,c,d){return fb(a,b,c,d)},Q:function(a,b,c,d){return gb(a,b,c,d,25,"touchcancel")},R:function(a,b,c,d){return gb(a,b,c,d,23,"touchend")},S:function(a,
b,c,d){return gb(a,b,c,d,24,"touchmove")},T:function(a,b,c,d){return gb(a,b,c,d,22,"touchstart")},L:function(a,b,c,d){Bb(a,b,c,d,31,"webglcontextlost");return 0},K:function(a,b,c,d){Bb(a,b,c,d,32,"webglcontextrestored");return 0},X:function(a,b,c,d){return(a=J(a))?"undefined"!=typeof a.onwheel?Cb(a,b,c,d):-1:-4},Sa:function(a,b){b>>=2;b={alpha:!!A[b],depth:!!A[b+1],stencil:!!A[b+2],antialias:!!A[b+3],premultipliedAlpha:!!A[b+4],preserveDrawingBuffer:!!A[b+5],powerPreference:Db[A[b+6]],failIfMajorPerformanceCaveat:!!A[b+
7],jc:A[b+8],Cc:A[b+9],hc:A[b+10],vc:A[b+11],Ec:A[b+12],Fc:A[b+13]};a=J(a);return!a||b.vc?0:yb(a,b)},Qa:function(a,b){a=tb[a];b=b?I(b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&hb(V);"OES_vertex_array_object"==b&&ib(V);"WEBGL_draw_buffers"==b&&jb(V);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&kb(V);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&lb(V);"WEBGL_multi_draw"==b&&mb(V);return!!a.ac.getExtension(b)},Ta:function(a){a>>=2;for(var b=0;14>b;++b)A[a+
b]=0;A[a]=A[a+1]=A[a+3]=A[a+4]=A[a+8]=A[a+10]=1},Ra:function(a){T=tb[a];g.zc=V=T&&T.ac;return!a||V?0:-5},g:function(a){V.activeTexture(a)},z:function(a,b){V.attachShader(P[a],Q[b])},d:function(a,b){35051==a?V.ec=b:35052==a&&(V.Tb=b);V.bindBuffer(a,ob[b])},i:function(a,b){V.bindFramebuffer(a,pb[b])},h:function(a,b){V.bindSampler(a,R[b])},a:function(a,b){V.bindTexture(a,rb[b])},I:function(a){V.bindVertexArray(sb[a])},E:function(a,b,c,d){V.blendColor(a,b,c,d)},F:function(a,b){V.blendEquationSeparate(a,
b)},G:function(a,b,c,d){V.blendFuncSeparate(a,b,c,d)},Za:function(a,b,c,d,e,k,f,m,n,p){V.blitFramebuffer(a,b,c,d,e,k,f,m,n,p)},za:function(a,b,c,d){2<=T.version?c&&b?V.bufferData(a,z,d,c,b):V.bufferData(a,b,d):V.bufferData(a,c?z.subarray(c,c+b):b,d)},ya:function(a,b,c,d){2<=T.version?c&&V.bufferSubData(a,b,z,d,c):V.bufferSubData(a,b,z.subarray(d,d+c))},sb:function(a,b,c,d){V.clearBufferfi(a,b,c,d)},ha:function(a,b,c){V.clearBufferfv(a,b,B,c>>2)},rb:function(a,b,c){V.clearBufferiv(a,b,A,c>>2)},j:function(a,
b,c,d){V.colorMask(!!a,!!b,!!c,!!d)},ka:function(a){V.compileShader(Q[a])},wa:function(a,b,c,d,e,k,f,m){2<=T.version?V.Tb||!f?V.compressedTexImage2D(a,b,c,d,e,k,f,m):V.compressedTexImage2D(a,b,c,d,e,k,z,m,f):V.compressedTexImage2D(a,b,c,d,e,k,m?z.subarray(m,m+f):null)},ta:function(a,b,c,d,e,k,f,m,n){V.Tb?V.compressedTexImage3D(a,b,c,d,e,k,f,m,n):V.compressedTexImage3D(a,b,c,d,e,k,f,z,n,m)},qa:function(){var a=xb(P),b=V.createProgram();b.name=a;b.$b=b.Yb=b.Zb=0;b.bc=1;P[a]=b;return a},ma:function(a){var b=
xb(Q);Q[b]=V.createShader(a);return b},B:function(a){V.cullFace(a)},Ma:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=ob[d];e&&(V.deleteBuffer(e),e.name=0,ob[d]=null,d==V.ec&&(V.ec=0),d==V.Tb&&(V.Tb=0))}},k:function(a,b){for(var c=0;c<a;++c){var d=A[b+4*c>>2],e=pb[d];e&&(V.deleteFramebuffer(e),e.name=0,pb[d]=null)}},J:function(a){if(a){var b=P[a];b?(V.deleteProgram(b),b.name=0,P[a]=null):S(1281)}},Ka:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=qb[d];e&&(V.deleteRenderbuffer(e),
e.name=0,qb[d]=null)}},Ia:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=R[d];e&&(V.deleteSampler(e),e.name=0,R[d]=null)}},r:function(a){if(a){var b=Q[a];b?(V.deleteShader(b),Q[a]=null):S(1281)}},La:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=rb[d];e&&(V.deleteTexture(e),e.name=0,rb[d]=null)}},Ha:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2];V.deleteVertexArray(sb[d]);sb[d]=null}},u:function(a){V.depthFunc(a)},t:function(a){V.depthMask(!!a)},c:function(a){V.disable(a)},H:function(a){V.disableVertexAttribArray(a)},
$a:function(a,b,c){V.drawArrays(a,b,c)},ab:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},bb:function(a,b,c,d){V.drawElements(a,b,c,d)},cb:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},f:function(a){V.enable(a)},nb:function(a){V.enableVertexAttribArray(a)},C:function(a){V.frontFace(a)},Aa:function(a,b){Eb(a,b,"createBuffer",ob)},ra:function(a,b){Eb(a,b,"createSampler",R)},xa:function(a,b){Eb(a,b,"createTexture",rb)},Ga:function(a,b){Eb(a,b,"createVertexArray",sb)},ia:function(a,b){return V.getAttribLocation(P[a],
b?I(b):"")},b:function(a,b){Fb(a,b)},na:function(a,b,c,d){a=V.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(A[c>>2]=b)},y:function(a,b,c){if(c)if(a>=nb)S(1281);else if(a=P[a],35716==b)a=V.getProgramInfoLog(a),null===a&&(a="(unknown error)"),A[c>>2]=a.length+1;else if(35719==b){if(!a.$b)for(b=0;b<V.getProgramParameter(a,35718);++b)a.$b=Math.max(a.$b,V.getActiveUniform(a,b).name.length+1);A[c>>2]=a.$b}else if(35722==b){if(!a.Yb)for(b=0;b<V.getProgramParameter(a,35721);++b)a.Yb=
Math.max(a.Yb,V.getActiveAttrib(a,b).name.length+1);A[c>>2]=a.Yb}else if(35381==b){if(!a.Zb)for(b=0;b<V.getProgramParameter(a,35382);++b)a.Zb=Math.max(a.Zb,V.getActiveUniformBlockName(a,b).length+1);A[c>>2]=a.Zb}else A[c>>2]=V.getProgramParameter(a,b);else S(1281)},ja:function(a,b,c,d){a=V.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(A[c>>2]=b)},w:function(a,b,c){c?35716==b?(a=V.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),A[c>>2]=a?a.length+1:0):35720==
b?(a=V.getShaderSource(Q[a]),A[c>>2]=a?a.length+1:0):A[c>>2]=V.getShaderParameter(Q[a],b):S(1281)},Na:function(a,b){if(2>T.version)return S(1282),0;var c=ub[a];if(c)return 0>b||b>=c.length?(S(1281),0):c[b];switch(a){case 7939:return c=V.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){var e=Gb(d)+1,k=M(e);k&&L(d,k,e);return k}),c=ub[a]=c,0>b||b>=c.length?(S(1281),0):c[b];default:return S(1280),0}},m:function(a,b){b=b?I(b):"";if(a=P[a]){var c=a,d=c.Wb,
e=c.sc,k;if(!d)for(c.Wb=d={},c.rc={},k=0;k<V.getProgramParameter(c,35718);++k){var f=V.getActiveUniform(c,k);var m=f.name;f=f.size;var n=Hb(m);n=0<n?m.slice(0,n):m;var p=c.bc;c.bc+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.rc[p++]=n}c=a.Wb;d=0;e=b;k=Hb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.sc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||V.getUniformLocation(a,b)))return d}else S(1281);return-1},Ya:function(a,b,c){for(var d=Ib[b],e=0;e<b;e++)d[e]=A[c+4*e>>2];V.invalidateFramebuffer(a,d)},pa:function(a){a=
P[a];V.linkProgram(a);a.Wb=0;a.sc={}},Fa:function(a,b){3317==a&&(vb=b);V.pixelStorei(a,b)},D:function(a,b){V.polygonOffset(a,b)},_a:function(a){V.readBuffer(a)},A:function(a,b,c){V.samplerParameterf(R[a],b,c)},e:function(a,b,c){V.samplerParameteri(R[a],b,c)},tb:function(a,b,c,d){V.scissor(a,b,c,d)},la:function(a,b,c,d){for(var e="",k=0;k<b;++k){var f=d?A[d+4*k>>2]:-1,m=A[c+4*k>>2];f=m?I(m,0>f?void 0:f):"";e+=f}V.shaderSource(Q[a],e)},Da:function(a,b,c){V.stencilFunc(a,b,c)},ga:function(a,b,c,d){V.stencilFuncSeparate(a,
b,c,d)},s:function(a){V.stencilMask(a)},Ca:function(a,b,c){V.stencilOp(a,b,c)},fa:function(a,b,c,d){V.stencilOpSeparate(a,b,c,d)},ua:function(a,b,c,d,e,k,f,m,n){if(2<=T.version)if(V.Tb)V.texImage2D(a,b,c,d,e,k,f,m,n);else if(n){var p=Jb(m);V.texImage2D(a,b,c,d,e,k,f,m,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else V.texImage2D(a,b,c,d,e,k,f,m,null);else{p=V;var w=p.texImage2D;if(n){var r=Jb(m),N=31-Math.clz32(r.BYTES_PER_ELEMENT),U=vb;n=r.subarray(n>>N,n+e*(d*({5:3,6:4,8:2,29502:3,29504:4,26917:2,
26918:2,29846:3,29847:4}[f-6402]||1)*(1<<N)+U-1&-U)>>N)}else n=null;w.call(p,a,b,c,d,e,k,f,m,n)}},sa:function(a,b,c,d,e,k,f,m,n,p){if(V.Tb)V.texImage3D(a,b,c,d,e,k,f,m,n,p);else if(p){var w=Jb(n);V.texImage3D(a,b,c,d,e,k,f,m,n,w,p>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else V.texImage3D(a,b,c,d,e,k,f,m,n,null)},mb:function(a,b,c){if(2<=T.version)b&&V.uniform1fv(W(a),B,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);V.uniform1fv(W(a),d)}},x:function(a,
b){V.uniform1i(W(a),b)},ib:function(a,b,c){if(2<=T.version)b&&V.uniform1iv(W(a),A,c>>2,b);else{if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);V.uniform1iv(W(a),d)}},lb:function(a,b,c){if(2<=T.version)b&&V.uniform2fv(W(a),B,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);V.uniform2fv(W(a),d)}},hb:function(a,b,c){if(2<=T.version)b&&V.uniform2iv(W(a),A,c>>2,2*b);else{if(144>=
b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);V.uniform2iv(W(a),d)}},kb:function(a,b,c){if(2<=T.version)b&&V.uniform3fv(W(a),B,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);V.uniform3fv(W(a),d)}},gb:function(a,b,c){if(2<=T.version)b&&V.uniform3iv(W(a),A,c>>2,3*b);else{if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],
d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);V.uniform3iv(W(a),d)}},jb:function(a,b,c){if(2<=T.version)b&&V.uniform4fv(W(a),B,c>>2,4*b);else{if(72>=b){var d=X[4*b-1],e=B;c>>=2;for(var k=0;k<4*b;k+=4){var f=c+k;d[k]=e[f];d[k+1]=e[f+1];d[k+2]=e[f+2];d[k+3]=e[f+3]}}else d=B.subarray(c>>2,c+16*b>>2);V.uniform4fv(W(a),d)}},fb:function(a,b,c){if(2<=T.version)b&&V.uniform4iv(W(a),A,c>>2,4*b);else{if(72>=b)for(var d=Y[4*b-1],e=0;e<4*b;e+=4)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*
e+4)>>2],d[e+2]=A[c+(4*e+8)>>2],d[e+3]=A[c+(4*e+12)>>2];else d=A.subarray(c>>2,c+16*b>>2);V.uniform4iv(W(a),d)}},eb:function(a,b,c,d){if(2<=T.version)b&&V.uniformMatrix4fv(W(a),!!c,B,d>>2,16*b);else{if(18>=b){var e=X[16*b-1],k=B;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=k[m];e[f+1]=k[m+1];e[f+2]=k[m+2];e[f+3]=k[m+3];e[f+4]=k[m+4];e[f+5]=k[m+5];e[f+6]=k[m+6];e[f+7]=k[m+7];e[f+8]=k[m+8];e[f+9]=k[m+9];e[f+10]=k[m+10];e[f+11]=k[m+11];e[f+12]=k[m+12];e[f+13]=k[m+13];e[f+14]=k[m+14];e[f+15]=k[m+15]}}else e=
B.subarray(d>>2,d+64*b>>2);V.uniformMatrix4fv(W(a),!!c,e)}},n:function(a){a=P[a];V.useProgram(a);V.tc=a},pb:function(a,b){V.vertexAttribDivisor(a,b)},qb:function(a,b,c,d,e,k){V.vertexAttribPointer(a,b,c,!!d,e,k)},ub:function(a,b,c,d){V.viewport(a,b,c,d)},Pa:function(){g.lc=a=>{0!=Pb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.lc)},Ja:function(){g.qc=a=>{const b=a.clipboardData.getData("text");Ha(()=>{const c=Mb(b);Qb(c)})};window.addEventListener("paste",g.qc)},
Ba:function(a){g.Gc=[];a=a?I(a):"";a=document.getElementById(a);g.mc=b=>{b.stopPropagation();b.preventDefault()};g.nc=b=>{b.stopPropagation();b.preventDefault()};g.oc=b=>{b.stopPropagation();b.preventDefault()};g.pc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Hc=c;Rb(c.length);for(let e=0;e<c.length;e++)Ha(()=>{const k=Mb(c[e].name);Sb(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Tb(b.clientX,b.clientY,d)};a.addEventListener("dragenter",
g.mc,!1);a.addEventListener("dragleave",g.nc,!1);a.addEventListener("dragover",g.oc,!1);a.addEventListener("drop",g.pc,!1)},ob:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},q:function(){const a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Ub()});document.body.append(a)},p:function(){document.getElementById("_sokol_app_input_element").focus()},oa:function(a){a=
a?I(a):"";g.Vb=document.getElementById(a);g.Vb||console.log("sokol_app.h: invalid target:"+a);g.Vb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Oa:function(){window.removeEventListener("beforeunload",g.lc)},Ea:function(){window.removeEventListener("paste",g.qc)},va:function(a){a=a?I(a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.mc);a.removeEventListener("dragleave",g.nc);a.removeEventListener("dragover",g.oc);a.removeEventListener("drop",
g.pc)},v:function(){g.Vb&&g.Vb.requestPointerLock&&g.Vb.requestPointerLock()},db:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(z.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},o:function(){document.getElementById("_sokol_app_input_element").blur()},ea:function(a,b){b=b?I(b):"";switch(a){case 0:console.error(b);
break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};
(function(){function a(c){c=c.exports;g.asm=c;ja=g.asm.vb;pa();qa=g.asm.Lb;sa.unshift(g.asm.wb);D--;g.monitorRunDependencies&&g.monitorRunDependencies(D);if(0==D&&(null!==xa&&(clearInterval(xa),xa=null),E)){var d=E;E=null;d()}return c}var b={a:Vb};D++;g.monitorRunDependencies&&g.monitorRunDependencies(D);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return x("Module.instantiateWasm callback failed with error: "+c),!1}Da(b,function(c){a(c.instance)});return{}})();
var Ub=g.__sapp_emsc_notify_keyboard_hidden=function(){return(Ub=g.__sapp_emsc_notify_keyboard_hidden=g.asm.xb).apply(null,arguments)},Qb=g.__sapp_emsc_onpaste=function(){return(Qb=g.__sapp_emsc_onpaste=g.asm.yb).apply(null,arguments)},Pb=g.__sapp_html5_get_ask_leave_site=function(){return(Pb=g.__sapp_html5_get_ask_leave_site=g.asm.zb).apply(null,arguments)},Rb=g.__sapp_emsc_begin_drop=function(){return(Rb=g.__sapp_emsc_begin_drop=g.asm.Ab).apply(null,arguments)},Sb=g.__sapp_emsc_drop=function(){return(Sb=
g.__sapp_emsc_drop=g.asm.Bb).apply(null,arguments)},Tb=g.__sapp_emsc_end_drop=function(){return(Tb=g.__sapp_emsc_end_drop=g.asm.Cb).apply(null,arguments)};g.__sapp_emsc_invoke_fetch_cb=function(){return(g.__sapp_emsc_invoke_fetch_cb=g.asm.Db).apply(null,arguments)};var Wb=g._main=function(){return(Wb=g._main=g.asm.Eb).apply(null,arguments)};g.__saudio_emsc_pull=function(){return(g.__saudio_emsc_pull=g.asm.Fb).apply(null,arguments)};
g.__sfetch_emsc_head_response=function(){return(g.__sfetch_emsc_head_response=g.asm.Gb).apply(null,arguments)};g.__sfetch_emsc_get_response=function(){return(g.__sfetch_emsc_get_response=g.asm.Hb).apply(null,arguments)};g.__sfetch_emsc_failed_http_status=function(){return(g.__sfetch_emsc_failed_http_status=g.asm.Ib).apply(null,arguments)};g.__sfetch_emsc_failed_buffer_too_small=function(){return(g.__sfetch_emsc_failed_buffer_too_small=g.asm.Jb).apply(null,arguments)};
function M(){return(M=g.asm.Kb).apply(null,arguments)}function Fa(){return(Fa=g.asm.Mb).apply(null,arguments)}function Ga(){return(Ga=g.asm.Nb).apply(null,arguments)}function Lb(){return(Lb=g.asm.Ob).apply(null,arguments)}g.___start_em_js=4976;g.___stop_em_js=14651;var Xb;E=function Yb(){Xb||Zb();Xb||(E=Yb)};function $b(a=[]){var b=Wb;a.unshift(ca);var c=a.length,d=Lb(4*(c+1)),e=d>>2;a.forEach(f=>{A[e++]=Mb(f)});A[e]=0;try{var k=b(c,d);Kb(k)}catch(f){f instanceof v||"unwind"==f||h(1,f)}}
function Zb(){var a=ba;function b(){if(!Xb&&(Xb=!0,g.calledRun=!0,!ka)){Ea(sa);Ea(ta);if(g.onRuntimeInitialized)g.onRuntimeInitialized();ac&&$b(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();va.unshift(c)}Ea(va)}}if(!(0<D)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)wa();Ea(ra);0<D||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var ac=!0;g.noInitialRun&&(ac=!1);Zb();
