var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa={},h;for(h in e)e.hasOwnProperty(h)&&(aa[h]=e[h]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var l=!1,p=!1,q=!1,ba=!1;
if(e.ENVIRONMENT)if("WEB"===e.ENVIRONMENT)l=!0;else if("WORKER"===e.ENVIRONMENT)p=!0;else if("NODE"===e.ENVIRONMENT)q=!0;else if("SHELL"===e.ENVIRONMENT)ba=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else l="object"===typeof window,p="function"===typeof importScripts,q="object"===typeof process&&"function"===typeof require&&!l&&!p,ba=!l&&!q&&!p;
if(q){var ca,da;e.read=function(a,b){ca||(ca=require("fs"));da||(da=require("path"));a=da.normalize(a);a=ca.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof r))throw a;});process.on("unhandledRejection",
function(){process.exit(1)});e.inspect=function(){return"[Emscripten Module object]"}}else if(ba)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(l||p)e.read=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},p&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};
e.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;e.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||e.print;e.print=e.print;e.printErr=e.printErr;for(h in aa)aa.hasOwnProperty(h)&&(e[h]=aa[h]);aa=void 0;function ea(a){assert(!fa);var b=t;t=t+a+15&-16;return b}function ha(a){var b;b||(b=16);return Math.ceil(a/b)*b}function ia(a){ja||(ja={});ja[a]||(ja[a]=1,e.printErr(a))}var ja,v=0;
function assert(a,b){a||w("Assertion failed: "+b)}function ka(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=("function"===typeof la?la:ea)(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)x[a>>2]=0;for(b=d+c;a<b;)ma[a++>>0]=0;return d}a.subarray||a.slice?y.set(a,d):y.set(new Uint8Array(a),d);return d}
function z(a,b){if(0===b||!a)return"";for(var c=0,d,f=0;;){d=y[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,y.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return na(y,a)}var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function na(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&oa)return oa.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var k=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|k;else{var n=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|k<<6|n;else{var m=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|k<<12|n<<6|m}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}
function A(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);55296<=k&&57343>=k&&(k=65536+((k&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(2097151>=k){if(c+3>=d)break;b[c++]=240|k>>18}else{if(67108863>=k){if(c+4>=d)break;b[c++]=248|k>>24}else{if(c+5>=d)break;b[c++]=252|k>>30;b[c++]=128|k>>24&63}b[c++]=128|k>>18&63}b[c++]=128|
k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}function pa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function qa(a){var b=pa(a)+1,c=ra(b);A(a,ma,c,b);return c}var buffer,ma,y,B,sa,x,ta,D,E;
function ua(){e.HEAP8=ma=new Int8Array(buffer);e.HEAP16=B=new Int16Array(buffer);e.HEAP32=x=new Int32Array(buffer);e.HEAPU8=y=new Uint8Array(buffer);e.HEAPU16=sa=new Uint16Array(buffer);e.HEAPU32=ta=new Uint32Array(buffer);e.HEAPF32=D=new Float32Array(buffer);e.HEAPF64=E=new Float64Array(buffer)}var va,t,fa,wa,xa,ya,za,Aa;va=t=wa=xa=ya=za=Aa=0;fa=!1;
function Ba(){w("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+F+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Ca=e.TOTAL_STACK||5242880,F=e.TOTAL_MEMORY||134217728;F<Ca&&e.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+F+"! (TOTAL_STACK="+Ca+")");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:F/65536,maximum:F/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(F),e.buffer=buffer);ua();x[0]=1668509029;B[1]=25459;if(115!==y[2]||99!==y[3])throw"Runtime error: expected the system to be little-endian!";
function G(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.A;"number"===typeof c?void 0===b.i?e.dynCall_v(c):e.dynCall_vi(c,b.i):c(void 0===b.i?null:b.i)}}}var Da=[],Ea=[],Fa=[],Ga=[],Ha=[],Ia=!1;function Ja(){var a=e.preRun.shift();Da.unshift(a)}var H=0,Ka=null,La=null;e.preloadedImages={};e.preloadedAudios={};
function Ma(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(C){w(C)}}function b(){return e.wasmBinary||!l&&!p||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){n=a.exports;if(n.memory){a=n.memory;var b=e.buffer;a.byteLength<b.byteLength&&e.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;ua()}e.asm=n;e.usingWasm=!0;H--;e.monitorRunDependencies&&e.monitorRunDependencies(H);0==H&&(null!==Ka&&(clearInterval(Ka),Ka=null),La&&(a=La,La=null,a()))}
function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,k)}).then(a).catch(function(a){e.printErr("failed to asynchronously prepare wasm: "+a);w(a)})}if("object"!==typeof WebAssembly)return e.printErr("no native wasm support detected"),!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return e.printErr("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;k.global={NaN:NaN,Infinity:Infinity};k["global.Math"]=Math;k.env=a;H++;e.monitorRunDependencies&&e.monitorRunDependencies(H);
if(e.instantiateWasm)try{return e.instantiateWasm(k,c)}catch(Zb){return e.printErr("Module.instantiateWasm callback failed with error: "+Zb),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Ma(f)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),k).then(d).catch(function(a){e.printErr("wasm streaming compile failed: "+a);e.printErr("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="imgui-emsc.wast",f="imgui-emsc.wasm",
g="imgui-emsc.temp.asm.js";"function"===typeof e.locateFile&&(Ma(d)||(d=e.locateFile(d)),Ma(f)||(f=e.locateFile(f)),Ma(g)||(g=e.locateFile(g)));var k={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},parent:e},n=null;e.asmPreload=e.asm;var m=e.reallocBuffer;e.reallocBuffer=function(a){if("asmjs"===u)var b=m(a);else a:{var c=e.usingWasm?65536:16777216;0<a%c&&(a+=c-a%c);c=e.buffer.byteLength;if(e.usingWasm)try{b=-1!==e.wasmMemory.grow((a-c)/65536)?
e.buffer=e.wasmMemory.buffer:null;break a}catch(rc){b=null;break a}b=void 0}return b};var u="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.memoryBase||(b.memoryBase=e.STATIC_BASE);b.tableBase||(b.tableBase=0);(b=c(b))||
w("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return b}})();va=1024;t=va+1774624;Ea.push({A:function(){Na()}});e.STATIC_BASE=va;e.STATIC_BUMP=1774624;t+=16;var J=0;function K(){J+=4;return x[J-4>>2]}var Oa={};
function L(a,b){J=b;try{var c=K(),d=K(),f=K();a=0;L.w||(L.w=[null,[],[]],L.H=function(a,b){var c=L.w[a];assert(c);0===b||10===b?((1===a?e.print:e.printErr)(na(c,0)),c.length=0):c.push(b)});for(b=0;b<f;b++){for(var g=x[d+8*b>>2],k=x[d+(8*b+4)>>2],n=0;n<k;n++)L.H(c,y[g+n]);a+=k}return a}catch(m){return"undefined"!==typeof FS&&m instanceof FS.g||w(m),-m.l}}function Pa(a){e.___errno_location&&(x[e.___errno_location()>>2]=a);return a}function M(){w()}var N=0,Qa=0,O=0,Ra=0,Sa=null,Ta=null,Ua=!1;
function Va(){Ua||(Ga.push(function(){for(var a=P.length-1;0<=a;--a)Wa(a)}),Ua=!0)}function Q(a){return a?("number"==typeof a&&(a=z(a)),"#window"==a?window:"#document"==a?document:"#screen"==a?window.screen:"#canvas"==a?e.canvas:"string"==typeof a?document.getElementById(a):a):window}var Xa=[];function Ya(){if(Za&&$a.h)for(var a=0;a<Xa.length;++a){var b=Xa[a];Xa.splice(a,1);--a;b.aa.apply(this,b.R)}}var Za=0,$a=null,P=[];
function ab(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function Wa(a){var b=P[a];b.target.removeEventListener(b.b,b.J,b.m);P.splice(a,1)}function bb(a){function b(b){++Za;$a=a;Ya();a.u(b);Ya();--Za}if(a.s)a.J=b,a.target.addEventListener(a.b,b,a.m),P.push(a),Va();else for(var c=0;c<P.length;++c)P[c].target==a.target&&P[c].b==a.b&&Wa(c--)}
function cb(a,b,c,d,f,g){N||(N=la(164));a={target:Q(a),h:ab()?!1:!0,b:g,s:d,u:function(a){a=a||window.event;A(a.key?a.key:"",y,N+0,32);A(a.code?a.code:"",y,N+32,32);x[N+64>>2]=a.location;x[N+68>>2]=a.ctrlKey;x[N+72>>2]=a.shiftKey;x[N+76>>2]=a.altKey;x[N+80>>2]=a.metaKey;x[N+84>>2]=a.repeat;A(a.locale?a.locale:"",y,N+88,32);A(a.char?a.char:"",y,N+120,32);x[N+152>>2]=a.charCode;x[N+156>>2]=a.keyCode;x[N+160>>2]=a.which;e.dynCall_iiii(d,f,N,b)&&a.preventDefault()},m:c};bb(a)}
function db(a,b,c){E[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();x[a+8>>2]=b.screenX;x[a+12>>2]=b.screenY;x[a+16>>2]=b.clientX;x[a+20>>2]=b.clientY;x[a+24>>2]=b.ctrlKey;x[a+28>>2]=b.shiftKey;x[a+32>>2]=b.altKey;x[a+36>>2]=b.metaKey;B[a+40>>1]=b.button;B[a+42>>1]=b.buttons;x[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-Sa;x[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-Ta;if(e.canvas){var d=e.canvas.getBoundingClientRect();
x[a+60>>2]=b.clientX-d.left;x[a+64>>2]=b.clientY-d.top}else x[a+60>>2]=0,x[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},x[a+52>>2]=b.clientX-d.left,x[a+56>>2]=b.clientY-d.top):(x[a+52>>2]=0,x[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(Sa=b.screenX,Ta=b.screenY)}
function eb(a,b,c,d,f,g){Qa||(Qa=la(72));a=Q(a);c={target:a,h:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,b:g,s:d,u:function(c){c=c||window.event;db(Qa,c,a);e.dynCall_iiii(d,f,Qa,b)&&c.preventDefault()},m:c};ab()&&"mousedown"==g&&(c.h=!1);bb(c)}
function fb(a,b,c,d,f){function g(c){c=c||window.event;db(O,c,a);E[O+72>>3]=c.wheelDeltaX||0;E[O+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);E[O+88>>3]=0;x[O+96>>2]=0;e.dynCall_iiii(d,9,O,b)&&c.preventDefault()}function k(c){c=c||window.event;db(O,c,a);E[O+72>>3]=c.deltaX;E[O+80>>3]=c.deltaY;E[O+88>>3]=c.deltaZ;x[O+96>>2]=c.deltaMode;e.dynCall_iiii(d,9,O,b)&&c.preventDefault()}O||(O=la(104));a=Q(a);bb({target:a,h:!0,b:f,s:d,u:"wheel"==f?k:g,m:c})}
var R=null,gb="",S=0,hb=null,ib=0,jb=0,kb=0,lb=0,mb=[],nb={},ob,pb,qb,rb=!1,sb=!1,tb=[];
function ub(){function a(){sb=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}e.preloadPlugins||(e.preloadPlugins=[]);if(!vb){vb=!0;try{wb=!0}catch(c){wb=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}xb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:wb?null:console.log("warning: no BlobBuilder");
yb="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;e.C||"undefined"!==typeof yb||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),e.C=!0);e.preloadPlugins.push({canHandle:function(a){return!e.C&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,f,g){var c=null;if(wb)try{c=new Blob([a],{type:zb(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:zb(b)}))}catch(u){ia("Blob constructor present but fails: "+
u+"; falling back to blob builder")}c||(c=new xb,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=yb.createObjectURL(c),m=new Image;m.onload=function(){assert(m.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=m.width;c.height=m.height;c.getContext("2d").drawImage(m,0,0);e.preloadedImages[b]=c;yb.revokeObjectURL(d);f&&f(a)};m.onerror=function(){console.log("Image "+d+" could not be decoded");g&&g()};m.src=d}});e.preloadPlugins.push({canHandle:function(a){return!e.$&&
a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,f,g){function c(c){m||(m=!0,e.preloadedAudios[b]=c,f&&f(a))}function d(){m||(m=!0,e.preloadedAudios[b]=new Audio,g&&g())}var m=!1;if(wb){try{var u=new Blob([a],{type:zb(b)})}catch(I){return d()}u=yb.createObjectURL(u);var C=new Audio;C.addEventListener("canplaythrough",function(){c(C)},!1);C.onerror=function(){if(!m){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",f=0,g=0,
k=0;k<a.length;k++)for(f=f<<8|a[k],g+=8;6<=g;){var n=f>>g-6&63;g-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[n]}2==g?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&3)<<4],d+="=="):4==g&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&15)<<2],d+="=");C.src="data:audio/x-"+b.substr(-3)+";base64,"+d;c(C)}};C.src=u;Ab(function(){c(C)})}else return d()}});var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&
b.addEventListener("click",function(a){!sb&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),a.preventDefault())},!1))}}
function Bb(a,b,c,d){if(b&&e.j&&a==e.canvas)return e.j;if(b){var f={antialias:!1,alpha:!1};if(d)for(var g in d)f[g]=d[g];if(f=Cb(a,f))var k=Db[f].GLctx}else k=a.getContext("2d");if(!k)return null;c&&(b||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),e.j=k,b&&Eb(f),e.ba=b,tb.forEach(function(a){a()}),ub());return k}var Fb=!1,Gb=void 0,Hb=void 0;
function Ib(a,b,c){function d(){rb=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){},f.exitFullscreen=f.exitFullscreen.bind(document),Gb&&f.requestPointerLock(),rb=!0,Hb&&("undefined"!=typeof SDL&&
(x[SDL.screen>>2]=ta[SDL.screen>>2]|8388608),Jb())):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),Hb&&("undefined"!=typeof SDL&&(x[SDL.screen>>2]=ta[SDL.screen>>2]&-8388609),Jb()));if(e.onFullScreen)e.onFullScreen(rb);if(e.onFullscreen)e.onFullscreen(rb);Kb(f)}Gb=a;Hb=b;Lb=c;"undefined"===typeof Gb&&(Gb=!0);"undefined"===typeof Hb&&(Hb=!1);"undefined"===typeof Lb&&(Lb=null);var f=e.canvas;Fb||(Fb=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",
d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var g=document.createElement("div");f.parentNode.insertBefore(g,f);g.appendChild(f);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?g.requestFullscreen({da:c}):
g.requestFullscreen()}function Mb(a,b,c){e.printErr("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");Mb=function(a,b,c){return Ib(a,b,c)};return Ib(a,b,c)}var Nb=0;function Ob(a){var b=Date.now();if(0===Nb)Nb=b+1E3/60;else for(;b+2>=Nb;)Nb+=1E3/60;setTimeout(a,Math.max(Nb-b,0))}
function Pb(a){"undefined"===typeof window?Ob(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||Ob),window.requestAnimationFrame(a))}function Ab(a){e.noExitRuntime=!0;setTimeout(function(){v||a()},1E4)}
function zb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Qb=[];function Jb(){var a=e.canvas;Qb.forEach(function(b){b(a.width,a.height)})}
function Kb(a,b,c){b&&c?(a.O=b,a.L=c):(b=a.O,c=a.L);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*g)}Hb?
(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var vb,wb,xb,yb,Lb;
function Rb(a,b){jb=a;kb=b;if(hb)if(0==a)R=function(){var a=Math.max(0,pb+b-M())|0;setTimeout(qb,a)},gb="timeout";else if(1==a)R=function(){Pb(qb)},gb="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);p?(void 0===e.setImmediates&&(e.setImmediates=[]),e.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}R=function(){setImmediate(qb)};gb="immediate"}}
function Sb(a,b,c,d,f){e.noExitRuntime=!0;assert(!hb,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");hb=a;ib=d;var g="undefined"!==typeof d?function(){e.dynCall_vi(a,d)}:function(){e.dynCall_v(a)};var k=S;qb=function(){if(!v)if(0<mb.length){var a=Date.now(),b=mb.shift();b.A(b.i);if(ob){var c=ob,d=0==c%1?c-1:Math.floor(c);ob=b.S?d:(8*c+(d+.5))/9}console.log('main loop blocker "'+
b.name+'" took '+(Date.now()-a)+" ms");e.setStatus&&(a=e.statusMessage||"Please wait...",b=ob,c=nb.W,b?b<c?e.setStatus(a+" ("+(c-b)+"/"+c+")"):e.setStatus(a):e.setStatus(""));k<S||setTimeout(qb,0)}else if(!(k<S))if(lb=lb+1|0,1==jb&&1<kb&&0!=lb%kb)R();else{0==jb&&(pb=M());"timeout"===gb&&e.j&&(e.printErr("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
gb="");a:if(!(v||e.preMainLoop&&!1===e.preMainLoop())){try{g()}catch(I){if(I instanceof r)break a;I&&"object"===typeof I&&I.stack&&e.printErr("exception thrown: "+[I,I.stack]);throw I;}e.postMainLoop&&e.postMainLoop()}k<S||("object"===typeof SDL&&SDL.audio&&SDL.audio.N&&SDL.audio.N(),R())}};f||(b&&0<b?Rb(0,1E3/b):Rb(1,1),R());if(c)throw"SimulateInfiniteLoop";}var Tb=1,Ub=0,Vb=[],T=[],Wb=[],Xb=[],U=[],V=[],Db=[],W=null,Yb={},$b={},ac={},bc=[];function X(a){Ub||(Ub=a)}
function Y(a){for(var b=Tb++,c=a.length;c<b;c++)a[c]=null;return b}var cc=null,dc=[0];
function Cb(a,b){function c(a){d=a.statusMessage||d}"undefined"===typeof b.majorVersion&&"undefined"===typeof b.minorVersion&&(b.majorVersion="undefined"!==typeof WebGL2RenderingContext?2:1,b.minorVersion=0);var d="?";try{a.addEventListener("webglcontextcreationerror",c,!1);try{if(1==b.majorVersion&&0==b.minorVersion)var f=a.getContext("webgl",b)||a.getContext("experimental-webgl",b);else if(2==b.majorVersion&&0==b.minorVersion)f=a.getContext("webgl2",b);else throw"Unsupported WebGL context version "+
majorVersion+"."+minorVersion+"!";}finally{a.removeEventListener("webglcontextcreationerror",c,!1)}if(!f)throw":(";}catch(g){return e.print("Could not create canvas: "+[d,g,JSON.stringify(b)]),0}return f?ec(f,b):0}
function ec(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=Y(Db),f={handle:d,attributes:b,version:b.majorVersion,GLctx:a};f.a=2<=f.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.o=f);Db[d]=f;("undefined"===typeof b.enableExtensionsByDefault||b.enableExtensionsByDefault)&&fc(f);return d}function Eb(a){a=Db[a];if(!a)return!1;GLctx=e.j=a.GLctx;W=a;return!0}
function fc(a){a||(a=W);if(!a.M){a.M=!0;var b=a.GLctx;a.Z=b.getParameter(b.MAX_VERTEX_ATTRIBS);if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,f){c.drawArraysInstancedANGLE(a,b,d,f)},b.drawElementsInstanced=function(a,b,d,f,g){c.drawElementsInstancedANGLE(a,b,d,f,g)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},
b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var f=b.getExtension("WEBGL_draw_buffers");f&&(b.drawBuffers=function(a,b){f.drawBuffersWEBGL(a,b)})}b.U=b.getExtension("EXT_disjoint_timer_query");var g="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear WEBGL_compressed_texture_atc WEBKIT_WEBGL_compressed_texture_pvrtc WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_frag_depth EXT_sRGB WEBGL_draw_buffers WEBGL_shared_resources EXT_shader_texture_lod EXT_color_buffer_float".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=g.indexOf(a)&&b.getExtension(a)})}}function _glDrawArrays(a,b,c){GLctx.drawArrays(a,b,c)}function _glDrawElements(a,b,c,d){GLctx.drawElements(a,b,c,d)}
function hc(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:c=GLctx.getParameter(34467).length;break;case 33309:if(2>GLctx.canvas.o.version){X(1282);return}c=2*GLctx.getSupportedExtensions().length;break;case 33307:case 33308:if(2>GLctx.canvas.o.version){X(1280);return}c=33307==a?3:0}if(void 0===c)switch(c=GLctx.getParameter(a),typeof c){case "number":break;case "boolean":c=c?1:0;break;case "string":X(1280);return;case "object":if(null===
c)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=0;break;default:X(1280);return}else{if(c instanceof Float32Array||c instanceof Uint32Array||c instanceof Int32Array||c instanceof Array){for(a=0;a<c.length;++a)x[b+4*a>>2]=c[a];return}if(c instanceof WebGLBuffer||c instanceof WebGLProgram||c instanceof WebGLFramebuffer||c instanceof WebGLRenderbuffer||c instanceof WebGLQuery||c instanceof WebGLSampler||c instanceof WebGLSync||
c instanceof WebGLTransformFeedback||c instanceof WebGLVertexArrayObject||c instanceof WebGLTexture)c=c.name|0;else{X(1280);return}}break;default:X(1280);return}x[b>>2]=c}else X(1281)}
function ic(a,b,c,d,f){switch(b){case 6406:case 6409:case 6402:case 6403:case 36244:b=1;break;case 6410:case 33319:case 33320:b=2;break;case 6407:case 35904:case 36248:b=3;break;case 6408:case 35906:case 36249:b=4;break;default:return X(1280),null}switch(a){case 5121:case 5120:b*=1;break;case 5123:case 36193:case 5131:case 5122:b*=2;break;case 5125:case 5126:case 5124:b*=4;break;case 34042:case 35902:case 33640:case 35899:case 34042:b=4;break;case 33635:case 32819:case 32820:b=2;break;default:return X(1280),
null}c*=b;b=4*Math.floor((c+4-1)/4);d=0>=d?0:(d-1)*b+c;switch(a){case 5120:return ma.subarray(f,f+d);case 5121:return y.subarray(f,f+d);case 5122:return B.subarray(f>>1,f+d>>1);case 5124:return x.subarray(f>>2,f+d>>2);case 5126:return D.subarray(f>>2,f+d>>2);case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return ta.subarray(f>>2,f+d>>2);case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return sa.subarray(f>>1,f+d>>1);default:return X(1280),null}}
function jc(a){switch(a){case 5120:return ma;case 5121:return y;case 5122:return B;case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return sa;case 5124:return x;case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return ta;case 5126:return D;default:return null}}
function kc(a){switch(a){case 5120:case 5121:return 0;case 5122:case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return 1;case 5124:case 5126:case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return 2;default:return 0}}
q?M=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?M=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?M=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?M=function(){return performance.now()}:M=Date.now;
(function(){if("undefined"!==typeof window){window.addEventListener("gamepadconnected",function(){++Ra});window.addEventListener("gamepaddisconnected",function(){--Ra});var a=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null;a&&(Ra=a.length)}})();e.requestFullScreen=function(a,b,c){e.printErr("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");e.requestFullScreen=e.requestFullscreen;Mb(a,b,c)};
e.requestFullscreen=function(a,b,c){Ib(a,b,c)};e.requestAnimationFrame=function(a){Pb(a)};e.setCanvasSize=function(a,b,c){Kb(e.canvas,a,b);c||Jb()};e.pauseMainLoop=function(){R=null;S++};e.resumeMainLoop=function(){S++;var a=jb,b=kb,c=hb;hb=null;Sb(c,0,!1,ib,!0);Rb(a,b);R()};e.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};e.createContext=function(a,b,c,d){return Bb(a,b,c,d)};var GLctx;cc=new Float32Array(256);
for(var Z=0;256>Z;Z++)dc[Z]=cc.subarray(0,Z+1);for(Z=0;32>Z;Z++)bc.push(Array(Z));Aa=ea(4);wa=xa=ha(t);ya=wa+Ca;za=ha(ya);x[Aa>>2]=za;fa=!0;function lc(a){var b=Array(pa(a)+1);A(a,b,0,b.length);return b}e.wasmTableSize=46;e.wasmMaxTableSize=46;e.F={};
e.G={abort:w,enlargeMemory:function(){Ba()},getTotalMemory:function(){return F},abortOnCannotGrowMemory:Ba,___lock:function(){},___setErrNo:Pa,___syscall140:function(a,b){J=b;try{var c=Oa.B();K();var d=K(),f=K(),g=K();FS.Y(c,d,g);x[f>>2]=c.position;c.K&&0===d&&0===g&&(c.K=null);return 0}catch(k){return"undefined"!==typeof FS&&k instanceof FS.g||w(k),-k.l}},___syscall145:function(a,b){J=b;try{var c=Oa.B(),d=K(),f=K();return Oa.V(c,d,f)}catch(g){return"undefined"!==typeof FS&&g instanceof FS.g||w(g),
-g.l}},___syscall146:L,___syscall221:function(a,b){J=b;return 0},___syscall5:function(a,b){J=b;try{var c=z(K()),d=K(),f=K();return FS.open(c,d,f).fd}catch(g){return"undefined"!==typeof FS&&g instanceof FS.g||w(g),-g.l}},___syscall54:function(a,b){J=b;return 0},___syscall6:function(a,b){J=b;try{var c=Oa.B();FS.close(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof FS.g||w(d),-d.l}},___unlock:function(){},_clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a&&(q||"undefined"!==
typeof dateNow||(l||p)&&self.performance&&self.performance.now))a=M();else return Pa(22),-1;x[b>>2]=a/1E3|0;x[b+4>>2]=a%1E3*1E6|0;return 0},_emscripten_memcpy_big:function(a,b,c){y.set(y.subarray(b,b+c),a);return a},_emscripten_set_canvas_element_size:function(a,b,c){a=a?Q(a):e.canvas;if(!a)return-4;a.width=b;a.height=c;return 0},_emscripten_set_keydown_callback:function(a,b,c,d){cb(a,b,c,d,2,"keydown");return 0},_emscripten_set_keypress_callback:function(a,b,c,d){cb(a,b,c,d,1,"keypress");return 0},
_emscripten_set_keyup_callback:function(a,b,c,d){cb(a,b,c,d,3,"keyup");return 0},_emscripten_set_main_loop:Sb,_emscripten_set_mousedown_callback:function(a,b,c,d){eb(a,b,c,d,5,"mousedown");return 0},_emscripten_set_mousemove_callback:function(a,b,c,d){eb(a,b,c,d,8,"mousemove");return 0},_emscripten_set_mouseup_callback:function(a,b,c,d){eb(a,b,c,d,6,"mouseup");return 0},_emscripten_set_wheel_callback:function(a,b,c,d){a=Q(a);return"undefined"!==typeof a.onwheel?(fb(a,b,c,d,"wheel"),0):"undefined"!==
typeof a.onmousewheel?(fb(a,b,c,d,"mousewheel"),0):-1},_emscripten_webgl_create_context:function(a,b){var c={};c.alpha=!!x[b>>2];c.depth=!!x[b+4>>2];c.stencil=!!x[b+8>>2];c.antialias=!!x[b+12>>2];c.premultipliedAlpha=!!x[b+16>>2];c.preserveDrawingBuffer=!!x[b+20>>2];c.preferLowPowerToHighPerformance=!!x[b+24>>2];c.failIfMajorPerformanceCaveat=!!x[b+28>>2];c.majorVersion=x[b+32>>2];c.minorVersion=x[b+36>>2];c.explicitSwapControl=x[b+44>>2];a=(a=z(a))&&"#canvas"!==a||!e.canvas?Yb[a]||Q(a):e.canvas.id?
Yb[e.canvas.id]||Q(e.canvas.id):e.canvas;return a?c.explicitSwapControl?(console.error("emscripten_webgl_create_context failed: explicitSwapControl is not supported, please rebuild with -s OFFSCREENCANVAS_SUPPORT=1 to enable targeting the experimental OffscreenCanvas specification!"),0):Cb(a,c):0},_emscripten_webgl_init_context_attributes:function(a){x[a>>2]=1;x[a+4>>2]=1;x[a+8>>2]=0;x[a+12>>2]=1;x[a+16>>2]=1;x[a+20>>2]=0;x[a+24>>2]=0;x[a+28>>2]=0;x[a+32>>2]=1;x[a+36>>2]=0;x[a+40>>2]=1;x[a+44>>2]=
0},_emscripten_webgl_make_context_current:function(a){return Eb(a)?0:-5},_glActiveTexture:function(a){GLctx.activeTexture(a)},_glAttachShader:function(a,b){GLctx.attachShader(T[a],V[b])},_glBindBuffer:function(a,b){var c=b?Vb[b]:null;35051==a?GLctx.T=b:35052==a&&(GLctx.I=b);GLctx.bindBuffer(a,c)},_glBindFramebuffer:function(a,b){GLctx.bindFramebuffer(a,b?Wb[b]:null)},_glBindTexture:function(a,b){GLctx.bindTexture(a,b?Xb[b]:null)},_glBlendColor:function(a,b,c,d){GLctx.blendColor(a,b,c,d)},_glBlendEquationSeparate:function(a,
b){GLctx.blendEquationSeparate(a,b)},_glBlendFuncSeparate:function(a,b,c,d){GLctx.blendFuncSeparate(a,b,c,d)},_glBufferData:function(a,b,c,d){c?W.a?GLctx.bufferData(a,y,d,c,b):GLctx.bufferData(a,y.subarray(c,c+b),d):GLctx.bufferData(a,b,d)},_glBufferSubData:function(a,b,c,d){W.a?GLctx.bufferSubData(a,b,y,d,c):GLctx.bufferSubData(a,b,y.subarray(d,d+c))},_glClear:function(a){GLctx.clear(a)},_glClearColor:function(a,b,c,d){GLctx.clearColor(a,b,c,d)},_glClearDepthf:function(a){GLctx.clearDepth(a)},_glClearStencil:function(a){GLctx.clearStencil(a)},
_glColorMask:function(a,b,c,d){GLctx.colorMask(!!a,!!b,!!c,!!d)},_glCompileShader:function(a){GLctx.compileShader(V[a])},_glCreateProgram:function(){var a=Y(T),b=GLctx.createProgram();b.name=a;T[a]=b;return a},_glCreateShader:function(a){var b=Y(V);V[b]=GLctx.createShader(a);return b},_glCullFace:function(a){GLctx.cullFace(a)},_glDeleteProgram:function(a){if(a){var b=T[a];b?(GLctx.deleteProgram(b),b.name=0,T[a]=null,$b[a]=null):X(1281)}},_glDeleteShader:function(a){if(a){var b=V[a];b?(GLctx.deleteShader(b),
V[a]=null):X(1281)}},_glDepthFunc:function(a){GLctx.depthFunc(a)},_glDepthMask:function(a){GLctx.depthMask(!!a)},_glDisable:function(a){GLctx.disable(a)},_glDisableVertexAttribArray:function(a){GLctx.disableVertexAttribArray(a)},_glDrawArrays:_glDrawArrays,_glDrawElements:_glDrawElements,_glEnable:function(a){GLctx.enable(a)},_glEnableVertexAttribArray:function(a){GLctx.enableVertexAttribArray(a)},_glFrontFace:function(a){GLctx.frontFace(a)},_glGenBuffers:function(a,b){for(var c=0;c<a;c++){var d=
GLctx.createBuffer();if(!d){for(X(1282);c<a;)x[b+4*c++>>2]=0;break}var f=Y(Vb);d.name=f;Vb[f]=d;x[b+4*c>>2]=f}},_glGenTextures:function(a,b){for(var c=0;c<a;c++){var d=GLctx.createTexture();if(!d){for(X(1282);c<a;)x[b+4*c++>>2]=0;break}var f=Y(Xb);d.name=f;Xb[f]=d;x[b+4*c>>2]=f}},_glGetAttribLocation:function(a,b){a=T[a];b=z(b);return GLctx.getAttribLocation(a,b)},_glGetIntegerv:function(a,b){hc(a,b)},_glGetProgramInfoLog:function(a,b,c,d){a=GLctx.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");
0<b&&d?(b=A(a,y,d,b),c&&(x[c>>2]=b)):c&&(x[c>>2]=0)},_glGetProgramiv:function(a,b,c){if(c)if(a>=Tb)X(1281);else{var d=$b[a];if(d)if(35716==b)a=GLctx.getProgramInfoLog(T[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b)x[c>>2]=d.v;else if(35722==b){if(-1==d.c){a=T[a];var f=GLctx.getProgramParameter(a,GLctx.ACTIVE_ATTRIBUTES);for(b=d.c=0;b<f;++b)d.c=Math.max(d.c,GLctx.getActiveAttrib(a,b).name.length+1)}x[c>>2]=d.c}else if(35381==b){if(-1==d.f)for(a=T[a],f=GLctx.getProgramParameter(a,
GLctx.P),b=d.f=0;b<f;++b){var g=GLctx.X(a,b);d.f=Math.max(d.f,g.length+1)}x[c>>2]=d.f}else x[c>>2]=GLctx.getProgramParameter(T[a],b);else X(1282)}else X(1281)},_glGetShaderInfoLog:function(a,b,c,d){a=GLctx.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");0<b&&d?(b=A(a,y,d,b),c&&(x[c>>2]=b)):c&&(x[c>>2]=0)},_glGetShaderiv:function(a,b,c){c?35716==b?(a=GLctx.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1):35720==b?(a=GLctx.getShaderSource(V[a]),x[c>>2]=null===a||0==
a.length?0:a.length+1):x[c>>2]=GLctx.getShaderParameter(V[a],b):X(1281)},_glGetString:function(a){if(ac[a])return ac[a];switch(a){case 7936:case 7937:case 37445:case 37446:var b=ka(lc(GLctx.getParameter(a)));break;case 7938:b=GLctx.getParameter(GLctx.VERSION);b=2<=GLctx.canvas.o.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=ka(lc(b));break;case 7939:b=GLctx.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=ka(lc(c.join(" ")));break;case 35724:b=
GLctx.getParameter(GLctx.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ka(lc(b));break;default:return X(1280),0}return ac[a]=b},_glGetUniformLocation:function(a,b){b=z(b);var c=0;if(-1!==b.indexOf("]",b.length-1)){var d=b.lastIndexOf("["),f=b.slice(d+1,-1);if(0<f.length&&(c=parseInt(f),0>c))return-1;b=b.slice(0,d)}a=$b[a];return a?(b=a.D[b])&&c<b[0]?b[1]+c:-1:-1},_glLinkProgram:function(a){GLctx.linkProgram(T[a]);
$b[a]=null;var b=T[a];$b[a]={D:{},v:0,c:-1,f:-1};a=$b[a];for(var c=a.D,d=GLctx.getProgramParameter(b,GLctx.ACTIVE_UNIFORMS),f=0;f<d;++f){var g=GLctx.getActiveUniform(b,f),k=g.name;a.v=Math.max(a.v,k.length+1);-1!==k.indexOf("]",k.length-1)&&(k=k.slice(0,k.lastIndexOf("[")));var n=GLctx.getUniformLocation(b,k);if(null!=n){var m=Y(U);c[k]=[g.size,m];U[m]=n;for(var u=1;u<g.size;++u)n=GLctx.getUniformLocation(b,k+"["+u+"]"),m=Y(U),U[m]=n}}},_glPolygonOffset:function(a,b){GLctx.polygonOffset(a,b)},_glScissor:function(a,
b,c,d){GLctx.scissor(a,b,c,d)},_glShaderSource:function(a,b,c,d){for(var f="",g=0;g<b;++g){if(d){var k=x[d+4*g>>2];k=0>k?z(x[c+4*g>>2]):z(x[c+4*g>>2],k)}else k=z(x[c+4*g>>2]);f+=k}GLctx.shaderSource(V[a],f)},_glStencilFunc:function(a,b,c){GLctx.stencilFunc(a,b,c)},_glStencilFuncSeparate:function(a,b,c,d){GLctx.stencilFuncSeparate(a,b,c,d)},_glStencilMask:function(a){GLctx.stencilMask(a)},_glStencilOp:function(a,b,c){GLctx.stencilOp(a,b,c)},_glStencilOpSeparate:function(a,b,c,d){GLctx.stencilOpSeparate(a,
b,c,d)},_glTexImage2D:function(a,b,c,d,f,g,k,n,m){if(W.a)GLctx.I?GLctx.texImage2D(a,b,c,d,f,g,k,n,m):0!=m?GLctx.texImage2D(a,b,c,d,f,g,k,n,jc(n),m>>kc(n)):GLctx.texImage2D(a,b,c,d,f,g,k,n,null);else{var u=null;m&&(u=ic(n,k,d,f,m));GLctx.texImage2D(a,b,c,d,f,g,k,n,u)}},_glTexParameteri:function(a,b,c){GLctx.texParameteri(a,b,c)},_glUniform1fv:function(a,b,c){if(W.a)GLctx.uniform1fv(U[a],D,c>>2,b);else{if(256>=b){var d=dc[b-1];for(var f=0;f<b;++f)d[f]=D[c+4*f>>2]}else d=D.subarray(c>>2,c+4*b>>2);GLctx.uniform1fv(U[a],
d)}},_glUniform1i:function(a,b){GLctx.uniform1i(U[a],b)},_glUniform2fv:function(a,b,c){if(W.a)GLctx.uniform2fv(U[a],D,c>>2,2*b);else{if(256>=2*b){var d=dc[2*b-1];for(var f=0;f<2*b;f+=2)d[f]=D[c+4*f>>2],d[f+1]=D[c+(4*f+4)>>2]}else d=D.subarray(c>>2,c+8*b>>2);GLctx.uniform2fv(U[a],d)}},_glUniform3fv:function(a,b,c){if(W.a)GLctx.uniform3fv(U[a],D,c>>2,3*b);else{if(256>=3*b){var d=dc[3*b-1];for(var f=0;f<3*b;f+=3)d[f]=D[c+4*f>>2],d[f+1]=D[c+(4*f+4)>>2],d[f+2]=D[c+(4*f+8)>>2]}else d=D.subarray(c>>2,c+
12*b>>2);GLctx.uniform3fv(U[a],d)}},_glUniform4fv:function(a,b,c){if(W.a)GLctx.uniform4fv(U[a],D,c>>2,4*b);else{if(256>=4*b){var d=dc[4*b-1];for(var f=0;f<4*b;f+=4)d[f]=D[c+4*f>>2],d[f+1]=D[c+(4*f+4)>>2],d[f+2]=D[c+(4*f+8)>>2],d[f+3]=D[c+(4*f+12)>>2]}else d=D.subarray(c>>2,c+16*b>>2);GLctx.uniform4fv(U[a],d)}},_glUniformMatrix4fv:function(a,b,c,d){if(W.a)GLctx.uniformMatrix4fv(U[a],!!c,D,d>>2,16*b);else{if(256>=16*b){var f=dc[16*b-1];for(var g=0;g<16*b;g+=16)f[g]=D[d+4*g>>2],f[g+1]=D[d+(4*g+4)>>2],
f[g+2]=D[d+(4*g+8)>>2],f[g+3]=D[d+(4*g+12)>>2],f[g+4]=D[d+(4*g+16)>>2],f[g+5]=D[d+(4*g+20)>>2],f[g+6]=D[d+(4*g+24)>>2],f[g+7]=D[d+(4*g+28)>>2],f[g+8]=D[d+(4*g+32)>>2],f[g+9]=D[d+(4*g+36)>>2],f[g+10]=D[d+(4*g+40)>>2],f[g+11]=D[d+(4*g+44)>>2],f[g+12]=D[d+(4*g+48)>>2],f[g+13]=D[d+(4*g+52)>>2],f[g+14]=D[d+(4*g+56)>>2],f[g+15]=D[d+(4*g+60)>>2]}else f=D.subarray(d>>2,d+64*b>>2);GLctx.uniformMatrix4fv(U[a],!!c,f)}},_glUseProgram:function(a){GLctx.useProgram(a?T[a]:null)},_glVertexAttribDivisorEXT:function(a,
b){GLctx.vertexAttribDivisor(a,b)},_glVertexAttribPointer:function(a,b,c,d,f,g){GLctx.vertexAttribPointer(a,b,c,!!d,f,g)},_glViewport:function(a,b,c,d){GLctx.viewport(a,b,c,d)},DYNAMICTOP_PTR:Aa,STACKTOP:xa};var mc=e.asm(e.F,e.G,buffer);e.asm=mc;var Na=e.__GLOBAL__sub_I_imgui_emsc_cc=function(){return e.asm.__GLOBAL__sub_I_imgui_emsc_cc.apply(null,arguments)};e._main=function(){return e.asm._main.apply(null,arguments)};
var la=e._malloc=function(){return e.asm._malloc.apply(null,arguments)},ra=e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)};e.dynCall_iiii=function(){return e.asm.dynCall_iiii.apply(null,arguments)};e.dynCall_v=function(){return e.asm.dynCall_v.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.dynCall_vi.apply(null,arguments)};e.asm=mc;function r(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}r.prototype=Error();
r.prototype.constructor=r;La=function nc(){e.calledRun||oc();e.calledRun||(La=nc)};e.callMain=function(a){a=a||[];Ia||(Ia=!0,G(Ea));var b=a.length+1,c=ra(4*(b+1));x[c>>2]=qa(e.thisProgram);for(var d=1;d<b;d++)x[(c>>2)+d]=qa(a[d-1]);x[(c>>2)+b]=0;try{var f=e._main(b,c,0);pc(f,!0)}catch(g){g instanceof r||("SimulateInfiniteLoop"==g?e.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),e.printErr("exception thrown: "+a),e.quit(1,g)))}finally{}};
function oc(a){function b(){if(!e.calledRun&&(e.calledRun=!0,!v)){Ia||(Ia=!0,G(Ea));G(Fa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();e._main&&qc&&e.callMain(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Ha.unshift(b)}G(Ha)}}a=a||e.arguments;if(!(0<H)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ja();G(Da);0<H||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);b()},1)):b())}}e.run=oc;function pc(a,b){if(!b||!e.noExitRuntime||0!==a){if(!e.noExitRuntime&&(v=!0,xa=void 0,G(Ga),e.onExit))e.onExit(a);q&&process.exit(a);e.quit(a,new r(a))}}e.exit=pc;function w(a){if(e.onAbort)e.onAbort(a);void 0!==a?(e.print(a),e.printErr(a),a=JSON.stringify(a)):a="";v=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=w;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var qc=!0;
e.noInitialRun&&(qc=!1);e.noExitRuntime=!0;oc();
