var f;f||(f=Module);var aa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function g(a,b){if(a){var c=l,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&aa)a=aa.decode(c.subarray(a,b));else{for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var k=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|k:(e&7)<<18|h<<12|k<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}a=d}}else a="";return a}
function q(a,b,c){var d=l;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);if(55296<=k&&57343>=k){var m=a.charCodeAt(++h);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(b>=c)break;d[b++]=k}else{if(2047>=k){if(b+1>=c)break;d[b++]=192|k>>6}else{if(65535>=k){if(b+2>=c)break;d[b++]=224|k>>12}else{if(b+3>=c)break;d[b++]=240|k>>18;d[b++]=128|k>>12&63}d[b++]=128|k>>6&63}d[b++]=128|k&63}}d[b]=0;return b-e}
var ba=new WebAssembly.Memory({initial:512,maximum:512}),t=ba.buffer,ca=new Int8Array(t),u=new Int16Array(t),v=new Int32Array(t),l=new Uint8Array(t),da=new Uint16Array(t),ea=new Uint32Array(t),w=new Float32Array(t),y=new Float64Array(t);v[2860]=5254576;var z=0,A=0,B=0,C=0,ha=0,ia=null,ja=null;
function D(a){try{if(!a)return window;"number"===typeof a&&(a=g(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?window.screen:"#canvas"===a?f.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}var ka=[];function la(){if(ma&&na.Wa)for(var a=0;a<ka.length;++a){var b=ka[a];ka.splice(a,1);--a;b.Ab.apply(this,b.ub)}}var ma=0,na=null,E=[];function oa(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}
function pa(a){var b=E[a];b.target.removeEventListener(b.Ua,b.ob,b.Xa);E.splice(a,1)}function F(a){function b(b){++ma;na=a;la();a.Za(b);la();--ma}if(a.Ya)a.ob=b,a.target.addEventListener(a.Ua,b,a.Xa),E.push(a);else for(var c=0;c<E.length;++c)E[c].target==a.target&&E[c].Ua==a.Ua&&pa(c--)}
function qa(a,b,c,d,e,h){z||(z=G(164));a={target:D(a),Wa:oa()?!1:!0,Ua:h,Ya:d,Za:function(a){a=a||window.event;var c=z;q(a.key?a.key:"",c+0,32);q(a.code?a.code:"",c+32,32);v[c+64>>2]=a.location;v[c+68>>2]=a.ctrlKey;v[c+72>>2]=a.shiftKey;v[c+76>>2]=a.altKey;v[c+80>>2]=a.metaKey;v[c+84>>2]=a.repeat;q(a.locale?a.locale:"",c+88,32);q(a.char?a.char:"",c+120,32);v[c+152>>2]=a.charCode;v[c+156>>2]=a.keyCode;v[c+160>>2]=a.which;H(d,e,c,b)&&a.preventDefault()},Xa:c};F(a)}
function ra(a,b,c){y[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();v[a+8>>2]=b.screenX;v[a+12>>2]=b.screenY;v[a+16>>2]=b.clientX;v[a+20>>2]=b.clientY;v[a+24>>2]=b.ctrlKey;v[a+28>>2]=b.shiftKey;v[a+32>>2]=b.altKey;v[a+36>>2]=b.metaKey;u[a+40>>1]=b.button;u[a+42>>1]=b.buttons;v[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-ia;v[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-ja;if(f.canvas){var d=f.canvas.getBoundingClientRect();
v[a+60>>2]=b.clientX-d.left;v[a+64>>2]=b.clientY-d.top}else v[a+60>>2]=0,v[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},v[a+52>>2]=b.clientX-d.left,v[a+56>>2]=b.clientY-d.top):(v[a+52>>2]=0,v[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(ia=b.screenX,ja=b.screenY)}
function I(a,b,c,d,e,h){A||(A=G(72));a=D(a);c={target:a,Wa:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Ua:h,Ya:d,Za:function(c){c=c||window.event;ra(A,c,a);H(d,e,A,b)&&c.preventDefault()},Xa:c};oa()&&"mousedown"==h&&(c.Wa=!1);F(c)}
function sa(a,b,c,d){C||(C=G(36));a=D(a);F({target:a,Wa:!1,Ua:"resize",Ya:d,Za:function(c){c=c||window.event;if(c.target==a){var e=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],k=C;v[k>>2]=c.detail;v[k+4>>2]=document.body.clientWidth;
v[k+8>>2]=document.body.clientHeight;v[k+12>>2]=window.innerWidth;v[k+16>>2]=window.innerHeight;v[k+20>>2]=window.outerWidth;v[k+24>>2]=window.outerHeight;v[k+28>>2]=e[0];v[k+32>>2]=e[1];H(d,10,k,b)&&c.preventDefault()}},Xa:c})}
function J(a,b,c,d,e,h){ha||(ha=G(1684));a=D(a);F({target:a,Wa:"touchstart"==h||"touchend"==h,Ua:h,Ya:d,Za:function(c){c=c||window.event;for(var h={},k=0;k<c.touches.length;++k){var n=c.touches[k];h[n.identifier]=n}for(k=0;k<c.changedTouches.length;++k)n=c.changedTouches[k],h[n.identifier]=n,n.nb=!0;for(k=0;k<c.targetTouches.length;++k)n=c.targetTouches[k],h[n.identifier].sb=!0;var p=n=ha;v[p+4>>2]=c.ctrlKey;v[p+8>>2]=c.shiftKey;v[p+12>>2]=c.altKey;v[p+16>>2]=c.metaKey;p+=20;var fa=f.canvas?f.canvas.getBoundingClientRect():
void 0,va=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},wa=0;for(k in h){var x=h[k];v[p>>2]=x.identifier;v[p+4>>2]=x.screenX;v[p+8>>2]=x.screenY;v[p+12>>2]=x.clientX;v[p+16>>2]=x.clientY;v[p+20>>2]=x.pageX;v[p+24>>2]=x.pageY;v[p+28>>2]=x.nb;v[p+32>>2]=x.sb;fa?(v[p+44>>2]=x.clientX-fa.left,v[p+48>>2]=x.clientY-fa.top):(v[p+44>>2]=0,v[p+48>>2]=0);v[p+36>>2]=x.clientX-va.left;v[p+40>>2]=x.clientY-va.top;p+=52;if(32<=++wa)break}v[n>>2]=wa;H(d,e,n,b)&&c.preventDefault()},Xa:c})}
function ta(a,b,c,d,e,h){a||(a=f.canvas);a={target:D(a),Wa:!1,Ua:h,Ya:d,Za:function(a){a=a||window.event;H(d,e,0,b)&&a.preventDefault()},Xa:c};F(a)}
function ua(a,b,c,d,e){function h(c){c=c||window.event;ra(B,c,a);y[B+72>>3]=c.wheelDeltaX||0;y[B+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);y[B+88>>3]=0;v[B+96>>2]=0;H(d,9,B,b)&&c.preventDefault()}function k(c){c=c||window.event;var e=B;ra(e,c,a);y[e+72>>3]=c.deltaX;y[e+80>>3]=c.deltaY;y[e+88>>3]=c.deltaZ;v[e+96>>2]=c.deltaMode;H(d,9,e,b)&&c.preventDefault()}B||(B=G(104));a=D(a);F({target:a,Wa:!0,Ua:e,Ya:d,Za:"wheel"==e?k:h,Xa:c})}
var xa=1,ya=0,K=[],L=[],za=[],Aa=[],M=[],N=[],O=[],P=[],Ba={},Q=null,R={},S={},Ca={};function T(a){ya||(ya=a)}function U(a){for(var b=xa++,c=a.length;c<b;c++)a[c]=null;return b}var Da=null,V=[0];function Ea(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=G(8),e={handle:d,attributes:b,version:b.lb,ib:a};e.Va=2<=e.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.tb=e);Ba[d]=e;("undefined"===typeof b.kb||b.kb)&&Fa(e);return d}
function Fa(a){a||(a=Q);if(!a.qb){a.qb=!0;var b=a.ib;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,e){c.drawArraysInstancedANGLE(a,b,d,e)},b.drawElementsInstanced=function(a,b,d,e,h){c.drawElementsInstancedANGLE(a,b,d,e,h)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var e=b.getExtension("WEBGL_draw_buffers");e&&(b.drawBuffers=function(a,b){e.drawBuffersWEBGL(a,b)})}b.wb=b.getExtension("EXT_disjoint_timer_query");var h="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=h.indexOf(a)&&b.getExtension(a)})}}var Ga={},Ha,Ia,Ja=["default","low-power","high-performance"],Ka=[];function La(a,b,c,d){for(var e=0;e<a;e++){var h=W[c](),k=h&&U(d);h?(h.name=k,d[k]=h):T(1282);v[b+4*e>>2]=k}}
function Ma(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=W.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Q.version){T(1282);return}c=2*W.getSupportedExtensions().length;break;case 33307:case 33308:if(2>Q.version){T(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=W.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=
0;break;default:T(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T(1280);console.error("GL_INVALID_ENUM in glGetIntegerv: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:T(1280);return}v[b>>2]=c}else T(1281)}
function X(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}b+=1;c=G(b);q(a,c,b);return c}var Na={6402:1,6403:1,6406:1,6407:3,6408:4,6409:1,6410:2,33319:2,33320:2,35904:3,35906:4,36244:1,36248:3,36249:4},Oa={5120:1,5121:1,5122:2,5123:2,5124:4,5125:4,5126:4,5131:2,32819:2,32820:2,33635:2,33640:4,34042:4,35899:4,35902:4,36193:2};
function Pa(a,b,c,d,e){if(b=Na[b]*Oa[a])switch(c=e+d*(c*b+4-1&-4),a){case 5120:return ca.subarray(e,c);case 5121:return l.subarray(e,c);case 5122:return u.subarray(e>>1,c>>1);case 5124:return v.subarray(e>>2,c>>2);case 5126:return w.subarray(e>>2,c>>2);case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return ea.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return da.subarray(e>>1,c>>1);default:T(1280)}else T(1280)}
function Qa(a){switch(a){case 5120:return ca;case 5121:return l;case 5122:return u;case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return da;case 5124:return v;case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return ea;case 5126:return w}}var Ra={5122:1,5123:1,5124:2,5125:2,5126:2,5131:1,32819:1,32820:1,33635:1,33640:2,34042:2,35899:2,35902:2,36193:1},W;Da=new Float32Array(256);for(var Y=0;256>Y;Y++)V[Y]=Da.subarray(0,Y+1);for(var Sa=0;32>Sa;Sa++)Ka.push(Array(Sa));
var Z={j:function(a){throw a;},S:function(){return window.devicePixelRatio},R:function(a,b,c){a=a?D(a):f.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),y[b>>3]=a.right-a.left,y[c>>3]=a.bottom-a.top):(y[b>>3]=a.clientWidth,y[c>>3]=a.clientHeight);return 0},Ea:function(){return 33554432},Ba:function(a,b,c){l.set(l.subarray(b,b+c),a)},ua:function(a,b){function c(d){Ta(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},F:function(a,b,c){"number"===typeof a&&
(a=g(a));a=a&&"#canvas"!==a?"undefined"!==typeof Ga&&R[a]?R[a]:D(a):"undefined"!==typeof Ga&&R.canvas?R.canvas:f.canvas;if(!a)return-4;a.width=b;a.height=c;return 0},la:function(a,b,c,d){qa(a,b,c,d,2,"keydown");return 0},fa:function(a,b,c,d){qa(a,b,c,d,1,"keypress");return 0},$:function(a,b,c,d){qa(a,b,c,d,3,"keyup");return 0},Ta:function(a,b,c,d){I(a,b,c,d,5,"mousedown");return 0},Sa:function(a,b,c,d){I(a,b,c,d,33,"mouseenter");return 0},Ra:function(a,b,c,d){I(a,b,c,d,34,"mouseleave");return 0},
Qa:function(a,b,c,d){I(a,b,c,d,8,"mousemove");return 0},Pa:function(a,b,c,d){I(a,b,c,d,6,"mouseup");return 0},Oa:function(a,b,c,d){sa(a,b,c,d);return 0},Na:function(a,b,c,d){J(a,b,c,d,25,"touchcancel");return 0},Ma:function(a,b,c,d){J(a,b,c,d,23,"touchend");return 0},La:function(a,b,c,d){J(a,b,c,d,24,"touchmove");return 0},Ka:function(a,b,c,d){J(a,b,c,d,22,"touchstart");return 0},Ja:function(a,b,c,d){ta(a,b,c,d,31,"webglcontextlost");return 0},Ia:function(a,b,c,d){ta(a,b,c,d,32,"webglcontextrestored");
return 0},Ha:function(a,b,c,d){a=D(a);return"undefined"!==typeof a.onwheel?(ua(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(ua(a,b,c,d,"mousewheel"),0):-1},Q:function(a,b){var c={};b>>=2;c.alpha=!!v[b];c.depth=!!v[b+1];c.stencil=!!v[b+2];c.antialias=!!v[b+3];c.premultipliedAlpha=!!v[b+4];c.preserveDrawingBuffer=!!v[b+5];c.powerPreference=Ja[v[b+6]];c.failIfMajorPerformanceCaveat=!!v[b+7];c.lb=v[b+8];c.xb=v[b+9];c.kb=v[b+10];c.pb=v[b+11];c.yb=v[b+12];c.zb=v[b+13];a=(a=g(a))&&"#canvas"!==
a||!f.canvas?R[a]?R[a].rb:D(a):f.canvas.id&&R[f.canvas.id]?R[f.canvas.id].rb||D(f.canvas.id):f.canvas;!a||c.pb?c=0:c=(a=1<c.lb?a.getContext("webgl2",c):a.getContext("webgl",c)||a.getContext("experimental-webgl",c))&&Ea(a,c);return c},Ga:function(a){a>>=2;for(var b=0;14>b;++b)v[a+b]=0;v[a]=v[a+1]=v[a+3]=v[a+4]=v[a+8]=v[a+10]=1},Fa:function(a){Q=Ba[a];f.vb=W=Q&&Q.ib;return!a||W?0:-5},t:function(a){W.activeTexture(a)},P:function(a,b){W.attachShader(L[a],O[b])},i:function(a,b){35051==a?W.jb=b:35052==
a&&(W.eb=b);W.bindBuffer(a,K[b])},f:function(a,b){W.bindFramebuffer(a,za[b])},s:function(a,b){W.bindTexture(a,M[b])},O:function(a){W.bindVertexArray(P[a])},N:function(a,b,c,d){W.blendColor(a,b,c,d)},M:function(a,b){W.blendEquationSeparate(a,b)},L:function(a,b,c,d){W.blendFuncSeparate(a,b,c,d)},m:function(a,b,c,d,e,h,k,m,r,n){W.blitFramebuffer(a,b,c,d,e,h,k,m,r,n)},K:function(a,b,c,d){Q.Va?c?W.bufferData(a,l,d,c,b):W.bufferData(a,b,d):W.bufferData(a,c?l.subarray(c,c+b):b,d)},J:function(a,b,c,d){Q.Va?
W.bufferSubData(a,b,l,d,c):W.bufferSubData(a,b,l.subarray(d,d+c))},Da:function(a){W.clear(a)},Ca:function(a,b,c,d){W.clearColor(a,b,c,d)},Aa:function(a){W.clearDepth(a)},za:function(a){W.clearStencil(a)},r:function(a,b,c,d){W.colorMask(!!a,!!b,!!c,!!d)},ya:function(a){W.compileShader(O[a])},xa:function(){var a=U(L),b=W.createProgram();b.name=a;L[a]=b;return a},wa:function(a){var b=U(O);O[b]=W.createShader(a);return b},I:function(a){W.cullFace(a)},va:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*
c>>2],e=K[d];e&&(W.deleteBuffer(e),e.name=0,K[d]=null,d==Ha&&(Ha=0),d==Ia&&(Ia=0),d==W.jb&&(W.jb=0),d==W.eb&&(W.eb=0))}},h:function(a,b){for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=za[d];e&&(W.deleteFramebuffer(e),e.name=0,za[d]=null)}},H:function(a){if(a){var b=L[a];b?(W.deleteProgram(b),b.name=0,L[a]=null,S[a]=null):T(1281)}},G:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Aa[d];e&&(W.deleteRenderbuffer(e),e.name=0,Aa[d]=null)}},q:function(a){if(a){var b=O[a];b?(W.deleteShader(b),O[a]=null):
T(1281)}},ta:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=M[d];e&&(W.deleteTexture(e),e.name=0,M[d]=null)}},sa:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2];W.deleteVertexArray(P[d]);P[d]=null}},p:function(a){W.depthFunc(a)},o:function(a){W.depthMask(!!a)},c:function(a){W.disable(a)},b:function(a){W.disableVertexAttribArray(a)},ra:function(a,b,c){W.drawArrays(a,b,c)},l:function(a,b){for(var c=Ka[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];W.drawBuffers(c)},qa:function(a,b,c,d){W.drawElements(a,
b,c,d)},e:function(a){W.enable(a)},pa:function(a){W.enableVertexAttribArray(a)},E:function(a){W.frontFace(a)},D:function(a,b){La(a,b,"createBuffer",K)},oa:function(a,b){La(a,b,"createTexture",M)},na:function(a,b){La(a,b,"createVertexArray",P)},C:function(a,b){return W.getAttribLocation(L[a],g(b))},B:function(a,b){Ma(a,b)},ma:function(a,b,c,d){a=W.getProgramInfoLog(L[a]);null===a&&(a="(unknown error)");0<b&&d?(b=q(a,d,b),c&&(v[c>>2]=b)):c&&(v[c>>2]=0)},A:function(a,b,c){if(c)if(a>=xa)T(1281);else{var d=
S[a];if(d)if(35716==b)a=W.getProgramInfoLog(L[a]),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b)v[c>>2]=d.fb;else if(35722==b){if(-1==d.$a){a=L[a];var e=W.getProgramParameter(a,35721);for(b=d.$a=0;b<e;++b)d.$a=Math.max(d.$a,W.getActiveAttrib(a,b).name.length+1)}v[c>>2]=d.$a}else if(35381==b){if(-1==d.ab)for(a=L[a],e=W.getProgramParameter(a,35382),b=d.ab=0;b<e;++b)d.ab=Math.max(d.ab,W.getActiveUniformBlockName(a,b).length+1);v[c>>2]=d.ab}else v[c>>2]=W.getProgramParameter(L[a],
b);else T(1282)}else T(1281)},ka:function(a,b,c,d){a=W.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");0<b&&d?(b=q(a,d,b),c&&(v[c>>2]=b)):c&&(v[c>>2]=0)},z:function(a,b,c){c?35716==b?(a=W.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1):35720==b?(a=W.getShaderSource(O[a]),v[c>>2]=null===a||0==a.length?0:a.length+1):v[c>>2]=W.getShaderParameter(O[a],b):T(1281)},ja:function(a){if(Ca[a])return Ca[a];switch(a){case 7939:var b=W.getSupportedExtensions();for(var c=[],d=
0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=X(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=W.getParameter(a))||T(1280);b=X(b);break;case 7938:b=W.getParameter(W.VERSION);b=2<=Q.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=X(b);break;case 35724:b=W.getParameter(W.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=X(b);break;default:return T(1280),
0}return Ca[a]=b},g:function(a,b){b=g(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=S[a]&&S[a].mb[b])&&0<=c&&c<a[0]?a[1]+c:-1},ia:function(a){W.linkProgram(L[a]);var b=L[a];a=S[a]={mb:{},fb:0,$a:-1,ab:-1};for(var c=a.mb,d=W.getProgramParameter(b,35718),e=0;e<d;++e){var h=W.getActiveUniform(b,e),k=h.name;a.fb=Math.max(a.fb,k.length+1);var m=k.lastIndexOf("[");0<m&&(k=k.slice(0,m));if(m=W.getUniformLocation(b,k)){var r=U(N);
c[k]=[h.size,r];N[r]=m;for(var n=1;n<h.size;++n)m=W.getUniformLocation(b,k+"["+n+"]"),r=U(N),N[r]=m}}},y:function(a,b){W.polygonOffset(a,b)},k:function(a){W.readBuffer(a)},ha:function(a,b,c,d){W.scissor(a,b,c,d)},ga:function(a,b,c,d){for(var e="",h=0;h<b;++h){var k=d?v[d+4*h>>2]:-1;e+=g(v[c+4*h>>2],0>k?void 0:k)}W.shaderSource(O[a],e)},ea:function(a,b,c){W.stencilFunc(a,b,c)},x:function(a,b,c,d){W.stencilFuncSeparate(a,b,c,d)},n:function(a){W.stencilMask(a)},da:function(a,b,c){W.stencilOp(a,b,c)},
w:function(a,b,c,d){W.stencilOpSeparate(a,b,c,d)},ca:function(a,b,c,d,e,h,k,m,r){Q.Va?W.eb?W.texImage2D(a,b,c,d,e,h,k,m,r):0!=r?W.texImage2D(a,b,c,d,e,h,k,m,Qa(m),r>>(Ra[m]|0)):W.texImage2D(a,b,c,d,e,h,k,m,null):W.texImage2D(a,b,c,d,e,h,k,m,r?Pa(m,k,d,e,r):null)},ba:function(a,b,c,d,e,h,k,m,r,n){W.eb?W.texImage3D(a,b,c,d,e,h,k,m,r,n):0!=n?W.texImage3D(a,b,c,d,e,h,k,m,r,Qa(r),n>>(Ra[r]|0)):W.texImage3D(a,b,c,d,e,h,k,m,r,null)},v:function(a,b,c){W.texParameterf(a,b,c)},d:function(a,b,c){W.texParameteri(a,
b,c)},aa:function(a,b,c){if(Q.Va)W.uniform1fv(N[a],w,c>>2,b);else{if(256>=b)for(var d=V[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);W.uniform1fv(N[a],d)}},u:function(a,b){W.uniform1i(N[a],b)},_:function(a,b,c){if(Q.Va)W.uniform2fv(N[a],w,c>>2,2*b);else{if(256>=2*b)for(var d=V[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);W.uniform2fv(N[a],d)}},Z:function(a,b,c){if(Q.Va)W.uniform3fv(N[a],w,c>>2,3*b);else{if(256>=3*b)for(var d=
V[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);W.uniform3fv(N[a],d)}},Y:function(a,b,c){if(Q.Va)W.uniform4fv(N[a],w,c>>2,4*b);else{if(256>=4*b)for(var d=V[4*b-1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);W.uniform4fv(N[a],d)}},X:function(a,b,c,d){if(Q.Va)W.uniformMatrix4fv(N[a],!!c,w,d>>2,16*b);else{if(256>=16*b)for(var e=V[16*b-1],
h=0;h<16*b;h+=16)e[h]=w[d+4*h>>2],e[h+1]=w[d+(4*h+4)>>2],e[h+2]=w[d+(4*h+8)>>2],e[h+3]=w[d+(4*h+12)>>2],e[h+4]=w[d+(4*h+16)>>2],e[h+5]=w[d+(4*h+20)>>2],e[h+6]=w[d+(4*h+24)>>2],e[h+7]=w[d+(4*h+28)>>2],e[h+8]=w[d+(4*h+32)>>2],e[h+9]=w[d+(4*h+36)>>2],e[h+10]=w[d+(4*h+40)>>2],e[h+11]=w[d+(4*h+44)>>2],e[h+12]=w[d+(4*h+48)>>2],e[h+13]=w[d+(4*h+52)>>2],e[h+14]=w[d+(4*h+56)>>2],e[h+15]=w[d+(4*h+60)>>2];else e=w.subarray(d>>2,d+64*b>>2);W.uniformMatrix4fv(N[a],!!c,e)}},W:function(a){W.useProgram(L[a])},V:function(a,
b){W.vertexAttribDivisor(a,b)},U:function(a,b,c,d,e,h){W.vertexAttribPointer(a,b,c,!!d,e,h)},T:function(a,b,c,d){W.viewport(a,b,c,d)},a:11440};Z.memory=ba;Z.table=new WebAssembly.Table({initial:16,maximum:16,element:"anyfunc"});Z.__memory_base=1024;Z.__table_base=0;var Ua,G,Ta,H;
WebAssembly.instantiate(f.wasm,{env:Z,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:{"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}}}).then(function(a){a=a.instance.exports;Ua=a.bb;G=a.cb;Ta=a.gb;H=a.hb;Ua()});
